<div class="row">
    <div class="col s12">
        <div id="breadcrumb">
            <ul>
                <li class="first"><a
                        href="<?php echo $this->url(array('controller' => 'principal', 'action' => 'index'), '', true); ?>"
                        title="Ir para In&iacute;cio">In&iacute;cio</a></li>
                <li class="last">Manter Agentes</li>
            </ul>
        </div>
        <div id="titulo">
            <div>Cadastrar usu&aacute;rio para o proponente
                <span class="voltar">
                    <a href="javascript:voltar();">Voltar</a>
                </span>
            </div>
        </div>
        <div id="conteudo">
            <div id="confirma"></div>
            <div>
                <?php echo $this->partial('agentes/inc/cabecalho.php', $this) ?>
            </div>
            <?php if (empty($this->dados[0]->idResponsavel)) : ?>
                <div id="formNovo">
                    <form id="formInfoAdicionais"
                          action="<?php echo $this->url(array('module' => 'agente', 'controller' => 'agentes', 'action' => 'salvar-usuario-agente')); ?>"
                          method="post">
                        <table class="tabela">
                            <caption class="red-text">Agente sem respons&aacute;vel cadastrado</caption>
                            <input type="hidden" name="agente" id="agente"
                                   value="<?php echo $this->dados[0]->idAgente; ?>"/>
                            <th colspan="2">Cadastrar Respons&aacute;vel pelo Proponente</th>
                            <tr>
                                <td class="destacar bold" align="right" width="150px" nowrap>Usu&aacute;rio <span
                                        style="color: red;">*</span></td>
                                <td>
                                    <select name="idResponsavel" id="idResponsavel" class="select_simples obrigatorio">
                                        <?php foreach ($this->responsaveis as $responsavel) : ?>
                                            <?php if ($responsavel['idResponsavel']) : ?>
                                                <option
                                                    value="<?= $responsavel['idResponsavel']; ?>">
                                                    [<?= $responsavel['cpfResponsavel']; ?>]
                                                    <?= $responsavel['nomeResponsavel']; ?>
                                                </option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div style="width: 100%; " align="center">
                                        <button type="submit" class="btn btn-primary" id="btnsalvar">Salvar</button>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            <?php else: ?>
                <div class="padding20 center-align">
                    <b>Proponente j&aacute; possui respons&aacute;vel cadastrado</b>
                </div>

                <table class="tabela">
                    <tr>
                        <td class="destacar bold" align="right" width="150px" nowrap>CPF</td>
                        <td>
                            <?= $this->dados[0]->cpfResponsavel; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="destacar bold" align="right" width="150px" nowrap>Usu&aacute;rio</td>
                        <td>
                            <?= $this->dados[0]->nomeResponsavel; ?>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
        </div>
    </div>
</div>
