<?php require_once "inc/menu.inc.php"; ?>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.material.min.css"/>
<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => 'index'),'',true);?>" title="Ir para Início">Início</a></li>
        <li class="last">Pareceristas</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Pareceristas Ativos</div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<div id="conteudo">
    <?php echo $this->qtd?>
        <table class="tabela " id="pareceristas">
            <thead>
            <tr class="titulo_tabela">
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados as $dado): ?>
                <tr>
                    <td><?php echo $dado->Nome; ?></td>
                    <td><?php echo Mascara::addMaskCPF($dado->CNPJCPF); ?></td>

                    <?php if(($this->grupoativo == "93")){ ?>
                        <td align="center"><input type="button" value=" " class="btn_ver" style="width: 88px;" onclick="redirecionar('<?php echo $this->url(array('module'=>'agente', 'controller' => 'agentes', 'action' => 'agentes','id' =>$p->idParecerista),'',true);?>')" /></td>
                    <?php } else { ?>
                        <td align="center"><input type="button" value=" " class="btn_editar" onclick="redirecionar('<?php echo $this->url(array('module'=>'agente', 'controller' => 'agentes', 'action' => 'agentes','id' =>$p->idParecerista),'',true);?>')" /></td>
                    <?php } ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

</div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />


<script
    src="https://code.jquery.com/jquery-1.12.4.js"
    integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
    crossorigin="anonymous"></script>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.material.min.js"></script>

<script type="text/javascript">
        
    (function($){

        $(document).ready (function(){
            $('#pareceristas').DataTable(
                {
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                    }
                    , "order": [0,1]
                    , "searching": true
                    , "lengthChange": true
                    ,  columnDefs: [
                    {
                        targets: [],
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ]
                    ,
                    "aoColumnDefs": [
                        { 'bSortable': false, 'aTargets': [ 2 ] }
                    ]
                });
        });
    }($.noConflict(true)));

</script>