<?php 
/**
 * PROPOSTA PEDAGÓGICA: Solicitação de alteração na Proposta Pedagógica do Projeto
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 30/03/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

require_once "inc/menu.inc.php"; // menu
// define os valores dos campos do formulário, se será lido o dado original ou o dado readequado
$especificacaoTecAP = !empty($this->dadosAP['EspecificacaoTecnica'])  ? strip_tags($this->dadosAP['EspecificacaoTecnica'])  : 'Não Aplicável';
$estrategiaExecAP  = !empty($this->dadosAP['EstrategiadeExecucao'])  ? strip_tags($this->dadosAP['EstrategiadeExecucao'])   : 'Não Aplicável';
$especificacaoTecSR = isset($this->dadosSR['dsEspecificacaoTecnica']) ? $this->dadosSR['dsEspecificacaoTecnica']            : '';
$estrategiaExecSR = isset($this->dadosSR['dsEstrategiaExecucao']) ? $this->dadosSR['dsEstrategiaExecucao']                  : '';
$Justificativa   = isset($this->pedido['dsJustificativa'])         ? $this->pedido['dsJustificativa']                       : '';

$urlPronac = null;
$urlPronac = (isset($this->idPronac)) ? "?idPronac=".Seguranca::encrypt($this->idPronac) : "";
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => ''), null, true); ?><?php echo $urlPronac; ?>" title="Ir para In&iacute;cio" onclick="carregandoModal();">Consultar dados do Projeto</a></li>
        <li>Readequa&ccedil;&atilde;o de projeto</li>
        <li class="last">Proposta pedag&oacute;gica</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Readequa&ccedil;&atilde;o de projeto - Proposta pedag&oacute;gica <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <!-- ========== INÍCIO TOPO PROJETO ========== -->
    <?php require_once "inc/topo.inc.php"; ?>
    <!-- ========== FIM TOPO PROJETO ========== -->

    <!-- ========== INÍCIO FORMULÁRIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'proposta-pedagogica')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="stPedidoAlteracao" id="stPedidoAlteracao" value="T" />
        <input type="hidden" name="siVerificacao" id="siVerificacao" value="0" />
        <input type="hidden" name="tpAlteracaoProjeto" id="tpAlteracaoProjeto" value="6" />
        <table class="tabela">
            <tr>
                <th>Especifica&ccedil;&otilde;es T&eacute;cnicas</th>
            </tr>
        </table>
        <table class="tabela">
            <tr class="destacar bold">
                <td align="center"><label for="especificacaoAprovada">ESPECIFICA&Ccedil;&Atilde;O T&Eacute;CNICA APROVADA</label></td>
            </tr>
            <tr>
                <td align="center">
                    - Especifica&ccedil;&otilde;es t&eacute;cnicas: propostas de edi&ccedil;&atilde;o de livro, revistas e peri&oacute;dicos<br />
                    - Projeto Pedag&oacute;gico/plano de execu&ccedil;&atilde;o: propostas de cursos/workshops *
                </td>
            </tr>
            <tr>
                <td><textarea name="especificacaoTecAprovada" id="especificacaoTecAprovada" cols="" rows="7" class="textarea_simples w99p" readonly="readonly"><?php echo $especificacaoTecAP; ?></textarea></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="informacoesAprovada">ESTRAT&Eacute;GIA DE EXECU&Ccedil;&Atilde;O APROVADA</label></td>
            </tr>
            <tr>
                <td align="center">
                    - Proposta museogr&aacute;fica: propostas de exposi&ccedil;&atilde;o tempor&aacute;ria ou acervo<br />
                    - Destina&ccedil;&atilde;o do bem patrimonial adquirido, ap&oacute;s o t&eacute;rmino do projeto: propostas com aquisi&ccedil;&atilde;o de material permanente<br />
                    - Listas dos bens hist&oacute;ricos: propostas de invent&aacute;rios e organiza&ccedil;&atilde;o de acervos
                </td>
            </tr>
            <tr>
                <td><textarea name="estrategiaExecAprovada" id="estrategiaExecAprovada" cols="" rows="7" class="textarea_simples w99p" readonly="readonly"><?php echo $estrategiaExecAP; ?></textarea></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="especificacaoSolicitada">NOVA ESPECIFICA&Ccedil;&Atilde;O T&Eacute;CNICA</label></td>
            </tr>
            <tr>
                <td><textarea name="especificacaoSolicitada" id="especificacaoSolicitada" cols="" rows="7" class="textarea_simples w99p"><?php echo $especificacaoTecSR; ?></textarea></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="informacoesSolicitada">NOVA ESTRAT&Eacute;GIA DE EXECU&Ccedil;&Atilde;O</label></td>
            </tr>
            <tr>
                <td><textarea name="estrategiaExecSolicitada" id="estrategiaExecSolicitada" cols="" rows="7" class="textarea_simples w99p"><?php echo $estrategiaExecSR; ?></textarea></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="justificativa">JUSTIFICATIVA</label></td>
            </tr>
            <tr>
                <td>
                    <textarea name="justificativa" id="justificativa" cols="" rows="7" class="textarea_simples w99p"><?php echo $Justificativa; ?></textarea>
                    <span style="float: left; color: red;">Limite máximo de 600 caracteres</span>
                </td>
            </tr>
        </table>
        <table class="tabela btnsModReadequacao">
            <tr>
                <td align="center">
                    <input type="submit" name="btn_salvar" id="btn_salvar" class="btn_salvar" value=" " title="Salvar" />
                    <input type="reset" name="btn_cancelar" id="btn_cancelar" class="btn_cancelar" value=" " title="Cancelar" />
                </td>
            </tr>
        </table>
    </form>
    <!-- ========== FIM FORMULÁRIO ========== -->

    <!-- ========== INÍCIO HISTÓRICO ========== -->
    <div id="historico"></div>
    <script type="text/javascript">
        carregaDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-proposta-pedagogica')); ?>', 'historico');
    </script>
    <!-- ========== FIM HISTÓRICO ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />