<style type="text/css">
    label.error{color:red;}
</style>
<script type="text/javascript">

    $(document).ready( function() {
        $("#cadastrarusuarioexterno").validate({
            // Define as regras
            rules:{
                cpf:{

                    required: true,
                    minlength: 14,
                    verificaCPF: true
                },
                nome:{

                    required: true, minlength: 2
                },
                nomeusuario:{

                    required: true,  minlength: 2
                },
                unidade: "required"

            },
            // Define as mensagens de erro para cada regra
            messages:{
                cpf:{
                    required: "Informe cpf",
                    minlength: "O seu nome deve conter, no mínimo, 11 caracteres",
                    verificaCPF: "Informe CPF v&aacute;lido"
                },
                nome:{
                    required: "Informe nome",
                    minlength: "O seu nome deve conter, no mínimo, 2 caracteres"
                },
                nomeusuario:{
                    required: "Informe usuário"
                },
                unidade: '<br>Selecione unidade'
            }
        });
    });

    function replaceAll(string, token, newtoken) {
        while (string.indexOf(token) != -1) {
            string = string.replace(token, newtoken);
        }
        return string;
    }
</script>

<!-- ========== INï¿½CIO BREADCRUMB (LINKS TOPO) ========== -->
<div style="display:none" id="confirm">Por favor, informe seu email!</div>
<div style="display:none" id="dialog-alert2"></div>
<div style="display:none" id="confirmInforma">Por favor, digite seu email corretamente!</div>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">In&iacute;cio</a></li>
        <li class="last">Cadastrar Usuário Externo</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INï¿½CIO Tï¿½TULO ========== -->
<div id="titulo">
    <div>Cadastrar Usuário Externo<span></span> <span class="voltar"><a href="javascript:voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM Tï¿½TULO ========== -->


<!-- ========== INï¿½CIO CONTEï¿½DO ========== -->
<div id="conteudo" align="center">
    <fieldset><legend>Informações</legend>
        <form method="POST" action="<?php echo $this->url(array('controller' => 'manterusuario', 'action' => 'cadastrarusuarioexterno')); ?>" name="cadastrarusuarioexterno" id="cadastrarusuarioexterno">
            <table class="tabela">
                <thead>
                    <tr>
                        <th colspan="2">Cadastrar Usuário Externo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>CPF </td>
                        <td><input value=""  onkeydown="mascaraCnpjCpf(this);" onkeypress="mascaraCnpjCpf(this);" onkeyup="mascaraCnpjCpf(this);" maxlength="14" class="input_simples" type="text" name="cpf" id="cpf"  /><div id="cpfRetorno" ></div> </td>
                    </tr>
                    <tr>
                        <td>Nome Completo </td>
                        <td><input type="text" name="nome" id="nome" class="input_simples w400"/></td>
                    <tr>
                        <td>Nome de Usuário </td>
                        <td><input type="text" name="nomeusuario" id="nomeusuario" class="input_simples w400"/></td>
                    </tr>
                    <tr>
                        <td>Unidade</td>
                        <td>
                            <select id="unidade" name="unidade" class="select_simples">
                                <option value="">Selecione a unidade</option>
                                <?php foreach ($this->orgaosExternos as $orgaosExternos) { ?>
                                <option value="<?php echo $orgaosExternos['org_codigo']?>"><?php echo $orgaosExternos['orgao_nome'] ?></option>
                                <?php } ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2">
                            <input id='btIncluir' type='submit' value='' class='btn_salvar enviar'/>
                            <input id='btLimpar' type='reset' value='' class='btn_limpar enviar'  />
                            <input id='btCancelar' type='button' value='' class='btn_cancelar enviar' onClick="history.go(-1)" onkeypress=" " />
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </fieldset>
</div>
<!-- ========== FIM CONTEï¿½DO ========== -->


<!-- ========== INï¿½CIO RODAPï¿½ DO CONTEï¿½DO ========== -->
<div id="rodapeConteudo"><span></span></div>

<!-- ========== FIM RODAPï¿½ DO CONTEï¿½DO ========== -->
<br clear="all" />




</body>
</html>