<main>
    <?php
    $links = array(
        array('Desist&#234ncia Recursal' => array())
    );
    gerarBreadCrumb($links);
    ?>
    <div class="content-fluid">
        <div class="row">
            <div class="col s12">
                <table class="bordered responsive-table" id="desistencia">
                    <thead>
                    <tr class="titulo_tabela">
                        <th width="14%" >PRONAC</th>
                        <th>Nome do Projeto</th>
                        <th align="center">A&ccedil;&atilde;o</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->recursos as $recurso): ?>
                        <tr>
                            <td class="center-align">
                                <a class="black-text btn white tooltipped" data-tooltip="Visualizar Projeto" href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($recurso->IdPRONAC); ?>">
                                <?php echo $recurso->IdPRONAC?>
                                    <i class="material-icons left hide-on-med-and-down">visibility</i>
                                </a>
                            </td>
                            <td><?php echo $recurso->NomeProjeto?></td>
                            <td class="center-align">
                                <a class="btn waves-effect waves-light tooltipped small" data-tooltip="Visualizar Projeto" href="<?php echo $this->url(array('module'=>'admissibilidade', 'controller' => 'enquadramento', 'action' => 'finalizar-desistencia-recursal'));?>?idPronac=<?php echo $recurso->IdPRONAC ?>&idRecurso=<?php echo $recurso->idRecurso ?>"
                                data-position="top" data-delay="50" data-tooltip="Finalizar">
                                    <i class="material-icons left hide-on-med-and-down">&#xE8E4;</i>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br clear="all"/>
    <script
        src="https://code.jquery.com/jquery-1.12.4.js"
        integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
    <script
    type = "text/javascript"
    src = "https://cdn.datatables.net/1.10.13/js/dataTables.material.min.js" ></script>

    <script
    type = "text/javascript" >
        (function ($) {

            $(document).ready(function () {
                $('#desistencia').DataTable(
                    {
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                        }
                        , "order": [0, 1]
                        , "searching": true
                        , "lengthChange": true
                        , columnDefs: [
                        {
                            targets: [0, 1],
                            className: 'mdl-data-table__cell--non-numeric'
                        }
                    ]
                        ,
                        "aoColumnDefs": [
                            {'bSortable': false, 'aTargets': [4]}
                        ]
                    });
            });
        }($.noConflict(true)));
    </script>
