<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.material.min.css"/>
<main>
    <nav class="breadcrumb">
        <div class="nav-wrapper" style="padding: 0 15px 0 15px">
            <div class="col s12">
                <a href="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'gerenciarparecer', 'action' => 'index'), null, true); ?>"
                   class="breadcrumb tooltipped"
                   data-position="top"
                   data-delay="50"
                   data-tooltip="Ir para In&iacute;cio">In&iacute;cio</a>

                <a href="#"
                   class="breadcrumb tooltipped"
                   data-position="top"
                   data-delay="50"
                   data-tooltip="Localizar Parecer">Encaminhar para Portaria</a>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="row">
            <div class="col s12">
                <h4>Gerenciar Enquadramentos</h4>
                <table class="bordered responsive-table" id="enquadramento">
                    <thead>
                    <tr class="titulo_tabela">
                        <th width="40">PRONAC</th>
                        <th>Nome do Projeto</th>
                        <th>&Aacute;rea</th>
                        <th>Segmento</th>
                        <th>Dias</th>
                        <th align="center">Encaminhar</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->dados as $dado): ?>
                        <?php if ($dado->Situacao == "B03") : ?>
                        <tr class="red lighten-4">
                        <?php else: ?>
                        <tr>
                        <?php endif; ?>
                            <td>
                                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index')) . "?idPronac={$dado->IdPRONAC}"; ?>"><u><?php echo $dado->pronac; ?></u></a>
                            </td>
                            <td><?php echo $dado->nomeProjeto; ?></td>
                            <td><?php echo $dado->area; ?></td>
                            <td><?php echo $dado->segmento; ?></td>
                            <td>@todo : Carregar</td>
                            <td>
                                <a class="btn waves-effect waves-light cyan tooltipped"
                                   href="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'enquadramento', 'action' => 'encaminhar-portaria')) . "?IdPRONAC={$dado->idpronac}&encaminhar=true" ?>"
                                   data-position="top"
                                   data-delay="50"
                                   data-tooltip="Encaminhar">
                                    <i class="material-icons white-text">navigate_next</i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="col s12 m6 l4">
                    <label>Legenda:</label>
                    <br />
                    <div class="red lighten-4" style="border: 1px solid gray; height: 20px; display: inline">&nbsp;&nbsp;&nbsp;&nbsp;</div>
                    Projeto Enquadrado Com Recurso
                    <br clear="both" />
                    <div class="" style="border: 1px solid gray; height: 20px; display: inline">&nbsp;&nbsp;&nbsp;&nbsp;</div>
                    Projeto Enquadrado
                </div>
            </div>
        </div>
    </div>
    <br clear="all"/>
    <script
        src="https://code.jquery.com/jquery-1.12.4.js"
        integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script></script>
    <script
    type = "text/javascript"
    src = "https://cdn.datatables.net/1.10.13/js/dataTables.material.min.js" ></script></script>

    <script
    type = "text/javascript" >
        (function ($) {

            $(document).ready(function () {
                $('#enquadramento').DataTable(
                    {
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                        }
                        , "order": [0, 1]
                        , "searching": true
                        , "lengthChange": true
                        , columnDefs: [
                        {
                            targets: [0, 1],
                            className: 'mdl-data-table__cell--non-numeric'
                        }
                    ]
                        ,
                        "aoColumnDefs": [
                            {'bSortable': false, 'aTargets': [4]}
                        ]
                    });
            });
        }($.noConflict(true)));
    </script>

</main>