<style>
    p {
        font-size:150%;
    }
</style>
<div class="modal-content">
    <div>
        <div align="center">
           <p>
                Realmente concorda com os termos anteriores e deseja desistir do prazo recursal?
           </p>
            <p>
                As ações efetuadas não podem ser alteradas.
            </p>
        </div>
    </div>
</div>
<div class="modal-footer">
    <a id="btn-enviar" style="margin-left: 15px;"
       href="<?php echo $this->Url(array('module' => 'default', 'controller' => 'solicitarrecursodecisao', 'action' => 'recurso-desistencia-enquadramento-salvar'));?>?idPronac=<?php echo $this->idPronac;?>"
       class="modal-action waves-effect waves-green btn-flat light-green">Concordo</a>
    <a href="<?php echo $this->Url(array('module'=> 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo $this->idPronac?>" class="modal-action modal-close waves-effect waves-orange btn-flat">Não Concordo</a>
</div>