<?php
/**
 * Solicitar Recurso da Decisão: Busca os Projetos
 * @author Equipe RUP - Politec
 * @since 21/07/2010
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.solicitarrecursodedecisao
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
	<div id="breadcrumb">
		<ul>
			<li class="last">Solicitar Recurso da Decisão </li>
		</ul>
	</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Projeto Indeferido <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">






	<!-- ========== INÍCIO FORMULÁRIO ========== -->
	<form name="form" id="form" action="<?php echo $this->url(array('controller' => 'solicitarrecursodecisao', 'action' => 'projetoindeferido')); ?>?idPronac=<?php echo $_GET['idPronac']; ?>" method="post">
	<?php foreach($this->projetos as $p): ?>
	<input type="hidden" name="idPronac" id="idPronac" value="<?php echo $this->escape($p->IdPRONAC);?>" />
	<input type="hidden" name="pronac" id="pronac" value="<?php echo $this->escape($p->pronac);?>" />
	<input type="hidden" name="idAgente" id="idAgente" value="<?php echo $this->escape($p->idAgente);?>" />
	<table class="tabela">
		<tr>
			<th>Pronac</th>
			<th>Nome do Projeto</th>
		</tr>
		<tr>
			<td><?php echo $this->escape($p->pronac);?></td>
			<td><?php echo $this->escape($p->NomeProjeto);?></td>
		</tr>
		<tr>
			<th>CNPJ/CPF:</th>
			<th>Proponente</th>
		</tr>
		<tr>
			<td><?php echo Validacao::mascaraCPFCNPJ($this->escape($p->CNPJCPF));?></td>
			<td><?php echo $this->escape($p->NomeProponente);?></td>
		</tr>
		<tr>
			<td colspan="2"><?php echo $this->escape($p->StatusProjeto);?></td>
		</tr>

		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<th colspan="2">Recurso</th>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2">
				<!-- ========== EDITOR ========== -->
				<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/ckeditor.js"></script>
				<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.js"></script>
				<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.css" />

				<textarea cols="80" id="dsRecurso" name="dsRecurso" rows="10">&lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;p&gt;Digite seu texto aqui...&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</textarea>
				<script type="text/javascript">
				//<![CDATA[
					CKEDITOR.replace('dsRecurso', { fullPage : true });
				//]]>
				</script>
			</td>
		</tr>
	</table>
	<?php endforeach;?>



	<!-- ========== BOTÕES ========== -->
	<table class="tabela">
		<tr>
			<td  colspan="2" align="right">
				
				<input type="submit" id="bt_enviar" title=" Enviar " class="btn_enviar" value=" " />&nbsp;&nbsp;&nbsp;
				<input type="button" id="bt_cancelar" title=" Cancelar " class="btn_cancelar" value=" " />
				
			</td>
		</tr>
	</table>
	</form>
	<!-- ========== FIM FORMULÁRIO ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />