<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/materialize.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/materialize-custom.css">

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="msgAlerta"></div>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para Inï¿½cio">Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'), '', true); ?>?idPronac=<?php echo Seguranca::encrypt($this->escape($this->idPronac)); ?>" title="Consultar dados projeto">Consultar dados projeto</a></li>
        <li class="last">Solicitar Recurso da Decis&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>
        Solicitar Recurso <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span>
    </div>
</div>
<div id="conteudo">
    <div class="row">
    <div class="col s12">
    <?php if ($this->projeto): ?>
        <table class="bordered">
            <thead>
                <th class="">Pronac</th>
                <th class="">Nome do Projeto</th>
            </thead>
            <tbody>
                <tr>
                    <td><?php echo $this->projeto->pronac;?></td>
                    <td><?php echo $this->projeto->NomeProjeto;?></td>
                </tr>
            </tbody>
        </table>
        <table>
            <thead>
                <th>Estado do Projeto</th>
                <th>Tipo da Solicitação</th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <?php echo $this->projeto->situacao ?>
                    </td>
                    <td >
                        <?php if($this->recurso):  ?>
                            Recurso
                        <?php else :  ?>
                            Pedido de Reconsideração
                        <?php endif ?>
                    </td>
                </tr>
                <?php if($this->recurso): ?>
                    <tr>
                        <th colspan="2">Recurso anterior:</th>
                    </tr>
                    <tr>
                        <td colspan="2">
                                <?php echo $this->recurso->dsSolicitacaoRecurso  ?>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        </table>
        <form name="form" id="form"
                action="<?php echo $this->url(array('controller' => 'solicitarrecursodecisao', 'action' => 'recurso-enquadramento-salvar')); ?>?idPronac=<?php echo $this->projeto->IdPRONAC; ?>"
                method="post">
            <input type="hidden" name="idPronac" id="idPronac" value="<?php echo $this->projeto->IdPRONAC;?>" />
            <input type="hidden" name="tpSolicitacao" id="ER" value="ER" />
            <?php if($this->recurso):  ?>
                <input type="hidden" name="tpRecurso" value="2" />
            <?php else :  ?>
                <input type="hidden" name="tpRecurso" value="1" />
            <?php endif ?>
            <div class="input-field col s12">
                <label for="dsRecurso1">Recurso:</label>
            </div>
            <div class="input-field col s12">
                <textarea placeholder="Escreva o seu recurso..." class="materialize-textarea"  id="dsRecurso" name="dsRecurso" rows="10"></textarea>
            </div>
            <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
                <i class="material-icons right">send</i>
            </button>
            <button class="btn waves-effect waves-light red" type="reset" name="action">Cancelar
            </button>
        </form>
        <br clear="all" />
    <?php else: ?>
        <table class="tabela">
            <tr>
                <td class="centro">Nenhum registro encontrado.</td>
            </tr>
        </table>
    <?php endif ?>
</div>
</div>
</div>
<div id="rodapeConteudo"><span></span></div>
