<style type="text/css">
    label {
        font-weight: normal;
        margin-right: 15px;
    }

    .checkObrigatorio {
        margin-right: 5px;
    }
</style>

<?php

$breadcrumb = [
    ['Consultar dados projeto' => $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'), '', true) . '?idPronac=' . Seguranca::encrypt($this->escape($this->idPronac))],
    ['Solicitar Recurso da Decis&atilde;o' => '']
];

?>
<div class="container-fluid">
    <?php $this->PageTitle('Solicitar Recurso', $breadcrumb); ?>
    <div id="msgAlerta"></div>
    <div id="conteudo">
        <?php
        if ($this->projeto) : ?>
            <form
                name="formEnviarRecurso"
                id="formEnviarRecurso"
                action="<?php echo $this->url(array('module' => 'default', 'controller' => 'solicitarrecursodecisao', 'action' => 'enviar-recurso')); ?>"
                method="post">
                <input type="hidden" name="idPronac" id="idPronac"
                       value="<?php echo $this->escape($this->projeto['idPronac']); ?>"/>
                <table class="tabela">
                    <tr>
                        <td class="destacar bold">Pronac</td>
                        <td class="destacar bold" colspan="3">Nome do Projeto</td>
                    </tr>
                    <tr>
                        <td><?= $this->escape($this->projeto['pronac']); ?></td>
                        <td colspan="3"><?= $this->escape($this->projeto['nomeProjeto']); ?></td>
                    </tr>
                    <tr>
                        <td class="destacar bold">Tipo da Solicita&ccedil;&atilde;o</td>
                        <td class="destacar bold">Tipo do Recurso</td>
                        <td class="destacar bold">Prazo recurso</td>
                        <td class="destacar bold">Situa&ccedil;&atilde;o</td>
                    </tr>
                    <tr>
                        <td>
                            <?= (empty($this->projeto['tpRecurso']) || $this->projeto['tpRecurso']  == 1)
                                ? 'Pedido de reconsidera&ccedil;&atilde;o'
                                : 'Recurso';
                            ?>
                        </td>
                        <td>
                            <?= $this->projeto['tpSolicitacao'] == 'PI' ? 'Projeto Indeferido' : 'Or&ccedil;amento'; ?>
                        </td>
                        <td>
                            <?= $this->projeto['prazoRecurso']; ?> dias
                        </td>
                        <td>
                            <?= $this->projeto['situacao']; ?> - <?= $this->projeto['descricaoSituacao']; ?>
                        </td>
                    </tr>
                </table>

                <table class="tabela">
                    <tr>
                        <th>Recurso</th>
                    </tr>
                    <tr>
                        <td>
                            <textarea class="textarea_simples dsSolicitacaoRecurso" cols="80" id="dsSolicitacaoRecurso" name="dsSolicitacaoRecurso"
                                      rows="10"></textarea>
                        </td>
                    </tr>
                </table>

                <div style="width: 100%; text-align: center;">
                    <button id="bt_enviar"
                            data-tooltip="Enviar recurso"
                            class="waves-effect waves-dark white-text tooltipped btn btn-primary"
                            type="submit"
                            name="action">
                        Enviar <i class="material-icons right">send</i>
                    </button>

                    <a id="bt_cancelar" class="waves-effect waves-dark white-text tooltipped btn btn-info"
                       data-tooltip="Cancelar envio de recurso" href="javascript:void(0)">
                        <i class="material-icons left">close</i>Cancelar
                    </a>
                </div>
            </form>
        <?php else : ?>
            <table class="tabela">
                <tr>
                    <td class="centro">Nenhum registro encontrado.</td>
                </tr>
            </table>
        <?php endif; ?>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {

        var editorRico = $("#dsSolicitacaoRecurso").editorRico({
            altura: 200,
            isLimitarCarateres: true
        });

        $("#formEnviarRecurso").validate({
            rules: {
                dsSolicitacaoRecurso: {
                    validarPreenchimento: true,
                    validarPreenchimentoMaximo: true
                }
            },
            messages: {
                dsSolicitacaoRecurso: {
                    validarPreenchimento: "Texto do Recurso &eacute; obrigat&oacute;rio",
                    validarPreenchimentoMaximo: "Limite excedido"
                }
            },
            submitHandler: function (form) {
                $("#container-loading").show();
                $("#bt_enviar").addClass("disabled");
                form.submit();
            },
            invalidHandler: function (event, validator) {
                Materialize.toast(validator.submitted.dsSolicitacaoRecurso, 4000);
            }
        });

        $.validator.addMethod("validarPreenchimento", function (value, element) {
            if (editorRico.contarCaracteres() > 0) {
                return true;
            }
        });
        $.validator.addMethod("validarPreenchimentoMaximo", function (value, element) {
            if (editorRico.contarCaracteres() <= 30000) {
                return true;
            }
        });

    });
</script>
