<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>var $jq3 = jQuery.noConflict();</script>
<script src="<?php echo $this->baseUrl(); ?>/public/js/materialize.js"></script>
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/materialize.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/materialize-custom.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/animate.css">
<nav class="breadcrumb">
    <div class="nav-wrapper" style="padding: 0 15px 0 15px">
        <div class="col s12">
            <a href="<?php echo $this->Url(array('module' => 'default', 'controller' => 'principalproponente', 'action' => 'index'))?>" class="breadcrumb tooltipped" data-position="top" data-delay="50" data-tooltip="Ir para o início">Início</a>
            <a href="<?php echo $this->Url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'))?>?idPronac=<?php echo $this->projetos->IdPRONAC?>" class="breadcrumb tooltipped" data-position="top" data-delay="50" data-tooltip="Ir para consultar dados projeto">Consultar dados projeto</a>
            <a href="#" class="breadcrumb tooltipped" data-position="top" data-delay="50" data-tooltip="Página Atual">Desistência do Prazo Recursal</a>
        </div>
    </div>
</nav>

<style type="text/css">
    label{
        font-weight: normal;
        margin-right: 15px;
    }

    nav .nav-wrapper {
    background-color: #1b5e20;
    bottom: 19px;
    color: #fefefe;
    height: 56px;
    line-height: 56px;
    width: 100%;

    }
    
    div .termo {
        margin: 0 auto;
    }
    
    
    div .botoes {
        margin-top: 22px;
        text-align: center;
        text-align: center;
        margin-bottom:: 20px;
    }

</style>

<div class="container">
    
        <h3>Desistência do Prazo Recursal</h3>
        <form0 name="form" id="form" action="<?php echo $this->url(array('controller' => 'solicitarrecursodecisao', 'action' => 'recurso-desistencia-endraquamento')); ?>?idPronac=<?php echo $this->projetos->IdPRONAC; ?>" method="post">
            <input type="hidden" name="idPronac" id="idPronac" value="<?php echo $this->projetos->IdPRONAC; ?>" />
            <table class="tabela">
                <tr>
                    <td class="destacar bold centro">Pronac</td>
                    <td class="destacar bold centro">Nome do Projeto</td>
                </tr>
                <tr>
                    <td><?php echo $this->projetos->AnoProjeto.$this->projetos->Sequencial; ?></td>
                    <td><?php echo $this->projetos->NomeProjeto; ?></td>
                </tr>
            </table>
    <div class="card-panel indigo lighten-5 z-depth-4 termo">
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        This iLorem Ipsum tem sido o padrão desde a Idade Média. Um pintor teria peças mistas de texto em um livro exemplar e é este texto que nós usamos hoje. Outra versão diz que este é um trecho do livro de Cícero: "" De Finibus Bonorum e malorum "" seções 1.10.32 / 1.10.33. Este livro, muito popular durante a Renascença, é um tratado sobre a teoria da ética.
        Parece que apenas alguns trechos do texto original aparecem no Lipsum comumente usado, e que uma série de cartas tenham sido removido ou adicionado em diversos pontos do texto ao longo do tempo. É por isso que existem hoje em dia um número de texto Lorem Ipsum mais ou menos diferentes uns dos outros. Devido à sua data de produção, uso Lorem ipsum não está mais sujeito a direitos de autor e evita quaisquer questões de direitos autorais. s a card panel with a teal lighten-2 class
    </div>
        
            
        <div class="botoes">
            <a class="waves-effect waves-light btn modal-trigger" href="#modal1">
                Concordo
                <i class="material-icons right modal-trigger">send</i>
            </a>
            <button class="btn waves-effect waves-light red" id="btn_cancelar">
                Cancelar
            </button>
        </div>
    </form>

</div>

 <div id="modal1" class="modal">
    <div class="modal-content">
      <p>Tem certeza? Essa decisão não pode ser revertida.</p>
    </div>
    <div class="modal-footer">
      <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo $this->projetos->IdPRONAC;?>" class=" modal-action modal-close waves-effect waves-red btn-flat">Discordo</a>
        <a href="<?php echo $this->url(array('module' => 'default', 'controller'=> 'solicitarrecursodecisao', 'action' => 'recurso-desistencia-enquadramento-salvar'));?>?idPronac=<?php echo $this->projetos->IdPRONAC;?>" class=" modal-action modal-close waves-effect waves-green btn-flat">Concordo</a>
    </div>
  </div>

 <script>
        $jq3(document).ready(function () {
            $jq3('.modal').modal();
            
            $jq3('#btn_cancelar').click(function (){
                window.location.replace('<?php echo $this->Url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo $this->projetos->IdPRONAC; ?>');
            });
        });

</script>
