<div class="row" id="app">
    <dados idpronac="<?php echo $this->idpronac ?>"></dados>
</div>

<!-- vendor -->
<script src="/public/js/vue.js"></script>
<!-- vendor -->

<script>
    Vue.component('dados', {
        props: ['idpronac'],
        template: `<div class="col s12 m12" :informacoes = "informacoes">
                        <div class="card horizontal">
                            <div class="card-stacked">
                                <div class="center-align card-content  lighten-4">
                                    <span class="card-title"
                                          >
                                          {{ informacoes.Pronac }} - {{ informacoes.NomeProjeto }}
                                    </span>
                                </div>
                                <div class="card-panel teal">
                                    <span class="white-text" style="font-weight: bold; font-size: medium">
                                         <table>
                                            <tbody>
                                                <tr>
                                                    <td>Valor Aprovado</td>
                                                    <td>R$ {{ informacoes.vlAprovado }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Valor Comprovado</td>
                                                    <td>R$ {{ informacoes.vlComprovado }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Valor a Comprovar</td>
                                                    <td>R$ {{ informacoes.vlComprovar }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </span>
                                </div>
                                <div class="card-action">
                                    <a  :href="'/consultardadosprojeto/index?idPronac=' + idpronac " target="_blank"
                                        class="btn waves-effect waves-dark white-text">Ver Projeto
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>`,
        mounted: function () {
            let vue = this;
            $3.ajax({
                url: "/prestacao-contas/pagamento/planilha-dados-projeto/idpronac/" + this.idpronac
            }).done(function( data ) {
                vue.$data.informacoes = data;
            });
        },
        data: function () {
            return {
                informacoes: []
            };
        }
    })

    var app = new Vue ({
        el: '#app'
    })
</script>