<div class="row" id="app">
    <item
            idpronac="<?php echo $this->idpronac ?>"
            uf="<?php echo $this->uf ?>"
            etapa="<?php echo $this->idPlanilhaEtapa ?>"
            cidade="<?php echo $this->idMunicipio ?>"
            produto="<?php echo $this->codigoProduto ?>"
            idplanilhaitens="<?php echo $this->idPlanilhaItem ?>">
    </item>
</div>

<!-- vendor -->
<script src="/public/js/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<!-- vendor -->
<script>
    (function (global, factory) {
        if (typeof define === 'function' && define.amd) {
            define(['../numeral'], factory);
        } else if (typeof module === 'object' && module.exports) {
            factory(require('../numeral'));
        } else {
            factory(global.numeral);
        }
    }(this, function (numeral) {
        numeral.register('locale', 'pt-br', {
            delimiters: {
                thousands: '.',
                decimal: ','
            },
            abbreviations: {
                thousand: 'mil',
                million: 'milhões',
                billion: 'b',
                trillion: 't'
            },
            ordinal: function (number) {
                return 'º';
            },
            currency: {
                symbol: 'R$'
            }
        });
    }));

    numeral.locale('pt-br');

    function converteParaReal(value) {
        value = parseFloat(value);
        return numeral(value).format('0,0.00');
    }

    Vue.component('item', {
        props: ['idpronac', 'uf', 'etapa', 'cidade', 'produto', 'idplanilhaitens'],
        template: `<div class="col s12 m12" :informacoes = "informacoes">
                        <div class="card horizontal">
                            <div class="card-stacked">
                                <div class="center-align card-title lighten-4">
                                    Vincular Item de Custo
                                </div>
                                <div class="card-content">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>UF</th>
                                                <th>Cidade</th>
                                                <th>Produto</th>
                                                <th>Etapa</th>
                                                <th>Itens de Custo</th>
                                                <th style="text-align: right">Valor Aprovado</th>
                                                <th style="text-align: right">Total Comprovado</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>{{ informacoes.uf }}</td>
                                                <td>{{ informacoes.cidade }}</td>
                                                <td>{{ informacoes.Produto }}</td>
                                                <td>{{ informacoes.Etapa }}</td>
                                                <td>{{ informacoes.Item }}</td>
                                                <td style="text-align: right">R$ {{ converterParaReal(informacoes.vlAprovado) }}</td>
                                                <td style="text-align: right">R$ {{ converterParaReal(informacoes.vlComprovado) }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>`,
        mounted: function () {
            let vue = this;
            $3.ajax({
                url: "/prestacao-contas/pagamento/item/idpronac/" + this.idpronac
                + "/uf/" + this.uf
                + "/etapa/" + this.etapa
                + "/cidade/" + this.cidade
                + "/produto/"+ this.produto
                + "/idPlanilhaItens/" + this.idplanilhaitens
            }).done(function( data ) {
                vue.$data.informacoes = data;
            });
        },
        data: function () {
            return {
                informacoes: []
            };
        },
        methods:{
            converterParaReal: function (value) {
                value = parseFloat(value);
                return numeral(value).format('0,0.00');
            }
        }
    })

    var app = new Vue ({
        el: '#app'
    })
</script>