<!-- vendor -->
<script src="/public/js/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-produtos.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-etapas.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-ufs.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-cidades.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-itens.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-button.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/button-scroll-top.vue.js"></script>
<script src="/public/scripts/prestacao-contas/views/comprovacao-financeira.vue.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.5.0/d3.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.7/c3.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.7/c3.js"></script>

<div class="container-fluid" id="app">
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10">
                <h1>Prestação de Contas: Comprovação Financeira</h1>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a id="voltar" href="#" title="Página Anterior" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle">
                    <i class="material-icons">keyboard_return</i>
                </a>
            </div>
        </div>
    </div>
    <div class="row" >
        <div class="col s12 m12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title"><?php echo $this->pronac . " - " . $this->nomeProjeto ?></span>
                    <div class="row">
                        <div class="col s9 m9">
                             <table class="bordered">
                                <tbody>
                                    <tr>
                                        <td>Valor Aprovado</td>
                                        <td>R$ <?php echo number_format($this->vlAprovado, 2, ',', '.') ?></td>
                                    </tr>
                                    <tr>
                                        <td>Valor Comprovado</td>
                                        <td>R$ <?php echo number_format($this->vlComprovado, 2, ',', '.') ?></td>
                                    </tr>
                                    <tr>
                                        <td>Valor a Comprovar</td>
                                        <td>R$ <?php echo number_format($this->vlTotalComprovar, 2, ',', '.') ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="center-align col s3 m3">
                             <div id="chart1"></div>
                        </div>
                    </div>
                    <div class="card-action">
                        <a href="/consultardadosprojeto/index?idPronac=<?php echo $this->idpronac?>" target="_blank" class="btn waves-effect waves-dark white-text">Ver Projeto</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12">
            <comprovacao-financeira idpronac="<?php echo $this->idpronac ?>"></comprovacao-financeira>
        </div>
    </div>
    <div class="row">
        <div class="col s6 m12">
            <div class="card-panel teal">
                <span class="white-text" style="font-weight: bold; font-size: medium">
                    <table>
                        <tbody>
                            <tr>
                                <td>Valor Aprovado</td>
                                <td>R$ <?php echo number_format($this->vlAprovado, 2, ',', '.') ?></td>
                            </tr>
                            <tr>
                                <td>Valor Comprovado</td>
                                <td>R$ <?php echo number_format($this->vlComprovado, 2, ',', '.') ?></td>
                            </tr>
                            <tr>
                                <td>Valor a Comprovar</td>
                                <td>R$ <?php echo number_format($this->vlTotalComprovar, 2, ',', '.') ?></td>
                            </tr>
                        </tbody>
                    </table>
                </span>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn">
       <button-scroll-top></button-scroll-top>
    </div>
</div>

<!-- views -->
<script>
    (function (global, factory) {
        if (typeof define === 'function' && define.amd) {
            define(['../numeral'], factory);
        } else if (typeof module === 'object' && module.exports) {
            factory(require('../numeral'));
        } else {
            factory(global.numeral);
        }
    }(this, function (numeral) {
        numeral.register('locale', 'pt-br', {
            delimiters: {
                thousands: '.',
                decimal: ','
            },
            abbreviations: {
                thousand: 'mil',
                million: 'milhões',
                billion: 'b',
                trillion: 't'
            },
            ordinal: function (number) {
                return 'º';
            },
            currency: {
                symbol: 'R$'
            }
        });
    }));

    numeral.locale('pt-br');

    function converteParaReal(value) {
        value = parseFloat(value);
        return numeral(value).format('0,0.00');
    }

    var app = new Vue({
        el: '#app',
        methods: {
            iniciarCollapsible: function () {
                $3('.collapsible').each(function () {
                    $3(this).collapsible();
                });
            }
        }
    })

</script>
<script>
    $3(document).ready(function () {
        document.getElementById("voltar").href = '/projeto/#/incentivo/' + <?php echo $this->idpronac?>;

        $3("#visualizar-form").on('click', function () {
            tinymce.remove();
        });

        if ($3('#ir-para-o-topo').length) {
            var scrollTrigger = 100, // px
                backToTop = function () {
                    var scrollTop = $3(window).scrollTop();
                    if (scrollTop > scrollTrigger) {
                        $3('#ir-para-o-topo').parent().show();
                    } else {
                        $3('#ir-para-o-topo').parent().hide();
                    }
                };
            backToTop();

            $3(window).on('scroll', function () {
                backToTop();
            });

            $3('#ir-para-o-topo').on('click', function (e) {
                e.preventDefault();
                $3('html,body').animate({
                    scrollTop: 0
                }, 700);
            });
        }

        var chart = c3.generate({
            bindto:'#chart1',
            data: {
                columns: [
                    ['Falta Comprovar', <?php echo $this->vlTotalComprovar ?> ],
                    ['Comprovado', <?php echo $this->vlComprovado ?>],
                ],
                type : 'pie',
                 colors: {
                    'Falta Comprovar': '#586057',
                    'Comprovado': '#35b225',
                },
            },
            size: {
                height: 200,
                width: 150 
            },
        });
    });
</script>
