<div id="app" class="container-fluid">
    <v-app>
        <v-content>
            <page-title></page-title>
            <v-container>
                <router-view></router-view>
            </v-container>
        </v-content>
    </v-app>
</div>

<div class="row">
    <div class="col s12 m12">
        <div class="card">
            <div class="card-content">
                <div class="card">
                    <div class="center-align card-content grey lighten-4">
                        <span class="card-title">PLANILHA DE ORÇAMENTO APROVADA</span>
                    </div>
                </div>
                <div id="app-7">
                    <ul>
                        <todo-item
                             v-for="item in groceryList"
                             v-bind:todo="item"
                             v-bind:key="item.id">
                        </todo-item>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- vendor -->
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- vendor -->

<!-- views -->
<script>
    Vue.component('todo-item', {
        props: ['todo'],
        template: '<li>{{ todo.text }}</li>'
    })
    var app7 = new Vue({
        el: '#app-7',
        data: {
            groceryList: [
                { id: 0, text:'Pineapple'  },
                { id: 1, text:'Vegetables'  },
                { id: 2, text:'Apple'  },
                { id: 3, text:'Surprise'  }
            ]
        }
    })
</script>
<!-- views -->