<nav>
    <div class="nav-wrapper" style="padding: 0 15px 0 15px">
        <div class="col s12">
<!--            <a href="#!" class="breadcrumb">Admissibilidade</a>-->
            <a href="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'enquadramento', 'action' => 'listar')); ?>" class="breadcrumb tooltipped" data-position="top" data-delay="50" data-tooltip="Ir para a tela de enquadramento">Enquadramento</a>
            <a href="#!" class="breadcrumb tooltipped" data-position="top" data-delay="50" data-tooltip="Nome e Numero do Pronac">Perguntas do Pronac: Projeto TAL (<?php echo $this->id ?></a>)
        </div>
    </div>
</nav>
<!--<div class="row">-->
<!--    <div class="col s12">-->
<!--        <h3 class="header">Mensagem</h3>-->
<!--        <div class="center-align">-->
<!--            <a class="green darken-3 waves-effect waves-light btn" href="#modal1">Enviar mensagem</a>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!--<div class="container-fluid">-->
<!--<div class="row">-->
<!--    <div class="col s12">-->
<!--        <ul class="tabs">-->
<!--            <li class="tab col s3"><a class="active" href="#test1">A responder</a></li>-->
<!--            <li class="tab col s3"><a  href="#test2">Respondidas</a></li>-->
<!--            <li class="tab col s3 disabled"><a href="#test3">Disabled Tab</a></li>-->
<!--        </ul>-->
<!--    </div>-->
<!--    <div id="test1" class="col s12">Test 1</div>-->
<!--    <div id="test2" class="col s12">Test 2</div>-->
<!--</div>-->
<div id="container-list"></div>
<div class="fixed-action-btn">
    <a data-modal="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => 'salvar')); ?>" href="javascript:void(0);" class="btn-floating btn-large tooltipped waves-effect waves-light" data-position="left" data-delay="50" data-tooltip="Escrever pergunta">
        <i class="large material-icons">create</i>
    </a>
</div>
<!--</div>-->

<script type="text/javascript">
    //    (function($){
    //        $(document).ready (function(){
    //            $('.modal').modal();
    //            $('.modal').find('select').material_select();
    //            $('body').on('#btn-enviar', 'click', function () {
    //                console.info('asd')
    ////                $.post('admissibilidade/mensagem', $('#form-mensagem').serialize());
    //            });
    //        });
    //    }($.noConflict(true)));
</script>
<script>
    $jq3(document).ready(function () {
        // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $jq3('.modal').modal();
        $jq3('.modal').find('select').material_select();
        $jq3('.tooltipped').tooltip({delay: 50});

        $jq3('body').on('click', '#btn-enviar', function () {
            $jq3.post($jq3('#form-mensagem').attr('action'), $jq3('#form-mensagem').serialize(), function (result) {
                result = $jq3.parseJSON(result);
                console.info(result)
                if (result.status == '1') {
                    $jq3('#modal').modal('close');
                    $jq3('#form-mensagem')[0].reset();
                    list();
                    Materialize.toast(result.msg, 4000);
                } else {
                    Materialize.toast(result.msg, 4000);
                }
            });
        });
        $jq3('body').on('click', '[data-modal]', function() {
            var objClick = $jq3(this),
                strUrl = objClick.attr('data-modal'),
                objModal = $jq3('#modal');

//            if ( typeof objModal == 'undefined' || typeof objModal == 'object') {
                $jq3('#modal').remove();
                $jq3('body').append('<div id="modal" class="modal modal-fixed-footer"></div>');
                $jq3('#modal').modal();
//            }

            $jq3.ajax({
                method: "GET",
                url: strUrl,
                data: {idPronac: "<?php echo $this->id; ?>"}
            }).done(function (result) {
                $jq3('#modal').html(result);
                $jq3('#modal').modal('open');
            });
            console.info(objModal);
            console.info(objClick);
            console.info(strUrl)
        });

        list();
    });

    function modal(id)
    {
        $jq3.ajax({
            method: "GET",
            url: "/admissibilidade/mensagem/listar",
            data: {id: "<?php echo $this->id; ?>"}
        }).done(function (result) {
            $jq3('#container-list').hide().html(result).fadeIn();
        });
    }

    function list() {
        $jq3.ajax({
            method: "GET",
            url: "/admissibilidade/mensagem/listar",
            data: {id: "<?php echo $this->id; ?>"}
        }).done(function (result) {
            $jq3('#container-list').hide().html(result).fadeIn();
        });
    }
</script>
<!--<div id="rodapeConteudo"><span></span></div>-->
<!--<br clear="all"/>-->