<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb">Pronac: 54654</a>
            <a href="#!" class="breadcrumb">Projeto tal</a>
        </div>
    </div>
</nav>
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
<!--        <h4>Enviar mensagem</h4>-->
        <form id="form-mensagem">
            <input name="IdPRONAC" type="hidden" value="<?php echo $this->id; ?>"/>
            <div class="row">
                <div class="input-field col s12">
                    <select name="idDestinatario">
                        <option value="" disabled selected>Selecione...</option>
                        <?php foreach ($this->arrUsuarios as $key => $arrGrupo): ?>
                            <optgroup label="<?php echo $key ?>">
                                <?php foreach ($arrGrupo as $values): ?>
                                    <option value="<?php echo $values['usu_codigo'] ?>"><?php echo $values['usu_nome'] ?></option>
                                <?php endforeach; ?>
                            </optgroup>
                        <?php endforeach; ?>
                    </select>
                    <label>Optgroups</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <textarea name="dsMensagem" class="materialize-textarea"></textarea>
                    <label for="textarea1">Descricao</label>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <a id="btn-enviar" style="margin-left: 15px;"
           class="modal-action waves-effect waves-green btn-flat light-green">Enviar</a>
        <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Cancelar</a>
    </div>
</div>
<div class="row">
    <div class="col s12">
<!--        <h3 class="header">Mensagem</h3>-->
        <div class="center-align">
            <a class="green darken-3 waves-effect waves-light btn" href="#modal1">Enviar mensagem</a>
        </div>
    </div>
</div>
<!--<div class="container-fluid">-->
<div id="container-list"></div>
<div class="fixed-action-btn">
    <a href="#modal1" class="btn-floating btn-large tooltipped waves-effect waves-light" data-position="top" data-delay="50" data-tooltip="Enviar mensagem">
        <i class="large material-icons">send</i>
    </a>
</div>
<!--</div>-->

<script type="text/javascript">
    //    (function($){
    //        $(document).ready (function(){
    //            $('.modal').modal();
    //            $('.modal').find('select').material_select();
    //            $('body').on('#btn-enviar', 'click', function () {
    //                console.info('asd')
    ////                $.post('admissibilidade/mensagem', $('#form-mensagem').serialize());
    //            });
    //        });
    //    }($.noConflict(true)));
</script>
<script>
    $jq3(document).ready(function () {
        // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $jq3('.modal').modal();
        $jq3('.modal').find('select').material_select();
        $jq3('.tooltipped').tooltip({delay: 50});
        $jq3('body').on('click', '#btn-enviar', function () {
            console.info($jq3('#form-mensagem').serialize());
            $jq3.post('/admissibilidade/mensagem/salvar', $jq3('#form-mensagem').serialize(), function (result) {
                result = $jq3.parseJSON(result);
                if (result.status == '1') {
                    $jq3('#modal1').modal('close');
                    $jq3('#form-mensagem')[0].reset();
                    list();
                    Materialize.toast(result.msg, 4000);
                } else {
                    Materialize.toast(result.msg, 4000);
                }
            });
        });

        list();
    });

    function list() {
        $jq3.ajax({
            method: "GET",
            url: "/admissibilidade/mensagem/listar",
            data: {id: "<?php echo $this->id; ?>"}
        }).done(function (result) {
            $jq3('#container-list').hide().html(result).fadeIn();
        });
    }
</script>
<!--<div id="rodapeConteudo"><span></span></div>-->
<!--<br clear="all"/>-->