<div class="modal-content">
    <h4>Visualizar Pergunta</h4>
    <form id="form-mensagem" action="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => $this->action)); ?>">
        <input name="idMensagemProjeto" type="hidden" value="<?php echo $this->id; ?>"/>
        <input name="IdPRONAC" type="hidden" value="<?php echo $this->idPronac; ?>"/>
        <div class="row">
            <div class="input-field col s12">
                <select class="invalid" data-url="/admissibilidade/mensagem/usuarios"
                        data-target="select[name=idDestinatario]"
                        name="idDestinatarioUnidade" disabled="disabled">
                    <option value="" disabled selected>Selecione...</option>
                    <?php foreach ($this->arrUnidades as $values): ?>
                        <option <?php if (isset($this->dataForm['idDestinatarioUnidade']) && $this->dataForm['idDestinatarioUnidade'] == $values['Codigo']) echo 'selected="selected"' ?>
                            value="<?php echo $values['Codigo'] ?>"><?php echo $values['Sigla'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <label>Unidade</label>
            </div>
        </div>
        <?php if (isset($this->dataForm['idDestinatario']) && !empty($this->dataForm['idDestinatario'])): ?>
            <div class="row">
                <div class="input-field col s12">
                    <select class="invalid" required="required" name="idDestinatario" disabled="disabled">
                        <option value="" disabled selected>Selecione...</option>
                    </select>
                    <label>Agente</label>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="input-field col s12">
                <br />
                <?php if (isset($this->dataForm['dsMensagem'])) echo $this->dataForm['dsMensagem']; ?>
                <br />
                <label for="textarea1" <?php if (isset($this->dataForm['dsMensagem'])) echo 'class="active"' ?>>Pergunta</label>
            </div>
        </div>
        <?php if ((!isset($this->arrConfig['dsResposta']) || $this->arrConfig['dsResposta']['show'] !== false)): ?>
            <div class="row">
                <div class="input-field col s12">
                    <br />
                    <?php if (isset($this->dataForm['dsResposta'])) echo $this->dataForm['dsResposta']; ?>
                    <br />
                    <label for="textarea1" class="active">Resposta</label>
                </div>
            </div>
        <?php endif; ?>
    </form>
</div>
<div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat light-green">Fechar</a>
</div>
<script>
    $3(document).ready(function () {
        $3('.modal').find('select').material_select();
    });
    $3(document).ready(function () {
        $3('#form-mensagem').find('select').material_select();
        var select = $3('select[data-target]'),
            strUrl = select.attr('data-url'),
            objTarget = $3(select.attr('data-target'));
        ajaxRender(strUrl, objTarget, select.val(), '<?php echo (isset($this->dataForm['idDestinatario'])) ? $this->dataForm['idDestinatario'] : '' ?>');
    });

    function ajaxRender(strUrl, objTarget, strVal, strValChecked) {
        var strHtml = '';
        $3.ajax({
            method: "POST",
            url: strUrl,
            data: {id: strVal}
        }).done(function (result) {
            json = $3.parseJSON(result);
            strHtml = '<option value="" selected>Selecione...</option>';
            $3.each(json, function(key, value){
                strHtml += '<optgroup label="' + key + '">';
                $3.each(value, function(key2, value2){
                    if (strValChecked && strValChecked == key2) {
                        strHtml += '<option value="' + key2 + '" selected="selected">' + value2 + '</option>';
                    } else {
                        strHtml += '<option value="' + key2 + '">' + value2 + '</option>';
                    }
                });
                strHtml += '</optgroup>';
            });
            objTarget.html(strHtml);
            objTarget.material_select();
        });
    }
</script>