<script type="text/javascript">
    $(document).ready(function(){
        $('.visualizarObs').click(function(){
            var texto = $(this).children().attr('dsObservacao');
            $("#modalAlerta").dialog("destroy");
            $("#modalAlerta").html(texto);
            $("#modalAlerta").dialog({
                resizable: true,
                title: 'Observações',
                width:350,
                modal: true,
                buttons : {
                    'OK' : function(){
                        $(this).dialog('close');
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
            return false;
        });

    });
</script>

<?php require_once "scripts/avaliaracompanhamentoprojeto/inc/menu.inc.php"; ?>
<div id="modalAlerta" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Lista de Relatórios">Lista de Relatórios</a></li>
        <li class="last">Bens Doados</li>
    </ul>
</div>


<div id="titulo">
    <div>Bens Doados <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <th colspan="8">Bens Móveis / Imóveis Doados</th>
        </tr>
        <?php if(count($this->BensCadastrados)>0) { ?>
        <tr align="center">
            <td class="destacar bold">Tipo do Bem</td>
            <td class="destacar bold">Item Orçamentário</td>
            <td class="destacar bold">CNPJ/CPF</td>
            <td class="destacar bold">Nome</td>
            <td class="destacar bold">Arquivo Doação</td>
            <td class="destacar bold">Arquivo Aceite</td>
            <td class="destacar bold">Quantidade</td>
            <td class="destacar bold">Observação</td>
        </tr>
        <?php foreach ($this->BensCadastrados as $bens) { ?>
        <tr>
            <td><?php echo ($bens->tpBem == 'M') ? 'Móvel' : 'Imóvel'; ?></td>
            <td><?php echo $bens->ItemOrcamentario; ?></td>
            <td align="center"><?php echo (strlen($bens->CNPJCPF) == 11) ? Mascara::addMaskCPF($bens->CNPJCPF) : Mascara::addMaskCNPJ($bens->CNPJCPF); ?></td>
            <td><?php echo $bens->NomeAgente; ?></td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $bens->idArquivoDoacao; ?>"><?php echo $bens->nmArquivoDoacao; ?></a></td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $bens->idArquivoAceite; ?>"><?php echo $bens->nmArquivoAceite; ?></a></td>
            <td><?php echo $bens->qtBensDoados; ?></td>
            <td align="center">
                <a href="#" class="visualizarObs"><img src="<?php echo $this->baseUrl(); ?>/public/img/table_multiple.png" dsObservacao="<?php echo $bens->dsObservacao; ?>" /></a>
            </td>
        </tr>
        <?php } ?>
        <?php } else { ?>
        <tr>
            <td colspan="8" align="center">Nenhum registro encontrado.</td>
        </tr>
        <?php } ?>
    </table>

    <br clear="all" />
</div>


<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
