<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
 
  //Contador de limitadores de caracteres

function ExecucaoDaFuncaoLimiterPag(){
		    var count  = CountCharacters("informacaoAdicional");
		    var count2 = CountCharacters("orientacao");
		    var count3 = CountCharacters("conclusao"); 

                    document.getElementById("contadorinformacaoAdicional").innerHTML = "Caracteres: " + count + "/7500";
		    document.getElementById("contadororientacao").innerHTML = "Caracteres: " + count2 + "/950";
		    document.getElementById("contadorconclusao").innerHTML = "Caracteres: " + count3 + "/950";

                    if(count > 7500){
		        document.getElementById("contadorinformacaoAdicional").style.color = "red";
		    }else{
                        document.getElementById("contadorinformacaoAdicional").style.color = "black";
		    }

		    if(count2 > 950){
		        document.getElementById("contadororientacao").style.color = "red";
		    }else{
                        document.getElementById("contadororientacao").style.color = "black";
		    }

    	            if(count3 > 950){
		        document.getElementById("contadorconclusao").style.color = "red";
		    }else{
                        document.getElementById("contadorconclusao").style.color = "black";
		    }

}
    window.onload = function () {
        tinymce.init({
            selector: 'textarea',
            width: 1510,
            setup: function (ed) {
                ed.on('load', function (e) {
		ExecucaoDaFuncaoLimiterPag();
                }).on('keyup',function (e) {
		ExecucaoDaFuncaoLimiterPag();
		});
            }
        });
    }

    function CountCharacters(contador) {
        var body = tinymce.get(contador).getBody();
        var content = tinymce.trim(body.innerText || body.textContent);
        return content.length;
    };

    function Validacao(valido) {
        var max7500 = 7500;
	var max950= 950;
	var valido = true;  

        var count = CountCharacters("informacaoAdicional");
	var count2= CountCharacters("orientacao");
	var count3= CountCharacters("conclusao");
 
        if (count > max7500) {
	     $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Você ultrapassou o número de caracteres no campo Considerações!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            valido = false;
	}
	if (count2 > max950) {
	     $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Você ultrapassou o número de caracteres no campo Recomendações!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
	    valido = false;
	}
	if (count3 > max950) {
	    $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Você ultrapassou o número de caracteres no campo Conclusão!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
	    valido = false;
	}
        return valido;
    }
   
   function SalvarFormulario(){
       var valido = Validacao();
       if (valido == true){
           $('#formParecer').submit();	
       }
      return;
   }
   
   function EnviarFormulario(){
       var valido = Validacao();
       if (valido == true){
           $('#btn_finalizar').click(function(){
            var preenchimento = true,
                campoRadioMarcado = false;
            $('.obrigatorio').each(function(){
                if($.trim($(this).val()) == '')
                    preenchimento = false;
            });

            $('input:radio').each(function(){
                if($(this).attr('checked'))
                    campoRadioMarcado = true;
            });

            if(!preenchimento || !campoRadioMarcado) {
                $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Favor preencher o campo obrig&aacute;torio!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            } else {
                $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Deseja realmente finalizar?");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'Não' : function(){
                            $(this).dialog('close');
                        },
                        'Sim' : function(){
                            $(this).dialog('close');
                            $('#formParecer').append('<input type="hidden" name="finalizar" value="1" />');
                            $('#formParecer').submit();
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            }
         });

       }
   }

</script>


<?php require_once "scripts/avaliaracompanhamentoprojeto/inc/menu.inc.php"; ?>
<div id="camposObrigatorios" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Lista de Relatórios">Lista de Relatórios</a></li>
        <li class="last">Parecer Técnico</li>
    </ul>
</div>


<div id="titulo">
    <div>Parecer Técnico <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <form id="formParecer" action="<?php echo $this->url(array('controller' => 'avaliaracompanhamentoprojeto', 'action' => 'avaliar-relatorio'), '', true); ?>?idpronac=<?php echo $this->idPronac; ?>" method="post">
        <table class="tabela">
            <tr align="center">
                <td class="destacar bold">CONSIDERAÇÕES</td>
            </tr>
            <tr>
                <td>
                    <textarea name="informacaoAdicional" id="informacaoAdicional" cols="" rows="7" style="width: 99%;" class="informacaoAdicional" <?php echo $this->contadorTextarea('form.informacaoAdicional', 'form.exibirContadorTextarea1', 7500); ?>><?php echo $this->DadosParecer->dsInformacaoAdicional; ?></textarea>
                  <!--  <span style="clear:both;"><?php echo $this->exibirContadorTextarea('exibirContadorTextarea1', 4, 7500, strlen($this->DadosParecer->dsInformacaoAdicional), '30px'); ?></span> -->
                    <div id="contadorinformacaoAdicional" ></div>
 	   	</td>
            </tr>
            <tr align="center">
                <td class="destacar bold">RECOMENDAÇÕES</td>
            </tr>
            <tr>
                <td>
                    <textarea name="orientacao" id="orientacao" cols="" rows="7" style="width: 99%;" class="orientacao" <?php echo $this->contadorTextarea('form.orientacao', 'form.exibirContadorTextarea2', 950); ?>><?php echo $this->DadosParecer->dsOrientacao; ?></textarea>
                <!--    <span style="clear:both;"><?php echo $this->exibirContadorTextarea('exibirContadorTextarea2', 4, 950, strlen($this->DadosParecer->dsOrientacao), '30px'); ?></span> -->
                <div id="contadororientacao"></div>
		</td>
            </tr>
            <tr align="center">
                <td class="destacar bold">CONCLUSÃO <span style="color: red;">*</span></td>
            </tr>
            <tr>
                <td>
                    <textarea name="conclusao" id="conclusao" cols="" rows="7" style="width: 99%;" class="textarea_simples obrigatorio" <?php echo $this->contadorTextarea('form.conclusao', 'form.exibirContadorTextarea3', 950); ?>><?php echo $this->DadosParecer->dsConclusao; ?></textarea>
                <!--    <span style="clear:both;"><?php echo $this->exibirContadorTextarea('exibirContadorTextarea3', 4, 950, strlen($this->DadosParecer->dsConclusao), '30px'); ?></span> -->
                <div id="contadorconclusao"></div>
		</td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <th colspan="2">Avaliação</th>
            </tr>
            <tr>
                <td class="destacar bold w100" align="right">Resultado <span style="color: red;">*</span></td>
                <td>
                    <input
                        type="radio"
                        id="cumpriuObjetivos"
                        value="A"
                        name="resultadoAvaliacao"
                        <?php echo ($this->DadosParecer->stResultadoAvaliacao == 'A') ? 'checked="checked"' : ''; ?>
                        />
                    <label for="cumpriuObjetivos">Cumpriu os objetos e objetivos</label>
                    <input
                        type="radio"
                        id="naoCumpriuObjetivos"
                        value="R"
                        name="resultadoAvaliacao"
                        <?php echo ($this->DadosParecer->stResultadoAvaliacao == 'R') ? 'checked="checked"' : ''; ?>
                        style="margin-left: 25px;"
                        />
                    <label for="naoCumpriuObjetivos">Não cumprimento dos objetos e objetivos</label>
                    <input
                        type="radio"
                        id="cumpriuParcialmenteObjetivos"
                        value="P"
                        name="resultadoAvaliacao"
                        <?php echo ($this->DadosParecer->stResultadoAvaliacao == 'P') ? 'checked="checked"' : ''; ?>
                        style="margin-left: 25px;"
                        />
                    <label for="cumpriuParcialmenteObjetivos">Cumpriu parcialmente os objetos e objetivos</label>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" rowspan="2" align="right">Avaliadores <span style="color: red;">*</span></td>
                <td>
                    <select class="select_simples w200" disabled="disabled">
                        <option value="<?php echo $this->nmusuario; ?>"><?php echo $this->nmusuario; ?></option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples obrigatorio" name="chefiaImediata">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Usuarios as $usuarios) { ?>
                        <option value="<?php echo $usuarios->idUsuario; ?>" <?php echo ($this->DadosParecer->idChefiaImediata == $usuarios->idUsuario) ? 'selected="selected"' : ''; ?>><?php echo $usuarios->Nome; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
        </table>
    </form>

    <p align="center">
        <input type="button" class="btn_salvar" id="btn_salvar" onclick="return SalvarFormulario();">
        <input type="button" value="" class="btn_finalizar" id="btn_finalizar" onclick="return EnviarFormulario();">
    </p>

    <br clear="all" />
</div>


<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
