<?php
/**
 * Alterar Projeto
 * @author Equipe RUP - Politec
 * @since 15/01/2011
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.alterarprojeto
 * @copyright (c) 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para p&aacute;gina inicial">Início</a></li>
        <li><!--a href="<?php echo $this->baseUrl(); ?>" title="Início"-->Manuten&ccedil;&atilde;o<!--/a--></li>
        <li class="last">Alterar projeto</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<script type="text/javascript">
    $(document).ready(function(){
        $("#pronac").numeric();
    });
</script>

<div id="titulo">
    <div>Alterar projeto <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>

<div id="conteudo">
    <form class="form" name="formBuscar" id="formBuscar" method="POST" action="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'alterarprojeto')); ?>">
        <table class="tabela">
            <tr>
                <td class="destacar bold w150" align="center">PRONAC</td>
                <td>
                    <input class="input_simples w150" type="text" name="pronac" id="pronac" maxlength="7" onkeyup="mascara(this, format_pronac);" value="<?php echo $this->pronac;?>"/>
                    <input type="hidden" name="pesquisa" id="pesquisa" value="true"/>
                </td>
            </tr>
        </table>
        <table class="tabela">
            <tr>
                <td class="centro"><input class="btn_localizar" title="Localizar" type="submit" value=" " /></td>
            </tr>
        </table>
    </form>
    <br clear="all" />
</div>


<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />