<?php
/**
 * Alterar Projeto
 * @author Equipe RUP - Politec
 * @since 15/01/2011
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.alterarprojeto
 * @copyright (c) 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

include_once 'scripts/alterarprojeto/inc/menu.inc.php';
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para p&aacute;gina inicial">Início</a></li>
        <li><!--a href="<?php echo $this->baseUrl(); ?>" title="Início"-->Manuten&ccedil;&atilde;o<!--/a--></li>
        <li><a href="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'consultarprojeto')); ?>" title="Ir para alterar projeto">Alterar projeto</a></li>
        <li class="last">Alterar per&iacute;odo de execu&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== BUTTON VOLTAR ========== -->
<div id="titulo">
    <div>Alterar per&iacute;odo de execu&ccedil;&atilde;o <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== GRID NOME DA PROPOSTA ========== -->
<script type="text/javascript">
    $(document).ready( function() {
        $("#formularioAtualiza").validate({
            // Define as regras
            rules:{
                dtFimExecucao:{
                    required: true
                },
                dtInicioExecucao:{
                    required: true
                },
                justificativa:{
                    required: true
                }
            },
            // Define as mensagens de erro para cada regra
            messages:{
                dtFimExecucao:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                },
                dtInicioExecucao:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                },
                justificativa:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                }
            }
        });
    });

    function abrir_fechar(id_div){
        $('#'+id_div).slideToggle(400);
        $('#maiss'+id_div).toggle().focus();
        $('#menoss'+id_div).toggle().focus();
    }

    $(document).ready(function(){
        $("#formularioAtualiza").submit(function(){

            var faseExecIni = $("#dtInicioExecucao").val();
            var faseExecFim = $("#dtFimExecucao").val();

            var dtInicioExecucao = parseInt(faseExecIni.split("/")[2].toString() + faseExecIni.split("/")[1].toString() + faseExecIni.split("/")[0].toString());
            var dtFimExecucao = parseInt(faseExecFim.split("/")[2].toString() + faseExecFim.split("/")[1].toString() + faseExecFim.split("/")[0].toString());

            if (dtFimExecucao <= dtInicioExecucao){
                $("#mensagemData").html('<font color="red">Data final de elaboraç&atilde;o é menor ou igual a inicial</font>');
                return false;
            }
        });

        // calendário
        $.datepicker.regional['pt-BR'] = {
            closeText: 'Fechar',
            prevText: '&#x3c;Anterior',
            nextText: 'Pr&oacute;ximo&#x3e;',
            currentText: 'Hoje',
            monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','S&aacute;bado'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
            dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 0,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
        };
        $.datepicker.setDefaults($.datepicker.regional['pt-BR']);

        // id dos campos que utilizarão o calendário
        $("#dtInicioExecucao, #dtFimExecucao").datepicker($.datepicker.regional['pt-BR']);
    });
</script>

<div id="conteudo">
    <div id="mensagemData" name="mensagemData" style="display:block"></div>
    <form name="formularioAtualiza" id="formularioAtualiza" method="post" action="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'salvaalterarprojeto')); ?>" >
        <input type="hidden" name="pronac" value="<?php echo $this->parecer->pronac ?>" />
        <input type="hidden" name="pagina" value="periododeexecucao" />
        <table class="tabela">
            <tr>
                <th colspan="2" class="centro">Identifica&ccedil;&atilde;o</th>
            </tr>
            <tr class="destacar centro bold">
                <td width="200">PRONAC</td>
                <td>Nome do Projeto</td>
            </tr>
            <tr>
                <td align="center"><?php echo $this->parecer->pronac; ?></td>
                <td align="center"><?php echo $this->parecer->NomeProjeto; ?></td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td width="200" class="destacar bold" align="right">Data In&iacute;cio</td>
                <td><input class="input_simples btn_calendario" name="dtInicioExecucao" id="dtInicioExecucao" autocomplete="off" onkeyup="mascara(this, format_data);" maxlength="10" value="<?php echo ConverteData(strtotime($this->parecer->DtInicioExecucao),5) ?>" type="text" /></td>
            </tr>
            <tr>
                <td width="200" class="destacar bold" align="right">Data Final</td>
                <td><input class="input_simples btn_calendario" name="dtFimExecucao" id="dtFimExecucao" autocomplete="off" onkeyup="mascara(this, format_data);" maxlength="10" value="<?php echo ConverteData(strtotime($this->parecer->DtFimExecucao),5) ?>" type="text" /></td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <th>Justificativa<span style="color: red;">*</span></th>
            </tr>
            <tr>
                <td align="center">
                    <textarea class="textarea_simples h100" style="width:99%" id="justificativa" obrigatorio="1" name="justificativa"></textarea>
                </td>
            </tr>
            <tr>
                <td class="centro">

                    <table class="tabela">
                        <tr>
                            <td class="esquerda"><input type="button" class="btn_adicionar" title="Expandir" value=" " onclick="return abrir_fechar('lista')" onkeypress="return abrir_fechar('lista')" /> Anexar Documentos</td>
                        </tr>
                    </table>

                    <div id="lista">
                        <input type="hidden" name="excuir[]" id="excuir" value="" />
                        <table class="tabela">
                            <tbody id="tabelaArquivos">
                                <tr class="titulo_tabela" >
                                    <th>Tipo Documento</th>
                                    <th>Data</th>
                                    <th>Classifica&ccedil;&atilde;o</th>
                                    <th>Documento</th>
                                    <th>A&ccedil;&atilde;o</th>
                                </tr>
                                <?php foreach($this->documentos as $doc) { ?>
                                <tr>
                                    <td><?php echo !empty($doc->AgenteDoc) ? 'Proponente' : 'Projeto' ?></td>
                                    <td><?php echo date("d/m/Y H:i:s",strtotime($doc->dtHistoricoAlteracaoProjeto)) ?></td>
                                    <td><?php echo $doc->Descricao ?></td>
                                    <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $doc->idArquivo; ?>"><?php echo $doc->nmArquivo ?></a></td>
                                    <td>&nbsp;</td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>

                        <table class="tabela" >
                            <tr>
                                <td class="direita">
                                    <input class="btn_incluir" id="btn_incluir" value=" " type="button" onclick="EnviarArquivo()" title="Incluir" />
                                </td>
                            </tr>
                        </table>

                    </div>

                </td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td class="centro">
                    <input class="btn_salvar" id="btn_salvar" value=" " type="submit" title="Salvar" />
                </td>
            </tr>
        </table>
    </form>
</div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />
<iframe name="enviar_arquivo" id="enviar_arquivo" style="height: 20px; display: none;"></iframe>