<input type="hidden" id="url" value="<?php echo $this->tela;?>">
<input type="hidden" id="mensagem" value="<?php echo $this->mensagem;?>">
<script>
    $(document).ready(function(){
        if($('#mensagem').val()){
            janelaAlerta($('#mensagem').val(),redirecionar);
        }else{
            redirecionar();
        }
    });

    function redirecionar(){
        window.location = $('#url').val();
    }
    function janelaAlerta(mensagem,funcaoAdcional){
        if(funcaoAdcional==undefined){
            funcaoAdcional = function(){}
        }
        var nomeJanelaAlerta =   janelaObj({
            parametros : {
                width:      400,
                autoOpen:   false,
                resizable:  false,
                modal:      true,
                buttons: {
                    OK: function() {
                        funcaoAdcional();
                        $(this).dialog('close');
                    }
                }
            },
            removerBtFechar:true,
            title : 'Alerta'
        });
        nomeJanelaAlerta.divConteudo.html(mensagem);
        nomeJanelaAlerta.abrirJanela();

        return nomeJanelaAlerta;
    }
    function janelaObj(dados){
        var divConteudo = $('<div></div>')
        .attr('title',dados.title)
        .appendTo('body');
        var novaJanela = {
            divConteudo : divConteudo,
            removerBtFechar: true,
            parametros : {autoOpen: false},
            iniciarJanela : function(dados){
                this.refineParametrosObj(dados);

                this.divConteudo.dialog(this.parametros);
            },
            abrirJanela:function(){
                this.divConteudo.dialog('open');
                if(this.removerBtFechar)
                    $('.ui-dialog-titlebar-close').remove();
            },
            fecharJanela:function(){
                this.divConteudo.dialog('close');
                this.divConteudo.remove();
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){
                        this[j]=data[j];
                    }
            }
        }
        novaJanela.iniciarJanela(dados);
        return novaJanela;
    }
</script>