<!-- ========== INICIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="last">Analisar Solicitação de Item</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<div id="titulo">
    <div>Analisar Solicitação de Item</div>
</div>


<div id="conteudo">

    <?php if(count($this->dados)>0){ ?>
    <!-- ============ PAGINAÇÃO ============ -->
    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr>
                <td align="center">
                <form name="form1" id="form1" action="<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index'));?>" method="get">
                    <?php if($this->paginacao['pag']>1) { ?>
                    <input style="width: 88px;" lass="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'">
                    <?php } ?>
                    <input style="width: 88px;" id="btn_p_anterior" type="button"
                    <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                    <?php }else { ?>
                           class="btn_p_anterior"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'"
                    <?php } ?>>
                    <input style="width: 88px;"  id="btn_p_proximo" type="button"
                           <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                           class="btn_p_proximo-off"
                    <?php }else { ?>
                           class="btn_p_proximo"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'"
                    <?php } ?>>
                    <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                    <input style="width: 88px;" class="btn_ultimo" id="btn_ultimo" type="button"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'">
                    <?php } ?>
                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()" class="input_simples">
                        <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                        <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                        <?php endfor; ?>
                    </select>
                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                 </form>
                </td>
            </tr>
        </tbody>
    </table>
    <center>
        <?php
            echo $this->paginacao['inicio']." a ";
            echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
            echo " de ". $this->paginacao['total'];
        ?>
    </center>
    <!-- ========== FIM PAGINAÇÃO ========== -->
    <?php } ?>


    <?php if($this->qtdRelatorios != 0){ ?>
    <table class="tabela tablesorter">
        <tr>
            <th>Produto</th>
            <th>Etapa</th>
            <th>Item Solicitado</th>
            <th>Justificativa da Solicitação</th>
            <th>Tipo Solicitação</th>
        </tr>
        <?php foreach($this->dados as $dp){ ?>
        <tr>
            <td nowrap><?php echo $dp->Produto; ?></td>
            <td nowrap><?php echo $dp->Etapa; ?></td>
            <td nowrap><a href="<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'detalhar'));?>?item=<?php echo $dp->idSolicitarItem; ?>"><?php echo $dp->ItemSolicitado; ?></a></td>
            <td><?php echo $dp->Justificativa; ?></td>
            <td><?php echo $dp->TipoSolicitacao; ?></td>
        </tr>
        <?php } ?>
    </table>

    <?php if(count($this->dados)>0){ ?>

        <!-- ============ PAGINAÇÃO ============ -->
        <?php if($this->qtdRelatorios > 10) { //echo $this->dados; ?>
        <center>
            <?php
                echo $this->paginacao['inicio']." a ";
                echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                echo " de ". $this->paginacao['total'];
            ?>
        </center>
        <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td align="center">
                    <form name="form2" id="form2" action="<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index'));?>" method="get">
                        <?php if($this->paginacao['pag']>1) { ?>
                        <input style="width: 88px;" lass="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'">
                        <?php } ?>
                        <input style="width: 88px;" id="btn_p_anterior" type="button"
                        <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                        <?php }else { ?>
                               class="btn_p_anterior"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'"
                        <?php } ?>>
                        <input style="width: 88px;"  id="btn_p_proximo" type="button"
                               <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                               class="btn_p_proximo-off"
                        <?php }else { ?>
                               class="btn_p_proximo"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'"
                        <?php } ?>>
                        <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                        <input style="width: 88px;" class="btn_ultimo" id="btn_ultimo" type="button"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'analisarsituacaoitem', 'action' => 'index')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao']; ?>'">
                        <?php } ?>
                        Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()" class="input_simples">
                            <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                            <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                            <?php endfor; ?>
                        </select>
                        &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                     </form>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- ========== FIM PAGINAÇÃO ========== -->

    <?php } } ?>


    <?php } else { ?>
    <!--<table class="tabela">
        <tr>
            <td align="center">NENHUM PRODUTO PARA DISTRIBUIR!</td>
        </tr>
    </table>-->
    <?php } ?>
    <br clear="all" />


</div>
<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />