<script>
    $(document).ready(function(){
    	$(".orderBy").click(function(){
            var campo = $(this).attr("valorOrdenacao");

            if("ASC" == $("#tipoOrdenacao").val()){
                tipo = "DESC";
            }else{
                tipo = "ASC";
            }

            ordenar(campo, tipo);
        });

        $(".orderBy").each(function(){
            if($("#ordenacao").val() == $(this).attr("valorOrdenacao")){
                if($("#tipoOrdenacao").val() == "ASC"){
                    $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-baixo.PNG" align="absmiddle"></span>');
                }else{
                    $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-cima.PNG" align="absmiddle"></span>');
                }
            }
        });
        
        
        $('#btn_xls').click(function(){
            $('#frmPaginacao').attr('target','_blank').append('<input type="hidden" name="tipo" id="xls" value="xls"/>');
            $('#frmPaginacao').submit();
            $('#xls').remove();
            
        });
        
        $('#btn_imprimir').click(function(){
            $('#frmPaginacao').attr('target','_blank').append('<input type="hidden" name="tipo" id="pdf" value="pdf"/>');
            $('#frmPaginacao').submit();
            $('#pdf').remove();
            
        });
        
    });

    function paginar(pag){
        $("#pag").val(pag);
        jqAjaxForm(document.getElementById("frmPaginacao"), "resultadoConsulta");
        $("#resultadoConsulta").html("Aguarde, carregando dados ...");
    }

    function ordenar(campo, tipo){
    	$("#ordenacao").val(campo);
        $("#tipoOrdenacao").val(tipo);
        paginar(1);
    }
    
</script>
<fieldset>
    <legend>Resultado</legend>
<div class="conteudoImprimivel" id="conteudoImprimivel">
<table class="tabela" style="width: 90%">
    <tbody>
    <tr>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="1">Banco</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="2">Ag&ecirc;ncia</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="4">Nome da Ag&ecirc;ncia</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="5">Cidade</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="6">UF</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="7">Telefone</a></th>
        <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="8">Perfil</a></th>
    </tr>
    <?php if(count($this->contasBancarias) > 0):?>
    <?php foreach($this->contasBancarias as $conta):?>
    <tr>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->Banco?></td>
        <td rowspan="1" valign="top" align="center"><?php echo aplicaMascara($conta->Agencia, "9999-9")?></td>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->NomeAgencia?></td>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->Cidade?></td>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->Uf?></td>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->Telefone?></td>
        <td rowspan="1" valign="top" align="center"><?php echo $conta->Perfil?></td>
    </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <tr>
        <td colspan="7" valign="top" align="center">Nenhum Registro Encontrado</td>
    </tr>
    <?php endif; ?>
</tbody>
</table>
</div>
    
<form action="<?php echo $this->url(array('controller' => 'operacional', 'action' => 'resultado-agencia-bancaria')); ?>" method="post" name="frmPaginacao" id="frmPaginacao">
<?php foreach($this->parametrosBusca as $name=>$value):?>
    <input type="hidden" name="<?php echo $name?>" id="<?php echo $name?>" value="<?php echo $value?>"/>
<?php endforeach; ?>
    <?php if(empty($this->parametrosBusca["pag"])):?>
    <input type="hidden" name="pag" id="pag" value="<?php echo $this->pag; ?>"/>
    <?php endif; ?>
    <?php if(empty($this->parametrosBusca["ordenacao"])):?>
    <input type="hidden" name="ordenacao" id="ordenacao" value="<?php echo (!empty($this->parametrosBusca["ordenacao"]))?$this->parametrosBusca["ordenacao"]:""; ?>"/>
    <?php endif; ?>
    <?php if(empty($this->parametrosBusca["tipoOrdenacao"])):?>
    <input type="hidden" name="tipoOrdenacao" id="tipoOrdenacao" value="<?php echo (!empty($this->parametrosBusca["tipoOrdenacao"]))?$this->parametrosBusca["tipoOrdenacao"]:""; ?>"/>
    <?php endif; ?>
</form>

<form method="POST" id="formGerarXls" name="formGerarXls" action="<?php echo $this->url(array('controller' => 'operacional', 'action' => 'gerar-xls')); ?>" style="display:none">
    <textarea name="html" id="conteudoXLS"></textarea>
</form>

<form method="POST" id="formGerarPdf" name="formGerarPdf" action="<?php echo $this->url(array('controller' => 'operacional', 'action' => 'gerar-pdf')); ?>" style="display:none">
    <textarea name="html" id="conteudoImprimir"></textarea>
</form>

<table class="tabela" style="width: 90%;">
    <tr>
        <td align="center">
            <input type="button" style="width: 88px" class="btn_inicio" id="btn_inicio" onclick="paginar('1')"/>
            <input type="button" style="width: 88px" class="btn_p_anterior" id="btn_p_anterior" onclick="paginar('<?php echo ($this->pag > 1)?$this->pag-1:1; ?>')"/>
            <select name="pagina" id="pagina" class="input_simples" onchange="paginar(this.value)">
                <?php for($i=1; $i<$this->totalPag+1; $i++): ?>
                <option value="<?php echo $i; ?>" <?php if($i == $this->pag){ echo " selected='selected' "; } ?>><?php echo $i; ?></option>
                <?php endfor; ?>
            </select>
            <input type="button" style="width: 88px" class="btn_p_proximo" id="btn_p_proximo" onclick="paginar('<?php echo ($this->pag < $this->totalPag)?$this->pag+1:$this->totalPag; ?>')"/>
            <input type="button" style="width: 88px" class="btn_ultimo" id="btn_ultimo" onclick="paginar('<?php echo $this->totalPag; ?>')"/>
            <input type="button" style="width: 44px" class="btn_xls" id="btn_xls" />
            <input type="button" style="width: 88px" class="btn_imprimir" id="btn_imprimir" />
            Exibindo de <b><?php echo $this->inicio; ?></b> a <b><?php echo $this->fim; ?></b> de um total de <b><?php echo $this->total; ?></b>
        </td>
    </tr>
</table>
</fieldset>