<?php header('Content-Type: text/plain; charset=ISO-8859-1'); ?>
<script>
$(document).ready(function(){	
    $(".orderBy").click(function(){
            var campo = $(this).attr("valorOrdenacao");

            if("ASC" == $("#tipoOrdenacao").val()){
                tipo = "DESC";
            }else{
                tipo = "ASC";
            }

            ordenar(campo, tipo);
        });

        $(".orderBy").each(function(){
            if($("#ordenacao").val() == $(this).attr("valorOrdenacao")){
                if($("#tipoOrdenacao").val() == "ASC"){
                    $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-baixo.PNG" align="absmiddle"></span>');
                }else{
                    $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-cima.PNG" align="absmiddle"></span>');
                }
            }
        });
        
        
        $('#btn_xls').click(function(){
            $('#frmPaginacao').attr('target','_blank').append('<input type="hidden" name="tipo" id="xls" value="xls"/>');
            $('#frmPaginacao').submit();
            
        });
        
        $('#btn_imprimir').click(function(){
            $('#frmPaginacao').attr('target','_blank').append('<input type="hidden" name="tipo" id="pdf" value="pdf"/>');
            $('#frmPaginacao').submit();
            
        });
    });

function paginar(pag){
    $("#pag").val(pag);
    jqAjaxForm(document.getElementById("frmPaginacao"), "resultadoConsulta");
    $("#resultadoConsulta").html("Aguarde, carregando dados ...");
    //jqAjaxLink("<?php echo $this->baseUrl()?>/operacional/tabelas?consulta="+$("#consulta").val(), null, "resultadoConsulta");
}

function ordenar(campo, tipo){
	$("#ordenacao").val(campo);
    $("#tipoOrdenacao").val(tipo);
    paginar(1);
}

</script>
<fieldset>
    <legend>Situa&ccedil;&otilde;es</legend>
    <div class="conteudoImprimivel">
		<table class="tabela">
		    <tbody>
		        <tr>
		            <th valign="middle" align="center" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="1">C&oacute;digo</a></th>
		            <th valign="middle" align="left" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="2">Situa&ccedil;&atilde;o</a></th>
		            <th valign="middle" align="left" bgcolor="#abda5d"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="4">Estado</a></th>
		        </tr>
		        <?php foreach($this->dados as $dado): ?>
		        <tr>
		            <td valign="middle" align="center"><?php echo $dado->Codigo?></td>
		            <td valign="middle" align="left"><?php echo $dado->Descricao?></td>
		            <td valign="middle" align="left"><?php if($dado->StatusProjeto == 1){ echo "Ativado"; }elseif($dado->StatusProjeto == 0){ echo "Desativado"; }else{ echo "Arquivado"; }?></td>
		        </tr>
		        <?php endforeach; ?>
		    </tbody>
		</table>
	</div>
	<form action="<?php echo $this->url(array('controller' => 'operacional', 'action' => 'tabelas')); ?>?consulta=situacoes" method="post" name="frmPaginacao" id="frmPaginacao">
    <?php foreach($this->parametrosBusca as $name=>$value):?>
        <?php if(!is_array($value)): ?>
        <input type="hidden" name="<?php echo $name?>" id="<?php echo $name?>" value="<?php echo $value?>"/>
        <?php else: ?>
            <?php foreach($value as $valor):?>
                <input type="hidden" name="<?php echo $name?>[]" id="<?php echo $name?>" value="<?php echo $valor?>"/>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
        <?php if(empty($this->parametrosBusca["pag"])):?>
        <input type="hidden" name="pag" id="pag" value="<?php echo $this->pag; ?>"/>
        <?php endif; ?>
        <?php if(empty($this->parametrosBusca["ordenacao"])):?>
	    <input type="hidden" name="ordenacao" id="ordenacao" value="<?php echo (!empty($this->parametrosBusca["ordenacao"]))?$this->parametrosBusca["ordenacao"]:""; ?>"/>
	    <?php endif; ?>
	    <?php if(empty($this->parametrosBusca["tipoOrdenacao"])):?>
	    <input type="hidden" name="tipoOrdenacao" id="tipoOrdenacao" value="<?php echo (!empty($this->parametrosBusca["tipoOrdenacao"]))?$this->parametrosBusca["tipoOrdenacao"]:""; ?>"/>
	    <?php endif; ?>
    </form>
    
    <form method="POST" id="formGerarXls" name="formGerarXls" action="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'gerar-xls')); ?>" style="display:none">
        <textarea name="html" id="conteudoXLS"></textarea>
    </form>

    <form method="POST" id="formGerarPdf" name="formGerarPdf" action="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'gerar-pdf')); ?>" style="display:none">
        <textarea name="html" id="conteudoImprimir"></textarea>
    </form>
    
    <table class="tabela">
        <tr>
            <td align="center">
                <input type="button" style="width: 88px" class="btn_inicio" id="btn_inicio" onclick="paginar('1')"/>
                <input type="button" style="width: 88px" class="btn_p_anterior" id="btn_p_anterior" onclick="paginar('<?php echo ($this->pag > 1)?$this->pag-1:1; ?>')"/>
                <select name="pagina" id="pagina" class="input_simples" onchange="paginar(this.value)">
                    <?php for($i=1; $i<$this->totalPag+1; $i++): ?>
                    <option value="<?php echo $i; ?>" <?php if($i == $this->pag){ echo " selected='selected' "; } ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
                <input type="button" style="width: 88px" class="btn_p_proximo" id="btn_p_proximo" onclick="paginar('<?php echo ($this->pag < $this->totalPag)?$this->pag+1:$this->totalPag; ?>')"/>
                <input type="button" style="width: 88px" class="btn_ultimo" id="btn_ultimo" onclick="paginar('<?php echo $this->totalPag; ?>')"/>
                <input type="button" style="width: 44px" class="btn_xls" id="btn_xls" />
                <input type="button" style="width: 88px" class="btn_imprimir" id="btn_imprimir" />
                Exibindo de <b><?php echo $this->inicio; ?></b> a <b><?php echo $this->fim; ?></b> de um total de <b><?php echo $this->total; ?></b>
            </td>
        </tr>
    </table>
</fieldset>