<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINISTÉRIO DA CULTURA<br>
    Secretaria de Fomento e Incentivo à Cultura<br>
    Esplanada dos Ministérios, Bloco "B"<br>
    Brasília/DF - CEP 70.068-900
</p>
<div>
    <p lang="pt-BR" align="LEFT">
    <strong>
        Comunicado nº ____/<?php echo date('Y'); ?>
    </strong>
    </p>
    <p lang="pt-BR" align="LEFT">
        <strong> </strong>
    </p>
    <p lang="pt-BR" align="RIGHT">
        Brasília-DF, ___/ ___/ _____.
    </p>
    <p lang="pt-BR" align="LEFT">
        À </br>
        Brincante Produções Artísticas Ltda. </br>
        Comercial - Rua - Purpurina - 428 - Sumarezinho - teatro </br>
        São Paulo /SP </br>
        CEP: 05.435-030
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        Projeto: {nomeProjeto}</br>
        Proponente: {nomeProponente}</br>
        Processo: {processo}</br>
        Pronac: {pronac}
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        1. No exercício das competências legalmente atribuídas ao Ministério da Cultura, comunicamos a Vossa Senhoria que a análise da prestação de contas do
        projeto em referência foi concluída e <strong>APROVADA</strong> por este Ministério e que estão disponíveis para consulta no Sistema de Apoio às Leis de
        Incentivo à Cultura (SalicWeb) o Relatório de Execução, a Avaliação da Prestação de Contas e o Laudo acerca da prestação de contas do projeto acima.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
    2. Ressaltamos que documentos fiscais, relatórios e demais documentos pertinentes ao projeto em referência deverão ser guardados pelo prazo mínimo de    <strong>10 (dez) anos</strong>, conforme art. 83 da Instrução Normativa MinC nº 01/2013, <em>in verbis</em>:
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        "
        <em>
            Art. 83. Cabe ao proponente emitir comprovantes em favor dos doadores ou patrocinadores, bem como manter o controle documental das receitas e despesas
            do projeto pelo prazo de dez anos, contados da aprovação da prestação de contas, à disposição do MinC e dos órgãos de controle e fiscalização, caso
            seja instado a apresentá-las, conforme previsto no art. 36 da Instrução Normativa RFB nº 1.131, de 21 de fevereiro de 2011
        </em>
        ".
    </p>
    <p lang="pt-BR">
        3. Por oportuno, colocamo-nos à disposição para quaisquer dúvidas a respeito do assunto em pauta, bem como registramos nossa satisfação pela conclusão
        dessa exitosa ação desenvolvida em prol da cultura brasileira.
    </p>
    <p lang="pt-BR" align="LEFT">
        Atenciosamente,
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorIncentivoACultura}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Secretário(a) de Fomento e Incentivo à Cultura
    </p>
</div>