<?php


//require_once "inc/menu.inc.php"; // menu
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''),'',true); ?>" title="Ir para Início">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'gerenciarpareceres', 'action' => 'index'),'',true); ?>" title="Gerenciar Pareceres">Gerenciar Pareceres T&eacute;cnicos</a></li>
		<li class="last">Consolidação manual de Pareceres</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Consolidação manual de Pareceres<span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<table class="tabela">
		<tr>
			<td align="center" style="font-size:15px; color:#000">
				<br />
				A consolidação de Pareceres é uma tarefa automatizada pelo Sistema,<br />
				no entanto, você pode forçar uma consolidação neste momento.
				<br />
				<br />
			</td>
		</tr>
	</table>
	
	<table class="tabela">
		<tr>
			<td align="center">
				<input type="button" class="btn_confirmar" style="width:88px;" name="btn_confirmar" value=" " onclick="redirecionar('./execconsolidacao');"/>
				<input type="button" class="btn_voltar" name="btn_voltar" value=" " onclick="voltar();"/>
			</td>
		</tr>
	</table>




</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />