<?php require_once "inc/menu.inc.php"; // menu ?>
<!-- início: navegação local #qm0 -->

<!-- início: #breadcrumb -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="Início">Início</a></li>
        <li class="last">Comprovar Execu&ccedil;&atilde;o F&iacute;sica</li>
    </ul>
</div> <!-- final: #breadcrumb -->

<!-- início: #titulo -->
<div id="titulo">
    <div>Comprova&ccedil;&atilde;o de Execu&ccedil;&atilde;o F&iacute;sica do Projeto<span>ID #23A</span> <span class="voltar"><a style="cursor: pointer;" onclick="history.back();">Voltar</a></span></div>
</div>
<!-- final: #titulo -->

<!-- início: área principal #conteudo -->
<div id="conteudo">

    <form action="/NovoSalic/execucaofisicadoprojeto/buscarpronac" method="post" id="formBuscar" name="formBuscar" class="form">
        <table class="tabela" style="font-size: 12px; margin-top: 50px; margin-bottom: 50px; width: 80%;">
            <tbody>
                <tr>
                    <th style="width: 1%;">Pronac</th>
                    <th>Nome do Projeto</th>
                </tr>
                <?php
                    foreach($this->TodosProjetos as $TodosProjetos){
//                        xd($TodosProjetos);
                ?>
                <tr>
                    <td><a href="<?php echo $this->baseUrl(); ?>/comprovarexecucaofisica/relatoriotrimestral/idpronac/<?php echo $TodosProjetos->IdPRONAC ?>"><?php echo $TodosProjetos->AnoProjeto."".$TodosProjetos->Sequencial; ?></a></td>
                    <td><?php echo $TodosProjetos->NomeProjeto ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </form>

</div><!-- final: conteúdo principal #conteudo -->

<!-- início: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />