<script type="text/javascript">
    $(document).ready(function(){
        //PERMITIR SOMENTE NUMEROS PARA O CAMPO EM QUESTAO
        $("input[name='quantidade']").bind("keyup blur focus", function(e) {
            e.preventDefault();
            var expre = /[^0-9]/g;
            // REMOVE OS CARACTERES DA EXPRESSAO ACIMA
            if ($(this).val().match(expre))
                $(this).val($(this).val().replace(expre,''));
        });

        $('.adicionarPlano').click(function(){

            var mensagem = 'Favor preencher os dados obrig&aacute;torios!',
                preenchimento = false;
            $('.obrigatorio').each(function(){
                $(this).css('border-color','#CCC');
                if($.trim($(this).val()) == ''){
                    preenchimento = true;
                    $(this).css('border-color','red');
                }
            });

            if($.trim($('#idAgente').val()) == ''){
                $('#cnpjcpf').css('border-color','red');
                if(preenchimento){
                    mensagem = 'Favor preencher os dados obrig&aacute;torios e cadastrar o Agente.';
                } else {
                    mensagem = 'É necessário cadastrar o Agente!';
                }
                preenchimento = true;
            }

            if(preenchimento) {

                $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html(mensagem);
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            
            } else {

                var vlPatrocinador = $('#quantidade').val(),
                    vlDivulgacao = $('#quantidade').val(),
                    vlBeneficiario = $('#quantidade').val(),
                    id = $('#produto').val();

                if($('#tipoDocumento').val() == 19){
                    $('.qtdPatrocinador'+id).each(function(){
                        if($.trim($(this).val()) != ''){
                            vlPatrocinador = parseInt(vlPatrocinador)+parseInt($(this).val());
                        }
                    });
                    if($('#totalPatrocinador'+id).val() < vlPatrocinador){
                        alertaModal('Ultrapassou a quantidade de Produtos aprovados destinados ao Patrocinador.');
                        return false;
                    }
                } else if($('#tipoDocumento').val() == 20){
                    $('.qtdDivulgacao'+id).each(function(){
                        if($.trim($(this).val()) != ''){
                            vlDivulgacao = parseInt(vlDivulgacao)+parseInt($(this).val());
                        }
                    });
                    if($('#totalDivulgacao'+id).val() < vlDivulgacao){
                        alertaModal('Ultrapassou a quantidade de Produtos aprovados destinados à Divulgação.');
                        return false;
                    }
                } else if($('#tipoDocumento').val() == 21){
                    $('.qtdBeneficiario'+id).each(function(){
                        if($.trim($(this).val()) != ''){
                            vlBeneficiario = parseInt(vlBeneficiario)+parseInt($(this).val());
                        }
                    });
                    if(vlBeneficiario > $('#totalBeneficiario'+id).val()){
                        alertaModal('Ultrapassou a quantidade de Produtos aprovados destinados ao Beneficiário.');
                        return false;
                    }
                }
                $('#formCadastroPlano').submit();
                window.setTimeout("carregandoModal()", 500);
            }
        });

        $('#cnpjcpf').focusout(function(){
            $('#nmAgente').html('');
            $('#idAgente').val('');

            if($('#cnpjcpf').val().length == 14 || $('#cnpjcpf').val().length == 18){
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'buscar-agente'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                    data: {
                        cnpjcpf: $('#cnpjcpf').val()
                    },
                    success: function(data){
                        if(data.resposta){
                            for ( i in data.conteudo){
                                $("#cnpjcpf").addClass('sumir');
                                $("#nmAgente").removeClass('sumir');
                                $('#nmAgente').html(data.conteudo[i].nmAgente);
                                $('#idAgente').val(data.conteudo[i].idAgente);
                            }
                        } else {
                            $('html').css('overflow', 'hidden');
                            $("body").append("<div id='divDinamicaAgentes'></div>");
                            $("#divDinamicaAgentes").html("");
                            $('#divDinamicaAgentes').html("<br><br><center>Carregando dados...</center>");
                            $.ajax({
                                url : '<?php echo $this->url(array('controller' => 'agentes', 'action' => 'incluirbeneficiario')); ?>',
                                data : {
                                    cpf : data.CNPJCPF,
                                    caminho: "",
                                    modal : "s"
                                },
                                success: function(data){
                                    if (data.error) {
                                        $('#divDinamicaAgentes').html(data.msg);
                                    } else {
                                        $('#divDinamicaAgentes').html(data);
                                    }
                                },
                                complete: function(){
                                    $("#resultadoFinalizar").html("");
                                },
                                type : 'post'
                            });

                            $("#divDinamicaAgentes").dialog({
                                resizable: true,
                                width:$(window).width() - 100,
                                height:$(window).height() - 100,
                                modal: true,
                                autoOpen:true,
                                draggable:false,
                                title: 'Cadastrar Beneficiário',
                                buttons: {
                                    'Fechar': function() {
                                        $("#divDinamicaAgentes").remove();
                                        $(this).dialog('close');
                                        $('html').css('overflow', 'auto');
                                        outroAgente();
                                    }
                                }
                            });
                        }
                    },
                    dataType : 'json'
                });

            } else {
                $("#nmAgente").html('');
                $("#nmAgente").addClass('sumir');
                $("#idAgente").val('');
            }
        });

        $('#nmAgente').click(function(){
            $("#idAgente").val('');
            $("#cnpjcpf").removeClass('sumir');
            $("#cnpjcpf").focus();
            $('#nmAgente').html('');
            $('#nmAgente').addClass('sumir');
        });

        $('.btn_excluir').click(function(){
            var id = $(this).attr('idBenPrdCult'),
                arquivo = $(this).attr('idArquivo');
            $("#modalPerguntas").dialog("destroy");
            $("#modalPerguntas").html("Tem certeza que deseja excluir os dados do Plano de Distribuiçao?");
            $("#modalPerguntas").dialog({
                resizable: false,
                title: 'Alerta!',
                width:320,
                height:180,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $("#modalPerguntas").dialog('close');
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'excluir-plano-distribuicao'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                            data: {
                                beneficiario: id,
                                arquivo: arquivo
                            },
                            success: function(data){
                                if(data.resposta){
                                    $("#alerta").dialog("destroy");
                                    $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"></div>');
                                    $("#alerta").dialog({
                                        resizable: false,
                                        width:320,
                                        height:120,
                                        modal: true,
                                        title: 'Carregando..'
                                    });
                                    $('.ui-dialog-titlebar-close').remove();
                                    window.setTimeout('location.reload()', 1000);
                                } else {
                                    alertaModal("Não foi possível excluir o Plano de Distribuição.");
                                }
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });

    });

    function outroAgente(){
        $("#divPerguntaCadastro").dialog('close');
        $("#divPerguntaCadastro").html('Deseja utilizar este agente no cadastro do Plano de Distribuição?');
        $("#divPerguntaCadastro").dialog('open');
        $("#divPerguntaCadastro").dialog({
            resizable: false,
            width: 320,
            height: 180,
            modal: true,
            draggable:false,
            title: 'Alerta!',
            buttons: {
                'Não': function(){
                    $("#idAgente").val('');
                    $('#cnpjcpf').val('');
                    $('#cnpjcpf').focus();
                    $("#divPerguntaCadastro").dialog('close');
                },
                'Sim': function() {
                    $("#divPerguntaCadastro").dialog('close');
                    $('#cnpjcpf').focusout();
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }

    function alertaModal(msg){
        $("#alerta").dialog("destroy");
        $("#alerta").html(msg);
        $("#alerta").dialog({
            resizable: false,
            title: 'Alerta!',
            width:330,
            height:170,
            modal: true,
            buttons : {
                'OK' : function(){
                    $(this).dialog('close');
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }

    function carregandoModal(){
        $("#alerta").dialog("destroy");
        $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"></div>');
        $("#alerta").dialog({
            resizable: false,
            width:320,
            height:120,
            modal: true,
            title: 'Carregando..'
        });
        $('.ui-dialog-titlebar-close').remove();
    }
</script>

<?php require_once "scripts/comprovarexecucaofisica/inc/menu-cadastro.php"; ?>
<div id="alerta" class="sumir"></div>
<div id="modalPerguntas" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>
<div id="divPerguntaCadastro" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Consultar dados do Projeto">Consultar dados do Projeto</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/comprovarexecucaofisica/relatoriotrimestral/idpronac/<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Relat&oacute;rio Trimestral">Relat&oacute;rio Trimestral</a></li>
        <li class="last">Plano de Distribuição</li>
    </ul>
</div>


<div id="titulo">
    <div>Plano de Distribuição <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/comprovarexecucaofisica/relatoriotrimestral/idpronac/<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <th colspan="4">Comprovar Distribuição de Produto</th>
        </tr>
        <tr align="center">
            <td class="destacar bold">Produto</td>
            <td class="destacar bold">Patrocionador</td>
            <td class="destacar bold">Divulgação</td>
            <td class="destacar bold">População de Baixa Renda</td>
        </tr>
        <?php foreach ($this->PlanoDeDistribuicao as $PlanoDeDistribuicao) { ?>
        <tr>
            <td><?php echo $PlanoDeDistribuicao->Produto; ?></td>
            <td align="right">
                <input type="hidden" id="totalPatrocinador<?php echo $PlanoDeDistribuicao->idPlanoDistribuicao; ?>" value="<?php echo $PlanoDeDistribuicao->QtdePatrocinador; ?>">
                <?php echo $PlanoDeDistribuicao->QtdePatrocinador; ?>
            </td>
            <td align="right">
                <input type="hidden" id="totalDivulgacao<?php echo $PlanoDeDistribuicao->idPlanoDistribuicao; ?>" value="<?php echo $PlanoDeDistribuicao->QtdeProponente; ?>">
                <?php echo $PlanoDeDistribuicao->QtdeProponente; ?>
            </td>
            <td align="right">
                <input type="hidden" id="totalBeneficiario<?php echo $PlanoDeDistribuicao->idPlanoDistribuicao; ?>" value="<?php echo $PlanoDeDistribuicao->QtdeOutros; ?>">
                <?php echo $PlanoDeDistribuicao->QtdeOutros; ?>
            </td>
        </tr>
        <?php } ?>
    </table>
    
    <br clear="all" />

    <form id="formCadastroPlano" action="<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'cadastrar-plano-distribuicao'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" method="post" enctype="multipart/form-data">
        <table class="tabela">
            <tr align="center">
                <td class="destacar bold">Produto</td>
                <td class="destacar bold">Beneficiário do Produto Cultural</td>
                <td class="destacar bold">CNPJ/CPF</td>
                <td class="destacar bold">Quantidade</td>
                <td class="destacar bold">Arquivo</td>
                <td class="destacar bold">&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples obrigatorio" id="produto" name="produto">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->PlanoDeDistribuicao as $PlanoDeDistribuicao) { ?>
                        <option value="<?php echo $PlanoDeDistribuicao->idPlanoDistribuicao; ?>"><?php echo $PlanoDeDistribuicao->Produto; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td>
                    <select class="select_simples obrigatorio" id="tipoDocumento" name="tipoDocumento">
                        <option value=""> - Selecione - </option>
                        <option value="19">Patrocinador</option>
                        <option value="20">Divulgação</option>
                        <option value="21">População de Baixa Renda</option>
                    </select>
                </td>
                <td align="center">
                    <input maxlength="18" onkeydown="mascaraCnpjCpf(this);" onkeypress="mascaraCnpjCpf(this);" onkeyup="mascaraCnpjCpf(this);" type="text" name="cnpjcpf" id="cnpjcpf" class="input_simples obrigatorio">
                    <input type="hidden" id="idAgente" name="idAgente">
                    <span id="nmAgente" class="sumir" style="cursor: pointer; text-decoration: underline;"></span>
                </td>
                <td align="center"><input type="text" class="input_simples obrigatorio" id="quantidade" name="quantidade" maxlength="9"></td>
                <td><input type="file" id="arquivo" name="arquivo" class="obrigatorio"></td>
                <td><a href="#" class="adicionarPlano"><img src="<?php echo $this->baseUrl(); ?>/public/img/buttons/novo-p.gif" alt="adicionar" /></a></td>
            </tr>
        </table>
    </form>

    <br clear="all" />

    <?php if(count($this->PlanosCadastrados)>0) { ?>
    <table class="tabela">
        <tr align="center">
            <th colspan="7">Beneficiários de Produto Cultural</th>
        </tr>
        <tr align="center">
            <td class="destacar bold">Produto</td>
            <td class="destacar bold">Tipo Beneficiário</td>
            <td class="destacar bold">CNPJ/CPF</td>
            <td class="destacar bold">Nome</td>
            <td class="destacar bold">Quantidade</td>
            <td class="destacar bold">Arquivo</td>
            <td class="destacar bold" width="1%">Ação</td>
        </tr>
        <?php foreach ($this->PlanosCadastrados as $PlanosCadastrados) { ?>
        <tr>
            <td><?php echo $PlanosCadastrados->Produto; ?></td>
            <td>
                <?php
                    if($PlanosCadastrados->idTipoBeneficiario == 19){
                        echo 'Patrocinador';
                        $classNomeCampo = 'qtdPatrocinador'.$PlanosCadastrados->idPlanoDistribuicao;
                    } else if($PlanosCadastrados->idTipoBeneficiario == 20){
                        echo 'Divulgação';
                        $classNomeCampo = 'qtdDivulgacao'.$PlanosCadastrados->idPlanoDistribuicao;
                    } else {
                        echo 'Beneficiário';
                        $classNomeCampo = 'qtdBeneficiario'.$PlanosCadastrados->idPlanoDistribuicao;
                    }
                ?>
            </td>
            <td align="center"><?php echo (strlen($PlanosCadastrados->CNPJCPF)==11) ? Mascara::addMaskCPF($PlanosCadastrados->CNPJCPF) : Mascara::addMaskCNPJ($PlanosCadastrados->CNPJCPF); ?></td>
            <td><?php echo $PlanosCadastrados->Beneficiario; ?></td>
            <td align="right"><?php echo $PlanosCadastrados->qtRecebida; ?><input type="hidden" class="<?php echo $classNomeCampo; ?>" value="<?php echo $PlanosCadastrados->qtRecebida; ?>"></td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $PlanosCadastrados->idArquivo; ?>"><?php echo $PlanosCadastrados->nmArquivo; ?></a></td>
            <td align="center">
                <input type="button" value=" " class="btn_excluir" idBenPrdCult="<?php echo $PlanosCadastrados->idBeneficiarioProdutoCultural; ?>" idArquivo="<?php echo $PlanosCadastrados->idArquivo; ?>"/>
            </td>
        </tr>
        <?php } ?>
    </table>
    <br clear="all" />
    <?php } ?>

</div>

<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
