<?php
/**
 * Alterar proponente
 * @author Equipe RUP - Politec
 * @since 15/01/2011
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.alterarprojeto
 * @copyright (c) 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

include_once 'scripts/alterarprojeto/inc/menu.inc.php';
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para p&aacute;gina inicial">Início</a></li>
        <li><!--a href="<?php echo $this->baseUrl(); ?>" title="Início"-->Manuten&ccedil;&atilde;o<!--/a--></li>
        <li><a href="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'consultarprojeto')); ?>" title="Ir para alterar projeto">Alterar projeto</a></li>
        <li class="last">Alterar proponente</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== BUTTON VOLTAR ========== -->
<div id="titulo">
    <div>Alterar proponente <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== GRID NOME DA PROPOSTA ========== -->
<script type="text/javascript">
    $(document).ready( function() {
       	$("#formularioAtualiza").validate({
            // Define as regras
            rules:{
                nome:{
                    // campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
                    required: true
                },
                justificativa:{
                    // campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
                    required: true
                }
            },
            // Define as mensagens de erro para cada regra
            messages:{
                nome:{
                    required: "<br>Informe um Agente cadastrado"
                },
                justificativa:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                }
            }
        });

        mascaraCnpjCpf(document.getElementById('cpfocuto'));
        setTimeout("formatacpf()", 10);
    });

    function formatacpf(){
        //document.getElementById('escrevecpf').innerHTML = document.getElementById('cpfocuto').value;
    }

    function abrir_fechar(id_div){
        $('#'+id_div).slideToggle(400);
        $('#maiss'+id_div).toggle().focus();
        $('#menoss'+id_div).toggle().focus();
    }
    function buscaAgente(){
        var cpf = $("#CGCCPF").val();
        if(cpf.length >= 14){
            $("#AgenteERROR").html('Buscando Agente');
            var url = '<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'buscaragente'));?>';
            url = url +'?cpf='+$('#CGCCPF').val() +'&cpfatual='+$('#cpfocuto').val();
            //funcao responsavel acessar a url via ajax e retornar os dados para o local indicado
            jqAjaxLinkSemLoading(url, "", "AgenteERROR");
        }

    }
</script>

<div id="conteudo">
    <form name="formularioAtualiza" id="formularioAtualiza" method="post" action="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'salvaalterarprojeto')); ?>" >
        <input type="hidden" name="pronac" value="<?php echo $this->parecer->pronac ?>" />
        <input type="hidden" name="pagina" value="proponente" />
        <table class="tabela">
            <tr>
                <th colspan="2" class="centro">Identifica&ccedil;&atilde;o</th>
            </tr>
            <tr class="destacar centro bold">
                <td width="200">PRONAC</td>
                <td>Nome do Projeto</td>
            </tr>
            <tr>
                <td align="center"><?php echo $this->parecer->pronac; ?></td>
                <td align="center"><?php echo $this->parecer->NomeProjeto; ?></td>
            </tr>
            <tr class="destacar centro bold">
                <td>CNPJ / CPF</td>
                <td>Proponente</td>
            </tr>
            <tr>
                <td align="center"><input type="hidden" id="cpfocuto" value="<?php echo ($this->parecer->CgcCpf) ?>" /><?php echo strlen($this->parecer->CgcCpf) == 11 ? Mascara::addMaskCPF($this->parecer->CgcCpf) : Mascara::addMaskCNPJ($this->parecer->CgcCpf); ?></td>
                <td align="center"><?php echo $this->agente ?></td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td class="destacar bold" align="right" width="200">CNPJ / CPF</td>
                <td>
                    <input type="text" class="input_simples w150" name="CGCCPF" id="CGCCPF" onchange="buscaAgente()" onblur="mascaraCnpjCpf(this)" onkeyup="buscaAgente(); mascaraCnpjCpf(this)">
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right" width="200">Novo Proponente</td>
                <td>
                    <div id="AgenteERROR" style="width:400px;"><input type='hidden' name='nome' id='nome' value='' /></div>
                </td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <th>Justificativa<span style="color: red;">*</span></th>
            </tr>
            <tr>
                <td align="center">
                    <textarea class="textarea_simples h100" style="width:99%" id="justificativa" obrigatorio="1" name="justificativa"></textarea>
                </td>
            </tr>
            <tr>
                <td class="centro">

                    <table class="tabela">
                        <tr>
                            <td class="esquerda"><input type="button" class="btn_adicionar" value=" " title="Expandir" onclick="return abrir_fechar('lista')" onkeypress="return abrir_fechar('lista')" /> Anexar Documentos</td>
                        </tr>
                    </table>

                    <div id="lista">
                        <input type="hidden" name="excuir[]" id="excuir" value="" />
                        <table class="tabela">
                            <tbody id="tabelaArquivos">
                                <tr class="titulo_tabela" >
                                    <th>Tipo Documento</th>
                                    <th>Data</th>
                                    <th>Classifica&ccedil;&atilde;o</th>
                                    <th>Documento</th>
                                    <th>A&ccedil;&atilde;o</th>
                                </tr>
                                <?php foreach($this->documentos as $doc) { ?>
                                <tr>
                                    <td><?php echo !empty($doc->AgenteDoc) ? 'Proponente' : 'Projeto' ?></td>
                                    <td><?php echo date("d/m/Y H:i:s",strtotime($doc->dtHistoricoAlteracaoProjeto)) ?></td>
                                    <td><?php echo $doc->Descricao ?></td>
                                    <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $doc->idArquivo; ?>" title="Abrir arquivo"><?php echo $doc->nmArquivo ?></a></td>
                                    <td>&nbsp;</td>
                                </tr>
                                    <?php } ?>
                            </tbody>
                        </table>

                        <table class="tabela" >
                            <tr>
                                <td class="direita">
                                    <input class="btn_incluir" id="btn_incluir" value=" " type="button" title="Incluir" onclick="EnviarArquivo()" />
                                </td>
                            </tr>
                        </table>

                    </div>
                </td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td class="centro">
                    <input class="btn_salvar" id="btn_salvar" value=" " type="submit" title="Salvar" />
                </td>
            </tr>
        </table>
    </form>
</div>


<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />
<iframe name="enviar_arquivo" id="enviar_arquivo" style="height: 20px; display: none;"></iframe>