<?php
/**
 * Alterar situacao
 * @author Equipe RUP - Politec
 * @since 15/01/2011
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.alterarprojeto
 * @copyright (c) 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
$menuX = !empty($_GET['menu']) ? $_GET['menu'] : 0;
if ($menuX != 1) {
    include_once 'scripts/alterarprojeto/inc/menu.inc.php';
}
//xd('aa');
//require_once 'scripts/alterarprojeto/inc/menu.inc.php';
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para p&aacute;gina inicial">Início</a></li>
        <li><!--a href="<?php echo $this->baseUrl(); ?>" title="Início"-->Manuten&ccedil;&atilde;o<!--/a--></li>
        <li><a href="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'consultarprojeto')); ?>" title="Ir para alterar projeto">Alterar projeto</a></li>
        <li class="last">Alterar situa&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== BUTTON VOLTAR ========== -->
<div id="titulo">
    <div>Alterar situa&ccedil;&atilde;o <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== GRID NOME DA PROPOSTA ========== -->
<script type="text/javascript">
    $(document).ready( function() {
        $("#formularioAtualiza").validate({
            // Define as regras
            rules:{
                Situacao:{
                    // campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
                    required: true
                },
                justificativa:{
                    // campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
                    required: true
                }
            },
            // Define as mensagens de erro para cada regra
            messages:{
                Situacao:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                },
                justificativa:{
                    required: "<br>Dados obrigatórios n&atilde;o informados"
                }
            }
        });
    });

    function abrir_fechar(id_div){
        $('#'+id_div).slideToggle(400);
        $('#maiss'+id_div).toggle().focus();
        $('#menoss'+id_div).toggle().focus();
    }
</script>

<div id="conteudo">
    <form name="formularioAtualiza" id="formularioAtualiza" method="post" action="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'salvaalterarprojeto')); ?>">
        <input type="hidden" name="pronac" value="<?php echo $this->pronac ?>" />
        <input type="hidden" name="pagina" value="situacao" />
        <table class="tabela">
            <tr>
                <th colspan="2" class="centro">Identifica&ccedil;&atilde;o</th>
            </tr>
            <tr class="destacar centro bold">
                <td width="200">PRONAC</td>
                <td>Nome do Projeto</td>
            </tr>
            <tr>
                <td align="center"><?php echo $this->parecer->pronac; ?></td>
                <td align="center"><?php echo $this->parecer->NomeProjeto; ?></td>
            </tr>
            <tr class="destacar centro bold">
                <td>Data Situa&ccedil;&atilde;o Atual</td>
                <td>Situa&ccedil;&atilde;o Atual</td>
            </tr>
            <tr>
                <td align="center"><?php echo ConverteData(strtotime($this->parecer->DtSituacao),5) ?></td>
                <td align="center"><?php echo $this->parecer->Situacao." - ".$this->parecer->dsSituacao ?></td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td width="200" class="destacar bold" align="right">Nova Situa&ccedil;&atilde;o</td>
                <td>
                    <select class="select_simples" obrigatorio="1" name="Situacao" id="Situacao">
                        <?php foreach ($this->situacao as $situacao) {
                            if($situacao->StatusProjeto == 1) {
                                echo '<option value="'.$situacao->Codigo.' "';
                                if($situacao->Codigo == $this->parecer->Situacao) {
                                    echo 'selected="selected"';
                                }
                                echo '">'.$situacao->Codigo.' - '.$situacao->Descricao.'</option>';
                            }
                        }
                        ?>
                    </select>
                </td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <th>Providência Tomada<span style="color: red;">*</span></th>
            </tr>
            <tr>
                <td>
                    <?php if(isset($this->parecer->ProvidenciaTomada)){ $nrCaracteres = strlen($this->parecer->ProvidenciaTomada); } ?>
                    <textarea class="textarea_simples h100" style="width:99%" id="justificativa" obrigatorio="1" name="justificativa" <?php echo $this->contadorTextarea('form.justificativa', 'form.exibirContadorTextarea', 1000); ?>><?php echo isset($this->parecer->ProvidenciaTomada) ? $this->parecer->ProvidenciaTomada: ''; ?></textarea>
                    <span style="clear:both;"><?php echo $this->exibirContadorTextarea('exibirContadorTextarea', 3, 1000, $nrCaracteres, '25px'); ?></span>
                    <input type="hidden" value="<?php echo $menuX ; ?>" name="menu" />
                </td>
            </tr>
            <?php if($menuX == 0) { ?>
            <tr>
                <td class="centro">

                    <table class="tabela">
                        <tr>
                            <td class="esquerda"><input type="button" class="btn_adicionar" title="Expandir" value=" " onclick="return abrir_fechar('lista')" onkeypress="return abrir_fechar('lista')" /> Anexar Documentos</td>
                        </tr>
                    </table>

                    <div id="lista">
                        <input type="hidden" name="excuir[]" id="excuir" value="" />
                        <table class="tabela">
                            <tbody id="tabelaArquivos">
                                <tr class="titulo_tabela" >
                                    <th>Tipo Documento</th>
                                    <th>Data</th>
                                    <th>Classifica&ccedil;&atilde;o</th>
                                    <th>Documento</th>
                                    <th>A&ccedil;&atilde;o</th>
                                </tr>
                                <?php foreach($this->documentos as $doc) { ?>
                                <tr>
                                    <td><?php echo !empty($doc->AgenteDoc) ? 'Proponente' : 'Projeto' ?></td>
                                    <td><?php echo date("d/m/Y H:i:s",strtotime($doc->dtHistoricoAlteracaoProjeto)) ?></td>
                                    <td><?php echo $doc->Descricao ?></td>
                                    <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $doc->idArquivo; ?>"><?php echo $doc->nmArquivo ?></a></td>
                                    <td>&nbsp;</td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>

                        <table class="tabela" >
                            <tr>
                                <td class="direita">
                                    <input class="btn_incluir" id="btn_incluir" title="Incluir" value=" " type="button" onclick="EnviarArquivo()"/>
                                </td>
                            </tr>
                        </table>

                    </div>
                </td>
            </tr>
                <?php } ?>
        </table>

        <table class="tabela">
            <tr>
                <td class="centro">
                    <input class="btn_salvar" id="btn_salvar" value="" type="submit" title="Salvar" />
                    <input type="button" class="btn_imprimir" id="btn_imprimir" onclick="window.open('<?php echo $this->baseUrl(); ?>/alterarprojeto/imprimirsituacao?pronac=<?php echo $this->parecer->pronac; ?>')"/>
                </td>
            </tr>
        </table>

    </form>
</div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />
<iframe name="enviar_arquivo" id="enviar_arquivo" style="height: 20px; display: none;"></iframe>