<?php //header("Content-Type: text/html; charset=ISO-8859-1"); ?>
<script type="text/javascript">
        $(document).ready(function(){
         $('#vlunitario').priceFormat({limit: 8});
        //$("#vlunitario").val(format_moeda($("#vlunitario").val()));
       <?php if(isset($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
             //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
             JSBloquearAlteracaoFormulario();
        <?php endif; ?>
        
        $('.soma').keyup(function(){
            var soma = 0;
            var vlunitario = $("#vlunitario").val().replace('R$','');
            vlunitario = $.trim(vlunitario.replace('.',''));
            vlunitario = vlunitario.replace(',','.');
            vlunitario = new Number(vlunitario);
            var qtd = new Number($("#qtd").val());
            var ocorrencia = new Number($("#ocorrencia").val());
            soma = qtd*ocorrencia*vlunitario;
            soma = soma.toFixed(2);
            $("#total").val('R$ ' + soma).priceFormat({
                limit:10,
                centsLimit: 2
            });
        });

        if($("#total").val() == 'R$ NaN'){
			alert("Valores Invalidos");
        }

        if($('#uf').val() != '' &&  $('#municipio').val() != '' && $('#item').val() != '' && $('#etapa').val() != '' ){
            //$('#uf').attr('disabled','disabled');
            //$('#municipio').attr('disabled','disabled');
            $('#item').attr('disabled','disabled');
            $('#etapa').attr('disabled','disabled');

        }

        $('.numero').keydown(function(event){
            //		var texto = '';
            //		 for(j in event){
            //			 texto += j+' = '+event[j]+' | ';
            //				}
            //
            //		alert(texto);return false;
            if((event.keyCode >= 96 && event.keyCode <= 105) || (event.keyCode >= 48 && event.keyCode <= 57) || event.keyCode == 8 || event.keyCode ==9 ){
                return true;
            }
            else
                return false;
            //$(this).val($(this).val().replace(/\D/g,''));
        });

        $("#error").dialog({
            resizable: true,
            width:450,
            height:150,
            modal: true,
            autoOpen:false,
            buttons: {
                'OK': function() {
                    $(this).dialog('close');
                }
            }
        });
        $('.btn_salvar').click(function(){
            var validar = true;
            $('.valida').each(function(){
                if($(this).val() == ''){
                    validar = false;
                }
            });
    
            if(validar == false){
                $("#error").html('Dados obrigat&oacute;rios n&atilde;o informados!');
                $("#error").dialog('open');
            
            } else {
                var jstv = $('#editor1').val();
                if(jstv.length > 500){
                    $("#justificativaErro").dialog("destroy");
                    $("#justificativaErro").html('O campo Justificativa não pode ultrapassar 500 caracteres!');
                    $("#justificativaErro").dialog ({
                        width:320,
                        height:180,
                        title:'Alerta!',
                        draggable:true,
                        EscClose:true,
                        modal:true,
                        buttons: {
                            'Ok': function() {
                                $(this).dialog('close');
                            }
                        }
                    });
                    return false;
                }

                $("#msg").dialog("destroy");
                $("#msg").html("Carregando...");
                $.ajax({
                    url : $("#form").attr('action'),
                    type: "POST",
                    async: false,
                    data : $("#form").serialize(),
                    success: function(valor){
                        $("#msg").html(valor);
                    }
                });
                $("#msg").dialog({
                    width:400,
                    height:160,
                    draggable:true,
                    EscClose:true,
                    modal:true,
                    buttons: {
                        'OK': function() {
                            $("#form").dialog("destroy");
                            window.location.reload();
                        }
                    }
                });
            }
        });

        $('#uf').change(function(){
            if($(this).val() == 0){
                $("#municipio").find('option').remove();
                $("#municipio").append('<option value=""> - Selecione - </option>');
            }
            else{
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'Manterorcamento', 'action' => 'cadastrarprodutos')); ?>',
                    type: "POST",
                    data :{
                        iduf : $(this).val(),
                        idPreProjeto : <?php echo $this->idPreProjeto;?>
                    },
                    success: function(valor){
                        $("#municipio").find('option').remove();
                        $("#municipio").append('<option value=""> - Selecione - </option>');

                        for(a in valor){
                            $("#municipio").append('<option value="'+valor[a].idCidade+'">'+valor[a].nomeCidade+'</option>');
                        }
                    }
                    , dataType : 'json'
                });
            }
        });
        $('#etapa').change(function(){
            if($(this).val() == 0){
                $("#item").find('option').remove();
                $("#item").append('<option value=""> - Selecione - </option>');
            }
            else{
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'Manterorcamento', 'action' => 'cadastrarprodutos')); ?>',
                    type: "POST",
                    data :{
                        idetapa : $(this).val(),
                        idPreProjeto : <?php echo $this->idPreProjeto;?>
                    },
                    success: function(valor){
                        $("#item").find('option').remove();
                        $("#item").append('<option value=""> - Selecione - </option>');

                        for(a in valor){
                            $("#item").append('<option value="'+valor[a].idItem+'">'+valor[a].nomeItem+'</option>');
                        }
                    }
                    , dataType : 'json'
                });
            }
        });

    somaValores();
    });

    function somaValores(){
        var soma = 0;
        var vlunitario = $("#vlunitario").val().replace('R$','');
        var vlunitario = $.trim(vlunitario.replace('.',''));
        var vlunitario = $.trim(vlunitario.replace(',','.'));
        soma = parseFloat($("#qtd").val() * $("#ocorrencia").val() * vlunitario);
        soma = format_moeda(soma.toFixed(2).replace('.',','));
        $("#total").val(soma);
    }

    function Limpar(valor, validos) {
        // retira caracteres invalidos da string
        var result = "";
        var aux;
        for (var i=0; i < valor.length; i++) {
            aux = validos.indexOf(valor.substring(i, i+1));
            if (aux>=0) {
                result += aux;
            }
        }
        return result;
    }

    //Formata número tipo moeda usando o evento onKeyDown
    function Formata(campo,tammax,teclapres,decimal) {
        var tecla = teclapres.keyCode;
        vr = Limpar(campo.value,"0123456789");
        tam = vr.length;
        dec=decimal

        if (tam < tammax && tecla != 8){ tam = vr.length + 1 ; }
        if (tecla == 8 ) { tam = tam - 1 ; }
        if ( tecla == 8 || tecla >= 48 && tecla <= 57 || tecla >= 96 && tecla <= 105 )
        {
            if ( tam <= dec ) { campo.value = vr ; }
            if ( (tam > dec) && (tam <= 5) ){
                campo.value = vr.substr( 0, tam - 2 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 6) && (tam <= 8) ){
                campo.value = vr.substr( 0, tam - 5 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ;
            }
            if ( (tam >= 9) && (tam <= 11) ){
                campo.value = vr.substr( 0, tam - 8 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 12) && (tam <= 14) ){
                campo.value = vr.substr( 0, tam - 11 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 15) && (tam <= 17) ){
                campo.value = vr.substr( 0, tam - 14 ) + "." + vr.substr( tam - 14, 3 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - 2, tam ) ;}
        }
    }
</script>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php
//require_once "scripts/manterpropostaincentivofiscal/inc/menu.inc.php"; // menu
?>
<body>
    <!-- ========== INCIO BREADCRUMB (LINKS TOPO) ========== -->
    <!--
    <div id="breadcrumb">
        
        <ul>
            <li class="first"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'propostas')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
            <li class="last">Or&ccedil;amento</li>
            <li class="first"><a href="<?php echo $this->url(array('controller' => 'manterorcamento', 'action' => 'produtoscadastrados')); ?>" title="Ir para In&iacute;cio">Produtos Cadastrados</a></li>
            <li class="last">Cadastrar Planilha por Produto</li>
        </ul>
    </div>
    -->
    <!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

    <!-- ========== INCIO TTULO ========== -->
    <div id="titulo" style="width: 97%;">
        <div>Cadastrar Planilha por Produto</div>
    </div>

    <div id='error'></div>
    <div id='justificativaErro' class="sumir"></div>
    <div id="msg" class="sumir"></div>
    <!-- ========== FIM TTULO ========== -->
    <!-- ========== INCIO CONTEDO ========== -->
    <div id="conteudo" style="width: 97%;"><!-- ========== INCIO TABELA DADOS ========== -->
        <?php foreach ($this->Dados as $dados):?>
        <form name="form" id="form" action='<?php echo $this->url(array('controller' => 'manterorcamento', 'action' => 'editarprodutos')); ?>' method='post'>
            <input type="hidden" name="produto" id="produto" value="<?php echo $dados->CodigoProduto ?>">
            <input type="hidden" name="proposta" id="proposta" value="<?php echo $dados->idPlanilhaProposta ?>">
            <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto ?>">
            <!-- <input type="hidden" name="idPlanilhaProposta" id="idPlanilhaProposta" value="<?php // echo $this->Item[0]->idPlanilhaProposta ?>"> -->
            <div style="float: left; width: 25%">
                <fieldset>
                    <legend>Despesas</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify">
                                <label for="uf">FONTE DE RECURSO*:</label> <br />
                                <select class="select_simples valida" style="width: 90%" id="fonterecurso" name='fonterecurso'>
                                    <option value=""> - Selecione - </option>
                                        <?php foreach($this->Recurso as $recursos) {
                                            if ($dados->Recurso == $recursos->idVerificacao) { ?>
                                    <option selected="selected" value="<?php echo $recursos->idVerificacao ?>"><?php echo utf8_encode($recursos->VerificacaoDescricao); ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $recursos->idVerificacao ?>"><?php echo utf8_encode($recursos->VerificacaoDescricao); ?></option>
                                                <?php }
                                        }
                                        ?>
                                </select>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>
            <div style="float: left; width: 40%">
                <fieldset>
                    <legend>Localiza&ccedil;&atilde;o</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify" width="20%">
                                <label for="uf">UF*</label> <br />
                                <input type="hidden" name="uf" value="<?php echo $dados->IdUf; ?>"/>
                                <select class="select_simples valida" id='uf' name='uf'>
                                    <option> - Selecione - </option>
                                        <?php foreach($this->Estados as $estados) {
                                            if($dados->IdUf == $estados->id) {?>
                                    <option selected="selected" value="<?php echo $estados->id ?>"><?php echo $estados->descricao ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $estados->id ?>"><?php echo $estados->descricao ?></option>
                                                <?php }
                                        }
                                        ?>
                                </select>
                            </td>
                            <td align="left">
                                <label for="cidade">MUNIC&Iacute;PIO*</label><br />
                                <input type="hidden" name="municipio" value="<?php echo $dados->Municipio; ?>"/>
                                <select class="select_simples valida" style="width: 80%" id='municipio' name='municipio'>
                                    <option> - Selecione - </option>
                                        <?php foreach($this->Cidades as $cidades) {
                                            if($dados->Municipio == $cidades->id) {?>
                                    <option selected="selected" value="<?php echo $cidades->id ?>"><?php echo utf8_encode($cidades->descricao); ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $cidades->id ?>"><?php echo utf8_encode($cidades->descricao); ?></option>
                                                <?php }
                                        }
                                        ?>
                                </select>
                            </td>
                            <!--
                            <td align="center">
                                <br />
                                <label><input type="button" class="btn_alterar" id='alterarlocalidade'></label>
                            </td>
                            -->
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 34%">
                <fieldset>
                    <legend>Etapa / Meta</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify" width="20%">
                                <label for="etapa">ETAPA / META*</label> <br />
                                <input type="hidden" name="etapa" value="<?php echo $dados->idEtapa; ?>"/>
                                <select class="select_simples valida" id='etapa' name='etapa'>
                                    <option value="<?php echo "" ?>"> - Selecione - </option>

                                        <?php foreach($this->Etapa as $etapa) {
                                            if ($dados->idEtapa == $etapa->idplanilhaetapa) { ?>
                                    <option selected="selected" value="<?php echo $etapa->idplanilhaetapa ?>"><?php echo utf8_encode($etapa->Descricao); ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $etapa->idplanilhaetapa ?>"><?php echo utf8_encode($etapa->Descricao); ?></option>
                                                <?php }
                                        }
                                        ?>
                                </select>
                            </td>
                            <td align="left">
                                <label for="item">ITEM*</label><br />
                                <input type="hidden" name="item" value="<?php echo $dados->idItem; ?>"/>
                                <select class="select_simples valida" style="width: 80%" id='item' name='item'>
                                    <option value="<?php echo "" ?>"> - Selecione - </option>
                                        <?php foreach($this->Item as $itens) {
                                            if ($dados->idItem == $itens->idPlanilhaItens) { ?>
                                    <option selected="selected" value="<?php echo $itens->idPlanilhaItens ?>"><?php echo $itens->Descricao ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $itens->idPlanilhaItens ?>"><?php echo $itens->Descricao ?></option>
                                                <?php }

                                        }
                                        ?>
                                </select>
                            </td>
                            <!--
                            <td align="center">
                                <br />
                                <label><input type="button" class="btn_alterar" id='alteraretapa'></label>
                            </td>
                            -->
                        </tr>
                    </table>
                </fieldset>
            </div>

            
            <div style="float: left; width: 37%">
                <fieldset>
                    <legend>Indicadores F&iacute;sicos</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr align="left" lang="">
                            <td>
                                <label for="uf">UNIDADE*</label> <br />
                                <select class="select_simples valida" id="unidade" name='unidade'>
                                    <option value="<?php echo "" ?>"> - Selecione - </option>
                                        <?php foreach($this->Unidade as $unidades) {
                                            if ($dados->Unidade == $unidades->idUnidade) { ?>
                                    <option selected="selected" value="<?php echo $unidades->idUnidade ?>"><?php echo utf8_encode($unidades->Descricao); ?></option>
                                                <?php } else { ?>
                                    <option value="<?php echo $unidades->idUnidade ?>"><?php echo utf8_encode($unidades->Descricao); ?></option>
                                                <?php }
                                        }
                                        ?>
                                </select>
                            </td>
                            <td>
                                <label for="qtd">QTD*</label><br />
                                <input type="text" class="input_simples valida soma numero" size="3" 
                                id="qtd" maxlength="10" name="qtd"  value="<?php echo (int) $dados->Quantidade?>">


                            </td>
                            <td>
                                <label for="ocorrencia">OCORR&Ecirc;NCIA*</label><br />
                                <input type="text" maxlength="4" class="input_simples valida soma numero" size="3" id="ocorrencia" maxlength="10" name="ocorrencia" value="<?php echo (int) $dados->Ocorrencia?>">

                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>
            <div style="float: left; width: 37%" >
                <fieldset>
                    <legend>Indicadores Financeiros</legend>
                    <table cellpadding="0" cellspacing="0" width="100%" id="indicadores" >
                        <tr>
                            <td nowrap align="left">
                                <label for="uf">VALOR UNIT&Aacute;RIO*</label> <br />
                                <input type="text" maxlength="13" class="input_simples valida soma numero" size="10" id="vlunitario" name="vlunitario" value="<?php echo $dados->ValorUnitario?>">
                            </td>
                            <td nowrap align="left">
                                <label for="uf">&nbsp;&nbsp;&nbsp;&nbsp;TOTAL*</label> <br />
                                <b>R$</b><input type="text" value="" maxlength="6" class="input_simples valida" size="15" name="total" id="total" readonly="readonly">
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 25%">
                <fieldset>
                    <legend>Tempo de Dura&ccedil;&atilde;o</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify">
                                <label for="uf">QTD DE DIAS*</label> <br />
                                <input type="text" maxlength="8" class="input_simples valida numero" size="15" value="<?php echo $dados->QtdDias?>" name='qtdDias' id='qtdDias' />
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 99%">
                <fieldset>
                    <legend>Detalhamento / Justificativa / Observa&ccedil;&otilde;es</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify">
                                <textarea cols="80" id="editor1" class="valida" name="editor1" rows="7" class="textarea_simples" style="width:99%;"><?php echo $dados->Justificativa; ?></textarea>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>
        </form>

        <table class="tabela" cellpadding="0" cellspacing="0">
            <tr>
                <td align="center">
                    <input type="button" class="btn_salvar">&nbsp;
                    <!--<input type="button" id="btn_sair" name="sair" style="width: 88px" class="btn_sair" onclick="voltar()">-->
                </td>
            </tr>
        </table>
        <?php endforeach;?>

    </div>
    <!-- ========== FIM CONTEDO ========== --> <!-- ========== INCIO RODAP DO CONTEDO ========== -->
    <div id="rodapeConteudo"><span></span></div>
    <!-- ========== FIM RODAP DO CONTEDO ========== --> <br clear="all" />
</body>
