<script type="text/javascript">
    $(document).ready(function(){
        $("#formaprovacao").validate({
            // Define as regras
            rules:{
                justificativa:{
                    required: true
                }
            },
            messages:{
                justificativa:{
                    required:  "Favor preencher a justificativa de envio da procura&ccedil;&atilde;o!"
                }
            },
            submitHandler: function(form) {
                form.submit(); 
            }
        });
    });

    function aprovacao(idDocumento, tipoaprovacao) {
        var msg = "";
        if(tipoaprovacao == 1) {
            msg = "Deseja aprovar a procuração?";
            $("#situacao").val("1");
        } else {
            msg = "Deseja rejeitar a procuração?";
            $("#situacao").val("0");
        }

        if($('#justificativa').val().length > 300){
            $("#error").html('O campo justificativa deve ter no máximo 300 caracteres.');
            $("#error").dialog({
                resizable: true,
                width:320,
                height:180,
                modal: true,
                autoOpen:false,
                closeOnEscape : false,
                title : 'Alerta!',
                buttons: {
                    'Ok': function() {
                        $("#error").dialog('close');
                    }
                }
            });
            $("#error").dialog('open');
        } else {
            $("#confirm").html(msg);
            $("#confirm").dialog({
                resizable: true,
                width:320,
                height:160,
                modal: true,
                autoOpen:false,
                closeOnEscape : false,
                title : 'Alerta!',
                buttons: {
                    'Não': function() {
                        $("#confirm").dialog('close');
                    },
                    'Sim': function() {
                        $("#confirm").dialog('close');
                        $("#formaprovacao").submit();
                    }
                }
            });
            $("#confirm").dialog('open');
        }
    }
</script>
<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'procuracao', 'action' => 'analisar')); ?>" title="Ir para Início">Início</a></li>
        <li class="last">Analisar procuração</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Analisar procuração <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <div id="confirm" class="sumir"></div>
    <div id="error" class="sumir"></div>
    <form id="formaprovacao" action="<?php echo $this->url(array('controller' => 'procuracao', 'action' => 'aprovacao')); ?>" method="post">
        <table class="tabela">
            <tr>
                <th colspan="2">Procuração nº <?php echo $this->procuracao[0]->idDocumento; ?> </th>
            </tr>
            <tr>
                <td width="130">Visualizar procuração </td>
                <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $this->procuracao[0]->idArquivo; ?>"><img src="<?php echo $this->baseUrl(); ?>/public/img/btn_busca.jpg"/></a></td>
            </tr>
            <tr>
                <th colspan="2" align="left">RESPONSÁVEL</th>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->procuracao[0]->NomeResponsavel; ?></td>
            </tr>
            <tr>
                <th colspan="2" align="left">PROPONENTE</th>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->procuracao[0]->NomeProponente; ?></td>
            </tr>
            <tr>
                <th colspan="2">OBSERVAÇÃO</th>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->procuracao[0]->dsObservacao; ?></td>
            </tr>
            <tr>
                <th colspan="2">PROJETOS SELECIONADOS PARA A PROCURAÇÃO</th>
            </tr>
            <tr>
                <td class="titulo_tabela">PRONAC</td>
                <td class="titulo_tabela">NOME DO PROJETO</td>
            </tr>
            <?php foreach ($this->procuracao as $p): ?>
            <tr>
                <td><?php echo $p->pronac; ?>
                    <input type="hidden" name="idProcuracao[]" value="<?php echo $p->idProcuracao; ?>" />
                    <input type="hidden" name="idVinculoProposta[]" value="<?php echo $p->idVinculoProposta; ?>" />
                </td>
                <td><?php echo $p->NomeProjeto; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>

        <table class="tabela">
            <tr>
                <th>Justificativa</th>
            </tr>
            <tr>
                <td align="center"><textarea name="justificativa" id="justificativa" rows="5" class="input_simples" style="width: 99%;"></textarea></td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <td align="center">
                    <input class="btn_aprovar" type="button" value=" " onclick="aprovacao('<?php echo $this->procuracao[0]->idDocumento; ?>', '1');"/>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input class="btn_rejeitar" type="button" value=" " onclick="aprovacao('<?php echo $this->procuracao[0]->idDocumento; ?>', '2');"/>
                </td>
            </tr>
        </table>
        <input type="hidden" value="" name="situacao" id="situacao">
        <input type="hidden" value="<?php echo $this->procuracao[0]->idUsuarioResponsavel; ?>" name="responsavel" id="responsavel">
        <input type="hidden" value="<?php echo $this->procuracao[0]->idDocumento; ?>" name="idDocumento" id="idDocumento">
    </form>
</div>

<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />