<div class="row">
    <div class="col s12">
        <table class="bordered striped highlight">
            <thead class="green darken-1 white-text">
                <tr>
                    <th>#</th>
                    <th data-field="id" class="center-align">Data</th>
                    <th data-field="id" class="center-align">Qtd Dias</th>
                    <th data-field="teste" class="center-align">Remetente</th>
                    <th data-field="teste2" class="center-align">Destinat&aacuterio</th>
                    <th data-field="teste3" class="center-align">Pergunta</th>
                    <th data-field="teste3" class="center-align">Resposta</th>
                    <th data-field="teste3" class="center-align">A&ccedil;&atilde;o</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->arrResult as $int => $arrValue): ?>
                <tr>
                    <td><?php echo $int + 1; ?></td>
                    <td><?php echo $arrValue['dtMensagemTreated']; ?></td>
                    <td <?php if ($arrValue['tempoResposta'] > 9) echo 'style="color: red;"'; ?>><?php echo $arrValue['tempoResposta']; ?></td>
                    <td><?php echo $arrValue['remetenteUnidadeNome'] . ' / ' . $arrValue['usu_nome_remetente']; ?></td>
                    <td><?php echo ($arrValue['usu_nome_destinatario']) ? $arrValue['destinatarioUnidadeNome'] . ' / ' . $arrValue['usu_nome_destinatario'] : $arrValue['destinatarioUnidadeNome']; ?></td>
                    <td><?php echo $arrValue['dsMensagem']; ?></td>
                    <td><?php echo $arrValue['dsResposta']; ?></td>
                    <td>
                        <a
                            data-ajax-modal="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => 'visualizar', 'id' => $arrValue['idMensagemProjeto'], 'idPronac' => $this->idPronac), null, true); ?>"
                            href="javascript:void(0);"
                            class="btn small waves-effect waves-light tooltipped" data-position="top" data-delay="50"
                            data-tooltip="Visualizar">
                            <i class="material-icons">zoom_in</i>
                        </a>
                        <?php if ($arrValue['qtdResposta'] === '0') : ?>
                            <?php if ($this->usuOrgao == 91) : ?>
                                <a data-ajax-modal="<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => 'encaminhar', 'id' => $arrValue['idMensagemProjeto'], 'idPronac' => $this->idPronac), null, true); ?>"
                                   href="javascript:void(0);"
                                   class="btn small waves-effect waves-light tooltipped" data-position="top"
                                   data-delay="50" data-tooltip="Encaminhar">
                                    <i class="material-icons">subdirectory_arrow_right</i>
                                </a>
                            <?php endif; ?>
                            <?php if ($this->usuCodigo == $arrValue['idDestinatario'] || (is_null($arrValue['idDestinatario']) && $this->usuOrgao == $arrValue['idDestinatario'])): ?>
                                <a href="javascript:$3.redirect('<?php echo $this->url(array('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => 'responder', 'id' => $arrValue['idMensagemProjeto'], 'idPronac' => $this->idPronac), null, true); ?>');"
                                   class="btn small waves-effect waves-light tooltipped" data-position="top"
                                   data-delay="50" data-tooltip="Responder"><i class="material-icons">insert_comment</i></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<div class="content padding20 clearfix">
    <?php if (is_array($this->dados) && count($this->dados) > 0) : ?>
    <div class="row">
        <div class="col s10">
            <?php gerarBreadCrumb($links); ?>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <table class="bordered margin0" id="enquadramento" style="width: 100%">
                <thead>
                    <tr class="">
                        <th class="center-align">Pronac</th>
                        <th class="center-align">Nome do Projeto</th>
                        <th class="center-align">Dt. Solicita&ccedil;&atilde;o</th>
                        <th class="center-align">Proponente</th>
                        <th class="center-align" align="center">A&ccedil;&otilde;es</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->dados as $dado): ?>
                    <tr>
                        <td class="center-align" align="center">
                            <a class="waves-effect waves-dark btn white black-text"
                               href="<?php echo $this->url(
                                       array(
                                           'module' => 'default',
                                           'controller' => 'consultardadosprojeto',
                                           'action' => 'index'
                                       )
                                   ) . "?idPronac={$dado['IdPRONAC']}"; ?>"><u><?php echo $dado['pronac']; ?></u></a>
                        </td>
                        <td class="center-align" align="center"><?php echo $dado['nomeProjeto']; ?></td>
                        <td class="center-align" align="center"><?php echo $dado['dtSolicitacao']; ?></td>
                        <td class="center-align" align="center"><?php echo $dado['proponente']; ?></td>
                        <td class="center-align" align="center">
                            <?php
                            $situacaoAssinatura = "Fechado para assinatura";
                            if($dado['cdSituacao'] == Assinatura_Model_TbDocumentoAssinatura::CD_SITUACAO_DISPONIVEL_PARA_ASSINATURA) {
                                $situacaoAssinatura = "Dispon&iacute;vel para assinatura";
                            }
                            echo $situacaoAssinatura;
                            ?>
                        </td>
                        <td class="center-align" align="center">
                            <?php
                            $estadoAssinatura = "<span style='color:red'>Inativo</span>";
                            if($dado['stEstado'] == Assinatura_Model_TbDocumentoAssinatura::ST_ESTADO_DOCUMENTO_ATIVO) {
                                $estadoAssinatura = "<span style='color:green'>Ativo</span>";
                            }
                            echo $estadoAssinatura;
                            ?>
                        </td>
                        <td class="center-align" align="center">
                            <?php
                            $parametrosVisualicacao = "?idDocumentoAssinatura={$dado['idDocumentoAssinatura']}";
                            ?>
                            <a class="btn waves-effect waves-light tooltipped small "
                               href="<?php echo $this->url(array(
                                       'module' => 'assinatura',
                                       'controller' => 'index',
                                       'action' => 'visualizar-projeto'
                                   )) . $parametrosVisualicacao ?>"
                               data-position="top"
                               data-delay="50"
                               data-tooltip="Visualizar">
                                <i class="material-icons">search</i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php else: ?>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10">
            <div class="padding20 green white-text">Sem solicita&ccedil;&otilde;es.</div>
        </div>
        <div class="col s11"></div>
    </div>
<?php endif; ?>