<script type="text/javascript">
    $(document).ready(function(){
        
        //sumete a pagina quando clicar no ENTER do teclado
        $(window).bind('keypress', function(e) {
            if(e.keyCode == 13){ //codigo da tecla ENTER do teclado
                if($("#nrreuniao").val() == ""){
                    $("#msgErroReuniao").html("<font color='red'>Campo obrigatório não informado.</font><br />");
                return false;
                }else{
                    $("#msgErroReuniao").html("");
                    $("#formBuscar").submit();
                }
            }
        });

        $(".btn_pesquisar").click(function(){
            if($("#nrreuniao").val() == ""){
                $("#msgErroReuniao").html("<font color='red'>Campo obrigatório não informado.</font><br />");
                return false;
            }else{
                $("#msgErroReuniao").html("");
                $("#formBuscar").submit();
            }
        });
        
        $("#btsubmit").click(function(){
            var n = $("input:checked").length;
            if(n >= 1){
                $("#msgErro").html("");
                $("#formPDF").submit();
            }else{
                $("#msgErro").html("<font color='red'>É necessário informar ao menos um Projeto para gerar o termo.</font><br />");
            }
        });
        
        $("#selecionar").change(function(){
            if($(this).attr('checked') == true){
                $('.idpronac').attr('checked',true);
            }
            else{
                $('.idpronac').attr('checked',false);
            }

        });
        
        $('#nomeSecretario').val('<?php echo $this->nomeSecretario;?>');
        $('#nomeOrgao').val('<?php echo $this->nomeOrgao;?>');
        
    });
</script>


<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="InIn&iacute;ciocio">In&iacute;cio</a></li>
        <li class="last">Gerar Termo de Decisão</li>
    </ul>
</div> <!-- final: #breadcrumb -->
<div id="titulo"><div>Gerar Termo de Decisão</div>
</div>  
<div id="conteudo"> 
    <div id="miolo">
        <form name="formBuscar" id="formBuscar" method="post" action="<?php echo $this->url(array('controller' => 'gerartermodeaprovacao', 'action' => 'index')); ?>">
            <fieldset><legend>Gerar Termo de Aprova&ccedil;&atilde;o</legend>
                <table style="margin: 5px auto; width: 100%;" class="tabela">
                    <tbody>
                        <tr>
                            <td>
                                <div style="float: left; padding-right: 1em; font-weight: bold">
                                    * N&uacute;mero da reunião Plen&aacute;ria:&nbsp;
                                    <input type="text" name="NrReuniao" id="nrreuniao" maxlength="5" size="5" value ="<?php echo  $this->ultimaCNIC  ?>" class="input_simples"/>
                                    &nbsp;&nbsp;&nbsp;
                                    PRONAC:&nbsp;
                                    <input type="text" name="pronac" id="pronac" maxlength="8" size="10" value ="" class="input_simples"/>
                                </div><input type="button" name="procurar" class="btn_pesquisar" value="" style="height: 21px; vertical-align: bottom" />
                                &nbsp;<span id="msgErroReuniao"></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <br>
            </fieldset>
        </form>
        <div <?php echo isset($this->buscartermo) ? '': "style='display:none;'"?>>
            <form name="formPDF" target="_blank" id="formPDF" method="post" action="<?php echo $this->url(array('controller' => 'gerartermodeaprovacao', 'action' => 'gerarpdf')); ?>">
                <input type="hidden" name="nrReuniao" id="nrReuniao" value="<?php echo $this->nrReuniao;?>" class="input_simples">
                <fieldset><legend>Resultado da Pesquisa</legend>
                    <table width="100%" border="0" cellpadding="0" cellspacing="1">
                        <thead>
                            <tr>
                                <th width="5%"></th>
                                <th>
                                    <?php if(count($this->buscartermo) > 0): ?>
                                    <input type="checkbox" value="Selecionar todos" class="btn" id='selecionar' >
                                    <?php endif;?>
                                </th>
                                <th>PRONAC</th>
                                <th>Nome do Projeto</th>
                                <th>Tipo de Parecer</th>
                            </tr>
                        </thead>
                        <?php
                                $i = 0;
                                $linha = 1;
                                if(count($this->buscartermo) > 0):
                                    echo "<div><p align='center'><b>Plen&aacute;ria CNIC N&ordm:" . $this->dadosultimaCNIC['NrReuniao'] . " - ";
                                    echo "Data de Realiza&ccedil;&atilde;o:" .Data::tratarDataZend($this->dadosultimaCNIC['DtFinal'] , "brasileiro" . "</b></p></div>");
                                    foreach ($this->buscartermo as $resultado) { ?>
                                        <tr class="linha">
                                            <td width="5%"><?php echo $linha; ?></td>
                                            <td class='centro'><input type="checkbox" value="<?php echo $resultado['IdPRONAC']; ?>" class="idpronac" name="idpronac[]"> </td>
                                            <td><?php echo $this->escape($resultado['PRONAC']); ?></td>
                                            <td><?php echo $this->escape($resultado['NomeProjeto']); ?></td>
                                            <td><?php echo $this->tipoAprovacao($resultado['stAnalise']); ?>
                                            </td>
                                        </tr>
                                        <?php
                                        $i++;
                                        $linha++;
                                    }
                                 else: ?> 
                                <tr>
                                    <td colspan="5" class="centro"><em>Nenhum projeto encontrado com os parâmentros de pesquisa informados.</em></td>
                                </tr> 
                        <?php endif;?> 
                        <tr>

                            <th colspan="4" align="right"  ><b>Total de Projetos Encontrados</b></th>
                            <th colspan="1" align="center" ><b><?php echo $i; ?></b></th>

                        </tr>

                    </table>
                    <br />
                    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
                        <tr class="destacar">
                            <td class="centro">
                                <center>
                                    <div style="width: 800px;">
                                        <div style="width: 210px; float: left; text-align: right; vertical-align: bottom">Secretário(a): </div>
                                        <div style="width: 400px; padding-bottom: 4px"><input type="text" name="nomeSecretario" id="nomeSecretario" class="input_simples" style="width: 370px"></div>
                                        <div style="width: 210px; float: left; text-align: right">Órgão: </div>
                                        <div style="width: 400px;"><input type="text" name="nomeOrgao" id="nomeOrgao" class="input_simples" style="width: 370px"></div>
                                    </div>
                                </center>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <center>
                                    <span id="msgErro"></span><br>
                                    <input type="button" id="btsubmit" class="btn" value="Gerar Termo e Imprimir" />
                                </center>
                            </td>
                        </tr>
                    </table>

                </fieldset>
            </form>
            <!-- Colar Conteudo dentro-->
        </div>
    </div>
    <!-- final: conteudo principal #conteudo -->
</div>
<!-- inicio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>  
<!-- final: detalhe final da div conteudo #rodapeConteudo -->  
<br clear="all" />