<style>
    body {
        margin:0;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        color:#000;
        line-height:14pt;
    }
    a:link, a:active, a:visited {
        text-decoration:underline;
    }
    a:hover {
        text-decoration:none;
    }
    .tabela { /* tamanho de tabelas com registros */
        margin:10px auto;
        width:97%;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #CCC solid;
    }
    table td {
        background:#fff;
        padding:4px;
        color:auto;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #CCC solid;
    }
    table tr.destacar td, table td.destacar {
        background:#e2e2e2;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
    }
    table th {
        background:#cccccc;
        padding:4px;
        text-transform:uppercase;
        font-size:11px;
    }
    #brasao{
        width : 85px;
        height: 86px;
    }
    legend{
        font-size:13px;
        font-weight: bold;
    }
    .btn_imprimir{
        border-top:1px solid #efefef;
        border-left:1px solid #efefef;
        border-right:1px solid #aaa;
        border-bottom:1px solid #aaa;
        margin:0 5px 0 0;
        width:20px;
        height:21px;
        text-align:center;
        cursor:pointer;
        background:url('<?php echo $this->baseUrl(); ?>/public/img/buttons/imprimir.gif') center center no-repeat;
    }
    .btn_imprimir:hover{
        background-color:#fff;
        border-top:1px solid #aaa;
        border-left:1px solid #aaa;
        border-right:1px solid #efefef;
        border-bottom:1px solid #efefef;
    }
    .paginaA4{
        width:auto;
        margin: 1.111cm 1cm 1cm 1.005cm;
        page-break-after: always;
    }
</style>
<script type="text/javascript">
    
    /*
     * Fun&ccedil;&atilde;o responsável pela exibi&ccedil;&atilde;o ou ocultamento de conteúdo,
     * mudando a imagem.
     **/
    window.onload = function(){
        //document.getElementById("conteudoImprimir").value = document.getElementById("conteudoImp").innerHTML;
        //document.forms["formGerarPdf"].submit();
        window.print();
    }
    
</script>

    <table class="tabela">
            <tr>
                <th>  
                    Proponente
                </th>
            </tr>
            <tr>
                <td align="center">
                    <div id="proponente">
                        <fieldset>
                            <legend>Identifica&ccedil;&atilde;o</legend>
                            <table class="tabela">
                                <tr>
                                    <td width="10%" class="esquerda destacar"><b>CNPJ / CPF</b></td>
                                    <td class="esquerda"><?php echo (strlen($this->itensGeral[0]->CNPJCPF) > 11) ? aplicaMascara($this->itensGeral[0]->CNPJCPF, "99.999.999/9999-99") : aplicaMascara($this->itensGeral[0]->CNPJCPF, "999.999.999-99") ?></td>
                                    <td width="10%" class="esquerda destacar"><b>Proponente</b></td>
                                    <td class="esquerda"><?php echo $this->itensGeral[0]->NomeAgente ?></td>
                                </tr>
                            </table>
                        </fieldset>
                        <fieldset>
                            <legend>Endere&ccedil;o</legend>
                            <table class="tabela">
                                <tr class="destacar">
                                    <td width="10%" nowrap class="centro"><b>Tipo de Endere&ccedil;o</b></td>
                                    <td width="10%" nowrap class="centro"><b>Tipo do Logradouro</b></td>
                                    <td width="20%" class="centro"><b>Logradouro</b></td>
                                    <td class="centro"><b>Número</b></td>
                                    <td class="centro"><b>Complemento</b></td>
                                    <td class="centro"><b>Bairro</b></td>
                                    <td class="centro"><b>Cidade</b></td>
                                    <td class="centro"><b>UF</b></td>
                                    <td class="centro"><b>CEP</b></td>
                                </tr>
                                <?php $auxEndCEP = "";
                                $auxEndLogra = ""; ?>
                                <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) {
                                    foreach ($this->itensGeral as $endereco) {
                                        ?>
                                            <?php if ($endereco->CEP != $auxEndCEP || $endereco->Logradouro != $auxEndLogra): ?>
                                            <tr>
                                                <td><?php echo $endereco->endereco ?></td>
                                                <td><?php echo $endereco->logradouro ?></td>
                                                <td><?php echo $endereco->Logradouro ?></td>
                                                <td><?php echo $endereco->Numero ?></td>
                                                <td><?php echo $endereco->Complemento ?></td>
                                                <td><?php echo $endereco->Bairro ?></td>
                                                <td><?php echo $endereco->NomeCidade ?></td>
                                                <td><?php echo $endereco->SiglaUf ?></td>
                                                <td><?php echo aplicaMascara($endereco->CEP, "99999-999") ?></td>
                                            </tr>
                                        <?php endif; ?>
                                        <?php $auxEndCEP = $endereco->CEP; ?>
                                        <?php $auxEndLogra = $endereco->Logradouro; ?>
                                        <?php }
                                        } ?>
                            </table>
                        </fieldset>
                        <fieldset>
                            <legend>Telefones</legend>
                            <table class="tabela">
                                <tr class="destacar">
                                    <td width="10%"><b>Tipo</b></td>
                                    <td><b>UF</b></td>
                                    <td><b>DDD</b></td>
                                    <td><b>Número</b></td>
                                    <td><b>Divulgar</b></td>
                                </tr>
                                <?php if (is_array($this->itensTelefone) and count($this->itensTelefone) > 0) {
                                foreach ($this->itensTelefone as $telefone) {
                                    ?>
                                        <tr>
                                            <td><?php echo $telefone->Descricao ?></td>
                                            <td><?php echo $telefone->Sigla ?></td>
                                            <td><?php echo $telefone->DDD ?></td>
                                            <td><?php echo $telefone->Numero ?></td>
                                            <td><?php if ($telefone->Divulgar == 1) echo "Sim"; else echo "Nao"; ?></td>
                                        </tr>
                                 <?php }
                                    }?>
                            </table>
                        </fieldset>
                        <fieldset>
                            <legend>E-mail</legend>
                            <table class="tabela">
                                <tr class="destacar">
                                    <td width="10%"><b>Tipo</b></td>
                                    <td><b>E-mail</b></td>
                                    <td><b>Para correspond&ecirc;ncia?</b></td>
                                    <td><b>Posso divulgar?</b></td>
                                </tr>
                                <?php $auxEmail = array();
                                    $auxEmailTipo = array(); ?>
                                <?php foreach ($this->itensGeral as $email) { ?>
                                    <?php if (!in_array($email->agente, $auxEmail) || !in_array($email->email, $auxEmailTipo)): ?>
                                        <tr>
                                            <td nowrap><?php echo $email->email ?></td>
                                            <td nowrap><?php echo $email->agente ?></td>
                                            <td><?php if ($email->divulgarEmail == 1) echo "Sim"; else echo "Nao"; ?></td>
                                            <td><?php if ($email->divulgarEmail == 1) echo "Sim"; else echo "Nao"; ?></td>
                                        </tr>
                                     <?php endif; ?>
                                        <?php $auxEmail[] = $email->agente; ?>
                                    <?php $auxEmailTipo[] = $email->email; ?>
                                        <?php } ?>
                            </table>
                        </fieldset>
                        <fieldset>
                            <legend>Natureza</legend>
                            <table class="tabela">
                                <tr class="destacar">
                                    <td width="10%"><b>Direito</b></td>
                                    <td><b>Esfera</b></td>
                                    <td><b>Poder</b></td>
                                    <td><b>Administra&ccedil;&atilde;o</b></td>
                                </tr>
                                <tr>
                                    <?php if (!empty($this->itensGeral[0]->direito)) { ?>
                                        <td nowrap><?php echo $this->itensGeral[0]->direito ?></td>
                                        <td><?php echo $this->itensGeral[0]->esfera ?></td>
                                        <td><?php echo $this->itensGeral[0]->poder ?></td>
                                        <td><?php echo $this->itensGeral[0]->Admins ?></td>
                                    <?php } else { ?>
                                        <td colspan="4" align="center">Natureza n&atilde;o informada</td>
                                    <?php } ?>
                                </tr>
                            </table>
                        </fieldset>                        
                        <fieldset>
                            <legend>Dirigente</legend>
                                <table class="tabela">
                                    <?php if ($this->dirigentes && count($this->dirigentes)>0) { ?>
                                        <tr class="destacar">
                                            <td width="20%" align="center"><b>CPF</b></td>
                                            <td align="center"><b>Nome</b></td>
                                        </tr>
                                            <?php foreach ($this->dirigentes as $tbdirigentes): ?>
                                                <?php 
                                                $cpfCnpjDirigente = $tbdirigentes['CNPJCPFDirigente'];
                                                $nomeDirigente = $tbdirigentes['NomeDirigente'];
                                                if($cpfCnpjDirigente != '00000000000000'): ?>
                                                    <tr>
                                                        <td align="center"><?php echo empty($cpfCnpjDirigente) ? '<em>Dados n&atilde;o informados!</em>' : aplicaMascara($cpfCnpjDirigente, "999.999.999-99"); ?>
                                                        <td align="left"><?php echo $nomeDirigente; ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td></td>
                                                            <td>
                                                                <table class='tabela'>           
                                                                    <tr class="destacar">
                                                                        <td class="centro" colspan="4">Mandatos</td>
                                                                    </tr>
                                                                    <?php if(count($this->mandatos[$nomeDirigente]) > 0)
:                                                                            foreach ($this->mandatos[$nomeDirigente] as $mandato): ?>  
                                                                        <tr>
                                                                        <td>
                                                                           <b>Tipo de documento</b><br>
                                                                            <?php echo $mandato->Descricao;?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Nº do documento</b><br>
                                                                            <?php echo $mandato->dsNumeroDocumento;?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Per&iacute;odo de vig&ecirc;ncia</b><br>
                                                                            <?php echo date('d/m/Y',strtotime($mandato->dtInicioMandato)).' à '.date('d/m/Y',strtotime($mandato->dtFimMandato)); ?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Arquivo</b><br>
                                                                            <a href="<?php echo $this->url(array('controller'=>'upload','action'=>'abrir')); ?>?id=<?php echo $mandato->idArquivo; ?>"><?php echo $mandato->nmArquivo ?></a>
                                                                        </td>
                                                                    </tr>
                                                                    <?php endforeach; ?>
                                                           <?php else: ?>
                                                                <tr>
                                                                    <td class="centro" colspan="4"><em>N&atilde;o existem mandatos cadastrados!</em></td>
                                                                </tr>
                                                           <?php endif; ?>
                                                    </table>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php } else { ?>
                                    <tr>
                                        <td colspan="2" align="center"><em>N&atilde;o existem Dirigentes cadastrados!</em></td>
                                    </tr>
                            <?php } ?>
                        </table>
                    </fieldset>                                     
                    <fieldset>
                        <legend>Usu&aacute;rio SalicWEB</legend>
                        <table class="tabela">
                            <tr>
                                    <?php if (is_array($this->itensGeral) and !empty($this->itensGeral[0]->nomeUsuario)) { ?>
                                    <td width="10%" class="esquerda destacar"><b>CPF</b></td>
                                    <td class="esquerda"><?php echo aplicaMascara($this->itensGeral[0]->Cpf, "999.999.999-99") ?></td>
                                    <td width="10%" class="esquerda destacar"><b>Nome</b></td>
                                    <td class="esquerda"><?php echo $this->itensGeral[0]->nomeUsuario ?></td>
                                    <?php } ?>
                            </tr>
                        </table>
                    </fieldset>
                </div><!-- fecha div proponente -->
            </td>
        </tr>
        <tr>
            <th>                
                Proposta cultural
            </th>
        </tr>
        <tr>
            <td>
                <div id="projetoCultural">
                    <fieldset>
                        <legend>Identifica&ccedil;&atilde;o</legend>
                        <table class="tabela">
                            <tr>
                                <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                    <td width="10%" class="destacar"><b>N&ordm; da Proposta</b></td>
                                    <td><?php echo $this->itensGeral[0]->idPreProjeto ?></td>
                                    <td width="10%" nowrap class="destacar"><b>T&iacute;tulo da Proposta</b></td>
                                    <td><?php echo $this->itensGeral[0]->NomeProjeto ?></td>
                                <?php } ?>
                            </tr>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Informaç&otilde;es Complementares</legend>
                        <table class="tabela">
                            <tr class="destacar">
                                <td><b>&Eacute; proposta de audiovisual?</b></td>
                                <td><b>Mecanismo</b></td>
                                <td><b>Ag&ecirc;ncia Banc&aacute;ria</b></td>
                                <td><b>Dt. In&iacute;cio Execuï¿½&atilde;o</b></td>
                                <td><b>Dt. Final Execu&ccedil;&atilde;o</b></td>
                                <td><b>Dt. Fixa</b></td>
                                <td><b>Plano Atual</b></td>
                            </tr>
                                <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php if ($this->itensGeral[0]->AreaAbrangencia == 1) echo "Sim"; else echo "Nao"; ?></td>
                                    <td><?php if ($this->itensGeral[0]->Mecanismo == 1) echo "Incentivo Fiscal Federal"; ?></td>
                                    <td><?php echo $this->itensGeral[0]->AgenciaBancaria ?></td>
                                    <td><?php echo substr($this->itensGeral[0]->DtInicioDeExecucao, 0, 10) ?></td>
                                    <td><?php echo substr($this->itensGeral[0]->DtFinalDeExecucao, 0, 10) ?></td>
                                    <td><?php if ($this->itensGeral[0]->stDataFixa == 1) echo "Sim"; else echo "Nao"; ?></td>
                                    <td><?php if ($this->itensGeral[0]->stPlanoAnual == 1) echo "Sim"; else echo "Nao"; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Informaç&otilde;es sobre tombamento</legend>
                        <table class="tabela">
                            <tr class="destacar">
                                <td><b>N&ordm; Ato Tombamento</b></td>
                                <td><b>Dt. Ato Tombamento</b></td>
                                <td><b>Esfera Tombamento</b></td>
                            </tr>
                                <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo $this->itensGeral[0]->NrAtoTombamento ?></td>
                                    <td><?php echo $this->itensGeral[0]->DtAtoTombamento ?></td>


                                    <?php $esferaTombamento = array('', 'Municipal', 'Estadual', 'Federal') ?>

                                    <td><?php echo $esferaTombamento[$this->itensGeral[0]->EsferaTombamento] ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>

                    <fieldset>
                        <legend>Resumo do Projeto</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (strip_tags($this->itensGeral[0]->ResumoDoProjeto)) ? strip_tags($this->itensGeral[0]->ResumoDoProjeto, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Objetivos</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->Objetivos)) != "") ? strip_tags($this->itensGeral[0]->Objetivos, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Justificativa</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->Justificativa)) != "") ? strip_tags($this->itensGeral[0]->Justificativa, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Acessibilidade</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->Acessibilidade)) != "") ? strip_tags($this->itensGeral[0]->Acessibilidade, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Democratizaç&atilde;o de Acesso</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->DemocratizacaoDeAcesso)) != "") ? strip_tags($this->itensGeral[0]->DemocratizacaoDeAcesso, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Etapa de Trabalho</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->EtapaDeTrabalho)) != "") ? strip_tags($this->itensGeral[0]->EtapaDeTrabalho, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Ficha Técnica</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->FichaTecnica)) != "") ? strip_tags($this->itensGeral[0]->FichaTecnica, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Sinopse de obra</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->Sinopse)) != "") ? strip_tags($this->itensGeral[0]->Sinopse, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Impacto Ambiental</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->ImpactoAmbiental)) != "") ? strip_tags($this->itensGeral[0]->ImpactoAmbiental, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Especificaç&otilde;es técnicas do produto</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->EstrategiaDeExecucao)) != "") ? strip_tags($this->itensGeral[0]->EstrategiaDeExecucao, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>
                    <fieldset>
                        <legend>Outras Informaç&otilde;es</legend>
                        <table class="tabela">
                            <?php if (is_array($this->itensGeral) and count($this->itensGeral) > 0) { ?>
                                <tr>
                                    <td><?php echo (trim(strip_tags($this->itensGeral[0]->EspecificacaoTecnica)) != "") ? strip_tags($this->itensGeral[0]->EspecificacaoTecnica, "<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>") : "N&atilde;o informado."; ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </fieldset>

                </div><!-- fecha div proposta cultural -->
            </td>
        </tr>

        <tr>
            <th align="center">                
                Plano de Distribuiç&atilde;o do Produto
            </th>
        </tr>
        <tr>
            <td align="center">                
                    <table class="tabela">
                        <tr class="destacar">
                            <td style="font-size:11px">Nome do Evento / Produto</td>
                            <td style="font-size:11px">Área</td>
                            <td style="font-size:11px">Segmento</td>
                            <td style="font-size:11px">Posiç&atilde;o da Logomarca</td>
                            <td style="font-size:11px">N&ordm; Exemplares / Ingressos</td>
                            <td style="font-size:11px">Distribuiç&atilde;o / Patrocinador</td>
                            <td style="font-size:11px">Distribuíç&atilde;o / Divulgaç&atilde;o</td>
                            <td style="font-size:11px">Distribuíç&atilde;o / Beneficiários</td>
                            <td style="font-size:11px">Total Venda Normal</td>
                            <td style="font-size:11px">Total Venda Promocional</td>
                            <td style="font-size:11px">Preço Unitário Normal</td>
                            <td style="font-size:11px">Preço Unitário Promocional</td>
                            <td style="font-size:11px">Receita Prevista Venda Normal (R$)</td>
                            <td style="font-size:11px">Receita Prevista Venda Promocional (R$)</td>
                            <td style="font-size:10px">Total de Receita Prevista (R$)</td>
                        </tr>
                        <?php
                        $vlQtdeProduzida = 0;
                        $vlQtdePatrocinador = 0;
                        $vlQtdeProponente = 0;
                        $vlQtdeOutros = 0;
                        $vlQtdeVendaNormal = 0;
                        $vlQtdeVendaPromocional = 0;
                        $vlPrecoUnitarioNormal = 0;
                        $vlPrecoUnitarioPromocional = 0;
                        $vlReceitaNormal = 0;
                        $vlReceitaPro = 0;
                        $vlReceitaPrevista = 0;

                        if (is_array($this->itensPlanosDistribuicao) and count($this->itensPlanosDistribuicao) > 0)
                            foreach ($this->itensPlanosDistribuicao as $distribuicao) {
                                $destacar = "";
                                if ($distribuicao->stPrincipal == 1) {
                                    $destacar = 'style="color:#FF0000"';
                                }
                                ?>
                                <tr>
                                    <td align="left" <?php echo $destacar ?>><?php echo $distribuicao->produto ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php echo $distribuicao->area ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php echo $distribuicao->segmento ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php echo $distribuicao->posicaoLogo ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdeProduzida += $distribuicao->QtdeProduzida;
                                echo $distribuicao->QtdeProduzida; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdePatrocinador += $distribuicao->QtdePatrocinador;
                                echo $distribuicao->QtdePatrocinador; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdeProponente += $distribuicao->QtdeProponente;
                        echo $distribuicao->QtdeProponente; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdeOutros += $distribuicao->QtdeOutros;
                        echo $distribuicao->QtdeOutros; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdeVendaNormal += $distribuicao->QtdeVendaNormal;
                        echo $distribuicao->QtdeVendaNormal; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlQtdeVendaPromocional += $distribuicao->QtdeVendaPromocional;
                        echo $distribuicao->QtdeVendaPromocional; ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlPrecoUnitarioNormal += $distribuicao->PrecoUnitarioNormal;
                        echo number_format($distribuicao->PrecoUnitarioNormal, 2, ',', '.'); ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlPrecoUnitarioPromocional += $distribuicao->PrecoUnitarioPromocional;
                        echo number_format($distribuicao->PrecoUnitarioPromocional, 2, ',', '.'); ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlReceitaNormal += $distribuicao->ReceitaNormal;
                        echo number_format($distribuicao->ReceitaNormal, 2, ',', '.'); ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlReceitaPro += $distribuicao->ReceitaPro;
                        echo number_format($distribuicao->ReceitaPro, 2, ',', '.'); ?></td>
                                    <td align="center" <?php echo $destacar ?>><?php $vlReceitaPrevista += $distribuicao->ReceitaPrevista;
                        echo number_format($distribuicao->ReceitaPrevista, 2, ',', '.'); ?></td>
                                </tr>
    <?php } ?>
                        <tr>
                            <td align="center" colspan="4"><b>Total Geral</b></td>
                            <td align="center"><?php echo $vlQtdeProduzida; ?></td>
                            <td align="center"><?php echo $vlQtdePatrocinador; ?></td>
                            <td align="center"><?php echo $vlQtdeProponente; ?></td>
                            <td align="center"><?php echo $vlQtdeOutros; ?></td>
                            <td align="center"><?php echo $vlQtdeVendaNormal; ?></td>
                            <td align="center"><?php echo $vlQtdeVendaPromocional; ?></td>
                            <td align="center"><?php echo number_format($vlPrecoUnitarioNormal, 2, ',', '.'); ?></td>
                            <td align="center"><?php echo number_format($vlPrecoUnitarioPromocional, 2, ',', '.'); ?></td>
                            <td align="center"><?php echo number_format($vlReceitaNormal, 2, ',', '.'); ?></td>
                            <td align="center"><?php echo number_format($vlReceitaPro, 2, ',', '.'); ?></td>
                            <td align="center"><?php echo number_format($vlReceitaPrevista, 2, ',', '.'); ?></td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <th align="center">                
                Planilha Orçamentária
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="planilhaOrcamentaria">
                    <?php
                    $item = 1;

                    $totalVal_01_Fonte = (float) 0;
                    $totalVal_02_Fonte = (float) 0;

                    // inicializa valor total por produto
                    $totalVal_01_Produto = (float) 0;
                    $totalVal_02_Produto = (float) 0;
                    $totalVal_03_Produto = (float) 0;

                    // inicializa valor total por etapa
                    $totalVal_01_Etapa = (float) 0;
                    $totalVal_02_Etapa = (float) 0;
                    $totalVal_03_Etapa = (float) 0;

                    // inicializa valor total por uf
                    $totalVal_01_UF = (float) 0;
                    $totalVal_02_UF = (float) 0;
                    $totalVal_03_UF = (float) 0;

                    // arrays que servem para armazenar os elementos, e, posteriormente,
                    // verificar se o elemento j&aacute; encontra-se no array e evitar a sua "impressï¿½o" duplicada na tela
                    $arrayIncentivo = array();
                    $arrayProdutos = array();
                    $arrayEtapas = array();
                    $arrayUFs = array();

                    // total geral
                    $totalVal_01_Geral = (float) 0;
                    $totalVal_02_Geral = (float) 0;


                    foreach ($this->AnaliseCustos as $resposta) :
                        // contador dos itens
                        /**
                         * INï¿½CIO FOREACH PRODUTOS
                         * Percorre todos os produtos
                         */
                        // vari&aacute;veis que servirï¿½o para fazer compara&ccedil;ï¿½o dos itens j&aacute; existentes,
                        // e, evitar "imprimir" um iten j&aacute; "impresso"
                        $comparadorIncentivo = $resposta->idFonte;
                        $comparadorProdutos = $resposta->idFonte . $resposta->idProduto;
                        $comparadorEtapas = $resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa;
                        $comparadorUFs = $resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa . $resposta->idUF . $resposta->idMunicipio;
                        ?>

                        <!-- ========== INï¿½CIO Tï¿½TULO INCENTIVO FISCAL FEDERAL ========== -->
                        <?php if (!in_array($comparadorIncentivo, $arrayIncentivo)): ?>
                            <tr>
                                <td colspan="9">
                                    <strong>
                                        <div><a href="#IFF<?php echo $comparadorIncentivo; ?>" onclick="AbrirFecharPlanilha('IFF<?php echo $comparadorIncentivo; ?>');" onkeypress=" "><div id="IFF<?php echo $comparadorIncentivo; ?>" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 18pt;"><?php echo utf8_decode(htmlentities($resposta->FonteRecurso)); ?></span></div></a></div>
                                    </strong>
                                </td>
                            </tr>
                        <?php endif; ?>
                        <!-- ========== FIM Tï¿½TULO INCENTIVO FISCAL FEDERAL ========== -->



                        <!-- ========== INï¿½CIO BUSCA POR PRODUTO ========== -->

                        <?php if (!in_array($comparadorProdutos, $arrayProdutos)): ?>
                            <!-- ========== INï¿½CIO Tï¿½TULO PRODUTOS ========== -->
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> linha">
                                <td colspan="9">
                                    <strong>
                                        <div><a href="#IFF_PRODUTO<?php echo $comparadorProdutos; ?>" onclick="AbrirFecharPlanilha('IFF_PRODUTO<?php echo $comparadorProdutos; ?>');" onkeypress=" "><div id="IFF_PRODUTO<?php echo $comparadorProdutos; ?>" class="icn_menos" style="width:98%; margin-left:2%;"><span class="green del_link"><?php echo utf8_decode(htmlentities($resposta->Produto)); ?></span></div></a></div>
                                    </strong>
                                </td>
                            </tr>
                            <!-- ========== FIM Tï¿½TULO PRODUTOS ========== -->
                        <?php endif; ?>



                        <?php if (!in_array($comparadorEtapas, $arrayEtapas)): ?>
                            <!-- ========== INï¿½CIO Tï¿½TULO ETAPAS ========== -->
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?>">
                                <td colspan="9">
                                    <strong style="margin-left:2%;">
                                        <div><a href="#IFF_ETAPA<?php echo $comparadorEtapas; ?>" onclick="AbrirFecharPlanilha('IFF_ETAPA<?php echo $comparadorEtapas; ?>');" onkeypress=" "><div id="IFF_ETAPA<?php echo $comparadorEtapas; ?>" class="icn_menos" style="width:90%; margin-left:4%;"><span class="orange del_link"><?php echo $resposta->idPlanilhaEtapa; ?> - <?php echo utf8_decode(htmlentities($resposta->Etapa)); ?></span></div></a></div>
                                    </strong>
                                </td>
                            </tr>
                            <!-- ========== INï¿½CIO Tï¿½TULO ETAPAS ========== -->
                        <?php endif; ?>



                        <?php if (!in_array($comparadorUFs, $arrayUFs)): ?>
                            <!-- ========== INï¿½CIO Tï¿½TULO UF ========== -->
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?> IFF_ETAPA<?php echo $comparadorEtapas; ?>">
                                <td colspan="9">
                                    <strong style="margin-left:3%;">
                                        <div><a href="#IFF_UF<?php echo $comparadorUFs; ?>" onclick="AbrirFecharPlanilha('IFF_UF<?php echo $comparadorUFs; ?>');" onkeypress=" "><div id="IFF_UF<?php echo $comparadorUFs; ?>" class="icn_menos" style="width:90%; margin-left:6%"><span class="black del_link"><?php echo $resposta->UF; ?> - <?php echo utf8_decode(htmlentities($resposta->Municipio)); ?></span></div></a></div>
                                    </strong>
                                </td>
                            </tr>
                            <!-- ========== FIM Tï¿½TULO UF ========== -->


                            <!-- ========== INï¿½CIO TITULO ï¿½TENS ========== -->
                            <tr class="destacar IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?> IFF_ETAPA<?php echo $comparadorEtapas; ?> IFF_UF<?php echo $comparadorUFs; ?>">
                                <td>&nbsp;</td>
                                <td width="20%">Item</td>
                                <td>Dias</td>
                                <td>Unidade</td>
                                <td>Qtde</td>
                                <td>Ocor.</td>
                                <td width="12%">Vl. Unit&aacute;rio</td>
                                <td width="12%">Vl. Solicitado</td>
                                <!--<td width="12%">Vl. Sugerido do Parecerista</td>-->
                                <td width="20%">Justificativa do Proponente</td>
                                <!--<th width="20%">Justificativa do Parecerista</th>-->
                                <!--<th width="12%">Vl. Sugerido do Relator</th>
                                <th>Justificativa do Relator</th>-->
                            </tr>
                            <!-- ========== FIM TITULO ï¿½TENS ========== -->
    <?php endif; ?>

                        <!-- ========== INï¿½CIO ï¿½TENS ========== -->
    <?php
    $totalItens = 0;

    //$i = $resposta->idPlanilhaProjeto; // criar&aacute; id ï¿½nico
    ?>

                        <tr onmouseover="over_tr(this);" onfocus="over_tr(this);" onmouseout="out_tr(this);" onblur="out_tr(this);" onclick="click_tr(this);" onkeypress="click_tr(this);"
                            class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?> IFF_ETAPA<?php echo $comparadorEtapas; ?> IFF_UF<?php echo $comparadorUFs; ?>
    <?php
    $totalItens--;
    ?>
                            ">
                            <td><?php echo $item; ?></td>
                            <td><?php echo $this->escape($resposta->Item); ?></td>
                            <td class="direita"><?php echo $this->escape($resposta->QtdeDias); ?></td>
                            <td class="centro"><?php echo $this->escape($resposta->Unidade); ?></td>
                            <td class="direita"><?php echo $this->escape($resposta->Quantidade); ?></td>
                            <td class="direita"><?php echo $this->escape($resposta->Ocorrencia); ?></td>
                            <td class="direita"><?php echo $this->formatarReal($this->escape($resposta->ValorUnitario)); ?></td>
                            <td class="direita blue"><?php echo $this->formatarReal($this->escape($resposta->VlSolicitado)); ?></td>
                            <!--<td class="direita green"><?php //echo $this->formatarReal($this->escape($resposta->Sugerido)); ?></td>-->
                            <td class="direita"><?php echo strip_tags($this->escape($resposta->JustificativaProponente)); ?></td>
                            <!--<td><?php //echo $this->escape($resposta->Justificativa); ?></td> -->
                            <!--<td class="direita"><?php //if($resposta->VlSugeridoConselheiro) echo $this->formatarReal($this->escape($resposta->VlSugeridoConselheiro)); ?></td>
                            <td><?php //echo $this->escape($this->LimitadorCaracteres($resposta->dsJustificativaConselheiro));  ?></td>-->
                        </tr>
                        <!-- ========== FIM ï¿½TENS ========== -->



                        <!-- ========== INï¿½CIO TOTAL UF ========== -->
                        <?php
                        // ===== CALCULA TOTAL UFS =====
                        $totalVal_01_UF += (float) $resposta->VlSolicitado;
                        $totalVal_02_UF += (float) $resposta->Sugerido;

                        $ultimaUF = isset($this->AnaliseCustos[$item]->idMunicipio) ? $this->AnaliseCustos[$item]->idFonte . $this->AnaliseCustos[$item]->idProduto . $this->AnaliseCustos[$item]->idPlanilhaEtapa . $this->AnaliseCustos[$item]->idUF . $this->AnaliseCustos[$item]->idMunicipio : null;

                        // compara a uf atual com a prï¿½xima uf para poder exibir o valor total
                        if ($resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa . $resposta->idUF . $resposta->idMunicipio != $ultimaUF) :
                            ?>
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?> IFF_ETAPA<?php echo $comparadorEtapas; ?> IFF_UF<?php echo $comparadorUFs; ?>">
                                <td colspan="8"><strong>Total de UF</strong></td>
                                <td class="direita"><strong><?php echo $this->formatarReal($totalVal_01_UF); ?></strong></td>
                                <!--<td>&nbsp;</td>-->
                                <!--<td>&nbsp;</td>-->
                            </tr>
                            <?php
                            // ===== ZERA TOTAL UFS =====
                            $totalVal_01_UF = (float) 0;
                            $totalVal_02_UF = (float) 0;
                        endif;
                        ?>
                        <!-- ========== FIM TOTAL UF ========== -->



                        <!-- ========== INï¿½CIO TOTAL ETAPAS ========== -->
                        <?php
                        // ===== CALCULA TOTAL ETAPAS =====
                        $totalVal_01_Etapa += (float) $resposta->VlSolicitado;
                        $totalVal_02_Etapa += (float) $resposta->Sugerido;

                        $ultimaEtapa = isset($this->AnaliseCustos[$item]->idPlanilhaEtapa) ? $this->AnaliseCustos[$item]->idFonte . $this->AnaliseCustos[$item]->idProduto . $this->AnaliseCustos[$item]->idPlanilhaEtapa : null;

                        // compara a etapa atual com a prï¿½xima etapa para poder exibir o valor total
                        if ($resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa != $ultimaEtapa) :
                            ?>
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?> IFF_ETAPA<?php echo $comparadorEtapas; ?>">
                                <td colspan="8" class="orange"><strong>Total da Etapa</strong></td>
                                <td class="direita orange"><strong><?php echo $this->formatarReal($totalVal_01_Etapa); ?></strong></td>
                                <!--<td>&nbsp;</td>-->
                                <!--<td>&nbsp;</td>-->
                            </tr>
                            <?php
                            // ===== ZERA TOTAL ETAPAS =====
                            $totalVal_01_Etapa = (float) 0;
                            $totalVal_02_Etapa = (float) 0;
                        endif;
                        ?>
                        <!-- ========== FIM TOTAL ETAPAS ========== -->



                        <!-- ========== INï¿½CIO TOTAL PRODUTOS ========== -->
                        <?php
                        // ===== CALCULA TOTAL PRODUTOS =====
                        $totalVal_01_Produto += (float) $resposta->VlSolicitado;
                        $totalVal_02_Produto += (float) $resposta->Sugerido;

                        $ultimoProduto = isset($this->AnaliseCustos[$item]->idProduto) ? $this->AnaliseCustos[$item]->idFonte . $this->AnaliseCustos[$item]->idProduto : null;

                        // compara o produto atual com o prï¿½ximo produto para poder exibir o valor total
                        if ($resposta->idFonte . $resposta->idProduto != $ultimoProduto) :
                            ?>
                            <tr class="IFF<?php echo $comparadorIncentivo; ?> IFF_PRODUTO<?php echo $comparadorProdutos; ?>">
                                <td colspan="8" class="green"><strong>Total dos Custos Administrativos ou do Produto</strong></td>
                                <td class="direita green"><strong><?php echo $this->formatarReal($totalVal_01_Produto); ?></strong></td>
                                <!--<td>&nbsp;</td>-->
                                <!--<td>&nbsp;</td>-->
                            </tr>
                            <?php
                            // ===== ZERA TOTAL PRODUTOS =====
                            $totalVal_01_Produto = (float) 0;
                            $totalVal_02_Produto = (float) 0;
                        endif;
                        ?>
                        <!-- ========== FIM TOTAL PRODUTOS ========== -->





                        <!-- ========== INICIO TOTAL GERAL ========== -->
                        <?php
                        // ===== CALCULA TOTAL UFS =====
                        $totalVal_01_Fonte += (float) $resposta->VlSolicitado;
                        $totalVal_02_Fonte += (float) $resposta->Sugerido;

                        $ultimaFonte = isset($this->AnaliseCustos[$item]->idFonte) ? $this->AnaliseCustos[$item]->idFonte : null;

                        // compara a etapa atual com a prï¿½xima etapa para poder exibir o valor total
                        if ($resposta->idFonte != $ultimaFonte) :
                            ?> 
                            <tr class="IFF<?php echo $comparadorIncentivo; ?>">
                                <td colspan="8" class="red" style="font-size: 12pt;"><strong>Total da Fonte de Recurso</strong></td>
                                <td class="direita red" style="font-size: 12pt;"><strong><?php echo $this->formatarReal($totalVal_01_Fonte); ?></strong></td>
                                <!--<td colspan="4">&nbsp;</td>-->
                            </tr>
                            <?php
                            // ===== ZERA TOTAL FONTE =====
                            $totalVal_01_Fonte = (float) 0;
                            $totalVal_02_Fonte = (float) 0;
                        endif;

                        // total geral
                        $totalVal_01_Geral += (float) $resposta->VlSolicitado;
                        $totalVal_02_Geral += (float) $resposta->Sugerido;
                        ?>
                        <!-- ========== FIM TOTAL PRODUTOS ========== -->

    <?php
    // adiciona os elementos no array para guardar no histï¿½rico
    $arrayIncentivo[] = $resposta->idFonte;
    $arrayProdutos[] = $resposta->idFonte . $resposta->idProduto;
    $arrayEtapas[] = $resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa;
    $arrayUFs[] = $resposta->idFonte . $resposta->idProduto . $resposta->idPlanilhaEtapa . $resposta->idUF . $resposta->idMunicipio;

    $item++; // incrementa o contador de itens

endforeach;
/**
 * FIM FOREACH PRODUTOS
 */
?>
                    <!-- ========== FIM BUSCA POR PRODUTO ========== -->



                    <!-- ========== INICIO TOTAL GERAL ========== -->
                    <tr class="destacar">
                        <td class="left" colspan="8" style="font-size: 12pt;"><strong>Total Geral</strong></td>
                        <td class="direita red" style="font-size: 12pt;"><strong><?php echo $this->formatarReal($totalVal_01_Geral); ?></strong></td>
                        <!--<th colspan="4">&nbsp;</th>-->
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <th>                
                Fonte de Recurso
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="fonteRecurso">
                    <tr class="destacar">
                        <td align="left"><b>Fonte de Recurso</b></td>
                        <td align="right"><b>Valor</b></td>
                    </tr>
<?php if (is_array($this->itensFonteRecurso) and count($this->itensFonteRecurso) > 0)
    foreach ($this->itensFonteRecurso as $fonte) {
        ?>
                            <tr>
                                <td><?php echo $fonte->Descricao ?></td>
                                <td align="right"><?php echo number_format($fonte->valor, 2, ',', '.') ?></td>
                            </tr>
    <?php } ?>
                </table>
            </td>
        </tr>
        <tr>
            <th>                
                Local de Realiza&ccedil;&atilde;o / Deslocamento
            </th>
        </tr>
        <tr>
            <td>
                <fieldset id="localRealizacao">
                    <legend>Local de Realiza&ccedil;&atilde;o</legend>
                    <table class="tabela" id="localRealizacao">
                        <tr class="destacar">
                            <td align="left"><b>Pais</b></td>
                            <td align="left"><b>UF</b></td>
                            <td align="left"><b>Cidade</b></td>
                            <!--<td align="center"><b>Dt. Inï¿½cio Execu&ccedil;&atilde;o</b></td>
                            <td align="center"><b>Dt. Final Execu&ccedil;&atilde;o</b></td>-->
                        </tr>
<?php
if (is_array($this->itensLocalRealiazacao) and count($this->itensLocalRealiazacao) > 0) {
    foreach ($this->itensLocalRealiazacao as $itensLocalRealizacao) {
        ?>
                                <tr>
                                    <td><?php echo $itensLocalRealizacao->Pais ?></td>
                                    <td><?php echo $itensLocalRealizacao->UF ?></td>
                                    <td><?php echo $itensLocalRealizacao->Cidade ?></td>
                                    <!--<td align="center"><?php //echo $itensLocalRealizacao->DtInicioDeExecucao  ?></td>
                                    <td align="center"><?php //echo $itensLocalRealizacao->DtFinalDeExecucao  ?></td>-->
                                </tr>
                            <?php }
                        } else {
                            ?>
                            <td colspan="5" align="center">N&atilde;o informado</td>
<?php } ?>
                    </table>
                </fieldset>
                <fieldset id="deslocamento">
                    <legend>Deslocamento</legend>
                    <table class="tabela" id="deslocamento">
                        <tr class="destacar">
                            <td align='left'><b>Pais de Origem</b></td>
                            <td align='left'><b>UF de Origem</b></td>
                            <td align='left'><b>Cidade de Origem</b></td>
                            <td align='left'><b>Pais de Destino</b></td>
                            <td align='left'><b>UF de Destino</b></td>
                            <td align='left'><b>Cidade de Destino</b></td>
                            <td>Quantidade</td>
                        </tr>
<?php if (is_array($this->itensDeslocamento) and count($this->itensDeslocamento) > 0) {
    foreach ($this->itensDeslocamento as $deslocamento) {
        ?>
                                <tr>
                                    <td class="esquerda"><?php echo $deslocamento->paisOrigem ?></td>
                                    <td class="esquerda"><?php echo $deslocamento->ufOrigem ?></td>
                                    <td class="esquerda"><?php echo $deslocamento->municipioOrigem ?></td>
                                    <td class="esquerda"><?php echo $deslocamento->paisDestino ?></td>
                                    <td class="esquerda"><?php echo $deslocamento->ufDestino ?></td>
                                    <td class="esquerda"><?php echo $deslocamento->municipioDestino ?></td>
                                    <td align="center" ><?php echo $deslocamento->Qtde ?></td>
                                </tr>
        <?php
    }
} else {
    ?>
                            <td colspan="7" align="center">N&atilde;o informado</td>
<?php } ?>
                    </table>
                </fieldset>
            </td>
        </tr>

        <tr>
            <th>                
                Plano de Divulga&ccedil;&atilde;o
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="planoDivulgacao">
                    <tr class="destacar">
                        <td align="left"><b>Peça de Divulga&ccedil;&atilde;o</b></td>
                        <td align="left"><b>Veículo de Divulga&ccedil;&atilde;o</b></td>
                    </tr>
                    <?php if (is_array($this->itensPlanoDivulgacao) and count($this->itensPlanoDivulgacao) > 0)
                        foreach ($this->itensPlanoDivulgacao as $divulgacao) {
                            ?>
                            <tr>
                                <td align="left"><?php echo $divulgacao->Peca ?></td>
                                <td align="left"><?php echo $divulgacao->Veiculo ?></td>
                            </tr>
                            <?php } ?>
                </table>
            </td>
        </tr>
        <tr>
            <th>                
                Documentos Anexados
            </th>
        </tr>
        <tr>
            <td>
                <fieldset id="documentosProponente">
                    <legend>Documentos Proponente</legend>
                    <?php if (is_array($this->itensDocumentoAgente) and count($this->itensDocumentoAgente) > 0) { ?>
                        <table class="tabela" id="documentosAnexados">
                            <tr class="destacar">
                                <td><b>Tipo de Documento</b></td>
                                <td><b>Nome do Documento</b></td>
                                <td><b>Data</b></td>
                            </tr>
                        <?php foreach ($this->itensDocumentoAgente as $docAgente) { ?>
                                <tr>
                                    <td align="center"><?php echo $this->documentosExigidos[$this->relacionamentoAvaliacaoDocumentosExigidos[$docPreProjeto->idArquivo]]["Descricao"] ?></td>
                                    <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $docPreProjeto->idArquivo; ?>"><?php echo $docPreProjeto->nmArquivo ?></a></td>
                                    <td align="center"><?php echo Data::formatarDataMssql($docPreProjeto->dtEnvio) ?></td>
                                </tr>
                            <?php } ?>
                        </table>
                    <?php } ?><br>
                </fieldset>

                <fieldset id="documentosProposta">
                    <legend>Documentos Proposta</legend>
                        <?php //if(is_array($this->itensDocumentoPreProjeto) and count($this->itensDocumentoPreProjeto)>0){  ?>
                    <table class="tabela" id="documentosAnexados">
                        <tr class="destacar">
                            <td><b>Tipo de Documento</b></td>
                            <td><b>Nome do Documento</b></td>
                            <td><b>Data</b></td>
                            <td><b>Observa&ccedil;&atilde;o</b></td>
                        </tr>
                            <?php foreach ($this->itensDocumentoPreProjeto as $docPreProjeto) { ?>
                            <tr>                               
                                <td align="left"><?php echo $docPreProjeto->TipoDocumento ?></td>
                                <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir-documentos-pre-projeto')); ?>?id=<?php echo $docPreProjeto->idDocumentosPreprojetos; ?>"><?php echo $docPreProjeto->NoArquivo ?></a></td>
                                <td align="left"><?php echo ConverteData($docPreProjeto->Data, 5) ?></td>
                                <td align="left"><?php echo $docPreProjeto->dsDocumento ?></td>
                            </tr>
                            <?php } ?>
                    </table>
                    <?php //}  ?><br>
                </fieldset>
            </td>
        </tr>
        <tr>
            <th>            
                Histórico de Avalia&ccedil;&otilde;es
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="historicoAvaliacoes">
                    <tr class="destacar">
                        <td align="left"><b>Data</b></td>
                        <td align="left"><b>Avalia&ccedil;&atilde;o</b></td>
                    </tr>
            <?php
                if (is_array($this->itensHistorico) and count($this->itensHistorico) > 0)
                foreach ($this->itensHistorico as $historico) {
            ?>
                            <tr>
                                <td align="left" nowrap><?php echo $historico->DtAvaliacao ?></td>
                                <td align="left"><?php echo $historico->Avaliacao ?></td>
                            </tr>
    <?php } ?>
                </table>
            </td>
        </tr>
    </table>
