<?php
if(!$this->menu){
	include_once 'scripts/admissibilidade/inc/menu.inc.php';
}
$IncluirAvaliacao                 = $this->url(array('controller' => 'admissibilidade', 'action' => 'incluiravaliacao'));
//Zend_Debug::dump($this->itensHistorico);
//die;

?>
<!--<div id="breadcrumb">
    <ul>
        <li class="first"> <a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>" title="Ir para Projetos">Projetos</a></li>
        <li class="last">Listar Propostas</li>
    </ul>
</div>-->
<div id="titulo">
    <div><?php if(!$this->tituloTopo){?>Admissibilidade de propostas - Proposta cultural<?php } else { echo $this->tituloTopo;} ?>
        <span class="voltar">
            <?php if(isset($_GET['gravado']) && $_GET["gravado"]=="sim" ) :?>
                <a href="<?php echo $this->url(array('controller' => 'admissibilidade', 'action' => 'listar-propostas'))."?idPreProjeto=".$this->idPreProjeto; ?>"/>Voltar</a>
           <?php else: ?>
                <a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a>
            <?php endif; ?>
        </span>
    </div>
</div>
<style type="text/css">
.mensagem {
    padding: 8px;
    border: darkgreen;
    background: #e3e3c7;
}
</style>
<script type="text/javascript">
    /*
     * Fun&ccedil;&atilde;o responsável pela exibi&ccedil;&atilde;o ou ocultamento de conteúdo,
     * mudando a imagem.
     **/
    $(document).ready(function(){
        $('#novo').click(function(){

            $('#preProjeto').attr('action','<?php echo $IncluirAvaliacao;?>');
            $('#preProjeto').submit();

        });
        $('#novo1').click(function(){

            $('#preProjeto').attr('action','<?php echo $IncluirAvaliacao;?>');
            $('#preProjeto').submit();

        });
        $('.btn_imprimir').click(function(){
          // $("#html").html($(".conteudoImprimir").html());
           $("#formGerarPdf").submit();
        });

    });
    function abrirDinamico(elemento, obj) {
        if($(elemento).css('display') == 'none') {
            $(elemento).fadeIn('fast', function() {
                $('img', $(obj)).attr('src','<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png');
            });
        } else {
            $(elemento).fadeOut('fast', function() {
                $('img', $(obj)).attr('src','<?php echo $this->baseUrl(); ?>/public/img/navigation-baixo.PNG');
            });
        }
    }
    function toogleAjax(id, url){
        if(!url) {
            $('#'+id).toggle('slow');
        } else {
            elemento = '#'+id;
            if($(elemento).css('display') == 'none') {
                $(elemento).html('<img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /> ');
                $(elemento).fadeIn('fast');
                $.ajax({
                    type: "POST",
                    data: {
                        teste: 'testando'
                    },
                    url: url,
                    success: function(data) {
                        $(elemento).html(data);
                    }
                });
            } else {
                $(elemento).fadeOut('fast');
            }
        }
    };

    function AbrirFecharPlanilha(elemento)
    {
            $('.' + elemento).toggle();

            if ($('#' + elemento).hasClass('icn_mais'))
            {
                    $('#' + elemento).addClass('icn_menos');
                    $('#' + elemento).removeClass('icn_mais');
            }
            else
            {
                    $('#' + elemento).addClass('icn_mais');
                    $('#' + elemento).removeClass('icn_menos');
            }
    }
</script>
<div id="conteudo">
<form method="get" id="formGerarPdf" target="_blank" action="<?php echo $this->url(array('controller' => 'admissibilidade', 'action' => 'imprimirpropostacultural')); ?>" style="display:none">
    <textarea name="html" id="html"></textarea>
    <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto; ?>" />
</form>
    <form id="preProjeto" method="post">
        <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto; ?>" />
        <!--<input type="hidden" name="nomeProjeto" id="nomeProjeto" value="<?php echo $this->itensGeral[0]->NomeProjeto ?>" />-->
    </form>
    <br />
    <div align="center">
        <?php if((isset($_GET['realizar_analise']) && $_GET['realizar_analise']=="sim")):?>
        <input type="button" id="novo" class="btn_novo"/>
        <?php endif; ?>
        <iframe name="esconde" id="esconde" class="sumir"> </iframe>
        <!--<a href="<?php echo $this->url(array('controller' => 'admissibilidade', 'action' => 'imprimirpropostacultural'))."?idPreProjeto=".$this->idPreProjeto; ?>" target="esconde">
        <input type="button" class="btn_imprimir"/>
        </a>-->

        <input type="button" class="btn_imprimir" title="Imprimir" />

        <!--<input type="button" class="btn_sair" onclick="voltar();"/>
        <input  type="button" name="imprimir" class="btn_imprimir" onclick='$("#conteudoImprimir").val($(".conteudoPdf").html()); $("#formGerarPdf").submit();'>-->
    </div>

    <div class="conteudoImprimir">
    <table class="tabela">
        <tr onclick="abrirDinamico('#proponente', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Proponente
            </th>
        </tr>
        <tr>
            <td align="center">
                <div id="proponente">
                <table class="tabela">
                    <tr>
                        <td class="red bold destacar" style="font-size: 14px;">Edital - <?php echo $this->nmEdital; ?></td>
                    </tr>
                </table>
                <fieldset>
                    <legend>Identifica&ccedil;&atilde;o</legend>
                    <table class="tabela">
                        <tr>
                            <td width="10%" class="esquerda destacar"><b>CNPJ / CPF</b></td>
                            <td class="esquerda"><?php echo (strlen($this->itensGeral[0]->CNPJCPF) > 11)?aplicaMascara($this->itensGeral[0]->CNPJCPF, "99.999.999/9999-99"):  aplicaMascara($this->itensGeral[0]->CNPJCPF, "999.999.999-99") ?></td>
                            <td width="10%" class="esquerda destacar"><b>Proponente</b></td>
                            <td class="esquerda"><?php echo $this->itensGeral[0]->NomeAgente ?></td>
                        </tr>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Endere&ccedil;o</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td width="10%" nowrap class="centro"><b>Tipo de Endereço</b></td>
                            <td width="10%" nowrap class="centro"><b>Tipo do Logradouro</b></td>
                            <td width="20%" class="centro"><b>Logradouro</b></td>
                            <td class="centro"><b>Número</b></td>
                            <td class="centro"><b>Complemento</b></td>
                            <td class="centro"><b>Bairro</b></td>
                            <td class="centro"><b>Cidade</b></td>
                            <td class="centro"><b>UF</b></td>
                            <td class="centro"><b>CEP</b></td>
                        </tr>
                        <?php $auxEndCEP = ""; $auxEndLogra = ""; ?>
                        <?php if(is_array($this->itensGeral) and count($this->itensGeral)>0){
                                 foreach($this->itensGeral as $endereco){ ?>
                                 <?php if($endereco->CEP != $auxEndCEP || $endereco->Logradouro != $auxEndLogra): ?>
                                    <tr>
                                        <td><?php echo $endereco->endereco ?></td>
                                        <td><?php echo $endereco->logradouro ?></td>
                                        <td><?php echo $endereco->Logradouro ?></td>
                                        <td><?php echo $endereco->Numero ?></td>
                                        <td><?php echo $endereco->Complemento ?></td>
                                        <td><?php echo $endereco->Bairro ?></td>
                                        <td><?php echo $endereco->NomeCidade ?></td>
                                        <td><?php echo $endereco->SiglaUf ?></td>
                                        <td><?php echo aplicaMascara($endereco->CEP, "99999-999") ?></td>
                                    </tr>
                                  <?php endif; ?>
                                  <?php $auxEndCEP = $endereco->CEP; ?>
                                  <?php $auxEndLogra = $endereco->Logradouro; ?>
                            <?php  }
                               } ?>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Telefones</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td width="10%"><b>Tipo</b></td>
                            <td><b>UF</b></td>
                            <td><b>DDD</b></td>
                            <td><b>Número</b></td>
                            <td><b>Divulgar</b></td>
                        </tr>
                        <?php if(is_array($this->itensTelefone) and count($this->itensTelefone)>0){
                                 foreach($this->itensTelefone as $telefone){ ?>
                                    <tr>
                                        <td><?php echo $telefone->Descricao ?></td>
                                        <td><?php echo $telefone->Sigla ?></td>
                                        <td><?php echo $telefone->DDD ?></td>
                                        <td><?php echo $telefone->Numero ?></td>
                                        <td><?php if($telefone->Divulgar == 1) echo "Sim"; else echo "Nao"; ?></td>
                                    </tr>
                        <?php    }
                              } ?>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>E-mail</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td width="10%"><b>Tipo</b></td>
                            <td><b>E-mail</b></td>
                            <td><b>Para correspond&ecirc;ncia?</b></td>
                            <td><b>Posso divulgar?</b></td>
                        </tr>
                        <?php $auxEmail = array(); $auxEmailTipo = array(); ?>
                        <?php foreach($this->itensGeral as $email){ ?>
                        <?php if(!in_array($email->agente, $auxEmail) || !in_array($email->email, $auxEmailTipo)): ?>
                                    <tr>
                                        <td nowrap><?php echo $email->email ?></td>
                                        <td nowrap><?php echo $email->agente ?></td>
                                        <td><?php if($email->divulgarEmail == 1) echo "Sim"; else echo "Nao"; ?></td>
                                        <td><?php if($email->divulgarEmail == 1) echo "Sim"; else echo "Nao"; ?></td>
                                    </tr>
                        <?php endif; ?>
                        <?php $auxEmail[] = $email->agente; ?>
                        <?php $auxEmailTipo[] = $email->email; ?>
                        <?php } ?>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Natureza</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td width="10%"><b>Direito</b></td>
                            <td><b>Esfera</b></td>
                            <td><b>Poder</b></td>
                            <td><b>Administra&ccedil;&atilde;o</b></td>
                        </tr>
                        <tr>
                            <?php if(!empty($this->itensGeral[0]->direito)){ ?>
                                <td nowrap><?php echo $this->itensGeral[0]->direito ?></td>
                                <td><?php echo $this->itensGeral[0]->esfera ?></td>
                                <td><?php echo $this->itensGeral[0]->poder ?></td>
                                <td><?php echo $this->itensGeral[0]->Admins ?></td>
                            <?php }else{ ?>
                                <td colspan="4" align="center">Natureza n&atilde;o informada</td>
                            <?php } ?>
                        </tr>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Dirigente</legend>
                        <table class="tabela">
                            <?php if ($this->dirigentes && count($this->dirigentes)>0) { ?>
                                <tr class="destacar">
                                    <td width="20%" align="center"><b>CPF</b></td>
                                    <td align="center"><b>Nome</b></td>
                                </tr>
                                    <?php foreach ($this->dirigentes as $tbdirigentes): ?>
                                        <?php if($tbdirigentes->CNPJCPFDirigente != '00000000000000'): ?>
                                            <tr>
                                                <td align="center"><?php echo empty($tbdirigentes->CNPJCPFDirigente) ? '<em>Dados n&atilde;o informados!</em>' : aplicaMascara($tbdirigentes->CNPJCPFDirigente, "999.999.999-99"); ?>
                                                <td align="left"><?php echo $tbdirigentes->NomeDirigente; ?></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>
                                                    <table class='tabela'>           
                                                        <tr class="destacar">
                                                            <td class="centro" colspan="4">Mandatos</td>
                                                        </tr>
                                                        <?php if(count($this->mandatos[$tbdirigentes->NomeDirigente]) > 0):
                                                                foreach ($this->mandatos[$tbdirigentes->NomeDirigente] as $mandato): ?>  
                                                                    <tr>
                                                                        <td>
                                                                            <b>Tipo de documento</b><br>
                                                                            <?php echo $mandato->Descricao;?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Nº do documento</b><br>
                                                                            <?php echo $mandato->dsNumeroDocumento;?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Per&iacute;odo de vig&ecirc;ncia</b><br>
                                                                            <?php echo date('d/m/Y',strtotime($mandato->dtInicioMandato)).' à '.date('d/m/Y',strtotime($mandato->dtFimMandato)); ?>
                                                                        </td>
                                                                        <td>
                                                                            <b>Arquivo</b><br>
                                                                            <a href="<?php echo $this->url(array('controller'=>'upload','action'=>'abrir')); ?>?id=<?php echo $mandato->idArquivo; ?>"><?php echo $mandato->nmArquivo ?></a>
                                                                        </td>
                                                                    </tr>
                                                                    <?php endforeach; ?>
                                                           <?php else: ?>
                                                                <tr>
                                                                    <td class="centro" colspan="4"><em>N&atilde;o existem mandatos cadastrados!</em></td>
                                                                </tr>
                                                           <?php endif; ?>
                                                    </table>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                            <?php } else { ?>
                                    <tr>
                                        <td colspan="2" align="center"><em>N&atilde;o existem Dirigentes cadastrados!</em></td>
                                    </tr>
                            <?php } ?>
                        </table>
                    </fieldset> 
                <?php if(is_array($this->itensGeral) and !empty($this->itensGeral[0]->nomeUsuario)){ ?>
                <fieldset>
                    <legend>Usu&aacute;rio SalicWEB</legend>
                    <table class="tabela">
                        <tr>
                            <td width="10%" class="esquerda destacar"><b>CPF</b></td>
                            <td width="40%" class="esquerda"><?php echo aplicaMascara($this->itensGeral[0]->Cpf, "999.999.999-99"); ?></td>
                            <td width="10%" class="esquerda destacar"><b>Nome</b></td>
                            <td width="40%" class="esquerda"><?php echo $this->itensGeral[0]->nomeUsuario ?></td>
                        </tr>
                    </table>
                </fieldset>
                <?php } ?>
                </div><!-- fecha div proponente -->
            </td>
        </tr>
        <tr onclick="abrirDinamico('#projetoCultural', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Proposta cultural
            </th>
        </tr>
        <tr>
            <td>
                <div id="projetoCultural">
                <fieldset>
                    <legend>Identifica&ccedil;&atilde;o</legend>
                    <table class="tabela">
                        <tr>
                        <?php if(is_array($this->itensGeral) and count($this->itensGeral)>0){ ?>
                            <td width="10%" class="destacar"><b>N&ordm; da Proposta</b></td>
                            <td><?php echo $this->itensGeral[0]->idPreProjeto ?></td>
                            <td width="10%" nowrap class="destacar"><b>T&iacute;tulo da Proposta</b></td>
                            <td><?php echo $this->itensGeral[0]->NomeProjeto ?></td>
                        <?php } ?>
                        </tr>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Informaç&otilde;es Complementares</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td><b>&Eacute; proposta de audiovisual?</b></td>
                            <td><b>Mecanismo</b></td>
                            <td><b>Ag&ecirc;ncia Banc&aacute;ria</b></td>
                            <td><b>Dt. In&iacute;cio Execuç&atilde;o</b></td>
                            <td><b>Dt. Final Execu&ccedil;&atilde;o</b></td>
                            <td><b>Dt. Fixa</b></td>
                            <td><b>Plano Atual</b></td>
                        </tr>
                        <?php if(is_array($this->itensGeral) and count($this->itensGeral)>0){ ?>
                        <tr>
                            <td><?php if($this->itensGeral[0]->AreaAbrangencia == 1) echo "Sim"; else echo "Nao"; ?></td>
                            <td><?php if($this->itensGeral[0]->Mecanismo == 1) echo "Incentivo Fiscal Federal"; ?></td>
                            <td><?php echo $this->itensGeral[0]->AgenciaBancaria ?></td>
                            <td><?php echo substr($this->itensGeral[0]->DtInicioDeExecucao,0,10) ?></td>
                            <td><?php echo substr($this->itensGeral[0]->DtFinalDeExecucao,0,10) ?></td>
                            <td><?php if($this->itensGeral[0]->stDataFixa == 1) echo "Sim"; else echo "Nao"; ?></td>
                            <td><?php if($this->itensGeral[0]->stPlanoAnual == 1) echo "Sim"; else echo "Nao"; ?></td>
                        </tr>
                        <?php }?>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Informaç&otilde;es sobre tombamento</legend>
                    <table class="tabela">
                        <tr class="destacar">
                            <td><b>N&ordm; Ato Tombamento</b></td>
                            <td><b>Dt. Ato Tombamento</b></td>
                            <td><b>Esfera Tombamento</b></td>
                        </tr>
                        <?php if(is_array($this->itensGeral)  and isset($this->itensGeral[0]->EsferaTombamento) and !empty($this->itensGeral[0]->EsferaTombamento)){ ?>
                        <tr>
                            <td><?php echo $this->itensGeral[0]->NrAtoTombamento ?></td>
                            <td><?php echo $this->itensGeral[0]->DtAtoTombamento ?></td>


                            <?php $esferaTombamento = array('','Municipal','Estadual','Federal') ?>

                            <td><?php echo $esferaTombamento[$this->itensGeral[0]->EsferaTombamento] ?></td>
                        </tr>
                        <?php } else {?>
                        <td colspan="3" align="center">N&atilde;o informado</td>
                        <?php } ?>
                    </table>
                </fieldset>

                <fieldset>
                    <legend>Resumo do Projeto</legend>
                    <table class="tabela">
                        <?php if(is_array($this->itensGeral) and count($this->itensGeral)>0){ ?>
                        <tr>
                            <td><?php  echo (strip_tags($this->itensGeral[0]->ResumoDoProjeto))?strip_tags($this->itensGeral[0]->ResumoDoProjeto,"<b></b><ul></ul><li></li><strong></strong><i></i><p></p><br>"):"N&atilde;o informado."; ?></td>
                        </tr>
                        <?php }?>
                    </table>
                </fieldset>
                </div><!-- fecha div proposta cultural -->
            </td>
        </tr>
        <tr onclick="abrirDinamico('#localRealizacao', $(this)); abrirDinamico('#deslocamento', $(this));" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Local de Realiza&ccedil;&atilde;o / Deslocamento
            </th>
        </tr>
        <tr>
            <td>
                <fieldset id="localRealizacao">
                    <legend>Local de Realiza&ccedil;&atilde;o</legend>
                    <table class="tabela" id="localRealizacao">
                        <tr class="destacar">
                            <td align="left"><b>Pais</b></td>
                            <td align="left"><b>UF</b></td>
                            <td align="left"><b>Cidade</b></td>
                            <!--<td align="center"><b>Dt. Início Execu&ccedil;&atilde;o</b></td>
                            <td align="center"><b>Dt. Final Execu&ccedil;&atilde;o</b></td>-->
                        </tr>
                            <?php
                               if(is_array($this->itensLocalRealiazacao) and count($this->itensLocalRealiazacao)>0){
                               foreach($this->itensLocalRealiazacao as $itensLocalRealizacao){
                              ?>
                                <tr>
                                    <td><?php echo $itensLocalRealizacao->Pais ?></td>
                                    <td><?php echo $itensLocalRealizacao->UF ?></td>
                                    <td><?php echo $itensLocalRealizacao->Cidade ?></td>
                                    <!--<td align="center"><?php //echo $itensLocalRealizacao->DtInicioDeExecucao ?></td>
                                    <td align="center"><?php //echo $itensLocalRealizacao->DtFinalDeExecucao ?></td>-->
                                </tr>
                            <?php }
                               }else{ ?>
                            <td colspan="5" align="center">N&atilde;o informado</td>
                            <?php } ?>
                    </table>
                </fieldset>
            </td>
            </tr>
        <tr onclick="abrirDinamico('#documentosProponente', $(this)); abrirDinamico('#documentosProposta', $(this));" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Documentos Anexados
            </th>
        </tr>
        <tr>
            <td>
                <fieldset id="documentosProponente">
                    <legend>Documentos Proponente</legend>
                    <?php $ctArqProponente = 0; ?>
                    <?php if(is_array($this->itensDocumentoPreProjeto) && count($this->itensDocumentoPreProjeto)>0): ?>
                    <table class="tabela" id="documentosAnexados">
                        <?php foreach ($this->itensDocumentoPreProjeto as $documentoPreProjeto): ?>
                        <?php foreach ($documentoPreProjeto as $docPreProjeto): ?>
                        <?php if($this->documentosExigidos[$this->relacionamentoAvaliacaoDocumentosExigidos[$docPreProjeto->idArquivo]]["Opcao"] == "1"): ?>
                        <?php if($ctArqProponente == 0): ?>
                        <?php $ctArqProponente++; ?>
                        <tr class="destacar">
                            <td width="50%" nowrap><b>Tipo de Documento</b></td>
                            <td width="40%" nowrap><b>Nome do Documento</b></td>
                            <td width="10%" nowrap><b>Data</b></td>
                        </tr>
                        <?php endif; ?>
                        <tr>
                            <td align="left"><?php echo $this->documentosExigidos[$this->relacionamentoAvaliacaoDocumentosExigidos[$docPreProjeto->idArquivo]]["Descricao"] ?></td>
                            <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $docPreProjeto->idArquivo; ?>"><?php echo $docPreProjeto->nmArquivo ?></a></td>
                            <td align="center"><?php echo Data::formatarDataMssql($docPreProjeto->dtEnvio) ?></td>
                        </tr>
                        <?php endif; ?>
                        <?php endforeach; ?>
                        <?php endforeach; ?>
                    </table>
                        <?php endif; ?>
                    <?php if(is_object($this->itensDocumentoProposta) && count($this->itensDocumentoProposta)>0): ?>
                    <table class="tabela" id="documentosAnexados2">
                        <?php foreach ($this->itensDocumentoProposta as $documentoProposta): ?>
                            <?php if($documentoProposta->Opcao == "1"): ?>
                                <?php if($ctArqProponente == 0): ?>
                                <?php $ctArqProponente++; ?>
                                <tr class="destacar">
                                    <td width="50%" nowrap><b>Tipo de Documento</b></td>
                                    <td width="40%" nowrap><b>Nome do Documento</b></td>
                                    <td width="10%" nowrap><b>Data</b></td>
                                </tr>
                                <?php endif; ?>
                                <tr>
                                    <td align="left"><?php echo $documentoProposta->TipoDocumento; ?></td>
                                    <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir-documentos-pre-projeto')); ?>?id=<?php echo $documentoProposta->idDocumentosPreprojetos; ?>"><?php echo $documentoProposta->NoArquivo ?></a></td>
                                    <td align="center"><?php echo date("d/m/Y",strtotime($documentoProposta->Data)); ?></td>
                                </tr>
                             <?php endif; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php endif; ?>
                    <?php if($ctArqProponente == 0): ?>
                    <table class="tabela">
                        <tr class="destacar">
                            <td align="center">N&atilde;o informado</td>
                        </tr>
                    </table>
                    <?php endif; ?>
                </fieldset>

                <fieldset id="documentosProposta">
                    <legend>Documentos Proposta</legend>
                    <?php $ctArqProposta = 0; ?>
                    <?php if(is_array($this->itensDocumentoPreProjeto) && count($this->itensDocumentoPreProjeto)>0): ?>
                    <table class="tabela" id="documentosAnexados">
                        <?php foreach ($this->itensDocumentoPreProjeto as $documentoPreProjeto): ?>
                            <?php foreach ($documentoPreProjeto as $docPreProjeto): ?>
                                <?php if($this->documentosExigidos[$this->relacionamentoAvaliacaoDocumentosExigidos[$docPreProjeto->idArquivo]]["Opcao"] == "2"): ?>
                                <?php if($ctArqProposta == 0): ?>
                                <?php $ctArqProposta++; ?>
                                <tr class="destacar">
                                    <td width="50%" nowrap><b>Tipo de Documento</b></td>
                                    <td width="40%" nowrap><b>Nome do Documento</b></td>
                                    <td width="10%" nowrap><b>Data</b></td>
                                </tr>
                                <?php endif; ?>
                                <tr>
                                    <td align="left"><?php echo $this->documentosExigidos[$this->relacionamentoAvaliacaoDocumentosExigidos[$docPreProjeto->idArquivo]]["Descricao"] ?></td>
                                    <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $docPreProjeto->idArquivo; ?>"><?php echo $docPreProjeto->nmArquivo ?></a></td>
                                    <td align="center"><?php echo Data::formatarDataMssql($docPreProjeto->dtEnvio) ?></td>
                                </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php endif; ?>
                    <?php if(is_object($this->itensDocumentoProposta) && count($this->itensDocumentoProposta)>0): ?>
                    <table class="tabela" id="documentosAnexados2">
                        <?php foreach ($this->itensDocumentoProposta as $documentoProposta): ?>
                            <?php if($documentoProposta->Opcao == "2"): ?>
                                <?php if($ctArqProposta == 0): ?>
                                <?php $ctArqProposta++; ?>
                                <tr class="destacar">
                                    <td width="50%" nowrap><b>Tipo de Documento</b></td>
                                    <td width="40%" nowrap><b>Nome do Documento</b></td>
                                    <td width="10%" nowrap><b>Data</b></td>
                                </tr>
                                <?php endif; ?>
                                <tr>
                                    <td align="left"><?php echo $documentoProposta->TipoDocumento; ?></td>
                                    <td align="left"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir-documentos-pre-projeto')); ?>?id=<?php echo $documentoProposta->idDocumentosPreprojetos; ?>"><?php echo $documentoProposta->NoArquivo ?></a></td>
                                    <td align="center"><?php echo date("d/m/Y",strtotime($documentoProposta->Data)); ?></td>
                                </tr>
                             <?php endif; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php endif; ?>
                    <?php if($ctArqProposta == 0): ?>
                    <table class="tabela">
                        <tr class="destacar">
                            <td align="center">N&atilde;o informado</td>
                        </tr>
                    </table>
                    <?php endif; ?>
                </fieldset>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#historicoAvaliacoes', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Histórico de Avalia&ccedil;&otilde;es
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="historicoAvaliacoes">
                    <tr class="destacar">
                        <!--<td align="left"><b>Ator</b></td>-->
                        <td align="left"><b>Data</b></td>
                        <td align="left"><b>Avalia&ccedil;&atilde;o</b></td>
                    </tr>
                    <?php
                        if(is_array($this->itensHistorico) and count($this->itensHistorico)>0):
                            foreach ($this->itensHistorico as $historico){ ?>
                    <tr>
                        <!--<td align="left" nowrap><?php echo $historico->usu_Nome ?></td>-->
                        <td align="left" nowrap><?php echo ConverteData($historico->DtAvaliacao, 25) ?></td>
                        <td align="left"><?php echo $historico->Avaliacao ?></td>
                    </tr>
                    <?php if($historico->dtResposta != "" && strlen(strip_tags($historico->dsResposta)) > 1): ?>
                    <tr>
                        <!--<td align="left" nowrap><?php echo $historico->usu_Nome ?></td>-->
                        <td align="left" nowrap><?php echo ConverteData($historico->dtResposta, 25) ?></td>
                        <td align="left"><?php echo strip_tags($historico->dsResposta) ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php } endif; ?>
                </table>
            </td>
        </tr>
        <?php if(count($this->perguntas) > 0): ?>
        <tr onclick="abrirDinamico('#questionario', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl();?>/public/img/navigation-right.png" id="imgDinamica" align="left" />
                Question&aacute;rio
            </th>
        </tr>
        <?php foreach($this->perguntas as $registro): ?>
        <tr>
            <td width="100%">
                <table class="tabela" id="questionario">
                    <tr class="destacar">
                        <td align="left" colspan="2" width="100%"><b><?php echo $registro["titulo"]; ?></b></td>
                    </tr>
                    <tr>
                        <td align="center" width="50%"><b>Pergunta</b></td>
                        <td align="center" width="50%"><b>Resposta(s)</b></td>
                    </tr>
                    <?php foreach ($registro["pergunta"] as $pergunta): ?>
                    <tr>
                        <td align="left"><?php echo $pergunta["dsPergunta"] ?></td>
                        <td align="left">
                            <?php foreach($this->respostas as $resposta): ?>
                                <?php foreach($resposta as $resp): ?>
                                    <?php if($pergunta["nrPergunta"] == $resp["nrPergunta"]): ?>
                                        <?php if(($resp["dsRespostaSubj"]) != "" && trim($resp["dsRespostaSubj"]) != ""): ?>
                                             - <?php echo $resp["dsRespostaSubj"] ?><br />
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
    </table>
    </div><!-- fecha div de impressao -->
    <br />
    <table class="tabela">
	<tr>
	<td class="centro">
        <?php if((isset($_GET['realizar_analise']) && $_GET['realizar_analise']=="sim")):?>
        <input type="button" id="novo1" class="btn_novo" title="Novo" />
        <?php endif; ?>
        <input type="button" class="btn_imprimir" title="Imprimir" />
	</td>
	</tr>
    </table>
</div>
<!-- ========== FIM CONTEUDO ========== -->
<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />