<script> 
    $(document).ready(function(){
         JSVisualizarProjetoDaGrid();
    }); //fecha document.read
    
    $(".orderByPI").click(function(){
        var campo = $(this).attr("valorOrdenacaoPI");

        if("ASC" == $("#tipoOrdenacaoPI").val()){
            tipo = "DESC";
        }else{
            tipo = "ASC";
        }

        ordenarPI(campo, tipo);
    });

    $(".orderByPI").each(function(){
        if($("#ordenacaoPI").val() == $(this).attr("valorOrdenacaoPI")){
            if($("#tipoOrdenacaoPI").val() == "ASC"){
                $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-baixo.PNG" align="absmiddle"></span>');
            }else{
                $(this).after('<span style="padding-left:4px;"><img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-cima.PNG" align="absmiddle"></span>');
            }
        }
    });
    
    function ordenarPI(campo, tipo){
        $("#ordenacaoPI").val(campo);
        $("#tipoOrdenacaoPI").val(tipo);
        paginarProponenteIrregular(1);
    }

    function paginarProponenteIrregular(pag){
        $("#pagPI").val(pag);
        jqAjaxForm(document.getElementById("frmProponenteIrregular"), "proponenteirregular_resultado");
        $("#proponenteirregular_resultado").html("");
        $('#proponenteirregular_resultado').html('<br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
    }
</script>
<?php
    header('Content-Type: text/plain; charset=ISO-8859-1');
?>
<!-- ================================================================-->
<!-- ================ PROPONENTE DILIGENCIADO =======================-->
<!-- ================================================================-->
<table class="tabela tablesorter" id="irregularAP" tipo="irregularAP">
    <?php if (count($this->proponenteIrregular) <= 0) : ?>
    <tr>
            <td align="center" colspan="<?php if (!empty($this->coordenador)){ echo 18; } else { echo 16; }?>"><em>Nenhum Projeto Aprovado - Proponente Irregular</em></td>
    </tr>
    <?php else: ?>
    <thead>
        <tr>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="1">pronac</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="2">Nome do Projeto</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="20">Área Cultural/Segmento</a></th>
            <th>Resumo</th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="9">UF</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="22">Art.</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="12">Período de Capta&ccedil;&atilde;o</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="10">Período de Execu&ccedil;&atilde;o</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="19">Valor Aprovado</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="25">N° da Reunião</a></th>
            <?php if (!empty ($this->coordenador ) ){?>
                <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="28">Técnico</a></th>
            <?php }?>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="29">Status</a></th>
            <th><a href="#proponenteirregular_resultado" class="orderByPI" valorOrdenacaoPI="31">Tempo de Análise</a></th>
            <th>Regularidade do Proponente</th>
            <th>Dilig&ecirc;ncia</th>
            <th id="testetoltip">Alterar</th>
            <th>Enviar Mensagem</th>
            <th>Finalizar Análise</th>
            <?php if (!empty ($this->coordenador ) ){?>
                <th>Encaminhar Para Portaria</th>
            <?php }?> 
        </tr>
    </thead>
    <tbody>
    <?php
    if ( !empty ( $this->proponenteIrregular ) ){
        foreach ($this->proponenteIrregular as $projeto) { ?>
            <tr id="scroll<?php echo $projeto['idpronac'];?>">
                <td>
                    <a target="_blank" href="<?php echo $this->url ( array ('controller' => 'consultardadosprojeto', 'action' => '' ),'',true ) . '?idPronac=' . $projeto['idpronac']; ?>" class="itenspronac" style="text-decoration: underline; cursor: pointer;">
                        <?php echo $this->escape($projeto['pronac']); ?>
                    </a>
                    <!--<a id="consultarprojetos" href="<?php //echo $this->url(array('controller' => 'dadosprojeto', 'action' => 'index', 'idpronac'=>$projeto['IdPRONAC']),'',true); ?>" target="_new" title="Ir para Consultar Projetos">
                        <?php //echo $this->escape($projeto['pronac']); ?>
                    </a>-->
                </td>
                <td><?php echo $this->escape($projeto['NomeProjeto']); ?></td>
                <td><?php echo $this->escape($projeto['area']); ?><br/>/<?php echo $this->escape($projeto['segmento']); ?></td>
                <td>
                    <div class="sumir" id="resumo_<?php echo $this->escape($projeto['pronac']); ?>"><?php echo $this->escape($projeto['ResumoProjeto']); ?></div>
                    <center><a name="#resumo" style="cursor:pointer;" onclick="JSAbrirModal( $('#resumo_<?php echo $this->escape($projeto['pronac']); ?>').html() );"><img src="<?php echo $this->baseUrl();?>/public/img/ico/eye.png" /></a></center>
                </td>
                <td><?php echo $this->escape($projeto['UfProjeto']); ?></td>
                <td><?php echo $this->escape($projeto['enquadramento']); ?></td>
                <td>
                    <?php echo $this->escape(Data::tratarDataZend($projeto['DtInicioCaptacao'], 'brasileiro')); ?>
                    <?php echo $this->escape(Data::tratarDataZend($projeto['DtFimCaptacao'], 'brasileiro')); ?>
                </td>
                <td>
                    <?php echo $this->escape(Data::tratarDataZend($projeto['DtInicioExecucao'], 'brasileiro')); ?>
                    <?php echo $this->escape(Data::tratarDataZend($projeto['DtFimExecucao'], 'brasileiro')); ?>
                </td>
                <td><?php echo $this->escape($this->formatarReal($projeto['AprovadoReal'])); ?></td>
                <td class="centro"><?php echo $this->escape($projeto['NrReuniao']); ?></td>
                <?php if (!empty ($this->coordenador ) ){?>
                    <td align="center">
                        <?php echo $this->escape($projeto['NomeTecnico']); ?>
                    </td>
                <?php }?>
                <td align="center">
                    <?php if($projeto['stAnaliseProjeto'] == '1' || empty($projeto['stAnaliseProjeto'])) $bg = '#FF7B00';?>
                    <?php if($projeto['stAnaliseProjeto'] == '2') $bg = '#16C0C9';?>
                    <?php if($projeto['stAnaliseProjeto'] == '3') $bg = '#66B20A';?>
                    <span style="font-weight: bold; color: <?php echo $bg;?>"><?php echo $this->escape($projeto['status']); ?></span>
                </td>
                <td align="center"><?php echo $this->escape($projeto['tempoAnalise']); ?> dias</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ico/archive.png" onclick="JSRegularidadeProponente('<?php echo ($projeto['CgcCpf']); ?>')" style="cursor: pointer"/></td>
                <td align="center">
                <?php
                    $arrPrazo = $this->prazoRespostaDiligencia($projeto['idpronac'], $this->codDiligencia);
                    $icone = $arrPrazo['iconeDiligencia']['icone'];
                    $title = $arrPrazo['iconeDiligencia']['title'];
                ?>
                <a target="_blank" href="<?php echo $this->url(array('controller' => 'diligenciar', 'action' =>'listardiligenciaanalista')).'?idPronac=' . $projeto['idpronac'] . '&situacao=D25&tpDiligencia=181';?>" ><img src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $icone; ?>" title="<?php echo $title; ?>" width="30px"/></a><br>
                <?php echo (!empty($arrPrazo['prazoPadrao']) && $title != "Diligencia respondida") ? $arrPrazo['prazoRespostaCrescente'] ." de ". $arrPrazo['prazoPadrao'] : "";?>
                </td>
                <td>
                    <input type="button" name="alterar" id="alterar" class="btn_alterar" onclick="JSAlterarProjeto('<?php echo ($projeto['idpronac']); ?>','proponenteirregular')" title="Alterar projeto">
                </td>
                <td id="colunafinalizar<?php echo ($projeto['idpronac']); ?>">
                    <?php if($projeto['stAnaliseProjeto'] == '1' || $projeto['stAnaliseProjeto'] == '2' ): ?>
                        <input type="button" name="finalizar" id="finalizar" class="btn_finalizar" onclick="JSFinalizarAnalise('<?php echo ($projeto['idpronac']); ?>','<?php echo ($projeto['idAprovacao']); ?>','proponenteirregular')"  title="Finalizar análise">
                    <?php else: ?>    
                        <input type="button" name="finalizar" id="finalizar" class="btn_finalizar-off">
                    <?php endif; ?>
                </td>
                <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $projeto['idpronac']; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                <?php if (!empty ($this->coordenador ) ){?>
                    <td align="center">
                        <?php if ($projeto['stAnaliseProjeto'] == '3'){ //Analise finalizada?>
                            <img id="encaminhar" src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" style="cursor: pointer" onclick="JSEncaminharPortaria(<?php echo $this->escape($projeto['idpronac']); ?>)"/>
                        <?php }?>
                    </td>
                <?php }?>
            </tr>
            <?php
        }
    }
    ?>
    <?php endif; ?>
    </tbody>
</table>

<!-- FORMULARIO DE PAGINACAO/ORDENACAO -->
<form action="<?php echo $this->url(array('controller' => 'checklistpublicacao', 'action' => 'proponente-irregular', 'tipoAnalise' => $this->tipoAnalise)); ?>" method="post" name="frmProponenteIrregular" id="frmProponenteIrregular">
    <input type="hidden" class="input_simples" name="idPronac" id="idPronac" value="<?php echo $this->idPronac; ?>"/>
<?php if(!empty($this->parametrosBuscaPI)) foreach($this->parametrosBuscaPI as $name=>$value):?>
    <?php if(!is_array($value)): ?>
    <input type="hidden" name="<?php echo $name?>" id="<?php echo $name?>" value="<?php echo utf8_decode($value)?>"/>
    <?php else: ?>
        <?php foreach($value as $valor):?>
            <input type="hidden" name="<?php echo $name?>[]" id="<?php echo $name?>" value="<?php echo utf8_decode($valor)?>"/>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>
    <?php if(empty($this->parametrosBuscaPI["pagPI"])):?>
    <input type="hidden" name="pagPI" id="pagPI" value="<?php echo $this->pagPI; ?>"/>
    <?php endif; ?>
    <?php if(empty($this->parametrosBuscaPI["ordenacaoPI"])):?>
    <input type="hidden" name="ordenacaoPI" id="ordenacaoPI" value="<?php echo (!empty($this->parametrosBuscaPI["ordenacaoPI"]))?$this->parametrosBuscaPI["ordenacaoPI"]:""; ?>"/>
    <?php endif; ?>
    <?php if(empty($this->parametrosBuscaPI["tipoOrdenacaoPI"])):?>
    <input type="hidden" name="tipoOrdenacaoPI" id="tipoOrdenacaoPI" value="<?php echo (!empty($this->parametrosBuscaPI["tipoOrdenacaoPI"]))?$this->parametrosBuscaPI["tipoOrdenacaoPI"]:""; ?>"/>
    <?php endif; ?>
</form>