<div class="container" id="app"> <!-- inicio do container -->
    <agente-form></agente-form>


    <div class="row center-align">
        <div class="col s4 offset-s4">
            <a href="#" class="btn">Salvar</a>
        </div>
    </div>
</div> <!-- final do container -->


<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<script>
    Vue.component('agente-form',{

        template:  `
        <form id="formulario">
        <h4>Novo Cadastro</h4>
        <fieldset>
            <legend>DADOS PRINCIPAIS</legend>

            <div class="row">
                <label>
                    <input class="with-gap" type="radio" id="cpf" value="1" v-model="TipoPessoa"/>
                    <label for="cpf">CPF</label>
                    <input class="with-gap" type="radio" id="cnpj"  value="2" v-model="TipoPessoa">
                    <label for="cnpj">CNPJ</label>
                </label>
            </div>

            <div class="row">
                <div class="input-field col s3">
                    <input id="first_name" type="text" v-model="CPFCNPJ">
                    <label for="first_name">CPF/CNPJ</label>
                </div>

                <div class="input-field col s6">
                    <input id="last_name" type="text" class="validate" v-model="Nome">
                    <label for="last_name">Nome *</label>
                </div>

                <div class="col s3">
                    <label>Visão do Agente</label>
                    <select class="browser-default"  v-model="Fornecedor">
                        <option v-for="forne in Fornecedores" :value="forne.id" v-if="forne.descricao === 'Fornecedor'">{{forne.descricao}}</option>
                    </select>
                </div>
            </div>

        </fieldset>

        <fieldset>
            <legend>NOVO ENDEREÇO</legend>

            <div class="row">
                <div class="input-field col s3">
                    <input type="text"
                           name="cep"
                           id="cep"
                           class="validate"
                           :value="CEPmask"
                           maxlength="8"
                           v-on:keyup="cepMask(CEP)"
                           v-on:blur="buscarcep(CEPmask)"
                           v-on:input="inputCEP($event.target.value)">
                        <span id="erroCep" class="spanError"></span>

                    <label for="first_name">CEP *</label>
                </div>
                <div class="col s3">
                    <label>Tipo *</label>
                    <select class="browser-default" v-model="Tipo">
                        <option v-for="logradouro in TiposLogradouros" :value="logradouro.descricao" >{{logradouro.descricao}}</option>
                    </select>
                </div>

            </div>

            <div class="row">
                <div class="input-field col s12">
                    <input type="text" id="logradouro" name="logradouro" class="validate" v-model.lazy="Logradouro">
                    <label for="last_name">Logradouro *</label>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s6">
                    <input type="text" id="last_name" class="validate" v-model="Numero">
                    <label for="last_name">Número *</label>
                </div>
                <div class="input-field col s6">
                    <input type="text" id="last_name" class="validate" v-model="Complemento">
                    <label for="last_name">Complemento</label>
                </div>
            </div>

            <div class="row">
                <div class="col s3">
                    <label>UF *</label>
                    <select class="browser-default" v-on:change="combo()" v-model="uf">
                        <option v-for="uf in UFs" :value="uf.id">{{uf.descricao}}</option>
                    </select>
                </div>
                <div class="col s3">
                    <label>Cidade *</label>
                    <select class="browser-default" v-model="Cidade">
                        <option v-for="cidade in Cidades" :value="cidade.id">{{cidade.descricao}}</option>
                    </select>

                </div>
                <div class="input-field col s4">
                    <input type="text" id="last_name" class="validate" v-model="Bairro">
                    <label for="last_name">Bairro *</label>
                </div>
            </div>

            <div class="row">
                <div class="col s3">
                    <label>Tipo de Endereço *</label>
                    <select class="browser-default" v-model="TipoDeEndereço">
                        <option v-for="endereco in TiposEnderecos" :value="endereco.descricao" >{{endereco.descricao}}</option>
                    </select>
                </div>
                <div class="col s3">
                    <label>Autoriza Divulgar?</label>
                    <div class="align-bottom">
                        <input class="with-gap" type="radio" id="sim" value="1" v-model="Autorizar" />
                        <label for="sim">Sim</label>

                        <input class="with-gap" type="radio" id="nao" value="0" v-model="Autorizar"/>
                        <label for="nao">Não</label>
                    </div>
                </div>
            </div>

        </fieldset>
    </form>

        ` ,
        data: function () {

           return {
               TipoPessoa: "",
               CPFCNPJ: "",
               Nome: "",
               Fornecedor: "",
               CEP: "",
               CEPmask: "",
               Tipo: "",
               Logradouro: "",
               Numero: "",
               Complemento: "",
               UFs: "",
               Cidade: "",
               Bairro: "",
               TipoDeEndereço: "",
               Autorizar: "",
               uf: "",
               Cidades: "",
               Fornecedores: "",
               TiposEnderecos: "",
               TiposLogradouros: "",
           }

        },
        mounted: function () {
           var vue = this;

           let url = ['/prestacao-contas/fornecedor/uf',
                      '/prestacao-contas/fornecedor/fornecedores-tipo',
                      '/prestacao-contas/fornecedor/logradouro-tipo',
                      '/prestacao-contas/fornecedor/endereco-tipo'];

            $3.ajax({
                type: "GET",
                url: url[0],
            })
            .done((data) => vue.UFs = data)
            .fail((jqXHR) => alert('error'));

            $3.ajax({
                type: "GET",
                url: url[1],
            })
            .done((fornecedor) => vue.Fornecedores = fornecedor)
            .fail((jqXHR) => alert('error'));

            $3.ajax({
                type: "GET" ,
                url: url[2]
            })
            .done((logradouro) => vue.TiposLogradouros = logradouro)
            .fail((jqXHR) => alert('error'));

            $3.ajax({
                type: "GET" ,
                url: url[3]
            })
            .done((endereco) => vue.TiposEnderecos = endereco)
            .fail((jqXHR) => alert('error'));
        },
        methods:
            {
               combo:function () {
                 var vue = this;
                 let url = '/prestacao-contas/fornecedor/cidade/id/'+this.uf;
                 $3.ajax({
                     type: "GET",
                     url: url,
                })
                 .done( (cidade) => vue.Cidades = cidade )
                },

                cepMask: function(){
                        return this.CEP.replace(/(\d{2})(\d{3})(\d{2})/,"$1.$2-$3")
                },

                inputCEP: function(e) {
                        if (e.length == 8) {
                            this.CEP = e;
                            this.CEPmask = this.cepMask();
                        } else {
                            this.CEP = '';
                        }
                },

                buscarcep(cep) {

                   let vue = this;

                    var elmLogradouro = $3("#logradouro");
                    var elmTipoLogradouro = $3("#tipoLogradouro");
                    var elmBairro = $3("#bairro");
                    var elmCidade = $3("#cidade");
                    var elmUF = $3("#uf");

                    if (cep.length != 10) {
                        $3('#erroCep').html("CEP inv&aacute;lido");
                        limparEndereco();
                        return false;
                    }

                    $3.ajax({
                        url: "<?= $this->url(array('module' => 'default', 'controller' => 'cep', 'action' => 'cep-ajax')); ?>",
                        data: {
                            cep: cep
                        }
                    }).done(function (result) {
                        
                        if (result.status === true) {
                            console.info(result);

                            vue.Logradouro = result.logradouro;
                            vue.uf = result.idcidadeuf;
                                // this.Tipo= "";
                                // this.UFs= "";
                                // this.Cidade= "";
                                // this.Bairro= "";
                                // this.TiposLogradouros= "";
                                // this.uf="";
                                // this.Cidades= "";

                            console.info("Resultado: "+ this.Logradouro)


                        } else {

                            $3('#erroCep').html("CEP inv&aacute;lido ou n&atilde;o encontrado!");
                            limparEndereco();
                        }
                    });


                } // fecha funcao buscar_cep()

            },


    });


    var app = new Vue({
        el: '#app',

    })

</script>


</body>
</html>