<?php echo $this->partial('manual/inc/menu.inc.phtml', $this) ?>

<div class="container-fluid">
	<div class="page-title">
		<div class="row">
			<div class="col s12 m9 l10">
				<h1>Mensagens</h1>

				<ul id="migalhas">
					<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a> /</li>
					<li><a href="<?php echo $this->url(array('controller' => 'manual-legado', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a> /</li>
					<li class="last">Mensagens</li>
				</ul>
			</div>
			<div class="col s12 m3 l2 right-align">
				<a href="#!" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">comments</i></a>
			</div>
		</div>
	</div>

	<div class="content">

		<div id="miolo">
			<h4 class="centro">Mensagens em PHP (dentro das controllers)</h4>

			<p class="bold">parent::message("Mensagem de advertência!", "controller/action", "ALERT");</p>
			<div class="msgALERT">
				<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgALERT" onclick="$('.msgALERT').hide();" onkeypress="$('.msgALERT').hide();"/></div>
				<div>Mensagem de advertência!</div>
			</div>

			<br />

			<p class="bold">parent::message("Mensagem de sucesso!", "controller/action", "CONFIRM");</p>
			<div class="msgCONFIRM">
				<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgCONFIRM" onclick="$('.msgCONFIRM').hide();" onkeypress="$('.msgCONFIRM').hide();"/></div>
				<div>Mensagem de sucesso!</div>
			</div>

			<br />

			<p class="bold">parent::message("Mensagem de erro!", "controller/action", "ERROR");</p>
			<div class="msgERROR">
				<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgERROR" onclick="$('.msgERROR').hide();" onkeypress="$('.msgERROR').hide();"/></div>
				<div>Mensagem de erro!</div>
			</div>


			<br />
			<br />


			<h4 class="centro">Mensagens em JS (dentro das views)</h4>

			<strong>&lt;p class="msg"&gt;Mensagem de erro, validação de formulários, etc.&lt;/p&gt;</strong>
			<br />
			<p class="msg">Mensagem de erro, validação de formulários, etc.</p>

			<br />
			<br />

			<strong>&lt;label class="error"&gt;Mensagem de erro, validação de formulários, etc.&lt;/label&gt;</strong>
			<br />
			<label class="error">Mensagem de erro, validação de formulários, etc.</label>
		</div>

	</div>
</div>