<?php echo $this->partial('manual/inc/menu.inc.phtml', $this) ?>

<div class="container-fluid">
	<div class="page-title">
		<div class="row">
			<div class="col s12 m9 l10">
				<h1>Menu de abas</h1>

				<ul id="migalhas">
					<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial"><i class="material-icons">home</i>In&iacute;cio</a> /</li>
					<li><a href="<?php echo $this->url(array('controller' => 'manual-legado', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a> /</li>
					<li class="last">Menu de abas</li>
				</ul>
			</div>
			<div class="col s12 m3 l2 right-align">
				<a href="#!" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">comments</i></a>
			</div>
		</div>
	</div>

	<div class="content">

		<?php require_once "inc/menu_abas1.inc.phtml"; // menu abas ?>
		<h4 class="centro">Modelo 1</h4>

		<br />
		<br />

		<?php require_once "inc/menu_abas2.inc.phtml"; // menu abas ?>
		<h4 class="centro">Modelo 2</h4>

		<br />
		<br />

		<?php require_once "inc/menu_abas3.inc.phtml"; // menu abas ?>
		<h4 class="centro">Modelo 3</h4>

	</div>
</div>