<?php echo $this->partial('manual/inc/menu.inc.phtml', $this); ?>

<div class="container-fluid">
	<div class="page-title">
		<div class="row">
			<div class="col s12 m9 l10">
				<h1>Modal</h1>

				<ul id="migalhas">
					<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a> /</li>
					<li><a href="<?php echo $this->url(array('controller' => 'manual-legado', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a> /</li>
					<li class="last">Modal</li>
				</ul>
			</div>
			<div class="col s12 m3 l2 right-align">
				<a href="javascript:voltar();" title="Página Anterior" title="Página Anterior"
				   class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">keyboard_return</i>
				</a>
			</div>
		</div>
	</div>

	<div class="content">

		<script type="text/javascript">
		<!--
		$(document).ready(function()
		{
			$('#ex-alert, #bt-alert').click(function() // modal alert
			{
				alertModal("ALERT!", "exemplo-alert", 360, 180);
				return false;
			});
			$('#ex-confirm, #bt-confirm').click(function() // modal confirm
			{
				confirmModal("CONFIRM!", "exemplo-confirm", 360, 180);
				return false;
			});
		});
		//-->
		</script>



		<!-- ========== INÍCIO MARGEM ========== -->
		<div id="miolo">
			<h4>alertModal()</h4>
			<table class="tabela">
				<thead>
					<tr>
						<th colspan="2">Função alertModal()</th>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>
					<tr>
						<th>Parâmetro</th>
						<th>Descrição</th>
					</tr>
				</thead>
				<tbody class="registros">
					<tr>
						<td class="bold">titulo</td>
						<td>Descrição do título da modal. O valor padrão é <em>ALERT</em>.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">mensagem</td>
						<td>Id da div que possui a mensagem de alerta. Parâmetro obrigatório.</td>
					</tr>
					<tr>
						<td class="bold">largura</td>
						<td>Largura da modal. Parâmetro opcional. O valor default é <em>400</em>.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">altura</td>
						<td>Altura da modal. Parâmetro opcional. O valor default é <em>220</em>.</td>
					</tr>
					<tr>
						<td class="bold">campo</td>
						<td>Id do campo que estará ativado após o fechamento da modal quando o usuário clicar em <em>Ok</em>. Parâmetro opcional.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">url</td>
						<td>Endereço que será carregado após o fechamento da modal quando o usuário clicar em <em>Ok</em>. Parâmetro opcional.</td>
					</tr>
					<tr>
						<td class="bold">id_formulario</td>
						<td>Id do formulário que será submetido após o fechamento da modal quando o usuário clicar em <em>Ok</em>. Parâmetro opcional.</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>
				</tfoot>
			</table>

			<div id="exemplo-alert" class="sumir">Teste alertModal();</div>
			<p>Exemplo utilizando link: <a href="#" title="Abrir Modal" id="ex-alert">Abrir</a></p>
			<p>Exemplo utilizando botão: <input type="button" value=" " title="Abrir Modal" id="bt-alert" class="btn_abrir" /></p>



			<br />
			<br />
			<br />



			<h4>confirmModal()</h4>
			<table class="tabela">
				<thead>
					<tr>
						<th colspan="2">Função confirmModal()</th>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>
					<tr>
						<th>Parâmetro</th>
						<th>Descrição</th>
					</tr>
				</thead>
				<tbody class="registros">
					<tr>
						<td class="bold">titulo</td>
						<td>Descrição do título da modal. O valor padrão é <em>CONFIRM</em>.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">mensagem</td>
						<td>Id da div que possui a mensagem de alerta. Parâmetro obrigatório.</td>
					</tr>
					<tr>
						<td class="bold">largura</td>
						<td>Largura da modal. Parâmetro opcional. O valor default é <em>400</em>.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">altura</td>
						<td>Altura da modal. Parâmetro opcional. O valor default é <em>220</em>.</td>
					</tr>
					<tr>
						<td class="bold">campo_01</td>
						<td>Id do campo que estará ativado após o fechamento da modal quando o usuário clicar em <em>Sim</em>. Parâmetro opcional.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">url_01</td>
						<td>Endereço que será carregado após o fechamento da modal quando o usuário clicar em <em>Sim</em>. Parâmetro opcional.</td>
					</tr>
					<tr>
						<td class="bold">id_formulario_01</td>
						<td>Id do formulário que será submetido após o fechamento da modal quando o usuário clicar em <em>Sim</em>. Parâmetro opcional.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">campo_02</td>
						<td>Id do campo que estará ativado após o fechamento da modal quando o usuário clicar em <em>Não</em>. Parâmetro opcional.</td>
					</tr>
					<tr>
						<td class="bold">url_02</td>
						<td>Endereço que será carregado após o fechamento da modal quando o usuário clicar em <em>Não</em>. Parâmetro opcional.</td>
					</tr>
					<tr class="fundo_linha2">
						<td class="bold">id_formulario_02</td>
						<td>Id do formulário que será submetido após o fechamento da modal quando o usuário clicar em <em>Não</em>. Parâmetro opcional.</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>
				</tfoot>
			</table>

			<div id="exemplo-confirm" class="sumir">Teste confirmModal();</div>
			<p>Exemplo utilizando link: <a href="#" title="Abrir Modal" id="ex-confirm">Exemplo</a></p>
			<p>Exemplo utilizando botão: <input type="button" value=" " title="Abrir Modal" id="bt-confirm" class="btn_abrir" /></p>

		</div>
	</div>
</div>
