apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/culturagovbr/salic-minc:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/culturagovbr/salic-minc:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
  deploy:
    helm:
      releases:
      - name: salic-minc
        chartPath: charts/salic-minc
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/culturagovbr/salic-minc"
          image.tag: "{{.DIGEST_HEX}}"
