<?php
/**
 * Histórico Custos Administrativos
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 24/04/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

$dados = $this->planSR;
?>



<table class="tabela" summary="Histórico">
	<tr>
		 <td><input type="button" name="grid-custo-administrativo" id="g1-custo-administrativo" class="btn_adicionar" title="Expandir" /> <strong>Hist&oacute;rico de Solicita&ccedil;&atilde;o de Readequa&ccedil;&atilde;o - Custo Administrativo</strong></td>
	</tr>
</table>

<div id="div_g1-custo-administrativo" class="miolo_grid_01 sumir">
<?php if (count($dados) > 0) : ?>

<table class="tabela">
	<tr class="destacar bold" align="center">
		<td width="10%">Solicita&ccedil;&atilde;o</td>
		<td width="10%">Data Solicita&ccedil;&atilde;o</td>
		<td>Custo Administrativo</td>
		<td width="10%">Justificativa Proponente</td>
		<td width="10%">Data Avalia&ccedil;&atilde;o</td>
		<td width="10%">Avalia&ccedil;&atilde;o MinC</td>
		<td width="10%">Justificativa MinC</td>
	</tr>

	<tr>
		<td align="center">1°</td>
		<td align="center">08/05/2012</td>
		<td>
			<a href="javascript:alertModal('Planilha Solicitada', 'hsPlan1', ($(window).width() - 50), ($(window).height() - 50));" title="Visualizar planilha">Custo Administrativo</a>
	<!-- ========== INÍCIO PLANILHA SOLICITADA ========== -->
	<div id="hsPlan1" class="sumir">
	<table class="tabela">
		<tr>
			<th>Planilha Solicitada</th>
		</tr>

		<?php if (count($this->planSR) <= 0) : ?>
		<tr>
			<td align="center">N&atilde;o existe(m) item(ns) solicitado(s) para esse produto.</td>
		</tr>
		<?php endif; ?>

		<?php
		$nrFonte = 0;
		$item    = 1;
		foreach ($this->planSR as $fonte => $planilha) : //ForeachFonteIncentivo
		?>
			<tr>
				<td>
					<div tipoHISTADM="fonteHISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM" abertoHISTADM="true" class="icn_menos icn_menos_HISTADM" style="width:90%"><span class="red" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
				</td>
			</tr>
			<?php
			$nrProduto    = 0;
			$totalProduto = 0;
			if (is_array($this->planSR[$fonte]))
				foreach ($this->planSR[$fonte] as $produto => $planilha) : //ForeachProduto
			?>
				<tr class="masterHISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM">
					<td class="masterHISTADM">
						<div tipoHISTADM="produtoHISTADM" abertoHISTADM="true" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" class="icn_menos icn_menos_HISTADM clickprodutoHISTADM" style="width:98%; margin-left:2%;"><span class="green" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
					</td>
				</tr>
				<?php
				$nrEtapa = 0;
				if (is_array($this->planSR[$fonte][$produto]))
					foreach ($this->planSR[$fonte][$produto] as $etapa => $planilha) : //ForeachEtapa
						$totalEtapa = 0;
				?>
					<tr class="masterHISTADM produtoHISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" fonteHISTADM="<?php echo $nrFonte;?>HISTADM">
						<td>
							<div>
								<div tipoHISTADM="etapaHISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" etapaHISTADM="<?php echo $nrEtapa; ?>HISTADM" abertoHISTADM="true" class="icn_menos icn_menos_HISTADM clicketapaHISTADM" style="width:80%; margin-left:4%; "><span class="orange" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div>
							</div>
						</td>
					</tr>
					<?php
					$nrCidade = 0;
						if (is_array($this->planSR[$fonte][$produto][$etapa]))
							foreach ($this->planSR[$fonte][$produto][$etapa] as $cidade => $planilha) : //ForeachCidade
					?>
						<tr class="masterHISTADM produtoHISTADM etapaHISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" etapaHISTADM="<?php echo $nrEtapa; ?>HISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM">
							<td>
								<div tipoHISTADM="cidadeHISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" etapaHISTADM="<?php echo $nrEtapa; ?>HISTADM" cidadeHISTADM="<?php echo $nrCidade; ?>HISTADM" abertoHISTADM="true" class="icn_menos icn_menos_HISTADM clickcidadeHISTADM" style="width:94%; margin-left:6%;"><span class="black" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
							</td>
						</tr>
						<tr class="masterHISTADM produtoHISTADM etapaHISTADM cidadeHISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" etapaHISTADM="<?php echo $nrEtapa; ?>HISTADM" cidadeHISTADM="<?php echo $nrCidade; ?>HISTADM" fonteHISTADM="<?php echo $nrFonte; ?>HISTADM">
							<td>
								<table class="tabela">
									<tr class="masterHISTADM produtoHISTADM etapaHISTADM cidadeHISTADM" produtoHISTADM="<?php echo $nrProduto; ?>HISTADM" etapaHISTADM="<?php echo $nrEtapa; ?>HISTADM" cidadeHISTADM="<?php echo $nrCidade; ?>HISTADM" fonteHISTADM="<?php echo $nrFonte;?>HISTADM">
										<th>Item</th>
										<th>Unidade</th>
										<th>Quant.</th>
										<th>Ocorr.</th>
										<th>Vl. Unit&aacute;rio</th>
										<th>Total</th>
										<th>Qtd. Dias</th>
										<th>Justificativa Propopente</th>
										<th width="10%">Avalia&ccedil;&atilde;o MinC</th>
										<th width="10%">Justificativa MinC</th>
										<th>A&ccedil;&atilde;o</th>
									</tr>
									<?php
									$totalUF = 0;
									if (is_array($this->planSR[$fonte][$produto][$etapa][$cidade]))
										foreach ($this->planSR[$fonte][$produto][$etapa][$cidade] as $planilha) : //ForeachItem
											$totalUF += $planilha['vlTotal'];
									?>
										<tr class="item">
											<td><a href="javascript:alterar_item('<?php echo $planilha['idPlanilhaAprovacao']; ?>');" title="Clique para solicitar altera&ccedil;&atilde;o do item" class="linksModReadequacao">Cursto Administrativo</a></td>
											<td><?php echo $planilha['Unidade']; ?></td>
											<td><?php echo $planilha['qtItem']; ?></td>
											<td><?php echo $planilha['nrOcorrencia']; ?></td>
											<td><?php echo $this->formatarReal($planilha['vlUnitario']); ?></td>
											<td><?php echo $this->formatarReal($planilha['vlTotal']); ?></td>
											<td><?php echo $planilha['qtDias']; ?></td>
											<td><?php echo $planilha['dsJustificativa']; ?></td>
											<td class="green"><?php echo ($planilha['stAvaliacaoItem'] == 'AP') ? 'Deferido' : 'Indeferido'; ?></td>
											<td><?php echo $planilha['dsAvaliacaoItem']; ?></td>
											<td>
												<?php
												if ($planilha['tpAcao'] == 'E') :
													echo 'Excluir';
												elseif ($planilha['tpAcao'] == 'I') :
													echo 'Incluir';
												elseif ($planilha['tpAcao'] == 'A') :
													echo 'Alterar';
												else :
													echo '&nbsp;';
												endif;
												?>
											</td>
										</tr>
									<?php
											$item++;
										endforeach; //fechaForeachplanilha
									$nrCidade++;
									$totalEtapa   += $totalUF;
									$totalProduto += $totalUF;
									?>
									<tr>
										<td colspan="5" class="black" style="font-size: 14pt;">Total de UF</td>
										<td class="black" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalUF); ?></td>
										<td colspan="5">&nbsp;</td>
									</tr>
									<tr>
										<td colspan="5" class="orange" style="font-size: 14pt;">Total da Etapa</td>
										<td class="orange" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalEtapa); ?></td>
										<td colspan="5">&nbsp;</td>
									</tr>
									<tr>
										<td colspan="5" class="green" style="font-size: 14pt;">Valor para <?php echo $produto; ?></td>
										<td class="green" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalProduto); ?></td>
										<td colspan="5">&nbsp;</td>
									</tr>
								</table>
							</td>
						</tr>
		<?php
					endforeach; //fechaForeachcidade
					$nrEtapa++;
				endforeach; //fechaForeachetapa
				$totalProduto = 0;
				$nrProduto++;
			endforeach; //fechaForeachproduto
			$nrFonte++;
		endforeach; //fechaForeachFonteIncentivo
		?>
    </table>
    </div>
	<!-- ========== FIM PLANILHA SOLICITADA ========== -->
	
	</td>
		<td align="center">
			<a href="javascript:alertModal('Justificativa Proponente', 'dsProponente101', 580, 360);" title="Visualizar justificativa"><img src="<?php echo $this->baseUrl(); ?>/public/img/edit_ico.gif" alt="Visualizar anexos" /></a>
			<div id="dsProponente101" class="sumir">
				<table class="tabela">
					<tr>
						<th>Justificativa Proponente</th>
					</tr>
					<tr>
						<td>Justificativa Custo Administrativo Proponente</td>
					</tr>
				</table>
			</div>
		</td>
		<td align="center">08/05/2012</td>
		<td align="center" class="green">Aprovado</td>
		<td align="center">
			<a href="javascript:alertModal('Justificativa MinC', 'dsMinc101', 580, 360);" title="Visualizar justificativa"><img src="<?php echo $this->baseUrl(); ?>/public/img/edit_ico.gif" alt="Visualizar anexos" /></a>
			<div id="dsMinc101" class="sumir">
				<table class="tabela">
					<tr>
						<th>Justificativa MinC</th>
					</tr>
					<tr>
						<td>Justificativa Técnico</td>
					</tr>
				</table>
			</div>
		</td>
</table>

<?php else : ?>
<table class="tabela">
	<tr>
		<td align="center">N&atilde;o existe hist&oacute;rico de solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o para esse item.</td>
	</tr>
</table>
<?php endif; ?>
</div>



<script type="text/javascript">
<!--
/**
 * Função para abrir e fechar a grid
 */
function grid_custo_administrativo(elemento)
{
	if ( $('#' + elemento).attr('class') == 'btn_adicionar' )
	{
		$('#' + elemento).removeClass('btn_adicionar');
		$('#' + elemento).addClass('btn_remover');
		$('#' + elemento).attr({title:'Recolher'});
	}
	else
	{
		$('#' + elemento).removeClass('btn_remover');
		$('#' + elemento).addClass('btn_adicionar');
		$('#' + elemento).attr({title:'Expandir'});
	}
	$('#div_' + elemento).toggle('slow');
} // fecha função grid_custo_administrativo()

/**
 * Ações que serão executadas após o carregamento da página
 */
$(document).ready(function()
{
	$('input[name=grid-custo-administrativo]').click(function()
	{
		grid_custo_administrativo(this.id);return false;
	});
});

/**
 * Ações que serão executadas após o carregamento da página
 */
$(document).ready(function()
{
	// controle de exibição da planilha solicitada
	$(".icn_menos_HISTADM").click(function()
	{
		abrir_planilha(this, 'HISTADM');
	});
	$(".icn_menos_HISTADM").click();

	// efeitos ao passar o mouse sobre o item
	$(".item").mouseover(function()
	{
		$(this).addClass('fundo_linha3');
	});
	$(".item").mouseout(function()
	{
		$(this).removeClass('fundo_linha3');
	});

	$(".item").click(function()
	{
		if ($(this).hasClass('fundo_linha4'))
		{
			$(this).removeClass('fundo_linha4');
		}
		else
		{
			$(this).addClass('fundo_linha4');
		}
	});
});



/**
 * Função para expandir/recolher a planilha
 */
function abrir_planilha(item, planilha)
{
	var tipo    = $(item).attr('tipo' + planilha);
	var aberto  = $(item).attr('aberto' + planilha);
	var fonte   = 'fonte' + planilha;
	var produto = 'produto' + planilha;
	var etapa   = 'etapa' + planilha;
	var cidade  = 'cidade' + planilha;

	if (aberto == 'true')
	{
		adisplay = 'none';
		$(item).attr('aberto' + planilha, 'false');
		$(item).removeClass('icn_menos').addClass('icn_mais');
	}
	else
	{
		adisplay = '';
		$(item).attr('aberto' + planilha, 'true');
		$(item).removeClass('icn_mais').addClass('icn_menos');
	}

	if (tipo == fonte)
	{
		fonte = $(item).attr('fonte' + planilha);
		$(".master" + planilha + "[fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
		$(".clickproduto" + planilha + ", .clicketapa" + planilha + ", .clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
	}
	if (tipo == produto)
	{
		fonte   = $(item).attr('fonte' + planilha);
		produto = $(item).attr('produto' + planilha);
		$(".produto" + planilha + "[produto" + planilha + "='" + produto + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
		$(".clicketapa" + planilha + ", .clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
	}
	if (tipo == etapa)
	{
		fonte   = $(item).attr('fonte' + planilha);
		produto = $(item).attr('produto' + planilha);
		etapa   = $(item).attr('etapa' + planilha);
		$(".etapa" + planilha + "[produto" + planilha + "='" + produto + "'][etapa" + planilha + "='" + etapa + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
		$(".clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
	}
	if (tipo == cidade)
	{
		fonte   = $(item).attr('fonte' + planilha);
		produto = $(item).attr('produto' + planilha);
		etapa   = $(item).attr('etapa' + planilha);
		cidade  = $(item).attr('cidade' + planilha);
		$(".cidade" + planilha + "[produto" + planilha + "='" + produto + "'][etapa" + planilha + "='" + etapa + "'][cidade" + planilha + "='" + cidade + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
	}
} // fecha função abrir_planilha()
//-->
</script>