<?php 
/**
 * LOCAL DE REALIZAÇÃO: Solicitação de cadastros, alterações e inclusões de novos Locais de Realização
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 30/03/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

require_once "inc/menu.inc.php"; // menu
// define os valores dos campos do formulário, se será lido o dado original ou o dado readequado
$dadosAP       = $this->dadosAP;
$dadosSR       = $this->dadosSR;
$dados         = count($dadosSR) > 0 ? $dadosSR : $dadosAP;
$qtd           = count($dados);
$Justificativa = isset($this->pedido['dsJustificativa']) ? $this->pedido['dsJustificativa'] : '';

$urlPronac = null;
$urlPronac = (isset($this->idPronac)) ? "?idPronac=".Seguranca::encrypt($this->idPronac) : "";
?>


<script type="text/javascript">
/**
 * Ações que serão executadas após o carregamento da página
 */
    $(document).ready(function(){
        // desabilita a uf e a cidade caso o país não seja o brasil
        $('#pais').change(function()
        {
            if ($(this).val() == 31)
            {
                $('#cidade, #uf').attr('disabled', false);
            }
            else
            {
                // reseta a combo de uf
                document.getElementById('uf').options[0].selected = true;
                document.getElementById('uf').options[0].text     = ' - Selecione - ';
                document.getElementById('uf').options[0].value    = '';

                // reseta a combo de cidade
                document.getElementById('cidade').options[0].selected = true;
                document.getElementById('cidade').options[0].text     = ' - Selecione - ';
                document.getElementById('cidade').options[0].value    = '';
                document.getElementById('cidade').options.length      = 1;

                $('#cidade, #uf').attr('disabled', true);
            }
        });

        // carrega as cidades de acordo com a uf selecionada
        $('#uf').change(function(){
            carregar_combo(this.value, 'cidade', '<?php echo $this->url(array('controller' => 'municipios', 'action' => 'combo')); ?>', ' - Selecione uma UF - ');
        });

	// exclusão de local de realização
	$('.btn_excluir_local').click(function(){
            item = $(this).attr('id'); // pega o registro que está sendo excluído
            $('#dsExclusao').attr('value', ''); // limpa a justificativa

            $('#modal-exclusao-local').dialog('destroy');
            $('#modal-exclusao-local').dialog
            ({
                modal: true,
                resizable: false,
                width: 660,
                height: 300,
                title: 'Justificativa da Exclusão',
                autoOpen: true,
                buttons:
                    {
                    Não: function()
                    {
                        fecharModal('modal-exclusao-local');
                    },
                    'Sim': function()
                    {
                        if ($('#dsExclusao').val() == "")
                        {
                            alertModal('Alerta!', 'div-excluir-local', 320, 180, 'dsExclusao');
                            $('.ui-dialog-titlebar-close').remove();
                        }
                        else
                        {
                            $('#tpAcao').attr('value', 'E'); // atribui a acao
                            $('#justificativaExclusao').attr('value', $('#dsExclusao').val()); // atribui a justificativa

                            // atribui os valores dos campos para enviar através do formulário de inclusão (unificado)
                            $('#pais, #cidade, #uf').attr('disabled', false); // caso esteja desabilitado, habilita
                            $('#pais, #cidade, #uf').attr('readonly', true); // define para modo de leitura apenas
                            document.getElementById('pais').options.length        = 1; // deixa apenas uma opção no pais
                            document.getElementById('pais').options[0].selected   = true; // seleciona o campo
                            document.getElementById('pais').options[0].text       = ' - Selecione - '; // texto a ser exibido
                            document.getElementById('pais').options[0].value      = $('#tmpPais' + item).val(); // atribui o valor
                            document.getElementById('uf').options.length          = 1; // deixa apenas uma opção na uf
                            document.getElementById('uf').options[0].selected     = true; // seleciona o campo
                            document.getElementById('uf').options[0].text         = ' - Selecione - '; // texto a ser exibido
                            document.getElementById('uf').options[0].value        = $('#tmpUF' + item).val(); // atribui o valor
                            document.getElementById('cidade').options.length      = 1; // deixa apenas uma opção na cidade
                            document.getElementById('cidade').options[0].selected = true; // seleciona o primeiro campo
                            document.getElementById('cidade').options[0].text     = ' - Selecione - '; // texto a ser exibido
                            document.getElementById('cidade').options[0].value    = $('#tmpCidade' + item).val(); // atribui o valor

                            // envia o formulário
                            fecharModal('modal-exclusao-local');
                            carregandoModal();
                            $('#formReadequacao').submit();
                        } // fecha else
                    } // fecha button sim
                } // fecha button
            });
	});
    });
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => ''), null, true); ?><?php echo $urlPronac; ?>" title="Ir para In&iacute;cio" onclick="carregandoModal();">Consultar dados do Projeto</a></li>
        <li>Readequa&ccedil;&atilde;o de projeto</li>
        <li class="last">Local de realiza&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Readequa&ccedil;&atilde;o de projeto - Local de realiza&ccedil;&atilde;o <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

    <!-- ========== INÍCIO TOPO PROJETO ========== -->
    <?php require_once "inc/topo.inc.php"; ?>
    <!-- ========== FIM TOPO PROJETO ========== -->

    <!-- ========== INÍCIO FORMULÁRIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'local-realizacao')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="stPedidoAlteracao" id="stPedidoAlteracao" value="T" />
        <input type="hidden" name="siVerificacao" id="siVerificacao" value="0" />
        <input type="hidden" name="tpAlteracaoProjeto" id="tpAlteracaoProjeto" value="4" />
        <input type="hidden" name="tpAcao" id="tpAcao" value="I" />
        <input type="hidden" name="justificativaExclusao" id="justificativaExclusao" maxlength="255" />
        <!-- ========== INÍCIO MODAL EXCLUSÃO DE LOCAL ========== -->
        <div id="div-excluir-local" class="sumir">O preenchimento da justificativa &eacute; obrigat&oacute;rio para realiza&ccedil;&atilde;o da exclus&atilde;o!</div>
        <div class="sumir" id="modal-exclusao-local">
            Deseja realmente Excluir?
            <br /><br />
            <p><label for="dsExclusao">Justificativa:</label></p>
            <p><input type="text" name="dsExclusao" id="dsExclusao" maxlength="255" class="input_simples w600" /></p>
        </div>
        <!-- ========== FIM MODAL EXCLUSÃO DE LOCAL ========== -->
        <table class="tabela">
            <tr>
                <th colspan="4">Local de Realiza&ccedil;&atilde;o</th>
            </tr>
        </table>
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td>PA&Iacute;S</td>
                <td>UF</td>
                <td>CIDADE</td>
                <td>A&Ccedil;&Atilde;O</td>
            </tr>

            <?php $cont = 0; ?>
            <?php foreach ($dados as $d) : ?>
            <tr align="center" class="<?php echo (isset($d->tpAcao) && $d->tpAcao != 'N') ? 'red' : ''; ?>">
                <td><?php echo $d->dsPais; ?></td>
                <td><?php echo $d->dsUF; ?></td>
                <td><?php echo $d->dsMunicipioIBGE; ?></td>
                <td>
                    <input type="hidden" name="tmpPais[]"   id="tmpPais<?php echo $cont; ?>"   value="<?php echo $d->idPais; ?>" />
                    <input type="hidden" name="tmpUF[]"     id="tmpUF<?php echo $cont; ?>"     value="<?php echo $d->idUF; ?>" />
                    <input type="hidden" name="tmpCidade[]" id="tmpCidade<?php echo $cont; ?>" value="<?php echo $d->idMunicipioIBGE; ?>" />
                    <?php
                    if ($this->stPedidoAlteracao === 'A' && isset($d->tpAcao)) : // caso o formulário esteja desabilitado
                        if (trim($d->tpAcao)     == 'I') : echo 'Inclusão';
                        elseif (trim($d->tpAcao) == 'E') : echo 'Exclusão';
                        elseif (trim($d->tpAcao) == 'N') : echo 'Não alterado';
                        else                             : echo '-';
                        endif;
                    else :
                    ?>
                        <?php if ($qtd <= 1) : ?>
                        -
                        <?php else : ?>
                        <input type="button" name="btn_excluir[]" id="<?php echo $cont; ?>" class="btn_excluir btnsModReadequacao btn_excluir_local" value=" " title="Excluir" />
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php $cont++; ?>
            <?php endforeach; ?>

            <tr align="center">
                <td colspan="4">&nbsp;</td>
            </tr>
            <tr class="destacar bold">
                <th colspan="4">NOVO LOCAL DE REALIZA&Ccedil;&Atilde;O</th>
            </tr>
            <tr class="destacar bold" align="center">
                <td><label for="pais">PA&Iacute;S</label></td>
                <td><label for="uf">UF</label></td>
                <td colspan="2"><label for="cidade">CIDADE</label></td>
            </tr>
            <tr align="center">
                <td>
                    <select name="pais" id="pais" class="select_simples">
                        <?php foreach ($this->pais as $p) : ?>
                        <option value="<?php echo $p->idPais; ?>" <?php if ($p->idPais == '31') { echo 'selected="selected"'; } ?>><?php echo $p->Descricao; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    <select name="uf" id="uf" class="select_simples">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->uf as $u) : ?>
                        <option value="<?php echo $u->idUF; ?>"><?php echo $u->Sigla; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td colspan="2">
                    <select name="cidade" id="cidade" class="select_simples">
                        <option value=""> - Selecione - </option>
                    </select>
                </td>
            </tr>
            <tr class="destacar bold">
                <td colspan="4" align="center"><label for="justificativa">JUSTIFICATIVA</label></td>
            </tr>
            <tr>
                <td colspan="4">
                    <textarea name="justificativa" id="justificativa" cols="" rows="7" class="textarea_simples w99p"><?php echo $Justificativa; ?></textarea>
                    <span style="float: left; color: red;">Limite máximo de 600 caracteres</span>
                </td>
            </tr>
            <tr class="destacar bold">
                <td colspan="4" align="center"><label for="arquivo">ANEXOS</label></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div>
                        <span style="float: left; margin-right: 10px;"><input type="file" name="arquivo[]" id="arquivo" class="multi input_simples w99p" accept="pdf" /></span>
                        <span style="float: left; color: red;">Tamanho máximo de 5 MB</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                <?php if (count($this->arquivos) > 0) : ?>
                    <?php foreach ($this->arquivos as $a) : ?>
                    <div id="excluir_arq<?php echo $a->idPedidoAlteracao . $a->idArquivo; ?>">
                        <input type="button" class="btn_exclusao btnsModReadequacao" title="Excluir Arquivo" onclick="excluir_arq_readeq('<?php echo $a->idPedidoAlteracao; ?>', '<?php echo $a->idArquivo; ?>', '<?php echo $a->nmArquivo; ?>');" />
                        <a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')) . '?id=' . $a->idArquivo; ?>" title="Abrir Arquivo"><?php echo $a->nmArquivo; ?></a>
                    </div>
                    <?php endforeach; ?>
                <?php else : ?>
                    Nenhum arquivo encontrado!
                <?php endif; ?>
                </td>
            </tr>
        </table>

        <table class="tabela btnsModReadequacao">
            <tr>
                <td align="center">
                    <input type="submit" name="btn_salvar" id="btn_salvar" class="btn_salvar" value=" " title="Salvar" />
                    <input type="reset" name="btn_cancelar" id="btn_cancelar" class="btn_cancelar" value=" " title="Cancelar" />
                </td>
            </tr>
        </table>
    </form>
    <!-- ========== FIM FORMULÁRIO ========== -->

    <!-- ========== INÍCIO HISTÓRICO ========== -->
    <div id="historico"></div>
    <script type="text/javascript">
        carregaDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-local-realizacao')); ?>', 'historico');
    </script>
    <!-- ========== FIM HISTÓRICO ========== -->
</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />