<?php 
/**
 * PRAZO DE CAPTAÇÃO: Solicitação de prorrogação de Prazo de Captação do Projeto
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 30/03/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

require_once "inc/menu.inc.php"; // menu
// define os valores dos campos do formulário, se será lido o dado original ou o dado readequado
$DtInicioExecucaoAP = isset($this->dadosExecAP->DtInicioExecucao)    ? $this->dadosExecAP->DtInicioExecucao    : '';
$DtFimExecucaoAP    = isset($this->dadosExecAP->DtFimExecucao)       ? $this->dadosExecAP->DtFimExecucao       : '';
$DtInicioExecucaoSR = isset($this->dadosExecSR['dtInicioNovoPrazo']) ? $this->dadosExecSR['dtInicioNovoPrazo'] : '';
$DtFimExecucaoSR    = isset($this->dadosExecSR['dtFimNovoPrazo'])    ? $this->dadosExecSR['dtFimNovoPrazo']    : '';
$DtInicioCaptacaoAP = isset($this->dadosAP->DtInicioCaptacao)        ? $this->dadosAP->DtInicioCaptacao    : '';
$DtFimCaptacaoAP    = isset($this->dadosAP->DtFimCaptacao)           ? $this->dadosAP->DtFimCaptacao       : '';
$DtInicioCaptacaoSR = isset($this->dadosSR['dtInicioNovoPrazo'])     ? $this->dadosSR['dtInicioNovoPrazo'] : '';
$DtFimCaptacaoSR    = isset($this->dadosSR['dtFimNovoPrazo'])        ? $this->dadosSR['dtFimNovoPrazo']    : '';
$Justificativa      = isset($this->pedido['dsJustificativa'])        ? $this->pedido['dsJustificativa']    : '';

$urlPronac = null;
$urlPronac = (isset($this->idPronac)) ? "?idPronac=".Seguranca::encrypt($this->idPronac) : "";
?>

<script type="text/javascript">
    /**
     * Funções que são chamadas após a página ser carregada
     */
    $(document).ready(function()
        {
            // máscaras dos campos
            $("#dtInicioCaptacaoSR, #dtFimCaptacaoSR").keyup(function()
            {
		mascara(this, format_data); // data
            });

            // calendário
            $.datepicker.regional['pt-BR'] =
                {
		closeText: 'Fechar',
		prevText: '&#x3c;Anterior',
		nextText: 'Pr&oacute;ximo&#x3e;',
		currentText: 'Hoje',
		monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
		monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
		dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','S&aacute;bado'],
		dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
		dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
		weekHeader: 'Sm',
		dateFormat: 'dd/mm/yy',
		firstDay: 0,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['pt-BR']);

            // id dos campos que utilizarão o calendário
            $("#dtInicioCaptacaoSR, #dtFimCaptacaoSR").datepicker($.datepicker.regional['pt-BR']);
        }); // fim $(document).ready()
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => ''), null, true); ?><?php echo $urlPronac; ?>" title="Ir para In&iacute;cio" onclick="carregandoModal();">Consultar dados do Projeto</a></li>
        <li>Readequa&ccedil;&atilde;o de projeto</li>
        <li class="last">Prorrogar prazos de capta&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Readequa&ccedil;&atilde;o de projeto - Prorrogar prazos de capta&ccedil;&atilde;o <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <!-- ========== INÍCIO TOPO PROJETO ========== -->
    <?php require_once "inc/topo.inc.php"; ?>
    <!-- ========== FIM TOPO PROJETO ========== -->

    <!-- ========== INÍCIO FORMULÁRIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'prazo-captacao')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="stPedidoAlteracao" id="stPedidoAlteracao" value="T" />
        <input type="hidden" name="siVerificacao" id="siVerificacao" value="0" />
        <input type="hidden" name="tpAlteracaoProjeto" id="tpAlteracaoProjeto" value="8" />
        <table class="tabela">
            <tr>
                <th colspan="4">Prorrogar Prazo de Capta&ccedil;&atilde;o</th>
            </tr>
        </table>
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td colspan="4">PER&Iacute;ODO DE EXECU&Ccedil;&Atilde;O ATUAL</td>
            </tr>
            <tr align="center">
                <td colspan="2" class="w50p"><label for="dtInicioExecucao">Data de In&iacute;cio Atual</label> <input type="text" name="dtInicioExecucao" id="dtInicioExecucao" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtInicioExecucaoAP; ?>" /></td>
                <td colspan="2" class="w50p"><label for="dtFimExecucao">Data de Fim Atual </label> <input type="text" name="dtFimExecucao" id="dtFimExecucao" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtFimExecucaoAP; ?>" /></td>
            </tr>

            <?php if (!empty($DtInicioExecucaoSR) && !empty($DtFimExecucaoSR)) : ?>
            <tr class="destacar bold" align="center">
                <td colspan="4">PER&Iacute;ODO DE EXECU&Ccedil;&Atilde;O SOLICITADO</td>
            </tr>
            <tr align="center">
                <td colspan="2" class="w50p"><label for="dtInicioExecucaoSR">Data de In&iacute;cio Solicitado</label> <input type="text" name="dtInicioExecucaoSR" id="dtInicioExecucaoSR" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtInicioExecucaoSR; ?>" /></td>
                <td colspan="2" class="w50p"><label for="dtFimExecucaoSR">Data de Fim Solicitado</label> <input type="text" name="dtFimExecucaoSR" id="dtFimExecucaoSR" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtFimExecucaoSR; ?>" /></td>
            </tr>
            <?php endif; ?>

            <tr class="destacar bold" align="center">
                <td colspan="2" class="w50p">PER&Iacute;ODO DE CAPTA&Ccedil;&Atilde;O ATUAL</td>
                <td colspan="2" class="w50p">NOVO PER&Iacute;ODO DE CAPTA&Ccedil;&Atilde;O</td>
            </tr>
            <tr align="center">
                <td><label for="dtInicioCaptacao">Data de In&iacute;cio Atual</label> <input type="text" name="dtInicioCaptacao" id="dtInicioCaptacao" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtInicioCaptacaoAP; ?>" /></td>
                <td><label for="dtFimCaptacao">Data de Fim Atual </label> <input type="text" name="dtFimCaptacao" id="dtFimCaptacao" class="input_simples btn_calendario-off" maxlength="10" readonly="readonly" value="<?php echo $DtFimCaptacaoAP; ?>" /></td>
                <td><label for="dtInicioCaptacaoSR">Data de In&iacute;cio </label> <input type="text" name="dtInicioCaptacaoSR" id="dtInicioCaptacaoSR" class="input_simples btn_calendario" maxlength="10" value="<?php echo $DtInicioCaptacaoSR; ?>" /></td>
                <td><label for="dtFimCaptacaoSR">Data de Fim </label> <input type="text" name="dtFimCaptacaoSR" id="dtFimCaptacaoSR" class="input_simples btn_calendario" maxlength="10" value="<?php echo $DtFimCaptacaoSR; ?>" /></td>
            </tr>
            <tr class="destacar bold">
                <td colspan="4" align="center"><label for="justificativa">JUSTIFICATIVA</label></td>
            </tr>
            <tr>
                <td colspan="4">
                    <textarea name="justificativa" id="justificativa" cols="" rows="7" class="textarea_simples w99p"><?php echo $Justificativa; ?></textarea>
                    <span style="float: left; color: red;">Limite máximo de 600 caracteres</span>
                </td>
            </tr>
            <tr class="destacar bold">
                <td colspan="4" align="center"><label for="arquivo">ANEXOS</label></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div>
                        <span style="float: left; margin-right: 10px;"><input type="file" name="arquivo[]" id="arquivo" class="multi input_simples w99p" accept="pdf" /></span>
                        <span style="float: left; color: red;">Tamanho máximo de 5 MB</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <?php if (count($this->arquivos) > 0) : ?>
                        <?php foreach ($this->arquivos as $a) : ?>
                        <div id="excluir_arq<?php echo $a->idPedidoAlteracao . $a->idArquivo; ?>">
                            <input type="button" class="btn_exclusao btnsModReadequacao" title="Excluir Arquivo" onclick="excluir_arq_readeq('<?php echo $a->idPedidoAlteracao; ?>', '<?php echo $a->idArquivo; ?>', '<?php echo $a->nmArquivo; ?>');" />
                            <a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')) . '?id=' . $a->idArquivo; ?>" title="Abrir Arquivo"><?php echo $a->nmArquivo; ?></a>
                        </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        Nenhum arquivo encontrado!
                    <?php endif; ?>
                </td>
            </tr>
        </table>

        <table class="tabela btnsModReadequacao">
            <tr>
                <td align="center">
                    <input type="submit" name="btn_salvar" id="btn_salvar" class="btn_salvar" value=" " title="Salvar" />
                    <input type="reset" name="btn_cancelar" id="btn_cancelar" class="btn_cancelar" value=" " title="Cancelar" />
                </td>
            </tr>
        </table>
    </form>
    <!-- ========== FIM FORMULÁRIO ========== -->

    <!-- ========== INÍCIO HISTÓRICO ========== -->
    <div id="historico"></div>
    <script type="text/javascript">
        carregaDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-prazo-captacao')); ?>', 'historico');
        //-->
    </script>
    <!-- ========== FIM HISTÓRICO ========== -->
</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />