<thead>
    <tr class="titulo_tabela">
        <th>#</th>
        <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=3&ordem='.$this->paginacao['novaOrdem'];?>">PRONAC</a></th>
        <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=4&ordem='.$this->paginacao['novaOrdem'];?>">Nome do Projeto</a></th>
        <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">
            Dt. Envio Avaliador</a>
        </th>
        <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">
            Dt. Retorno Avaliador</a>
        </th>
        <th>Qt Dias Solicitação</th>
        <th>Qt Dias Avaliar</th>
        <th>Readequação</th>
        <th>Encaminhamento</th>
        <th>Receptor</th>
        <th>Unidade</th>
        <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=6&ordem='.$this->paginacao['novaOrdem'];?>">Tipo Readequa&ccedil;&atilde;o</a></th>
        <th>Ação</th>
        <th>Devolver</th>
        <th>Regularidade</th>
    </tr>
</thead>
<tbody>
<?php $count=1; foreach($this->dados as $d): ?>
        <tr>
            <td align="center" style="width: 1px;"><?php echo $count; ?></td>
            <td align="center">
                <a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->idPronac); ?>" target="_blank">
                    <?php echo $d->PRONAC; ?>
                </a>
            </td>
            <td><?php echo $d->NomeProjeto; ?></td>
            <td align="center"><?php echo Data::tratarDataZend($d->DtEnvioAvaliador, 'Brasileira'); ?></td>
            <td align="center"><?php echo Data::tratarDataZend($d->DtRetornoAvaliador, 'Brasileira'); ?></td>
            <td align="center"><?php echo $d->qtDiasSolicitacao?></td>
            <td align="center"><?php echo $d->qtDiasAvaliar?></td>
            <td align="center"><?php echo $d->dsReadequacao?></td>
            <td align="center"><?php echo $d->dsEncaminhamento?></td>
            <td align="center"><?php echo $d->Receptor?></td>
            <td align="center"><?php echo $d->Unidade?></td>
            <td align="center"><?php echo $d->dsReadequacao; ?></td>
            <?php if($this->filtro == 'analisados'): ?>
                <td align="center">
                    <input type="button" class="btn_ver" idReadequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>" />
                </td>
                <td align="left">
                    <?php if($this->filtro == 'analisados'): ?>
                        <select name="tecnico" class="select_simples comboComponente">
                            <option value=""> - Selecione - </option>
                            <?php foreach ($this->conselheiros as $conselheiro): ?>
                                <option value="<?php echo $conselheiro->id; ?>"><?php echo $conselheiro->nome; ?></option>
                            <?php endforeach; ?>
                            <input style="margin-left: 10px;" type="button" name="btn_enviar" class="btn_enviar finalizarReadequacao" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Enviar para Componente da Comissão">
                        </select>
                    <?php  else :?>
                        <?php echo '-';  ?>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
            <?php if($this->filtro != 'encaminhados'): ?>
                <td align="left" style="width: 1px;" nowrap>
                    <?php if($this->filtro == 'analisados'): ?>
                        <?php if($d->siEncaminhamento == 6 || $d->siEncaminhamento == 10): ?>
                        <input type="button" name="btn_encaminhar" class="btn_finalizar finalizarAnaliseReadequacao" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Finalizar a análise">
                        <?php endif; ?>
                    <?php else: ?>
                        <input type="button" name="btn_avaliar" id="btn_avaliar" class="btn_encaminhar" readequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>"
                                pronac="<?php echo $d->PRONAC; ?>"
                                nomeprojeto="<?php echo $d->NomeProjeto; ?>" title="Encaminhar">
                    <?php endif; ?>
                </td>
            <?php endif; ?>
            <?php if($this->filtro == 'analisados'): ?>
                <td align="center" style="width: 1px;">
                    <img src="<?php echo $this->baseUrl().'/public/img/desarquivar.gif'; ?>" style="cursor: pointer;" class="devolverReadequacao" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Devolver para nova análise">
                </td>
                <td align="center">
                    <img class="imgRegularidade" style="cursor: pointer" cgccpf="<?php echo $d->CgcCpf; ?>" pronac="<?php echo $this->pronac; ?>" src="<?php echo $this->baseUrl(); ?>/public/img/ico/archive.png" />
                </td>
            <?php endif; ?>
        </tr>
<?php $count++; endforeach; ?>
