    <table class="tabela tablesorter">
        <thead>
            <tr class="titulo_tabela">
                <th style="width: 80px;"><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=3&ordem='.$this->paginacao['novaOrdem'];?>">PRONAC</a></th>
                <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=4&ordem='.$this->paginacao['novaOrdem'];?>">Nome do Projeto</a></th>
		<th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=10&ordem='.$this->paginacao['novaOrdem'];?>">Tipo Readequa&ccedil;&atilde;o</a></th>
		
		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Envio</a></th>

		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Distribui&ccedil;&atilde;o</a></th>

		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Devolu&ccedil;&atilde;o</a></th>

		<th>Parecerista</th>
		<th>Qtd dias para distribuir</th>
		<th>Qtd dias para avaliar</th>
		<th>Total em dias para avaliar</th>

         <th style="width: 130px;">Encaminhar</th>

		<th>Finalizar</th>

         </tr>
        </thead>
        <tbody>
          <?php foreach($this->dados as $d): ?>
          <tr>
                <td align="center">
                    <a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->idPronac); ?>" target="_blank">
                        <?php echo $d->PRONAC; ?>
                    </a>
                </td>

		<td><?php echo $d->NomeProjeto; ?></td>
		
		<td><?php echo $d->tpReadequacao; ?></td>
		
        <td align="center"><?php if ($d->dtEnvio == '') { echo '---'; } else { echo Data::tratarDataZend($d->dtEnvio, 'Brasileira'); } ?></td>

        <td align="center"><?php if ($d->dtDistribuicao == '') { echo '---'; } else { echo Data::tratarDataZend($d->dtDistribuicao, 'Brasileira'); } ?></td>
		<td><?php echo $d->dtDevolucao; ?></td>
		<td><?php echo $d->nmParecerista; ?></td>
		<td><?php echo $d->qtDiasDistribuir; ?></td>
		<td><?php echo $d->qtDiasAvaliar; ?></td>
		<td><?php echo $d->qtTotalDiasAvaliar; ?></td>
		
        <td align="center">
          <?php 
             $p = new Projetos();
             $dadosProjetos = $p->buscar(array('IdPRONAC = ?'=>$d->idPronac))->current();

          $Pareceristas = array();
          if(count($dadosProjetos)>0){
          $a = new Agentes();
          $Pareceristas = $a->buscarPareceristas($this->idOrgao, $dadosProjetos->Area, $dadosProjetos->Segmento);
          }
          ?>
          <select name="tecnico" class="select_simples comboTecnico">
            <option value=""> - Selecione - </option>
            <?php foreach ($Pareceristas as $Parecerista) : ?>
              <option value='<?php echo $Parecerista->id; ?>' <?php echo ($d->nmParecerista == $Parecerista->nome) ? 'selected="selected"' : ''; ?> >
	    <?php echo $Parecerista->nome; ?></option>
<?php endforeach; ?>
</select>
<input type="button" name="btn_enviar" class="btn_enviar enviarReadequacao" idDistRead="<?php echo $d->idDistribuirReadequacao; ?>" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Enviar">
		</td>
		
		<td align="center">
                  <input type="button" name="btn_finalizar" class="btn_finalizar" idDistProj="<?php echo $d->idDistribuirReadequacao; ?>" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Finalizar">
		</td>
                		
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
