<?php require_once "scripts/analisarexecucaofisicatecnico/inc/menu.php"; ?>
<div id="camposObrigatorios" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/analisarexecucaofisicatecnico" title="CLista de Relatórios">Lista de Relatórios</a></li>
        <li class="last">Etapas de Trabalho</li>
    </ul>
</div>


<div id="titulo">
    <div>Etapas de Trabalho <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/analisarexecucaofisicatecnico" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <td class="destacar bold">ETAPAS DE TRABALHO EXECUTADAS</td>
        </tr>
        <tr>
            <td style="text-align: justify;"><?php echo $this->DadosRelatorio->dsEtapasExecutadas; ?><br /><br /></td>
        </tr>
        <tr align="center">
            <td class="destacar bold">MEDIDAS DE ACESSIBILIDADE FÍSICA</td>
        </tr>
        <tr>
            <td style="text-align: justify;"><?php echo $this->DadosRelatorio->dsAcessibilidade; ?><br /><br /></td>
        </tr>
        <tr align="center">
            <td class="destacar bold">MEDIDAS DE ESTÍMULO À FRUÍÇÃO DE DEMOCRATIZAÇÃO AO ACESSO PÚBLICO</td>
        </tr>
        <tr>
            <td style="text-align: justify;"><?php echo $this->DadosRelatorio->dsDemocratizacaoAcesso; ?><br /><br /></td>
        </tr>
        <tr align="center">
            <td class="destacar bold">MEDIDAS PREVENTIVAS QUANTO A IMPACTOS AMBIENTAIS</td>
        </tr>
        <tr>
            <td style="text-align: justify;"><?php echo $this->DadosRelatorio->dsImpactoAmbiental; ?><br /><br /></td>
        </tr>
    </table>

    <br clear="all" />
</div>


<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
