<div class="container-fluid">
    <div class="row">

        <?php $this->PageTitle('Projetos', array(
            array('Lista de projetos' => '')
        )); ?>

        <div class="content">
            <div class="row card-panel">
                <div class="col s12 m12 l3">
                    <label for="mecanismo"><b>Mecanismo</b></label></br>
                    <select name="mecanismo" id="mecanismo" class="browser-default">
                        <option value="1">Incentivo Fiscal Federal</option>
                    </select>
                </div>
                <div class="col s12 m12 l9">
                    <label><b>CPF/CNPJ Proponente:</b></label></br>
                    <select name="idProponente" id="idProponente" class="browser-default">
                        <option value="">Selecione</option>
                        <?php foreach ($this->proponentes as $proponente) : ?>
                            <option
                                class="proponente"
                                value="<?= $proponente['idAgenteProponente'] ?>"
                                <?= ($this->idAgente == $proponente['idAgenteProponente']) ? 'selected="selected"' : ''; ?>
                            ><?= "[" . Validacao::mascaraCPFCNPJ($proponente['CPF']) . "] - " . $proponente['Nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="row card-panel padding10">
                <div class="col s12 m12 l12">
                    <div id="listar-projetos-cadastrados">
                        <table
                            class="bordered striped conteudoImprimivel"
                            id="lista-de-projetos"
                            style="width: 100%"
                        >
                            <thead>
                            <tr>
                                <th>Pronac</th>
                                <th>Projeto</th>
                                <th>Situação</th>
                                <th>Período de Execução</th>
                                <th>Mecanismo</th>
                                <th class="right-align">A&ccedil;&otilde;es</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="conteudoRelatorio" class="sumir"></div>
<div id="mensagem-modal" class="sumir"></div>

<form name="frmGerarRelatorio" id="frmGerarRelatorio" class="sumir" method="post"
      action="<?php echo $this->url(array('module' => 'defauult','controller' => 'mantercalendariocnic', 'action' => 'gerarpdf')); ?>">
    <input type="hidden" id="html" name="html" value="">
    <input type="hidden" id="formato" name="formato" value="">
</form>

<div id="conteudo">

    <div id="corpo_impressao">
        <?php
        $i = 0;
        $z = 0;
        $idAgente = 0;
        if (!empty ($this->listarprojetos)) : ?>

            <!--            <fieldset>-->
            <!--                <legend>Registros</legend>-->

            <?php if (count($this->listarprojetos) > 0) :
                $ct = 0;
                foreach ($this->listarprojetos as $projeto): $ct++;

                    $cpfCnpj = $projeto["CgcCpf"];
                    if (strlen($cpfCnpj) == 11) {
                        $projeto["CgcCpf"] = aplicaMascara($projeto["CgcCpf"], "999.999.999 - 99");

                    } else {
                        $projeto["CgcCpf"] = aplicaMascara($projeto["CgcCpf"], "99.999.999 / 9999 - 99");
                    }
                    ?>

                    <?php if ($idAgente != $projeto["idAgente"] && $idAgente != 0): ?>
                        </table></td></tr>
                    <?php endif; ?>

                    <?php if ($idAgente != $projeto["idAgente"]): ?>
                        <table class="tabela">
                        <tr>
                            <td class="esquerda">
                                <input type="button" class="btn_remover expandir"
                                       idAgente=" <?php echo $projeto["idAgente"]; ?>"/>
                                <b><?php echo $projeto["CgcCpf"] . " - " . utf8_decode(htmlentities($projeto["NomeProponente"])); ?></b>
                                (<?php
                                if ($projeto["Ordem"] == 0) {
                                    echo 'Proponente';
                                } else if ($projeto["Ordem"] == 1) {
                                    if ($projeto["idSolicitante"] == 989898) { // Código cadastrado pelo Rômulo para identificar procuradores que foram migrados do sistema antigo para o novo com perfil de procurador, mas com função de Responsável.
                                        echo 'Responsável';
                                    } else {
                                        echo 'Procurador';
                                    }
                                } else if ($projeto["Ordem"] == 2) {
                                    echo 'Dirigente';
                                }
                                ?>)
                            </td>
                        </tr>

                        <tr class="mostraProposta_<?php echo $projeto["idAgente"]; ?>">
                        <td>
                        <table class="tabela">
                        <thead
                        <tr>
                            <th>Pronac</th>
                            <th>Nome do Projeto</th>
                            <th>Situa&ccedil;&atilde;o do Projeto</th>
                            <th>Per&iacute;odo de Execu&ccedil;&atilde;o</th>
                            <th>Mecanismo</th>
                            <th width="70px">A&ccedil;&otilde;es</th>
                        </tr>

                    <?php endif; ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index')); ?>?idPronac=<?php echo Seguranca::encrypt($this->escape($projeto["IdPRONAC"])); ?>"
                               target="_blanck" style="padding: 0 1rem">
                                <?php echo $this->escape($projeto["Pronac"]); ?>
                            </a>
                        <td><?php echo $projeto["NomeProjeto"]; ?></td>
                        <td><?php echo $projeto["Situacao"] . ' - ' . $projeto["Descricao"]; ?></td>
                        <td>
                            <?php
                            if (!empty($projeto["DtInicioDeExecucao"]) && !empty($projeto["DtFinalDeExecucao"])) {
                                echo Data::tratarDataZend($projeto["DtInicioDeExecucao"], 'brasileiro') . ' a ' . Data::tratarDataZend($projeto["DtFinalDeExecucao"], 'brasileiro');
                            }
                            ?>
                        <td>
                            <?php if ($projeto["Mecanismo"] == 1) {
                                echo 'Incentivo Fiscal Federal';
                            } else if ($projeto["Mecanismo"] == 2) {
                                echo 'FNC';
                            } else if ($projeto["Mecanismo"] == 6) {
                                echo 'Recurso do Tesouro';
                            }
                            ?></td>
                        <td>
                            <p>
                            <div style="position: relative; height: 50px;">
                                <div class="fixed-action-btn horizontal"
                                     style="position: absolute; top: -10px; right: 0; padding: 15px 0 15px 15px; z-index: 996;">
                                    <a class="btn btn-primary small" style="margin-left: 15px;">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul>
                                        <li>
                                            <a class="btn btn-floating red tooltipped"
                                               data-tooltip="Solicita&ccedil;&otilde;es"
                                               href="/solicitacao/mensagem/index/idPronac/<?= $this->escape($projeto["IdPRONAC"]); ?>">
                                                <i class="material-icons">message</i>
                                            </a>
                                        </li>
                                        <?php if ($projeto["podeClonarProjeto"]) : ?>
                                            <li>
                                                <a class="clonar-projeto btn btn-floating tooltipped btn-primary"
                                                   data-tooltip="Clonar Projeto" target="_blank"
                                                   href="javascript:void(0)"
                                                   id-pronac="<?= $this->escape($projeto["IdPRONAC"]); ?>"
                                                   pronac="<?= $this->escape($projeto["Pronac"]); ?>"
                                                   titulo="<?= $projeto["NomeProjeto"]; ?>">
                                                    <i class="material-icons">content_copy</i>
                                                </a>
                                            </li>
                                        <?php endif; ?>

                                        <?php if ($projeto["liberarEdicao"]) : ?>
                                            <li>
                                                <a class="btn btn-floating waves-effect waves-light tooltipped btn-default"
                                                   data-tooltip="Adequar à realidade ou Encaminhar para o MinC"
                                                   target="_blank"
                                                   href="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'identificacaodaproposta', 'idPreProjeto' => $projeto["idProjeto"])); ?>">
                                                    <i class="material-icons">edit</i>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                            </p>
                        </td>
                    </tr>

                    <?php $idAgente = $projeto["idAgente"]; ?>

                <?php endforeach; ?>
                </table>
                </td>
                </tr>
                </table>

            <?php else : ?>
                <table class="tabela">
                    <tr>
                        <td>
                            <div><font color='red'>Nenhum projeto encontrado.</font></div>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
            <!--            </fieldset>-->
        <?php else :
            if (isset($_POST) && !empty($_POST)) {
                echo '<fieldset style="text-align:center">N&atilde;o existem projetos cadastrados.</fieldset>';
            }
        endif; ?>

        <table class="tabela">
            <tr class="retirar">
                <td align="center">
                    <input type="button" class="btn_pdf" style="margin-right:20px" onclick="gerar_pdf('pdf')">
                    <input type="button" class="btn_xls" onclick="gerar_pdf('excel')">
                </td>
            </tr>
        </table>

    </div> <!-- ========== DIV IMPRESSAO ========== -->
</div> <!-- ========== DIV CONTEUDO ========== -->

<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
<script type="text/javascript" src="/public/scripts/projeto/index/listar.datatable.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css"/>

<script type="text/javascript">

    function gerar_pdf(formato) {
        $("#html").val("<html><style>table {width:798px;} table td { background-color:#EEE; padding:3px; text-align:center}table th { background-color:#CCC; padding:3px; text-align:center}</style><center><h2>Listar Projetos</h2></center>");
        $("#conteudoRelatorio").html($("#corpo_impressao").html());
        $('#conteudoRelatorio').find('.retirar').each(function () {
            $(this).remove();
        });
        $('a', $('#conteudoRelatorio')).attr('href', '#');
        //$('#conteudoRelatorio').find('retirar').each(function(){$(this).remove();});
        $('#html').val($("#html").val() + $("#conteudoRelatorio").html() + "</html>");
        $("#formato").val(formato);
        $("#frmGerarRelatorio").submit();
    }

    function clonar_projeto(idPronac) {

        if (!idPronac) {
            return false;
        }
        $3('#loading-message').html('Clonando projeto...');
        $3.ajax({
            type: 'POST',
            url: "<?php echo $this->url(array('controller' => 'listarprojetos', 'action' => 'clonar-projeto-ajax')); ?>",
            data: {
                idPronac: idPronac
            },
            success: function (data) {
                if (data.status == true) {
                    var url = "<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'identificacaodaproposta')); ?>" + '/idPreProjeto/' + data.idPreProjeto;

                    Materialize.toast(data.msg, 4000, 'green darken-1 white-text',
                        function () {
                            window.location = url
                        })
                    ;
                } else {
                    Materialize.toast(data.msg, 8000, 'red darken-1 white-text');
                }

            },
            dataType: 'json'
        });
    }

    //    $3(document).ready(function () {
    //        $3('.modal-pre-loader').modal();
    //    });



</script>
