<style>
    body {
        overflow-x: hidden;
        overflow-y: hidden;
    }
</style>
<?php
$auth = Zend_Auth::getInstance();
if (isset ($auth->getIdentity()->Cpf)) { ?>
    <div id="breadcrumb">
        <ul>
            <li class="first"><a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index')); ?>">In&iacute;cio</a>
            </li>
            <li class="last">Cadastrar Usuário</li>
        </ul>
    </div>
<?php } ?>
<div class="container">
    <div class="row">
        <div class="col s12 m3 l3"></div>
        <div class="col s12 m6 l6">
            <div class="card green-text text-darken-4 animated fadeInUp">
                <div class="card-content  white-text"
                     style="background: url(<?php echo $this->baseUrl(); ?>/public/img/bg-topo.png) no-repeat center 0 #acda5d ;">
                    <div class="row" style="margin: 0;">
                        <div class="col s12 center-align">
                            <img alt="Salic" src="<?php echo $this->baseUrl(); ?>/public/img/logo.png">
                        </div>
                        <div class="col s12">
                            <span class="card-title"><b>Cadastro</b></span>
                        </div>
                    </div>
                </div>
                <div class="card-content">
                    <form
                        class="materialize"
                        data-ajax-form="true"
                        onsubmit="return validaSenha();" method="POST"
                        action="<?php echo $this->url(array('module' => 'autenticacao', 'controller' => 'index', 'action' => 'cadastrarusuario')); ?>"
                        name="cadastraUsuario"
                        id="cadastraUsuario">
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">account_circle</i>
                                <input required="required" value="<?php echo $this->cpf ?>"
                                       onkeyup="mascara(this, format_cpf);" maxlength="14" type="text" name="cpf"
                                       id="cpf"
                                       minlength="14"
                                />
                                <label for="cpf">CPF</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">person</i>
                                <input required="required" value="<?php echo $this->nome ?>" maxlength="200" type="text"
                                       name="nome" id="nome" size="50"
                                       minlength="2"/>
                                <label for="nome">Nome Completo</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">date_range</i>
                                <label for="dataNasc">Data de Nascimento</label>
                                <input value="<?php echo $this->dtNascimento ?>" onblur="validaData(this)" onkeyup="mascara(this, format_data);"
                                       onkeydown="mascara(this, format_data);" onkeypress="mascara(this, format_data);"
                                       maxlength="10" type="date" class="datepicker" name="dataNasc" id="dataNasc"
                                       required="required"/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">mail_outline</i>
                                <input required="required" value="<?php echo $this->email ?>" maxlength="200"
                                       type="email" name="email" id="email" size="50"/>
                                <label for="email">E-mail</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">mail_outline</i>
                                <input required="required" value="<?php echo $this->email ?>" maxlength="200"
                                       type="email" name="emailConf" id="emailConf" size="50"/>
                                <label for="emailConf">Confirme o e-mail</label>
                            </div>
                        </div>
                        <button style="width: 100%;" id="btConfirmar"
                                class="btn waves-effect waves-light tooltipped" data-delay="50"
                                data-tooltip="Realizar o cadastro no sistema" type="submit" name="action">Cadastrar
                        </button>
                    </form>
                </div>
                <div class="card-action center-align">
                    <a href="javascript:redirect('<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'autenticacao')); ?>');"
                       class="tooltipped" data-delay="50" data-tooltip="Acessar o sistema">J&aacute; sou cadastrado</a>&nbsp;&nbsp;&nbsp;
                    <a href="javascript:redirect('<?php echo $this->url(array('controller' => 'index', 'action' => 'solicitarsenha', 'module' => 'autenticacao')); ?>');"
                       class="tooltipped" data-delay="50" data-tooltip="Resetar senha">Esqueci a senha</a>
                </div>
            </div>
        </div>
        <div class="col s12 m3 l3"></div>
    </div>
</div>
<script>
    function redirect(strUrl) {
        strAnimate = 'fadeOutDown';
        $('.card').removeClass('fadeInUp');
        $('.card').removeClass('animated');
        $('.card').addClass(strAnimate);
        $('.card').addClass('animated');
        $('.card').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
            window.location.href = strUrl;
        });
    }

    var dateNow = new Date();
    dateNow.setFullYear(dateNow.getUTCFullYear() - 16);
    $3(document).ready(function($){
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 100, // Creates a dropdown of 15 years to control year
            max: dateNow
        });
        $("form.materialize").validate({
            rules: {
                cpf: {
                    cpfBR: $('#cpf').val()
                },
                emailConf: {
                    equalTo: "#email"
                }
            },
            messages: {
                emailConf: {
                    equalTo: "Digite correto o seu e-mail."
                }
            }
        });
    });
</script>
