<!--<style>-->
<!--    body {overflow-x: hidden;overflow-y: hidden;}-->
<!--</style>-->
<?php if (!$this->habilitarServicoLoginCidadao): ?>
    <div class="container login">
        <div id="title" class="row animated fadeIn">
            <div class="col s12 l4"></div>
            <div class="col s12 l4 center-align">
                <h4 class="white-text">Bem-vindo(a)!</h4>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m3 l3"></div>
            <div class="col s12 m6 l6">
                <div class="card animated fadeInUp">
                    <div class="cabecalho-login">
                        <div class="row" style="margin-bottom: 2px">
                            <div class="col s12 center-align" style="padding-top: 10px;">
                                <div class="logo-salic"></div>
                            </div>
                            <div class="col s4 center-align">
                                <span class="card-title white-text"><b>Entrar</b></span>
                            </div>
                        </div>
                    </div>
                    <div class="card-content">
                        <form class="materialize" name="inicial" id="inicial"
                              onsubmit="return validaSenha();"
                              method="POST"
                              action="<?php echo $this->url(array('module' => 'autenticacao', 'controller' => 'index', 'action' => 'login'), null, true); ?>">
                            <div class="row">
                                <input type="hidden" name="from" value="<?php echo $this->from; ?>" />
                                <div class="input-field col s12">
                                    <i class="material-icons prefix green-text">account_circle</i>
                                    <input required="required" type="text" name="Login"
                                           id="Login"
                                           class="cpf"
                                           autocomplete="username"
                                    />
                                    <label for="Login">CPF</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12 container-senha">
                                    <i class="material-icons prefix green-text">lock</i>
                                    <input required="required" type="password" name="Senha" id="Senha" autocomplete="current-password"/>
                                    <label for="Senha">Senha</label>
                                    <a href="javascript:void(0)" class="material-icons prefix green-text mostrar-senha" onclick="mostrarSenha();">remove_red_eye</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <a href="javascript:redirect('<?php echo $this->url(array('controller' => 'index', 'action' => 'solicitarsenha', 'module' => 'autenticacao')); ?>');"
                                       class="tooltipped right" data-delay="50" data-tooltip="Recuperar senha">
                                        Recuperar senha
                                    </a>
                                </div>
                            </div>
                            <button style="width: 100%;" id="btConfirmar"
                                    class="btn waves-effect waves-light tooltipped" data-delay="50" data-tooltip="Acessar o sistema" type="submit" name="action">Entrar
                            </button>
                        </form>
                    </div>
                    <div class="card-action center-align">
                        <a href="javascript:redirect('<?php echo $this->url(array('controller' => 'index', 'action' => 'cadastrarusuario', 'module' => 'autenticacao')); ?>');" class="tooltipped" data-delay="50" data-tooltip="Ir para tela de cadastro">Cadastrar-se
                        </a>
                    </div>
                </div>
            </div>
            <div class="col s12 m3 l3"></div>
        </div>
    </div>
<?php else: ?>
    <p align="center" colspan="2">
        <a href="<?php echo $this->url(array('controller' => 'logincidadao', 'module' => 'autenticacao')) ?>">
            <img style="border: 0px"
                 src="<?php echo $this->baseUrl(); ?>/public/img/buttons/login_cidadao/BotaoParaLogin_escuro.png"
                 alt="Governo Federal - Brasil - Pa&iacute;s rico &eacute; pa&iacute;s sem pobreza"
                 title="Governo Federal - Brasil - Pa&iacute;s rico &eacute; pa&iacute;s sem pobreza"/>
        </a>
    </p>
<?php endif; ?>
<script type="text/javascript">

    function mostrarSenha() {
        var senha = document.getElementById('Senha');
        if (senha.type === 'password') {
            senha.type = 'text';
        } else {
            senha.type = 'password';
        }

        return false;
    }

    $3(document).ready(function ($) {
        $("#inicial").validate({
            // Define as regras
            rules: {
                Login: {
                    // campoNome sera obrigatorio (required) e tera tamanho manimo (minLength)
//                    required: true,
                    minlength: 14,
                    maxlength: 14
                },
                Senha: {
                    // campoSenha sera obrigatorio (required)
//                    required: true,
                    minlength: 2
                }
            },
            // Define as mensagens de erro para cada regra
            messages: {
                Login: {
                    required: " Digite o seu CPF!",
                    minlength: " O CPF deve conter exatamente 11 caracteres!"
                },
                Senha: {
                    required: " Digite a sua senha!",
                    minlength: " A senha deve conter, no m&iacute;nimo, 2 caracteres!"
                }
            }
        });
    });

    function validaSenha() {
        var data = document.getElementById("Senha").value;
        //var iChars = "<";
        data = data.replace("<", "##menor##");
        data = data.replace(">", "##maior##");
        data = data.replace("'", "##aspa##");

        document.getElementById("Senha").value = data;
        //document.inicial.submit();
        return true;
    }
</script>
