<script type="text/javascript">
    $(document).ready(function(){
//        $(function() {
//            // máscaras dos campos
//            $("#dataPortaria").keyup(function(){
//                mascara(this, format_data); // data
//            });
//    		
//            $.datepicker.regional['pt-BR'] = {
//                closeText: 'Fechar',
//                prevText: '&#x3c;Anterior',
//                nextText: 'Pr&oacute;ximo&#x3e;',
//                currentText: 'Hoje',
//                monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
//                monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
//                dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sabado'],
//                dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
//                dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
//                weekHeader: 'Sm',
//                dateFormat: 'dd/mm/yy',
//                firstDay: 0,
//                isRTL: false,
//                showMonthAfterYear: false,
//                yearSuffix: ''};
//            $.datepicker.setDefaults($.datepicker.regional['pt-BR']);
//            $(".cmpData").datepicker($.datepicker.regional['pt-BR']);
//        });
        
        $('#btn_incluir').click(function(){
            var erros = 0;
            $('.obrigatorio').each(function(){
                if($.trim($(this).val()) == ''){
                    erros++;
                }
            });
            
            var dsAvaliacao = CKEDITOR.instances['portaria'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,'');
            if (dsAvaliacao == ''){
                erros++;
            }

            if(erros > 0) {
                $("#alerta").dialog("destroy");
                $("#alerta").html("Favor preencher os dados obrig&aacute;torios!");
                $("#alerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            
            } else {
                $('#frmCadastro').submit();
            }
        });
        
        CKEDITOR.replace( 'portaria', { toolbar: [] } );
    });
</script>

<!-- ========== INICIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second">Configurar Secretário</li>
        <li class="last">Cadastrar Secretário</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<div id="alerta" class="sumir"></div>

<!-- ========== INICIO TITULO ========== -->
<div id="titulo">
    <div>Cadastrar Secretário <span class="voltar"><a href="<?php echo $this->url(array('controller' => 'configuracoes', 'action' => 'secretarios')); ?>">Voltar</a></span></div>
</div>
<!-- ========== FIM TITULO ========== -->


<!-- ========== INICIO CONTEUDO ========== -->
<div id="conteudo">
    
    <form action="<?php echo $this->url(array('controller' => 'configuracoes', 'action' => 'incluir-secretario')); ?>" method="post" name="frmCadastro" id="frmCadastro">
        <table class="tabela">
            <tr class="destacar">
                <th class="centro bold" colspan="2">Cadastrar Secretário</th>
            </tr>
            <tr>
                <td class="destacar bold w100">Nome <span class="red bold">*</span></td>
                <td>
                    <input type="text" class="input_simples obrigatorio w300" name="nome" />
                </td>
            </tr>
            <tr>
                <td class="destacar bold w100">Cargo <span class="red bold">*</span></td>
                <td>
                    <input type="text" class="input_simples obrigatorio w300" name="cargo" />
                </td>
            </tr>
            <tr>
                <td class="destacar bold">Portaria <span class="red bold">*</span></td>
                <td>
                    <textarea class="textarea_simples" style="width: 99%" name="portaria" id="portaria"></textarea>
                </td>
            </tr>
<!--            <tr>
                <td class="destacar bold w100">Data da Portaria de Publicação <span class="red bold">*</span></td>
                <td>
                    <input type="text" class="input_simples obrigatorio btn_calendario cmpData" value="" maxlength="10" name="dataPortaria" id="dataPortaria" />
                </td>
            </tr>-->
        </table>
        <p align="center"><input type="button" class="btn_incluir" id="btn_incluir" /></p>
    </form>

</div>
<!-- ========== FIM CONTEUDO ========== -->

<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->

<br clear="all" />