<script type="text/javascript">
    $(document).ready(function(){

        $("#listaMarcas").tablesorter({
            headers: {3:{sorter: false}, 4:{sorter: false}, 5:{sorter: false}}
        });

        $('.btn_aprovar, .btn_rejeitar').click(function(){
            var btn = $(this),
                titulo = 'Justificativa de Aprova&ccedil;&atilde;o!';
            if(btn.attr('st') == 'I'){
                titulo = 'Justificativa de Rejei&ccedil;&atilde;o!';
            }
            $('#justificativaCampo').val('');
            $("#justificativaModal").dialog("destroy");
            $("#justificativaModal").dialog({
                resizable: false,
                title: titulo,
                width:550,
//                height:300,
                modal: true,
                buttons : {
                    'Cancelar' : function(){
                        $(this).dialog('close');
                        $('#justificativaCampo').css('border-color','#CCCCCC');
                    },
                    'Confirmar' : function(){
                        $(this).dialog('close');
                        $("#msgAlerta").dialog('destroy');
                        $("#msgAlerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                        $("#msgAlerta").dialog({
                            resizable: false,
                            width:320,
                            modal: true,
                            title: 'Carregando..'
                        });
                        $('.ui-dialog-titlebar-close').remove();

                        $('#justificativaCampo').css('border-color','#CCCCCC');
                        if($('#justificativaCampo').val().length > 0){
                            $.ajax({
                                type: 'POST',
                                url: '<?php echo $this->url(array('controller' => 'marcas', 'action' => 'processar-marcas')); ?>',
                                data: {
                                    documento: btn.attr('documento'),
                                    pronacId: btn.attr('pronacId'),
                                    stAtivo: btn.attr('st'), //D=Deferido - I=Indeferido
                                    justificativa: $('#justificativaCampo').val()
                                },
                                success: function(data){
                                    if(data.resposta){
                                        $('.linha'+btn.attr('documento')).remove();
                                        $("#justificativaModal").dialog('close');

                                        $("#msgAlerta").dialog('destroy');
                                        $("#msgAlerta").html(data.mensagem);
                                        $("#msgAlerta").dialog({
                                            resizable: false,
                                            title: 'Alerta!',
                                            width:320,
                                            height:160,
                                            modal: true,
                                            buttons : {
                                                'Ok' : function(){
                                                    $(this).dialog('close');
                                                }
                                            }
                                        });
                                        $('.ui-dialog-titlebar-close').remove();
                                    }
                                },
                                dataType : 'json'
                            });
                        } else {
                            $('#justificativaCampo').css('border-color','red');
                            $('#justificativaCampo').focus();
                        }
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });

        $("#ListaMarcas").tablesorter();

    });
</script>

<div id="justificativaModal" class="sumir">
    <table class="tabela">
        <tr>
            <td class="destacar bold">Informe a Justificativa<span style="color: red;">*</span></td>
        </tr>
        <tr>
            <td><textarea name="justificativaCampo" style="width: 98%" id="justificativaCampo" class="textarea_simples" cols="70" rows="4"></textarea></td>
        </tr>
    </table>
</div>
<div id="msgAlerta" class="sumir"></div>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => '', 'action' => 'principal')); ?>" title="Ir para Inï¿½cio">Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'marcas', 'action' => 'index'), '', true); ?>" title="Processar Marcas">Processar Marcas</a></li>
        <li class="last">Lista</li>
    </ul>
</div>

<div id="titulo">
    <div>Lista<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>

<div id="conteudo">

    <table id="listaMarcas" class="tabela tablesorter">
        <?php //$arrayPronac = array(); $arrayNomeProjeto = array();
            if(count($this->lista) > 0) { ?>
        <thead>
            <tr>
                <th>Pronac</th>
                <th>Nome do Projeto</th>
                <th>Data de Envio</th>
                <th>Observa&ccedil;&atilde;o</th>
                <th>Arquivo</th>
                <th colspan="2">Avalia&ccedil;&atilde;o</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->lista as $lista) { ?>
            <tr class="linha<?php echo $lista->idDocumento; ?>">
                <td class="bold">
                    <a target="_blank" href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo $lista->idPronac; ?>"><?php echo $lista->Pronac; ?></a>
                </td>
                <td class="bold">
                    <?php //Verifica se o NomeProjeto já está no array (lista). Se estiver, não mostra o NomeProjeto.
//                        if (!in_array($lista->NomeProjeto, $arrayNomeProjeto)) {
                            echo $lista->NomeProjeto;;
//                        }
                    ?>
                </td>
                <td nowrap><?php echo Data::tratarDataZend($lista->dtEnvio, 'brasileiro', true);?></td>
                <td><?php echo $lista->dsDocumento; ?></td>
                <td nowrap width="1px"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $lista->idArquivo; ?>"><?php echo $lista->nmArquivo; ?></a></td>
                <td align="center" width="1px">
                    <input class="btn_aprovar" type="button" value=" " documento="<?php echo $lista->idDocumento; ?>" st="D" pronacId="<?php echo $lista->idPronac; ?>" />
                </td>
                <td align="center" width="1px">
                    <input class="btn_rejeitar" type="button" value=" " documento="<?php echo $lista->idDocumento; ?>" st="I" pronacId="<?php echo $lista->idPronac; ?>" />
                </td>
            </tr>
            <?php
                //Acrescenta nos arrays os dados montrado acima.
//                $arrayPronac[] = $lista->Pronac;
//                $arrayNomeProjeto[] = $lista->NomeProjeto;
                } } else {
            ?>
            <tr>
                <td colspan="7" style="text-align: center; font-weight: 600; font-size: 14pt;">Nenhum registro encontrado.</td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    
    <br clear="all" />
</div>


<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />