<?php
if (isset($this->proposta['idpreprojeto'])) {
    echo $this->action('menu', 'menu', 'proposta', array('idPreProjeto' => $this->proposta['idpreprojeto']));  // menu
}
?>
<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Enquadramento da Proposta</h1>
                    <?php
                    $links = [
                        $this->layout['listagem'],
                        [
                            'An&aacute;lise de Proposta Cultural' => [
                                'module' => 'admissibilidade',
                                'controller' => 'admissibilidade',
                                'action' => 'exibirpropostacultural',

                            ]
                        ],
                    ];
                    gerarBreadCrumb($links, 'migalhas');
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <?php if (!$this->menu): ?>
                        <a href="javascript:voltar()"
                           title="P&aacute;gina Anterior"
                           class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle">
                            <i class="material-icons">keyboard_return</i>
                        </a>
                    <?php endif ?>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="card-panel">


                <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Hist&oacute;rico</div>
      <div class="collapsible-body">
        <table class="bordered">
            <thead>
                <tr>
                    <th></th>
                    <th>Data</th>
                    <th>Avalia&ccedil;&atilde;o</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->historicoRecursoProposta as $avaliacao) { ?>
                    <tr>
                        <td><?php echo $avaliacao['tpRecurso'] ?></td>
                        <td><?php echo $avaliacao['dtRecursoProponente'] ?></td>
                        <td><?php echo $avaliacao['dsAvaliacaoTecnica'] ?> <?php echo ($avaliacao['stRascunho'] == '1') ? "<hr /><b>[Rascunho]</>" : '' ?></td>
                    </tr>
                    
            <?php } ?>
            </tbody>
        </table>
      </div>
    </li>
  </ul>
                    <script>
                    $(document).ready(function(){
                        $('.collapsible').collapsible();
                    });
                    </script>

                <?php
                echo $this->partial("recurso-proposta/inc/bloco_identificacao-proposta-cultural.phtml", $this);
                ?>
                <br/>
                
                <?php
                echo $this->partial("recurso-proposta/inc/bloco_enquadramento-proposto-avaliador.phtml", $this);
                ?>
                <br/>
                <?php
                echo $this->partial("recurso-proposta/inc/bloco_formulario-recurso-visao-proponente.phtml", $this);
                ?>
            </div>
        </div>
    </div>
</div>
