export const SET_LOCAL_REALIZACAO_DESLOCAMENTO = 'SET_LOCAL_REALIZACAO_DESLOCAMENTO';
export const SET_FONTES_DE_RECURSOS = 'SET_FONTES_DE_RECURSOS';
export const SET_DOCUMENTOS = 'SET_DOCUMENTOS';
export const SET_DADOS_PROPOSTA = 'SET_DADOS_PROPOSTA';
