export const SET_MARCAS_ANEXADAS = 'SET_MARCAS_ANEXADAS';
export const SET_DADOS_READEQUACOES = 'SET_DADOS_READEQUACOES';
export const SET_PEDIDO_PRORROGACAO = 'SET_PEDIDO_PRORROGACAO';
export const SET_DADOS_FISCALIZACAO_LISTA = 'SET_DADOS_FISCALIZACAO_LISTA';
export const SET_DADOS_FISCALIZACAO_VISUALIZA = 'SET_DADOS_FISCALIZACAO_VISUALIZA';
