<script type="text/javascript">
    $(document).ready(function(){
        $('.comboReadequacoes').change(function(){
            var valor = $(this).val(),
                solicitacoesSimples = new Array(3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,20,21);
                                
            if(valor != 0){
                $('.btnIncluir').removeClass('sumir');
                $('.solicitacoesSimples').removeClass('sumir');
            } else {
                $('.btnIncluir').addClass('sumir');
                $('.localRealizacao').addClass('sumir');
                $('.planosDeDivulgacao').addClass('sumir');
                $('.planosDeDistribuicao').addClass('sumir');
                $('.solicitacoesSimples').addClass('sumir');
                $('#campoAdicionadoPorTipoReadequacao').addClass('sumir');
                $('#campoCriadoTipoReadequacao').html('');
            }
       
            if(valor == 9){
                $('.localRealizacao').removeClass('sumir');
                $('.planosDeDivulgacao').addClass('sumir');
                $('.planosDeDistribuicao').addClass('sumir');
                $('#campoAdicionadoPorTipoReadequacao').addClass('sumir');
                $('#campoCriadoTipoReadequacao').html('');
                atualizarDadosLocaisRealizacao();
            } else if(valor == 11){
                $('.planosDeDistribuicao').removeClass('sumir');
                $('.localRealizacao').addClass('sumir');
                $('.planosDeDivulgacao').addClass('sumir');
                $('#campoAdicionadoPorTipoReadequacao').addClass('sumir');
                $('#campoCriadoTipoReadequacao').html('');
                atualizarDadosPlanosDeDistribuicao();
            } else if(valor == 14){
                $('.planosDeDivulgacao').removeClass('sumir');
                $('.localRealizacao').addClass('sumir');
                $('.planosDeDistribuicao').addClass('sumir');
                $('#campoAdicionadoPorTipoReadequacao').addClass('sumir');
                $('#campoCriadoTipoReadequacao').html('');
                atualizarDadosPlanosDeDivulgacao();
            } else if(in_array(valor,solicitacoesSimples)){
                $('.localRealizacao').addClass('sumir');
                $('.planosDeDistribuicao').addClass('sumir');
                $('.planosDeDivulgacao').addClass('sumir');
                $('#campoAdicionadoPorTipoReadequacao').removeClass('sumir');
                
                if(valor == 3){
                    $('#txAuxilio').html('a alteração de razão social');
                } else if(valor == 4){
                    $('#txAuxilio').html('a agência bancária');
                } else if(valor == 5){
                    $('#txAuxilio').html('a sinopse da obra');
                } else if(valor == 6){
                    $('#txAuxilio').html('o impacto ambiental');
                } else if(valor == 7){
                    $('#txAuxilio').html('a especificação técnica');
                } else if(valor == 8){
                    $('#txAuxilio').html('a estratégia de execução');
                } else if(valor == 10){
                    $('#txAuxilio').html('a alteração de proponente');
                } else if(valor == 12){
                    $('#txAuxilio').html('o nome do projeto');
                } else if(valor == 13){
                    $('#txAuxilio').html('o período de execução');
                } else if(valor == 15){
                    $('#txAuxilio').html('a síntese do projeto');
                } else if(valor == 16){
                    $('#txAuxilio').html('os objetivos');
                } else if(valor == 17){
                    $('#txAuxilio').html('a justificativa');
                } else if(valor == 18){
                    $('#txAuxilio').html('a acessibilidade');
                } else if(valor == 19){
                    $('#txAuxilio').html('a democratização de acesso');
                } else if(valor == 20){
                    $('#txAuxilio').html('as etapas de trabalho');
                } else if(valor == 21){
                    $('#txAuxilio').html('a ficha técnica');
                }
                criarCampoTipoReadequacao(valor);
            }
        });
        
        $('.detalharTextos').click(function(){
            var texto = $(this).attr('texto');
            $("#msgAlerta").dialog("destroy");
            $("#msgAlerta").html(texto);
            $("#msgAlerta").dialog({
                resizable: false,
                title: 'Texto detalhado',
                width:800,
                height:500,
                modal: true,
                buttons : {
                    'OK' : function(){
                        $(this).dialog('close');
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('#btn_cancelar').click(function(){
            window.location = "<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'), null, true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>";
        });
        
        $('#IncluirReadequacao').click(function(){
            var descJustificativa = CKEDITOR.instances['descJustificativa'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,''),
                texto = CKEDITOR.instances['descJustificativa'].getData(),
                erro = 0,
                msg = 'Favor preencher os dados obrigatórios!',
                tipoRead = $('#tipoReadequacao').val(),
                solicitacoesSimples = new Array(3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,20,21),
                solicitacoesSimplesCKEditor = new Array(5,6,7,8,16,17,18,19,20,21),
		naoPedeConfirmacao = new Array(11);
                
            if (descJustificativa == ''){
                erro++;
            }
            
            if(texto.length > 6000){
                erro++;
                msg = 'O campo só permite 5.000 caracteres!';
            }
            
            if(in_array(tipoRead, solicitacoesSimples)){
                
                if(tipoRead == 3 || tipoRead == 13){
                    var campoRead = $('#descSolicitacao').val();
                    if(campoRead == ''){
                        erro++;
                    }
                }
                
                if(tipoRead == 4){
                    var campoRead = $('#descSolicitacao').val();
                    if(campoRead == ''){
                        erro++;
                    } else if(campoRead.length < 5){
                        erro++;
                        msg = 'Agência bancária incorreta.';
                    }
                }
                
                if(tipoRead == 10){
                    var campoRead = $('#descSolicitacao').val();
                    if(campoRead == ''){
                        erro++;
                    } else if(campoRead.length < 14){
                        erro++;
                        msg = 'CPF ou CNPJ inválido.';
                    } else if(campoRead.length == 15 || campoRead.length == 16 || campoRead.length == 17){
                        erro++;
                        msg = 'CPF ou CNPJ inválido.';
                    }
                }
                
                if(tipoRead == 12){
                    var campoRead = $('#descSolicitacao').val();
                    if(campoRead == ''){
                        erro++;
                    } else if(campoRead.length > 300){
                        erro++;
                        msg = 'O campo de alteração de nome do projeto só permite 300 caracteres.';
                    }
                }
                
                if(tipoRead == 15){
                    var campoRead = CKEDITOR.instances['descSolicitacao'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,''),
                        textoSolicitacao = CKEDITOR.instances['descSolicitacao'].getData();
                    if(campoRead == ''){
                        erro++;
                    } else if(textoSolicitacao.length > 1000){
                        erro++;
                        msg = 'O campo só permite 1.000 caracteres!';
                    }
                }
                
                if(in_array(tipoRead, solicitacoesSimplesCKEditor)){
                    var campoRead = CKEDITOR.instances['descSolicitacao'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,''),
                        textoSolicitacao = CKEDITOR.instances['descSolicitacao'].getData();
                    if(campoRead == ''){
                        erro++;
//                    } else if(textoSolicitacao.length > 8000){
//                        erro++;
//                        msg = 'O campo só permite 8.000 caracteres!';
                    }
                }
            }
            
            if (erro > 0) {
                $("#msgAlerta").dialog("destroy");
                $("#msgAlerta").html(msg);
                $("#msgAlerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:340,
                    height:170,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            } else {
		// tipos de readequacao que não pedem confirmação
		if ($.inArray(tipoRead, naoPedeConfirmacao)) {
		    enviarformulario();
		} else {		    
                    $("#msgAlerta").dialog("destroy");
                    $("#msgAlerta").html('Deseja incluir essa solicitação de readequação?');
                    $("#msgAlerta").dialog({
			resizable: false,
			title: 'Alerta!',
			width:360,
			height:170,
			modal: true,
			buttons : {
                            'Não' : function(){
				$(this).dialog('close');
                            },
                            'Sim' : function(){
				$(this).dialog('close');
				$("#msgAlerta").dialog("destroy");
				$("#msgAlerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
				$("#msgAlerta").dialog({
                                    resizable: false,
                                    width:320,
                                    modal: true,
                                    title: 'Carregando..'
				});
				$('.ui-dialog-titlebar-close').remove();
				window.setTimeout('enviarformulario()', 1000);
                            }
			}
                    });
                    $('.ui-dialog-titlebar-close').remove();
		}
	    }
        });
	
        $('.btn_exclusao').click(function(){
            var idReadequacao = $(this).attr('readequacao');
            $("#msgAlerta").dialog("destroy");
            $("#msgAlerta").html('Deseja excluir a solicitação de readequação?');
            $("#msgAlerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width:360,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $(this).dialog('close');
                        $("#msgAlerta").dialog("destroy");
                        $("#msgAlerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                        $("#msgAlerta").dialog({
                            resizable: false,
                            width:320,
                            modal: true,
                            title: 'Carregando..'
                        });
                        $('.ui-dialog-titlebar-close').remove();
                        window.setTimeout('excluirReadequacao('+idReadequacao+')', 1000);
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('#newUF').change(function(){
            $("#newMunicipio").html('<option value=""> - Carregando - </option>');
            if($(this).val() == 0){
                $("#newMunicipio").html('<option value=""> - Selecione - </option>');
            }
            else{
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'index'), null, true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                    type: "POST",
                    data :{
                        iduf : $(this).val()
                    },
                    success: function(valor){
                        $("#newMunicipio").html('<option value=""> - Selecione - </option>');

                        for(a in valor){
                            $("#newMunicipio").append('<option value="'+valor[a].idCidade+'">'+valor[a].nomeCidade+'</option>');
                        }
                    },
                    type : 'post'
                    , dataType : 'json'
                });
            }
        });
        
        $('#newEtapa').change(function(){
            $('#newProduto').change();
        });
        
        $('#newProduto').change(function(){
            $("#newItem").html('<option value=""> - Carregando - </option>');
            if($(this).val() == 0){
                $("#newItem").html('<option value=""> - Selecione - </option>');
            }
            else{
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'index'), null, true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                    type: "POST",
                    data :{
                        idEtapa : $('#newEtapa').val(),
                        idProduto : $(this).val()
                    },
                    success: function(valor){
                        $("#newItem").html('<option value=""> - Selecione - </option>');
                        for(a in valor){
                            $("#newItem").append('<option value="'+valor[a].idPlanilhaItens+'">'+valor[a].Item+'</option>');
                        }
                    },
                    type : 'post'
                    , dataType : 'json'
                });
            }
        });
        
        $('.btn_finalizar').click(function(){
            $("#msgAlerta").dialog("destroy");
            $("#msgAlerta").html('Deseja realmente finalizar as solicitações de readequação cadastradas?<br /><br />Ao finalizar, todas as solicitações serão encaminhadas ao MinC.');
            $("#msgAlerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width:360,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $(this).dialog('close');
                        $("#msgAlerta").dialog("destroy");
                        $("#msgAlerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                        $("#msgAlerta").dialog({
                            resizable: false,
                            width:320,
                            modal: true,
                            title: 'Carregando..'
                        });
                        $('.ui-dialog-titlebar-close').remove();
                        window.setTimeout('finalizarformulario()', 1000);
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $(".icn_menos").click(function(){
            var tipo = $(this).attr('tipo');
            var aberto = $(this).attr('aberto');
            if(aberto == 'true'){
                adisplay = 'none';
                $(this).attr('aberto','false')
                $(this).removeClass('icn_menos').addClass('icn_mais')
            }
            else{
                adisplay = '';
                $(this).attr('aberto','true')
                $(this).removeClass('icn_mais').addClass('icn_menos')
            }
            if(tipo == 'fonte'){
                fonte = $(this).attr('fonte');
                $(".master[fonte='"+fonte+"']").css('display', adisplay);
                $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
            }
            if(tipo == 'produto'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'etapa'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'cidade'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                cidade = $(this).attr('cidade');
                $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
        });
        $(".item").mouseover(function(){
            $(this).addClass('fundo_linha3');
        });
        $(".item").mouseout(function(){
            $(this).removeClass('fundo_linha3');
        });
        $(".item").click(function(){
            if($(this).hasClass('fundo_linha4')){
                $(this).removeClass('fundo_linha4');
            }
            else{
                $(this).addClass('fundo_linha4');
            }
        });
        
        $('.editarItem').live('click', function(){
            var idPlanilhaAprovacao = $(this).attr('idPlanilhaAprovacao'),
                itemClicado = $(this);
                
            //AO ABRIR A MODAL, LIMPA TODOS OS CAMPOS EDITÁVEIS
            $('.modalObrigatorios').each(function(){
                $(this).css('border-color', '#CCCCCC');
                $(this).val('');
            });
            $('#TotalCalculado').html('R$ 0,00');
            $('#campoTotal').css('color','#222222');
            $('#TotalCalculado').css('color','#222222');
            $('#textoErroValores').html('');

            //BUSCA OS DADOS DO ITEM PARA VISUALIZAÇÃO DOS NA MODAL
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'alterar-item-solicitacao'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                data: {
                    idPlanilha: idPlanilhaAprovacao
                },
                success: function(data){
                    
                    if(data.resposta){
                        $('#campoPronac').html(data.dadosProjeto.PRONAC);
                        $('#campoNomeProjeto').html(data.dadosProjeto.NomeProjeto);

                        $('#campoProduto').html(data.dadosPlanilhaAtiva.descProduto);
                        $('#campoEtapa').html(data.dadosPlanilhaAtiva.descEtapa);
                        $('#campoItem').html(data.dadosPlanilhaAtiva.descItem);

                        $('#campoUnidadeSolicitado').html(data.dadosPlanilhaAtiva.descUnidade);
                        $('#campoQtdSolicitado').html(data.dadosPlanilhaAtiva.Quantidade);
                        $('#campoOcorrenciaSolicitado').html(data.dadosPlanilhaAtiva.Ocorrencia);
                        $('#campoVlUnitarioSolicitado').html(data.dadosPlanilhaAtiva.ValorUnitario);
                        $('#campoDiasSolicitado').html(data.dadosPlanilhaAtiva.QtdeDias);
                        $('#campoTotalSolicitado').html(data.dadosPlanilhaAtiva.TotalSolicitado);
                        
                        $('#campoValorComprovado').html(data.valoresDoItem.vlComprovadoDoItem);

                        $('#modalUnidade').val(data.dadosPlanilhaEditavel.idUnidade);
                        $('#modalQuantidade').val(data.dadosPlanilhaEditavel.Quantidade);
                        $('#modalOcorrencia').val(data.dadosPlanilhaEditavel.Ocorrencia);
                        $('#modalValorUnitario').val(data.dadosPlanilhaEditavel.ValorUnitario.replace('R$ ',''));
                        $('#modalDias').val(data.dadosPlanilhaEditavel.QtdeDias);
                        $('#modalJustificativa').val(data.dadosPlanilhaEditavel.Justificativa);
                        $('#TotalCalculado').html(data.dadosPlanilhaEditavel.TotalSolicitado);
                        
                        $('#campoIdPlanilha').attr('idPlanilha', idPlanilhaAprovacao);

                        var vlComprovadoDoItemValidacao = data.valoresDoItem.vlComprovadoDoItemValidacao,
                            valorParaMsgErro = data.dadosPlanilhaAtiva.TotalSolicitado,
                            mensagem = '';
                    
                        //MOSTRA OS DADOS NA MODAL APÓS ABRI-LA
                        $("#modalItem").dialog("destroy");
                        $("#modalItem").dialog({
                            resizable: false,
                            title: 'Alterar Item!',
                            width: 800,
                            modal: true,
                            buttons : {
                                'Cancelar' : function(){
                                    $(this).dialog('close');
                                    itemClicado.parent().parent().removeClass('fundo_linha4');
                                },
                                'Salvar' : function(){
                                    var Unidade = $('#modalUnidade').val(),
                                        Quantidade = $('#modalQuantidade').val(),
                                        Ocorrencia = $('#modalOcorrencia').val(),
                                        ValorUnitario = $('#modalValorUnitario').val(),
                                        QtdeDias = $('#modalDias').val(),
                                        Justificativa = $('#modalJustificativa').val(),
                                        obrigatorios = 0,
                                        erros = 0;

                                    //VERIFICA SE OS CAMPOS FORAM PREENCHIDOS
                                    $('.modalObrigatorios').each(function(){
                                        if($.trim($(this).val()) == ''){
                                            obrigatorios++;
                                            erros++;
                                            $(this).css('border-color', 'red');
                                        } else {
                                            $(this).css('border-color', '#CCCCCC');
                                        }
                                    });
                                    
                                    if(obrigatorios > 0){
                                        mensagem += '- Favor preencher os dados obrigatórios.<br/>';
                                    }

                                    var TotalCalculadoComponente = $('#TotalCalculado').html().replace(/[^\d]/g, "");
                                    if(parseInt(TotalCalculadoComponente) < parseInt(vlComprovadoDoItemValidacao)){
                                        //$('#TotalCalculado').css('color','red');
                                        mensagem += '- O valor total do item não pode ser menor do que o valor comprovado de '+data.valoresDoItem.vlComprovadoDoItem+'.<br/>';
                                        erros++;
                                    }
                                    
                                    //SE HOUVER ALGO DE ERRADO, EXIBE MENSAGEM DE ALERTA.
                                    if(erros > 0){
                                        $('#TotalCalculado').css('color','red');
                                        $("#msgAlerta").html(mensagem);
                                        $("#msgAlerta").dialog({
                                            resizable: false,
                                            title: 'Alerta!',
                                            width:320,
                                            modal: true,
                                            buttons : {
                                                'OK' : function(){
                                                    $(this).dialog('close');
                                                }
                                            }
                                        });
                                        $('.ui-dialog-titlebar-close').remove();
                                        erros = 0;
                                        mensagem = '';
                                        return false;
                                        
                                    //SE NENHUM CAMPO ESTIVER EM BRANCO, SALVA OS DADOS
                                    } else {
                                        $.ajax({
                                            type: 'POST',
                                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'salvar-avaliacao-do-item'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                                            data: {
                                                idPlanilha: idPlanilhaAprovacao,
                                                Unidade: Unidade,
                                                Quantidade: Quantidade,
                                                Ocorrencia: Ocorrencia,
                                                ValorUnitario: ValorUnitario,
                                                QtdeDias: QtdeDias,
                                                Justificativa: Justificativa,
                                                valorSolicitado: valorParaMsgErro
                                            },
                                            success: function(data){
                                                $("#modalItem").dialog("destroy");
                                                atualizarDadosPlanilha();
                                            }
                                        });
                                    }
                                }
                            }
                        });
                        $('.ui-dialog-titlebar-close').remove();
                    }
                },
                dataType : 'json'
            });

            return false;
        });
        
        $('.excluirItemPlanilha').live('click', function(){
            var idPlanilhaAprovacao = $(this).attr('idPlanilhaAprovacao'),
                itemClicado = $(this);
                
            //ABRE O MODAL DE CONFIRMAÇÃO DA AÇÃO REALIZADA
            $("#msgAlerta").dialog("destroy");
            $("#msgAlerta").html('Tem certeza que deseja excluir o item da planilha?');
            $("#msgAlerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width:380,
                height:170,
                modal: true,
                buttons : {
                    'Não' : function(){
                        itemClicado.parent().parent().removeClass('fundo_linha4');
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        //BUSCA OS DADOS DO ITEM PARA VISUALIZAÇÃO DOS NA MODAL
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'excluir-item-solicitacao'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                            data: {
                                idPlanilha: idPlanilhaAprovacao
                            },
                            success: function(data){
                                $("#msgAlerta").dialog("destroy");
                                atualizarDadosPlanilha();
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('.multiplicarValores').keyup(function(){
            // recebe os valores do formulário
            var qtd = $('#modalQuantidade').val(),
                ocorrencia = $('#modalOcorrencia').val(),
                valor = $('#modalValorUnitario').val();

            // retira os pontos e as vírgulas, deixando somente números
            valor = valor.replace(/\D/g, "")
            .replace(/(\d{0})(\d)/, "$1$2")
            // adiciona o ponto na casa decimal
            .replace(/(\d)(\d{2})$/, "$1.$2");

            // converte para float e adiciona precisão decimal
            qtd        = parseFloat(qtd).toFixed(2);
            ocorrencia = parseFloat(ocorrencia).toFixed(2);
            valor      = parseFloat(valor).toFixed(2);

            // variável com o resultado
            resultado = parseFloat(qtd * ocorrencia * valor).toFixed(2); // armazena o resultado

            // se não for número
            if (isNaN(resultado))
            {
                resultado = '';
            }
            // caso seja número
            else
            {
                // formata para real
                resultado = resultado.replace(/\D/g, "");
                resultado = resultado.replace(/(\d)(\d{2})$/, "$1,$2");
                resultado = resultado.replace(/(\d+)(\d{3},\d{2})$/g, "$1.$2");

                var q = (resultado.length - 3) / 3; // quantidade caracteres
                var c = 0; // contador
                while (q > c)
                {
                    c++;
                    resultado = resultado.replace(/(\d+)(\d{3}.*)/, "$1.$2");
                }
                resultado = resultado.replace(/^(0+)(\d)/g, "$2");
                resultado = 'R$ ' + resultado;
            } // fecha else

            $('#TotalCalculado').html(resultado);
        });
        
        $('.newMultiplicarValores').keyup(function(){
            // recebe os valores do formulário
            var qtd = $('#newQuantidade').val(),
                ocorrencia = $('#newOcorrencia').val(),
                valor = $('#newValorUnitario').val();

            // retira os pontos e as vírgulas, deixando somente números
            valor = valor.replace(/\D/g, "")
            .replace(/(\d{0})(\d)/, "$1$2")
            // adiciona o ponto na casa decimal
            .replace(/(\d)(\d{2})$/, "$1.$2");

            // converte para float e adiciona precisão decimal
            qtd        = parseFloat(qtd).toFixed(2);
            ocorrencia = parseFloat(ocorrencia).toFixed(2);
            valor      = parseFloat(valor).toFixed(2);

            // variável com o resultado
            resultado = parseFloat(qtd * ocorrencia * valor).toFixed(2); // armazena o resultado

            // se não for número
            if (isNaN(resultado))
            {
                resultado = '';
            }
            // caso seja número
            else
            {
                // formata para real
                resultado = resultado.replace(/\D/g, "");
                resultado = resultado.replace(/(\d)(\d{2})$/, "$1,$2");
                resultado = resultado.replace(/(\d+)(\d{3},\d{2})$/g, "$1.$2");

                var q = (resultado.length - 3) / 3; // quantidade caracteres
                var c = 0; // contador
                while (q > c)
                {
                    c++;
                    resultado = resultado.replace(/(\d+)(\d{3}.*)/, "$1.$2");
                }
                resultado = resultado.replace(/^(0+)(\d)/g, "$2");
                resultado = 'R$ ' + resultado;
            } // fecha else

            $('#newTotalCalculado').html(resultado);
        });

        $("#modalValorUnitario").priceFormat();
        $("#newValorUnitario").priceFormat();
        
        CKEDITOR.replace( 'descJustificativa', { toolbar: [] } );
        
        
        <?php if($this->idPerfil == 1111){ ?>
            $('.restaurarItem').live('click', function(){
                var idPlanilha = $(this).attr('idPlanilha'),
                    tpAcao = $(this).attr('tipo'),
                    msg = 'Tem certeza que deseja restaurar o item excluído?';

                $("#msgAlerta").dialog("destroy");
                $("#msgAlerta").html(msg);
                $("#msgAlerta").dialog({
                    resizable: false,
                    width:320,
                    modal: true,
                    title: 'Alerta!',
                    buttons : {
                        'Não' : function(){
                            $(this).dialog('close');
                        },
                        'Sim' : function(){
                            $("#msgAlerta").dialog('close');
                            $.ajax({
                                type: 'POST',
                                url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'alteracoes-tecnicas-no-item'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                                data: {
                                    idPlanilha: idPlanilha,
                                    tpAcao: tpAcao
                                },
                                success: function(data){
                                    $("#msgAlerta").dialog("destroy");
                                    atualizarDadosPlanilha();
                                }
                            });
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            });
        <?php } ?>
    });
    
    function enviarformulario(){
        $('#formReadequacao').submit();
    }
    
    function finalizarformulario(){
        window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'finalizar-solicitacao-readequacao'), null, true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>";
    }
    
    function excluirReadequacao(idReadequacao){
        window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'excluir-solicitacao-readequacao'), null, true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>&idReadequacao="+idReadequacao;
    }

    function atualizarDadosLocaisRealizacao(){
        jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'carregar-locais-de-realizacao'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>', '', 'locaisParaRealizacao');
   }
    
    function atualizarDadosPlanosDeDivulgacao(){
        jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'carregar-planos-de-divulgacao'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>', '', 'planosDeDivulgacao');
    }
    
    function atualizarDadosPlanosDeDistribuicao(){
        jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'carregar-planos-de-distribuicao'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>', '', 'planosDeDistribuicao');
	// adicionar verificação da readequacao
        $.ajax({
            url : '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'consultar-readequacao'), '', true); ?>',
            type: "POST",
	    data: {
		idPronac: <?php echo $this->idPronac; ?>,
		idTipoReadequacao: 11,
		idReadequacao: ''
	    },
	    success: function(data) {
		var readequacoes = JSON.parse(data).readequacoes;

		// @todo remove
		// se houver mais de uma readequacao pega a primeira
		var readequacao = (typeof readequacoes.length != 'undefined') ? readequacoes[0] : readequacoes;
		
		if (readequacao.idReadequacao != '') {
		    $('#idReadequacao').val(readequacao.idReadequacao);
		    CKEDITOR.instances['descJustificativa'].setData(readequacao.dsJustificativa);
		}
	    }
	});
    }
    
    function criarCampoTipoReadequacao(tpReadequacao){
        jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'criar-campo-tipo-readequacao'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>&tpReadequacao='+tpReadequacao, '', 'campoCriadoTipoReadequacao');
    }
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'), null, true); ?><?php echo '?idPronac='. Seguranca::encrypt($this->idPronac); ?>" title="Ir para In&iacute;cio">Consultar dados do Projeto</a></li>
        <li class="last">Solicitar Readequa&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Solicitar Readequa&ccedil;&atilde;o<span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="msgAlerta" class="sumir"></div>

<div id="conteudo">

    <!-- ========== INÍCIO FORMULÁRIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'incluir-solicitacao-readequacao'), null, true); ?><?php echo '?idPronac='. Seguranca::encrypt($this->idPronac); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" id="idReadequacao" name="idReadequacao" value="<?php echo ''; ?>">
        <table class="tabela">
            <tr>
                <th style="width: 30%">PRONAC</th>
                <th>Nome do Projeto</th>
            </tr>
            <tr class="centro">
                <td><?php echo $this->projeto->AnoProjeto.$this->projeto->Sequencial; ?></td>
                <td><?php echo $this->projeto->NomeProjeto; ?></td>
            </tr>
        </table>
        
        <table class="tabela">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Tipo de Readequa&ccedil;&atilde;o</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples comboReadequacoes" style="width: 200px;" name="tipoReadequacao" id="tipoReadequacao">
                        <option value="0"> - Selecione - </option>
                        <?php foreach ($this->TiposReadequacao as $tipos){ ?>
                        <?php if($tipos->idTipoReadequacao != 1 && $tipos->idTipoReadequacao != 2){ //Retirando o Tipo de Readequação de Remanejamento 20% e planilha orçamentária / remanejamento interno ?>
                        <option value="<?php echo $tipos->idTipoReadequacao; ?>"><?php echo $tipos->dsReadequacao; ?></option>
                        <?php } ?>
                        <?php } ?>
                    </select>
                </td>
            </tr>
        </table>
        
        <table class="tabela localRealizacao sumir">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Local de Realiza&ccedil;&atilde;o</td>
            </tr>
            <tr>
                <td id="locaisParaRealizacao"></td>
            </tr>
        </table>
        
        <table class="tabela planosDeDivulgacao sumir">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Plano de Divulga&ccedil;&atilde;o</td>
            </tr>
            <tr>
                <td id="planosDeDivulgacao"></td>
            </tr>
        </table>
        
        <table class="tabela planosDeDistribuicao sumir">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Plano de Distribui&ccedil;&atilde;o</td>
            </tr>
            <tr>
                <td id="planosDeDistribuicao"></td>
            </tr>
        </table>
        
        <table class="tabela sumir" id="campoAdicionadoPorTipoReadequacao">
            <tr>
                <td class="destacar">
                    <p class="bold" style="font-size: 13px;">Apresente abaixo <span id="txAuxilio"></span> que irá substituir a informação atual. <span class="red">*</span></p>
                    <p class="red">Atenção: O texto apresentado deve estar completo, inclusive com as partes que não serão alteradas, uma vez que as informações apresentadas irão substituir integralmente as aprovadas contidas no SALIC.</p>
                </td>
            </tr>
            <tr>
                <td id="campoCriadoTipoReadequacao"></td>
            </tr>
        </table>
        
        
        <table class="tabela solicitacoesSimples sumir">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Justificativa da Solicita&ccedil;&atilde;o <span class="red">*</span></td>
            </tr>
            <tr>
                <td><textarea cols="80" id="descJustificativa" name="descJustificativa" rows="10"></textarea></td>
            </tr>
            <tr>
                <td><span class="red">* Campo obrigatório e permite o máximo de 5.000 caracteres</span></td>
            </tr>
        </table>
        
        <table class="tabela solicitacoesSimples sumir">
            <tr>
                <td class="destacar bold" style="font-size: 13px;">Anexo</td>
            </tr>
            <tr>
                <td><input type="file" name="arquivo" class="input_simples"> <span style="margin-left: 10px;" class="red">Somente arquivos .pdf</span></td>
            </tr>
        </table>
        
        <table class="tabela btnIncluir sumir">
            <tr>
                <td class="centro">
                    <input type="button" class="btn_salvar" id="IncluirReadequacao" />
                </td>
            </tr>
        </table>
        
        <?php if(count($this->readequacoesCadastradas)>0){ ?>
        <fieldset>
            <legend>Readequações cadastradas</legend>
            <table class="tabela">
                <tr>
                    <th>Tipo Readequação</th>
                    <th>Dt. Solicitação</th>
                    <th>Descrição</th>
                    <th>Justificativa</th>
                    <th>Arquivo</th>
                    <th>Ação</th>
                </tr>
                <?php foreach ($this->readequacoesCadastradas as $rc){ ?>
                <tr>
                    <td><?php echo $rc->dsReadequacao; ?></td>
                    <td class="centro"><?php echo Data::tratarDataZend($rc->dtSolicitacao, 'Brasileira', true); ?></td>
                    <td class="centro">
                        <?php if(!empty($rc->dsSolicitacao)){ ?>
                        <img src="<?php echo $this->baseUrl(); ?>/public/img/table_multiple.png" style="cursor: pointer;" class="detalharTextos" texto="<?php echo htmlentities($rc->dsSolicitacao); ?>" />
                        <?php } else { echo '-'; } ?>
                    </td>
                    <td class="centro">
                        <?php if(!empty($rc->dsJustificativa)){ ?>
                        <img src="<?php echo $this->baseUrl(); ?>/public/img/table_multiple.png" style="cursor: pointer;" class="detalharTextos" texto="<?php echo htmlentities($rc->dsJustificativa); ?>" />
                        <?php } else { echo '-'; } ?>
                    </td>
                    <?php if(!empty($rc->idArquivo)){ ?>
                        <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $rc->idArquivo; ?>"><?php echo $rc->nmArquivo; ?></a></td>
                    <?php } else { ?>
                        <td class="centro">-</td>
                    <?php } ?>
                    <td class="centro" style="width: 150px;"><input type="button" class="btn_exclusao" readequacao="<?php echo $rc->idReadequacao; ?>"></td>
                </tr>
                <?php } ?>
            </table>
        </fieldset>
        
        <table class="tabela">
            <tr>
                <td class="centro">
                    <input type="button" class="btn_finalizar" id="btn_finalizar" title="Finalizar" />
                    <input type="button" class="btn_cancelar" id="btn_cancelar" title="Cancelar" />
                </td>
            </tr>
        </table>
        <?php } ?>
    </form>
    <!-- ========== FIM FORMULÁRIO ========== -->

    <?php //MODAL DE AVALIAÇÃO DO ITEM ?>
    <div id="modalItem" class="sumir">
        <table class="tabela">
            <tr>
                <td class="destacar bold">Produto</td>
                <td class="destacar bold">Etapa</td>
                <td class="destacar bold">Item</td>
                <td class="destacar bold">Vl. Comprovado</td>
            </tr>
            <tr>
                <td id="campoProduto" class="camposModal">&nbsp;</td>
                <td id="campoEtapa" class="camposModal">&nbsp;</td>
                <td id="campoItem" class="camposModal">&nbsp;</td>
                <td class="camposModal green bold direita"><span id="campoValorComprovado">&nbsp;</span></td>
            </tr>
        </table>
        
        <table class="tabela">
            <tr>
                <th colspan="6">Valores Solicitados</th>
            </tr>
            <tr class="centro">
                <td class="destacar bold">Unidade</td>
                <td class="destacar bold">Qtd</td>
                <td class="destacar bold">Ocorrência</td>
                <td class="destacar bold">Vl. Unitário</td>
                <td class="destacar bold">Dias</td>
                <td class="destacar bold">Total</td>
                <!--<td class="destacar bold" style="width: 1px;">Reintegrar</td>-->
            </tr>
            <tr>
                <td id="campoUnidadeSolicitado" class="camposModal">&nbsp;</td>
                <td id="campoQtdSolicitado" class="direita camposModal">&nbsp;</td>
                <td id="campoOcorrenciaSolicitado" class="direita camposModal">&nbsp;</td>
                <td id="campoVlUnitarioSolicitado" class="direita camposModal">&nbsp;</td>
                <td id="campoDiasSolicitado" class="direita camposModal">&nbsp;</td>
                <td id="campoTotalSolicitado" class="direita camposModal">&nbsp;</td>
<!--                <td class="centro">
                    <img idPlanilha="" src="<?php //echo $this->baseUrl(); ?>/public/img/refresh.gif" title="Reintegrar Item" class="reintegrar" id="campoIdPlanilha" style="cursor: pointer">
                </td>-->
            </tr>
        </table>
        
        <table class="tabela">
            <tr>
                <th colspan="6">Dados para a readequação</th>
            </tr>
            <tr class="centro">
                <td class="destacar bold">Unidade</td>
                <td class="destacar bold">Qtd</td>
                <td class="destacar bold">Ocorrência</td>
                <td class="destacar bold">Vl. Unitário</td>
                <td class="destacar bold">Dias</td>
                <td class="destacar bold">Total</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples w150 modalObrigatorios" name="modalUnidade" id="modalUnidade">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Unidade as $unit){ ?>
                        <option value="<?php echo $unit->idUnidade; ?>"><?php echo $unit->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td class="centro"><input class="input_simples w50 multiplicarValores modalObrigatorios" id="modalQuantidade" type="text" maxlength="5" name="Quantidade" onkeyup="mascara(this, format_num);"></td>
                <td class="centro"><input class="input_simples w50 multiplicarValores modalObrigatorios" id="modalOcorrencia" type="text" maxlength="4" name="Ocorrencia" onkeyup="mascara(this, format_num);"></td>
                <td class="centro"><input class="input_simples w100 multiplicarValores modalValorUnitario modalObrigatorios" id="modalValorUnitario" type="text" maxlength="11" name="ValorUnitario"></td>
                <td class="centro"><input class="input_simples w50 modalObrigatorios" id="modalDias" type="text" maxlength="4" name="Dias" onkeyup="mascara(this, format_num);"></td>
                <td id="TotalCalculado" class="direita" style="width: 125px;"></td>
            </tr>
            <tr>
                <td colspan="6" class="destacar bold centro">Justificativa da Readequação <span class="red">*</span> <span id="textoErroValores" style="float:right; color: red;"></span></td>
            </tr>
            <tr>
                <td colspan="6" class="centro">
                    <textarea id="modalJustificativa" class="textarea_simples modalObrigatorios" rows="3" style="width:98%" name="Justificativa"></textarea>
                </td>
            </tr>
        </table>
    </div>
    <?php //FIM MODAL DE AVALIAÇÃO DO ITEM ?>

    <?php //MODAL DE INCLUSÃO DE ITEM ?>
    <div id="modalInclusaoItem" class="sumir">
        <table class="tabela">
            <tr><?php //xd($this->UFs); ?>
                <td class="destacar bold" style="width: 33%">Recursos</td>
                <td class="destacar bold" style="width: 33%">UF</td>
                <td class="destacar bold" style="width: 33%">Município</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples w200 camposObrigatoriosInclusao" name="newRecursos" id="newRecursos">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Recursos as $rec){ ?>
                        <option value="<?php echo $rec->idVerificacao; ?>"><?php echo $rec->VerificacaoDescricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td>
                    <select class="select_simples w200 newUF camposObrigatoriosInclusao" name="newUF" id="newUF">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->UFs as $ufs){ ?>
                        <option value="<?php echo $ufs->id; ?>"><?php echo $ufs->descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td>
                    <select class="select_simples w200 camposObrigatoriosInclusao" name="newMunicipio" id="newMunicipio">
                        <option value=""> - Selecione - </option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" style="width: 33%">Etapa</td>
                <td class="destacar bold" style="width: 33%">Produto</td>
                <td class="destacar bold" style="width: 33%">Item</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples w200 camposObrigatoriosInclusao" name="newEtapa" id="newEtapa">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Etapas as $etapas){ ?>
                        <option value="<?php echo $etapas->idPlanilhaEtapa; ?>"><?php echo $etapas->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td>
                    <select class="select_simples w200 camposObrigatoriosInclusao" name="newProduto" id="newProduto">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Produtos as $prod){ ?>
                        <option value="<?php echo $prod->idProduto; ?>"><?php echo $prod->Produto; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td>
                    <select class="select_simples w200 camposObrigatoriosInclusao" name="newItem" id="newItem">
                        <option value=""> - Selecione - </option>
                    </select>
                </td>
            </tr>
        </table>

        <table class="tabela">
            <tr>
                <th colspan="6">Dados do Item</th>
            </tr>
            <tr class="centro">
                <td class="destacar bold w150">Unidade</td>
                <td class="destacar bold">Qtd</td>
                <td class="destacar bold">Ocorrência</td>
                <td class="destacar bold">Vl. Unitário</td>
                <td class="destacar bold">Dias</td>
                <td class="destacar bold">Total</td>
            </tr>
            <tr>
                <td>
                    <select class="select_simples w150 camposObrigatoriosInclusao" name="newUnidade" id="newUnidade">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->Unidade as $unit){ ?>
                        <option value="<?php echo $unit->idUnidade; ?>"><?php echo $unit->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td class="centro"><input class="input_simples w50 newMultiplicarValores camposObrigatoriosInclusao" type="text" maxlength="5" name="newQuantidade" id="newQuantidade" onkeyup="mascara(this, format_num_float);"></td>
                <td class="centro"><input class="input_simples w50 newMultiplicarValores camposObrigatoriosInclusao" type="text" maxlength="4" name="newOcorrencia" id="newOcorrencia" onkeyup="mascara(this, format_num_float);"></td>
                <td class="centro"><input class="input_simples w100 newMultiplicarValores camposObrigatoriosInclusao" type="text" maxlength="11" name="newValorUnitario" id="newValorUnitario"></td>
                <td class="centro"><input class="input_simples w50 camposObrigatoriosInclusao" type="text" maxlength="4" name="newDias" id="newDias" onkeyup="mascara(this, format_num);"></td>
                <td id="newTotalCalculado" class="direita" style="width: 125px;"></td>
            </tr>
            <tr>
                <td colspan="6" class="destacar bold centro">Justificativa <span class="red">*</span></td>
            </tr>
            <tr>
                <td colspan="6" class="centro">
                    <textarea class="textarea_simples camposObrigatoriosInclusao" rows="3" style="width:98%" name="newJustificativa" id="newJustificativa"></textarea>
                </td>
            </tr>
        </table>
    </div>
    <?php //MODAL DE INCLUSÃO DE ITEM ?>

</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />
