<script type="text/javascript">
    $(document).ready(function(){
        $("#btn_pesquisar").click(function(){
            $('#formPesquisa').submit();
        });

        $('.btn_imprimir').click(function(){
            $('#formImpressao').submit();
        });

        $('.btn_ver').click(function(){
            var id = $(this).attr('idReadequacao');
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'visualizar-readequacao')); ?>?id="+id;
        });

        $('.finalizarAnaliseReadequacao').click(function(){
            var id = $(this).attr('idReadequacao');
            $("#alerta").dialog("destroy");
            $("#alerta").html('Deseja realmente finalizar a análise da readequação?');
            $("#alerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width: 380,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'encaminhar-readequacao-checklist')); ?>?id="+id;
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });

        $('.devolverReadequacao').click(function(){
            var id = $(this).attr('idReadequacao');
            $("#alerta").dialog("destroy");
            $("#alerta").html('Deseja realmente devolver a readequação para uma nova análise?');
            $("#alerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width: 340,
                height: 180,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'devolver-readequacao')); ?>?id="+id;
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });

        $('.btn_encaminhar').click(function(){
            var id = $(this).attr('readequacao');
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'encaminhar-analise-tecnica')); ?>?id="+id + "&filtro=<?php echo $this->filtro; ?>";
        });

        $('.btn_avaliar').click(function(){
            var id = $(this).attr('readequacao');
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'avaliar-readequacao')); ?>?id="+id + "&filtro=<?php echo $this->filtro; ?>";
        });        

        $('.imgRegularidade').click(function(){
            var cpfcnpj = $(this).attr('cgccpf'),
                pronac = $(this).attr('pronac');
            $('#cpfCnpj').val(cpfcnpj);
            $('#pronacEnviado').val(pronac);
            $('#formRegularidade').submit();
        });

        $('.finalizarReadequacao').click(function(){
            var componente = $(this).parent().parent().find('select.comboComponente').val(),
                idReadequacao = $(this).attr('idReadequacao');

            if(componente==''){
                $("#alerta").dialog("destroy");
                $("#alerta").html('Favor selecionar o componente da comissão!');
                $("#alerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:340,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();

            } else {
                $("#alerta").dialog("destroy");
                $("#alerta").html('Deseja realmente enviar a readequação para a análise da CNIC?<br /><br />Ao enviar a readequação será removida do seu painel.');
                $("#alerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width: 430,
                    modal: true,
                    buttons : {
                        'Não' : function(){
                            $(this).dialog('close');
                        },
                        'Sim' : function(){
                            $.ajax({
                                type: 'POST',
                                url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'coord-analise-finalizar-readequacao'), '', true); ?>',
                                data: {
                                    componente: componente,
                                    idReadequacao: idReadequacao
                                },
                                success: function(data){
                                    if(data.resposta){
                                        $("#alerta").dialog("destroy");
                                        $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                                        $("#alerta").dialog({
                                            resizable: false,
                                            width:320,
                                            modal: true,
                                            title: 'Carregando..'
                                        });
                                        $('.ui-dialog-titlebar-close').remove();
                                        window.setTimeout('location.reload()', 1000);
                                    } else {
                                        alertaModal("Não foi possível finalizar a readequação.");
                                    }
                                },
                                dataType : 'json'
                            });
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            }
        });
 
        $('.comboFiltro').change(function(){
	    $('#formPesquisa').submit();
        });	       
    });
</script>

<?php
$situacoes = array(
    'aguardando_distribuicao' => 'Aguardando distribuição',
    'em_analise' => 'Em análise',
    'analisados' => 'Analisados'
);
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="alerta"></div>

<div id="breadcrumb">
    <ul>
        <li class="first">Início</li>
        <li>Readequa&ccedil;&otilde;es</li>
        <li class="last"><?php echo $situacoes[$this->filtro]; ?></li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div><?php echo $situacoes[$this->filtro]; ?></div>
</div>

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <form name="formPesquisa" id="formPesquisa" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel'));?>" method="get">
        <table class="tabela">
            <tr>
                <th colspan="8">Filtro de Pesquisa</th>
            </tr>
            <tr class="divFiltroPesquisa">
                <td class="destacar bold" width="60">PRONAC</td>
                <td width="120">
                    <input type="text" class="input_simples" name="pronac" maxlength="7" style="width: 70px;" value="<?php echo $this->pronac;?>">
                    <input type="hidden" name="qtde" value="<?php echo $this->intTamPag;?>">
                </td>
                <td class="destacar bold" width="60">Situa&ccedil;&atilde;o</td>
                <td width="200">
                    <select name="tipoFiltro" style="width: 200px;" class="input_simples comboFiltro">
		      <?php foreach ($situacoes as $chave => $valor): ?>
		      <option value="<?php echo $chave; ?>" <?php echo ($this->filtro == $chave) ? "selected" : ""; ?>><?php echo $valor; ?></option>
<?php endforeach; ?>                                                                              
                    </select>
                </td>
                <td colspan="6" align="rigth">
                    <input type="button" name="btn_pesquisar" id="btn_pesquisar" class="btn_pesquisar" value="">
                </td>
            </tr>
        </table>
    </form>

    <?php if(count($this->dados)>0){ ?>
    <!-- ============ PAGINAÇÃO ============ -->
    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr>
                <td align="center">
                <form name="form1" id="form1" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel'));?>" method="get">
                    <?php if($this->paginacao['pag']>1): ?>
                    <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                    <?php endif; ?>
                    <input id="btn_p_anterior" type="button"
                    <?php if($this->paginacao['pag']<=1):  ?> class="btn_p_anterior-off"
                    <?php else: ?>
                           class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                    <?php endif; ?>>
                    <input id="btn_p_proximo" type="button"
                           <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']):  ?>
                           class="btn_p_proximo-off"
                    <?php else: ?>
                           class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                    <?php endif; ?>>
                    <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']): ?>
                    <input class="btn_ultimo" id="btn_ultimo" type="button"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                    <?php endif; ?>
                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()" class="input_simples">
                        <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                            <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                        <?php endfor; ?>
                    </select>
                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                    <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
                    <input type="hidden" name="pronac" value="<?php echo $this->pronac;?>">
                    <input type="button" class="btn_imprimir">
                 </form>
                </td>
            </tr>
        </tbody>
    </table>
    <center>
        <?php
            echo $this->paginacao['inicio']." a ";
            echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
            echo " de ". $this->paginacao['total']. " Projetos listados";
        ?>
    </center>
    <!-- ========== FIM PAGINAÇÃO ========== -->
    <?php } ?>


    <!-- Tabela com os dados-->
    <?php if($this->qtdRegistros > 0): ?>
        <table class="tabela tablesorter">
            <?php if($this->filtro == 'analisados'): ?>
	    <?php echo $this->partial('readequacoes/partial/analisados.phtml', array('dados' => $this->dados, 'filtro' => $this->filtro, 'conselheiros' => $this->conselheiros, 'paginacao' => $this->paginacao, 'pronac' => $this->pronac)); ?>
            <?php elseif($this->filtro == 'em_analise'): ?>
                <?php echo $this->partial('readequacoes/partial/emAnalise.phtml', array('dados' => $this->dados, 'filtro' => $this->filtro, 'paginacao' => $this->paginacao, 'pronac' => $this->pronac)); ?>
            <?php else: ?>
                <?php echo $this->partial('readequacoes/partial/aguardandoDistribuicao.phtml', array('dados' => $this->dados, 'filtro' => $this->filtro, 'paginacao' => $this->paginacao, 'pronac' => $this->pronac)); ?>
            <?php endif;?>
        </table>

        <?php if(count($this->dados)>0): ?>

            <!-- ============ PAGINAÇÃO ============ -->
            <?php if($this->qtdRegistros > 10) { //echo $this->dados; ?>
            <center>
                <?php
                    echo $this->paginacao['inicio']." a ";
                    echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                    echo " de ". $this->paginacao['total'];
                ?>
            </center>
            <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td align="center">
                            <form name="form2" id="form2" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel'));?>" method="get">
                                <?php if($this->paginacao['pag']>1) : ?>
                                    <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                                       onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                                <?php endif; ?>

                                <input id="btn_p_anterior" type="button"
                                    <?php if($this->paginacao['pag']<=1) : ?> class="btn_p_anterior-off"
                                    <?php else : ?>
                                           class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                                    <?php endif; ?>>

                                <input id="btn_p_proximo" type="button"
                                       <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']):  ?>
                                           class="btn_p_proximo-off"
                                        <?php else: ?>
                                               class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                                        <?php endif; ?>>

                                <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']): ?>
                                    <input class="btn_ultimo" id="btn_ultimo" type="button"
                                           onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                                <?php endif; ?>
                                Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()" class="input_simples">
                                    <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                                        <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                                    <?php endfor; ?>
                                </select>
                                &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                                <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                                <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                                <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
                                <input type="hidden" name="pronac" value="<?php echo $this->pronac;?>">
                                <input type="button" class="btn_imprimir">
                             </form>
                        </td>
                    </tr>
                </tbody>
            </table>
            <!-- ========== FIM PAGINAÇÃO ========== -->
        <?php }  ?>
        <?php endif; ?>

    <?php else:  ?>
    <table class="tabela">
        <tr>
            <td align="center">Nenhum registro encontrado.</td>
        </tr>
    </table>
    <?php endif; ?>
    <br clear="all" />

    <form target="_blank" class="form" name="formRegularidade" id="formRegularidade" method="post" action='<?php echo $this->url(array('controller' => 'manterregularidadeproponente', 'action' => 'manterregularidadeproponente')); ?>'>
        <input type="hidden" name="cpfCnpj" id="cpfCnpj" value="" />
        <input type="hidden" name="pronacEnviado" id="pronacEnviado" value="" />
    </form>

    <form target="_blank" class="form" name="formImpressao" id="formImpressao" method="post"
            action='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'imprimir-readequacoes')); ?>'>
        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
        <input type="hidden" name="pag" value="<?php echo $this->paginacao['pag'];?>">
        <input type="hidden" name="qtde" value="<?php echo $this->intTamPag;?>">
        <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
        <input type="hidden" name="pronac" value="<?php echo $this->pronac;?>">
    </form>
</div>

<div id="modalConfirmacao" class="sumir"></div>
<div id="modalAvaliacao" class="sumir" title="Avalição de Readequação">
    <form name="formencaminhar" action="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/encaminhacoordacompanhamento" method="post">
        <table class="tabela">
            <tr>
                <td class="destacar bold" width="1%">PRONAC</td>
                <td class="destacar bold">Nome do Projeto</td>
            </tr>
            <tr>
                <td align="center" id="xPronac"></td>
                <td id="xNomeProjeto"></td>
            </tr>
            <tr>
                <td class="destacar bold" colspan="2">Solicita&ccedil;&atilde;o</td>
            </tr>
            <tr>
                <td colspan="2" id="xRecurso"></td>
            </tr>
        </table>
        <table class="tabela">
            <tr>
                <td class="destacar bold" colspan="2">Resposta</td>
            </tr>
            <tr>
                <td colspan="2">
                    <label style="font-weight: normal;"><input type="radio" class="radioAvaliacao" value="1" name="avaliacao" checked="checked"> Deferir</label>
                    <label style="font-weight: normal;"><input type="radio" class="radioAvaliacao" value="2" name="avaliacao" style="margin-left: 20px;"> Indeferir</label>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <textarea maxlength="255" class="textarea_simples" name="observacao" id="observacao" disabled="disabled" rows="4" cols="50" style="width:98%;"></textarea>
                    <span style="font-size: 11px;">Quantidade m&aacute;xima de 255 caracteres.</span>
                </td>
            </tr>
        </table>
        <table class="tabela">
            <tr>
                <td class="destacar bold" width="130px;">Encaminhar para:</td>
                <td>
                    <select name="entidade" id="entidade" class="select_simples" disabled="disabled" style="width:100%;">
                        <option value="0"> - Selecione - </option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" width="130px;">Destinatário:</td>
                <td>
                    <select name="destinatario" id="destinatario" class="select_simples" disabled="disabled" style="width:100%;"></select>
                </td>
            </tr>
        </table>
    </form>
</div>
<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />
