<script type="text/javascript">
    $(document).ready(function(){
        $("#btn_pesquisar").click(function(){
            $('#formPesquisa').submit();
        });

        $('.btn_imprimir').click(function(){
            $('#formImpressao').submit();
        });
        
        $('.btn_ver').click(function(){
            var id = $(this).attr('idReadequacao');
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'visualizar-readequacao')); ?>?id="+id;
        });
        
        $('.enviarReadequacao').click(function(){
            var parecerista = $(this).parent().parent().find('select').val(),
                idDistRead = $(this).attr('idDistRead'),
                idReadequacao = $(this).attr('idReadequacao');
                
            if(parecerista==''){
                $("#alerta").dialog("destroy");
                $("#alerta").html('Favor selecionar o parecerista!');
                $("#alerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            } else {
            
                $("#alerta").dialog("destroy");
                $("#alerta").html('Deseja realmente enviar a solicitação para o parecerista?');
                $("#alerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:170,
                    modal: true,
                    buttons : {
                        'Não' : function(){
                            $(this).dialog('close');
                        },
                        'Sim' : function(){
                            $(this).dialog('close');
                            $.ajax({
                                type: 'POST',
                                url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'encaminhar-readequacao'), '', true); ?>',
                                data: {
                                    parecerista: parecerista,
                                    idDistRead: idDistRead,
                                    idReadequacao: idReadequacao
                                },
                                success: function(data){
                                    if(data.resposta){
                                        $("#alerta").dialog("destroy");
                                        $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                                        $("#alerta").dialog({
                                            resizable: false,
                                            width:320,
                                            modal: true,
                                            title: 'Carregando..'
                                        });
                                        $('.ui-dialog-titlebar-close').remove();
                                        window.setTimeout('location.reload()', 1000);
                                    } else {
                                        alertaModal("Não foi possível encaminhar a readequação.");
                                    }
                                },
                                dataType : 'json'
                            });
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            }
        });
        
        $('.btn_finalizar').click(function(){
            var idDistProj = $(this).attr('idDistProj'),
                idReadequacao = $(this).attr('idReadequacao');
                
            $("#alerta").dialog("destroy");
            $("#alerta").html('Deseja realmente finalizar a análise da readequação?<br /><br />Ao finalizar a readequação será devolvida ao MinC.');
            $("#alerta").dialog({
                resizable: false,
                title: 'Alerta!',
                width: 430,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'coord-parecer-finalizar-readequacao'), '', true); ?>',
                            data: {
                                idDistProj: idDistProj,
                                idReadequacao: idReadequacao
                            },
                            success: function(data){
                                if(data.resposta){
                                    $("#alerta").dialog("destroy");
                                    $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"><br />Aguarde..</div>');
                                    $("#alerta").dialog({
                                        resizable: false,
                                        width:320,
                                        modal: true,
                                        title: 'Carregando..'
                                    });
                                    $('.ui-dialog-titlebar-close').remove();
                                    window.setTimeout('location.reload()', 1000);
                                } else {
                                    alertaModal("Não foi possível finalizar a readequação.");
                                }
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
            
        });
        
        $('.avaliacaoParecerista').click(function(){
            var id = $(this).attr('idReadequacao');
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'form-avaliar-readequacao')); ?>?id="+id;
        });

        $('.comboFiltro').change(function(){
            window.location = "<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')); ?>?tipoFiltro=" + $(this).val();
        });	
        
    });
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="alerta" class="sumir"></div>

<?php
$situacoes = array(
    'painel_do_tecnico' => 'Painel do técnico',
    'aguardando_distribuicao' => 'Aguardando distribuição',
    'em_analise' => 'Em análise',
    'analisados' => 'Analisados'
);
?>    
     
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para Inï¿½cio">Início</a></li>
        <li>Avaliar Readequa&ccedil;&otilde;es</li>
	<li class="last"><?php echo $situacoes[$this->filtro]; ?></li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div><?php echo $situacoes[$this->filtro]; ?></div>
</div>


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <?php if($this->idPerfil == 93){ ?>
    <form name="formPesquisa" id="formPesquisa" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes'));?>" method="get">
        <table class="tabela">
            <tr>
                <th colspan="2">Filtro de Pesquisa</th>
            </tr>
            <tr class="divFiltroPesquisa">
                <td class="destacar bold" width="60">Situa&ccedil;&atilde;o</td>
                <td>
                    <select name="tipoFiltro" style="width: 200px;" class="input_simples comboFiltro">
		      <?php foreach ($situacoes as $chave => $valor): ?>
		      <option value="<?php echo $chave; ?>" <?php echo ($this->filtro == $chave) ? "selected" : ""; ?>><?php echo $valor; ?></option>
                      <?php endforeach; ?>
                    </select>
                    <input type="button" name="btn_pesquisar" id="btn_pesquisar" class="btn_pesquisar" value="" style="margin-left: 10px;">
                </td>
            </tr>
        </table>
    </form>
    <?php } ?>
    
    <?php if(count($this->dados)>0){ ?>
    <!-- ============ PAGINAÇÃO ============ -->
    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr>
                <td align="center">
                <form name="form1" id="form1" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes'));?>" method="get">
                    <?php if($this->paginacao['pag']>1) { ?>
                    <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                    <?php } ?>
                    <input id="btn_p_anterior" type="button"
                    <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                    <?php }else { ?>
                           class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                    <?php } ?>>
                    <input id="btn_p_proximo" type="button"
                           <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                           class="btn_p_proximo-off"
                    <?php }else { ?>
                           class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                    <?php } ?>>
                    <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                    <input class="btn_ultimo" id="btn_ultimo" type="button"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                    <?php } ?>
                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()" class="input_simples">
                        <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                        <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                        <?php endfor; ?>
                    </select>
                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                    <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
                    <input type="hidden" name="pronac" value="<?php echo $this->pronac;?>">
                    <!--<input type="button" class="btn_imprimir">-->
                 </form>
                </td>
            </tr>
        </tbody>
    </table>
    <center>
        <?php
            echo $this->paginacao['inicio']." a ";
            echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
            echo " de ". $this->paginacao['total']. " Projetos listados";
        ?>
    </center>
    <!-- ========== FIM PAGINAÇÃO ========== -->
    <?php } ?>


    <?php if($this->qtdRegistros > 0){ ?>
    <table class="tabela tablesorter">
        <thead>
            <tr class="titulo_tabela">
                <th style="width: 80px;"><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=3&ordem='.$this->paginacao['novaOrdem'];?>">PRONAC</a></th>
                <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=4&ordem='.$this->paginacao['novaOrdem'];?>">Nome do Projeto</a></th>
                <th><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=10&ordem='.$this->paginacao['novaOrdem'];?>">Tipo Readequação</a></th>
		
		<?php if ($this->filtro == 'aguardando_distribuicao' || $this->filtro == 'analisados'): ?> 
		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Envio</a></th>
		<?php endif; ?>

		<?php if ($this->filtro == 'em_analise' || $this->filtro == 'analisados' || $this->filtro == 'painel_do_tecnico'): ?> 
		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Distribuição</a></th>
		<?php endif; ?>

		<?php if ($this->filtro == 'analisados'): ?> 
		<th style="width: 130px;" nowrap><a href="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1&qtde='.$this->paginacao['qtde'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac.'&campo=5&ordem='.$this->paginacao['novaOrdem'];?>">Data Devolução</a></th>
		<?php endif; ?>
		
		<?php if ($this->filtro == 'aguardando_distribuicao'): ?>
		<th>Qtd dias aguardando distribuição</th>
		<?php endif; ?>
		
		<?php if ($this->filtro == 'em_analise'): ?>
		<th>Qtd dias aguardando análise</th>
		<?php endif; ?>

		<?php if ($this->filtro == 'painel_do_tecnico'): ?>
		<th>Qtde dias em avalia&ccedil;atilde;o</th>
		<th>Dilig&ecirc;ncia</th>
		<th>Avaliar</th>
		<?php endif; ?>
		
		<?php if ($this->filtro == 'analisados'): ?>
		<th>Qtd dias para distribuir</th>
		<th>Qtd dias para avaliar</th>
		<th>Total em dias para avaliar</th>
		<?php endif; ?>
		
                <th style="width: 130px;">Visualizar</th>
                <th style="width: 130px;">Encaminhar</th>

		<?php if ($this->filtro == 'analisados'): ?>
		<th>Finalizar</th>
		<?php endif; ?>
            </tr>
        </thead>
        <tbody>
          <?php foreach($this->dados as $d): ?>
          <tr>
                <td align="center">
                    <a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->idPronac); ?>" target="_blank">
                        <?php echo $d->PRONAC; ?>
                    </a>
                </td>

		<td><?php echo $d->NomeProjeto; ?></td>
		
		<td><?php echo $d->tpReadequacao; ?></td>
		
		<?php if ($this->filtro == 'aguardando_distribuicao' || $this->filtro == 'analisados'): ?>
		
                <td align="center"><?php if ($d->dtEnvio == '') { echo '---'; } else { echo Data::tratarDataZend($d->dtEnvio, 'Brasileira'); } ?></td>
		<?php endif; ?>	
		
		<?php if ($this->filtro == 'em_analise' || $this->filtro == 'analisados' || $this->filtro == 'painel_do_tecnico'): ?>
                <td align="center"><?php if ($d->dtDistribuicao == '') { echo '---'; } else { echo Data::tratarDataZend($d->dtDistribuicao, 'Brasileira'); } ?></td>
		<?php endif; ?>
		
		<?php if ($this->filtro == 'aguardando_distribuicao'): ?>
		<td><?php echo $d->qtDiasAguardandoDistribuicao; ?></td>
		<?php endif; ?>
		
		<?php if ($this->filtro == 'em_analise'): ?>
		<td><?php echo $d->qtDiasEmAnalise; ?></td>
		<?php endif; ?>

		<?php if ($this->filtro == 'painel_do_tecnico'): ?>
		<td><?php echo $d->qtDiasAvaliacao; ?></td>
		
		<?php if($this->idPerfil == 121): //FUNO CRIADA APENAS PARA O PARECERISTA E TECNICO DE ACOMPANHAMENTO ?>
                 <td align="center" style="width: 1px;">
                     <?php
                         $tpDiligencia = 0;
                         if($this->idPerfil == 94){ //Parecerista
                             $tpDiligencia = 179;
                         } else if($this->idPerfil == 121){ //Tcnico de Acompanhamento
                             $tpDiligencia = 171;
                         }
                         
                         $arrPrazo = $this->prazoRespostaDiligencia($d->idPronac, $tpDiligencia);
                         $icone = $arrPrazo['iconeDiligencia']['icone'];
                         $title = $arrPrazo['iconeDiligencia']['title']; ?>
                         <a target="_blank" href="<?php echo $this->url(array('controller' => 'diligenciar', 'action' =>'listardiligenciaanalista')).'?idPronac=' . $d->idPronac . '&situacao=E59&tpDiligencia='.$tpDiligencia; ?>" ><img src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $icone; ?>" title="<?php echo $title; ?>" width="30px"/></a><br>
                 </td>
                 <?php endif; ?>
		 <td>
		   <input type="button" name="btn_avaliar" class="btn_avaliar avaliacaoParecerista" idReadequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>" title="Avaliar">
		 </td>
		 
		<?php endif; ?>
		
		<?php if ($this->filtro == 'analisados'): ?>
		<td><?php echo $d->dtDevolucao; ?></td>
		<td><?php echo $d->qtDiasDistribuir; ?></td>
		<td><?php echo $d->qtDiasAvaliar; ?></td>
		<td><?php echo $d->qtTotalDiasAvaliar; ?></td>
		<?php endif; ?>
		
                <td align="center">
                    <input type="button" class="btn_ver" idReadequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>" />
                </td>		

                <td align="center">
                  <input type="button" name="btn_encaminhar" class="btn_encaminhar enviarReadequacao" idDistRead="<?php echo $d->idDistribuirReadequacao; ?>" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Enviar">
		</td>
		
		<?php if ($this->filtro == 'analisados'): ?>
		<td align="center">
                  <input type="button" name="btn_finalizar" class="btn_finalizar" idDistProj="<?php echo $d->idDistribuirReadequacao; ?>" idReadequacao="<?php echo $d->idReadequacao; ?>" title="Finalizar">
		</td>
		<?php endif; ?>
		<!------------------------------- -->
                		
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php if(count($this->dados)>0){ ?>

        <!-- ============ PAGINAÇÃO ============ -->
        <?php if($this->qtdRegistros > 10) { //echo $this->dados; ?>
        <center>
            <?php
                echo $this->paginacao['inicio']." a ";
                echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                echo " de ". $this->paginacao['total'];
            ?>
        </center>
        <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td align="center">
                    <form name="form2" id="form2" action="<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes'));?>" method="get">
                        <?php if($this->paginacao['pag']>1) { ?>
                        <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                        <?php } ?>
                        <input id="btn_p_anterior" type="button"
                        <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                        <?php }else { ?>
                               class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                        <?php } ?>>
                        <input id="btn_p_proximo" type="button"
                               <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                               class="btn_p_proximo-off"
                        <?php }else { ?>
                               class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'"
                        <?php } ?>>
                        <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                        <input class="btn_ultimo" id="btn_ultimo" type="button"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'painel-readequacoes')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&tipoFiltro='.$this->filtro.'&pronac='.$this->pronac; ?>'">
                        <?php } ?>
                        Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()" class="input_simples">
                            <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                            <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                            <?php endfor; ?>
                        </select>
                        &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                        <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
                        <input type="hidden" name="pronac" value="<?php echo $this->pronac;?>">
                        <!--<input type="button" class="btn_imprimir">-->
                     </form>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- ========== FIM PAGINAÇÃO ========== -->

    <?php } } ?>


    <?php } else { ?>
    <table class="tabela">
        <tr>
            <td align="center">Nenhum registro encontrado.</td>
        </tr>
    </table>
    <?php } ?>
    <br clear="all" />

</div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />
