<div id="modalTransformarProposta" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h5>Deseja Transformar a proposta Nr. <span id="idPreProjetoSpan"></span>, em Projeto?</h5>
    </div>
    <div class="modal-footer">
        <button class="btn waves-effect waves-light "
                id="botaoTransformarPropostaEmProjeto"
                type="button">
            Sim
        </button>
        <a class="btn waves-effect waves-dark red-text white modal-close">
            Cancelar
        </a>
    </div>
</div>
<script type="text/javascript">
        $3("#modalTransformarProposta").modal();
        $3('#transformarPropostaEmProjeto').on('click', function () {
            $3("#idPreProjetoSpan").html($3(this).data("id-pre-projeto"));
            $3("#modalTransformarProposta").modal('open');
        });

        $("#botaoTransformarPropostaEmProjeto").click(function () {
            var idPreProjeto = parseInt($("#idPreProjetoSpan").html(), 10);

            Materialize.toast('Gerando PRONAC...', 3000, '', function () {
                $.post('<?php echo $this->baseUrl(); ?>/admissibilidade/admissibilidade/transformar-proposta-em-projeto?idPreProjeto=' + idPreProjeto,
                    {},
                    function (response) {
//console.log(response);
                        var resposta = response.sucesso;
                        if(response.hasOwnProperty("erro")){
                            resposta = response.erro;
                        }
                        Materialize.toast(resposta, 3000, '', function () {
                            window.location = '<?php echo $this->baseUrl(); ?>/admissibilidade/admissibilidade/listar-propostas';
                        });
                    },
                    'json'
                );
            });
        });
</script>
