<div>

    <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s1 right-align"><i class="medium orange-text material-icons">help_outline</i></div>
                <div class="col s11">
                    <p><b>Tem certeza que deseja finalizar a homologa&ccedil;&atilde;o desse projeto?</b></p>
                    <p>Ap&oacute;s a finaliza&ccedil;&atilde;o o projeto ter&aacute; a seguinte situa&ccedil;&atilde;o:
                        <?= $this->situacaoFutura['codigo']; ?> -  <?= $this->situacaoFutura['mensagem']; ?>.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <ul class="collapsible" data-collapsible="accordion">
        <?= $this->partial('/homologacao/partials/homologar-parecer.phtml', ['arrValue' => $this->arrValue, 'booShowAll' => false]); ?>
        <?= $this->partial('/homologacao/partials/visualizar-parecer-homologacao.phtml', ['arrValue' => $this->arrValue, 'booShowAll' => false]); ?>
    </ul>
</div>
