<li>
    <div class="collapsible-header active"><b>Identificação do projeto</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <tbody>
            <tr>
                <td>PRONAC</td>
                <td><?= $this->arrValue['Pronac'] ?></td>
                <td colspan="2"><?= $this->arrValue['enquadramentoProjeto']['NomeProjeto'] ?></td>
            </tr>
            <tr>
                <td>Proponente</td>
                <td><?= Validacao::mascaraCPFCNPJ($this->arrValue['enquadramentoProjeto']['CNPJCPF']) ?></td>
                <td colspan="2"><?= $this->arrValue['enquadramentoProjeto']['Proponente'] ?></td>
            </tr>
            <tr>
                <td>&Aacute;rea: <?= $this->arrValue['enquadramentoProjeto']['Area'] ?></td>
                <td colspan="3">Segmento: <?= $this->arrValue['enquadramentoProjeto']['Segmento'] ?></td>
            </tr>
            <tr>
                <td>UF: <?= $this->arrValue['enquadramentoProjeto']['UfProjeto'] ?></td>
                <td>Per&iacute;odo de execu&ccedil;&atilde;o: <?= reset(explode(' ', Data::dataBrasileira($this->arrValue['enquadramentoProjeto']['DtInicioExecucao']))) ?>
                    &agrave; <?= reset(explode(' ', Data::dataBrasileira($this->arrValue['enquadramentoProjeto']['DtFimExecucao']))) ?></td>
                <td>Enquadramento: <?= $this->arrValue['enquadramentoProjeto']['Enquadramento'] ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>Resumo do Projeto</b></div>
    <div class="collapsible-body">
        <?= nl2br($this->arrValue['enquadramentoProjeto']['ResumoProjeto']) ?>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>Memoria de C&aacute;lculo</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <tbody>
            <tr>
                <td colspan="2">Proponente</td>
                <td colspan="2">Homologado</td>
            </tr>
            <tr>
                <td>Vl.Solicitado</td>
                <td class="right-align"><?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['VlSolicitado']) ?></td>
                <td>Custo do Projeto</td>
                <td class="right-align"><?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['CustoProjeto']) ?></td>
            </tr>
            <tr>
                <td>Vl.Outras Fontes</td>
                <td class="right-align"> <?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['VlOutrasFontes']) ?></td>
                <td>Vl.Outras Fontes</td>
                <td class="right-align"> <?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['VlOutrasFontesAprovado']) ?></td>
            </tr>
            <tr>
                <td>Vl.Projeto</td>
                <td class="right-align"><?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['VlProjeto']) ?></td>
                <td>Custo Total</td>
                <td class="right-align"><?= Mascara::addMaskMoeda($this->arrValue['enquadramentoProjeto']['CustoTotal']) ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>Avalia&ccedil;&atilde;o T&eacute;cnica</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <tbody>
            <tr>
                <td width="20%">Posicionamento T&eacute;cnico</td>
                <td><?php if (!is_null($this->arrValue['parecer']['ParecerFavoravel'])) echo ($this->arrValue['parecer']['ParecerFavoravel'] == 1)? 'Desfavor&aacute;vel' : 'Favor&aacute;vel' ?></td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= nl2br($this->arrValue['parecer']['ResumoParecer']) ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>A&ccedil;&otilde;es Relevantes Para o Sucesso do Projeto</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <?= nl2br($this->arrValue['acaoProjeto']['dsAcaoAlcanceProduto']) ?>
        </table>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>Aprecia&ccedil;&atilde;o do Comission&aacute;rio Relator</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <tbody>
            <tr>
                <td width="30%">Posicionamento do Comiss&aacute;rio</td>
                <td><?php if (!is_null($this->arrValue['aparicaoComissario']['ParecerFavoravel'])) echo ($this->arrValue['aparicaoComissario']['ParecerFavoravel'] == 1)? 'Desfavor&aacute;vel' : 'Favor&aacute;vel' ?></td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= nl2br($this->arrValue['aparicaoComissario']['ResumoParecer']) ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</li>
<li>
    <div class="collapsible-header <?= (isset($this->booShowAll) && $this->booShowAll === true)? 'active' : '' ?>"><b>Parecer de Homologa&ccedil;&atilde;o</b></div>
    <div class="collapsible-body">
        <table class="responsive-table bordered-all" style="width: 100%;">
            <tbody>
            <tr>
                <td width="20%">Decis&atilde;o</td>
                <td><?php if (!is_null($this->arrValue['parecerHomologacao']['stDecisao'])) echo ($this->arrValue['parecerHomologacao']['stDecisao'] == 1)? 'Desfavor&aacute;vel' : 'Favor&aacute;vel' ?></td>
            </tr>
            <tr>
                <td colspan="2">
                    <?= $this->arrValue['parecerHomologacao']['dsHomologacao'] ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</li>
