<?php
/** 
 * Menu de abas
 * @author Emanuel Sampaio <emanuelonline@gmail.com>
 * @since 29/03/2010
 * @version 1.0
 * @copyright © 2010 Politec - Todos os direitos reservados.
 * @package application
 * @subpackage application.views.scripts.index
 * @link http://www.politec.com.br
 */
?>

<!-- ========== MENU ========== -->
<ul id="menu">
	<li><a href="#" id="menuAnalise">Aguardando Análise</a></li>
	<li><a href="#" id="menuResposta">Aguardando Resposta de Diligência</a></li>
	<li><a href="#" id="menuDiligencia">Diligência Respondida</a></li>
</ul>
