export const getReadequacoesProponente = state => state.readequacoesProponente;
export const getReadequacoesAnalise = state => state.readequacoesAnalise;
export const getReadequacoesFinalizadas = state => state.readequacoesFinalizadas;
export const getReadequacao = state => state.readequacao;
export const getCampoAtual = state => state.campoAtual;
export const getTiposDisponiveis = state => state.tiposDisponiveis;
export const getDocumentoReadequacao = state => state.readequacao.documento;
export const saldoAplicacao = state => state.saldoAplicacao;
export const saldoAplicacaoDisponivelEdicaoItem = state => state.readequacao.saldoAplicacaoDisponivelEdicaoItem;
