export const SET_READEQUACAO = 'SET_READEQUACAO';
export const UPDATE_READEQUACAO = 'UPDATE_READEQUACAO';
export const UPDATE_READEQUACAO_DS_SOLICITACAO = 'UPDATE_READEQUACAO_DS_SOLICITACAO';
export const VERIFICAR_DISPONIVEL_READEQUACAO_PLANILHA = 'VERIFICAR_DISPONIVEL_READEQUACAO_PLANILHA';
