export const GET_READEQUACOES = 'GET_READEQUACOES';
export const SET_READEQUACAO = 'SET_READEQUACAO';
export const UPDATE_READEQUACAO = 'UPDATE_READEQUACAO';
export const EXCLUIR_READEQUACAO = 'EXCLUIR_READEQUACAO';
export const ADICIONAR_DOCUMENTO = 'ADICIONAR_DOCUMENTO';
export const EXCLUIR_DOCUMENTO = 'EXCLUIR_DOCUMENTO';
export const BUSCA_READEQUACAO_PRONAC_TIPO = 'BUSCA_READEQUACAO_PRONAC_TIPO';
export const UPDATE_READEQUACAO_DS_SOLICITACAO = 'UPDATE_READEQUACAO_DS_SOLICITACAO';
export const UPDATE_READEQUACAO_SALDO_APLICACAO_DS_SOLICITACAO = 'UPDATE_READEQUACAO_SALDO_APLICACAO_DS_SOLICITACAO';
export const OBTER_DISPONIVEL_EDICAO_ITEM_SALDO_APLICACAO = 'OBTER_DISPONIVEL_EDICAO_ITEM_SALDO_APLICACAO';

