<?php
/**
 * Monta o XML dos ddds
 * @author Equipe RUP - Politec
 * @since 29/03/2010
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.ddd
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

$gmtDate = gmdate("D, d M Y H:i:s");
header("Expires: {$gmtDate} GMT");
header("Last-Modified: {$gmtDate} GMT");
header("Cache-Control: no-cache, must-revalidate");
header("Pragma: no-cache");
header("Content-Type: text/html; charset=ISO-8859-1", true);

$xml = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
$xml.= "<ddds>\n";

foreach ($this->ddds as $ddd)
{
	$xml.= "<ddd>\n";
	$xml.= "<codigo>".$ddd->id."</codigo>\n";
	$xml.= "<descricao>".$ddd->descricao."</descricao>\n";
	$xml.= "</ddd>\n";
}

$xml.= "</ddds>\n";
Header("Content-type: application/xml; charset=iso-8859-1");

echo $xml;
?>