<script type="text/javascript">
    $(document).ready(function(){
        $('#conteudoXLS').val($('#conteudoImprimivel').html());
        $('#formGerarXls').submit();
    });
</script>
<form method="POST" id="formGerarXls" name="formGerarXls" action="<?php echo $this->url(array('controller' => 'operacional', 'action' => ($this->tipo == 'xls') ? 'gerar-xls' : 'html2-pdf')); ?>" style="display:none">
    <textarea name="html" id="conteudoXLS"></textarea>
</form>
<div class="conteudoImprimivel" id="conteudoImprimivel" style="display:none">
    <table class="tabela" width="100%">
        <tbody>
            <tr>
                <th valign="middle" align="center" bgcolor="#D0D0D0"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="3">Pe&ccedil;a de Divulga&ccedil;&atilde;o</a></th>
            </tr>
            <?php foreach($this->dados as $dado): ?>
            <tr>
                <td valign="middle" align="left"><?php echo $dado->Descricao?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


