<script type="text/javascript">
    $(document).ready(function(){
        $('#conteudoXLS').val($('#conteudoImprimivel').html());
        $('#formGerarXls').submit();
    });
</script>
<form method="POST" id="formGerarXls" name="formGerarXls" action="<?php echo $this->url(array('controller' => 'operacional', 'action' => ($this->tipo == 'xls') ? 'gerar-xls' : 'html2-pdf')); ?>" style="display:none">
    <textarea name="html" id="conteudoXLS"></textarea>
</form>
<div class="conteudoImprimivel" id="conteudoImprimivel" style="display:none">
    <table class="tabela" >
        <tbody>
            <tr>
                <th valign="middle" align="center" bgcolor="#D0D0D0"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="2">Segmento Cultural</a></th>
                <th valign="middle" align="left" bgcolor="#D0D0D0"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="3">&Oacute;rg&atilde;o</a></th>
                <th valign="middle" align="left" bgcolor="#D0D0D0"><a href="#resultadoConsulta" class="orderBy"  valorOrdenacao="4">Estado</a></th>
            </tr>
            <?php foreach ($this->dados as $dado): ?>
                <tr>
                    <td valign="middle" align="left"><?php echo $dado->Descricao ?></td>
                    <td valign="middle" align="left"><?php echo $this->orgaos[$dado->idOrgao]["SiglaOrgao"] ?></td>
                    <td valign="middle" align="left"><?php echo ($dado->stEstado == 1) ? "Ativado" : "Desativado" ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


