<script type="text/javascript">
    $(document).ready(function(){
        $('#btn_salvar').click(function(){
            var preenchimento = true,
                campoRadioMarcado = false;
            $('.obrigatorio').each(function(){
                if($.trim($(this).val()) == '')
                    preenchimento = false;
            });

            $('input:radio').each(function(){
                if($(this).attr('checked'))
                    campoRadioMarcado = true;
            });

            if(!preenchimento || !campoRadioMarcado) {
                $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Favor preencher os dados obrigat&oacute;rios!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
//                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            } else {
                $('#formCadastro').submit();
            }
        });
    });
</script>

<?php require_once "scripts/comprovarexecucaofisica/inc/menu-relatorio-final.php"; ?>
<div id="camposObrigatorios" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Consultar dados do Projeto">Consultar dados do Projeto</a></li>
        <li class="second">Comprovar Realização do Objeto</li>
        <li class="last">Aceite de Obra</li>
    </ul>
</div>


<div id="titulo">
    <div>Aceite de Obra <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <form id="formCadastro" action="<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'cadastrar-aceite-obra'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" method="post" enctype="multipart/form-data">
        <table class="tabela">
            <tr align="center">
                <th>Termo de Aceite da Obra</th>
            </tr>
            <tr>
                <td class="destacar bold">O projeto prevê construção, reforma, restauro, criação de obras esculturais ou similares? <span style="color: red;">*</span></td>
            </tr>
            <tr>
                <td>
                    <span style="padding-right: 20px;">Sim <input type="radio" name="construcaoCriacaoRestauro" value="1" <?php echo (!empty($this->DadosRelatorio) && isset($this->DadosRelatorio->stConstrucaoCriacaoRestauro) && $this->DadosRelatorio->stConstrucaoCriacaoRestauro == 1)?'checked="checked"':''; ?>></span>
                    <span>Não <input type="radio" name="construcaoCriacaoRestauro" value="0" <?php echo (!empty($this->DadosRelatorio) && isset($this->DadosRelatorio->stConstrucaoCriacaoRestauro) && $this->DadosRelatorio->stConstrucaoCriacaoRestauro == 0)?'checked="checked"':''; ?>></span>
                </td>
            </tr>
            <tr>
                <td class="destacar bold">Descrição do Termo <span style="color: red;">*</span></td>
            </tr>
            <tr>
                <td>
                    <textarea name="descricaoTermoAceite" id="descricaoTermoAceite" cols="" rows="7" style="width: 99%;" class="textarea_simples obrigatorio"><?php echo isset($this->DadosRelatorio->dsDescricaoTermoAceite) ? $this->DadosRelatorio->dsDescricaoTermoAceite : ''; ?></textarea>
                    <br clear="all" /><span style="color: #FF9999; font-size: 11px;">Limite máximo de 2000 caracteres</span>
                </td>
            </tr>
            <tr>
                <td class="destacar bold">Upload do Termo <span style="color: red;">*</span></td>
            </tr>
            <tr>
                <td>
                    <input type="file" id="arquivo" name="arquivo" class="obrigatorio">
                    <?php if(!empty($this->DadosRelatorio)){ ?>
                    <input type="hidden" id="idArquivo" name="idArquivo" value="<?php echo $this->DadosRelatorio->idArquivo; ?>">
                    <?php } ?>
                </td>
            </tr>
        </table>
    </form>

    <?php if(!empty($this->DadosRelatorio)){ ?>
    <table class="tabela">
        <tr>
            <td class="destacar bold" style="width: 25%">Arquivo</td>
            <td class="destacar bold" style="width: 25%">Tipo do Arquivo</td>
            <td class="destacar bold" style="width: 25%">Extensão do Arquivo</td>
            <td class="destacar bold" style="width: 25%">Data de Envio</td>
        </tr>
        <tr>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $this->DadosRelatorio->idArquivo; ?>"><?php echo $this->DadosRelatorio->nmArquivo; ?></a></td>
            <td>Aceite de Obra</td>
            <td><?php echo $this->DadosRelatorio->sgExtensao; ?></td>
            <td><?php echo Data::tratarDataZend($this->DadosRelatorio->dtEnvio, 'Brasileira', true); ?></td>
        </tr>
    </table>
    <?php } ?>

    <p align="center">
        <input type="button" class="btn_salvar" id="btn_salvar">
    </p>

    <br clear="all" />
</div>


<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
