<script type="text/javascript">
    $(document).ready(function(){
        $("input[name='qtBensDoados']").bind("keyup blur focus", function(e) {
            e.preventDefault();
            var expre = /[^0-9]/g;
            // REMOVE OS CARACTERES DA EXPRESSAO ACIMA
            if ($(this).val().match(expre))
                $(this).val($(this).val().replace(expre,''));
        });

        $('#btn_salvar_movel').click(function(){
            var preenchimento = false;
            $('.obrigatorioMovel').each(function(){
                $(this).css('border-color','#CCC');
                if($.trim($(this).val()) == ''){
                    preenchimento = true;
                    $(this).css('border-color','red');
                }
            });

            if(preenchimento) {
                camposObrigatorios();
            } else {
                $('#formBemMovel').submit();
            }
        });

        $('#btn_salvar_imovel').click(function(){
            var preenchimentoImovel = false;
            $('.obrigatorioImovel').each(function(){
                $(this).css('border-color','#CCC');
                if($.trim($(this).val()) == ''){
                    preenchimentoImovel = true;
                    $(this).css('border-color','red');
                }
            });

            if(preenchimentoImovel) {
                camposObrigatorios();
            } else {
                $('#formBemImovel').submit();
            }
        });

        $('.btn_excluir').click(function(){
            var id = $(this).attr('idBensDoados'),
                idDoacao = $(this).attr('idDoacao'),
                idAceite = $(this).attr('idAceite');
            $("#modalPerguntas").dialog("destroy");
            $("#modalPerguntas").html("Deseja realmente excluir este Bem Doado?");
            $("#modalPerguntas").dialog({
                resizable: false,
                title: 'Alerta!',
                width:330,
                height:160,
                modal: true,
                buttons : {
                    'Não' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $("#modalPerguntas").dialog('close');
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'excluir-bem-doado'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                            data: {
                                bensDoados: id,
                                doacao: idDoacao,
                                aceite: idAceite
                            },
                            success: function(data){
                                if(data.resposta){
                                    $("#alerta").dialog("destroy");
                                    $("#alerta").html('<br /><div align="center"><img src="<?php echo $this->baseUrl().'/public/img/ajax.gif'; ?>"></div>');
                                    $("#alerta").dialog({
                                        resizable: false,
                                        width:320,
                                        height:120,
                                        modal: true,
                                        title: 'Carregando..'
                                    });
                                    $('.ui-dialog-titlebar-close').remove();
                                    window.setTimeout('location.reload()', 1000);
                                } else {
                                    alertaModal("Não foi possível excluir o Bem Doado.");
                                }
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });

        $('#cnpjcpfMovel').focusout(function(){
            $('#nomeAgenteMovel').html('');
            $('#agenteMovel').val('');

            if($('#cnpjcpfMovel').val().length == 14 || $('#cnpjcpfMovel').val().length == 18){
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'buscar-agente'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                    data: {
                        cnpjcpf: $('#cnpjcpfMovel').val()
                    },
                    success: function(data){
                        if(data.resposta){
                            for ( i in data.conteudo){
                                $('#nomeAgenteMovel').html(data.conteudo[i].nmAgente);
                                $('#agenteMovel').val(data.conteudo[i].idAgente);
                            }
                        } else {
                            $('html').css('overflow', 'hidden');
                            $("body").append("<div id='divDinamicaAgentes'></div>");
                            $("#divDinamicaAgentes").html("");
                            $('#divDinamicaAgentes').html("<br><br><center>Carregando dados...</center>");
                            $.ajax({
                                url : '<?php echo $this->url(array('controller' => 'agentes', 'action' => 'incluirbeneficiario')); ?>',
                                data : {
                                    cpf : data.CNPJCPF,
                                    caminho: "",
                                    modal : "s"
                                },
                                success: function(data){
                                    if (data.error) {
                                        $('#divDinamicaAgentes').html(data.msg);
                                    } else {
                                        $('#divDinamicaAgentes').html(data);
                                    }
                                },
                                complete: function(){
                                    $("#resultadoFinalizar").html("");
                                },
                                type : 'post'
                            });

                            $("#divDinamicaAgentes").dialog({
                                resizable: true,
                                width:$(window).width() - 100,
                                height:$(window).height() - 100,
                                modal: true,
                                autoOpen:true,
                                draggable:false,
                                title: 'Cadastrar Beneficiário',
                                buttons: {
                                    'Fechar': function() {
                                        $("#divDinamicaAgentes").remove();
                                        $(this).dialog('close');
                                        $('html').css('overflow', 'auto');
                                        outroAgente();
                                    }
                                }
                            });
                        }
                    },
                    dataType : 'json'
                });

            } else {
                $('#nomeAgenteMovel').html('');
                $('#agenteMovel').val('');
            }
        });

        $('#cnpjcpfImovel').focusout(function(){
            $('#nomeAgenteImovel').html('');
            $('#agenteImovel').val('');

            if($('#cnpjcpfImovel').val().length == 14 || $('#cnpjcpfImovel').val().length == 18){
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'buscar-agente'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                    data: {
                        cnpjcpf: $('#cnpjcpfImovel').val()
                    },
                    success: function(data){
                        if(data.resposta){
                            for ( i in data.conteudo){
                                $('#nomeAgenteImovel').html(data.conteudo[i].nmAgente);
                                $('#agenteImovel').val(data.conteudo[i].idAgente);
                            }
                        } else {
                            $('html').css('overflow', 'hidden');
                            $("body").append("<div id='divDinamicaAgentes'></div>");
                            $("#divDinamicaAgentes").html("");
                            $('#divDinamicaAgentes').html("<br><br><center>Carregando dados...</center>");
                            $.ajax({
                                url : '<?php echo $this->url(array('controller' => 'agentes', 'action' => 'incluirbeneficiario')); ?>',
                                data : {
                                    cpf : data.CNPJCPF,
                                    caminho: "",
                                    modal : "s"
                                },
                                success: function(data){
                                    if (data.error) {
                                        $('#divDinamicaAgentes').html(data.msg);
                                    } else {
                                        $('#divDinamicaAgentes').html(data);
                                    }
                                },
                                complete: function(){
                                    $("#resultadoFinalizar").html("");
                                },
                                type : 'post'
                            });

                            $("#divDinamicaAgentes").dialog({
                                resizable: true,
                                width:$(window).width() - 100,
                                height:$(window).height() - 100,
                                modal: true,
                                autoOpen:true,
                                draggable:false,
                                title: 'Cadastrar Beneficiário',
                                buttons: {
                                    'Fechar': function() {
                                        $("#divDinamicaAgentes").remove();
                                        $(this).dialog('close');
                                        $('html').css('overflow', 'auto');
                                        outroAgenteImovel();
                                    }
                                }
                            });
                        }
                    },
                    dataType : 'json'
                });

            } else {
                $('#nomeAgenteImovel').html('');
                $('#agenteImovel').val('');
            }
        });

        $('.visualizarObs').click(function(){
            var texto = $(this).children().attr('dsObservacao');
            $("#camposObrigatorios").dialog("destroy");
            $("#camposObrigatorios").html(texto);
            $("#camposObrigatorios").dialog({
                resizable: true,
                title: 'Observações',
                width:350,
                modal: true,
                buttons : {
                    'OK' : function(){
                        $(this).dialog('close');
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
            return false;
        });

    });

    function outroAgente(){
        $("#divPerguntaCadastro").dialog('close');
        $("#divPerguntaCadastro").html('Deseja utilizar este novo agente no cadastro?');
        $("#divPerguntaCadastro").dialog('open');
        $("#divPerguntaCadastro").dialog({
            resizable: false,
            width: 320,
            height: 180,
            modal: true,
            draggable:false,
            title: 'Alerta!',
            buttons: {
                'Não': function(){
                    $("#agenteMovel").val('');
                    $("#nomeAgenteMovel").html('');
                    $('#cnpjcpfMovel').val('');
                    $('#cnpjcpfMovel').focus();
                    $("#divPerguntaCadastro").dialog('close');
                },
                'Sim': function() {
                    $("#divPerguntaCadastro").dialog('close');
                    $('#cnpjcpfMovel').focusout();
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }

    function outroAgenteImovel(){
        $("#divPerguntaCadastro").dialog('close');
        $("#divPerguntaCadastro").html('Deseja utilizar este novo agente no cadastro?');
        $("#divPerguntaCadastro").dialog('open');
        $("#divPerguntaCadastro").dialog({
            resizable: false,
            width: 320,
            height: 180,
            modal: true,
            draggable:false,
            title: 'Alerta!',
            buttons: {
                'Não': function(){
                    $("#agenteImovel").val('');
                    $("#nomeAgenteImovel").html('');
                    $('#cnpjcpfImovel').val('');
                    $('#cnpjcpfImovel').focus();
                    $("#divPerguntaCadastro").dialog('close');
                },
                'Sim': function() {
                    $("#divPerguntaCadastro").dialog('close');
                    $('#cnpjcpfImovel').focusout();
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }

    function camposObrigatorios(){
        $("#camposObrigatorios").dialog("destroy");
        $("#camposObrigatorios").html("Favor preencher os dados obrigat&oacute;rios!");
        $("#camposObrigatorios").dialog({
            resizable: false,
            title: 'Alerta!',
            width:320,
//            height:160,
            modal: true,
            buttons : {
                'OK' : function(){
                    $(this).dialog('close');
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }
</script>

<?php require_once "scripts/comprovarexecucaofisica/inc/menu-relatorio-final.php"; ?>
<div id="alerta" class="sumir"></div>
<div id="modalPerguntas" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>
<div id="divPerguntaCadastro" class="sumir"></div>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Consultar dados do Projeto">Consultar dados do Projeto</a></li>
        <li class="second">Comprovar Realização do Objeto</li>
        <li class="last">Bens Doados</li>
    </ul>
</div>


<div id="titulo">
    <div>Bens Doados <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <form id="formBemMovel" action="<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'cadastrar-bens-moveis'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" method="post" enctype="multipart/form-data">
        <table class="tabela">
            <tr align="center">
                <th colspan="2">Bens Móveis</th>
            </tr>
            <tr>
                <td class="destacar bold" width="200px" align="right">Itens Orçamentários<span style="color: red;">*</span></td>
                <td>
                    <select class="select_simples obrigatorioMovel" name="itemOrcamentario">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->DadosItens as $itens) { ?>
                        <option value="<?php echo $itens->idPlanilhaItem; ?>"><?php echo $itens->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Upload de documento de doação<span style="color: red;">*</span></td>
                <td><input type="file" class="obrigatorioMovel" name="documentoDoacao"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">Beneficiário que recebeu o bem ao final do projeto</td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">CPF/CNPJ<span style="color: red;">*</span></td>
                <td><input maxlength="18" onkeydown="mascaraCnpjCpf(this);" onkeypress="mascaraCnpjCpf(this);" onkeyup="mascaraCnpjCpf(this);" type="text" name="cnpjcpf" id="cnpjcpfMovel" class="input_simples obrigatorioMovel"></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Nome<span style="color: red;">*</span></td>
                <td>
                    <input type="hidden" class="input_simples obrigatorioMovel" name="agenteMovel" id="agenteMovel" />
                    <span id="nomeAgenteMovel" ></span>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Quantidade doada<span style="color: red;">*</span></td>
                <td><input type="text" class="input_simples obrigatorioMovel" name="qtBensDoados" maxlength="9" /></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Upload do aceite do bem<span style="color: red;">*</span></td>
                <td><input type="file" class="obrigatorioMovel" name="documentoAceite" /></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Observações</td>
                <td>
                    <textarea name="observacao" cols="" rows="7" style="width: 99%;" class="textarea_simples"></textarea>
                    <br clear="all" /><span style="color: #FF9999; font-size: 11px;">Limite máximo de 1000 caracteres</span>
                </td>
            </tr>
        </table>
    </form>

    <p align="center">
        <input type="button" class="btn_salvar" id="btn_salvar_movel">
    </p>

    <br clear="all" />

    <form id="formBemImovel" action="<?php echo $this->url(array('controller' => 'comprovarexecucaofisica', 'action' => 'cadastrar-bens-imoveis'), '', true); ?>?idpronac=<?php echo Seguranca::encrypt($this->idPronac); ?>" method="post" enctype="multipart/form-data">
        <table class="tabela">
            <tr align="center">
                <th colspan="2">Bens Imóveis</th>
            </tr>
            <tr>
                <td class="destacar bold" width="200px" align="right">Itens Orçamentários<span style="color: red;">*</span></td>
                <td>
                    <select class="select_simples obrigatorioImovel" name="itemOrcamentario">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->DadosItens as $itens) { ?>
                        <option value="<?php echo $itens->idPlanilhaItem; ?>"><?php echo $itens->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Upload de documento de doação<span style="color: red;">*</span></td>
                <td><input type="file" class="obrigatorioImovel" name="documentoDoacao"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">Beneficiário que recebeu o bem ao final do projeto</td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">CPF/CNPJ<span style="color: red;">*</span></td>
                <td><input maxlength="18" onkeydown="mascaraCnpjCpf(this);" onkeypress="mascaraCnpjCpf(this);" onkeyup="mascaraCnpjCpf(this);" type="text" name="cnpjcpf" id="cnpjcpfImovel" class="input_simples obrigatorioImovel"></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Nome<span style="color: red;">*</span></td>
                <td>
                    <input type="hidden" class="input_simples obrigatorioImovel" name="agenteImovel" id="agenteImovel" />
                    <span id="nomeAgenteImovel" ></span>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Quantidade doada<span style="color: red;">*</span></td>
                <td><input type="text" class="input_simples obrigatorioImovel" name="qtBensDoados" maxlength="9" /></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Upload do aceite do bem<span style="color: red;">*</span></td>
                <td><input type="file" class="obrigatorioImovel" name="documentoAceite" /></td>
            </tr>
            <tr>
                <td colspan="2" align="center">Favor informar nome do cartório, número do registro e de folha, especificando o imóvel também.</td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Observações</td>
                <td>
                    <textarea name="observacao" cols="" rows="7" style="width: 99%;" class="textarea_simples"></textarea>
                    <br clear="all" /><span style="color: #FF9999; font-size: 11px;">Limite máximo de 1000 caracteres</span>
                </td>
            </tr>
        </table>
    </form>

    <p align="center">
        <input type="button" class="btn_salvar" id="btn_salvar_imovel">
    </p>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <th colspan="9">Bens Móveis / Imóveis Doados</th>
        </tr>
        <?php if(count($this->BensCadastrados)>0) { ?>
        <tr align="center">
            <td class="destacar bold">Tipo do Bem</td>
            <td class="destacar bold">Item Orçamentário</td>
            <td class="destacar bold">CNPJ/CPF</td>
            <td class="destacar bold">Nome</td>
            <td class="destacar bold">Arquivo Doação</td>
            <td class="destacar bold">Arquivo Aceite</td>
            <td class="destacar bold">Quantidade</td>
            <td class="destacar bold">Observação</td>
            <td class="destacar bold">Ação</td>
        </tr>
        <?php foreach ($this->BensCadastrados as $bens) { ?>
        <tr>
            <td><?php echo ($bens->tpBem == 'M') ? 'Móvel' : 'Imóvel'; ?></td>
            <td><?php echo $bens->ItemOrcamentario; ?></td>
            <td align="center"><?php echo (strlen($bens->CNPJCPF) == 11) ? Mascara::addMaskCPF($bens->CNPJCPF) : Mascara::addMaskCNPJ($bens->CNPJCPF); ?></td>
            <td><?php echo $bens->NomeAgente; ?></td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $bens->idArquivoDoacao; ?>"><?php echo $bens->nmArquivoDoacao; ?></a></td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $bens->idArquivoAceite; ?>"><?php echo $bens->nmArquivoAceite; ?></a></td>
            <td><?php echo $bens->qtBensDoados; ?></td>
            <td align="center">
                <a href="#" class="visualizarObs"><img src="<?php echo $this->baseUrl(); ?>/public/img/table_multiple.png" dsObservacao="<?php echo $bens->dsObservacao; ?>" /></a>
            </td>
            <td align="center">
                <input type="button" value=" " class="btn_excluir" idBensDoados="<?php echo $bens->idBensDoados; ?>" idDoacao="<?php echo $bens->idArquivoDoacao; ?>" idAceite="<?php echo $bens->idArquivoAceite; ?>" />
            </td>
        </tr>
        <?php } ?>
        <?php } else { ?>
        <tr>
            <td colspan="9" align="center">Nenhum registro encontrado.</td>
        </tr>
        <?php } ?>
    </table>

    <br clear="all" />
</div>


<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
