<?php $frmplanoHref = $this->url(array('module' => 'proposta' , 'controller' => 'plano-distribuicao', 'action' => 'frm-plano-distribuicao')).'?idPreProjeto='.$_GET['idPreProjeto']; ?>

<div class="container-fluid">
    <div class="row">
        <?php echo $this->partial("inc/menu.phtml", $this); ?>
        <div class="content col s10 m12 l10 planilha-produtos">
            <?php if( $this->localRealizacao): ?>
                <div id="confirm" title="Confirma&ccedil;&atilde;o" style="display: none">Tem certeza que deseja excluir o registro?</div>
                <?php
                gerarBreadCrumb(array(
                    $this->layout['listagem'],
                    array('Plano de Distribui&ccedil;&atilde;o' => '')
                )); ?>

                <div id="titulo">
                    <div>Plano de Distribui&ccedil;&atilde;o</div>
                </div>

                <div id="conteudo">
                    <div id="div_form"></div>

                        <?php //var_dump($this->planosDistribuicao) ?>
                        <?php $totalExemplares=0; $totalReceita=0; ?>
                        <?php if(!empty($this->planosDistribuicao)){ ?>
                            <?php foreach($this->planosDistribuicao as $planoDistribuicao){ ?>
                                <?php
                                $totalExemplares += $planoDistribuicao->QtdeProduzida;
                                $receita = ($planoDistribuicao->QtdeVendaNormal*$planoDistribuicao->PrecoUnitarioNormal)+($planoDistribuicao->QtdeVendaPromocional*$planoDistribuicao->PrecoUnitarioPromocional);
                                $totalReceita += $receita;
                                ?>
                    <table class="tabela">
                        <tr class="titulo_tabela">
                            <th width="25%">Nome do Evento / Produto</th>
                            <th width="25%">&Aacute;rea</th>
                            <th width="15%">Segmento</th>
                            <th width="15%">Principal</th>
                            <th width="20%">A&ccedil;&otilde;es</th>
                        </tr>
                            <tr class="fundo">
                                <td class="centro"><?php echo $planoDistribuicao->Produto; ?></td>
                                <td class="centro"><?php echo $planoDistribuicao->DescricaoArea; ?></td>
                                <td align="right"><?php echo $planoDistribuicao->DescricaoSegmento; ?></td>
                                <td align="right"><?php echo ($planoDistribuicao->stPrincipal == 0) ? 'N&atilde;o' : 'Sim'; ?></td>
                                <td class="centro" nowrap>
                                    <?php if ($this->isEditarProposta || ($this->isEditarProjeto && $planoDistribuicao->stPrincipal != 1)) : ?>
                                        <input type="button" class="btn_editar" id="btn_editar" onclick="editar(<?php echo $planoDistribuicao->idPlanoDistribuicao; ?>)"/>&nbsp;
                                        <input type="button" class="btn_exclusao" id="btn_excluir" onclick="confirma('<?php echo $this->urlApagar; ?>&idPlanoDistribuicao=<?php echo $planoDistribuicao['idPlanoDistribuicao']; ?>')"/></td>
                                    <?php endif; ?>
                            </tr>
                            <tr class="fundo">
                                <td colspan="5">
                                    <table class="tabela">
                                        <tr>
                                            <th class="centro">Quantidade de Exemplar / Ingresso</th>
                                            <th class="centro">
                                                Divulga&ccedil;&atilde;o
                                            </th>
                                            <th class="centro">
                                                Patrocinador
                                            </th>
                                            <th class="centro">
                                                Popula&atilde;o
                                            </th>
                                            <th class="centro">
                                                Quantidade  de Inteira
                                            </th>
                                            <th class="centro">
                                                Quantidade de Meia Entrada
                                            </th>
                                            <th class="centro">
                                                Pre&ccedil;o Unit&aacute;rio do Ingresso
                                            </th>
                                            <th class="centro">
                                                Receita da Inteira
                                            </th>
                                            <th class="centro">
                                                Valor da Meia Entrada
                                            </th>
                                            <th class="centro">
                                                Quantidade  de Inteira
                                            </th>
                                            <th class="centro">
                                                Quantidade de Meia Entrada
                                            </th>
                                            <th class="centro">
                                                Pre&ccedil;o em m&eacute;dia simples
                                            </th>
                                            <th class="centro">
                                                Receita da Inteira
                                            </th>
                                            <th class="centro">
                                                Receita da Meia Entrada
                                            </th>
                                            <th class="centro">
                                                Receita Prevista
                                            </th>
                                        </tr>
                                        <tr class="fundo">
                                            <td class="centro"><?php echo $planoDistribuicao->QtdeProduzida ; ?></td>
                                            <td><?php echo $planoDistribuicao->QtdeProponente	?></th>
                                            <td><?php echo $planoDistribuicao->QtdePatrocinador	?></th>
                                            <td><?php echo $planoDistribuicao->QtdeOutros	?></th>
                                            <td><?php echo $planoDistribuicao->QtdeVendaPopularNormal?></th>
                                            <td><?php echo $planoDistribuicao->QtdeVendaPopularPromocional?></th>
                                            <td><?php echo $planoDistribuicao->vlUnitarioPopularNormal?>	</th>
                                            <td><?php echo $planoDistribuicao->ReceitaPopularNormal	?></th>
                                            <td><?php echo $planoDistribuicao->ReceitaPopularPromocional	?></th>
                                            <td><?php echo $planoDistribuicao->QtdeVendaNormal	?></th>
                                            <td><?php echo $planoDistribuicao->QtdeVendaPromocional	?></th>
                                            <td><?php echo $planoDistribuicao->vlUnitarioNormal	?></th>
                                            <td><?php echo $planoDistribuicao->PrecoUnitarioNormal	?></th>
                                            <td><?php echo $planoDistribuicao->PrecoUnitarioPromocional?></th>
                                            <td><?php echo $planoDistribuicao->PrecoUnitarioPromocional?></th>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <?php } ?>
                        <?php } ?>
                    </table>
                <div id="miolo"> <!-- ========== INICIO MIOLO IDENTIFICACAO ========== -->
                    <table class="tabela" style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td align="center">
                                <button type="button" class="btn thite-text" id="btn_novo">Novo</button>
                                <?php if(!empty($this->planosDistribuicao->toArray())): ?>
                                    <a
                                        href="/proposta/plano-distribuicao/detalhar-plano-distribuicao/idPreProjeto/<?php echo $this->idPreProjeto ?>"
                                        class="btn white-text" id="detalhar">Detalhar</a>
                                    <?php else: ?>
                                        <button disabled class="btn white-text" >Detalhar</button>
                                    <?php endif ?>
                            </td>
                        </tr>
                    </table>
                </div>
            <?php else: ?>
                <div class="row">
                    <div class="col s12">
                        <p>Preencher primeiro o <a href="<?php echo $this->url(array('module'=>'proposta', 'controller'=>'localderealizacao', 'action'=> 'index')) ?>">
                            local de realiza&ccedil;&atilde;o</a>
                         </p>
                    </div>
                </div>
            <?php endif; ?>

            </div><!-- ========== FIM CONTEUDO ========== -->

            <!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
            <div id="rodapeConteudo"><span></span></div>
            <!-- ========== FIM RODAPE DO CONTEUDO ========== -->
            <br clear="all" />
        </div>
    </div>
</div>

<script language="javascript" type="text/javascript">

    $(document).ready(function(){
        <?php if (!$this->isEditavel) : ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>
    });

    function confirma(obj){
        $("#confirm").dialog("destroy");
        $("#confirm").dialog({
            width:350,
            height:150,
            EscClose:false,
            modal:true,
            buttons: {
                'Cancelar':function(){
                    $(this).dialog('close'); // fecha a modal
                },
                'Confirmar':function(){
                    location.href=obj;
                }
            }
        });
        $("#confirm").dialog('open');
    }

    function requisicaoAjaxObj(){
        var ajaxObj={
            pagina          :   '',
            parametros      :   {},
            type            :   'post',
            dataType        :   '',
            resposta        :   '#conteudo',
            async           :   true,
            funcaoRetorno   :   function (resposta){
                $(this.resposta).html(resposta);
            },
            executar        :   function(dados){
                this.refineParametrosObj(dados);
                var esteObj = this;
                if(this.resposta != undefined && this.resposta != '')
                    $(this.resposta).html('<img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" alt="carregando"><br/><br/>Carregando...<br>Por Favor, aguarde!!');
                $.ajax({
                    type      : esteObj.type,
                    url       : esteObj.pagina,
                    data      : esteObj.parametros,
                    async     : esteObj.async,
                    success   : function(resp){
                        esteObj.funcaoRetorno(resp);
                    }
                    ,dataType  : esteObj.dataType
                });
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){

                        this[j]=data[j];
                    }
            }
        }
        return ajaxObj;
    }

    function janelaObj(dados){
        var divConteudo = $('<div></div>')
            .attr('title',dados.title)
            .appendTo('body');
        var novaJanela = {
            divConteudo : divConteudo,
            removerBtFechar: true,
            parametros : {autoOpen: false},
            iniciarJanela : function(dados){
                this.refineParametrosObj(dados);
                var esse = this.divConteudo;
                this.parametros.close = function (){
                    esse.html('');
                }
                this.divConteudo.dialog(this.parametros);
            },
            abrirJanela:function(){
                this.divConteudo.dialog('open');
                if(this.removerBtFechar)
                    $('.ui-dialog-titlebar-close').remove();
            },
            fecharJanela:function(){
                this.divConteudo.dialog('close');
                this.divConteudo.remove();
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){
                        this[j]=data[j];
                    }
            }
        }
        novaJanela.iniciarJanela(dados);
        return novaJanela;
    }

    $(function(){
        $('#btn_novo').click(function(){
            $("#div_form").html('<br><center><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center>');
            jqAjaxLinkSemLoading("<?php echo $frmplanoHref; ?>", "", "div_form");
        });
    });

    function editar(idPlanoDistribuicao){
        var url = '<?php echo $this->url(array('controller' => 'plano-distribuicao', 'action' => 'frm-plano-distribuicao')).'?idPreProjeto='.$_GET['idPreProjeto'].'&idPlanoDistribuicao=';?>'+idPlanoDistribuicao;
        $("#div_form").html('<br><center><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center>');
        jqAjaxLinkSemLoading(url, "", "div_form");
    }
</script>
