<?php
/**
 * Planilha Orçamento
 * @author Equipe RUP - Politec
 * @since 07/06/2010
 * @version 1.0
 * @package application
 * @subpackage application.controller.realizaranaliseprojeto
 * @link http://www.cultura.gov.br
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 */
	
?>
	
	<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
	<div id="breadcrumb">
		<ul>
			<li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para Início">Início</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'solicitarrecursodecisao', 'action' => 'planilhaorcamento')); ?>" title="Ir para Análise do Membro da Comissão">Análise do Membro da Comissão</a></li>
			<li class="last">Planilha de Orçamento Aprovada</li>
		</ul>
	</div>
	<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
	
	
	
	<!-- ========== INÍCIO TÍTULO ========== -->
	<div id="titulo">
		<div>Planilha de Orçamento Aprovada <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
	</div>
	<!-- ========== FIM TÍTULO ========== -->
	
	
	
	<!-- ========== INÍCIO CONTEÚDO ========== -->
	<div id="conteudo">
	
	
	
	
	
	<script language="javascript">  

	function verifica()    
	{         
		if (formu.justificativa.value=="")              
		alert("Por favor, Digite a Justificativa!");         
	return false;               

	} 
	
	</script>
	
	
	
		<!-- ========== INÍCIO PRONAC ========== -->
		
		
				
		
		<table class="tabela">
	
			<?php foreach ($this->pronac as $p) : ?>
			<tr>
				<th>
					<p>PRONAC: <?php echo $p->pronac; ?>- <?php echo $p->NomeProjeto; ?></p>
				</th>
			</tr>
			<?php endforeach; ?>
	
		</table>
		<!-- ========== FIM PRONAC ========== -->
		

	
	
	<form name="form" id="form" action="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'recurso')); ?>?idPronac=<?php echo $p->IdPRONAC; ?>" method="post">

								
		<table class="tabela">
	

			<!-- ========== INÍCIO BUSCA POR PRODUTO ========== -->
			<?php
			$item = 1; // contador para os itens
			$contadorProd  = 0;
			$contadorEtapa = 0;
			$contadorUF    = 0;
			?>
			<?php foreach ($this->buscarProd as $buscarProd) : ?>
			<tr class="IFF linha">
				<td colspan="12">
					<strong>
						<div id="icn_maisIFF_PRODUTO<?php echo $contadorProd; ?>" class="sumir"><a href="#icn_menosIFF_PRODUTO<?php echo $contadorProd; ?>" onclick="$('#icn_menosIFF_PRODUTO<?php echo $contadorProd; ?>, .IFF_PRODUTO<?php echo $contadorProd; ?>').show(); $('#icn_maisIFF_PRODUTO<?php echo $contadorProd; ?>').hide();" onkeypress=" "><div class="icn_mais" style="width:98%; margin-left:2%;"><span class="green del_link"><?php echo $buscarProd->Produto; ?></span></div></a></div>
						<div id="icn_menosIFF_PRODUTO<?php echo $contadorProd; ?>"><a href="#icn_maisIFF_PRODUTO<?php echo $contadorProd; ?>" onclick="$('#icn_maisIFF_PRODUTO<?php echo $contadorProd; ?>').show(); $('#icn_menosIFF_PRODUTO<?php echo $contadorProd; ?>, .IFF_PRODUTO<?php echo $contadorProd; ?>').hide();" onkeypress=" "><div class="icn_menos" style="width:98%; margin-left:2%;"><span class="green del_link"><?php echo $buscarProd->Produto; ?></span></div></a></div>
					</strong>
				</td>
			</tr>
	
	
	
				<!-- ========== INÍCIO BUSCA POR ETAPA ========== -->
				<?php
				foreach (RecursoDAO::analiseDeCustosBuscarEtapa($buscarProd->IdPRONAC, $buscarProd->idProduto, true) as $buscarEtapa) :
				?>
	
				<tr class="IFF IFF_PRODUTO<?php echo $contadorProd; ?>">
					<td colspan="12">
						<strong style="margin-left:2%;">
							<?php foreach ($this->planilhaEtapa as $etapa) : // Nome ou Descrição da Etapa ?>
								<?php if ($buscarEtapa->idEtapa == $etapa->idPlanilhaEtapa) : ?>
									<div id="icn_maisIFF_ETAPA<?php echo $contadorEtapa; ?>" class="sumir"><a href="#icn_menosIFF_ETAPA<?php echo $contadorEtapa; ?>" onclick="$('#icn_menosIFF_ETAPA<?php echo $contadorEtapa; ?>, .IFF_ETAPA<?php echo $contadorEtapa; ?>').show(); $('#icn_maisIFF_ETAPA<?php echo $contadorEtapa; ?>').hide();" onkeypress=" "><div class="icn_mais" style="width:90%; margin-left:4%;"><span class="orange del_link"><?php echo $buscarEtapa->idEtapa; ?> - <?php echo $etapa->Descricao; ?></span></div></a></div>
									<div id="icn_menosIFF_ETAPA<?php echo $contadorEtapa; ?>"><a href="#icn_maisIFF_ETAPA<?php echo $contadorEtapa; ?>" onclick="$('#icn_maisIFF_ETAPA<?php echo $contadorEtapa; ?>').show(); $('#icn_menosIFF_ETAPA<?php echo $contadorEtapa; ?>, .IFF_ETAPA<?php echo $contadorEtapa; ?>').hide();" onkeypress=" "><div class="icn_menos" style="width:90%; margin-left:4%;"><span class="orange del_link"><?php echo $buscarEtapa->idEtapa; ?> - <?php echo $etapa->Descricao; ?></span></div></a></div>
								<?php endif; ?>
							<?php endforeach; ?>
						</strong>
					</td>
				</tr>
	
	
	
					<!-- ========== INÍCIO BUSCA POR UF ========== -->
					<?php
					//foreach (RealizarAnaliseProjetoDAO::analiseDeCustosBuscarUF($buscarEtapa->IdPRONAC, $buscarEtapa->idProduto, $buscarEtapa->idEtapa, true) as $buscarUF) :
					?>
	
	
	
						<!-- ========== INÍCIO ÍTENS ========== -->
					    <tr class="IFF IFF_PRODUTO<?php echo $contadorProd; ?> IFF_ETAPA<?php echo $contadorEtapa; ?> IFF_UF<?php echo $contadorUF; ?>">
						<th>Nome do Item</th>
					        <th width="10%">Valor Solicitado/th>
					        <th width="10%">Valor Aprovado</th>
					        <th width="49%">Justificativa Proponente</th>
					        <th width="6%">Justificativa Técnica</th>
					    </tr>
	
						<?php
						// caso tenha projetos
						$totalItens = 0;
						if (count(RecursoDAO::analiseDeConta($buscarEtapa->IdPRONAC, $buscarEtapa->idProduto, $buscarEtapa->idEtapa, null, null, true)) > 0)
						{
							foreach (RecursoDAO::analiseDeConta($buscarEtapa->IdPRONAC, $buscarEtapa->idProduto, $buscarEtapa->idEtapa, null, null, true) as $resposta) :
								$i = $resposta->idPlanilhaAprovacao; // criará id únido
						?>
	
					    <tr onmouseover="over_tr(this);" onfocus="over_tr(this);" onmouseout="out_tr(this);" onblur="out_tr(this);" onclick="click_tr(this);" onkeypress="click_tr(this);" 
					    	class="IFF IFF_PRODUTO<?php echo $contadorProd; ?> IFF_ETAPA<?php echo $contadorEtapa; ?> IFF_UF<?php echo $contadorUF; ?> 
					    		<?php
					    		if ($i == $_GET['Ativo'])
					    		{
					    			echo "fundo_linha4";
					    		}
					    		else
					    		{
					    			echo $this->corLinha($totalItens);
					    		}
					      		if ($resposta->VlSugeridoParecerista != $resposta->VlSugeridoConselheiro)
					    		{
					    			echo " red";
					    		}
					    		$totalItens--;
					    		?>">
					        <td>
	
	
	
								<a onclick="modal(<?php echo $i; ?>)"><?php echo $this->escape($resposta->Item); ?></a> 
					        </td>
					        
					
	
					      
					        <td class="direita<?php if ($resposta->VlSugeridoParecerista == $resposta->VlSugeridoConselheiro) echo " blue"; ?>"><?php echo $this->formatarReal($this->escape($resposta->VlSolicitado)); ?></td>
					        <td class="direita<?php if ($resposta->VlSugeridoParecerista == $resposta->VlSugeridoConselheiro) echo " green"; ?>"><?php echo $this->formatarReal($this->escape($resposta->VlSugeridoParecerista)); ?></td>
							<td><?php echo html_entity_decode($resposta->justproponente);?>
							<td> <textarea cols="80" id="justificativatecnico" name="justificativatecnico" rows="5"></textarea></td>
	
					
						</tr>
	
	
	
						<?php
								$item++; // incrementa o contador de itens
							endforeach; // fecha foreach itens		
						} // fecha if (caso tenha projetos)
						?>
						<!-- ========== FIM ÍTENS ========== -->
	
	
	
						<?php $contadorUF++; ?>
					<?php // endforeach; ?>
					<!-- ========== FIM BUSCA POR UF ========== -->
	
	
	
				<?php
					$contadorEtapa++;
				endforeach;
				?>
				<!-- ========== FIM BUSCA POR ETAPA ========== -->
	
	
	
			<?php $contadorProd++; ?>
			<?php endforeach; ?>
			<!-- ========== FIM BUSCA POR PRODUTO ========== -->

	
			<tr>
				<td colspan="10">
	
					<div class="float_right">
						<input type="submit" class="btn_salvar" value=" " onclick="return valida()" /></input>
						<input type="hidden" name="idProduto" value="<?php echo $resposta->idProduto; ?>" /></input>
						<input type="hidden" name="idPronac" value="<?php echo $resposta->IdPRONAC; ?>" /></input>
						<input type="hidden" name="idPlanilha" value="<?php echo $resposta->idPlanilhaAprovacao; ?>" /></input>
						<input type="hidden" name="idRecurso" value="<?php echo $resposta->idRecurso; ?>" /></input>
					</div>
				</td>
			</tr>
		</table>
	</form>
	</div>
	<!-- ========== FIM CONTEÚDO ========== -->
	
	
	
	<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
	<div id="rodapeConteudo"><span></span></div>
	<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
	
	<br clear="all" />