<div id="alerta"></div>
<div class="container-fluid">
    <h4>Análise Enquadramento Recurso</h4>
    <div class="row">
    <table class="bordered">
        <caption>Recurso fase 1</caption>
        <thead>
            <tr class="">
                <th class="center-align">PRONAC</th>
                <th class="center-align">Nome do Projeto</th>
                <th class="center-align">Dt. Solicita&ccedil;&atilde;o Recurso</th>
                <th class="center-align">Tipo Solicita&ccedil;&atilde;o</th>
                <th class="center-align">Tipo Recurso</th>
                <th class="center-align">Avaliar</th>
            </tr>
        </thead>
        <tbody>
            <?php if(!empty($this->dados->current())) : ?>
            <?php foreach($this->dados as $d): ?>
            <tr>
                <td class="center-align">
                    <a class="black-text btn white tooltipped" data-tooltip="Visualizar Projeto" href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->idPronac); ?>" target="_blank">
                        <?php echo $d->PRONAC; ?>
                        <i class="material-icons left hide-on-med-and-down">visibility</i>
                    </a>
                </td>
                <td class="center-align"><?php echo $d->NomeProjeto; ?></td>
                <td class="center-align"><?php echo Data::tratarDataZend($d->dtSolicitacaoRecurso, 'Brasileira'); ?></td>
                <td class="center-align"><?php echo $d->tpSolicitacao; ?></td>
                <td class="center-align"><?php echo $d->tpRecurso; ?></td>
                <td class="center-align">
                    <?php if($this->idPerfil == 131): ?>
                        <a class="white-text btn tooltipped" data-tooltip="Avaliar Recurso" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'recurso', 'action' => 'avaliar-recurso-enquadramento-editar'))?>?recurso=<?php echo $d->idRecurso; ?>">
                            <i class="material-icons">thumbs_up_down</i>
                        </a>
                    <?php else : ?>
                        <a class="white-text btn tooltipped" data-tooltip="Avaliar Recurso" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'recurso', 'action' => 'avaliar-recurso-enquadramento'))?>?recurso=<?php echo $d->idRecurso; ?>">
                            <i class="material-icons">thumbs_up_down</i>
                        </a>
                    <?php endif ?>
                </td>
            </tr>
            <?php endforeach ?>
        <?php else : ?>
            <tr>
                <td  colspan="6" align="center">Nenhum registro encontrado.</td>
            </tr>
        <?php endif ?>
    </table>
    </div>
    <?php if($this->recurso2fase > 0) : ?>
        <div class="row">
        <table class="bordered">
            <caption>Recurso fase 2</caption>
            <thead>
                <tr class="">
                    <th class="center-align">PRONAC</th>
                    <th class="center-align">Nome do Projeto</th>
                    <th class="center-align">Dt. Solicita&ccedil;&atilde;o Recurso</th>
                    <th class="center-align">Tipo Solicita&ccedil;&atilde;o</th>
                    <th class="center-align">Tipo Recurso</th>
                    <th class="center-align">Avaliar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->recurso2fase as $d): ?>
                <tr>
                    <td class="center-align">
                        <a class="btn white black-text waves-effect"  href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->idPronac); ?>" target="_blank">
                            <?php echo $d->PRONAC; ?>
                            <i class="material-icons left">visibility</i>
                        </a>
                    </td>
                    <td class="center-align"><?php echo $d->NomeProjeto; ?></td>
                    <td class="center-align"><?php echo Data::tratarDataZend($d->dtSolicitacaoRecurso, 'Brasileira'); ?></td>
                    <td class="center-align"><?php echo $d->tpSolicitacao; ?></td>
                    <td class="center-align"><?php echo $d->tpRecurso; ?></td>
                    <td class="center-align">
                        <a class="white-text btn"
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'recurso', 'action' => 'avaliar-recurso-enquadramento-editar'));?>?recurso=<?php echo $d->idRecurso; ?>">
                            <i class="material-icons">thumbs_up_down</i>
                        </a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        </div>
    <?php endif ?>
</div>
