<?php header('Content-Type: text/plain; charset=ISO-8859-1'); ?>
<script type="text/javascript">
 function AbrirFecharPlanilha(elemento)
 {
     $('.' + elemento).toggle();

     if ($('#' + elemento).hasClass('icn_mais'))
         {
             $('#' + elemento).addClass('icn_menos');
             $('#' + elemento).removeClass('icn_mais');
         }
     else
         {
             $('#' + elemento).addClass('icn_mais');
             $('#' + elemento).removeClass('icn_menos');
         }
 }

 $(document).ready(function(){
     $(".icn_menos").click(function(){
         var tipo = $(this).attr('tipo');
         var aberto = $(this).attr('aberto');
         if(aberto == 'true'){
             adisplay = 'none';
             $(this).attr('aberto','false')
             $(this).removeClass('icn_menos').addClass('icn_mais')
         }
         else{
             adisplay = '';
             $(this).attr('aberto','true')
             $(this).removeClass('icn_mais').addClass('icn_menos')
         }
         if(tipo == 'fonte'){
             fonte = $(this).attr('fonte');
             $(".master[fonte='"+fonte+"']").css('display', adisplay);
             $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
         }
         if(tipo == 'produto'){
             fonte = $(this).attr('fonte');
             produto = $(this).attr('produto');
             $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
         }
         if(tipo == 'etapa'){
             fonte = $(this).attr('fonte');
             produto = $(this).attr('produto');
             etapa = $(this).attr('etapa');
             $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
         }
         if(tipo == 'cidade'){
             fonte = $(this).attr('fonte');
             produto = $(this).attr('produto');
             etapa = $(this).attr('etapa');
             cidade = $(this).attr('cidade');
             $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
         }
     });
     $(".item").mouseover(function(){
         $(this).addClass('fundo_linha3');
     });
     $(".item").mouseout(function(){
         $(this).removeClass('fundo_linha3');
     });
     $(".item").click(function(){
         if($(this).hasClass('fundo_linha4')){
             $(this).removeClass('fundo_linha4');
         }
         else{
             $(this).addClass('fundo_linha4');
         }
     });

     $('.detalharItemComp').click(function(){
         $("#modalComprovantes").html('Carregando...');
         var idPlanilha = $(this).attr('idPlanilha');
         jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'consultardadosprojeto', 'action' => 'carregar-comprovantes-comprovados-por-item'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>&idPlanilha='+idPlanilha, '', 'modalComprovantes');

         $("#modalComprovantes").dialog("destroy");
         $("#modalComprovantes").dialog({
             resizable: true,
             title: 'Comprovantes do Item',
             width: 1200,
	     //                height:160,
             modal: true
         });
     });
 });
</script>

<div class="sumir centro" id="modalComprovantes">Carregando...</div>

<?php
switch ($this->tipoPlanilha) {
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_PROPOSTA:
        echo $this->partial('index/partial/planilha-proposta.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_PROPONENTE:
        echo $this->partial('index/partial/planilha-proponente.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_PARECERISTA:
        echo $this->partial('index/partial/planilha-parecerista.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_APROVADA_ATIVA:
        echo $this->partial('index/partial/planilha-ativa.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_CORTES_APROVADOS:
        echo $this->partial('index/partial/planilha-proposta.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_REMANEJAMENTO:
        echo $this->partial('index/partial/planilha-remanejamento.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_READEQUACAO:
        echo $this->partial('index/partial/planilha-readequacao.phtml', $this);
        break;
    case spPlanilhaOrcamentaria::TIPO_PLANILHA_SALDO_APLICACAO:
        echo $this->partial('index/partial/planilha-readequacao.phtml', $this);
        break;
}
