<?php
if (getenv('APPLICATION_ENV') != 'production') {
    $arrConf = array();
    $arrDb['PDO_MSSQL'] = 'SQL Server';
    $arrDb['PDO_PGSQL'] = 'Postgre SQL';

    $arrEnv = array();
    $arrEnv['development'] = 'Desenvolvimento';
    $arrEnv['testing']     = 'Homologa&ccedil;&atilde;o';
    $arrEnv['staging']     = 'Treinamento';

    $config = new Zend_Config_Ini(APPLICATION_PATH .'/configs/application.ini', APPLICATION_ENV);
    $strDb = $config->resources->db->adapter;
    $strEnv = getenv('APPLICATION_ENV');
} else {
    $strDb = false;
    $strEnv = false;
}
?>
<div id="container-progress-part" style="display: none;" class="preloader-wrapper big active">
    <div class="spinner-layer spinner-green">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-blue">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-red">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-yellow">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
</div>
<div id="container-progress" class="progress" style="margin: 0; position: fixed; display: none;">
    <div class="indeterminate"></div>
</div>
<div id="container-loading" style="display: none">
    <div class="sk-cube-grid">
        <div class="sk-cube sk-cube1"></div>
        <div class="sk-cube sk-cube2"></div>
        <div class="sk-cube sk-cube3"></div>
        <div class="sk-cube sk-cube4"></div>
        <div class="sk-cube sk-cube5"></div>
        <div class="sk-cube sk-cube6"></div>
        <div class="sk-cube sk-cube7"></div>
        <div class="sk-cube sk-cube8"></div>
        <div class="sk-cube sk-cube9"></div>
    </div>
    <div id="loading-message">carregando ...</div>
</div>

<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            <div class="row" style="margin: 0">
                <div class="col s12 m3 l3 offset-m1 offset-l1">
                    <a
                        class="orange-text text-lighten-3 tooltipped"
                        data-position="top"
                        data-delay="50"
                        data-tooltip="Ir para o portal de not&iacute;cias, tutoriais e legisla&ccedil;&otilde;es da Lei Rouanet"
                        target="_blank"
                        href="http://rouanet.cultura.gov.br/">LEI ROUANET</a>
                </div>
                <div class="col s12 m3 l3">
                    <div class="center-align">
                        <?php if ($strDb): ?>
                            <?php echo $arrEnv[$strEnv]; ?> | <?php echo $arrDb[$strDb]; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col s12 m3 l3">
                    <div class="center-align">
                        <?php echo $this->vcs(); ?>
                    </div>
                </div>
                <div class="col s12 m2 l2">
                    <div class="center-align">
                        <a
                            class="orange-text text-lighten-3 tooltipped"
                            data-position="top"
                            data-delay="50"
                            data-tooltip="Ir para o Site: Desenvolvimento Salic MinC"
                            target="_blank"
                            href="https://github.com/culturagovbr/salic-minc">Desenvolvimento</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
