    <?php
    if( isset($this->idPreProjeto)) {
        $idPreProjeto = $this->idPreProjeto;
    } elseif (isset($this->proposta->idPreProjeto)) {
        $idPreProjeto = $this->proposta->idPreProjeto;
    } elseif( $this->proposta['idpreprojeto'] ) {
        $idPreProjeto = $this->proposta['idpreprojeto'];
    }

    $arrMenuProponente = array();
    $arrMenuProponente['principal'] = array(
        'id' => 'informacaoinicial',
        'label' => 'Informa&ccedil;&otilde;es iniciais',
        'title' => '',
        'url' => '',
        'menu' => array(),
        'grupo' => array()
    );
    $arrMenuProponente['principal']['menu'][] = array('label' => 'Form antigo', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'editar', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );
    $arrMenuProponente['principal']['menu'][] = array('label' => 'Identifica&ccedil&atilde;o da proposta', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'identificacaodaproposta', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );
    $arrMenuProponente['principal']['menu'][] = array('label' => 'Responsabilidade Social', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'responsabilidadesocial', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );
    $arrMenuProponente['principal']['menu'][] = array('label' => 'Detalhes t&eacute;cnicos', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'detalhestecnicos', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );
    $arrMenuProponente['principal']['menu'][] = array('label' => 'Outras informa&ccedil;&otilde;es', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaincentivofiscal', 'action' => 'outrasinformacoes', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );

    $arrMenuProponente['localderealizacao'] = array(
        'id' => 'localderealizacao',
        'label' => 'Local de realiza&ccedil;&atilde;o',
        'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'localderealizacao', 'action' => 'index', 'idPreProjeto' => $idPreProjeto)),
        'menu' => array(),
        'grupo' => array()
    );

    $arrMenuProponente['planodedistribuicao'] = array(
        'id' => 'planodedistribuicao',
        'label' => 'Plano de distribui&ccedil;&atilde;o',
        'title' => 'Ir para plano de distribui&ccedil;&atilde;o',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'plano-distribuicao', 'action' => 'index', 'idPreProjeto' => $idPreProjeto)),
        'menu' => array(),
        'grupo' => array()
    );

    $arrMenuProponente['planilhaorcamentaria'] = array(
        'id' => 'planodedistribuicao',
        'label' => 'Or&ccedil;amento do projeto',
        'title' => '',
        'url' => '',
        'menu' => array(),
        'grupo' => array()
    );
    $arrMenuProponente['planilhaorcamentaria']['menu'][] = array('label' => 'Custos por produtos', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterorcamento', 'action' => 'produtoscadastrados', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );
    $arrMenuProponente['planilhaorcamentaria']['menu'][] = array('label' => 'Visualizar planilha', 'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterorcamento', 'action' => 'planilhaorcamentariageral', 'idPreProjeto' => $idPreProjeto)),
        'grupo' => array()
    );

    $arrMenuProponente['itensorcamentario'] = array(
        'id' => 'itensorcamentario',
        'label' => 'Itens or&ccedil;ament&aacute;rios',
        'title' => '',
        'url' => '',
        'menu' => array(),
        'grupo' => array()
    );
    $arrMenuProponente['itensorcamentario']['menu'][] = array('label' => 'Solicitar inclus&atilde;o de itens', 'title' => 'Ir para Solicitar inclus&atilde;o de itens',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'mantertabelaitens', 'action' => 'index')) . '?idPreProjeto='. $idPreProjeto,
        'grupo' => array()
    );
    $arrMenuProponente['itensorcamentario']['menu'][] = array('label' => 'Minhas solicita&ccedil;&otilde;es', 'title' => 'Ir para Minhas solicita&ccedil;&otilde;es',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'mantertabelaitens', 'action' => 'minhas-solicitacoes')) . '?idPreProjeto=' . $idPreProjeto,
        'grupo' => array()
    );

    $arrMenuProponente['anexardocumentos'] = array(
        'id' => 'anexardocumentos',
        'label' => 'Anexar documentos',
        'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaedital', 'action' => 'enviararquivoedital')) . '?idPreProjeto=' . $idPreProjeto,
        'menu' => array(),
        'grupo' => array()
    );

    $arrMenuProponente['imprimir'] = array(
        'id' => 'imprimir',
        'label' => 'Imprimir/Gerar PDF',
        'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'Gerarimprimirpdf', 'action' => 'index', 'idPreProjeto' => $idPreProjeto)),
        'menu' => array(),
        'grupo' => array()
    );

    $arrMenuProponente['imprimir'] = array(
        'id' => 'imprimir',
        'label' => 'Imprimir/Gerar PDF',
        'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'Gerarimprimirpdf', 'action' => 'index', 'idPreProjeto' => $idPreProjeto)),
        'menu' => array(),
        'grupo' => array()
    );

    $arrMenuProponente['mensagensenviadas'] = array(
        'id' => 'mensagensenviadas',
        'label' => 'Dilig&ecirc;ncias',
        'title' => '',
        'url' => $this->url(array('module' => 'proposta', 'controller' => 'diligenciar', 'action' => 'listardiligenciaproponente', 'idPreProjeto' => $idPreProjeto)),
        'menu' => array(),
        'grupo' => array()
    );

    if (isset($this->movimentacaoAtual) && $this->movimentacaoAtual == '95') {
        $arrMenuProponente['excluirproposta'] = array(
            'id' => 'excluirproposta',
            'label' => 'Excluir proposta',
            'title' => '',
            'url' => '',
            'menu' => array(),
            'grupo' => array()
        );

        $arrMenuProponente['enviarproposta'] = array(
            'id' => 'enviarproposta',
            'label' => 'Enviar proposta ao MinC',
            'title' => '',
            'url' => '',
            'menu' => array(),
            'grupo' => array()
        );

    }
?>

<div class="col s2 m12 l2">
    <aside id="left-sidebar-nav">
        <ul class="sidebar-nav">
            <li class="proposta-detalhes green darken-2 no-padding">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <p class="white-text valign-wrapper">
                            <i class="material-icons left"><?php echo (!$this->isEditavel) ? 'lock_outline' : 'lock_open'; ?></i>
                            <?php echo isset($this->configs['titleShort']) ? $this->titleShort : 'Proposta'; ?> n&#186;
                            <?php echo isset($this->configs['projeto']) ? $this->configs['projeto'] : $this->proposta['idpreprojeto']; ?>
                        </p>
                        <p class="white-text"><?php echo isset($this->proposta['nomeprojeto']) ? $this->proposta['nomeprojeto'] : ''; ?></p>
                    </div>
                </div>
            </li>
            <?php echo $this->partialLoop('inc/item.phtml', $arrMenuProponente); ?>
        </ul>
    </aside>

    <div id="trocarproponente" style="display:none">

        <form id="formtrocaproponente"
              action="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'vincularresponsavel', 'action' => 'trocarproponente')); ?>"
              method="post">
            <?php
            $idVinculoProposta = "";
            if(!empty($this->dadosVinculo[0])) {
                $idVinculoProposta = $this->dadosVinculo[0]->idvinculoproposta;
            }
            ?>
            <input type="hidden" value="<?php echo $idVinculoProposta; ?>" name="idVinculoProposta"/>
            <input type="hidden" value="<?php echo $idPreProjeto; ?>" name="idPreProjeto"/>
            <input type="hidden" value="1" name="mecanismo"/>
            <table class="tabela">
                <tr>
                    <td class="titulo_tabela">Selecione um Proponente ou cadastre um novo.</td>
                </tr>
                <tr>
                    <td>
                        CPF/CNPJ Proponente:&nbsp;
                        <select name="propronente" id="propronente" class="input_simples w240">
                            <?php $idAgente = 0; ?>
                            <?php if ($this->listaProponentes):?>
                                <?php foreach ($this->listaProponentes as $lp): $lp = array_change_key_case($lp);?>
                                    <?php if ($lp['idagenteproponente'] != $idAgente): ?>
                                        <option
                                            value="<?php echo $lp['idvinculo']; ?>:<?php echo $lp['idagenteproponente']; ?>"><?php echo $lp['nomeproponente']; ?></option>
                                    <?php endif; ?>

                                    <?php $idAgente = $lp['idagenteproponente']; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>&nbsp;<span id="msgValidaProponente"></span>&nbsp;&nbsp;&nbsp;
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
<script type="text/javascript">
    function layout_fluido() {
        var janela = $(window).width();

        $("#navglobal").css("width", "100%");
        $("#conteudo").css("width", "100%");
        $("#titulo").css("width", "100%");
        $("#rodapeConteudo").css("width", "100%");
        $("#rodape").css("width", "100%");
        $("div#rodapeConteudo").attr("id", "rodapeConteudo_com_menu");
    }

    $(document).ready(function () {

        $('.planilha').click(function () {
            $(this).next().toggle('fast');
        });

        $('#excluirproposta').click(function () {
            JSExcluirProposta();
        });

        $('#enviarproposta').click(function () {
            JSEnviarProposta();
        });

    });

    function JSExcluirProposta() {

        var text = 'Deseja realmente excluir sua proposta?';

        $('<div id="modalExcluirProposta"></div>').appendTo( $( "#left-sidebar-nav" ) ).html(text)

        $("#modalExcluirProposta").dialog("destroy");
        $("#modalExcluirProposta").dialog
        ({
            width: 450,
            height: 200,
            EscClose: false,
            modal: true
            , buttons: {
                'Cancelar': function () {
                    $(this).dialog('close');
                },
                'OK': function () {
                    window.location = "<?php echo $this->baseUrl(); ?>/proposta/manterpropostaedital/exluirproposta/?idPreProjeto=<?php echo $idPreProjeto; ?>";
                    $(this).dialog('close');
                }
            }
        });
        return false;
    }

    function JSEnviarProposta() {
        var text = 'Deseja realmente enviar sua proposta?';

        $('<div id="modalEnviarProposta"></div>').appendTo( $( "#left-sidebar-nav" ) ).html(text)

        $("#modalEnviarProposta").dialog("destroy");
        $("#modalEnviarProposta").dialog
        ({
            width: 450,
            height: 200,
            position: 'center',
            EscClose: false,
            modal: true,
            buttons: {
                'Cancelar': function () {
                    $(this).dialog('close');
                },
                'OK': function () {
                    window.location = "<?php echo $this->baseUrl(); ?>/proposta/manterpropostaincentivofiscal/enviar-proposta-ao-minc/idPreProjeto/?idPreProjeto=<?php echo $idPreProjeto; ?>";
                    $(this).dialog('close');
                }
            }
        });

        return false;
    }

    function trocarproponente() {

        $('<div id="trocarproponente"></div>').appendTo( $( "#left-sidebar-nav" ) ).html(text)

        $("#trocarproponente").dialog("destroy");
        $("#trocarproponente").dialog
        ({
            width: 600,
            height: 250,
            EscClose: false,
            modal: true,
            title: 'Trocar Proponente'
            , buttons: {
                'Cancelar': function () {
                    $(this).dialog('close'); // fecha a modal
                },
                'Novo Proponente': function () {
                    window.location = "<?php echo $this->url(array('module' => 'proposta', 'controller' => 'vincularresponsavel', 'action' => 'index')); ?>";
                },
                'Trocar Proponente': function () {
                    $("#formtrocaproponente").submit();

                }
            }
        });

        return false;
    }
</script>


