<?php if ($this->errorType == 'pagina' || $this->errorType == 'permissao' || $this->errorType == 'login') : ?>
    <div class="msg-error <?= $this->errorType ?>">
        <h3><?php echo $this->message ?></h3>
    </div>
<?php else: ?>
    <div class="msg-error exception">
    <span>
        <h3>CGTI, n&oacute;s temos um problema!</h3>
        <p>Erros processados pela requisi&ccedil;&atilde;o:</p>
    </span>
    </div>
    <?php if (isset($this->message)) echo "!!<p>{$this->message}</p>" ?>
    <?php if (isset($this->exception)): ?>
        <div class="msg-exception">
            <fieldset>
                <legend>Exce&ccedil;&atilde;o</legend>
                <b>Descri&ccedil;&atilde;o:</b> <?php echo $this->exception->getMessage() ?>
            </fieldset>

            <fieldset>
                <legend>Rastreamento do erro</legend>
                <pre><?php echo $this->exception->getTraceAsString() ?></pre>
            </fieldset>

            <fieldset>
                <legend>Par&acirc;metros requisitados</legend>
                <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
            </fieldset>
        </div>
    <?php endif;
endif ?>