<?php

class Projeto_Model_Situacao extends MinC_Db_Table_Abstract
{
    protected $_name = 'Situacao';
    protected $_schema = 'sac';
    protected $_primary = 'Codigo';

    const PROPOSTA_TRANSFORMADA_EM_PROJETO = 'B01';
    const PROJETO_ENQUADRADO_COM_RECURSO = 'B03';
    const PROJETO_EM_AVALIACAO_DOCUMENTAL = 'B04';
    const PROJETO_DEVOLVIDO_PARA_ENQUADRAMENTO = 'B05';
    const ENCAMINHADO_PARA_ANALISE_TECNICA = 'B11';
    const PROJETO_ADEQUADO_A_REALIDADE_DE_EXECUCAO = 'B20';
    const AGUARDANDO_ELABORACAO_DE_PORTARIA_DE_PRORROGACAO = 'D22';
    const PROJETO_ENCAMINHADO_PARA_INCLUSAO_EM_PORTARIA = 'D27';
    const ENCAMINHADO_PARA_INCLUSAO_EM_PORTARIA_COMPLEMENTACAO = 'D28';
    const ENCAMINHADO_PARA_INCLUSAO_EM_PORTARIA_REDUCAO = 'D29';
    const PARECER_TECNICO_EMITIDO = 'C20';
    const PROJETO_LIBERADO_PARA_AJUSTES = 'E90';
    const PROJETO_ENCAMINHADO_PARA_HOMOLOGACAO = 'D52';
    const PROJETO_APRECIADO_PELA_CNIC = 'D50';
    const INDEFERIDO_NAO_ENQUADRAMENTO_NOS_OBJETIVOS = 'A14';
    const INDEFERIDO_PROJETO_JA_REALIZADO = 'A16';
    const INDEFERIDO_NAO_ATENDIMENTO_A_DILIGENCIA = 'A17';
    const INDEFERIDO_PROJETO_EM_DUPLICIDADE = 'A20';
    const INDEFERIDO_SOMATORIO_DOS_PROJETOS_EXCEDE_O_LIMITE_PESSOA_FISICA = 'A23';
    const INDEFERIDO_SOMATORIO_DOS_PROJETOS_EXCEDE_O_LIMITE_PESSOA_JURIDICA = 'A24';
    const INDEFERIDO_50_PORCENTO_DE_CORTE_VALOR_SOLICITADO = 'A41';
    const PROJETO_ENQUADRADO = 'B02';
    const READEQUACAO_DO_PROJETO_APROVADA_AGUARDANDO_ANALISE_DOCUMENTAL = 'D02';
    const PROJETO_INDEFERIDO = 'D14';
    const PROJETO_APROVADO_AGUARDANDO_ANALISE_DOCUMENTAL = 'D03';
    const PROJETO_HOMOLOGADO = 'D51';
    const AUTORIZADA_CAPTACAO_RESIDUAL_DOS_RECURSOS = 'E12';
}
