<main>
    <?php
    $links = array(
        array('Gerenciar Projetos' => array(
            'module' => 'assinatura',
            'controller' => 'enquadramento',
            'action' => 'gerenciar-projetos'
        )),
        array('Visualizar ' => array())
    );
    montaGuiaLinks($controller, $links);
    ?>
    <div class="content">
        <div class="row">
            <div class="col s12">
                <form method="post"
                      class="materialize"
                      id="formGerenciamentoPropostas"
                      action="<?php echo $this->url(array(
                              'module' => 'assinatura',
                              'controller' => 'enquadramento',
                              'action' => 'assinarProjeto'
                          ), '', true) . "?IdPRONAC={$this->IdPRONAC}"; ?>"
                      onsubmit="return false;">
                    <table class="bordered responsive-table" id="enquadramento">
                        <thead>
                        <tr class="">
                            <th>
                                <input type="checkbox" name="marcarDesmarcarCheckbox" id="marcarDesmarcarCheckbox"
                                       class="filled-in"/>
                                <label id="marcarDesmarcarCheckboxLabel" for="marcarDesmarcarCheckbox"></label>
                            </th>
                            <th align="center" width="40">PRONAC</th>
                            <th>Nome do Projeto</th>
                            <th>&Aacute;rea</th>
                            <th>Segmento</th>
                            <th>Enquadramento</th>
                            <th>Valor Aprovado</th>
                            <th>Dias</th>
                            <th align="center">Ver</th>
                            <th align="center">Devolver</th>
                            <th align="center">Assinar</th>
                            <th align="center">Finalizar</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->dados as $dado): ?>
                            <tr>
                                <td>
                                    <input type="checkbox" name="IdPRONAC[]" id="IdPRONAC<?php echo $dado->IdPRONAC ?>"
                                           class="checkbox_legal filled-in" value="<?php echo $dado->IdPRONAC ?>"/>
                                    <label for="IdPRONAC<?php echo $dado->IdPRONAC ?>"></label>
                                </td>
                                <td align="center" >
                                    <a class="waves-effect waves-dark btn white black-text"
                                       href="<?php echo $this->url(
                                               array(
                                                   'module' => 'default',
                                                   'controller' => 'consultardadosprojeto',
                                                   'action' => 'index'
                                               )
                                           ) . "?idPronac={$dado['IdPRONAC']}"; ?>"><u><?php echo $dado['pronac']; ?></u></a>
                                </td>
                                <td align="center"><?php echo $dado['nomeProjeto']; ?></td>
                                <td align="center"><?php echo $dado['area']; ?></td>
                                <td align="center"><?php echo $dado['segmento']; ?></td>
                                <td align="center"><?php echo ((int)$dado['tp_enquadramento'] == 1) ? 'Artigo 26' : 'Artigo 18'; ?></td>
                                <td align="center"><?php echo (!empty($dado['vlAprovado'])) ? $dado['vlAprovado'] : '-'; ?></td>
                                <td align="center"><?php echo $dado['dias']; ?></td>
                                <td align="center">
                                    <a class="btn waves-effect waves-light white tooltipped small black-text"
                                       href="<?php echo $this->url(array(
                                           'module' => 'assinatura',
                                           'controller' => 'enquadramento',
                                           'action' => 'visualizar-enquadramento'
                                           )) . "?IdPRONAC={$dado['IdPRONAC']}&encaminhar=true" ?>"
                                       data-position="top"
                                       data-delay="50"
                                       data-tooltip="Visualizar">
                                        <i class="material-icons">search</i>
                                    </a>
                                </td>
                                <td align="center">
                                    <a class="btn waves-effect waves-light white tooltipped small black-text"
                                       href="<?php echo $this->url(array(
                                           'module' => 'assinatura',
                                           'controller' => 'enquadramento',
                                           'action' => 'devolver-projeto'
                                           )) . "?IdPRONAC={$dado['IdPRONAC']}&encaminhar=true" ?>"
                                       data-position="top"
                                       data-delay="50"
                                       data-tooltip="Devolver">
                                        <i class="material-icons">keyboard_backspace</i>
                                    </a>
                                </td>
                                <td align="center">
                                    <a class="btn waves-effect waves-light white tooltipped small black-text"
                                       href="<?php echo $this->url(array(
                                           'module' => 'assinatura',
                                           'controller' => 'enquadramento',
                                           'action' => 'assinar-projeto'
                                           )) . "?IdPRONAC={$dado['IdPRONAC']}&encaminhar=true" ?>"
                                       data-position="top"
                                       data-delay="50"
                                       data-tooltip="Assinar">
                                        <i class="material-icons">create</i>
                                    </a>
                                </td>
                                <td align="center">
                                    <a class="btn waves-effect waves-light white tooltipped small black-text"
                                       href="<?php echo $this->url(array(
                                           'module' => 'assinatura',
                                           'controller' => 'enquadramento',
                                           'action' => 'finalizar-assinatura'
                                           )) . "?IdPRONAC={$dado['IdPRONAC']}&encaminhar=true" ?>"
                                       data-position="top"
                                       data-delay="50"
                                       data-tooltip="Finalizar">
                                        <i class="material-icons">grade</i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div class="center-align" id="divAssinaturaEmMassa"
                         style="display: none;">
                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Assinar em massa <i class="material-icons right">send</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br clear="all"/>
    <script src="https://code.jquery.com/jquery-1.12.4.js"
            integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.material.min.js"></script>

    <!--    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>-->

    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                $('#enquadramento').DataTable({
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                    }
                    , "order": [0, 1]
                    , "searching": true
                    , "lengthChange": true
                    , columnDefs: [{
                        targets: [0, 1],
                        className: 'mdl-data-table__cell--non-numeric'
                    }]
                    ,
                    "aoColumnDefs": [
                        {'bSortable': false, 'aTargets': [0, 1, 2, 3]}
                    ]
                });
                $3("#marcarDesmarcarCheckboxLabel").click(function () {
                    utilitarios.marcarDesmarcarCheckBoxesMaterialize($3("#marcarDesmarcarCheckbox"), ".checkbox_legal");
                    tratarExibicaoCheckboxChecados('.checkbox_legal', '#divAssinaturaEmMassa');
                });

                function tratarExibicaoCheckboxChecados (seletorCheckboxes, seletorExibicao) {
                    var quantidadeCheckboxChecados = $(seletorCheckboxes).filter(':checked').length;
                    if(quantidadeCheckboxChecados > 0) {
                        $3(seletorExibicao).show('fast');
                    } else {
                        $3(seletorExibicao).hide('fast');
                    }
                }

                $3('.checkbox_legal').click(function () {
                    tratarExibicaoCheckboxChecados('.checkbox_legal', '#divAssinaturaEmMassa');
                });

                $3("#formGerenciamentoPropostas").validate({
                    rules: {
                        marcarDesmarcarCheckbox: {
                            validarPreenchimento: true
                        }
                    },
                    messages: {
                        marcarDesmarcarCheckbox: {
                            validarPreenchimento: ""
                        }
                    },

                    submitHandler: function (form) {
                        $3("#container-progress").show();
                        form.submit();
                    },
                    invalidHandler: function (event, validator) {
                        Materialize.toast("Selecione um item.", 4000);
                    }
                });

                $3.validator.addMethod("validarPreenchimento", function (value, element) {
                    var checkbox = $('input[type=checkbox]:checked').filter('.checkbox_legal');
                    if (checkbox.length > 0) {
                        return true;
                    }
                });
            });
        }($.noConflict(true)));
    </script>
</main>