<?php 
$hrefAlterarintemsolicitado = $this->url(array('controller' => 'Analisarprojetoparecer', 'action' => 'alterarintemsolicitado'));
?>
<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div> Análise do Produto Secundário</div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<div id="dialog-valor" class="sumir" title="Valor Inv&aacute;lido">
    <div class="msgERROR">
        <div>Valor de remanejamento maior que o permitido! M&aacute;ximo : <span id="valorpossivelApresentacao"></span></div>
    </div>
</div>
<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
        <table class="tabela" >
            <tr>
                <th>
                    Análise de Conteúdo do Projeto Nr: <?php echo $this->projeto->PRONAC; ?> - <?php echo $this->projeto->NomeProjeto; ?>
                    <br/>Produto <?php
            if ($this->projeto->stPrincipal) {
                echo 'Principal';
            } else {
                echo 'Secundario';
            }
            ?>: <?php echo $this->projeto->dsProduto; ?>
                </th>
            </tr>
        </table>
        <!-- FIM ANALISE DE CONTEÚDO  -->
        <table class="tabela">
            <tr>
                <td><input type="button" id="abaAnaliseConteudo" class="btn_adicionar" />Análise de conteúdo</td>
            </tr>
        </table>
        <!-- Formulario -->
        <div id="divAnaliseConteudo" style="display:none;">
            <form name="formAnaliseConteudo" id="formAnaliseConteudo" action="<?php echo $this->url(array('controller' => 'Analisarprojetoparecer', 'action' => 'analisedeconteudo')); ?>" method="post">
                <input type="hidden" id="stAcao" name="stAcao" value="0"/>
                <input type="hidden" name="idPRONAC" value="<?php echo $this->projeto->IdPRONAC; ?>"/>
                <input type="hidden" name="idProduto" value="<?php echo $this->projeto->idProduto; ?>"/>
                <input type="hidden" id="stPrincipal" name="stPrincipal" value="<?php echo $this->projeto->stPrincipal; ?>"/>

                <table class="tabela" style="width: 95%;">
                    <tr>
                        <th colspan="5" class="center">Enquadramento</th>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                    </tr>
                    <tr>
                        <td rowspan="2" id="Lei8313" colspan="2">
                            <b>Lei 8.313/91 alterada pela Lei 9.874/1999 * </b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" name="Lei8313" onclick="APPescolherLei_8313();"/>Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" name="Lei8313" onclick="APPescolherLei_8313();"/>N&atilde;o
                            </p>
                        </td>
                        <td id="Artigo3"><b>Artigo 3&deg;</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" name="Artigo3" onclick="APPescolherArtigo3();" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" name="Artigo3" onclick="APPescolherArtigo3();" />N&atilde;o
                            </p>
                        </td>
                        <td><b>Inciso</b>
                            <p>
                                <select class="campo select_simples" id="IncisoArtigo3" name="IncisoArtigo3">
                                    <option value="0" >Selecione</option>
                                    <option value="1">I</option>
                                    <option value="2" >II</option>
                                    <option value="3" >III</option>
                                    <option value="4" >IV</option>
                                    <option value="5" >V</option>
                                </select>
                            </p>
                        </td>
                        <td id="AlineaArtigo3">
                            <b>Alinea Artigo 3</b>
                            <p style="margin-top: 10px;">
                                <input type="text" class="input_simples" name="AlineaArtigo3" id="AlineaArtigo3" />
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td id="Artigo18">
                            <b>Artigo 18&deg;</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" name="Artigo18" onclick="APPescolherArt_18();" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" name="Artigo18" onclick="APPescolherArt_18();" />N&atilde;o
                            </p>
                        </td>
                        <td id="AlineaArtigo18">
                            <b>Alínea Artigo 18</b>
                            <p style="margin-top: 10px;">
                                <input type="text" class="input_simples" name="AlineaArtigo18" />
                                <input type="hidden" name="AlineaArt18" id="AlineaArt18" />
                            </p>
                        </td>
                        <td id="Artigo26">
                            <b>Artigo 26&deg;</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" name="Artigo26" onclick="APPescolherArt_26();" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" name="Artigo26" onclick="APPescolherArt_26();" />N&atilde;o
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <b>Decreto 5761/2006 *</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" name="Lei5761" onclick="APPescolherDecreto5761();" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" name="Lei5761" onclick="APPescolherDecreto5761();" />N&atilde;o
                            </p>
                        </td>
                        <td id="Artigo27">
                            <b>Artigo 27&deg;</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;"  value="1" name="Artigo27" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;"  value="0" name="Artigo27" />N&atilde;o
                            </p>
                        </td>
                        <td id="IncisoArtigo27">
                            <b>Inciso(s)</b>
                            <p style="margin-top: 10px;">
                                <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_I" />I &nbsp;&nbsp;&nbsp;
                                <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_II" />II &nbsp;&nbsp;&nbsp;
                                <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_III" />III &nbsp;&nbsp;&nbsp;
                                <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_IV" />IV
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <b>Enquadramento Favorável? *</b>
                            <p style="margin-top: 10px;">
                                <input type="radio" style="margin-right: 5px;" value="1" class="ParecerFavoravel" name="ParecerFavoravel" checked="checked" />Sim &nbsp;&nbsp;
                                <input type="radio" style="margin-right: 5px;" value="0" class="ParecerFavoravel" name="ParecerFavoravel" />N&atilde;o
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <b>Justificativa do enquadramento*</b>
                            <p>
                    <center>
                        <textarea class="textarea_simples" id="ParecerDeConteudo" name="ParecerDeConteudo" rows="10" style="width: 98%;"></textarea>
                    </center>
                    </td>
                    <?php if($this->grupoAtivo == 93):?>              
                    </tr>
                    <tr>
                       
                    </tr>
                    <?php else: ?>
                    <tr id="btSalvar">
                        <td colspan="6" align="center">
                            
                        </td>
                    </tr>
                    <?php endif; ?>
                </table>
            </form>
        </div>
        <table class="tabela">
            <tr>
                <td><input type="button" id="abaAnaliseCusto" class="btn_adicionar" />Análise de custos <input id="valorpossivel" value="<?php echo $this->valorpossivel;?>" type="hidden"/></td>
            </tr>
        </table>
        <div id="divAnaliseCusto" style="display:none;">
            <table class="tabela" style="width: 95%;" width="95%">
                <tr>
                    <th colspan="13">Planilha de Or&ccedil;amento Sugerido</th>
                </tr>
                <?php
                $nrfonte = 0;
                $item = 1;
                //ForeachFonteIncentivo
                foreach ($this->itens['fonte'] as $fonte => $arrayProdutos) 
                { 
                    ?>
                    <tr>
                        <td colspan="11">
                            <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
                        </td>
                    </tr>
                    <?php
                    $nrproduto = 0;
                    foreach ($arrayProdutos as $produto => $arrayEtapas) 
                    {
                        ?>
                        <tr class='master' fonte="<?php echo $nrfonte; ?>">
                            <td class='master' colspan="11">
                                <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                            </td>
                        </tr>
                        <?php
                        $nretapa = 0;
                        foreach ($arrayEtapas as $etapa => $arrayCidades) 
                        {
                            ?>
                            <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                                <td colspan="11">
                                    <div><div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div></div>
                                </td>
                            </tr>
                            <?php
                            $nrcidade = 0;
                            foreach ($arrayCidades as $cidade => $planilha) 
                            {
                                ?>
                                <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                                    <td colspan="11">
                                        <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;">
                                            <span class="black del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span>
                                        </div>
                                    </td>
                                </tr>
                                <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" cidade="<?php echo $nrcidade; ?>">
                                    <td colspan="11">
                                        <table class="tabela">
                                            <?php
                                            /* INICIO PLANILHA DE ITENS */
                                            $primeiro = 0;
                                            foreach ($planilha['itens'] as $idPlanilhaProjeto => $valPlanilha) 
                                            {
                                                $valorprodutosolicitado = 0;
                                                $valorprodutoparecerista = 0;
                                                $trCampo = "<tr>";
                                                $conteudo = "<tr class='item' idPlanilhaProjeto='{$idPlanilhaProjeto}' id='item{$idPlanilhaProjeto}'>";

                                                foreach ($valPlanilha as $camp => $cont) 
                                                {
                                                    $trCampo .= "<th>{$camp}</th>";
                                                    if ($camp == 'Valor Unitário' || $camp == 'Valor Solicitado' || $camp == 'Valor Sugerido pelo Parecerista') 
                                                    {
                                                        if ($camp == 'Valor Sugerido pelo Parecerista') 
                                                        {
                                                            $conteudo .= "<td class='ValorSugerido' style='width:10;'>{$this->formatarReal($cont)}</td>";
                                                        } 
                                                        else 
                                                        {
                                                            $conteudo .= "<td style='width:12%;'>{$this->formatarReal($cont)}</td>";
                                                        }
                                                    } 
                                                    else 
                                                    {
                                                        if ($camp == 'Justificativas do Parecerista') 
                                                        {
                                                            $conteudo .= "<td class='JustParecerista'>{$cont}</td>";
                                                        } 
                                                        else 
                                                        {
                                                            $conteudo .= "<td>{$cont}</td>";
                                                        }
                                                    }
                                                }
                                                $trCampo .= "</tr>";
                                                $conteudo .= "</tr>";
                                                
                                                if ($primeiro == 0) 
                                                {
                                                    echo $trCampo;
                                                }
                                                
                                                echo $conteudo;
                                                $primeiro++;
                                            }
                                            ?>
                                            <tr style="font-weight: bold;">
                                                <td class="esquerda black" style="font-size: 12pt; width: 12%;" colspan="7">Total de UF</th>
                                                <td class="esquerda black" style="font-size: 12pt; width: 15%;"><?php echo $planilha['totalUfSolicitado']; ?></td>
                                                <td class="esquerda black" style="font-size: 12pt; width: 12%;">&nbsp;</td>
                                                <td class="valorUfSugerido esquerda black" style="font-size: 12pt; width: 15%;"><?php echo $planilha['totalUfSugerido']; ?></td>
                                                <td class="esquerda black" style="font-size: 12pt; width: 12%;">&nbsp;</td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <?php
                                /* FIM PLANILHA DE ITENS */
                            }
                            $nretapa++;
                        } //fechaForeachetapa
                        $nrproduto++;
                    } //fechaForeachproduto
                    $nrfonte++;
                }//fechaForeachFonteIncentivo
                ?>
                <tr>
                    <td colspan="11">
                        <table class="tabela">
                            <tr>
                                <th colspan="5">Total Solicitado do produto - Todas as fontes de incentivo</th>
                                <th colspan="6">Total Sugerido do produto - Todas as fontes de incentivo</th>
                            </tr>
                            <tr>
                                <td class="esquerda black" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="5"><?php echo $this->itens['totalSolicitado']; ?></td>
                                <td class="valorTotalSugerido esquerda black" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="6"><?php echo $this->itens['totalSugerido']; ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
        
        <script>APPescolherArt_18(); APPescolherArt_26(); APPescolherLei_8313(); APPescolherArtigo3();</script>
        
        <!-- MODAL -->
        <div id="alteraritemsolicitado" link="<?php echo $hrefAlterarintemsolicitado; ?>" style="display: none;">

        </div>
        <div id="confirmacao" style="display: none;">

        </div>

        <!-- FIM MODAL -->
</div>
<!-- ========== FIM CONTEÚDO ========== -->

<div id="confirma"></div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?php echo $this->grupoAtivo; ?>" />
<br clear="all" />
<script type="text/javascript">

    function carregarTextAreaCKEditor(){
        CKEDITOR.replace( 'ParecerDeConteudo', { toolbar: [] } );
    }

    $(document).ready(function(){
        

        $("#valorpossivelApresentacao").html('<?php echo $this->formatarReal($this->valorpossivel);?>');
    	
        desabilitaFormConteudo(true);	
        $("#divAnaliseCusto a").click(function() { return false; }); 

        carregarAnaliseDeConteudo();
        $('#btSalvarAnaliseDeConteudo').click(function(){
                if($('#stAcao').val() != 0){
                        $('#formAnaliseConteudo').submit();
                }

                return false;
        });
        var cont = 0;
        $('.class_relatorio').each(function(){
                var contAux = cont;
                $('#abrir_fechar'+contAux).click(function(){
                    $('#div_relatorio'+contAux).toggle('slow');
                });
                cont++;
        });

        window.setTimeout('carregarTextAreaCKEditor()', 1000);
        
        $('.linkrelatorio').click(function(){
            var este = this;
            var cont = $(este).attr('cont');
            $('#div_relatorio'+cont).html('<table class="tabelaRelatorio" cellspacing="1" style="margin: 0;margin-left: 52px; width: 90%;  padding: 0px;"><tr><td align="center"><img src="../public/img/ajax.gif"/>&nbsp;Carregando...</td><tr></table>');
            $('#div_relatorio'+cont).css('display','');
            $.post($(este).attr('link'),{nrRelatorio: cont,idPRONAC:<?php echo $this->projeto->IdPRONAC; ?>},function(data){
                $('#div_relatorio'+$(este).attr('cont')).html(data);
            });
        });
        $(".icn_menos").click(function(){
            var tipo = $(this).attr('tipo');
            var aberto = $(this).attr('aberto');
            if(aberto == 'true'){
                adisplay = 'none';
                $(this).attr('aberto','false');
                $(this).removeClass('icn_menos').addClass('icn_mais');
            }
            else{
                adisplay = '';
                $(this).attr('aberto','true');
                $(this).removeClass('icn_mais').addClass('icn_menos');
            }
            if(tipo == 'fonte'){
                fonte = $(this).attr('fonte');
                $(".master[fonte='"+fonte+"']").css('display', adisplay);
                $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
            }
            if(tipo == 'produto'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'etapa'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'cidade'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                cidade = $(this).attr('cidade');
                $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
        });
        $(".item").mouseover(function(){
            $(this).addClass('fundo_linha3');
        });
        $(".item").mouseout(function(){
            $(this).removeClass('fundo_linha3');
        });
        $(".item").click(function(){
            if($(this).hasClass('fundo_linha4')){
                $(this).removeClass('fundo_linha4');
            }
            else{
                $(this).addClass('fundo_linha4');
            }
        });
       
        
    });
	function abrirfechar(elemento){
		$('#'+elemento).toggle();
	}
    
    function desabilitaFormConteudo(habilitar){
        $('#formAnaliseConteudo').find('input, select, textarea').each(function(key, object){
            if(habilitar){
                $(object).attr('disabled','true');
            }else{
                $(object).removeAttr('disabled');
            }
        });
    }
    
    
    function areadetrabalho()
    {
        $('#abrir_fechar4').click(function()
        {
            $('#enquadramento').toggle('slow');
            $('#parecer').toggle('slow');
            $('#divAnaliseConteudo').hide('slow');
            $('#div_teste2').hide('slow');
        });
        
        $('#abaAnaliseConteudo').click(function()
        {
            $('#divAnaliseConteudo').toggle('slow');
        });
        
        $('#abaAnaliseCusto').click(function()
        {
            $('#divAnaliseCusto').toggle('slow');
        });
    }
    
    window.onload = function()
    {
    	areadetrabalho();
    };

    function AbrirFecharPlanilha(elemento)
    {
        $('.' + elemento).toggle();
        if ($('#' + elemento).hasClass('icn_mais'))
        {
            $('#' + elemento).addClass('icn_menos');
            $('#' + elemento).removeClass('icn_mais');
        }
        else
        {
            $('#' + elemento).addClass('icn_mais');
            $('#' + elemento).removeClass('icn_menos');
        }
    }

    function carregarAnaliseDeConteudo()
    {
        recuperaFormulario($('#formAnaliseConteudo').attr('action'),{stAcao: 1, idPRONAC: <?php echo $this->projeto->IdPRONAC; ?>, idProduto: <?php echo $this->projeto->idProduto; ?>, stPrincipal:<?php echo $this->projeto->stPrincipal; ?>});
        return true;
    }
    
    function recuperaFormulario(url,params){
        if(params.length < 1)
        {
            params = {};
        }
        var btSalvar = false;
        $.post(url,params,function(data){
            if(data){
                $('#formAnaliseConteudo').find('input, select, textarea').each(function(key, object){
                    if($(object).attr('type') == 'radio'){
                        if($(object).val() == data[$(object).attr('name')]){
                            btSalvar = true;
                            $(object).attr('checked','true');
                        }
                    }else{
                        if($(object).attr('type') == 'checkbox'){
                            if(data[$(object).attr('name')] == 1){
                                btSalvar = true;
                                $(object).attr('checked','true');
                            }
                        }else{
                            btSalvar = true;
                            $(object).val(data[$(object).attr('name')]);
                        }
                    }
                });
                $('#stAcao').val(2);
               // desabilitaFormConteudo(false);
            }else{
                $('#stAcao').val(3);
            }
        },'json');
    }
    function AbrirFecharPlanilha(elemento){
        $('.' + elemento).toggle();

        if ($('#' + elemento).hasClass('icn_mais'))
        {
            $('#' + elemento).addClass('icn_menos');
            $('#' + elemento).removeClass('icn_mais');
        }
        else
        {
            $('#' + elemento).addClass('icn_mais');
            $('#' + elemento).removeClass('icn_menos');
        }
        return false;
    }    
    
    function AlterarItem(idPlanilhaProjeto,idPronac,idProduto,stPrincipal)
    {
        //$('html').css('overflow', 'hidden');
        var este = $('#alteraritemsolicitado');
        este.html('<br><br><br><br><br><br><br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
        este.dialog(
        {
            title:"Alterar Item",
            resizable: false,
            width:800,
            height:600,
            modal: false,
            autoOpen:true,
            closeOnEscape:true
        });
        
        $.post(este.attr('link'),{idPlanilhaProjeto:idPlanilhaProjeto,idPronac:idPronac,idProduto:idProduto,stPrincipal:stPrincipal}
        ,function(data)
        {

            este.html(data);
            este.dialog(
            {
                title:"Alterar Item",
                resizable: false,
                width:800,
                height:600,
                modal: false,
                autoOpen:true,
                closeOnEscape:true,
                buttons:
                {
                    'Cancelar': function()
                    {
                        $(this).dialog('close');
                        //$('html').css('overflow', 'auto');
                    },
                    'Salvar': function()
                    {

                    	var texto = $('#justificativa'+$('#idPlanilhaProjeto').val()).val();
                            texto = texto.replace(/^\s+|\s+$/g,""); //retirando espaços
                    	if (texto.length <= 0 || texto=="")
                        {
                                alertar('Dados obrigatórios não informados.');
                          	return false; 
                        }
                        else
                        {
                            var vlSugerido = $('#calcular_total'+$('#idPlanilhaProjeto').val()).html().replace(/\R\$\s+/g, '');
                                $('#totalcalculos'+$('#idPlanilhaProjeto').val()).val(vlSugerido);
                                
                            var dados = $('#formSalvarItem').serialize();
                            $(this).append('<br><center>Aguarde, salvando informações...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
                            $.post($('#formSalvarItem').attr('action'),dados
                            ,function(data)
                            {
                                var resposta = data;
                                $('#item'+$('#idPlanilhaProjeto').val()+' .JustParecerista').html($("#justificativa"+$('#idPlanilhaProjeto').val()).val());
                                $('#item'+$('#idPlanilhaProjeto').val()+' .ValorSugerido').html($("#calcular_total"+$('#idPlanilhaProjeto').val()).html());
                                somarValores();
                                
                                //atualiza novo valor possivel de remanejamento
                                var vlSolicitado = '<?php echo $this->vlSolicitado;?>';
                                var vlTotalSugerido = recuperaTotalSugerido();
                                var valorpossivel = vlSolicitado - vlTotalSugerido;
                                
                                $("#valorpossivel").val(valorpossivel);

                                //atualiza campo de apresentacao do novo valor possivel de remanejamento
                                var valorpossivelApresentacao = formatarParaReal(valorpossivel);
                                $("#valorpossivelApresentacao").html(valorpossivelApresentacao);
                                
                                este.dialog('close');
                                janelaAlerta('Informações salvas com sucesso');
                            });

                        }
                    }
                }
            });
        });
        

    }
    
    function recuperaTotalSugerido()
    {
        // pega o valor total do relator
        var valor = $('.valorTotalSugerido').html();
        valor = valor.replace('R$ ', '');

        // retira os pontos e as virgulas, deixando somente numeros
        valor = valor.replace(/\D/g, "");
        valor = valor.replace(/(\d{0})(\d)/, "$1$2");

        // adiciona o ponto na casa decimal
        valor = valor.replace(/(\d)(\d{2})$/, "$1.$2");

        // converte para float
        valor = parseFloat(valor);
        
        return valor;
    }
    
    // formata para real
    function formatarParaReal(valor)
    {
        valor = (parseFloat(valor)).toFixed(2);
        valor = valor.replace(/\D/g, "");
        valor = valor.replace(/(\d)(\d{2})$/, "$1,$2");
        valor = valor.replace(/(\d+)(\d{3},\d{2})$/g, "$1.$2");

        var q = (valor.length - 3) / 3; // quantidade caracteres
        var c = 0; // contador
        while (q > c)
        {
            c++;
            valor = valor.replace(/(\d+)(\d{3}.*)/, "$1.$2");
        }
        valor = valor.replace(/^(0+)(\d)/g, "$2");
        valor = 'R$ ' + valor;
        
        return valor;
    }
    function janelaAlerta(mensagem,funcaoAdcional)
    {
        if(funcaoAdcional==undefined)
        {
            funcaoAdcional = function(){}
        }
        var nomeJanelaAlerta =   janelaObj({
            parametros : {
                width:      400,
                autoOpen:   false,
                resizable:  false,
                modal:      true,
                buttons: {
                    OK: function() {
                        funcaoAdcional();
                        $(this).dialog('close');
                    }
                }
            },
            removerBtFechar:true,
            title : 'Alerta'
        });
        nomeJanelaAlerta.divConteudo.html(mensagem);
        nomeJanelaAlerta.abrirJanela();

        return nomeJanelaAlerta;
    }
    function janelaObj(dados){
        var divConteudo = $('<div></div>')
        .attr('title',dados.title)
        .appendTo('body');
        var novaJanela = 
        {
            divConteudo : divConteudo,
            removerBtFechar: true,
            parametros : {autoOpen: false},
            iniciarJanela : function(dados){
                this.refineParametrosObj(dados);

                this.divConteudo.dialog(this.parametros);
            },
            abrirJanela:function(){
                this.divConteudo.dialog('open');
                if(this.removerBtFechar)
                    $('.ui-dialog-titlebar-close').remove();
            },
            fecharJanela:function(){
                this.divConteudo.dialog('close');
                this.divConteudo.remove();
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){
                        this[j]=data[j];
                    }
            }
        }
        novaJanela.iniciarJanela(dados);
        return novaJanela;
    }
</script>
</html>