<?php
/**
 * Exemplo Menu de Abas
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout.inc
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */
?>

<table class="tabela">
	<tr>
		<th class="<?php echo (stripos($this->url(), 'menu-abas1') !== false) ? "fundo_linha2" : "fundo_linha5"; ?>"><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'menu-abas1'));?>" title="Ir para Menu de Abas 1">Menu de Abas 1</a></th>
		<th class="<?php echo (stripos($this->url(), 'menu-abas2') !== false) ? "fundo_linha2" : "fundo_linha5"; ?>"><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'menu-abas2'));?>" title="Ir para Menu de Abas 2">Menu de Abas 2</a></th>
		<th class="<?php echo (stripos($this->url(), 'menu-abas3') !== false) ? "fundo_linha2" : "fundo_linha5"; ?>"><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'menu-abas3'));?>" title="Ir para Menu de Abas 3">Menu de Abas 3</a></th>
		<th class="<?php echo (stripos($this->url(), 'menu-abas4') !== false) ? "fundo_linha2" : "fundo_linha5"; ?>"><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'menu-abas4'));?>" title="Ir para Menu de Abas 4">Menu de Abas 4</a></th>
	</tr>
</table>