<?php foreach ($this->dados as $pc): ?>
    <br/>
    <table class="tabela">
        <tr class="classNomeParecerista">
            <th colspan="4" align="left">Parecerista: <?php echo $pc->Parecerista; ?></th>
        </tr>
        <tr>
            <td rowspan="4" width="300" align="center"><b>Lei 8.313/91 alterada pela Lei 9.874/1999</b> <br/><br/>
                ( <?php echo $pc->Lei8313; ?> )
            </td>
            <td colspan="3"><b>Produto:</b> <br/> <?php echo $pc->Produto; ?></td>
        </tr>
        <tr>
            <td><b>Artigo 3&ordm;</b> <br/> <?php echo $pc->Artigo3; ?></td>
            <td><b>Inciso</b> <br/> <?php echo $pc->IncisoArtigo3; ?></td>
            <td><b>Al&iacute;nea</b> <br/> <?php echo $pc->AlineaArtigo3; ?></td>
        </tr>
        <tr>
            <td><b>Artigo 18&ordm;</b><br/> <?php echo $pc->Artigo18; ?></td>
            <td colspan="2"><b>Al&iacute;nea</b> <br/> <?php echo $pc->AlineaArtigo18; ?>
            </td>
        </tr>
        <tr>
            <td colspan="3"><b>Artigo 26&ordm;</b> <br/> <?php echo $pc->Artigo26; ?></td>
        </tr>
        <tr>
            <td><b>Decreto 5761/2006</b> <br/> <?php echo $pc->Lei5761; ?></td>
            <td><b>Artigo 27&ordm;</b> <br/> <?php echo $pc->Artigo27; ?></td>
            <td colspan="2"><b>Inciso(s)</b> <br/>

                (<?php echo $pc->IncisoArtigo27_I; ?>) <b>I</b>
                (<?php echo $pc->IncisoArtigo27_II; ?>) <b>II</b>
                (<?php echo $pc->IncisoArtigo27_III; ?>) <b>III</b>
                (<?php echo $pc->IncisoArtigo27_IV; ?>)<b>IV</b></td>
        </tr>
        <tr>
            <td colspan="4"><b>Parecer Favoravel ?</b>
                <br/> <?php echo $pc->ParecerFavoravel; ?></td>
        </tr>
        <tr>
            <td colspan="4"><b>Parecer</b> <br/><br/> <?php echo $pc->ParecerDeConteudo; ?>
            </td>
        </tr>
    </table>
    <br/>
<?php endforeach; ?>