<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" LANGUAGE="JavaScript">
    $(document).ready(function(){
        window.print();
    });
</script>

<style type="text/css" media="all">
    body {
        margin:0;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        color:#000;
        line-height:14pt;
    }
    a:link, a:active, a:visited {
        text-decoration:underline;
    }
    a:hover {
        text-decoration:none;
    }
    .tabela { /* tamanho de tabelas com registros */
        margin:10px auto;
        width:97%;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
        border-spacing: 1px;
        empty-cells: show;
    }
    table td {
        background:#fff;
        padding:4px;
        color:auto;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table tr.destacar td, table td.destacar {
        background:#e2e2e2;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table th {
        background:#cdcdcd;
        padding:4px;
        text-transform:uppercase;
        font-size:11px;
        border: 1px #999 solid;
        color: #000;
    }
    #brasao{
        width : 85px;
        height: 86px;
    }
    legend{
        font-size:13px;
        font-weight: bold;
    }
    .btn_imprimir{
        border-top:1px solid #efefef;
        border-left:1px solid #efefef;
        border-right:1px solid #aaa;
        border-bottom:1px solid #aaa;
        margin:0 5px 0 0;
        width:20px;
        height:21px;
        text-align:center;
        cursor:pointer;
        background:url('<?php echo $this->baseUrl(); ?>/public/img/buttons/imprimir.gif') center center no-repeat;
    }
    .btn_imprimir:hover{
        background-color:#fff;
        border-top:1px solid #aaa;
        border-left:1px solid #aaa;
        border-right:1px solid #efefef;
        border-bottom:1px solid #efefef;
    }
    .paginaA4{
        width:auto;
        margin: 1.111cm 1cm 1cm 1.005cm;
        page-break-after: always;
    }
    .TituloMinC{
        font-size: 14px;
        text-transform: uppercase;
    }
    .TituloDoDocumento{
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }
    .DataDoDocumento{
        font-size: 10px;
    }
    .QntdRegistros{
        font-size: 12px;
    }
</style>


<div class="paginaA4">
    <div align="center">
        <img id="brasao" src="<?php echo $this->baseUrl(); ?>/public/img/brasaoArmas.jpg" alt="Ministério da Cultura"/>
        <br clear="all" /><span class="TituloMinC">Ministério da Cultura</span>
        <br clear="all" /><span class="TituloDoDocumento">Gerenciar Pareceres</span>
        <br clear="all" /><span class="DataDoDocumento">Data da impressão: <?php echo date('d/m/Y - H:i:s'); ?></span>
    </div>

    <?php if($this->qtdDocumentos != 0){ ?>
    <table class="tabela">
        <tr>
            <th align="center" nowrap>PRONAC</th>
            <th align="center" nowrap>Nome do Projeto</th>
            <th align="center" nowrap>Situação</th>
            <th align="center" nowrap>Nome do Proponente</th>
            <th align="center" width="105">Dt Consolida&ccedil;&atilde;o</th>
        </tr>	
        <?php foreach($this->dados as $pc){ ?>
        <tr>
            <td align="center"><?php echo $pc->PRONAC; ?></td>
            <td align="left" style="padding-left: 20px;"><?php echo $pc->NomeProjeto; ?></td>
            <td align="left" style="padding-left: 20px;"><?php echo $pc->Situacao; ?></td>
            <td align="left" style="padding-left: 20px;"><?php echo $pc->NomeProponente; ?></td>
            <td align="center" nowrap><?php echo $pc->DtConsolidacao; ?></td>
        </tr>
        <?php } ?>	
    </table>

    <?php } else { ?>
    <table class="tabela">
        <tr>
            <td align="center">Nenhum registro encontrado.</td>
        </tr>
    </table>
    <?php } ?>
    <br clear="all" />
</div>
<!-- ========== FIM CONTEÚDO ========== -->