<thead>
<tr class="titulo_tabela">
    <th>#</th>
    <th>
        <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=3&ordem=' . $this->paginacao['novaOrdem']; ?>">PRONAC</a>
    </th>
    <th>
        <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=4&ordem=' . $this->paginacao['novaOrdem']; ?>">Nome
            do Projeto</a></th>
    <th>
        <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=7&ordem=' . $this->paginacao['novaOrdem']; ?>">Tipo
            Readequa&ccedil;&atilde;o</a></th>
    <th>
        <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=6&ordem=' . $this->paginacao['novaOrdem']; ?>">Data
            Envio</a></th>
    <th>
        <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=8&ordem=' . $this->paginacao['novaOrdem']; ?>">Qtd.
            de dias aguardando distribui&ccedil;&atilde;o</a></th>
    <th style="width: 90px; text-align: center">Visualizar</th>
    <th style="width: 90px; text-align: center">Avaliar</th>
</tr>
</thead>
<tbody>
<?php $count = 1;
foreach ($this->dados as $d): ?>
    <tr>
        <td align="center" style="width: 1px;"><?php echo $count; ?></td>
        <td align="center">
            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index')); ?>?idPronac=<?php echo($d->idPronac); ?>"
               target="_blank">
                <?php echo $d->PRONAC; ?>
            </a>
        </td>
        <td><?php echo $d->NomeProjeto; ?></td>
        <td align="center"><?php echo $d->tpReadequacao; ?></td>
        <td align="center"><?php if ($d->dtEnvio == '') {
                echo '---';
            } else {
                echo Data::tratarDataZend($d->dtEnvio, 'Brasileira');
            } ?></td>
        <td style="width: 200px" align="center"><?php echo $d->qtAguardandoDistribuicao; ?></td>
        <td align="center">
            <a
                href="javascript:void(0)"
                class="btn-ver btn small waves-effect waves-light tooltipped white-text btn-secondary"
                idReadequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>"
                data-tooltip="Visualizar Readequa&ccedil;&atilde;o"
            >
                <i class="material-icons">visibility</i>
            </a>
        </td>
        <td align="center">
            <a
                href="javascript:void(0)"
                class="btn-avaliar btn small waves-effect waves-light tooltipped btn-primary"
                readequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>"
                pronac="<?php echo $d->PRONAC; ?>"
                nomeprojeto="<?php echo $d->NomeProjeto; ?>"
                data-tooltip="Receber, rejeitar ou devolver para o proponente"
            >
                <i class="material-icons">gavel</i>
            </a>
        </td>
    </tr>
    <?php $count++; ?>
<?php endforeach; ?>
</tbody>
