<table class="tabela tablesorter">
    <thead>
    <tr class="titulo_tabela">
        <th style="width: 80px;"><a
                href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel-readequacoes')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=3&ordem=' . $this->paginacao['novaOrdem']; ?>">PRONAC</a>
        </th>
        <th>
            <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel-readequacoes')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=4&ordem=' . $this->paginacao['novaOrdem']; ?>">Nome
                do Projeto</a></th>
        <th>
            <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel-readequacoes')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=10&ordem=' . $this->paginacao['novaOrdem']; ?>">Tipo
                de Readequa&ccedil;&atilde;o</a></th>
        <th style="width: 130px;" nowrap><a
                href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel-readequacoes')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=5&ordem=' . $this->paginacao['novaOrdem']; ?>">Dt
                Envio</a></th>
        <th style="width: 130px;" nowrap><a
                href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'painel-readequacoes')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&tipoFiltro=' . $this->filtro . '&pronac=' . $this->pronac . '&campo=6&ordem=' . $this->paginacao['novaOrdem']; ?>">Qtd
                dias aguardando distribui&ccedil;&atilde;o</a></th>

        <th>Visualizar</th>
        <?php if ($this->idOrgao == 91) { ?>
            <th style="width: 130px;">Superintend&ecirc;ncias do IPHAN</th>
        <?php } else { ?>
            <th style="width: 130px;">Parecerista</th>
        <?php } ?>
        <th style="width: 130px;">Encaminhar</th>
    </thead>
    <tbody>
    <?php foreach ($this->dados as $d): ?>
        <tr>
            <td align="center">
                <a href='<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index')); ?>?idPronac=<?php echo($d->idPRONAC); ?>'
                   target="_blank">
                    <?php echo $d->PRONAC; ?>
                </a>
            </td>
            <td><?php echo $d->NomeProjeto; ?></td>
            <td><?php echo $d->tpReadequacao; ?></td>
            <td align="center"><?php if ($d->dtEnvio == '') {
                    echo '---';
                } else {
                    echo Data::tratarDataZend($d->dtEnvio, 'Brasileira');
                } ?></td>
            <td align="center"><?php echo $d->qtDiasAguardandoDistribuicao; ?></td>
            <td align="center">
                <input type="button" class="btn_ver"
                       idReadequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>"/>
            </td>
            <td style="align: center">
                <?php
                //	   $p = new Projetos();
                //	   $dadosProjetos = $p->buscar(array('IdPRONAC = ?'=>$d->idPronac))->current();

                $outrasVinculadas = array(92, 93, 94, 95, 335); // Vinculadas exceto IPHAN
                if ($this->idOrgao == 91) { // especificidade do IPHAN
                    $o = new Orgaos();
                    $superindendencias = $o->buscarSuperintendencias();
                } else if (!in_array($this->idOrgao, $outrasVinculadas)) {
                    $a = new Agente_Model_DbTable_Agentes();
                    $Pareceristas = array();
                    $Pareceristas = $a->buscarPareceristasIphan($this->idOrgao, $d->Area, $d->Segmento);
                } else {
                    $a = new Agente_Model_DbTable_Agentes();
                    $Pareceristas = array();
                    $Pareceristas = $a->buscarPareceristas($this->idOrgao, $d->Area, $d->Segmento);
                }
                ?>
                <select name="tecnico" id="tecnico-<?php echo $d->idDistribuirReadequacao ?>"
                        class="select_simples comboTecnico">
                    <option value=""> - Selecione -</option>
                    <?php if ($this->idOrgao == 91): ?>
                        <?php foreach ($superindendencias as $superindendencia): ?>
                            <option
                                value="<?php echo $superindendencia->Codigo; ?>"><?php echo $superindendencia->Sigla; ?></option>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php foreach ($Pareceristas as $Parecerista): ?>
                            <option value="<?php echo $Parecerista->id; ?>"><?php echo $Parecerista->nome; ?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </td>
            <td>
                <a
                    href="javascript:void(0)"
                    class="btn-enviar enviarReadequacao btn small waves-effect waves-light tooltipped btn-primary"
                    idPronac="<?php echo $d->idPronac; ?>"
                    idDistRead="<?php echo $d->idDistribuirReadequacao; ?>"
                    idReadequacao="<?php echo $d->idReadequacao; ?>"
                    data-tooltip="Avaliar readequa&ccedil;&atilde;o"
                >
                    <i class="material-icons">send</i>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
