<script type="text/javascript">
    $(document).ready(function () {
        $("#btn_pesquisar").click(function () {
            $('#formPesquisa').submit();
        });

        $('.btn_imprimir').click(function () {
            $('#formImpressao').submit();
        });

        $('#btn-avaliar').click(function () {
            var id = $(this).attr('readequacao');
            window.location = "<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'form-avaliar-readequacao-cnic')); ?>?id=" + id;
        });
    });
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="alerta"></div>
<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <?php
                    $paginaAtual = "Avaliar Readequa&ccedil;&otilde;es";
                    ?>
                    <h1><?= $paginaAtual; ?></h1>

                    <?php
                    gerarNovoBreadCrumb(
                        [
                            [$paginaAtual => '']
                        ]
                    );
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-panel">
            <div id="conteudo">
                <form name="formPesquisa" id="formPesquisa"
                      action="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')); ?>"
                      method="get">
                    <table class="tabela">
                        <tr>
                            <th colspan="2">
                                Filtro de Pesquisa
                            </th>
                        </tr>
                        <tr class="divFiltroPesquisa">
                            <td class="destacar bold" width="60">PRONAC</td>
                            <td>
                                <input type="text" class="input_simples" name="pronac" maxlength="7"
                                       style="width: 70px;" value="<?php echo $this->pronac; ?>">
                                <input type="hidden" name="qtde" value="<?php echo $this->intTamPag; ?>">
                                <input type="button" name="btn_pesquisar" id="btn_pesquisar" class="btn_pesquisar"
                                       value="">
                            </td>
                        </tr>
                    </table>
                </form>

                <?php if (count($this->dados) > 0) { ?>
                    <!-- ============ PAGINAÇÃO ============ -->
                    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
                        <tbody>
                        <tr>
                            <td align="center">
                                <form name="form1" id="form1"
                                      action="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')); ?>"
                                      method="get">
                                    <?php if ($this->paginacao['pag'] > 1) { ?>
                                        <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                                               onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1' . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'">
                                    <?php } ?>
                                    <input id="btn_p_anterior" type="button"
                                        <?php if ($this->paginacao['pag'] <= 1) { ?> class="btn_p_anterior-off"
                                        <?php } else { ?>
                                            class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['pag'] - 1) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'"
                                        <?php } ?>>
                                    <input id="btn_p_proximo" type="button"
                                        <?php if ($this->paginacao['pag'] + 1 > $this->paginacao['totalPag']) { ?>
                                            class="btn_p_proximo-off"
                                        <?php } else { ?>
                                            class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['pag'] + 1) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'"
                                        <?php } ?>>
                                    <?php if ($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                                        <input class="btn_ultimo" id="btn_ultimo" type="button"
                                               onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['totalPag']) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'">
                                    <?php } ?>
                                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()"
                                                 class="input_simples">
                                        <?php for ($i = 1; $i <= $this->paginacao['totalPag']; $i++): ?>
                                            <option value="<?php echo $i; ?>" <?php if ($this->paginacao['pag'] == $i) echo "selected"; ?>><?php echo $i; ?>
                                                &nbsp;
                                            </option>
                                        <?php endfor; ?>
                                    </select>
                                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde"
                                                                      class="input_simples"
                                                                      value="<?php echo $this->intTamPag; ?>"><input
                                            type="submit" class="btn_recarregar" value="">
                                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo']; ?>">
                                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem']; ?>">
                                    <input type="hidden" name="pronac" value="<?php echo $this->pronac; ?>">
                                    <!--<input type="button" class="btn_imprimir">-->
                                </form>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <center>
                        <?php
                        echo $this->paginacao['inicio'] . " a ";
                        echo ($this->paginacao['pag'] - 1) * $this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                        echo " de " . $this->paginacao['total'] . " Projetos listados";
                        ?>
                    </center>
                    <!-- ========== FIM PAGINAÇÃO ========== -->
                <?php } ?>


                <?php if ($this->qtdRegistros > 0) { ?>
                    <table class="tabela tablesorter">
                        <thead>
                        <tr class="titulo_tabela">
                            <th>
                                <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&pronac=' . $this->pronac . '&campo=3&ordem=' . $this->paginacao['novaOrdem']; ?>">PRONAC</a>
                            </th>
                            <th>
                                <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&pronac=' . $this->pronac . '&campo=4&ordem=' . $this->paginacao['novaOrdem']; ?>">Nome
                                    do Projeto</a></th>
                            <th>
                                <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&pronac=' . $this->pronac . '&campo=5&ordem=' . $this->paginacao['novaOrdem']; ?>">Dt.
                                    Solicita&ccedil;&atilde;o</a></th>
                            <th>
                                <a href="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1&qtde=' . $this->paginacao['qtde'] . '&pronac=' . $this->pronac . '&campo=6&ordem=' . $this->paginacao['novaOrdem']; ?>">Tipo
                                    Solicita&ccedil;&atilde;o</a></th>
                            <th>Diligência</th>
                            <th>Avaliar</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->dados as $d) { ?>
                            <tr>
                                <td align="center">
                                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index')); ?>?idPronac=<?php echo($d->idPronac); ?>"
                                       target="_blank">
                                        <?php echo $d->PRONAC; ?>
                                    </a>
                                </td>
                                <td><?php echo $d->NomeProjeto; ?></td>
                                <td align="center"><?php echo Data::tratarDataZend($d->dtSolicitacao, 'Brasileira'); ?></td>
                                <td><?php echo $d->dsReadequacao; ?></td>
                                <td align="center">
                                    <?php echo $this->partial(
                                        'diligenciar/partial/diligenciar-table-column.phtml', 'proposta',
                                        array(
                                            'idPronac' => $d->idPronac,
                                            'situacao' => 'D41',
                                            'tpDiligencia' => 178,
                                        )
                                    );
                                    ?>
                                </td>
                                <td align="center">
                                    <a
                                            href="javascript:void(0)"
                                            id="btn-avaliar"
                                            class="btn-avaliar btn small waves-effect waves-light tooltipped btn-primary"
                                            readequacao="<?php echo Seguranca::encrypt($d->idReadequacao); ?>"
                                            pronac="<?php echo $d->PRONAC; ?>"
                                            nomeprojeto="<?php echo $d->NomeProjeto; ?>"
                                            data-tooltip="Avaliar readequa&ccedil;&atilde;o"
                                    >
                                        <i class="material-icons">gavel</i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>

                    <?php if (count($this->dados) > 0) { ?>

                        <!-- ============ PAGINAÇÃO ============ -->
                        <?php if ($this->qtdRegistros > 10) { //echo $this->dados; ?>
                            <center>
                                <?php
                                echo $this->paginacao['inicio'] . " a ";
                                echo ($this->paginacao['pag'] - 1) * $this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                                echo " de " . $this->paginacao['total'];
                                ?>
                            </center>
                            <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
                                <tbody>
                                <tr>
                                    <td align="center">
                                        <form name="form2" id="form2"
                                              action="<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')); ?>"
                                              method="get">
                                            <?php if ($this->paginacao['pag'] > 1) { ?>
                                                <input class="btn_inicio" id="btn_inicio" type="button"
                                                       class="btn_inicio"
                                                       onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=1' . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'">
                                            <?php } ?>
                                            <input id="btn_p_anterior" type="button"
                                                <?php if ($this->paginacao['pag'] <= 1) { ?> class="btn_p_anterior-off"
                                                <?php } else { ?>
                                                    class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['pag'] - 1) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'"
                                                <?php } ?>>
                                            <input id="btn_p_proximo" type="button"
                                                <?php if ($this->paginacao['pag'] + 1 > $this->paginacao['totalPag']) { ?>
                                                    class="btn_p_proximo-off"
                                                <?php } else { ?>
                                                    class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['pag'] + 1) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'"
                                                <?php } ?>>
                                            <?php if ($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                                                <input class="btn_ultimo" id="btn_ultimo" type="button"
                                                       onclick="location.href='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'analisar-readequacoes-cnic')) . '?pag=' . ($this->paginacao['totalPag']) . "&qtde=" . $this->paginacao['qtde'] . $this->paginacao['ordenacao'] . '&pronac=' . $this->pronac; ?>'">
                                            <?php } ?>
                                            Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()"
                                                         class="input_simples">
                                                <?php for ($i = 1; $i <= $this->paginacao['totalPag']; $i++): ?>
                                                    <option value="<?php echo $i; ?>" <?php if ($this->paginacao['pag'] == $i) echo "selected"; ?>><?php echo $i; ?>
                                                        &nbsp;
                                                    </option>
                                                <?php endfor; ?>
                                            </select>
                                            &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde"
                                                                              class="input_simples"
                                                                              value="<?php echo $this->intTamPag; ?>"><input
                                                    type="submit" class="btn_recarregar" value="">
                                            <input type="hidden" name="campo"
                                                   value="<?php echo $this->paginacao['campo']; ?>">
                                            <input type="hidden" name="ordem"
                                                   value="<?php echo $this->paginacao['ordem']; ?>">
                                            <input type="hidden" name="pronac" value="<?php echo $this->pronac; ?>">
                                            <!--<input type="button" class="btn_imprimir">-->
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <!-- ========== FIM PAGINAÇÃO ========== -->

                        <?php }
                    } ?>


                <?php } else { ?>
                    <table class="tabela">
                        <tr>
                            <td align="center">Nenhum registro encontrado.</td>
                        </tr>
                    </table>
                <?php } ?>
                <br clear="all"/>

                <!--    <form target="_blank" class="form" name="formImpressao" id="formImpressao" method="post" action='<?php echo $this->url(array('module' => 'readequacao', 'controller' => 'readequacoes', 'action' => 'imprimir-readequacoes-cnic')); ?>'>
        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo']; ?>">
        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem']; ?>">
        <input type="hidden" name="pronac" value="<?php echo $this->pronac; ?>">
    </form>-->

            </div>
        </div>
    </div>
</div>
