<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
			<div id="breadcrumb">
				<ul>
					<li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para Início">Início</a></li>
					<li class="last">Agentes Vinculados</li>
				</ul>
			</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
				<div id="titulo">
					<div>Agentes Vinculados<span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
				</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
	<div id="conteudo">


<!-- ========== INÍCIO DO SCRIPT PARA CONFIRMAÇÃO DE EXCLUSÃO ========== -->

				<script language="javascript">
				function confirmaExclusao(idAgente, cnpjcpf)
				{
					if(confirm('Deseja realmente desvincular o agente?'))
					{
						location.href = "<?php echo $this->url(array('controller' => 'desvincularagentes','action' => 'excluir')); ?>?cnpjcpf=" + cnpjcpf + "&id=" + idAgente;
					}
				}
				</script>


<!-- ========== FIM DO SCRIPT PARA CONFIRMAÇÃO DE EXCLUSÃO ========== -->



<!-- ========== INICIO DA TABELA DOS DADOS CONTENDO AS INFORMAÇÕES DA INSTITUIÇÃO ========== -->	
		<table class="tabela" summary="Esta tabela contém os dados da Instituição que contém os agentes que podem ser desvinculados">
					
			  <?php foreach($this->entidade as $tbentidade): ?>
			
				  		<table class="tabela" summary="Esta tabela contém os dados da Instituição que contém os agentes que podem ser desvinculados">



				  		<tr>
				    				<td class="titulo_tabela" tabindex="1"><strong>CNPJ/CPF:<?php echo $this->escape($tbentidade->CNPJCPF);?></strong> </td>
                                                                <?php $cpfCnpj =  trim(strlen($this->escape($tbentidade->CNPJCPF)))?>
                                                                <?php if ( $cpfCnpj == 11 ) { ?>
				   					<td class="titulo_tabela" tabindex="2"><strong><?php echo $this->escape($tbentidade->nomeentidade);?></strong></td>
                                                                <?php } else {?>
                                                                        <td class="titulo_tabela" tabindex="2"><strong>Nome da Instituição: <?php echo $this->escape($tbentidade->nomeentidade);?></strong></td>
                                                                <?php }?>
				 		</tr>

		</table>
				<?php endforeach;?>	
		</table>

<!-- ========== FIM DA TABELA DOS DADOS CONTENDO AS INFORMAÇÕES DA INSTITUIÇÃO ========== -->	



<!-- ========== INICIO DA TABELA DOS DADOS CONTENDO AS INFORMAÇÕES DOS AGENTES QUE PODEM SER DESVINCULADOS DA INSTITUIÇÃO ========== -->	
<form id="formCadastrar" name="formCadastrar" method="post" action="<?php echo $this->url(array('controller' => 'desvincularagentes','action' => 'desvincularagentes')); ?>?cpf=<?php echo $this->escape($tbvinculoagente->CNPJCPF);?>">
   		
   
<table class="tabela" summary="Esta tabela contém os dados dos Agentes pertencentes á Instituiçãoe e que podem ser desvinculados">
				<tr>
						<td colspan="5" class="titulo_tabela" tabindex="3">AGENTES VINCULADOS</td>
				</tr>
		  		<tr>
		    			<th tabindex="4">CPF</th>
		    			<th tabindex="5">Nome</th>
		    			<th tabindex="6">Visão</th>
		    			<th tabindex="7">Desvincular</th>
		  		</tr>
	<?php foreach($this->vinculoagente as $tbvinculoagente): ?>
				<tr>
							<td tabindex="8"><?php echo $this->escape($tbvinculoagente->CNPJCPF);?></td>
							<td tabindex="9"><?php echo $this->escape($tbvinculoagente->NomeAgente);?></td>
							<td tabindex="10"><?php echo $this->escape($tbvinculoagente->vinculo);?></td>	
							<td tabindex="11" class="centro"><a href="javascript:confirmaExclusao('<?php echo $tbvinculoagente->idAgente; ?>', '<?php echo $_GET['cnpjcpf'];?>');">Excluir</a></td>			
				</tr>
		
	<?php endforeach;?>
</table>

<!-- ========== FIM DA TABELA DOS DADOS CONTENDO AS INFORMAÇÕES DOS AGENTES QUE PODEM SER DESVINCULADOS DA INSTITUIÇÃO ========== -->	
		
	
	</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
	<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
			<br clear="all" />
