        <form name="formulario" action="#">
                <tr>
                    <th colspan="0" class="centro">Dados da Capta&ccedil;&atilde;o</th>
                </tr>
                <tr>
                    <td colspan="0" align="center">CNPJ/CPF:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>   
                </tr>
                <tr class="destacar">
                    <td colspan="0" align="center">DATAS</td>              
                </tr>
                <tr>
                    <td colspan="0" align="center">RECIBO:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                    <td colspan="0" align="center">MINC:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                </tr>                
                <tr>
                    <td colspan="0" align="center">TIPO DE APOIO:</td>
                    <td colspan="0">
                        <select name='uf' class='select_simples focus w200'>
                            <option value='' selected>--Selecione--</option>
                            <option value='SSS'>1.DOA&Ccedil;&Atilde;O</option>
                            <option value='SSS'>2.PATROC&Iacute;NIO</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="0" align="center">VALOR:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                </tr>
                <tr class="destacar">
                    <td colspan="0" align="center">SALDO DO PROJETO (R$)</td>
                </tr>
                <tr>
                    <td align="center">APROVADO:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                </tr>
                <tr>
                    <td align="center">CAPTADO:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                </tr>
                <tr>
                    <td align="center">A CAPTAR:</td>
                    <td colspan="0">
                        <input name='Processo' type='text' class='input_simples w200 focus'/>
                    </td>
                </tr>               
            </table>            
            <table class="tabela" border="0" cellpadding="0" cellspacing="1" style="margin-top: 10px;">
                <tr>
                    <td colspan="0" class="centro">
                        <input class="btn_salvar" id="btn_salvar" value="" type="button" onclick="window.location='index.html';"/>
                        <input class="btn_imprimir" id="btn_imprimir" value="" type="button" onclick="window.location='index.html';"/>
                        <input class="btn_cancelar" id="btn_cancelar" value="" type="button" onclick="window.location='index.html';"/>
                    </td>
                </tr>
            </table>
        </form>