<?php
/**
 * Rodapé da Área de Login
 * @author Equipe RUP - Politec
 * @since 26/05/2010
 * @version 1.0
 * @package application
 * @subpackage application.layout
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

        <!-- ========== INÍCIO RODAPÉ ========== -->
        <div id="rodape">
            <!-- <div><strong>Salic - Sistema de Apoio às Leis de Incentivo à Cultura</strong> - Central de Atendimento: (61) 2134-3454 - <a href="mailto:suporte@salic.com.br?Subject=Suporte%20Salic" title="Enviar e-mail para suporte@salic.com.br">suporte@salic.com.br</a><br /></div> -->
            <div><strong>MINIST&Eacute;RIO DA CULTURA</strong><!-- - Atendimento ao Usu&aacute;rio: (61) 2024-2115 - <a href="mailto:suporte.salic@cultura.gov.br?Subject=Suporte%20Salic" title="Enviar e-mail para suporte.salic@cultura.gov.br">suporte.salic@cultura.gov.br</a>--><br /></div>
        </div>
        <!-- ========== FIM RODAPÉ ========== -->
        <div class="versao"><?php echo $this->vcs(); ?></div>
    </body>
</html>