<div class="col s2">
	<div class="top"></div>
	<div id="qm0" class="qmmc">
		<a class="sanfona" href="#" title="Ir para Estrutura de P&aacute;ginas">Estrutura de P&aacute;ginas</a>
		<div class="sanfonaDiv sumir">
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'pagina-simples'), '', true); ?>" title="Ir para P&aacute;gina Simples">P&aacute;gina Simples</a>
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'pagina-menu-lateral'), '', true); ?>" title="Ir para P&aacute;gina com Menu Lateral">P&aacute;gina com Menu Lateral</a>
		</div>

		<a class="sanfona" href="#" title="Ir para Menus">Menus</a>
		<div class="sanfonaDiv sumir">
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'menu-lateral'), '', true); ?>" title="Ir para Menu Lateral">Menu Lateral</a>
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'menu-abas1'), '', true); ?>" title="Ir para Menu de Abas">Menu de Abas</a>
		</div>

		<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'mensagens'), '', true); ?>" title="Ir para Mensagens">Mensagens</a>

		<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'formularios'), '', true); ?>" title="Ir para Formul&aacute;rios">Formul&aacute;rios</a>

		<a class="sanfona" href="#" title="Ir para M&aacute;scaras">M&aacute;scaras</a>
		<div class="sanfonaDiv sumir">
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'mascaras-js'), '', true); ?>" title="Ir para M&aacute;scaras em JavaScript">M&aacute;scaras em JavaScript</a>
			<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'mascaras-php'), '', true); ?>" title="Ir para M&aacute;scaras em PHP">M&aacute;scaras em PHP</a>
		</div>

		<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'tabelas'), '', true); ?>" title="Ir para Tabelas">Tabelas</a>

		<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'grids'), '', true); ?>" title="Ir para Grids">Grids</a>

		<a class="no_seta" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'planilha'), '', true); ?>" title="Ir para Planilha">Planilha</a>

		<a class="no_seta last" href="<?php echo $this->url(array('module' => 'manual', 'controller' => 'manual-layout', 'action' => 'modal'), '', true); ?>" title="Ir para Modal">Modal</a>

	</div>
	<br clear="left" class="br" />
	<div class="bottom"></div>
	<div id="espaco"></div>
</div>
<!-- ========== FIM MENU ========== -->
