<style>
label.error{color:red;}
</style>
<script type="text/javascript">

        $(document).ready( function() {
	$("#gerarSenha").validate({
		// Define as regras
		rules:{
                        cpf:{
				// campoNome sera obrigatório (required) e tera tamanho minimo (minLength)
				required: true,
                                minlength: 14,
                                verificaCPF: true
			},
			nome:{
				// campoNome sera obrigatório (required) e tera tamanho minimo (minLength)
				required: true, minlength: 5
			},
			email:{
				// campoEmail sera obrigatório (required) e precisara ser um e-mail valido (email)
				required: true, email: true, minlength: 2
			}

		},
		// Define as mensagens de erro para cada regra
		messages:{
                        cpf:{
				required: " Informe o CPF",
				minlength: " O CPF deve conter no mínimo 11 caracteres",
                                verificaCPF: " Informe CPF v&aacute;lido"
			},
			nome:{
				required: " Informe o Nome",
				minlength: " O nome deve conter no mínimo 5 caracteres"
			},
			email:{
				required: " Informe o E-mail",
				email: " Digite um e-mail válido",
                                minlength: " O nome deve conter no mínimo 2 caracteres"
			}
		}
	});
});

    $(document).ready(function() {
        $("#cpf").blur(function() {
            var cpfLimpo = replaceAll(replaceAll(replaceAll($(this).val(),".",""),"-",""),"/","");
            $.ajax({ //funcao jquery para enviar os formularios via ajax
                type: "POST",
                dataType: 'json',
                url:  "<?php echo $this->url(array('module'=>'default', 'controller' => 'manterusuario', 'action' => 'gerarsenha')); ?>",
                data: {
                    cpf : cpfLimpo
                },
                error:function(data) {
                    //alert(data);
                },
                success: function(data)
                {
                    if(!data.error) {

                    if ( data.semdados )
                    {
                        $('#cpfRetorno').html('<font color="red">N&atilde;o encontrado</font>');
                        $('#nome').val('');
                        $('#email').val('');
                    }
                    else
                    {
                        $('#cpfRetorno').html('');
                        $('#nome').val(data.Nome);
                        $('#email').val(data.Email);
                    }
                }
                else
                {
                    $('#cpfRetorno').html('<font color="red">N&atilde;o encontrado</font>');
                }

            }
        });
        });
    });
function replaceAll(string, token, newtoken) {
	while (string.indexOf(token) != -1) {
 		string = string.replace(token, newtoken);
	}
	return string;
}

    function carregaCampo(cpf){

   }


</script>


<!-- ========== INï¿½CIO BREADCRUMB (LINKS TOPO) ========== -->
<div style="display:none" id="confirm">Por favor, informe seu email!</div>
<div style="display:none" id="dialog-alert2"></div>
<div style="display:none" id="confirmInforma">Por favor, digite seu email corretamente!</div>
<div id="breadcrumb">

<ul>
<li class="first"><a href="<?php echo $this->url(array('controller' => 'cadastrarusuario', 'action' => 'index')); ?>">In&iacute;cio</a></li>
<li class="last">Cadastrar Usuário</li>
</ul>

</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INï¿½CIO Tï¿½TULO ========== -->

<div id="titulo">
<div>Regerar Senha Proponente<span></span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>

</div>
<!-- ========== FIM Tï¿½TULO ========== -->



<!-- ========== INï¿½CIO CONTEï¿½DO ========== -->

	<div id="conteudo">
<fieldset><legend>Informações</legend>

            <form method="POST" action="<?php echo $this->url(array('controller' => 'manterusuario', 'action' => 'gerarsenha')); ?>" name="gerarSenha" id="gerarSenha">
                <center>
                    <table class="tabela">
                    <thead>
                        <tr>
                            <th colspan="2">Regerar Senha Proponente</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td align="left">CPF </td>
                            <td align="left"><input value="" onblur="mascaraCnpjCpf(this);"  onkeydown="mascaraCnpjCpf(this);" onkeypress="mascaraCnpjCpf(this);" onkeyup="mascaraCnpjCpf(this);" maxlength="14" class="input_simples" type="text" name="cpf" id="cpf"  /><div id="cpfRetorno" ></div> </td>
                        </tr>
                        <tr>
                            <td align="left">Nome Completo </td>
                            <td align="left"><input value="" maxlength="200" class="input_simples" type="text" name="nome" id="nome"  style="height: 15px;width: 300px;"  /> </td>
                        <tr>
                            <td align="left">E-mail </td>
                            <td align="left"><input value="" maxlength="200" class="input_simples" type="text" name="email" id="email"  style="height: 15px;width: 300px;"  /> </td>
                        </tr>
                        <tr>
                            <td align="center" colspan="2">
                            <input type="hidden" id='alterar' name="alterar" value="alterar"/>
                            <input id='btIncluir' type='submit' value='' class='btn_enviar enviar'/>
                            <input id='btLimpar' type='reset' value='' class='btn_limpar enviar'  />
                            <input id='btCancelar' type='button' value='' class='btn_cancelar enviar' onClick="history.go(-1)" onkeypress=" " />
                            </td>
                        </tr>
                    </tbody>
                </table>
                </center>

            </form>
</fieldset>

        </div>


<!-- ========== FIM CONTEï¿½DO ========== -->



<!-- ========== INï¿½CIO RODAPï¿½ DO CONTEï¿½DO ========== -->
	<div id="rodapeConteudo"><span></span></div>

<!-- ========== FIM RODAPï¿½ DO CONTEï¿½DO ========== -->
			<br clear="all" />




</body>
</html>
