<script>
    function incluirTermo(orgao){

            location.href="<?php echo $this->url(array('controller' => 'mantertermodecisao', 'action' => 'incluirtermodecisao')); ?>";
    }
</script>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial">In&iacute;cio</a></li>
        <li>Administrativo</li>
        <li class="last">Manter termo de decis&atilde;o</li>
    </ul>
</div> <!-- final: #breadcrumb -->

<!-- início: #titulo -->
<div id="titulo">
        <div>Manter termo de decis&atilde;o <!-- <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span> --></div>
</div>
<!-- final: #titulo -->

<!-- início: área principal #conteudo -->
<div id="conteudo">
   
</div>
<!-- final: conteúdo principal #conteudo -->

<!-- início: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />