<?php echo $this->partial("analise/inc/menususpenso.phtml", $this); ?>

<?php
$IncluirAvaliacao = $this->url(array('module' => 'admissibilidade', 'controller' => 'admissibilidade', 'action' => 'incluiravaliacao'));
?>
<style>
    .modal.bottom-sheet {
        max-height: 70%;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>An&aacute;lise de adequa&ccedil;&atilde;o de Projeto</h1>

                    <?php
                    gerarNovoBreadCrumb(
                        [
                            ['Listar projetos' => ['module' => 'analise','controller' => 'analise','action' => 'listarprojetos']],
                            ['An&aacute;lise de adequa&ccedil;&atilde;o de Projeto' => '']
                        ]
                    );
                    ?>
                </div>

                <div class="col s12 m3 l2 right-align">
                    <a href="/analise/analise/listarprojetos"
                       title="Voltar para lista de projetos"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle">
                        <i class="material-icons">undo</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="content">
            <div id="container-vue">
                <salic-proposta-diff idpreprojeto="<?= $this->idPreProjeto; ?>" tipo="<?= $this->tipo; ?>"></salic-proposta-diff>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.avaliarProposta').click(function () {
            $('#preProjeto').attr('action', '<?php echo $IncluirAvaliacao;?>');
            $('#preProjeto').submit();
        });
    });
</script>


<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.1.0/addon/merge/dep/diff_match_patch.js" type="text/javascript"></script>
<script src="/public/js/jquery.pretty-text-diff.js" type="text/javascript"></script>
<script src="http://momentjs.com/downloads/moment-with-locales.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>

<script src="/public/js/componentes/salic-table-easy.js" type="text/javascript"></script>
<script src="/public/js/componentes/salic-texto-simples.vue.js" type="text/javascript"></script>

<script src="/public/scripts/proposta/visualizar/salic-proposta-diff.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-identificacao.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-documentos.vue.js" type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-fontes-de-recursos.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-historico-avaliacoes.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-local-realizacao-deslocamento.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-planilha-orcamentaria.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-plano-distribuicao.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-detalhamento-plano-distribuicao.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/proposta/visualizar/salic-proposta-custos-vinculados.vue.js"
        type="text/javascript"></script>
<script src="/public/scripts/agente/visualizar/salic-agente-proponente.vue.js" type="text/javascript"></script>
<script src="/public/scripts/autenticacao/index/salic-autenticacao-usuario.vue.js" type="text/javascript"></script>


<script type="text/javascript">

    new Vue({
        el: '#container-vue'
    });

</script>