<?php include_once('inc/menu.inc.php')?>

<script>
$(document).ready(function (){
    $('#abrir_fechar').click(function(){
        $('#tramitacao').toggle('slow');
    });
});
</script>

<!----------------------------------Bloco de Informações: Ultima Tramitação-------------------------------------------------------- -->

<div id="titulo"><div>Ultima Tramitação</div>
</div>

<div id="conteudo">

    <div id="miolo">

        <table class="tabela">
            <tr>
                <td>
                    <input id="abrir_fechar" class="btn_adicionar" type="button" />Ultima Tramitação
            </tr>
        </table>
        <div id="tramitacao" style="display:none">
            <table class="tabela">
                <tr class="titulo_tabela">
                    <th colspan="6">Última Tramitação</th>
                </tr>
                <tr>
                    <th>Emissor</th>
                    <th>Data de Envio</th>
                    <th>Estado</th>
                    <th>Destino</th>
                    <th>Receptor</th>
                    <th>Dt. Recebimento</th>
                </tr>
                <?php if (empty($this->dadosprojeto)) {
                    ?>
                <tr>
                    <td colspan="8" align= "center">Informação não cadastrada no projeto!</td>
                </tr>
                    <?php }
                else {?>
                    <?php foreach ($this->dadosprojeto as $tbdadosprojeto): ?>
                <tr>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->Emissor);?></td>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->DtTramitacaoRecebida);?></td>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->Situacao);?></td>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->Destino);?></td>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->Receptor);?></td>
                    <td align="center"><?php echo $this->escape($tbdadosprojeto->DtTramitacaoRecebida);?></td>
                </tr>
                    <?php endforeach;?>
                    <?php }?>
            </table>
        </div>

    </div>
</div>
<br>


<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->


<br clear="all" />