export const SET_PROJETO = 'SET_PROJETO';
export const SET_PROPONENTE = 'SET_PROPONENTE';
export const SET_PLANILHA_HOMOLOGADA = 'SET_PLANILHA_HOMOLOGADA';
export const SET_PLANILHA_ORIGINAL = 'SET_PLANILHA_ORIGINAL';
export const SET_PLANILHA_READEQUADA = 'SET_PLANILHA_READEQUADA';
export const SET_PLANILHA_AUTORIZADA = 'SET_PLANILHA_AUTORIZADA';
export const SET_PLANILHA_ADEQUADA = 'SET_PLANILHA_ADEQUADA';
export const SET_TRANSFERENCIA_RECURSOS = 'SET_TRANSFERENCIA_RECURSOS';
