<table id="listagemHomologacao">
    <thead>
    <tr>
        <th rowspan="2">&nbsp;</th>
        <th rowspan="2">PRONAC</th>
        <th rowspan="2">Nome do Projeto</th>
        <th rowspan="2">Enquadramento</th>
        <th colspan="2" class="center-align">Per&iacute;odo de Execu&ccedil;&atilde;o</th>
        <th rowspan="2">Nr.Reuni&atilde;o</th>
        <th rowspan="2">Vl.Homologado</th>
        <th rowspan="2">A&ccedil;&otilde;es</th>
    </tr>
    <tr>
        <th class="center-align">Dt.Inicio</th>
        <th class="center-align">Dt.Final</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script src="/public/js/jquery-1.12.4.min.js"></script>
<script src="/public/js/moment.js"></script>
<script type="text/javascript" src="/public/scripts/layout/datatables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/public/css/layout/datatables.min.css"/>
<script type="text/javascript">
    (function (global, factory) {
        if (typeof define === 'function' && define.amd) {
            define(['../numeral'], factory);
        } else if (typeof module === 'object' && module.exports) {
            factory(require('../numeral'));
        } else {
            factory(global.numeral);
        }
    }(this, function (numeral) {
        numeral.register('locale', 'pt-br', {
            delimiters: {
                thousands: '.',
                decimal: ','
            },
            abbreviations: {
                thousand: 'mil',
                million: 'milhões',
                billion: 'b',
                trillion: 't'
            },
            ordinal: function () {
                return '$';
            },
            currency: {
                symbol: 'R$ '
            }
        });
    }));
    numeral.locale('pt-br');

    (function ($) {
        $3(document).ready(function () {
            $3('.modal').modal();
            var listagemHomologacao = $('#listagemHomologacao').DataTable({

                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                },
                "ajax": {
                    url: "/projeto/homologacao/listar/",
                    data: {},
                    type: "POST"
                },
                "autoWidth": false,
                "serverSide": true,
                "columnDefs": [
                    { "width": "30%", "targets": 2 },
                    {"className": "dt-center", "targets": [0,1,3,4,5,6,7,8]},
                    {'bSortable': false, 'aTargets': [0, 8]},
                ],
                "searchDelay": 350,
                "columns": [
                    {
                        "targets": 0,
                        "data": null,
                        "name": "IdPRONAC",
                        render: (data, type, row, index) => {
                            return index.row+1;
                        }
                    },
                    {
                        "targets": 1,
                        "data": null,
                        "name": "Pronac",
                        render: function (data) {
                            return '<a class="waves-effect waves-dark btn white black-text" href="/default/consultardadosprojeto?idPronac='+ data.IdPRONAC +'" target="_blank">' + data.Pronac + '</a>'
                        }
                    },
                    {
                        "name": "NomeProjeto",
                        "data": "NomeProjeto"

                    },
                    {
                        "name": "Enquadramento",
                        "data": "Enquadramento"

                    },
                    {
                        "targets": 4,
                        "data": null,
                        "name": "DtInicioExecucao",
                        render: function (data) {
                            return moment(data.DtInicioExecucao).format('DD/MM/YYYY');
                        }
                    },
                    {
                        "targets": 5,
                        "data": null,
                        "name": "DtFimExecucao",
                        render: function (data) {
                            return moment(data.DtFimExecucao).format('DD/MM/YYYY');
                        }
                    },
                    {
                        "name": "NrReuniao",
                        "data": "NrReuniao"
                    },
                    {
                        "data": null,
                        "name": "vlHomologado",
                        render:  function (data) {
                            return numeral(parseFloat(data.vlHomologado)).format('$0,0.00');
                        }
                    },
                    {
                        "targets": 8,
                        "data": null,
                        render: function (data) {
                            var homologar = '<button data-ajax-modal-full="true" class="btn small waves-effect waves-light btn-primary" data-ajax-modal="/projeto/homologacao/homologar/id/'+ data.IdPRONAC +'"><i class="material-icons">assignment_turned_in</i></button>';
                            var visualizarParecer = '<button data-ajax-modal-full="true" class="btn small waves-effect waves-light btn-secondary" data-ajax-modal="/projeto/homologacao/visualizar/id/'+ data.IdPRONAC +'"><i class="material-icons">visibility</i></button>';
                            var diligenciar = '<a data-delay="50" data-position="top" data-tooltip="Dilig&ecirc;nciar" class="btn small waves-effect waves-light tooltipped" href="/proposta/diligenciar/listardiligenciaanalista/idPronac/'+ data.IdPRONAC +'/situacao/D25/tpDiligencia/181"><i class="material-icons">warning</i></a>';
                            var homologacaoFluxo= '<a data-delay="50" data-position="top" data-tooltip="Iniciar fluxo de Homologação" class="btn btn-primary small tooltipped" href="/projeto/homologacao/iniciar-fluxo-assinatura?idPronac=' + data.IdPRONAC + '"><i class="material-icons">edit</i></a>';

                            return homologar + visualizarParecer + diligenciar + homologacaoFluxo;
                        }
                    }
                ]
            });
        });
    }($.noConflict(true)));
</script>
