<div class="row">
    <div class="col s12">
        <table class="bordered striped highlight" style="width: 100%;">
            <thead>
            <tr>
                <th rowspan="2" class="center-align">#</th>
                <th rowspan="2" data-field="id" class="center-align">PRONAC</th>
                <th rowspan="2" data-field="id" class="center-align">Nome do Projeto</th>
                <th rowspan="2" data-field="teste" class="center-align">Enquadramento</th>
                <th colspan="2" data-field="teste2" class="center-align">Per&iacute;odo de Execu&ccedil;&atilde;o</th>
                <th rowspan="2" data-field="teste3" class="center-align">Nr.Reuni&atilde;o</th>
                <th rowspan="2" data-field="teste3" class="center-align">Vl.Homologado</th>
                <!-- <th rowspan="2" data-field="teste3" class="center-align">Visualizar pareceres</th>
                <th rowspan="2" data-field="teste3" class="center-align">t</th>
                <th rowspan="2" data-field="teste3" class="center-align">Dilig&ecirc;nciar</th>
                <th rowspan="2" data-field="teste3" class="center-align">Gerar documento</th>
                <th rowspan="2" data-field="teste3" class="center-align">Encaminhar</th> -->
                <th rowspan="2" data-field="teste3" class="center-align" style="width: 220px;">A&ccedil;&otilde;es</th>
            </tr>
            <tr>
                <th data-field="id" class="center-align">Dt.Inicio</th>
                <th data-field="id" class="center-align">Dt.Final</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->arrResult as $int => $arrValue): ?>
                <tr>
                    <td class="center-align"><?php echo $int + 1; ?></td>
                    <td class="center-align"><a
                            href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index')) . "?idPronac={$arrValue['IdPRONAC']}"; ?>"
                            target="_blank"><u><?php echo $arrValue['Pronac']; ?></td>
                    <td class="left-align"><?php echo $arrValue['NomeProjeto']; ?></td>
                    <td class="center-align"><?php echo $arrValue['Enquadramento']; ?></td>
                    <td class="center-align"><?php echo reset(explode(' ', Data::dataBrasileira($arrValue['DtInicioExecucao']))); ?></td>
                    <td class="center-align"><?php echo reset(explode(' ', Data::dataBrasileira($arrValue['DtInicioExecucao']))); ?></td>
                    <td class="center-align"><?php echo $arrValue['NrReuniao']; ?></td>
                    <td class="right-align"><?php echo 'R$ ' . number_format($arrValue['vlHomologado'], 2, ',', '.'); ?></td>
                    <td class="center-align">
                        <a data-ajax-modal="<?php echo $this->url(array('module' => 'projeto', 'controller' => 'homologacao', 'action' => 'homologar', 'id' => $arrValue['IdPRONAC']), null, true); ?>"
                           href="javascript:void(0);"
                           data-ajax-modal-full="true"
                           class="btn small waves-effect waves-light tooltipped btn-primary" data-position="top"
                           data-delay="50" data-tooltip="Homologar projeto"><i class="material-icons">assignment_turned_in</i></a>
                        <a data-ajax-modal="<?php echo $this->url(array('module' => 'projeto', 'controller' => 'homologacao', 'action' => 'visualizar', 'id' => $arrValue['IdPRONAC']), null, true); ?>"
                           href="javascript:void(0);"
                           data-ajax-modal-full="true"
                           class="btn small waves-effect waves-light tooltipped btn-secondary" data-position="top"
                           data-delay="50" data-tooltip="Visualizar pareceres"><i class="material-icons">visibility</i></a>
                        <a href="<?php echo $this->url(
                            array(
                                'module' => 'proposta',
                                'controller' => 'diligenciar',
                                'action' => 'listardiligenciaanalista',
                                'idPronac' => $arrValue['IdPRONAC'],
                                'situacao' => 'D25',
                                'tpDiligencia' => '181'), null, true); ?>"
                           target="_blank"
                           class="btn small waves-effect waves-light tooltipped" data-position="top"
                           data-delay="50" data-tooltip="Dilig&ecirc;nciar"><i class="material-icons">warning</i></a>
                        <!--                        <a href="javascript:$3.redirect('-->
                        <?php //echo $this->url(arr76ay('module' => 'admissibilidade', 'controller' => 'mensagem', 'action' => 'responder', 'id' => $arrValue['idMensagemProjeto'], 'idPronac' => $this->idPronac), null, true); ?><!--');"-->
                        <!--                            class="btn small waves-effect waves-light tooltipped" data-position="top"-->
                        <!--                            data-delay="50" data-tooltip="Gerar documento"><i class="material-icons">insert_drive_file</i></a>-->
                        <a data-ajax-modal="<?php echo $this->url(array('module' => 'projeto', 'controller' => 'homologacao', 'action' => 'encaminhar', 'id' => $arrValue['IdPRONAC']), null, true); ?>"
                           data-ajax-modal-full="true"
                           class="btn small waves-effect waves-light tooltipped btn-info" data-position="top"
                           data-delay="50" data-tooltip="encaminhar"><i
                                class="material-icons">forward</i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <!--                                                                                                                                                        /?idPronac=203042&idProduto=62&situacao=B11&tpDiligencia=124-->
            </tbody>
        </table>
    </div>
</div>
