<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript">
//    $(document).ready(function(){
//        window.print();
//    });
</script>

<style type="text/css">
    body {
        margin:0;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        color:#000;
        line-height:14pt;
    }
    a:link, a:active, a:visited {
        text-decoration:underline;
    }
    a:hover {
        text-decoration:none;
    }
    .tabela { /* tamanho de tabelas com registros */
        margin:10px auto;
        width:97%;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #CCC solid;
    }
    table td {
        background:#fff;
        padding:4px;
        color:auto;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px solid #bbb;
    }
    table tr.destacar td, table td.destacar {
        background:#e2e2e2;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
    }
    table th {
        background:#cccccc;
        padding:4px;
        text-transform:uppercase;
        font-size:11px;
        border: 1px solid #bbb;
    }
    #brasao{
        width : 85px;
        height: 86px;
    }
    legend{
        font-size:13px;
        font-weight: bold;
    }
    .btn_imprimir{
        border-top:1px solid #efefef;
        border-left:1px solid #efefef;
        border-right:1px solid #aaa;
        border-bottom:1px solid #aaa;
        margin:0 5px 0 0;
        width:20px;
        height:21px;
        text-align:center;
        cursor:pointer;
        background:url('<?php echo $this->baseUrl(); ?>/public/img/buttons/imprimir.gif') center center no-repeat;
    }
    .btn_imprimir:hover{
        background-color:#fff;
        border-top:1px solid #aaa;
        border-left:1px solid #aaa;
        border-right:1px solid #efefef;
        border-bottom:1px solid #efefef;
    }
    .paginaA4{
        width:auto;
        margin: 1.111cm 1cm 1cm 1.005cm;
        page-break-after: always;
        /*min-height: 3508px;*/
    }

    .tag_pre {
	overflow-x:auto;
	white-space:-moz-pre-wrap !important;
	white-space:-pre-wrap;
	white-space:-o-pre-wrap;
	white-space:pre-wrap;
	word-wrap: break-word;
    }
</style>

<div class="conteudoImprimivel" id="conteudoImprimivel">
    <div class="paginaA4">

        <?php if ($this->registros->count() > 0){ ?>
        <table class="tabela">
            <tr>
                <th colspan="4">Liberar conta bancária</th>
            </tr>
            <tr class="destacar">
                <td width="10%" align="center">PRONAC</td>
                <td width="50%">NOME DO PROJETO</td>
                <td width="10%" align="center">INABILITADO</td>
                <td width="10%" align="center" nowrap>CERTID&Otilde;ES NEGATIVAS</td>
            </tr>
            <?php foreach($this->registros as $projeto){ ?>
            <tr>
                <td align="center"><?php echo $projeto['Pronac'];?></td>
                <td><?php echo $projeto['NomeProjeto'];?></td>
                <td align="center">
                    <?php echo $projeto['Inabilitado'];?>
                </td>
                <td align="center">
                    <?php if ($projeto['Certidao'] == 'VENCIDA' || $projeto['Cadin'] == "CADIN PENDENTE"): ?>
                            <?php echo ($projeto['Certidao'] == 'VENCIDA') ? $projeto['Certidao'] : $projeto['Cadin'];?>
                    <?php else: ?>
                            <?php echo $projeto['Certidao'];?>
                    <?php endif;?>
                </td>
            </tr>
            <?php } ?>
        </table>
        <?php } else { ?>
        <table class="tabela">
            <tr>
                <td align="center" style="font-size: 15px;">Nenhum registro encontrado</td>
            </tr>
        </table>
        <?php } ?>
    </div>
</div>
