<?php
$historicoLink = $this->url(array('controller' => 'verificarreadequacaodeprojeto', 'action' => 'historico'));
?>

<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second">Acompanhamento</li>
        <li class="last">Verificar readequa&ccedil;&atilde;o de projeto</li>
    </ul>
</div>


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Verificar readequa&ccedil;&atilde;o de projeto</div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <div id="erro" class="sumir">Dados obrigatórios não preenchidos!</div>
    <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/public/js/projetosGerenciar.js'></script>

    <div id="dialog-alert"></div>
    <div style="width:100%; margin: 0 auto;">
        <table class="tabela">
            <tr>
                <th style="text-align:left; padding-left:2%" colspan="2">TIPOS DE READEQUAÇÕES</th>
                <th width="150px" align="center">Qntd de Projetos</th>
            </tr>
        </table>   

	<!-- MODAL PARA ENCAMINHAMENTO -->
	<?php foreach($this->AnaliseGeral as $AnaliseGeral): ?>
		
            <script type="text/javascript">

                window.document.body.onpaste = function() { return false; }; //Ctrl+V
                
		$(document).ready(function(){

                    $('.salvarencaminhamento<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').click(function(){
                        if($.trim($(this).parent().parent().find("input[name=AgenteId]").val()) == ''){
                            $("#erro").dialog({
                                title : 'Alerta',
                                resizable: false,
                                width:300,
                                height:150,
                                modal: true,
                                autoOpen:false,
                                buttons: {
                                    'OK': function() {
                                        $(this).dialog('close');
                                    }
                                }
                            });
                            $("#erro").dialog('open');
                        } else {
                            $(this).parent().parent().parent().find('form').submit();
                        }
                    });
			  	
                    $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#passaValor').change(function(){

                        var idorgao = $(this).val();
                        $.ajax({
                            url : '<?php echo $this->url(array('controller' => 'verificarreadequacaodeprojeto', 'action' => 'verificarreadequacaodeprojetocoordacompanhamento')); ?>',
                            data :
                            {
                                idorgao : idorgao,
                                verifica : 'a'
                            },
                            success: function(data){
                                    $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val('');
                                    var recebe = $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#recebeValor');
                                    if(data.resposta){
                                        recebe.html('');
                                        recebe.append("<option value=''>Selecione o agente</option>");
                                        for ( i in data.conteudo)
                                        {
                                            recebe.append("<option value='"+data.conteudo[i].idAgente+"/"+data.conteudo[i].idperfil+"'>"+data.conteudo[i].Perfil+" - "+data.conteudo[i].usu_nome+"</option>");
                                        }
                                    }
                                    else{
                                        recebe.html('');
                                        recebe.append("<option value=''>Nenhum registro encontrado</option>");
                                    }
                            },
                            type : 'post'
                            ,dataType : 'json'
                        });
                    });
		  	
                    $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#recebeValor').change(function(){

                    var perfil = $(this).val().split('/');
                    $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val(perfil[1]);
                    $('#encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgenteId').val(perfil[0]);
                });

            });
      </script>
		
        <div style="display:none;" id="encaminhar<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>" title="Encaminhar projeto para análise" >
            <form name="formencaminhar" id="form<?php echo $AnaliseGeral->ID_PRONAC; ?>" action="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/encaminhacoordacompanhamento" method="post" onsubmit="return validaForm()">

                <table class="tabela">
                    <tr>
                        <td class="destacar bold" width="1%">PRONAC</td>
                        <td class="destacar bold">Nome do Projeto</td>
                    </tr>
                    <tr>
                        <td align="center"><?php echo $AnaliseGeral->PRONAC; ?></td>
                        <td><?php echo $AnaliseGeral->NomeProjeto; ?></td>
                    </tr>
                    <tr>
                        <td class="destacar bold" colspan="2">Observação</td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <textarea maxlength="255" class="textarea_simples" name="justificativa" id="justificativaencaminha" rows="6" cols="50" style="width:98%;"></textarea>
                            <span style="font-size: 11px;">Quantidade m&aacute;xima de 255 caracteres.</span>
                        </td>
                    </tr>
                </table>

                <table class="tabela">
                    <tr>
                        <td class="destacar bold" width="130px;">Encaminhar para:</td>
                        <td>
                            <select name="passaValor" id="passaValor" class="select_simples" style="width:100%;">
                                <option value="0">Selecione uma opção</option>
                                <?php foreach ($this->listaEntidades as $listaEntidades): ?>
                                <option value="<?php echo $listaEntidades->Codigo; ?>"><?php echo $listaEntidades->Sigla; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="destacar bold" width="130px;">Destinatário:</td>
                        <td>
                            <select name="recebeValor" id="recebeValor" class="select_simples" style="width:100%;"></select>
                        </td>
                    </tr>
                </table>

                <input type="hidden" name="PRONAC" value="<?php echo $AnaliseGeral->PRONAC; ?>">
                <input type="hidden" name="NomeProjeto" value="<?php echo $AnaliseGeral->NomeProjeto; ?>">
                <input type="hidden" name="ID_PRONAC" value="<?php echo $AnaliseGeral->ID_PRONAC; ?>">
                <input type="hidden" name="idPedidoAlteracao" value="<?php echo $AnaliseGeral->idPedidoAlteracao; ?>">
                <input type="hidden" name="Orgao" value="<?php echo $AnaliseGeral->Orgao; ?>">
                <input type="hidden" name="tpAlteracaoProjeto" value="<?php echo $AnaliseGeral->tpAlteracaoProjeto; ?>">
                <input type="hidden" name="AgentePerfil" id="AgentePerfil" class="AgentePerfil" value="" />
                <input type="hidden" name="AgenteId" id="AgenteId" class="AgenteId" value="" />

                <p align="center" style="margin-top:1%;">
                    <input type="button" value=" " class="btn_enviar salvarencaminhamento<?php echo $AnaliseGeral->ID_PRONAC . $AnaliseGeral->tpAlteracaoProjeto; ?>">&nbsp;&nbsp;
                    <input type="reset" value=" " class="btn_limpar" />
                </p>
            </form>
        </div>
        <?php endforeach; ?>
	<!-- FIM DO MODAL PARA ENCAMINHAMENTO -->
	
	
	<!-- MODAL PARA ENCAMINHAMENTO DE PRODUTOS -->
	<?php foreach($this->AnaliseGeral as $AnaliseGeral): ?>
            <script type="text/javascript">
		$(document).ready(function(){

                    $('.salvarencaminhamento2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').click(function(){
			if($.trim($(this).parent().parent().find("input[name=AgenteId]").val()) == '')
                        {
                            $("#erro").dialog({
                                title : 'Alerta',
                                resizable: false,
                                width:300,
                                height:150,
                                modal: true,
                                autoOpen:false,
                                buttons: {
                                    'OK': function() {
                                        $(this).dialog('close');
                                    }
                                }
                            });
                            $("#erro").dialog('open');
                        }
                        else
                        {
                            $(this).parent().parent().parent().find('form').submit();
                        }
                    });
			
		  	$('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#passaValor').change(function(){		
	
			  	var idorgao = $(this).val();
				$.ajax({
					url : '<?php echo $this->url(array('controller' => 'verificarreadequacaodeprojeto', 'action' => 'verificarreadequacaodeprojetocoordacompanhamento')); ?>',
					data : 
					{
						idorgao : idorgao,
						verifica : 'b'
					},
					success: function(data){
						$('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val('');
						var recebe = $('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#recebeValor');
						if(data.resposta){
							recebe.html('');
							recebe.append("<option value=''>Selecione o agente</option>");
							for ( i in data.conteudo)
							{
								if (data.conteudo[i].idperfil == 93)
								{
									recebe.append("<option value='"+data.conteudo[i].idAgente+"/"+data.conteudo[i].idperfil+"'>"+data.conteudo[i].Perfil+" - "+data.conteudo[i].usu_nome+"</option>");
								}
							}
						}
						else{
							recebe.html('');
							recebe.append("<option value='0'>Nenhum registro encontrado</option>");
						}
					},
					type : 'post'
					,dataType : 'json'
				});
		  	});
		  	
		  	$('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('#recebeValor').change(function(){
			  			
			  	var perfil = $(this).val().split('/');
				$('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val(perfil[1]);
                                $('#encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>').find('.AgenteId').val(perfil[0]);
		  	});
			  	
		});
	  </script>
		
        <div style="display:none;" id="encaminhar2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>" title="Encaminhar projeto para análise" >
            <form name="formencaminhar" id="form<?php echo $AnaliseGeral->ID_PRONAC; ?>" action="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/encaminhacoordacompanhamento" method="post" onsubmit="return validaForm()">
				
                <table class="tabela">
                    <tr>
                        <th width="1%">PRONAC</th>
                        <th>Nome do Projeto</th>
                    </tr>
                    <tr>
                        <td><?php echo $AnaliseGeral->PRONAC; ?></td>
                        <td><?php echo $AnaliseGeral->NomeProjeto; ?></td>
                    </tr>
                </table>
				
                <br /><br />
				
                <textarea maxlength="255" name="justificativa" id="justificativaencaminha" rows="6" cols="50" style="width:95%;"
                onclick="limpar_campo(this, 'Digite a observação...');" onkeypress=" " class="textarea_simples" 
                onblur="restaurar_campo(this, 'Digite a observação...');">Digite a observação...</textarea>
                <span style="font-size: 11px;">Quantidade m&aacute;xima de 255 caracteres.</span>
			
                <br /><br>
                <div width="95%">
                    <tr>
                        <td><b>Encaminhar para:</b></td>
                        <td>
                            <select name="passaValor" id="passaValor" style="width: 70%;" class="select_simples">
                                <option value="0">Selecione uma opção</option>
                                <?php foreach($this->listaEntidadesPar as $listaEntidades): ?>
                                <option value="<?php echo $listaEntidades->Codigo;?>"><?php echo $listaEntidades->Sigla; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><b style="margin-left: 2.6em;">Destinatário:</b></td>
                        <td>
                            <select name="recebeValor" id="recebeValor" style="width: 70%; margin-top: 0.5em;" class="select_simples"></select>
                        </td>
                    </tr>
                </div>
					
                <br/>

                <input type="hidden" name="PRONAC" value="<?php echo $AnaliseGeral->PRONAC; ?>">
                <input type="hidden" name="NomeProjeto" value="<?php echo $AnaliseGeral->NomeProjeto; ?>">
                <input type="hidden" name="ID_PRONAC" value="<?php echo $AnaliseGeral->ID_PRONAC; ?>">
                <input type="hidden" name="idPedidoAlteracao" value="<?php echo $AnaliseGeral->idPedidoAlteracao; ?>">
                <input type="hidden" name="Orgao" value="<?php echo $AnaliseGeral->Orgao; ?>">
                <input type="hidden" name="tpAlteracaoProjeto" value="<?php echo $AnaliseGeral->tpAlteracaoProjeto; ?>">
                <input type="hidden" name="AgentePerfil" id="AgentePerfil" class="AgentePerfil" value="" />
                <input type="hidden" name="AgenteId" id="AgenteId" class="AgenteId" value="" />
					
					
                <p align="left" style="margin-top:1%;">
                    <input type="button"  value=" " class="btn_enviar salvarencaminhamento2<?php echo $AnaliseGeral->ID_PRONAC.$AnaliseGeral->tpAlteracaoProjeto; ?>" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset"  value=" " class="btn_limpar" />
                </p>
            </form>
        </div>
	<?php endforeach; ?>
	<!-- FIM DO MODAL PARA ENCAMINHAMENTO DE PRODUTOS -->
	
	
	
	<!-- MODAL PARA REENCAMINHAMENTO -->
	<?php foreach($this->AnaliseGeralDev as $AnaliseGeralDev): ?>
	
	<script type="text/javascript">
		$(document).ready(function(){
                    $('.salvarreencaminhamento').click(function(){
			if($.trim($(this).parent().parent().find("input[name=AgenteId]").val()) == ''){
                            $("#erro").dialog({
                                title : 'Alerta',
                                resizable: false,
                                width:300,
                                height:150,
                                modal: true,
                                autoOpen:false,
                                buttons: {
                                    'OK': function() {
                                        $(this).dialog('close');
                                    }
                                }
                            });
                            $("#erro").dialog('open');
                        } else {
                            $(this).parent().parent().parent().find('form').submit();
                        }
                    });

                    $('#reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#passaValor').change(function(){

                        var idorgao = $(this).val();
                        $.ajax({
                            url : '<?php echo $this->url(array('controller' => 'verificarreadequacaodeprojeto', 'action' => 'verificarreadequacaodeprojetocoordacompanhamento')); ?>',
                            data : {
                                idorgao : idorgao,
                                verifica : 'a'
                            },
                            success: function(data){
                                var recebe = $('#reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#recebeValor');
                                if(data.resposta){
                                    recebe.html('');
                                    recebe.append("<option value=''>Selecione o agente</option>");
                                    for ( i in data.conteudo) {
                                        recebe.append("<option value='"+data.conteudo[i].idAgente+"/"+data.conteudo[i].idperfil+"'>"+data.conteudo[i].Perfil+" - "+data.conteudo[i].usu_nome+"</option>");
                                    }
                                } else{
                                    recebe.html('');
                                    recebe.append("<option value='0'>Nenhum registro encontrado</option>");
                                }
                            },
                            type : 'post'
                            ,dataType : 'json'
                        });
                    });

                    $('#reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#recebeValor').change(function(){
                        var perfil = $(this).val().split('/');
                        $('#reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val(perfil[1]);
                        $('#reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('.AgenteId').val(perfil[0]);
                    });
		});
	  </script>
				
        <div style="display:none;" id="reencaminhar<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>" title="Reencaminhar projeto para análise" >
            <form name="formreencaminhar" id="form<?php echo $AnaliseGeralDev->ID_PRONAC; ?>" action="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/reencaminhacoordacompanhamento" method="post">
                <table class="tabela">
                    <tr>
                        <td class="destacar bold">PRONAC</td>
                        <td class="destacar bold">Nome do Projeto</td>
                    </tr>
                    <tr>
                        <td align="center"><?php echo $AnaliseGeralDev->PRONAC; ?></td>
                        <td><?php echo $AnaliseGeralDev->NomeProjeto; ?></td>
                    </tr>
                </table>
                    
                <br /><br />

                <textarea maxlength="255" name="justificativa" id="justificativaencaminha" rows="6" cols="50" style="width:95%;"
                            onclick="limpar_campo(this, 'Digite a observação...');" onkeypress=" "
                            onblur="restaurar_campo(this, 'Digite a observação...');">Digite a observação...</textarea>
                <span style="font-size: 11px;">Quantidade m&aacute;xima de 255 caracteres.</span>

                <br /><br>

                <div width="95%">
                    <tr>
                        <td><b>Encaminhar para:</b></td>
                        <td>
                            <select name="passaValor" id="passaValor" style="width: 70%; " class="select_simples">
                            <option value="0">Selecione uma opção</option>
                            <?php foreach($this->listaEntidades as $listaEntidades): ?>
                            <option value="<?php echo $listaEntidades->Codigo;?>"><?php echo $listaEntidades->Sigla; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><b style="margin-left: 2.6em;">Destinatário:</b></td>
                        <td>
                            <select name="recebeValor" id="recebeValor" style="width: 70%; margin-top: 0.5em;" class="select_simples"></select>
                        </td>
                    </tr>
                </div>
                <br/>

                <input type="hidden" name="PRONAC" value="<?php echo $AnaliseGeralDev->PRONAC; ?>">
                <input type="hidden" name="NomeProjeto" value="<?php echo $AnaliseGeralDev->NomeProjeto; ?>">
                <input type="hidden" name="ID_PRONAC" value="<?php echo $AnaliseGeralDev->ID_PRONAC; ?>">
                <input type="hidden" name="idPedidoAlteracao" value="<?php echo $AnaliseGeralDev->idPedidoAlteracao; ?>">
                <input type="hidden" name="Orgao" value="<?php echo $AnaliseGeralDev->idOrgao; ?>">
                <input type="hidden" name="tpAlteracaoProjeto" value="<?php echo $AnaliseGeralDev->tpAlteracaoProjeto; ?>">
                <input type="hidden" name="idAcao" value="<?php echo $AnaliseGeralDev->idAcao; ?>">
                <input type="hidden" name="AgentePerfil" id="AgentePerfil" class="AgentePerfil" value="" />
                <input type="hidden" name="AgenteId" id="AgenteId" class="AgenteId" value="" />
					
                <p align="left" style="margin-top:1%;">
                    <input id="btn_salvar" type="button"  value=" " class="btn_enviar salvarreencaminhamento" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset"  value=" " class="btn_limpar" />
                </p>
            </form>
        </div>
	<?php endforeach; ?>
	<!-- FIM DO MODAL PARA REENCAMINHAMENTO -->
	
	
	<!-- MODAL PARA REENCAMINHAMENTO DE PRODUTOS-->
	<?php foreach($this->AnaliseGeralDev as $AnaliseGeralDev): ?>
	
	<script type="text/javascript">
		$(document).ready(function(){
		  	$('#reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#passaValor').change(function(){		
	
			  	var idorgao = $(this).val();
				$.ajax({
					url : '<?php echo $this->url(array('controller' => 'verificarreadequacaodeprojeto', 'action' => 'verificarreadequacaodeprojetocoordacompanhamento')); ?>',
					data : 
					{
						idorgao : idorgao,
						verifica : 'b'
					},
					success: function(data){
						var recebe = $('#reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#recebeValor');
						if(data.resposta){
							recebe.html('');
							recebe.append("<option value=''>Selecione o agente</option>");
							for ( i in data.conteudo)
 							{
								if (data.conteudo[i].idperfil == 93)
								{
									recebe.append("<option value='"+data.conteudo[i].idAgente+"'>"+data.conteudo[i].Perfil+" - "+data.conteudo[i].usu_nome+"</option>");
								}
							}
						}
						else{
							recebe.html('');
							recebe.append("<option value='0'>Nenhum registro encontrado</option>");
						}
					},
					type : 'post'
					,dataType : 'json'
				});
		  	});
                        
                        $('#reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('#recebeValor').change(function(){

			  	var perfil = $(this).val().split('/');
				$('#reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('.AgentePerfil').val(perfil[1]);
                                $('#reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>').find('.AgenteId').val(perfil[0]);
		  	});
			  	
		});
	  </script>
				
        <div style="display:none;" id="reencaminhar2<?php echo $AnaliseGeralDev->ID_PRONAC.$AnaliseGeralDev->tpAlteracaoProjeto; ?>" title="Reencaminhar projeto para análise" >
            <form name="formreencaminhar" id="form<?php echo $AnaliseGeralDev->ID_PRONAC; ?>" action="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/reencaminhacoordacompanhamento" method="post">
                <table class="tabela">
                    <tr>
                        <th width="1%">PRONAC</th>
                        <th>Nome do Projeto</th>
                    </tr>
                    <tr>
                        <td><?php echo $AnaliseGeralDev->PRONAC; ?></td>
                        <td><?php echo $AnaliseGeralDev->NomeProjeto; ?></td>
                    </tr>
                </table>

                <br /><br />

                <textarea maxlength="255" onkeypress="javascript:limita('justificativaencaminha');" name="justificativa" id="justificativaencaminha" rows="6" cols="50" style="width:95%;"
                            onclick="limpar_campo(this, 'Digite a observação...');" onkeypress=" " class="textarea_simples" 
                            onblur="restaurar_campo(this, 'Digite a observação...');">Digite a observação...</textarea>
                <span style="font-size: 11px;">Quantidade m&aacute;xima de 255 caracteres.</span>

                <br /><br>

                <div width="95%">
                    <tr>
                        <td><b>Encaminhar para:</b></td>
                        <td>
                            <select name="passaValor" id="passaValor" style="width: 70%; " class="select_simples">
                                <option value="0">Selecione uma opção</option>
                                <?php foreach ($this->listaEntidadesPar as $listaEntidades): ?>
                                <option value="<?php echo $listaEntidades->Codigo; ?>"><?php echo $listaEntidades->Sigla; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><b style="margin-left: 2.6em;">Destinatário:</b></td>
                        <td>
                            <select name="recebeValor" id="recebeValor" style="width: 70%; margin-top: 0.5em;" class="select_simples"></select>
                        </td>
                    </tr>
                </div>
                <br/>

                <input type="hidden" name="PRONAC" value="<?php echo $AnaliseGeralDev->PRONAC; ?>">
                <input type="hidden" name="NomeProjeto" value="<?php echo $AnaliseGeralDev->NomeProjeto; ?>">
                <input type="hidden" name="ID_PRONAC" value="<?php echo $AnaliseGeralDev->ID_PRONAC; ?>">
                <input type="hidden" name="idPedidoAlteracao" value="<?php echo $AnaliseGeralDev->idPedidoAlteracao; ?>">
                <input type="hidden" name="Orgao" value="<?php echo $AnaliseGeralDev->idOrgao; ?>">
                <input type="hidden" name="tpAlteracaoProjeto" value="<?php echo $AnaliseGeralDev->tpAlteracaoProjeto; ?>">
                <input type="hidden" name="idAcao" value="<?php echo $AnaliseGeralDev->idAcao; ?>">
                <input type="hidden" name="AgentePerfil" id="AgentePerfil" class="AgentePerfil" value="" />
                <input type="hidden" name="AgenteId" id="AgenteId" class="AgenteId" value="" />

                <p align="left" style="margin-top:1%;">
                    <input id="btn_salvar" type="submit"  value=" " class="btn_enviar salvarreencaminhamento" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset"  value=" " class="btn_limpar" />
                </p>
            </form>
        </div>
	<?php endforeach; ?>
	<!-- FIM DO MODAL PARA REENCAMINHAMENTO DE PRODUTOS -->
	
	
	<!-- MODAL PARA VISUALIZAR HISTÓRICO -->
	<?php foreach($this->HistoricoUnico as $HistoricoUnico): ?>
        <div style="display:none;" id="visualizarhist<?php echo $HistoricoUnico->idAvaliacaoItemPedidoAlteracao; ?>" title="Visualizar Histórico" >
            <div id="recebeValor"></div>
        </div>
	<?php endforeach; ?>
	<!-- FIM DO MODAL PARA VISUALIZAR HISTÓRICO -->
	
	<!-- MODAL PARA CONFIRMAÇÃO DE ENCAMINHAMENTO-->
	<div id="mostra"></div>
	<!-- MODAL PARA CONFIRMAÇÃO DE ENCAMINHAMENTO-->
	

	<table class="tabela" summary="Aguardando Análise">
	   <tr class="destacar bold">
	     <td><input type="button" name="grid1" id="g1_analise" class="btn_remover" title="Recolher" /> AGUARDANDO ANÁLISE</td>
	     <td width="150px" align="center"><?php echo $this->AguardAnaliseQNTD;?></td>
	   </tr>   
	</table>
	
	<div id="div_g1_analise" class="miolo_grid_01">

            <table class="tabela" summary="nome do projeto">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_nomedoprojeto" class="btn_adicionar" title="Expandir" /> Nome do Projeto</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise5);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_nomedoprojeto" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise5 as $AguardAnalise5){ ?>
                    <tr class="tblGerenciar_projetos">
                        <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise5->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise5->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise5->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise5->areaDesc." / ".$AguardAnalise5->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise5->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise5->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs): ?>
                            <?php if($AguardAnalise5->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php endforeach; ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltnomproj?idpedidoalteracao=<?php echo $AguardAnalise5->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise5->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise5->ID_PRONAC.$AguardAnalise5->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise5->ID_PRONAC.$AguardAnalise5->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                        	<?php echo $this->verificarStatusAnalise($AguardAnalise5->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise5) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
	
            <table class="tabela" summary="troca de proponente">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_razaosocial" class="btn_adicionar" title="Expandir" /> Troca de Proponente</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise2);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_razaosocial" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise2 as $AguardAnalise2){ ?>
                    <tr class="tblGerenciar_projetos">
                    	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise2->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise2->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise2->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise2->areaDesc." / ".$AguardAnalise2->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise2->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise2->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs): ?>
                            <?php if($AguardAnalise2->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php endforeach; ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltrazsoc?idpedidoalteracao=<?php echo $AguardAnalise2->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise2->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise2->ID_PRONAC.$AguardAnalise2->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise2->ID_PRONAC.$AguardAnalise2->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                        	<?php echo $this->verificarStatusAnalise($AguardAnalise2->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise2) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
            <table class="tabela" summary="local de realização">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_localderealizacao" class="btn_adicionar" title="Expandir" /> Local de Realização</td>
                 <td width="6%"  align="center"><?php echo count($this->AguardAnalise4);?></td>
               </tr>
            </table>
                <div id="div_g1_analise_localderealizacao" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise4 as $AguardAnalise4){ ?>
                    <tr class="tblGerenciar_projetos">
                    	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise4->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise4->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise4->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise4->areaDesc." / ".$AguardAnalise4->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise4->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise4->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs): ?>
                            <?php if($AguardAnalise4->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php endforeach; ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltlocrel?idpedidoalteracao=<?php echo $AguardAnalise4->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise4->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise4->ID_PRONAC.$AguardAnalise4->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise4->ID_PRONAC.$AguardAnalise4->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                        	<?php echo $this->verificarStatusAnalise($AguardAnalise4->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise4) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="nome do proponente">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_nomedoproponente" class="btn_adicionar" title="Expandir" /> Nome do Proponente</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise1);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_nomedoproponente" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise1 as $AguardAnalise1){ ?>
                    <tr class="tblGerenciar_projetos">
                    	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise1->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise1->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise1->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise1->areaDesc." / ".$AguardAnalise1->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise1->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise1->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise1->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltnomprp?idpedidoalteracao=<?php echo $AguardAnalise1->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise1->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise1->ID_PRONAC.$AguardAnalise1->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise1->ID_PRONAC.$AguardAnalise1->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise1->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise1) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="ficha técnica">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_fichatecnica" class="btn_adicionar" title="Expandir" />  Ficha Técnica</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise3);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_fichatecnica" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise3 as $AguardAnalise3){ ?>
                    <tr class="tblGerenciar_projetos">
                        <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise3->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise3->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise3->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise3->areaDesc." / ".$AguardAnalise3->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise3->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise3->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise3->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltfictec?idpedidoalteracao=<?php echo $AguardAnalise3->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise3->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise3->ID_PRONAC.$AguardAnalise3->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise3->ID_PRONAC.$AguardAnalise3->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise3->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise3) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="prorrogação de prazos - captação">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_prorrogacaocaptacao" class="btn_adicionar" title="Expandir" /> Prorrogação de Prazos - Captação</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise8);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_prorrogacaocaptacao" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise8 as $AguardAnalise8){ ?>
                    <tr class="tblGerenciar_projetos">
                        <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise8->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise8->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise8->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise8->areaDesc." / ".$AguardAnalise8->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise8->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise8->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise8->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltprogprazcap?idpedidoalteracao=<?php echo $AguardAnalise8->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise8->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise8->ID_PRONAC.$AguardAnalise8->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise8->ID_PRONAC.$AguardAnalise8->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise8->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise8) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="prorrogação de prazos - execução">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_prorrogacaoexecucao" class="btn_adicionar" title="Expandir" /> Prorrogação de Prazos - Execução</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise9);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_prorrogacaoexecucao" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar Mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise9 as $AguardAnalise9){ ?>
                    <tr class="tblGerenciar_projetos">
                        <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise9->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise9->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise9->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise9->areaDesc." / ".$AguardAnalise9->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise9->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise9->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise9->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltprogprazexec?idpedidoalteracao=<?php echo $AguardAnalise9->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise9->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise9->ID_PRONAC.$AguardAnalise9->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise9->ID_PRONAC.$AguardAnalise9->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise9->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise9) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="produtos">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_produtos" class="btn_adicionar" title="Expandir" /> Produtos</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise7);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_produtos" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar Mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise7 as $AguardAnalise7){ ?>
                    <tr class="tblGerenciar_projetos">
                    	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise7->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise7->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise7->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise7->areaDesc." / ".$AguardAnalise7->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise7->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise7->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise7->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/consultareadequacaoprodutos?id=<?php echo $AguardAnalise7->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise7->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise7->ID_PRONAC.$AguardAnalise7->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise7->ID_PRONAC.$AguardAnalise7->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise7->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if (count($this->AguardAnalise7) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
		
		
            <table class="tabela" summary="proposta pedagogica">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_propostapedagogica" class="btn_adicionar" title="Expandir" /> Proposta Pedagógica</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise6);?></td>
               </tr>
            </table>
                <div id="div_g1_analise_propostapedagogica" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar Mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise6 as $AguardAnalise6){ ?>
                    <tr class="tblGerenciar_projetos">
                    	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise6->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise6->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise6->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise6->areaDesc." / ".$AguardAnalise6->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise6->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise6->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise6->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/propostapedagogica?id=<?php echo $AguardAnalise6->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise6->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar('<?php echo $AguardAnalise6->ID_PRONAC.$AguardAnalise6->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar('<?php echo $AguardAnalise6->ID_PRONAC.$AguardAnalise6->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise6->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if (count($this->AguardAnalise6) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>


            <table class="tabela" summary="itens de custo">
               <tr>
                 <td width="94%"><input type="button" name="grid1" id="g1_analise_itensdecusto" class="btn_adicionar" title="Expandir" /> Produtos + Itens de Custo</td>
                 <td width="6%" align="center"><?php echo count($this->AguardAnalise10);?></td>
               </tr>
            </table>
            <div id="div_g1_analise_itensdecusto" class="miolo_grid_01 sumir">
                <table class="tabela">
                    <tr>
                        <th width="7%" align="center">PRONAC</th>
                        <th width="40%" style="text-align:left;">Nome do projeto</th>
                        <th width="20%" align="center">Área / Segmento</th>
                        <th width="10%" align="center">Data de Recebimento</th>
                        <th width="10%" align="center">Estado(s)</th>
                        <th>Visualizar Readequa&ccedil;&atilde;o</th>
                        <!--<th>Enviar Mensagem</th>-->
                        <th width="8%" align="center">Encaminhar p/ análise</th>
                        <th width="5%" align="center">Controle</th>
                    </tr>
                    <?php foreach($this->AguardAnalise10 as $AguardAnalise10){ ?>
                    <tr class="tblGerenciar_projetos">
                        <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $AguardAnalise10->ID_PRONAC; ?>" target="_blank"><?php echo $AguardAnalise10->PRONAC; ?></a></td>
                        <td style="text-align:left;"><?php echo $AguardAnalise10->NomeProjeto; ?></td>
                        <td align="center"><?php echo $AguardAnalise10->areaDesc." / ".$AguardAnalise10->segmentoDesc; ?></td>
                        <td align="center"><?php if($AguardAnalise10->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($AguardAnalise10->DataEnvio,'brasileiro');} ?></td>
                        <td align="center">
                            <?php foreach($this->UFs as $UFs){ ?>
                            <?php if($AguardAnalise10->ID_PRONAC == $UFs->ID_PRONAC ){ echo $UFs->Sigla;} ?>
                            <?php } ?>
                        </td>
                        <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/consultareadequacaoitensdecusto?id=<?php echo $AguardAnalise10->ID_PRONAC; ?>');" /></td>
                        <!--<td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $AguardAnalise10->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>-->
                        <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return encaminhar2('<?php echo $AguardAnalise10->ID_PRONAC.$AguardAnalise10->tpAlteracaoProjeto; ?>')" onkeypress="return encaminhar2('<?php echo $AguardAnalise10->ID_PRONAC.$AguardAnalise10->tpAlteracaoProjeto; ?>')" alt="Encaminhar" /></td>
                        <td align="center">
                            <?php echo $this->verificarStatusAnalise($AguardAnalise10->DataEnvio); ?>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php if(count($this->AguardAnalise10) <= 0){ ?>
                    <tr>
                        <td colspan="9" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>

    <table class="tabela" summary="Devolvidos após Análise">
        <tr class="destacar bold">
          <td><input type="button" name="grid1" id="g1_devolvido" class="btn_remover" title="Recolher" /> DEVOLVIDOS APÓS ANÁLISE</td>
          <td width="150px" align="center"><?php echo $this->DevolvAnaliseQNTD;?></td>
        </tr>
    </table>

	<div id="div_g1_devolvido" class="miolo_grid_01">

        <table class="tabela" summary="nome do projeto">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_nomedoprojeto" class="btn_adicionar" title="Expandir" /> Nome do Projeto</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise5);?></td>
           </tr>
        </table>
        <div id="div_g1_devolvido_nomedoprojeto" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise5 as $DevolvAnalise5): ?>
                <tr class="tblGerenciar_projetos">
                	<td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise5->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise5->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise5->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise5->areaDesc." / ".$DevolvAnalise5->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise5->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise5->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise5->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise5->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise5->ID_PRONAC.$DevolvAnalise5->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise5->ID_PRONAC.$DevolvAnalise5->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise5->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltnomproj?idpedidoalteracao=<?php echo $DevolvAnalise5->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise5->ID_PRONAC, null, array(171)), $DevolvAnalise5->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise5->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise5->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise5->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise5->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise5->DataEnvio); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise5) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
	

        <table class="tabela" summary="troca de proponente">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_razaosocial" class="btn_adicionar" title="Expandir" /> Troca de Proponente</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise2);?></td>
           </tr>
        </table>
        <div id="div_g1_devolvido_razaosocial" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise2 as $DevolvAnalise2): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise2->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise2->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise2->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise2->areaDesc." / ".$DevolvAnalise2->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise2->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise2->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise2->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise2->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise2->ID_PRONAC.$DevolvAnalise2->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise2->ID_PRONAC.$DevolvAnalise2->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise2->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltrazsoc?idpedidoalteracao=<?php echo $DevolvAnalise2->ID_PRONAC; ?>');" /></td>
                    <td class="centro">					
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise2->ID_PRONAC, null, array(171)), $DevolvAnalise2->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise2->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise2->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise2->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise2->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise2->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise2) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="local de realização">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_localderealizacao" class="btn_adicionar" title="Expandir" /> Local de Realização</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise4);?></td>
           </tr>
        </table>
        <div id="div_g1_devolvido_localderealizacao" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise4 as $DevolvAnalise4): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise4->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise4->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise4->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise4->areaDesc." / ".$DevolvAnalise4->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise4->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise4->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise4->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise4->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise4->ID_PRONAC.$DevolvAnalise4->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise4->ID_PRONAC.$DevolvAnalise4->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise4->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
					<td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltlocrel?idpedidoalteracao=<?php echo $DevolvAnalise4->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise4->ID_PRONAC, null, array(171)), $DevolvAnalise4->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise4->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise4->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise4->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise4->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise4->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise4) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="nome do proponente">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_nomedoproponente" class="btn_adicionar" title="Expandir" /> Nome do Proponente</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise1);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_nomedoproponente" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise1 as $DevolvAnalise1): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise1->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise1->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise1->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise1->areaDesc." / ".$DevolvAnalise1->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise1->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise1->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise1->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise1->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise1->ID_PRONAC.$DevolvAnalise1->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise1->ID_PRONAC.$DevolvAnalise1->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise1->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltnomprp?idpedidoalteracao=<?php echo $DevolvAnalise1->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise1->ID_PRONAC, null, array(171)), $DevolvAnalise1->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise1->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise1->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise1->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise1->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise1->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise1) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="ficha técnica">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_fichatecnica" class="btn_adicionar" title="Expandir" /> Ficha Técnica</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise3);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_fichatecnica" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise3 as $DevolvAnalise3): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise3->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise3->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise3->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise3->areaDesc." / ".$DevolvAnalise3->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise3->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise3->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise3->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise3->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise3->ID_PRONAC.$DevolvAnalise3->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise3->ID_PRONAC.$DevolvAnalise3->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise3->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltfictec?idpedidoalteracao=<?php echo $DevolvAnalise3->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise3->ID_PRONAC, null, array(171)), $DevolvAnalise3->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise3->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise3->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise3->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise3->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise3->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise3) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="prorrogação de prazos - captação">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_prorrogacaocaptacao" class="btn_adicionar" title="Expandir" /> Prorrogação de Prazos - Captação</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise8);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_prorrogacaocaptacao" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise8 as $DevolvAnalise8): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise8->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise8->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise8->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise8->areaDesc." / ".$DevolvAnalise8->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise8->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise8->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise8->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise8->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise8->ID_PRONAC.$DevolvAnalise8->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise8->ID_PRONAC.$DevolvAnalise8->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise8->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltprogprazcap?idpedidoalteracao=<?php echo $DevolvAnalise8->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise8->ID_PRONAC, null, array(171)), $DevolvAnalise8->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise8->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise8->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise8->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise8->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise8->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise8) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="prorrogação de prazos - execução">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_prorrogacaoexecucao" class="btn_adicionar" title="Expandir" /> Prorrogação de Prazos - Execução</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise9);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_prorrogacaoexecucao" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise9 as $DevolvAnalise9): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise9->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise9->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise9->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise9->areaDesc." / ".$DevolvAnalise9->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise9->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise9->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise9->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise9->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise9->ID_PRONAC.$DevolvAnalise9->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise9->ID_PRONAC.$DevolvAnalise9->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise9->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificaralteracaocoordenador/solaltprogprazexec?idpedidoalteracao=<?php echo $DevolvAnalise9->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise9->ID_PRONAC, null, array(171)), $DevolvAnalise9->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise9->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise9->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise9->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise9->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise9->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise9) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="produtos">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_produtos" class="btn_adicionar" title="Expandir" /> Produtos</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise7);?></td>
           </tr>
        </table>
        <div id="div_g1_devolvido_produtos" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise7 as $DevolvAnalise7): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise7->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise7->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise7->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise7->areaDesc." / ".$DevolvAnalise7->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise7->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise7->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise7->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise7->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise7->ID_PRONAC.$DevolvAnalise7->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar2('<?php echo $DevolvAnalise7->ID_PRONAC.$DevolvAnalise7->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise7->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/readequacaoprodutos?id=<?php echo $DevolvAnalise7->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise7->ID_PRONAC, null, array(171)), $DevolvAnalise7->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise7->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise7->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise7->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise7->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise7->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise7) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>
		
		
        <table class="tabela" summary="proposta pedagogica">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_propostapedagogica" class="btn_adicionar" title="Expandir" /> Proposta Pedagógica</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise6);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_propostapedagogica" class="miolo_grid_01 sumir">
            <table class="tabela">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise6 as $DevolvAnalise6): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise6->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise6->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise6->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise6->areaDesc." / ".$DevolvAnalise6->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise6->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise6->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise6->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise6->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar('<?php echo $DevolvAnalise6->ID_PRONAC.$DevolvAnalise6->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar('<?php echo $DevolvAnalise6->ID_PRONAC.$DevolvAnalise6->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise6->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/propostapedagogicadev?id=<?php echo $DevolvAnalise6->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise6->ID_PRONAC, null, array(171)), $DevolvAnalise6->ID_PRONAC, 171, $this->verificarSituacaoProjeto($DevolvAnalise6->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise6->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise6->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise6->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise6->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise6) <= 0) : ?>
                <tr>
                	<td colspan="12" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>


        <table class="tabela" summary="itens de custo">
           <tr>
             <td width="94%"><input type="button" name="grid1" id="g1_devolvido_itensdecusto" class="btn_adicionar" title="Expandir" /> Produtos + Itens de Custo</td>
             <td width="6%" align="center"><?php echo count($this->DevolvAnalise10);?></td>
           </tr>
        </table>
		<div id="div_g1_devolvido_itensdecusto" class="miolo_grid_01 sumir">
            <table class="tabela"">
                <tr>
                    <th width="7%" align="center">PRONAC</th>
                    <th width="35%" style="text-align:left;">Nome do projeto</th>
                    <th width="15%" align="center">Área / Segmento</th>
                    <th width="7%" align="center">Data de envio para análise</th>
                    <th width="8%" align="center">Data de recebimento da análise</th>
                    <th width="7%" align="center">Reencaminhar p/ análise</th>
                    <th width="8%" align="center">Visualizar Histórico</th>
                    <th width="7%" align="center">Encaminhar p/ Componente</th>
                    <th>Visualizar Readequa&ccedil;&atilde;o</th>
                    <th>Diligenciar</th>
                    <th>Enviar Mensagem</th>
                    <th width="5%" align="center">Finalizar</th>
                    <th width="5%" align="center">Controle</th>
                </tr>
                <?php foreach($this->DevolvAnalise10 as $DevolvAnalise10): ?>
                <tr class="tblGerenciar_projetos">
                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/consultardadosprojeto/index?idPronac=<?php echo $DevolvAnalise10->ID_PRONAC; ?>" target="_blank"><?php echo $DevolvAnalise10->PRONAC; ?></a></td>
                    <td style="text-align:left;"><?php echo $DevolvAnalise10->NomeProjeto; ?></td>
                    <td align="center"><?php echo $DevolvAnalise10->areaDesc." / ".$DevolvAnalise10->segmentoDesc; ?></td>
                    <td align="center"><?php if($DevolvAnalise10->DataEnvio==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise10->DataEnvio,'brasileiro');} ?></td>
                    <td align="center"><?php if($DevolvAnalise10->DataFim==''){echo 'Não há registro';} else{ echo Data::tratarDataZend($DevolvAnalise10->DataFim,'brasileiro');} ?></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/user_gray.png" onclick="return reencaminhar2('<?php echo $DevolvAnalise10->ID_PRONAC.$DevolvAnalise10->tpAlteracaoProjeto; ?>')" onkeypress="return reencaminhar2('<?php echo $DevolvAnalise10->ID_PRONAC.$DevolvAnalise10->tpAlteracaoProjeto; ?>')" alt="Reencaminhar" /></td>
                    <td align="center"><img style="cursor: pointer;" border="0" class="abrirJanela" src="../public/img/table_multiple.png" idAvaliacao="<?php echo $DevolvAnalise10->idAvaliacaoItemPedidoAlteracao; ?>" alt="Visualizar Histórico" /></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/buttons/sair-p-off.gif" onclick="return componentecomissao(<?php echo $DevolvAnalise10->ID_PRONAC; ?>,<?php echo $DevolvAnalise10->idAcao; ?>)"></td>
<!--                    <td align="center"><a href="<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/encaminhacomponentecomissao/idpronac/<?php echo $DevolvAnalise10->ID_PRONAC; ?>/idacao/<?php echo $DevolvAnalise10->idAcao; ?>" title="Enviar para Componente da Comissão"><img style="cursor: pointer;" src="../public/img/buttons/sair-p-off.gif"></a></td>-->
					<td class="centro"><img style="cursor: pointer;" src="../public/img/ico/kdict.png" alt="Visualizar Projeto" title="Visualizar Projeto" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/verificarreadequacaodeprojeto/readequacaoitensdecusto?id=<?php echo $DevolvAnalise10->ID_PRONAC; ?>');" /></td>
                    <td class="centro">
						<?php
						echo $this->iconeDiligencia($this->checarDiligencia($DevolvAnalise10->ID_PRONAC, null, array(179)), $DevolvAnalise10->ID_PRONAC, 179, $this->verificarSituacaoProjeto($DevolvAnalise10->ID_PRONAC));
						?>
                    </td>
                    <td class="centro"><a target='_blank' href='<?php echo $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem'), '', true); ?>/idpronac/<?php echo $DevolvAnalise10->ID_PRONAC; ?>'><img src='<?php echo $this->baseUrl() ?>/public/img/buttons/sair-p.gif' title='Enviar mensagem'/></a></td>
                    <td align="center"><img style="cursor: pointer;" src="../public/img/passed.gif" onclick="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise10->idAcao; ?>')" onkeypress="return finalizarsolicitacaogeral('<?php echo $DevolvAnalise10->idAcao; ?>')"></img></td>
                    <td align="center">
                    	<?php echo $this->verificarStatusAnalise($DevolvAnalise10->DataFim); ?>
                    </td>
                </tr>
                <?php endforeach; ?>

                <?php if (count($this->DevolvAnalise10) <= 0) : ?>
                <tr>
                	<td colspan="13" class="centro">N&atilde;o existe(m) Projeto(s) com solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o!</td>
                </tr>
                <?php endif; ?>

            </table>
        </div>


</div>

<br /><br />

</div>

<script type="text/javascript">
$('.abrirJanela').click(function(){
	visualizarhist($(this).attr('idAvaliacao'),'<?php echo $historicoLink;?>');
});
$('.abrirJanela').keypress(function(){
	visualizarhist($(this).attr('idAvaliacao'),'<?php echo $historicoLink;?>');
});

function componentecomissao(idPronac, idAcao){
//    alert(idPronac);
//    alert(idAcao);

    $("#mostra").dialog("destroy");
    $('#mostra').html('Deseja encaminhar para o Componente da Comiss&atilde;o?');
    $("#mostra").dialog
    ({
        height: 180,
        modal: true,
        draggable: false,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            'Não': function()
            {
                    $(this).dialog('close');
            },
            'Sim': function()
            {
                    window.location.href = 'encaminhacomponentecomissao/idpronac/'+idPronac+'/idacao/'+idAcao;
            }
        }
    });
    $('.ui-dialog-titlebar-close').remove();
}

$("textarea[maxlength]").keypress(function(event){
    var key = event.which;
 
    //todas as teclas incluindo enter
    if(key >= 33 || key == 13) {
        var maxLength = $(this).attr("maxlength");
        var length = this.value.length;
        if(length >= maxLength) {
            event.preventDefault();
        }
    }
});
</script>

<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />