<?php require_once "scripts/avaliaracompanhamentoprojeto/inc/menu.inc.php"; ?>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Lista de Relatórios">Lista de Relatórios</a></li>
        <li class="last">Comprovantes de Execução</li>
    </ul>
</div>


<div id="titulo">
    <div>Comprovantes de Execução <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Voltar">Voltar</a></span></div>
</div>


<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">Nº PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <th colspan="4">Comprovantes Cadastrados</th>
        </tr>
        <tr align="center">
            <td class="destacar bold">Tipo de Comprovante</td>
            <td class="destacar bold">Nome do Arquivo</td>
            <td class="destacar bold">Data de Envio</td>
            <td class="destacar bold">Observações</td>
        </tr>
        <?php foreach ($this->DadosComprovantes as $DadosComprovantes) { ?>
        <tr>
            <td>
                <?php
                    if($DadosComprovantes->idTipoDocumento == 22){
                        echo 'Fotos';
                    } else if($DadosComprovantes->idTipoDocumento == 23){
                        echo 'Vídeos';
                    } else if($DadosComprovantes->idTipoDocumento == 24){
                        echo 'Arquivo';
                    }
                ?>
            </td>
            <td><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $DadosComprovantes->idArquivo; ?>"><?php echo $DadosComprovantes->nmArquivo; ?></a></td>
            <td><?php echo Data::tratarDataZend($DadosComprovantes->dtEnvio, 'Brasileira', true); ?></td>
            <td><?php echo $DadosComprovantes->dsDocumento; ?></td>
        </tr>
        <?php } ?>
    </table>

    <br clear="all" />
</div>

<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
