<style>
    table caption {
       background: -webkit-linear-gradient(#FFFFCC, #FFFFE8); /* For Safari 5.1 to 6.0 */
       background: -o-linear-gradient(#FFFFCC, #FFFFE8); /* For Opera 11.1 to 12.0 */
       background: -moz-linear-gradient(#FFFFCC, #FFFFE8); /* For Firefox 3.6 to 15 */
       background: linear-gradient(#FFFFCC, #FFFFE8); /* Standard syntax */
       color: #3A7300;
       font-size: 11px;
       padding: 8px;
       text-transform: uppercase;
       border-width: 2px 2px 0px 2px;
       border-style: solid;
       border-color: #CCC;
   }
</style>
<?php require_once "scripts/avaliaracompanhamentoprojeto/inc/menu.inc.php"; ?>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="last">Recursos por Fonte</li>
    </ul>
</div>

<div id="titulo">
    <div>
        Recursos por Divulgação 
        <span class="voltar">
            <a href="<?php echo $this->baseUrl(); ?>/avaliaracompanhamentoprojeto/index-tecnico" title="Voltar">Voltar</a>
        </span>
    </div>
</div>
<div id="conteudo">
    <table class="tabela">
        <caption>Recursos por Fonte</caption>
         <?php
         if ($this->recursosPorFonte) :
            $currency = new Zend_Currency('pt_BR');
         ?>
        <tr class="linha">
            <?php foreach ($this->recursosPorFonte as $recurso) : ?>
            <th align="center"><?php echo $recurso->fonteRecurso; ?></th>
            <?php endforeach; ?>
        </tr>
        <tr class="linha">
            <?php
            foreach ($this->recursosPorFonte as $recurso) :
                $currency->setValue($recurso->valorFonte)
                ?>
            <td align="center"><?php echo $currency; ?></td>
            <?php endforeach; ?>
        </tr>
        <?php endif; ?>
    </table>
    <br clear="all" />
</div>

<!-- inï¿½cio: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->

<br clear="all" />
