<?php
require_once "scripts/consultarpareceristas/inc/menu.inc.php";
?>
<script>
$(document).ready(function(){

	$('.numero').keydown(function(event){
        //		var texto = '';
        //		 for(j in event){
        //			 texto += j+' = '+event[j]+' | ';
        //				}
        //
        //		alert(texto);return false;
        if((event.keyCode >= 96 && event.keyCode <= 105) || (event.keyCode >= 48 && event.keyCode <= 57) || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 67 || event.keyCode == 86){
            return true;
        }
        else
            return false;
        //$(this).val($(this).val().replace(/\D/g,''));
    });
    
	$('.btn_localizar').click(function(){

	var validar = true;
	$('.valida').each(function(){
		if($(this).val() == ''){
			validar = false;
		}
	});
	if(validar == false){
		$("#MsgPronac").html('Campo obrigat&oacute;rio!');
		
	} else{
		switch($("#periodo").val())
        {
            case '2':
                if ($("#datainicio").val() != '' && $("#datafim").val() != '') {
                    if (1 == compararDataInicialDataFinal($("#datainicio").val(),$("#datafim").val())) {
                        alert("A Data Inicial n\xE3o pode ser maior que a Final");
                    } else {
                        $('#formConsulta').submit();
                    }
                } else {
                    alert ("Coloque as datas");
                }
                break;
            case '1':
                if ($("#datainicio").val() < 1 ) {
                    alert("Coloque a Data");
                } else {
                    $('#formConsulta').submit();
                }
                break;
            default:
                $('#formConsulta').submit();
        }
	}

	});
});

    function abrir_fechar(id_div){
        $('#'+id_div).toggle();
        $('#maiss'+id_div).toggle().focus();
        $('#menoss'+id_div).toggle().focus();
    }

    $(function() {
        $.datepicker.regional['pt-BR'] = {
            closeText: 'Fechar',
            prevText: '&#x3c;Anterior',
            nextText: 'Pr&oacute;ximo&#x3e;',
            currentText: 'Hoje',
            monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sabado'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
            dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 0,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''};
        $.datepicker.setDefaults($.datepicker.regional['pt-BR']);
        $("#datainicio").datepicker($.datepicker.regional['pt-BR']);
        $("#datafim").datepicker($.datepicker.regional['pt-BR']);
        $("#area").change(function() {
            $.ajax({
                type: "POST",
                data: {
                    codigo: $(this).val()
                },
                url: '<?php echo $this->url(array('controller' => 'consultarpareceristas', 'action' => 'ajaxcarregarsegmentos')); ?>',
                success: function(data) {
                    if(data) {
                        var dados = '<option value="">Todos</option>';
                        dados += data;
                        $("#segmento").html(dados);
                        $("#segmento").parent().fadeIn('fast');
                    } else {
                        $("#segmento").parent().fadeOut('fast');
                    }
                }
            });
        });
        $("#orgao").change(function() {
            $.ajax({
                type: "POST",
                data: {
                    idOrgao: $(this).val()
                },
                url: '<?php echo $this->url(array('controller' => 'consultarpareceristas', 'action' => 'ajaxcarregarpareceristas')); ?>',
                success: function(data) {
                    if(data) {
                        var dados = '';
                        dados += data;
                        $("#parecerista").html(dados);
                    } else {
                        var dados = '<option value=""> - Nenhum Parecerista para o Órgão Selecionado - </option>';
                        $("#parecerista").html(dados);
                    }
                }
            });

        });
    });
    function verificaDatas() {
        switch($("#periodo").val())
        {
            case '2':
                if ($("#datainicio").val() != '' && $("#datafim").val() != '') {
                    if (1 == compararDataInicialDataFinal($("#datainicio").val(),$("#datafim").val())) {
                        alert("A Data Inicial n\xE3o pode ser maior que a Final");
                    } else {
                        $('#formConsulta').submit();
                    }
                } else {
                    alert ("Coloque as datas");
                }
                break;
            case '1':
                if ($("#datainicio").val() < 1 ) {
                    alert("Coloque a Data");
                } else {
                    $('#formConsulta').submit();
                }
                break;
            default:
                $('#formConsulta').submit();
        }
    }
    function datas(valor) {
        switch(valor)
        {
            case 'exatamente':
                $("#datainicio").show();
                $("#datafim").val('');
                $("#datafim").hide();
                $("#ldata").hide();
                break;
            case 'entreDatas':
                $("#datainicio").show();
                $("#datafim").show();
                $("#ldata").show();
                break;
            default:
                $("#datafim").hide();
                $("#datainicio").hide();
                $("#ldata").hide();
                break;
        }
    }


function buscarPronac(v)
{
	if ( $("#pronac").val().length <= 0 )
	{
		$("#MsgPronac").html('Campo obrigat&oacute;rio!');
	}
	else if ( $("#pronac").val().length < 6 )
	{
		$("#MsgPronac").html('O Pronac deve ter no mínimo 6 caracteres!');
	}
	else{
		$("#MsgPronac").html('');
		dados = 'pronac=' + encodeURIComponent(v);
		enviar_pag('<?php echo $this->url(array('controller' => 'consultarpareceristas', 'action' => 'buscaprojeto')); ?>', dados, "orgaoERROR");
	}
}
</script>
<div id="titulo">
    <div><?php echo $this->titulo; ?><span>&nbsp;</span> <span class="voltar"><a href="javascript:history.back();">Voltar</a></span></div>
</div>
<div id="conteudo">
<div id="error"></div>

    <form id="formConsulta" method="post" action="<?php echo $this->url(array('controller' => 'consultarpareceristas', 'action' => 'tratardadosrelatoriopagamento')); ?>">
    	<input type="hidden" name="titulo" value="<?php echo $this->titulo; ?>" />
    	<input type="hidden" name="prod" value="1" />
        <table class="tabela" style="text-align: left;">
        	<tr>
        		<td width="120"><label for="name">PRONAC *</label></td>
                <td colspan="7">
                	<input type="text" class="input_simples valida numero" name="pronac" id="pronac" size="10" maxlength="7" onblur="buscarPronac(this.value);" size="7" />
                	&nbsp;<span id="MsgPronac" style="color:red;"></span>
                </td>
			</tr>
			<tr>
				<td><label for="name">Nome do projeto:</label></td>
				<td colspan="7">
					<div id="orgaoERROR" class="bold"></div>
                </td>
			</tr>
			<tr>
                <td><label for="produtos">Produtos </label></td>
                <td colspan="7">
                	<select name="filtro[produto]" class="input_simples" style="width: 250px;">
                		<option value="0">Todos</option>
                		<?php foreach ($this->produtos as $produtos){?>
                			<option value="<?php $produtos->idProduto; ?>"><?php echo $produtos->Descricao;?> </option>
                		<?php }?>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="tipo_produto">Tipo Produto </label></td>
                <td colspan="7">
                	<select name="filtro[tipo_produto]" class="input_simples" style="width: 250px;">
                		<option value="0">Todos</option>
                		<option value="1">Principal</option>
                        <option value="0">Secundário</option>
                    </select>
                </td>
            </tr>
            <tr>
            	 <td width="150"><label for="pagamentos">Pagamentos</label></td>
                 <td colspan="7">
                 	<select name="filtro[pagamento]" class="input_simples" style="width: 250px;">
                 		<option value="1">Efetuados </option>
                        <option value="0">Pendentes </option>
                    </select>
                </td>
           	</tr>
            <tr>
            	<td width="150"><label for="periodo">Período da Análise</label></td>
            	<td width="150">
            		<select name="filtro[periodo]" id="periodo" class="input_simples" style="width: 250px;" onchange="datas(this.value);">
            			<option value="0">Todos</option>
                        <option value="exatamente">Exatamente igual</option>
                        <option value="entreDatas">Entre dois valores</option>
                    </select>
                </td>
                <td colspan="6">
                	<input type="text" name="filtro[periodo][dataInicio]" id="datainicio" class="input_simples sumir" maxlength="10" value="" onkeyup="mascara(this, format_data);" onclick="limpar_campo(this, '00/00/0000');" onblur="restaurar_campo(this, '00/00/0000');" type="text">
                    <label id="ldata" class="sumir"> &agrave;</label>
                    <input type="text" name="filtro[periodo][datafim]" id="datafim" class="input_simples sumir" maxlength="10" value="" onkeyup="mascara(this, format_data);" onclick="limpar_campo(this, '00/00/0000');" onblur="restaurar_campo(this, '00/00/0000');" type="text">
                </td>
            </tr>
            <tr>
                <td align="center" colspan="8">
                    <input id="btn_localizar" type="button" value=" " class="btn_localizar"/>
                    <input type="reset" value=" " class="btn_limpar" />
                </td>
            </tr>
        </table>
    </form>
</div>
<span id="rodapeConteudo" style="width: 1543px;"><span></span></span>
<br clear="all" />