<main>
    <?php
    $links = array(
        array('Gerenciar Projetos' => array(
            'module' => 'readequacao',
            'controller' => 'readequacao-assinatura',
            'action' => 'gerenciar-assinaturas'
        )),
        array('Devolver' => array())
    );
    ?>
    <div class="content padding20">
        <form action="<?php
        echo $this->url(array(
                'module' => 'readequacao',
                'controller' => 'readequacao-assinatura',
                'action' => 'devolver-projeto'
            )) . "?IdPRONAC={$this->IdPRONAC}"
	       . "&idDocumentoAssinatura={$this->idDocumentoAssinatura}";
        ?>"
        method="post">
            <input type="hidden" name="IdPRONAC" value="<?php echo $this->IdPRONAC ?>" />
            <input type="hidden" name="idTipoDoAtoAdministrativo" value="<?php echo $this->idTipoDoAtoAdministrativo ?>" />
            <div class="row">
                <div class="col s1"></div>
                <div class="col s10">
                    <?php gerarBreadCrumb($links); ?>
                </div>
                <div class="col s1"></div>
            </div>
            <div class="row">
                <div class="col s1"></div>
                <div class="col s10">
                    <h3><?php echo $this->titulo ?></h3>
                </div>
                <div class="col s1"></div>
            </div>
            <div class="row">
                <div class="col s1"></div>
                <div class="col s3">
                    <label>PRONAC</label>
                    <p class="bordered padding20 bold">
                        <?php
                        echo $this->projeto['AnoProjeto'] . $this->projeto['Sequencial'];
                        ?>
                    </p>
                </div>
                <div class="col s7">
                    <label>Nome do Projeto</label>
                    <p class="bordered padding20 bold">

                        <?php
                        echo $this->projeto['NomeProjeto'];
                        ?>
                    </p>
                </div>
                <div class="col s1"></div>
            </div>
            <div class="row">
                <div class="col s1"></div>
                <div class="col s3">
                    <label>&Aacute;rea Cultural</label>
                    <p class="bordered padding20 bold">
                        <?php
                        echo $this->areaCultural['Descricao'];
                        ?>
                    </p>
                </div>
                <div class="col s4">
                    <label>Segmento Cultural</label>
                    <p class="bordered padding20 bold">
                        <?php
                        echo $this->segmentoCultural['Descricao'];
                        ?>
                    </p>
                </div>
                <div class="col s3">
                    <label>Enquadramento</label>
                    <p class="bordered padding20 bold">
                        <?php
                        echo ((int)$this->areaCultural['tp_enquadramento'] == 1) ? 'Artigo 26' : 'Artigo 18';
                        ?>
                    </p>
                </div>
                <div class="col s1"></div>
            </div>
            <div class="row">
                <div class="col s1"></div>
                <div class="col s10">
                    <p>
                        <label class="margin-bottom20">Motiva&ccedil;&atilde;o da avalia&ccedil;&atilde;o</label>
                    </p>
                    <div class="padding20 bordered">
                        <?php
                        echo $this->dadosEnquadramento['Observacao'];
                        ?>
                    </div>
                </div>
                <div class="col s1"></div>
            </div>
            <?php if($this->abertoParaDevolucao === true): ?>
            <div class="row">
                <div class="col s1"></div>
                <div class="col s10">
                    <p>
                        <label>Motiva&ccedil;&atilde;o da Devolu&ccedil;&atilde;o para nova avalia&ccedil;&atilde;o:</label>
                    </p>
                    <div class="padding20 bordered" style="height: 200px">
                        <textarea class="padding20 bordered"
                                  id="motivoDevolucao"
                                  name="motivoDevolucao"
                                  style="height: 100%"></textarea>
                    </div>
                </div>
                <div class="col s1"></div>
            </div>
            <?php endif; ?>
            <div class="row center-align">
                <a class="btn waves-effect waves-dark"
                   href="javascript:history.go(-1)">Voltar</a>
                <?php if($this->abertoParaDevolucao === true): ?>
                <button type="submit"
                        class="btn waves-effect waves-dark">Devolver</button>
                <?php endif; ?>
            </div>
        </form>
    </div>
    <br clear="all"/>
    <script type="text/javascript">
        jQuery(function ($) {

            var editorRico = $("#dsDespacho").editorRico({
                altura: 200,
                isLimitarCarateres: true
            });

            $("#formEnquadramentoProjeto").validate({
                rules: {
                    dsDespacho: {
                        validarPreenchimento: true,
                        validarPreenchimentoMaximo: true
                    }
                },
                messages: {
                    dsDespacho: {
                        validarPreenchimento: "Dado obrigat&oacute;rio n&atilde;o informado",
                        validarPreenchimentoMaximo: "limite excedido"
                    }
                },

                submitHandler: function (form) {
                    $("#container-progress").show();
                    form.submit();
                },
                invalidHandler: function (event, validator) {
                    Materialize.toast(validator.submitted.dsDespacho, 2000, '', function () {
                    });
                }
            });

            $.validator.addMethod("validarPreenchimento", function (value, element) {
                if (editorRico.contarCaracteres() > 0) {
                    return true;
                }
            });
            $.validator.addMethod("validarPreenchimentoMaximo", function (value, element) {
                if (editorRico.contarCaracteres() <= 1000) {
                    return true;
                }
            });
        });
    </script>
</main>
