<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Início">Início</a></li>
        <li class="last">Solicitar Alteração Projeto</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div> Solicitar Alteração Projeto     <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">


<table class="tabela"  >

            <tr>
            	<td class="titulo_tabela">Projeto Cultural</td>
            	 <tr>
            	 
            </tr>
      
            <tr>
            	<th>Detalhe do projeto</th>
            </tr>
            
</table>
<table class="tabela"  >
            <table class="tabela"  >
          <tr>
            	 <?php foreach ($this->resposta as $resposta) {?>    
            	<th >Proponente: 
            	<a href="alterarproponente/prop/<?php echo $this->escape($resposta->CgcCpf); ?>">Nome do Proponente</a> | 
            	<a href="alterarrazao/prop/<?php echo $this->escape($resposta->CgcCpf); ?>"">Razão Social</a></th>
            	 <?php } ?>
            </tr>            
</table>
<table class="tabela"  >           
            <tr>
            	<td class="titulo_dentro">Projeto 
            	 <?php foreach ($this->resposta as $resposta) {?>
            	<a href="<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/fichatecnica/prop/<?php echo $this->escape($resposta->CgcCpf); ?>/pron/<?php echo $this->escape($resposta->idPronac); ?>">Ficha Técnica</a> | 
            	<a href="<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/localrealizacao/prop/<?php echo $this->escape($resposta->CgcCpf); ?>/pron/<?php echo $this->escape($resposta->idPronac); ?>">Local de Realização</a> | 
            	<a href="<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/alterarnomeprojeto/prop/<?php echo $this->escape($resposta->CgcCpf); ?>/pron/<?php echo $this->escape($resposta->idPronac); ?>">Nome do Projeto</a> | 
            	<a href="<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/prorrogacaoprazo/prop/<?php echo $this->escape($resposta->CgcCpf); ?>/pron/<?php echo $this->escape($resposta->idPronac); ?>">Prorrogar Prazos</a>
            	<?php } ?>
            	</td>
            </tr>
</table>

<table class="tabela" >
            <tr>
                <td class="titulo_dentro">Identificação</td>                
            </tr>
            <?php foreach ($this->resposta as $resposta) {?>
            <tr>
                <td><strong>Pronac:</strong> <br>         <?php echo $this->escape($resposta->idPronac); ?></td>
                <td><strong>Nome do Projeto:</strong> <br><?php echo $this->escape($resposta->NomeProjeto); ?></td>
            </tr>
           
                     
           <tr>
                <td><strong>CNPJ / CPF:</strong> <br>
               <?php 
                	$arr2 = str_split($this->escape($resposta->CgcCpf), 3); 
                	echo $arr2["0"].".".$arr2["1"].".".$arr2["2"]."-".$arr2["3"]; 
                ?>
                </td>
                <td><strong>Proponente:</strong> <br><?php echo $this->escape($resposta->Nome); ?></td>
           </tr>
           <?php } ?>
</table>


<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />