<?php $idAgente = isset($this->idAgente) ? $this->idAgente : "false"; ?>
<script type="text/javascript">
    $(function(){
        $('.menuHorizontal').each(function(){
            var menu = this;
            $(menu).menu({
                content: $($(menu).attr('href')).html(),
                flyOut: true
            });
        });
    });

    /**
     * Funcao para mudar o perfil (órgao) do usuario
     */
    function alterarPerfil(GrupoOrgao){
        grupo = GrupoOrgao.substring(0, (i = GrupoOrgao.indexOf(':')));
        orgao = GrupoOrgao.substring(++i);

        url = '<?php echo $this->url(array('controller' => 'perfil', 'action' => 'alterarperfil', 'module' => 'autenticacao'), '', true); ?>';
        url+= '?codGrupo=' + grupo;
        url+= '&codOrgao=' + orgao;
        redirecionar(url);
    } // fecha funcao alterarPerfil()
</script>

<div id="combousuario" class="input-field">

    <select name="perfilXgrupo" id="perfilXgrupo" class="perfilXgrupo browser-default" onchange="alterarPerfil(this.value);">

        <?php if ($this->arrayGrupos): ?>
            <?php foreach ($this->arrayGrupos as $g){ ?>
                <option value="<?php echo $g->gru_codigo; ?>:<?php echo $g->uog_orgao; ?>"
                    <?php if ($g->gru_codigo == $this->grupoAtivo && $g->uog_orgao == $this->orgaoAtivo){ echo "selected=\"selected=\""; } ?>>
                    &nbsp; <?php echo $g->org_siglaautorizado; ?> - <?php echo $g->gru_nome; ?> &nbsp;
                </option>
            <?php } ?>
        <?php endif; ?>

        <?php if(!empty($this->arrayGrupoProponente)){ ?>
            <option value="<?php echo $this->arrayGrupoProponente["gru_codigo"]; ?>:<?php echo $this->arrayGrupoProponente["uog_orgao"]; ?>">&nbsp; <?php echo $this->arrayGrupoProponente["gru_nome"]; ?></option>
        <?php } ?>
    </select>
</div>
