<?php
    if (getenv('APPLICATION_ENV') != 'production') {
        $arrConf = array();
        $arrDb['PDO_MSSQL'] = 'SQL Server';
        $arrDb['PDO_PGSQL'] = 'Postgre SQL';

        $arrEnv = array();
        $arrEnv['development'] = 'Desenvolvimento';
        $arrEnv['testing']     = 'Homologa&ccedil;&atilde;o';
        $arrEnv['staging']     = 'Treinamento';

        $config = new Zend_Config_Ini(APPLICATION_PATH .'/configs/application.ini', APPLICATION_ENV);
        $strDb = $config->resources->db->adapter;
        $strEnv = getenv('APPLICATION_ENV');
    } else {
        $strDb = false;
        $strEnv = false;
    }
?>
<?php if ($strDb): ?>
    <div id="rodape" style="width: 1901px; top: 0; background: #36963f; ">
        <div style="background: transparent;"><strong><?php echo $arrEnv[$strEnv]; ?> | <?php echo $arrDb[$strDb]; ?></strong></div>
    </div>
<?php endif; ?>
