<?php
$dbTable = new Admissibilidade_Model_DbTable_TbMensagemProjeto();
$auth = Zend_Auth::getInstance();
$arrAuth = $auth->getIdentity();
$intQtd = count($dbTable->getAllBy(array('tbMensagemProjeto.idDestinatario' => $arrAuth->usu_codigo, 'tbMensagemProjeto.idMensagemOrigem IS NULL' => '')));
//$intQtd = count($dbTable->getAllBy(array('idDestinatario' => $arrAuth->usu_codigo, 'tbMensagemProjeto.idUnidade => $arrAuth->usu_orgao')));
if ($intQtd > 99) {
    $cssPadding = '1';
    $intQtd =  '99+';
} elseif ($intQtd > 9) {
    $cssPadding = '4';
} else {
    $cssPadding = '6';
}
?>
<style>
    .notificacao {
        margin-left: 15px;
        margin-top: 5px;
        /*display: inline;*/
    }
    .notificacao a {
        position: relative;
        padding: 0 !important;
        padding-top: 5px;
    }
    .notificacao .btn-floating {
        /*background-color: rgb(76, 175, 80);*/
        border-radius: 50%;
        color: #fff;
        cursor: pointer;
        height: 20px !important;
        width: 20px !important;
        line-height: 21px;
        /*overflow: hidden;*/
        /*padding: 0;*/
        position: relative;
        left: 8px;
        top: -10px;
        display: block;
        text-align: center;
        /*transition: all 0.3s ease 0s;*/
        vertical-align: middle;
        z-index: 1;
        font-size: 9px !important;
    }
    .notificacao .btn-floating p {
/*        display: block;*/
/*        text-align: center;*/
/*        left: */<?php //echo $cssPadding ?>/*px;*/
/*        line-height: 5pt;*/
/*        padding: 0 0 10px;*/
/*        position: absolute;*/
    }
</style>
<li class="noOverhere notificacao">
    <a href="/admissibilidade/mensagem">
        <i class="material-icons left">mail</i>
        <span class="btn-floating waves-effect waves-light orange darken-1"><?php echo $intQtd ?></span>
    </a>
</li>


