<?php
$CancelarHref = $this->url(array('controller' => 'Pesquisarprojetofiscalizacao', 'action' => 'parametropesquisa'));
$localizarHref = $this->url(array('controller' => 'Pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa'));
$carregaDadosHref = $this->url(array('controller' => 'Pesquisarprojetofiscalizacao', 'action' => 'carregadados'));
?>

<!-- ========== INICIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'grid')); ?>" title="Ir para Fiscalização do Projeto">Fiscalização do Projeto</a></li>
        <li class="last">Pesquisar projeto para fiscalização</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INICIO TITULO ========== -->
<div id="titulo">
    <div>Pesquisar Projeto para Fiscaliza&ccedil;&atilde;o <span class="voltar"><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'grid')); ?>">Voltar</a></span></div>
</div>
<!-- ========== FIM TITULO ========== -->


<div id="conteudo">
    <form action="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')); ?>" id="frLocalizar" method="get">
        <table class="tabela">
            <tr>
                <td width="150" class="destacar bold" align="right">PRONAC</td>
                <td><input type="text" name="pronac" id="pronac" autocomplete="off" sonumero="true" /></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Regi&atilde;o<span style="color: red;">*</span></td>
                <td>
                    <select class="campoForm" name="regiao" id="regiao" null="false">
                        <option value="" >- Selecione -</option>
                        <?php foreach ($this->regiao as $regiao) { ?>
                        <option value="<?php echo $regiao->Regiao; ?>" ><?php echo $regiao->Regiao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">UF<span style="color: red;">*</span></td>
                <td>
                    <select class="campoForm" name="uf" id="uf" null="false">
                        <option value="" >- Selecione -</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Cidade<span style="color: red;">*</span></td>
                <td>
                    <select class="campoForm" name="cidade" id="cidade" null="false">
                        <option value="" >- Selecione -</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Valor</td>
                <td>
                    <input class="campoForm" type="text" name="valorMenor" dinheiro="true" />
                    <input class="campoForm" type="text" name="valorMaior" dinheiro="true" />
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Mecanismo</td>
                <td>
                    <select class="campoForm" name="mecanismo" id="mecanismo">
                        <option value="" >- Selecione -</option>
                        <?php foreach ($this->mecanismo as $mecanismo) { ?>
                        <option value="<?php echo $mecanismo->Codigo; ?>" ><?php echo $mecanismo->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td height="27" class="destacar bold" align="right">Plano Anual</td>
                <td><input class="campoForm" type="checkbox" name="planoAnual" value="sim" /></td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Situação do Projeto</td>
                <td>
                    <select class="campoForm" name="situacaoprojeto" id="situacaoprojeto">
                        <option value="" >- Selecione -</option>
                        <?php foreach ($this->situacaoprojeto as $situacaoprojeto) { ?>
                        <option value="<?php echo $situacaoprojeto->Codigo; ?>" ><?php echo $situacaoprojeto->Codigo . ' - ' . $situacaoprojeto->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Área</td>
                <td>
                    <select class="campoForm" name="area" id="area">
                        <option value="" >- Selecione -</option>
                        <?php foreach ($this->area as $area) { ?>
                        <option value="<?php echo $area->Codigo; ?>" ><?php echo $area->Descricao; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="destacar bold" align="right">Segmento</td>
                <td>
                    <select class="campoForm" name="Segmento" id="Segmento">
                        <option value="" >- Selecione -</option>
                    </select>
                </td>
            </tr>
        </table>
        <p align="center"><input id="btSubmit" type="button" class="btn_localizar" value=""/></p>
    </form>
    <br clear="all" />
</div>

<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />


<script type="text/javascript">
    $(function(){
        mascaras('#frLocalizar');
        $('#pronac').keyup(function(event){
            if($('#pronac').val().length >= 1){
                $('#frLocalizar').find('input, select').each(function(){
                    var validar = false;
                    if($(this).attr('name') != 'pronac'){
                        if($(this).attr('type')=='checkbox'){
                            $(this).removeAttr('checked');
                            validar =  true;
                        }
                        if($(this).attr('type')=='select-one'){
                            $(this).val('');
                            validar =  true;
                        }
                        if($(this).attr('type')=='text'){
                            $(this).val('');
                            validar =  true;
                        }
                    }
                    if(validar){
                        $(this).attr('disabled','true');
                    }
                });
            }else{
                $('#frLocalizar').find('input, select').each(function(){
                    if($(this).attr('name') != 'pronac' || $(this).attr('type')=='select-one' || $(this).attr('type')=='text'){
                        $(this).removeAttr('disabled');
                    }
                });
            }
        });

        $('#regiao').change(function(){
            carregarPgHtml('<?php echo $carregaDadosHref; ?>','#uf',{option:'uf',regiao:$(this).val()},'- Selecione -');
            carregarPgHtml('<?php echo $carregaDadosHref; ?>','#cidade',{option:'cidade',idUF:$('#uf').val()},'- Selecione -');            
        });

        $('#uf').change(function(){
            carregarPgHtml('<?php echo $carregaDadosHref; ?>','#cidade',{option:'cidade',idUF:$(this).val()},'- Selecione -');
        });

        $('#area').change(function(){
            carregar_combo(this.value, 'Segmento', '<?php echo $this->url(array('controller' => 'segmentocultural', 'action' => 'combo-z')); ?>', '- Selecione -');
        });
        
        $('#frLocalizar').submit(function(){
            return validarFormulario('#frLocalizar','Dados obrigat&oacute;rios n&atilde;o informados.');
        });
        
        $('#btSubmit').click(function(){
            if($('#pronac').val().length > 0){
                $('#regiao, #uf, #cidade').attr('null','true');
                $('#frLocalizar').submit();
            }else{
                $('#frLocalizar').submit();
            }
        })
    });

    function mascaras(form){
        $('input[type!=submit]|[type!=button]').addClass('input_simples');
        $('textarea').addClass('textarea_simples');
        $('select[id!=perfilXgrupo]').addClass('select_simples');
        $(form).find('[data=true]').each(function(){
            $(this).keyup(function(){
                mascara(this,format_data);
                var este = this;
                setTimeout(function(){
                    $(este).val($(este).val().substr(0,10));
                },2);
            });
            $(this).datepicker({
                showOn: 'button',
                buttonImage: '<?php echo $this->baseUrl(); ?>/public/img/ico/calendar.gif',
                buttonImageOnly: true,
                dateFormat:'dd/mm/yy'
            });
        });
        $(form).find('[sonumero=true]').keyup(function(){
            mascara(this,format_num);
        });
        $(form).find('[dinheiro=true]').keyup(function(){
            mascara(this,format_moeda);
        });

        $(form).find('[cnpjcpf=true]').each(function(){
            var este = this;
            $('.'+$(este).attr('classaux')).click(function(){
                mascaraCNPJCPF(este);
                buscarFornecedor(este);
            });
        });
        $(form).find('[cnpjcpf=true]').keyup(function(){
            mascaraCNPJCPF(this);
            buscarFornecedor(this);
        });
    }
    function validarFormulario(form,mensagem){
        var validar = false;
    
        if(mensagem== undefined){
            mensagem = '';
        }

        $(form).find('[data=true]').each(function(){
            var estadata =   $(this).val().slice(6,10)+''+$(this).val().slice(3,5)+''+$(this).val().slice(0,2);

            if($(this).attr('menorque')!=undefined){
                var menorid     =   '#'+$(this).attr('menorque');
                if($(menorid).val() != ''){
                    var menordata   =   $(menorid).val().slice(6,10)+''+$(menorid).val().slice(3,5)+''+$(menorid).val().slice(0,2);
                    if(estadata > menordata){
                        validar     =   true;
                        mensagem    +=   '<br />A "'+$(this).attr('title')+'" deve ser menor que a "'+$(menorid).attr('title')+'"';
                    }
                }
            }
            if($(this).attr('maiorque')!=undefined){
                var maiorid     =   '#'+$(this).attr('maiorque');
                if($(maiorid).val() != ''){
                    var maiordata   =   $(maiorid).val().slice(6,10)+''+$(maiorid).val().slice(3,5)+''+$(maiorid).val().slice(0,2);
                    if(estadata < maiordata){
                        validar = true;
                        mensagem    +=   '<br />A "'+$(this).attr('title')+'" deve ser maior que a "'+$(maiorid).attr('title')+'"';
                    }
                }
            }
        });

        $(form).find('[null=false]').each(function(){
            if($(this).attr('type')=='radio'){
                var validaRadio = true;
                $(form+' [name='+$(this).attr('name')+']').each(function(){
                    if($(this).attr('checked'))
                        validaRadio = false;
                });
                if(validaRadio)
                    validar = true;
            }else{
                if($.trim($(this).val()).length == 0)
                    validar = true;
            }
        });

        if(validar){
            janelaAlerta(mensagem);
            return false;
        }
        else
            return true;
    }
    function buscarJson(pagina,dados){
        var retorno = '';
        var select = requisicaoAjaxObj();
        select.executar({
            pagina          :   pagina,
            parametros      :   dados,
            resposta        :   undefined,
            async           :   false,
            funcaoRetorno   :   function (resposta){
                retorno = resposta;
            }
            ,dataType        :   'json'
        });
        return retorno;
    }
    function carregarPgHtml(pagina,idSelect,dados,textoIni){
        if(textoIni == undefined)
            textoIni = 'Todos';
        var select      = '<option value="">'+textoIni+'</option>';
        var resposta    = buscarJson(pagina,dados);
        for(var j in resposta){
            select += '<option value="'+resposta[j].id+'">'+resposta[j].nome+'</option>';
        }
        $(idSelect).html(select);

    }
    function carregarRegiaoPronac(pagina,idSelect,dados,form){

        var resposta    = buscarJson(pagina,dados);
        
        if(resposta.length > 0){
            $(idSelect).attr('name','regiaoFake');
            $(idSelect).attr('null','true');
//
//            var input = $('<input>')
//            .attr('type','hidden')
//            .attr('name','regiao')
//            .attr('null','false')
//            .val(resposta);
//
//            input.appendTo(form);
            return true;
        }else{
            return false;
        }
    }
    function buscarJsonAux(pagina,dados){
        var retorno = '';
        var select = requisicaoAjaxObj();
        select.executar({
            pagina          :   pagina,
            parametros      :   dados,
            resposta        :   undefined,
            async           :   false,
            funcaoRetorno   :   function (resposta){
                alert(resposta);
                retorno = resposta;
            }
            //,dataType        :   'json'
        });
        return retorno;
    }
    function carregarPgHtmlAux(pagina,idSelect,dados,textoIni){
        var resposta    = buscarJsonAux(pagina,dados);
    }
    function requisicaoAjaxObj(){
        var ajaxObj={
            pagina          :   '',
            parametros      :   {},
            type            :   'post',
            dataType        :   '',
            resposta        :   '#conteudo',
            async           :   true,
            funcaoRetorno   :   function (resposta){
                $(this.resposta).html(resposta);
            },
            executar        :   function(dados){
                this.refineParametrosObj(dados);
                var esteObj = this;
                if(this.resposta != undefined && this.resposta != '')
                    $(this.resposta).html('<img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" alt="carregando"><br/><br/>Carregando...<br>Por Favor, aguarde!!');
                $.ajax({
                    type      : esteObj.type,
                    url       : esteObj.pagina,
                    data      : esteObj.parametros,
                    async     : esteObj.async,
                    success   : function(resp){
                        esteObj.funcaoRetorno(resp);
                    }
                    ,dataType  : esteObj.dataType
                });
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){

                        this[j]=data[j];
                    }
            }
        }
        return ajaxObj;
    }
    function janelaAlerta(mensagem,funcaoAdcional){
        if(funcaoAdcional==undefined){
            funcaoAdcional = function(){}
        }
        var nomeJanelaAlerta =   janelaObj({
            parametros : {
                width:      400,
                autoOpen:   false,
                resizable:  false,
                modal:      true,
                buttons: {
                    OK: function() {
                        funcaoAdcional();
                        $(this).dialog('close');
                    }
                }
            },
            removerBtFechar:true,
            title : 'Alerta'
        });
        nomeJanelaAlerta.divConteudo.html(mensagem);
        nomeJanelaAlerta.abrirJanela();

        return nomeJanelaAlerta;
    }
    function janelaObj(dados){
        var divConteudo = $('<div></div>')
        .attr('title',dados.title)
        .appendTo('body');
        var novaJanela = {
            divConteudo : divConteudo,
            removerBtFechar: true,
            parametros : {autoOpen: false},
            iniciarJanela : function(dados){
                this.refineParametrosObj(dados);

                this.divConteudo.dialog(this.parametros);
            },
            abrirJanela:function(){
                this.divConteudo.dialog('open');
                if(this.removerBtFechar)
                    $('.ui-dialog-titlebar-close').remove();
            },
            fecharJanela:function(){
                this.divConteudo.dialog('close');
                this.divConteudo.remove();
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){
                        this[j]=data[j];
                    }
            }
        }
        novaJanela.iniciarJanela(dados);
        return novaJanela;
    }
</script>
