<?php $parametros = '&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => 'index'));?>">Início</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'grid'));?>">Fiscalização do Projeto</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'parametropesquisa'));?>">Pesquisar projeto para fiscalização</a></li>
        <li class="last">Resultado da Pesquisa</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Resultado da Pesquisa</div>
</div>


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

    <?php if(count($this->dados)>0){ ?>
    <!-- ============ PAGINAÇÃO ============ -->
    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr>
                <td align="center">
                <form name="form1" id="form1" action="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa'));?>" method="get">
                    <?php if($this->paginacao['pag']>1) { ?>
                    <input style="width: 88px;" class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'">
                    <?php } ?>
                    <input style="width: 88px;" id="btn_p_anterior" type="button"
                    <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                    <?php }else { ?>
                           class="btn_p_anterior"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'"
                    <?php } ?>>
                    <input style="width: 88px;"  id="btn_p_proximo" type="button"
                           <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                           class="btn_p_proximo-off"
                    <?php }else { ?>
                           class="btn_p_proximo"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'"
                    <?php } ?>>
                    <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                    <input style="width: 88px;" class="btn_ultimo" id="btn_ultimo" type="button"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'">
                    <?php } ?>
                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()" class="input_simples">
                        <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++){ ?>
                        <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                        <?php } ?>
                    </select>
                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                    <input type="hidden" name="pronac" value="<?php echo $this->filtros->pronac;?>">
                    <input type="hidden" name="regiao" value="<?php echo $this->filtros->regiao;?>">
                    <input type="hidden" name="uf" value="<?php echo $this->filtros->uf;?>">
                    <input type="hidden" name="cidade" value="<?php echo $this->filtros->cidade;?>">
                    <input type="hidden" name="valorMenor" value="<?php echo $this->filtros->valorMenor;?>">
                    <input type="hidden" name="valorMaior" value="<?php echo $this->filtros->valorMaior;?>">
                    <input type="hidden" name="mecanismo" value="<?php echo $this->filtros->mecanismo;?>">
                    <input type="hidden" name="situacaoprojeto" value="<?php echo $this->filtros->situacaoprojeto;?>">
                    <input type="hidden" name="area" value="<?php echo $this->filtros->area;?>">
                    <input type="hidden" name="Segmento" value="<?php echo $this->filtros->Segmento;?>">
                 </form>
                </td>
            </tr>
        </tbody>
    </table>
    <center>
        <?php
            echo $this->paginacao['inicio']." a ";
            echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
            echo " de ". $this->paginacao['total'];
        ?>
    </center>
    <!-- ========== FIM PAGINAÇÃO ========== -->
    <?php } ?>


    <?php if($this->qtdDocumentos != 0){ ?>
    <table class="tabela tablesorter">
        <thead>
            <tr class="titulo_tabela">
                <th><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag=1&qtde='.$this->paginacao['qtde'].'&campo=IdPRONAC&ordem='.$this->paginacao['novaOrdem'].$parametros; ?>">PRONAC</a></th>
                <th><a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag=1&qtde='.$this->paginacao['qtde'].'&campo=NomeProjeto&ordem='.$this->paginacao['novaOrdem'].$parametros; ?>">Nome do Projeto</a></th>
                <th>Região</th>
                <th>UF</th>
                <th>Cidade</th>
                <th>Área</th>
                <th>Segmento</th>
                <th>Valor</th>
                <th>Mecanismo</th>
                <th>Plano Anual</th>
                <th>Fiscalizar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->dados as $d){ ?>
            <tr>
                <td align="center">
                    <a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($d->IdPRONAC); ?>" target="_blank">
                        <?php echo $d->AnoProjeto.$d->Sequencial; ?>
                    </a>
                </td>
                <td><?php echo $d->NomeProjeto; ?></td>
                <td><?php echo $d->Regiao; ?></td>
                <td align="center"><?php echo $d->uf; ?></td>
                <td><?php echo $d->cidade; ?></td>
                <td><?php echo $d->dsArea; ?></td>
                <td><?php echo $d->dsSegmento; ?></td>
                <td><?php echo 'R$ '.number_format($d->somatorio, 2, ',', '.'); ?></td>
                <td><?php echo $d->dsMecanismo; ?></td>
                <td><?php echo ($d->stPlanoAnual == 0) ? 'Não' : 'Sim'; ?></td>
                <td align="center">
                    <a href="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'oficializarfiscalizacao')).'?idPronac='.$d->IdPRONAC; ?>"><img src="../public/img/btn_busca.gif" alt="Dados da Fiscalização"/></a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php if(count($this->dados)>0){ ?>

        <!-- ============ PAGINAÇÃO ============ -->
        <?php if($this->qtdDocumentos > 10) { //echo $this->dados; ?>
        <center>
            <?php
                echo $this->paginacao['inicio']." a ";
                echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                echo " de ". $this->paginacao['total'];
            ?>
        </center>
        <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td align="center">
                    <form name="form2" id="form2" action="<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa'));?>" method="get">
                        <?php if($this->paginacao['pag']>1) { ?>
                        <input style="width: 88px;" class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'">
                        <?php } ?>
                        <input style="width: 88px;" id="btn_p_anterior" type="button"
                        <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                        <?php }else { ?>
                               class="btn_p_anterior"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'"
                        <?php } ?>>
                        <input style="width: 88px;"  id="btn_p_proximo" type="button"
                               <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                               class="btn_p_proximo-off"
                        <?php }else { ?>
                               class="btn_p_proximo"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'"
                        <?php } ?>>
                        <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                        <input style="width: 88px;" class="btn_ultimo" id="btn_ultimo" type="button"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'pesquisarprojetofiscalizacao', 'action' => 'resultadopesquisa')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&pronac='.$this->filtros->pronac.'&regiao='.$this->filtros->regiao.'&uf='.$this->filtros->uf.'&cidade='.$this->filtros->cidade.'&valorMenor='.$this->filtros->valorMenor.'&valorMaior='.$this->filtros->valorMaior.'&mecanismo='.$this->filtros->mecanismo.'&situacaoprojeto='.$this->filtros->situacaoprojeto.'&area='.$this->filtros->area.'&Segmento='.$this->filtros->Segmento; ?>'">
                        <?php } ?>
                        Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()" class="input_simples">
                            <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++){ ?>
                            <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                            <?php } ?>
                        </select>
                        &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                        <input type="hidden" name="pronac" value="<?php echo $this->filtros->pronac;?>">
                        <input type="hidden" name="regiao" value="<?php echo $this->filtros->regiao;?>">
                        <input type="hidden" name="uf" value="<?php echo $this->filtros->uf;?>">
                        <input type="hidden" name="cidade" value="<?php echo $this->filtros->cidade;?>">
                        <input type="hidden" name="valorMenor" value="<?php echo $this->filtros->valorMenor;?>">
                        <input type="hidden" name="valorMaior" value="<?php echo $this->filtros->valorMaior;?>">
                        <input type="hidden" name="mecanismo" value="<?php echo $this->filtros->mecanismo;?>">
                        <input type="hidden" name="situacaoprojeto" value="<?php echo $this->filtros->situacaoprojeto;?>">
                        <input type="hidden" name="area" value="<?php echo $this->filtros->area;?>">
                        <input type="hidden" name="Segmento" value="<?php echo $this->filtros->Segmento;?>">
                     </form>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- ========== FIM PAGINAÇÃO ========== -->

    <?php } } ?>


    <?php } else { ?>
    <!--<table class="tabela">
        <tr>
            <td align="center">NENHUM PRODUTO PARA DISTRIBUIR!</td>
        </tr>
    </table>-->
    <?php } ?>
    <br clear="all" />


    <form target="_blank" class="form" name="formRegularidade" id="formRegularidade" method="post" action='<?php echo $this->url(array('controller' => 'manterregularidadeproponente', 'action' => 'manterregularidadeproponente')); ?>'>
        <input type="hidden" name="cpfCnpj" id="cpfCnpj" value="" />
    </form>

</div>
<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />
