<style>
    .dt-button {
        left: 234px;
        top: 33px;
    }

    div.expansivel {
        display: none;
    }

    table.dataTable tbody td.no-padding {
        padding: 0;
    }
</style>

<main>
    <?php
    $links = array(
        array('Gerenciar Assinaturas' => array())
    );
    ?>
    <div class="content padding20 clearfix">

        <div class="row">
            <div class="col s10">
                <?php gerarBreadCrumb($links); ?>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="stripped" id="assinaturaProjetos">
                    <thead>
                    <tr>
                        <th align="center" width="40">PRONAC</th>
                        <th>Nome do Projeto</th>
                        <th>Dias</th>
                        <th>Tipo</th>
                        <th>A&ccedil;&atilde;o</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="center-align" id="divAssinaturaEmMassa"
                     style="display: none;">
                    <input type="hidden" id="idTipoDoAtoAdministrativo" value="" />
                    <button class="btn waves-effect waves-light" type="submit" name="action" id="enviarAssinaturaEmMassa">
                        Assinar em massa <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="/public/js/jquery-1.12.4.min.js"></script>
    <script src="/public/js/moment.js"></script>
    <script type="text/javascript" src="/public/scripts/layout/datatables.min.js"></script>
    <script src="/public/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="/public/js/buttons.print.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="/public/css/layout/datatables.min.css"/>

    <script type="text/javascript">
     (function ($) {
         $(document).ready(function () {

             $(document).ajaxStart(function () {
                 $('#container-loading').fadeIn('slow');
             });

             $(document).ajaxComplete(function () {
                 $('#container-loading').fadeOut('slow');
             });

             var assinaturaProjetos = $('#assinaturaProjetos').DataTable({
                 dom: 'Blfrtip',
                 buttons: [
                     {
                         title: '',
                         text: '<i class="material-icons">print</i>',
                         orientation: 'landscape',
                         extend: 'print',
                         className: 'waves-effect waves-dark btn white black-text',
                         exportOptions: {
                             columns: [0, 1, 2, 3, 4]
                         }
                     }
                 ],
                 initComplete: function () {
                     this.api().columns().every(function () {
                         var column = this;
                         var searchIndex = 0;
                         $("#seletorSelect").change(function () {
                             if (column[0].includes(searchIndex)) {
                                 column.search($("#seletorSelect").val()).draw();
                             }
                         });
                     });
                     this.api().columns(3).every(function () {
                         var column = this;
                         var select = $('<select class="btn grey lighten-3 black-text"><option value="">filtrar por Tipo de Assinatura</option></select>')
                             .appendTo( $(column.header()).empty() )
                             .on( 'change', function () {
                                 let val = '';
                                 val = $.fn.dataTable.util.escapeRegex(
                                     $(this).val()
                                 );
                                 column
                                     .search( val ? '^'+ val+'$': '', true, false )
                                     .draw();

                                 val = val.replace(/\\/, '');

                                 $('#assinaturaProjetos_filter input').val(val);
                                 $('#assinaturaProjetos_filter input').keyup();

                                 if (val !== '') {
                                     $('#marcarDesmarcarCheckbox').removeProp('disabled');
                                 } else {
                                     $('#marcarDesmarcarCheckbox').prop('disabled', true);
                                 }
                                 $('#marcarDesmarcarCheckbox').prop('checked', false);
                             });
                         column.data().unique().sort().each( function( d, j ) {
                             select.append('<option value="'+ d + '">' + d + '</option>');
                         });
                     });
                 },
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Todos"]],
                 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                 },
                 "ajax": {
                     url: "/assinatura/index/documentos-devolvidos-ajax/",
                     data: {},
                     type: "POST"
                 },
                 "autoWidth": false,
                 "serverSide": true,
                 "searchDelay": 350,
                 "order": [2],
                 "columnDefs": [
                     {"className": "dt-center", "targets": [0, 2, 4]},
                     {'bSortable': true, 'aTargets': [1]},
                 ],
                 "columns": [
                     {
                         "targets": 0,
                         "data": null,
                         "name": "pronac",
                         render: (data) => {
                             return '<a class="waves-effect waves-dark btn white black-text" ' +
                                    'href="/default/consultardadosprojeto/index?idPronac=' + data.IdPRONAC + '"><u> ' +
                                    data.pronac +
                                    '</u></a>';
                         }
                     },
                     {
                         "targets": 1,
                         "data": "nomeProjeto",
                         "name": "nomeProjeto"
                     },
                     {
                         "targets": 2,
                         "data": null,
                         "name": "dias",
                         render: (data) => {
                             return (parseInt(data.dias, 10) > 1) ? data.dias + ' dias' : '-';
                         }
                     },
                     {
                         "targets": 3,
                         "data": 'tipoDoAtoAdministrativo',
                         "name": 'tipoDoAtoAdministrativo',
                         "orderable": false,
                     },
                     {
                         "targets": 4,
                         "data": null,
                         render: (data) => {
                             let botaoVisualizar = '<a class="btn-floating waves-effect waves-light btn-primary tooltipped" ' +
                                                   ' href="/assinatura/index/visualizar-projeto?idDocumentoAssinatura=' + data.idDocumentoAssinatura + '"' +
                                                   ' data-position="top"' +
                                                   ' data-delay="50"' +
                                                   ' data-tooltip="Visualizar">' +
                                                   ' <i class="material-icons">search</i>' +
                                                   ' </a>';

                             return '<div style="position: relative; height: 60px;">'
                                  + '<div class="fixed-action-btn horizontal" style="position: absolute; top: 0px; right: 0; z-index: 996; padding: 15px 0 0 15px;">'
                                  + '<a class="btn btn-primary small">'
                                  + '<i class="material-icons">more_vert</i></a>'
                                  + '<ul>'
                                  + '<li>'
                                  + botaoVisualizar
                                  + '</li>'
                                  + '</ul>'
                                  + '</div>';

                             return stringBotoes;
                         }
                     },
                 ]
             });
         });
     }($.noConflict(true)));
    </script>
</main>
