<style>
    .dt-button {
        left: 234px;
        top: 33px;
    }

    div.expansivel {
        display: none;
    }

    table.dataTable tbody td.no-padding {
        padding: 0;
    }
</style>

<main>
    <?php
    $links = array(
        array('Gerenciar Assinaturas' => array())
    );
    ?>
    <div class="content padding20 clearfix">

        <div class="row">
            <div class="col s10">
                <?php gerarBreadCrumb($links); ?>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="stripped" id="assinaturaProjetos">
                    <thead>
                    <tr>
                        <th>
                            <input type="checkbox"
                                   name="marcarDesmarcarCheckbox"
                                   id="marcarDesmarcarCheckbox"
                                   class="filled-in"/>
                            <label id="marcarDesmarcarCheckboxLabel"
                                   for="marcarDesmarcarCheckbox"></label>
                        </th>
                        <th>&nbsp</th>
                        <th align="center" width="40">PRONAC</th>
                        <th>Nome do Projeto</th>
                        <th>&Aacute;rea / Segmento</th>
                        <th>Dias</th>
                        <th>Tipo</th>
                        <th>A&ccedil;&atilde;o</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="center-align" id="divAssinaturaEmMassa"
                     style="display: none;">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Assinar em massa <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="/public/js/jquery-1.12.4.min.js"></script>
    <script src="/public/js/moment.js"></script>
    <script type="text/javascript" src="/public/scripts/layout/datatables.min.js"></script>
    <script src="/public/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="/public/js/buttons.print.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="/public/css/layout/datatables.min.css"/>

    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {

                $(document).ajaxStart(function () {
                    $('#container-loading').fadeIn('slow');
                });

                $(document).ajaxComplete(function () {
                    $('#container-loading').fadeOut('slow');
                });

                $(document).on('click', "#marcarDesmarcarCheckboxLabel", function () {
                    $3('.checkbox_legal').prop("checked", !$3($("#marcarDesmarcarCheckbox")).prop("checked"));
                    tratarExibicaoCheckboxChecados('.checkbox_legal', '#divAssinaturaEmMassa');
                });

                function tratarExibicaoCheckboxChecados(seletorCheckboxes, seletorExibicao) {
                    var quantidadeCheckboxChecados = $(seletorCheckboxes).filter(':checked').length;
                    $(seletorExibicao).hide('fast');
                    if (quantidadeCheckboxChecados > 0) {
                        $(seletorExibicao).show('fast');
                    }
                }

                $(document).on('click', '.checkbox_legal', function () {
                    var quantidadeCheckBoxesSelecionados = $('.checkbox_legal').filter(':checked').length;
                    var isCheckBoxAtualSelecionado = ($(this).filter(':checked').length > 0);

                    $("#idTipoDoAtoAdministrativo").val(null);
                    if (quantidadeCheckBoxesSelecionados == 1) {
                        $("#idTipoDoAtoAdministrativo").val($(this).data('idtipoatoadministrativo'))
                    } else if (quantidadeCheckBoxesSelecionados > 1) {
                        if (isCheckBoxAtualSelecionado && $(this).data('idtipoatoadministrativo') != $("#idTipoDoAtoAdministrativo").val()) {
                            Materialize.toast("O Encaminhamento em massa só é permitido para projetos com o mesmo Tipo de Ato Administrativo.", 4000);
                            $(this).trigger('click');
                        }
                    }
                    tratarExibicaoCheckboxChecados('.checkbox_legal', '#divAssinaturaEmMassa');
                });


                var assinaturaProjetos = $('#assinaturaProjetos').DataTable({
                    dom: 'Blfrtip',
                    buttons: [
                        {
                            title: '',
                            text: '<i class="material-icons">print</i>',
                            orientation: 'landscape',
                            extend: 'print',
                            className: 'waves-effect waves-dark btn white black-text',
                            exportOptions: {
                                columns: [2, 3, 4, 5, 6]
                            }
                        }
                    ],
                    initComplete: function () {
                        this.api().columns().every(function () {
                            var column = this;
                            var searchIndex = 0;
                            $("#seletorSelect").change(function () {
                                if (column[0].includes(searchIndex)) {
                                    column.search($("#seletorSelect").val()).draw();
                                }
                            });
                        });
                    },
                    "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Todos"]],
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                    },
                    "ajax": {
                        url: "/assinatura/index/gerenciar-assinatura-ajax/",
                        data: {},
                        type: "POST"
                    },
                    "autoWidth": false,
                    "serverSide": true,
                    "searchDelay": 350,
                    "columnDefs": [
                        // { "width": "1%", "targets": 0 },
                        // { "width": "20%", "targets": 2 },
                        // { "width": "10%", "targets": 3 },
                        // { "width": "5%", "targets": [5,6,7,9] },
                        {"className": "dt-center", "targets": [0, 1, 2, 5, 7]},
                        {'bSortable': true, 'aTargets': [0, 1, 7]},
                    ],
                    "columns": [
                        {
                            "targets": 0,
                            "data": null,
                            "name": "IdPRONAC",
                            render: (data) => {
                                let assinarEmMassa = '<input type="checkbox" ' +
                                    'name="IdPRONAC[]" ' +
                                    'id="IdPRONAC' + data.IdPRONAC + '"' +
                                    'class="checkbox_legal filled-in"' +
                                    'value="' + data.IdPRONAC + '" ' +
                                    'data-idtipoatoadministrativo="' + data.idTipoDoAtoAdministrativo + '" ' +
                                    '/> ' +
                                    '<label for="IdPRONAC' + data.IdPRONAC + '" data-idtipoatoadministrativo="' + data.idTipoDoAtoAdministrativo + '">' +
                                    '</label>';

                                return assinarEmMassa;
                            }
                        },
                        {
                            "targets": 1,
                            "data": null,
                            "name": "IdPRONAC",
                            render: () => {
                                return '<button class="btn small waves-effect waves-light btn-secondary expand"><i class="material-icons">expand_more</i></button>';
                            }
                        },
                        {
                            "targets": 2,
                            "data": null,
                            "name": "pronac",
                            render: (data) => {
                                return '<a class="waves-effect waves-dark btn white black-text" ' +
                                    'href="/consultardadosprojeto/index?idPronac=' + data.IdPRONAC + '"><u> ' +
                                    data.pronac +
                                    '</u></a>';
                            }
                        },
                        {
                            "targets": 3,
                            "data": "nomeProjeto",
                            "name": "nomeProjeto"
                        },
                        {
                            "targets": 4,
                            "data": null,
                            "name": "area",
                            render: (data) => {
                                return data.area + ' / ' + data.segmento;
                            }
                        },
                        {
                            "targets": 5,
                            "data": null,
                            "name": "dias",
                            render: (data) => {
                                return (parseInt(data.dias, 10) > 1) ? data.dias + ' dias' : '-';
                            }
                        },
                        {
                            "targets": 6,
                            "data": 'tipoDoAtoAdministrativo',
                            "name": 'tipoDoAtoAdministrativo',
                        },
                        {
                            "targets": 7,
                            "data": null,
                            render: (data) => {
                                let botaoVisualizar = '<a class="btn-floating waves-effect waves-light btn-primary tooltipped" ' +
                                    ' href="/assinatura/index/visualizar-projeto?idDocumentoAssinatura=' + data.idDocumentoAssinatura + '"' +
                                    ' data-position="top"' +
                                    ' data-delay="50"' +
                                    ' data-tooltip="Visualizar">' +
                                    ' <i class="material-icons">search</i>' +
                                    ' </a>';
                                let botaoAssinar = '<a class="btn-floating waves-effect waves-light btn-primary tooltipped" ' +
                                    ' href="/assinatura/index/assinar-projeto?IdPRONAC=' + data.IdPRONAC +
                                    '&idTipoDoAtoAdministrativo=' + data.idTipoDoAtoAdministrativo + '"' +
                                    ' data-position="top" ' +
                                    ' data-delay="50" ' +
                                    ' data-tooltip="Assinar"> ' +
                                    ' <i class="material-icons">create</i> ' +
                                    ' </a>';

                                return '<div style="position: relative; height: 60px;">'
                                    + '<div class="fixed-action-btn horizontal" style="position: absolute; top: 0px; right: 0; z-index: 996; padding: 15px 0 0 15px;">'
                                    + '<a class="btn btn-primary small">'
                                    + '<i class="material-icons">more_vert</i></a>'
                                    + '<ul>'
                                    + '<li>'
                                    + botaoVisualizar
                                    + botaoAssinar
                                    + '</li>'
                                    + '</ul>'
                                    + '</div>';

                                return stringBotoes;
                            }
                        },
                    ]
                });

                function informacoes(data) {

                    let htmlBotoes = '', corBotao = '';

                    for(var contadorAssinatura = 1; contadorAssinatura <= data.quantidadeTotalAssinaturas; contadorAssinatura++) {
                        corBotao = 'grey lighten-4 black-text';
                        if(contadorAssinatura <= data.quantidadeAssinaturas) {
                            corBotao = 'light-green darken-1'
                        }
                        if(contadorAssinatura > 1) {
                            htmlBotoes += '<div style="display:inline-block"><i class="tiny material-icons">arrow_forward</i></div>';
                        }
                        htmlBotoes += '<div style="display:inline-block"><a class="margin20 btn-floating btn-large waves-effect waves-light ' + corBotao + '">' + contadorAssinatura + '</a></div>'
                    }

                    return '<div class="expansivel">' +
                        '<div class="col s12">' +
                        '<div class="card">' +
                        '<div class="card-content">' +

                        '<div class="row" style="text-align: center;">' +
                        '<div clas="row">' +
                        '<b>Fase atual do Projeto </b>' +
                        '</div>' +

                        '<div style="vertical-align:middle;">' +
                        htmlBotoes +
                        '</div>' +
                        '</div>' +


                        '<div clas="row">' +
                        '<b>Resumo do Projeto </b>' + data.ResumoProjeto +
                        '</div>' +
                        '<div clas="row">' +
                        '<b>Tipo do ato administrativo: </b>' + data.tipoDoAtoAdministrativo +
                        '</div>' +
                        '<div clas="row">' +
                        '<b>Quantidade atual de assinaturas: </b>' + data.quantidadeAssinaturas +
                        '</div>' +
                        '<div clas="row">' +
                        '<b>Quantidade de assinaturas necess&aacute;rias: </b>' + data.quantidadeTotalAssinaturas +
                        '</div>' +



                        '</div>' +
                        '</div>' +
                        '</div>';
                }

                $('#assinaturaProjetos tbody').on('click', '.expand', function () {
                    var tr = $(this).closest('tr');
                    var row = assinaturaProjetos.row(tr);

                    if (row.child.isShown()) {
                        $('div.expansivel', row.child()).slideUp(function () {
                            row.child.hide();
                            tr.removeClass('shown');
                        });
                        $(this).find('i').first().html('expand_more');
                    } else {
                        row.child(informacoes(row.data()), 'no-padding').show();
                        tr.addClass('shown');
                        $('div.expansivel', row.child()).slideDown();
                        $(this).find('i').first().html('expand_less');
                    }
                })
            });
        }($.noConflict(true)));
    </script>
</main>
