<?php if (is_array($this->dados) && count($this->dados) > 0) :  ?>
    <div class="row">
        <div class="col s12">
            <table class="bordered margin0" id="enquadramento" style="width: 100%">
                <thead>
                <tr class="">
                    <th align="center" width="40" class="center-align">PRONAC</th>
                    <th class="center-align">Nome do Projeto</th>
                    <th class="center-align" align="center">Tipo</th>
                    <th class="center-align" align="center">Ver</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->dados as $dado): ?>
                    <tr>
                        <td class="center-align" align="center">
                            <a class="waves-effect waves-dark btn white black-text"
                               href="<?php echo $this->url(
                                       array(
                                           'module' => 'default',
                                           'controller' => 'consultardadosprojeto',
                                           'action' => 'index'
                                       )
                                   ) . "?idPronac={$dado['IdPRONAC']}"; ?>"><u><?php echo $dado['pronac']; ?></u></a>
                        </td>
                        <td class="center-align" align="center"><?php echo $dado['nomeProjeto']; ?></td>
                        <td class="center-align" align="center"><?php echo $dado['dsAtoAdministrativo']; ?></td>
                        <td class="center-align" align="center">
                            <?php
                            $parametrosVisualicacao = "?idDocumentoAssinatura={$dado['idDocumentoAssinatura']}";
                            ?>
                            <a class="btn waves-effect waves-light tooltipped small "
                               href="<?php echo $this->url(array(
                                       'module' => 'assinatura',
                                       'controller' => 'index',
                                       'action' => 'visualizar-projeto'
                                   )) . $parametrosVisualicacao ?>"
                               data-position="top"
                               data-delay="50"
                               data-tooltip="Visualizar">
                                <i class="material-icons">search</i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <div class="row">
        <div class="col s12">
            <div class="padding20 green white-text">Sem documentos assinados para este projeto.</div>
        </div>
    </div>
<?php endif; ?>
