<?php $currentUri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>
<?php $link = !empty($this->link) ? $this->url($this->link, null, true) : ''; ?>
<li>
    <a class="waves-effect waves-cyan <?php echo ($currentUri == $link) ? 'active' : '' ?>"
       href="<?= ($link) ? $link : 'javascript:void(0);'; ?>"
       title="Ir para <?= ($this->label); ?>"><?= $this->label; ?></a>
</li>