<div class="container-fluid white">
    <div class="row">
        <?= $this->partial('/mensagem/partials/menu.phtml', $this); ?>

        <div class="col s10 m12 l10">
            <h5>Responder solicita&ccedil;&atilde;o</h5>
            <?= $this->partial('/mensagem/partials/form.phtml', $this->arrPartial); ?>

            <h5>Encaminhar para o outro t&eacute;cnico</h5><?php //xd($this); ?>
            <form method="post" data-ajax-form="true"
                  action="<?= $this->arrPartial['arrConfig']['actionredistribuirSolicitacao']; ?>">
                <input name="idSolicitacao" type="hidden"
                       value="<?= isset($this->arrPartial['dataForm']['idSolicitacao']) ? $this->arrPartial['dataForm']['idSolicitacao'] : ''; ?>"/>
                <input name="idPronac" type="hidden" value="<?= $this->arrPartial['dataForm']['idPronac']; ?>"/>
                <input name="idProjeto" type="hidden" value="<?= $this->arrPartial['dataForm']['idProjeto']; ?>"/>

                <div class="row">
                    <div class="col card s6 m12 l6">
                        <label>T&eacute;cnico</label>
                        <select class="browser-default" name="idTecnico">
                            <option value="" disabled selected>Selecione um técnico</option>
                            <?php foreach ($this->arrPartial['arrConfig']['redistribuirTecnicos'] as $tecnico) : ?>
                                <option value="<?= $tecnico->usu_codigo; ?>"><?= $tecnico->usu_nome; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div

                    <div class="row">
                        <div class="col card s12 m12 l12">
                            <?php if ($this->arrPartial['arrConfig']['actions']['show'] === true): ?>
                                <button type="submit" class="btn waves-effect waves-light bt_rascunho">Encaminhar
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
