<?php 
/**
 * Alterar Projeto
 * @author Equipe RUP - Politec
 * @since 15/01/2011
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.alterarprojeto
 * @copyright ? 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>
<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>/principal" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseurl(); ?>/analisarexecucaofisica/filtroconsulta">Analisar Relat&oacute;rios Trimestrais</a></li>
        <li class="last">Listagem Relat&oacute;rios Trimestrais</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<div id="titulo">
    <div>Analisar Relat&oacute;rios Trimestrais
        <span class="voltar"><a href="<?php echo $this->baseurl(); ?>/analisarexecucaofisica/projetos">Voltar</a></span>
    </div>
</div>
<div id="conteudo">
    <table class="tabela">
        <tr>
            <td><input type="button" id="abrir_fechar_analisados" class="btn_adicionar" />Relat&oacute;rios Trimestrais</td>
        </tr>
    </table>
    <table class="tabela">
        <tr>
            <th>Relat&oacute;rios</th>
            <th>Analisar Relat&oacute;rios</th>
            <th>Encaminhar</th>
            <th>Status</th>
            <th>Respons&aacute;vel pela An&aacute;lise</th>
        </tr>
        <?php foreach ($this->dadosRelatorios as $relatorios) { ?>
        <tr>
            <td><?php echo $relatorios['nrRelatorioTrimestral']?>&ordm; Relat&oacute;rio</td>
            <td style="text-align: center;">
                <a href="<?php echo $this->url(array('controller' => 'analisarexecucaofisica', 'action' => 'relatoriotrimestral', 'idRelatorio' => $relatorios->idRelatorioTrimestral)); ?>">
                    <img src="<?php echo $this->baseurl(); ?>/public/img/table_multiple.png" alt="">
                </a>
            </td>
            <td style="text-align: center;">
            <?php if($relatorios->stRelatorioTrimestral == 2){ ?>
                <a href="#" onclick="encaminhar(<?php echo $relatorios->idRelatorioTrimestral; ?>, '<?php echo $this->DadosProjeto->NomeProjeto; ?>', '<?php echo $this->DadosProjeto->AnoProjeto . $this->DadosProjeto->Sequencial; ?>')">
                    <img src="<?php echo $this->baseurl(); ?>/public/img/encaminhar22x22.jpg" alt="">
                </a>
            <?php } else { ?>
                    <img src="<?php echo $this->baseurl(); ?>/public/img/encaminhar22x22-off.jpg" alt="">
            <?php } ?>
            </td>
            <td>
                <?php
                switch($relatorios->stRelatorioTrimestral){
                    case 2:
                        echo "Aguardando análise";
                        break;
                    case 3:
                        echo "Aguardando análise";
                        break;
                    case 4:
                        echo "Em análise";
                        break;
                    case 5:
                        echo "Analisado";
                        break;
                    case 6:
                        echo "Em análise";
                        break;
                    case 7:
                        echo "Analisado";
                        break;
                } ?>
            </td>
            <td>
                <?php echo $this->nomeAgente($relatorios->idAgenteAvaliador); ?>
            </td>
        </tr>
        <?php } ?>
    </table>
</div>
<!-- final: conteudo principal #conteudo -->


<div id="telaencaminhar" class="sumir">
    <form id="formulario" action="<?php echo $this->url(array('controller' => 'analisarexecucaofisica', 'action' => 'encaminharprojetoanalise')); ?>" method="post">
        <input type="hidden" name="idRelatorioTrimestral" id="idRelatorioTrimestral"  value=""/>
        <table class="tabela">
            <tr>
                <th>PRONAC</th>
                <td id="valorpronac"></td>
            </tr>
            <tr>
                <th>Nome do Projeto</th>
                <td id="valornomeprojeto"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <th colspan="2">
                    Observa&ccedil;&atilde;o
                </th>
            </tr>
            <tr>
                <td colspan="2">
                    <textarea cols="" rows="" style="width: 700px; height: 150px;" class="input_simples" id="justificativaenvio" name="justificativaenvio"></textarea>
                </td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <th>Destinat&aacute;rio</th>
                <td>
                    <select class="select_simples" style="width: 400px;" id="destinatario" name="destinatario">
                        <option value="">--Selecione--</option>
                        <?php foreach ($this->tecnicos as $t) : ?>
                        <option value="<?php echo $t->idAgente; ?>"><?php echo $t->usu_nome; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
    </form>
</div>

<div id="erro-1" class="sumir">Dados obrigat&oacute;rios n&atilde;o preenchidos!</div>
<div id="msg-1" class="sumir">Deseja realmente encaminhar o relat&oacute;rio?</div>

<script type="text/javascript">
    function encaminhar(id, NomeProjeto, Pronac){
        document.getElementById('idRelatorioTrimestral').value = '';
        document.getElementById('justificativaenvio').value = '';
        document.getElementById('destinatario').options[0].selected = true;

        $("#valorpronac").html(Pronac);
        $("#valornomeprojeto").html(NomeProjeto);
        $("#idRelatorioTrimestral").val(id);

        $("#telaencaminhar").dialog({
            title : 'Encaminhar para An&aacute;lise',
            resizable: false,
            width:800,
            height:600,
            modal:true,
            buttons: {
                'Cancelar': function() {
                    $(this).dialog('close');
                },
                'Encaminhar': function() {
                    var justificativa = $("#justificativaenvio").val();
                    var destinatario = $("#destinatario").val();
                    if($.trim(justificativa)=='' ||  destinatario==''){
			alertModal("Alerta!", "erro-1", 360, 180);
			return false;
                    }
                    else{
			confirmModal("Alerta!", "msg-1", 360, 180, null, null, 'formulario', null, null, null);
			return false;
                    }
                }
            }
        });
        $('.ui-dialog-titlebar-close').remove();
    }
</script>

<!-- início: detalhe final da div conteudo #rodapeConteudo -->
<div id="rodapeConteudo"><span></span></div>
<!-- final: detalhe final da div conteudo #rodapeConteudo -->


<br clear="all" />