<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" rel="stylesheet"></link>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui"> 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vuetify/1.1.11/vuetify.min.css" />
<style> 
    body {
        font-family: 'Roboto', sans-serif;
    }
</style>

<div id="app"></div>
<script type="text/javascript" charset="utf-8" src="/public/dist/js/manifest.js?v=v5.0.6"></script>
<script type="text/javascript" charset="utf-8" src="/public/dist/js/vendor.js?v=v5.0.6"></script>
<script type="text/javascript" charset="utf-8" src="/public/dist/js/avaliacao_resultados.js?v=v5.0.6"></script>
