<?php if($this->projetosAguardandoAnalise > 0): ?>
    <table class="bordered striped">
        <thead>
            <tr>
                <th>PRONAC</th>
                <th>Nome do Projeto</th>
                <th>Situação</th>
                <th>Área / Segmento</th>
                <th>Mecanismo</a></th>
                <th>Encaminhar para Análise</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->projetosAguardandoAnalise as $projeto): ?>
                <tr>
                    <td>
                        <a class="btn pre-visualizar modal-trigger" data-idpronac="<?php echo ($projeto->idPronac); ?>" href="#abrirModal" ahref="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo ($projeto->idPronac); ?>" target="_blank">
                            <?php echo $projeto->Pronac; ?>
                        </a>
                    </td>
                    <td><?php echo $projeto->NomeProjeto; ?></td>
                    <td><?php echo $projeto->Situacao; ?></td>
                    <td><?php echo $projeto->Area.' / '.$projeto->Segmento; ?></td>
                    <td><?php $mecanismo = $projeto->Mecanismo; if ($mecanismo == 'Mecenato'){ echo "Incentivo Fiscal"; }else{ echo $projeto->Mecanismo;}?></td>
                    <td>
                        <button class="btn" onclick="return JSEncaminharParaAnalise('<?php echo $projeto->idPronac; ?>','<?php echo $this->codOrgao; ?>','<?php echo (isset($_GET['tipoFiltro']) && !empty($_GET['tipoFiltro'])) ? $_GET['tipoFiltro'] : 0; ?>',true)" alt="Encaminhar">
                            <i class=" tiny material-icons">assignment_ind</i> 
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <table>
        <tr>
            <td>Nenhum registro encontrado.</td>
        </tr>
    </table>
<?php endif ?>
