<div id="container-progress-part" style="display: none;" class="preloader-wrapper big active">
    <div class="spinner-layer spinner-green">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-blue">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-red">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
    <div class="spinner-layer spinner-yellow">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
            <div class="circle"></div>
        </div><div class="circle-clipper right">
            <div class="circle"></div>
        </div>
    </div>
</div>
<div id="container-progress" class="progress" style="margin: 0; display: none;">
    <div class="indeterminate"></div>
</div>
<footer class="page-footer green darken-4">
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col s4 l4">
                    <a class="orange-text text-lighten-3" target="_blank" href="http://cultura.gov.br">MINIST&Eacute;RIO DA CULTURA</a>
                </div>
                <div class="col s4 l4">
                    <div class="center-align">
                        <?php echo $this->partial('partials/environment.phtml'); ?>
                    </div>
                </div>
                <div class="col s4 l4">
                    <div class="center-align">
                        <?php echo $this->vcs(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->headScript(); ?>

