<div class="container-fluid">
    <div class="row">
        <div class="col s12">
            <div id="breadcrumb">
                <ul>
                    <li class="first">
                        <a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para p&aacute;gina inicial">Início</a>
                    </li>
                    <li>Presta&ccedil;&atilde;o de contas</li>
                    <li class="last">Analisar presta&ccedil;&atilde;o de contas</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <h5 class="left">Analisar presta&ccedil;&atilde;o de contas - Em análise</h5>
            <a class="btn right" href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <table id="tabela">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>PRONAC</th>
                        <th>Nome do Projeto</th>
                        <th>Situação</th>
                        <th>Área / Segmento</th>
                        <th>Estado</th>
                        <th>Mecanismo</th>
                        <th>Dt. Recebimento</th>
                        <th>Analisar Prestação de Contas</th>
                        <th>Devolver para Chefe de Divis&aacute;o</th>
                        <?php if($this->filtro == 'diligenciados'): ?>
                            <th>Consultoria AECI</th>
                            <th>Consultoria CONJUR</th>
                            <th>Visualizar Hist&oacute;rico</th>
                        <?php endif; ?>
                        <th>Dilig&ecirc;ncia</th>
                        <th>Hist&oacute;rico</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $x=1; foreach($this->dados as $projeto){ ?>
                    <tr>
                        <td><?php echo $x; ?></td>
                        <td>
                            <button class="btn pre-visualizar" data-idpronac="<?php echo ($projeto->idPronac); ?>">
                                <?php echo $projeto->Pronac; ?>
                            </button>
                        </td>
                        <td><?php echo $projeto->NomeProjeto; ?></td>
                        <td><?php echo $projeto->Situacao; ?></td>
                        <td><?php echo $projeto->Area.' / '.$projeto->Segmento; ?></td>
                        <td><?php echo $projeto->UfProjeto; ?></td>
                        <td><?php $mecanismo = $projeto->Mecanismo; if ($mecanismo == 'Mecenato'){ echo "Incentivo Fiscal"; }else{ echo $projeto->Mecanismo;}?></td>
                        <td><?php echo Data::tratarDataZend($projeto->DtSituacao, 'brasileira');?></td>
                        <td><img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/table_multiple.png" onclick="window.location='<?php echo $this->baseUrl(); ?>/realizarprestacaodecontas/planilhaorcamentaria/idPronac/<?php echo ($projeto->idPronac); ?>'" alt="Analisar"></td>
                        <td>
                            <?php if ($projeto->RelatorioTecnico == "False") { ?>
                                <img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/user_gray.png" onclick="return JSDevolverParaChefeDivisao('<?php echo $projeto->idPronac; ?>','<?php echo $this->codOrgao; ?>',true)" alt="Devolver para chefe de divisão" />
                            <?php } else { ?>
                                <em>Análise j&aacute; iniciada</em>
                            <?php } ?>
                        </td>
                        <td background="" align="center">
                            <?php
                                $arrPrazo = $this->prazoRespostaDiligencia($projeto->idPronac, 174);
                                $icone = $arrPrazo['iconeDiligencia']['icone'];
                                $title = $arrPrazo['iconeDiligencia']['title'];
                            ?>
                            <?php if($this->filtro == 'diligenciados'){ ?>
                                <a target="_blank" href="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'diligenciar', 'action' =>'listardiligenciaanalista')).'?idPronac=' . $projeto->idPronac . '&situacao=E17&tpDiligencia=174';?>" ><img src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $icone; ?>" title="<?php echo $title; ?>" width="30px"/></a><br>
                            <?php } else { ?>
                                <a target="_blank" href="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'diligenciar', 'action' =>'listardiligenciaanalista')).'?idPronac=' . $projeto->idPronac . '&situacao=E27&tpDiligencia=174';?>" ><img src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $icone; ?>" title="<?php echo $title; ?>" width="30px"/></a><br>
                            <?php } ?>
                        </td>
                        <td align="center"><img style="cursor: pointer;" src="../public/img/btn_busca.jpg" onclick="return JShistoricoEncaminhamento('<?php echo $projeto->idPronac; ?>')" alt="Encaminhar" /></td>
                    </tr>
                    <?php $x++; } ?>
                </tbody>
            </table>
        </div>
    </div>
    <form name="formImpressao" id="formImpressao" action="<?php echo $this->url(array('controller' => 'realizarprestacaodecontas', 'action' => 'imprimir-tecnico-prestacao-de-contas'));?>" method="post" target="_blank">
        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
        <input type="hidden" name="pag" value="<?php echo $this->paginacao['pag'];?>">
        <input type="hidden" name="qtde" value="<?php echo $this->intTamPag;?>">
        <input type="hidden" name="tipoFiltro" value="<?php echo $this->filtro;?>">
        <input type="hidden" name="pronac" value="<?php echo $this->pronacProjeto;?>">
    </form>
</div>


<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>
<script type="text/javascript">

    $(document).ready(function () {
        $('#tabela').DataTable (
            {
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                },
                paging: true
            }
        );
    });
</script>

<script src="/public/scripts/prestacao-contas/tecnicoprestacaocontas.js" type="text/javascript"></script>
<div style="display: none;" id="historicoEncaminhamento" title="Encaminhar projeto para análise"></div>

<?php echo $this->partial('/consultardadosprojeto/partial/consultar-ajax.phtml')?>
