<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/public/library/materialize/css/materialize.css" media="all" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl(); ?>/public/library/materialize/css/materialize-custom.css" media="all" rel="stylesheet" type="text/css">
    </head>
<body>
<header>

</header>
<main>
    <div class="content padding20 clearfix">
        <?php echo $this->layout()->content; ?>
    </div>
</main>
</body>
</html>
