<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Readequa&ccedil;&atilde;o Local de Realiza&ccedil;&atilde;o</h1>

                    <?php
                    gerarNovoBreadCrumb(array(
                        array('Local de realiza&ccedil;&atilde;o' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>
        <div class="content">
            <input type="hidden" id="idPronacHash" name="idPronacHash" value="<?php echo $this->idPronacHash; ?>">
            <div id="cabecalho" class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12">
                            <b>Pronac: </b> <?php echo $this->projeto->anoProjeto . $this->projeto->sequencial; ?>
                            <br>
                        </div>
                        <div class="col s12">
                            <b>Projeto: </b><?php echo $this->projeto->nomeProjeto; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->partial("partials/mensagem-solicitacao-em-analise.phtml", $this); ?>
            <?php if (!$this->existeSolicitacaoEmAnalise) : ?>
                <div id="conteudo" style="margin: 0; width: 100%">
                    <div class="card">
                        <div class="card-content">
                            <div id="locaisParaRealizacao">
                                carregando locais ...
                            </div>
                        </div>
                    </div>
                </div>

                <div id="formulario" class="card">
                    <div class="card-content">
                        <?php echo $this->partial("partials/formulario-salvar-readequacao.phtml", $this); ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<div id="msgAlerta"></div>
<?php if (!$this->existeSolicitacaoEmAnalise) : ?>

    <script type="text/javascript">
        function atualizarDadosLocaisRealizacao() {
            jqAjaxLinkSemLoading('<?php echo $this->Url(array('module' => 'readequacao', 'controller' => 'local-realizacao', 'action' => 'carregar-locais-de-realizacao'), '', true) ?>?idPronac=<?php echo $this->idPronacHash; ?>', '', 'locaisParaRealizacao');
        }

        $(document).ready(function () {
            atualizarDadosLocaisRealizacao();
        });

    </script>

<?php endif; ?>
