const PERFIL_TECNICO_ACOMPANHAMENTO = 121;
const PERFIL_COORDENADOR_ACOMPANHAMENTO = 122;
const PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO = 123;

const PERFIL_PROPONENTE = 1111;
const PERFIL_DIRETOR = 148;
const PERFIL_SECRETARIO = 149;

export default {
    PERFIL_TECNICO_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO,
    PERFIL_PROPONENTE,
    PERFIL_DIRETOR,
    PERFIL_SECRETARIO,
};
