const PERFIL_TECNICO_ACOMPANHAMENTO = 121;
const PERFIL_COORDENADOR_ACOMPANHAMENTO = 122;
const PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO = 123;

const PERFIL_PROPONENTE = 1111;
const PERFIL_DIRETOR = 148;
const PERFIL_SECRETARIO = 149;

const TIPO_READEQUACAO_REMANEJAMENTO_PARCIAL = 1;
const TIPO_READEQUACAO_PLANILHA_ORCAMENTARIA = 2;
const TIPO_READEQUACAO_RAZAO_SOCIAL = 3;
const TIPO_READEQUACAO_AGENCIA_BANCARIA = 4;
const TIPO_READEQUACAO_SINOPSE_OBRA = 5;
const TIPO_READEQUACAO_IMPACTO_AMBIENTAL = 6;
const TIPO_READEQUACAO_ESPECIFICACAO_TECNICA = 7;
const TIPO_READEQUACAO_ESTRATEGIA_EXECUCAO = 8;
const TIPO_READEQUACAO_LOCAL_REALIZACAO = 9;
const TIPO_READEQUACAO_ALTERACAO_PROPONENTE = 10;
const TIPO_READEQUACAO_PLANO_DISTRIBUICAO = 11;
const TIPO_READEQUACAO_NOME_PROJETO = 12;
const TIPO_READEQUACAO_PERIODO_EXECUCAO = 13;
const TIPO_READEQUACAO_PLANO_DIVULGACAO = 14;
const TIPO_READEQUACAO_RESUMO_PROJETO = 15;
const TIPO_READEQUACAO_OBJETIVOS = 16;
const TIPO_READEQUACAO_JUSTIFICATIVA = 17;
const TIPO_READEQUACAO_ACESSIBILIDADE = 18;
const TIPO_READEQUACAO_DEMOCRATIZACAO_ACESSO = 19;
const TIPO_READEQUACAO_ETAPAS_TRABALHO = 20;
const TIPO_READEQUACAO_FICHA_TECNICA = 21;
const TIPO_READEQUACAO_SALDO_APLICACAO = 22;
const TIPO_READEQUACAO_TRANSFERENCIA_RECURSOS = 23;

const SI_ENCAMINHAMENTO_ENVIADO_MINC = 1;
const SI_ENCAMINHAMENTO_SOLICITACAO_INDEFERIDA = 2;
const SI_ENCAMINHAMENTO_ENVIADO_UNIDADE_ANALISE = 3;
const SI_ENCAMINHAMENTO_ENVIADO_ANALISE_TECNICA = 4;
const SI_ENCAMINHAMENTO_DEVOLVIDO_ANALISE_TECNICA = 5;
const SI_ENCAMINHAMENTO_DEVOLVIDA_AO_MINC = 6;
const SI_ENCAMINHAMENTO_ENVIADO_CNIC = 7;
const SI_ENCAMINHAMENTO_ENVIADO_PLENARIA = 8;
const SI_ENCAMINHAMENTO_CHECKLIST_PUBLICACAO = 9;
const SI_ENCAMINHAMENTO_DEVOLVIDA_COORDENADOR_TECNICO = 10;
const SI_ENCAMINHAMENTO_NAO_ENVIA_MINC = 11;
const SI_ENCAMINHAMENTO_CADASTRADA_PROPONENTE = 12;
const SI_ENCAMINHAMENTO_FINALIZADA_SEM_PORTARIA = 15;
const SI_ENCAMINHAMENTO_DEVOLVIDA_CNIC_AO_COORDENADOR = 17;
const SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_COORDENADOR_GERAL = 18;
const SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_DIRETOR = 19;
const SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_SECRETARIO = 20;
const SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_COORDENADOR_GERAL = 21;
const SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_DIRETOR = 22;
const SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_SECRETARIO = 23;
const SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_PRESIDENTE_DA_VINCULADA = 24;
const SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_DE_PARECER_PELO_PRESIDENTE = 25;
const SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_FINAL = 26;
const SI_ENCAMINHAMENTO = {
    1: 'Solicitação encaminhada ao MinC pelo proponente',
    2: 'Solicitação indeferida e devolvida ao proponente',
    3: 'Solicitação encaminhada a  unidade de análise pelo MinC',
    4: 'Solicitação encaminhada ao parecerista /  técnico',
    5: 'Solicitação devolvida ao coordenador da unidade de análise pelo parecerista',
    6: 'Solicitação devolvida ao MinC pela unidade de análise',
    7: 'Solicitação encaminhada para o componente da comissão',
    8: 'Solicitação encaminhada  à plenára da CNIC pelo componente da comissão',
    9: 'Solicitação encaminhada para elaboração de portaria',
    10: 'Solicitação devolvida para o coordenador pelo técnico',
    11: 'Solicitação sem a necessidade de encaminhar ao MinC',
    12: 'Solicitação em cadastramento pelo proponente',
    15: 'Solicitação finalizada pelo MinC',
    17: 'Solicitação devolvida pela CNIC ao coordenador',
    18: 'Solicitação encaminhada ao coordenador-geral',
    19: 'Solicitação encaminhada ao diretor',
    20: 'Solicitação encaminhada ao secretario',
    21: 'Solicitação devolvida ao coordenador pelo coordenador-geral',
    22: 'Solicitação devolvida ao coordenador pelo diretor',
    23: 'Solicitação devolvida ao coordenador pelo secretário',
    24: 'Solicitação encaminhada ao presidente da vinculada',
    25: 'Solicitação devolvida ao coordenador de parecer  pelo presidente da vinculada',
    26: 'Solicitação devolvida ao Coordenador após completar o ciclo de assinaturas',
};

export default {
    PERFIL_TECNICO_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO,
    PERFIL_PROPONENTE,
    PERFIL_DIRETOR,
    PERFIL_SECRETARIO,
    TIPO_READEQUACAO_REMANEJAMENTO_PARCIAL,
    TIPO_READEQUACAO_PLANILHA_ORCAMENTARIA,
    TIPO_READEQUACAO_RAZAO_SOCIAL,
    TIPO_READEQUACAO_AGENCIA_BANCARIA,
    TIPO_READEQUACAO_SINOPSE_OBRA,
    TIPO_READEQUACAO_IMPACTO_AMBIENTAL,
    TIPO_READEQUACAO_ESPECIFICACAO_TECNICA,
    TIPO_READEQUACAO_ESTRATEGIA_EXECUCAO,
    TIPO_READEQUACAO_LOCAL_REALIZACAO,
    TIPO_READEQUACAO_ALTERACAO_PROPONENTE,
    TIPO_READEQUACAO_PLANO_DISTRIBUICAO,
    TIPO_READEQUACAO_NOME_PROJETO,
    TIPO_READEQUACAO_PERIODO_EXECUCAO,
    TIPO_READEQUACAO_PLANO_DIVULGACAO,
    TIPO_READEQUACAO_RESUMO_PROJETO,
    TIPO_READEQUACAO_OBJETIVOS,
    TIPO_READEQUACAO_JUSTIFICATIVA,
    TIPO_READEQUACAO_ACESSIBILIDADE,
    TIPO_READEQUACAO_DEMOCRATIZACAO_ACESSO,
    TIPO_READEQUACAO_ETAPAS_TRABALHO,
    TIPO_READEQUACAO_FICHA_TECNICA,
    TIPO_READEQUACAO_SALDO_APLICACAO,
    TIPO_READEQUACAO_TRANSFERENCIA_RECURSOS,
    SI_ENCAMINHAMENTO_ENVIADO_MINC,
    SI_ENCAMINHAMENTO_SOLICITACAO_INDEFERIDA,
    SI_ENCAMINHAMENTO_ENVIADO_UNIDADE_ANALISE,
    SI_ENCAMINHAMENTO_ENVIADO_ANALISE_TECNICA,
    SI_ENCAMINHAMENTO_DEVOLVIDO_ANALISE_TECNICA,
    SI_ENCAMINHAMENTO_DEVOLVIDA_AO_MINC,
    SI_ENCAMINHAMENTO_ENVIADO_CNIC,
    SI_ENCAMINHAMENTO_ENVIADO_PLENARIA,
    SI_ENCAMINHAMENTO_CHECKLIST_PUBLICACAO,
    SI_ENCAMINHAMENTO_DEVOLVIDA_COORDENADOR_TECNICO,
    SI_ENCAMINHAMENTO_NAO_ENVIA_MINC,
    SI_ENCAMINHAMENTO_CADASTRADA_PROPONENTE,
    SI_ENCAMINHAMENTO_FINALIZADA_SEM_PORTARIA,
    SI_ENCAMINHAMENTO_DEVOLVIDA_CNIC_AO_COORDENADOR,
    SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_COORDENADOR_GERAL,
    SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_DIRETOR,
    SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_SECRETARIO,
    SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_COORDENADOR_GERAL,
    SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_DIRETOR,
    SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_PELO_SECRETARIO,
    SI_ENCAMINHAMENTO_SOLICITACAO_ENCAMINHADA_AO_PRESIDENTE_DA_VINCULADA,
    SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_DE_PARECER_PELO_PRESIDENTE,
    SI_ENCAMINHAMENTO_SOLICITACAO_DEVOLVIDA_AO_COORDENADOR_FINAL,
    SI_ENCAMINHAMENTO,
};
