const PERFIL_TECNICO_ACOMPANHAMENTO = 121;
const PERFIL_COORDENADOR_ACOMPANHAMENTO = 122;
const PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO = 123;

const PERFIL_PROPONENTE = 1111;
const PERFIL_DIRETOR = 148;
const PERFIL_SECRETARIO = 149;

const TIPO_READEQUACAO_REMANEJAMENTO_PARCIAL = 1;
const TIPO_READEQUACAO_PLANILHA_ORCAMENTARIA = 2;
const TIPO_READEQUACAO_RAZAO_SOCIAL = 3;
const TIPO_READEQUACAO_AGENCIA_BANCARIA = 4;
const TIPO_READEQUACAO_SINOPSE_OBRA = 5;
const TIPO_READEQUACAO_IMPACTO_AMBIENTAL = 6;
const TIPO_READEQUACAO_ESPECIFICACAO_TECNICA = 7;
const TIPO_READEQUACAO_ESTRATEGIA_EXECUCAO = 8;
const TIPO_READEQUACAO_LOCAL_REALIZACAO = 9;
const TIPO_READEQUACAO_ALTERACAO_PROPONENTE = 10;
const TIPO_READEQUACAO_PLANO_DISTRIBUICAO = 11;
const TIPO_READEQUACAO_NOME_PROJETO = 12;
const TIPO_READEQUACAO_PERIODO_EXECUCAO = 13;
const TIPO_READEQUACAO_PLANO_DIVULGACAO = 14;
const TIPO_READEQUACAO_RESUMO_PROJETO = 15;
const TIPO_READEQUACAO_OBJETIVOS = 16;
const TIPO_READEQUACAO_JUSTIFICATIVA = 17;
const TIPO_READEQUACAO_ACESSIBILIDADE = 18;
const TIPO_READEQUACAO_DEMOCRATIZACAO_ACESSO = 19;
const TIPO_READEQUACAO_ETAPAS_TRABALHO = 20;
const TIPO_READEQUACAO_FICHA_TECNICA = 21;
const TIPO_READEQUACAO_SALDO_APLICACAO = 22;
const TIPO_READEQUACAO_TRANSFERENCIA_RECURSOS = 23;

export default {
    PERFIL_TECNICO_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_ACOMPANHAMENTO,
    PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO,
    PERFIL_PROPONENTE,
    PERFIL_DIRETOR,
    PERFIL_SECRETARIO,
	TIPO_READEQUACAO_REMANEJAMENTO_PARCIAL,
	TIPO_READEQUACAO_PLANILHA_ORCAMENTARIA,
	TIPO_READEQUACAO_RAZAO_SOCIAL,
	TIPO_READEQUACAO_AGENCIA_BANCARIA,
	TIPO_READEQUACAO_SINOPSE_OBRA,
	TIPO_READEQUACAO_IMPACTO_AMBIENTAL,
	TIPO_READEQUACAO_ESPECIFICACAO_TECNICA,
	TIPO_READEQUACAO_ESTRATEGIA_EXECUCAO,
	TIPO_READEQUACAO_LOCAL_REALIZACAO,
	TIPO_READEQUACAO_ALTERACAO_PROPONENTE,
	TIPO_READEQUACAO_PLANO_DISTRIBUICAO,
	TIPO_READEQUACAO_NOME_PROJETO,
	TIPO_READEQUACAO_PERIODO_EXECUCAO,
	TIPO_READEQUACAO_PLANO_DIVULGACAO,
	TIPO_READEQUACAO_RESUMO_PROJETO,
	TIPO_READEQUACAO_OBJETIVOS,
	TIPO_READEQUACAO_JUSTIFICATIVA,
	TIPO_READEQUACAO_ACESSIBILIDADE,
	TIPO_READEQUACAO_DEMOCRATIZACAO_ACESSO,
	TIPO_READEQUACAO_ETAPAS_TRABALHO,
	TIPO_READEQUACAO_FICHA_TECNICA,
	TIPO_READEQUACAO_SALDO_APLICACAO,
	TIPO_READEQUACAO_TRANSFERENCIA_RECURSOS,
};
