<?php if(count($this->PlanilhaEtapa) > 0) : ?>
    <script>
        $(document).ready(function(){
            $(".item").click(function(){
                var etapa = $(this).parent().parent().parent().parent().parent().find('.itens');
                if(etapa.css('display')== 'none'){
                    etapa.css('display','');
                }
                else{
                    etapa.css('display','none');
                }
            });
        });
    </script>
    <?php $total_geral = 0;?>
    <?php foreach ($this->PlanilhaEtapa as $etapas) : ?>
    <div class="etapas">
        <table width="95%" summary="Produto">
            <tr>
                <td width="4%"  align="center"><img style="cursor: pointer; width: 35%; height: 25%; border: 0px" class="btn_adicionar item" src="<?php echo $this->baseUrl(); ?>/public/img/buttons/btn_adicionar.gif" alt="Adicionar" /></td>
                <td width="88%" style="text-align:left; padding-left:2%;"> <?php echo utf8_decode(htmlentities($etapas->DescricaoEtapa)); ?>
                </td>
            </tr>
        </table>

        <div class="itens" style="display:on;">
            <table width="92%" cellspacing="0" cellpadding="0" style="margin:0 0 0 5%; width: 90%">
                <tr>
                    <th width="40%">&Iacute;tem</th>
                    <th>Unidade</th>
                    <th>Qtd</th>
                    <th>Ocorr&ecirc;ncia</th>
                    <th>Vl. Unit&aacute;rio</th>
                    <th>Vl. TOTAL</th>

                </tr>
                <?php $soma = 0;?>
                <?php foreach ($this->Planilha as $planilha) :?>
                    <?php if($etapas->idEtapa == $planilha->idEtapa) {?>
                    <tr class="fundo">
                        <td align="left"><?php echo utf8_decode(htmlentities($planilha->DescricaoItem)); ?></td>
                        <td class="centro" width="10%"><?php echo (int) utf8_decode(htmlentities($planilha->DescricaoUnidade)); ?></td>
                        <td  class="centro" width="6%"><?php echo (int) utf8_decode(htmlentities($planilha->Quantidade)); ?></td>
                        <td  class="centro" width="13%"><?php echo (int) utf8_decode(htmlentities($planilha->Ocorrencia)); ?></td>
                        <td class="centro" width="13%"><?php echo number_format($planilha->ValorUnitario,2,',','.') ?></td>
                            <?php $total = ($planilha->Quantidade * $planilha->Ocorrencia * $planilha->ValorUnitario);?>
                            <?php $soma = $soma + $total; ?>
                        <td class="centro" class="centro"><?php echo number_format($total,2,',','.')?></td>
                    </tr>
                    <?php }?>
                <?php endforeach; ?>
                <?php $total_geral = $total_geral + $soma;?>
                <tr>
                    <td align="left"><b><font size="3px" color="green">TOTAL: </font></b></td>
                    <td width="10%"></td>
                    <td width="6%"></td>
                    <td width="13%"></td>
                    <td width="13%"></td>
                    <td width="20%" align="center"><b><font size="3px" color="green"><?php echo "R$". number_format($soma,2,',','.')?></font></b></td>
                </tr>

            </table>
        </div>

    </div>
    <?php endforeach; ?>  <!-- FIM FOREACH ETAPAS -->
    <table width="92%" cellspacing="0" cellpadding="0" style="margin:0 0 0 5%; width: 90%">
        <tr>
            <td align="left" width="40%"><b><font size="4px" color="red">TOTAL GERAL: </font></b></td>
            <td width="10%"></td>
            <td width="6%"></td>
            <td width="13%"></td>
            <td width="13%"></td>
            <td width="20%" align="center"><b><font size="4px" color="red"><?php echo "R$".number_format($total_geral,2,',','.')?> </font></b></td>
        </tr>
    </table>
<?php else:?>
    <table class="tabela">
        <tr class="fundo">
            <td align="left">Nenhum registro encontrado.</td>
        </tr>
    </table>
<?php endif;?>