<?php
    $SalvarProduto = $this->url(array('module'=>'proposta', 'controller' => 'manterorcamento', 'action' => 'salvarprodutos'));
?>
<script type="text/javascript">
    //mascara('vlunitario', format_moeda);
    $('#vlunitario').priceFormat({limit: 8});
    $(document).ready(function(){



        <?php if(isset($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
             //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
             JSBloquearAlteracaoFormulario();
        <?php endif; ?>

            $.ajax({
                url : '<?php echo $this->url(array('controller' => 'Manterorcamento', 'action' => 'cadastrarprodutos')); ?>',
                type: "POST",
                data :{
                    idetapa : $('#etapa').val(),
                    idPreProjeto : <?php echo $this->idPreProjeto; ?>,
                    idProduto : <?php echo $this->idProduto; ?>
                },
                success: function(valor){
                    $("#item").find('option').remove();
                    $("#item").append('<option value=""> - Selecione - </option>');

                    for(a in valor){
                        $("#item").append('<option value="'+valor[a].idItem+'">'+valor[a].nomeItem+'</option>');
                    }
                }
                , dataType : 'json'
            });

        $('.soma').keyup(function(){
            var soma = 0;
            var vlunitario = $("#vlunitario").val().replace('R$ ','');

        	// retira os pontos e as virgulas, deixando somente numeros
            vlunitario = vlunitario.replace(/\D/g, "");
            vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

        	// adiciona o ponto na casa decimal
            vlunitario = vlunitario.replace(/(\d)(\d{2})$/, "$1.$2");

        	// converte para float e adiciona precisao decimal
        	qtd        = parseFloat($("#quantidade").val()).toFixed(2);
        	ocorrencia = parseFloat($("#ocorrencia").val()).toFixed(2);
        	valor      = parseFloat(vlunitario).toFixed(2);

            soma = parseFloat(qtd * ocorrencia * valor).toFixed(2); // armazena o resultado

            if(soma >= 0){
                $("#total").val(soma);
            }else{
                $("#total").val(0);
            }
            $("#total").priceFormat();
        });

        if($("#total").val() == 'R$ NaN'){
			alert("Valores Invalidos");
        }

        if($('#uf').val() != '' &&  $('#municipio').val() != '' && $('#item').val() != '' && $('#etapa').val() != '' ){
            somaValores();
        }

        $('.numero').keydown(function(event){
            if((event.keyCode >= 96 && event.keyCode <= 105) || (event.keyCode >= 48 && event.keyCode <= 57) || event.keyCode == 8 || event.keyCode ==9 ){
                return true;
            }
            else
                return false;
        });

        $("#error").dialog({
            resizable: true,
            width:450,
            height:150,
            modal: true,
            autoOpen:false,
            buttons: {
                'OK': function() {
                    $(this).dialog('close');
                }
            }
        });
        $('.btn_salvar').click(function(){
            var validar = true;
            $('.valida').each(function(){
                if($(this).val() == ''){
                    validar = false;
                }
            });

            if(validar == false){
                $("#error").html('Dados obrigat&oacute;rios n&atilde;o informados!');
                $("#error").dialog('open');

            } else {
            	if($("#quantidade").val() == 0){
                    $("#error").html('Quantidade n&atilde;o pode ser igual a zero');
                    $("#error").dialog('open');
                    $("#quantidade").val('');
                    return false;
                }

            	if($("#ocorrencia").val() == 0){
                    $("#error").html('Ocorr&ecirc;ncia n&atilde;o pode ser igual a zero');
                    $("#error").dialog('open');
                    $("#ocorrencia").val('');
                    return false;
                }

            	var vlunitario = $("#vlunitario").val();
            	vlunitario = vlunitario.replace(/\D/g, "");
            	vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

            	if(vlunitario == 0){
                    $("#error").html('Valor unit&aacute;rio n&atilde;o pode ser igual a zero');
                    $("#error").dialog('open');
                    $("#vlunitario").val('');
                    return false;
                }

                if($("#qtdDias").val() == 0){
                    $("#error").html('Quantidade de dias n&atilde;o pode ser igual a zero');
                    $("#error").dialog('open');
                    $("#qtdDias").val('');
                    return false;
                } else {
                    var jstv = $('#editor1').val();
                    if(jstv.length > 500){
                        $("#justificativaErro").dialog("destroy");
                        $("#justificativaErro").html('O campo Justificativa não pode ultrapassar 500 caracteres!');
                        $("#justificativaErro").dialog ({
                            width:320,
                            height:180,
                            title:'Alerta!',
                            draggable:true,
                            EscClose:true,
                            modal:true,
                            buttons: {
                                'Ok': function() {
                                    $(this).dialog('close');
                                }
                            }
                        });
                        return false;
                    }

                    $("#msg").html("");
                    $("#msg").dialog("destroy");
                    $("#msg").html("Carregando...");
                    $.ajax({
                        url : $("#form").attr('action'),
                        type: "POST",
                        async: false,
                        data : $("#form").serialize(),
                        success: function(valor){
                            $("#msg").html(valor);
                        }
                    });
                    $("#msg").dialog
                    ({
                        width:500,
                        height:160,
                        draggable:true,
                        EscClose:true,
                        modal:true,
                        close: function(){
                            $("#item").val("");
                            $("#unidade").val("");
                            $("#quantidade").val("");
                            $("#ocorrencia").val("");
                            $("#vlunitario").val("");
                            $("#qtdDias").val("");
                            $("#total").val("");
                            $("#editor1").val("");
                        },
                        buttons: {
                            'Nao': function() {
                                $("#frmCadastroItem").dialog("destroy");
                                window.location.reload();
                            },
                            'Sim': function() {
                                $(this).dialog('close');
                            }
                        }
                    });
                }
            }
        });

        $('#uf').change(function(){
            if($(this).val() == 0){
                $("#municipio").find('option').remove();
                $("#municipio").append('<option value=""> - Selecione - </option>');
            }
            else{
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'Manterorcamento', 'action' => 'cadastrarprodutos')); ?>',
                    type: "POST",
                    data :{
                        iduf : $(this).val(),
                        idPreProjeto : <?php echo $this->idPreProjeto;?>
                    },
                    success: function(valor){
                        $("#municipio").find('option').remove();
                        $("#municipio").append('<option value=""> - Selecione - </option>');

                        for(a in valor){
                            $("#municipio").append('<option value="'+valor[a].idCidade+'">'+valor[a].nomeCidade+'</option>');
                        }
                    },
                    type : 'post'
                    , dataType : 'json'
                });
            }
        });

    });

    function somaValores(){
        var soma = 0;
        var vlunitario = $("#vlunitario").val().replace('R$','');
        var vlunitario = $.trim(vlunitario.replace(',','.'));
        soma = $("#quantidade").val()*$("#ocorrencia").val() * vlunitario;
        soma = soma.toFixed(2).replace('.',',');
        $("#total").val(soma);
    }

    function Limpar(valor, validos) {
        // retira caracteres invalidos da string
        var result = "";
        var aux;
        for (var i=0; i < valor.length; i++) {
            aux = validos.indexOf(valor.substring(i, i+1));
            if (aux>=0) {
                result += aux;
            }
        }
        return result;
    }

    //Formata numero tipo moeda usando o evento onKeyDown

    function Formata(campo,tammax,teclapres,decimal) {
        var tecla = teclapres.keyCode;
        vr = Limpar(campo.value,"0123456789");
        tam = vr.length;
        dec=decimal

        if (tam < tammax && tecla != 8){ tam = vr.length + 1 ; }

        if (tecla == 8 )
        { tam = tam - 1 ; }

        if ( tecla == 8 || tecla >= 48 && tecla <= 57 || tecla >= 96 && tecla <= 105 )
        {

            if ( tam <= dec )
            { campo.value = vr ; }

            if ( (tam > dec) && (tam <= 5) ){
                campo.value = vr.substr( 0, tam - 2 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 6) && (tam <= 8) ){
                campo.value = vr.substr( 0, tam - 5 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ;
            }
            if ( (tam >= 9) && (tam <= 11) ){
                campo.value = vr.substr( 0, tam - 8 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 12) && (tam <= 14) ){
                campo.value = vr.substr( 0, tam - 11 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 15) && (tam <= 17) ){
                campo.value = vr.substr( 0, tam - 14 ) + "." + vr.substr( tam - 14, 3 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - 2, tam ) ;}
        }

    }
</script>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<body>
    <!-- ========== INCIO TTULO ========== -->
    <div id="titulo" style="width: 97%">
        <div>Cadastrar Planilha por Produto</div>
    </div>
    <div id='error'></div>
    <div id='justificativaErro' class="sumir"></div>
    <div id="msg" class="sumir"></div>
    <!-- ========== FIM TTULO ========== -->
    <!-- ========== INCIO CONTEDO ========== -->
    <div id="conteudo" style="width: 97%;"><!-- ========== INCIO TABELA DADOS ========== -->
        <?php foreach ($this->Dados as $dados):?>
        <form name="form" id="form" method="post" action ="<?php echo $this->url(array('module'=>'proposta', 'controller' => 'manterorcamento', 'action' => 'salvarprodutos')); ?>">
            <input type="hidden" name="produto" id="produto" value="<?php echo $dados->CodigoProduto ?>" />
            <input type="hidden" name="proposta" id="proposta" value="<?php echo $dados->idProposta ?>" />
            <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto ?>" />
            <div style="float: left; width: 25%">
                <fieldset><legend>Despesas</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="left"><label for="uf">FONTE DE RECURSO*:</label> <br />
                                <select class="select_simples valida" style="width: 90%" id="fonterecurso" name="fonterecurso">
                                    <option value="<?php echo "" ?>"> - Selecione - </option>
                                    <?php foreach($this->Recurso as $recurso) {?>
                                    <option value="<?php echo $recurso->idVerificacao ?>"><?php echo utf8_encode($recurso->VerificacaoDescricao) ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>
            <div style="float: left; width: 40%">
                <fieldset><legend>Localiza&ccedil;&atilde;o</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="left" width="20%"><label for="uf">UF*</label> <br />
                                <select class="select_simples valida" id='uf' name="uf" style="width: 110px">
                                    <option> - Selecione - </option>
                                    <?php foreach($this->Estados as $estados) {?>
                                    <option value="<?php echo $estados->id ?>"><?php echo $estados->descricao ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td align="left">
                                <label for="cidade">MUNIC&Iacute;PIO*</label><br />
                                <select class="select_simples valida" style="width:200px" id='municipio' name='municipio'>
                                    <option> - Selecione uma UF - </option>
                                        <?php if($this->Cidades):  ?>
                                        <?php foreach($this->Cidades as $cidades) {
                                            if($dados->Municipio == $cidades->id) {?>
                                                <option selected="selected" value="<?php echo $cidades->id ?>"><?php echo $cidades->descricao ?></option>
                                            <?php } else { ?>
                                                <option value="<?php echo $cidades->id ?>"><?php echo $cidades->descricao ?></option>
                                            <?php }
                                        } ?>
                                        <?php endif; ?>
                                </select>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 34%">
                <fieldset><legend>Etapa / Meta - <?php echo ($this->etapaSelecionada["etapaNome"]); ?></legend>
                    <input type="hidden" name="etapa" id="etapa" value="<?php echo $this->etapaSelecionada["id"]; ?>" />
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="left"><label for="item">ITEM*</label><br />
                                <select class="select_simples valida" id='item' name="item" style="width:250px">
                                    <option> - Selecione uma Etapa - </option>
                                </select>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 37%">
                <fieldset><legend>Indicadores F&iacute;sicos</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr align="left" lang="">
                            <td><label for="uf">UNIDADE*</label> <br />
                                <select class="select_simples valida" id="unidade" name="unidade" style="width: 200px">
                                    <option value="<?php echo "" ?>"> - Selecione - </option>
                                    <?php foreach($this->Unidade as $unidade) {?>
                                    <option value="<?php echo $unidade->idUnidade ?>"><?php echo $unidade->Descricao ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td><label for="qtd">QTD*</label><br />
                                <input type="text" maxlength="9" class="input_simples valida soma numero" size="3" id="quantidade" name="quantidade" maxlength="10" />
                            </td>
                            <td><label for="ocorrencia">OCORR&Ecirc;NCIA*</label><br />
                                <input type="text" maxlength="4" class="input_simples valida soma numero" size="3" id="ocorrencia" name="ocorrencia" />
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 37%">
                <fieldset><legend>Indicadores Financeiros</legend>
                    <table cellpadding="0" cellspacing="0" width="100%" id="indicadores">
                        <tr>
                            <td nowrap align="left"><label for="uf">VALOR UNIT&Aacute;RIO*</label> <br />
                                <!--<input type="text" maxlength="13" onKeyup="mascara(this, format_moeda);" class="input_simples valida soma numero" size="10" id="vlunitario" name="vlunitario"></td>-->
                                <input type="text" maxlength="13" class="input_simples valida soma numero" size="10" id="vlunitario" name="vlunitario" />
                            </td>
                            <td nowrap align="left">
                                <label for="uf">&nbsp;&nbsp;&nbsp;&nbsp;TOTAL*</label> <br />
                                <b>R$</b><input type="text" maxlength="8" value="" class="input_simples valida" size="12" name="total" id="total" readonly="readonly" />
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 25%">
                <fieldset><legend>Tempo de Dura&ccedil;&atilde;o</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify"><label for="uf">QTD DE DIAS*</label> <br />
                                <input type="text" maxlength="7" value="" class="input_simples valida numero" size="10" name="qtdDias" id="qtdDias" />
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

            <div style="float: left; width: 99%">
                <fieldset><legend>Detalhamento / Justificativa / Observa&ccedil;&otilde;es</legend>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td align="justify">
                                <textarea cols="80" id="editor1" name="editor1" rows="7" class="textarea_simples" style="width:99%;"></textarea>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

        </form>

        <table class="tabela" cellpadding="0" cellspacing="0">
            <tr>
                <td align="center">
                    <input type="button" class="btn_salvar" />
                </td>
            </tr>
        </table>
        <?php endforeach;?>
    </div>
<!-- ========== FIM CONTEDO ========== -->

<!-- ========== INCIO RODAP DO CONTEDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP DO CONTEDO ========== -->
<br clear="all" />

</body>

