<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php
$this->partial("manterpropostaincentivofiscal/inc/menu.inc.php"); // menu
$CadastrarCustos = $this->url(array('controller' => 'manterorcamento', 'action' => 'cadastrarcustos'))."?idPreProjeto=".$this->idPreProjeto;
?>
<script>

    $(document).ready(function(){
        <?php if(isset($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
             //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
             JSBloquearAlteracaoFormulario();
        <?php endif; ?>
    });

    function abrirFrmCadastroItem(url){
        $('html').css('overflow', 'hidden');
        $("#frmCadastroItem").html("");
        // modal com os ddos do dirigente
        $("#frmCadastroItem").dialog("destroy");
        $("#frmCadastroItem").dialog
        ({
            width:$(window).width() - 90,
            height:$(window).height() - 40,
            draggable:false,
            EscClose:false,
            modal:true,
            close: function(){
                window.location.reload();
            }
        });
        jqAjaxLink(url, null, "frmCadastroItem");
    }
</script>
<div id="frmCadastroItem" style="text-align: center; display: none;"></div>
<div id="breadcrumb">
    <ul>
		<li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => '')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
		<li class="second">Planilha Orçamentária</li>
		<li class="last">Custos Administrativos</li>
    </ul>
</div>
<!-- ========== INCIO TTULO ========== -->
<div id="titulo">
    <div>Custos Administrativos</div>
</div>
<!-- ========== FIM TTULO ========== -->

<!-- ========== INCIO CONTEDO ========== -->
<div id="conteudo">
    <?php foreach ($this->Etapas as $etapa):?>
    <?php $CadastrarProduto = $this->url(array('controller' => 'manterorcamento', 'action' => 'cadastrarcustos'))."?etapa=".$etapa->idEtapa."&etapaNome=".$etapa->DescricaoEtapa."&idPreProjeto=".$this->idPreProjeto;?>
    <div class="etapas">

        <table class="tabela">
            <tr>
                <td><input type="button" name="grid1" id="itens_<?php echo $etapa->idEtapa; ?>" class="btn_adicionar" title="Expandir" /><?php echo $etapa->DescricaoEtapa; ?></td>
                <td align="center" style="width: 10%"><input type="button" class="btn_novo" onclick="abrirFrmCadastroItem('<?php echo $CadastrarProduto?>');" /></td>
            </tr>
        </table>
        <div id="div_itens_<?php echo $etapa->idEtapa; ?>" class="miolo_grid_01 sumir">
            <table class="tabela tbitem" id="itens_<?php echo $etapa->idEtapa; ?>">
                <tr class="titulo_tabela">
                    <th>&Iacute;tem</th>
                    <th>Unidade</th>
                    <th>Qtde</th>
                    <th>Ocorr&ecirc;ncia</th>
                    <th>Valor Unit&aacute;rio</th>
                    <th>Total</th>
                    <th>Localiza&ccedil;&atilde;o (UF/Munic&iacute;pio)</th>
                    <th width="10%" colspan="2">A&ccedil;&atilde;o</th>
                </tr>
                <?php foreach ($this->EtapaCusto as $itens):?>
                <?php if($etapa->idEtapa == $itens->idEtapa):?>
                <tr class="fundo">
                    <td><?php echo $itens->DescricaoItem ?></td>
                    <td><?php echo $itens->Unidade ?></td>
                    <td align="right"><?php echo number_format($itens->Quantidade,0) ?></td>
                    <td align="right"><?php echo number_format($itens->Ocorrencia,0) ?></td>
                    <td align="right"><?php echo number_format($itens->ValorUnitario, 2, ",", ".") ?></td>
                    <td align="right"><?php echo  number_format(($itens->Quantidade * $itens->ValorUnitario) * $itens->Ocorrencia, 2, ",", ".") ?></td>
                    <td><?php echo utf8_encode($itens->Municipio) ?>/<?php echo $itens->SiglaUF ?></td>
                    <td class='centro' width="5%">
                        <input type="button" id="btn_editar" name="editar" class="btn_editar" onclick="abrirFrmCadastroItem('<?php echo $this->url(array('controller'=>'manterorcamento', 'action'=>'editarcustos')); ?>?item=<?php echo $this->escape($itens->idItem);?>&etapa=<?php echo $this->escape($itens->idEtapa);?>&idPlanilhaProposta=<?php echo $itens->idPlanilhaProposta?>&idPreProjeto=<?php echo $this->idPreProjeto;?>');">
                    </td>
                    <td class='centro' width="5%">
                        <input type="button" id="btn_excluir" name="excluir" class="btn_exclusao" onclick="excluir(<?php echo $itens->idPlanilhaProposta; ?>);">
                    </td>
                </tr>
                <?php endif; ?>
                <?php endforeach; ?>
            </table>
        </div>


    </div><!-- FIM DIV ETAPAS -->
    <?php endforeach; ?> <!-- FIM FOREACH ETAPAS -->
</div>

<div id="msg"></div>
<script>
function excluir(idPlanilhaProposta)
{
	$("#msg").html('Tem certeza que deseja excluir o registro?');
	$("#msg").dialog('open');
	$("#msg").dialog
    ({
    	width:350,
        height: 180,
        modal: true,
        draggable: false,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            'Não': function()
            {
                $(this).dialog('close');
            },
            'Sim': function()
            {
            	window.location.href="<?php echo $this->url(array('module'=>'proposta', 'controller'=>'manterorcamento', 'action'=>'excluiritensprodutos')); ?>?idPlanilhaProposta="+idPlanilhaProposta+"&retorno=custosadministrativos&idPreProjeto=<?php echo $this->idPreProjeto;?>";
            }
        }
    });
	$(".ui-dialog-titlebar-close").remove();
}

</script>
<!-- ========== INCIO RODAP DO CONTEDO ========== -->
	<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP DO CONTEDO ========== -->
<br clear="all" />
