<script type="text/javascript">
    $('#vlunitario').priceFormat({limit: 10});
    $(document).ready(function() {

        <?php if (!$this->isEditavel) : ?>
            //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
            JSBloquearAlteracaoFormulario();
        <?php endif; ?>

        $('.soma').keyup(function () {
            somaValores();
        });

        if ( $('#planilhaitem').val() != '') {
            somaValores();
        }

        $('.numero').keydown(function (event) {
            if ((event.keyCode >= 96 && event.keyCode <= 105) || (event.keyCode >= 48 && event.keyCode <= 57) || event.keyCode == 8 || event.keyCode == 9) {
                return true;
            }
            else
                return false;
        });

        $("#error").dialog({
            resizable: true,
            width: 450,
            height: 150,
            modal: true,
            autoOpen: false,
            buttons: {
                'OK': function () {
                    $(this).dialog('close');
                }
            }
        });
    });

    function somaValores(){

        var soma = 0;
        var vlunitario = $("#vlunitario").val();

        // retira os pontos e as virgulas, deixando somente numeros
        vlunitario = vlunitario.replace(/\D/g, "");
        vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

        // adiciona o ponto na casa decimal
        vlunitario = vlunitario.replace(/(\d)(\d{2})$/, "$1.$2");

        // converte para float e adiciona precisao decimal
        qtd = parseFloat($("#qtd").val()).toFixed(2);
        ocorrencia = parseFloat($("#ocorrencia").val()).toFixed(2);
        valor = parseFloat(vlunitario).toFixed(2);
        soma = parseFloat(qtd * ocorrencia * valor).toFixed(2); // armazena o resultado
        if (soma >= 0) {
            $("#total").val(soma);
        } else {
            $("#total").val(0);
        }
        $("#total").priceFormat();
    }

    function Limpar(valor, validos) {
        // retira caracteres invalidos da string
        var result = "";
        var aux;
        for (var i=0; i < valor.length; i++) {
            aux = validos.indexOf(valor.substring(i, i+1));
            if (aux>=0) {
                result += aux;
            }
        }
        return result;
    }

    //Formata numero tipo moeda usando o evento onKeyDown

    function Formata(campo,tammax,teclapres,decimal) {
        var tecla = teclapres.keyCode;
        vr = Limpar(campo.value,"0123456789");
        tam = vr.length;
        dec=decimal

        if (tam < tammax && tecla != 8){ tam = vr.length + 1 ; }

        if (tecla == 8 )
        { tam = tam - 1 ; }

        if ( tecla == 8 || tecla >= 48 && tecla <= 57 || tecla >= 96 && tecla <= 105 )
        {

            if ( tam <= dec )
            { campo.value = vr ; }

            if ( (tam > dec) && (tam <= 5) ){
                campo.value = vr.substr( 0, tam - 2 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 6) && (tam <= 8) ){
                campo.value = vr.substr( 0, tam - 5 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ;
            }
            if ( (tam >= 9) && (tam <= 11) ){
                campo.value = vr.substr( 0, tam - 8 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 12) && (tam <= 14) ){
                campo.value = vr.substr( 0, tam - 11 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - dec, tam ) ; }
            if ( (tam >= 15) && (tam <= 17) ){
                campo.value = vr.substr( 0, tam - 14 ) + "." + vr.substr( tam - 14, 3 ) + "." + vr.substr( tam - 11, 3 ) + "." + vr.substr( tam - 8, 3 ) + "." + vr.substr( tam - 5, 3 ) + "," + vr.substr( tam - 2, tam ) ;}
        }

    }
</script>

<div class="container-salic">
    <div class="row">
        <div class="col s12">
            <div class="section">
                <h5>Cadastrar novo item
                    <span class="badge" data-badge-caption=""><div><?php echo $this->Etapa['Descricao']; ?></div> <i class="material-icons">place</i> <div><?php echo $this->Municipio['Descricao']; ?> - <?php echo $this->Estado['Descricao']; ?></div></span>
                </h5>
            </div>

            <?php foreach ($this->Dados as $dados) : ?>
                <form name="form" id="form" method="post" action ="<?php echo $this->url(array('module'=>'proposta', 'controller' => 'manterorcamento', 'action' => 'salvaritem')); ?>">
                    <input type="hidden" name="produto" id="produto" value="<?php echo $dados->CodigoProduto ?>" />
                    <input type="hidden" name="idPlanilhaProposta" id="idPlanilhaProposta" value="<?php echo $dados->idPlanilhaProposta ?>" />
                    <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto ?>" />
                    <input type="hidden" name="uf" id="uf" value="<?php echo $this->Estado['idUF']; ?>" />
                    <input type="hidden" name="municipio" id="municipio" value="<?php echo $this->Municipio['idMunicipioIBGE'] ?>" />
                    <input type="hidden" name="idPlanilhaEtapa" id="idPlanilhaEtapa" value="<?php echo $this->Etapa['idPlanilhaEtapa'] ?>" />
                    <input type="hidden" name="valorMediana" id="valorMediana" value="" />

                    <div class="row">
                        <div class="col s4">
                            <label for="planilhaitem">Item</label>
                            <select class="valida browser-default" id="planilhaitem" name="planilhaitem">
                                <option disabled selected> - Selecione - </option>
                                <?php foreach($this->Item as $itens) : ?>
                                    <option value="<?php echo $itens->idPlanilhaItens ?>" <?php echo $dados->idItem == $itens->idPlanilhaItens ? "selected" : ""; ?>><?php echo $itens->Descricao ?></option>
                                <?php endforeach; ?>
                            </select>
                            <br>
                        </div>

                        <div class="col s3">
                            <label for="unidade">Unidade</label>
                            <select class="valida browser-default" id="unidade" name="unidade">
                                <option disabled selected> - Selecione - </option>
                                <?php foreach($this->Unidade as $unidade) : ?>
                                    <option value="<?php echo $unidade->idUnidade ?>" <?php echo ($dados->Unidade == $unidade->idUnidade) ? "selected" : ""; ?>><?php echo $unidade->Descricao ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <div class="input-field col s1">
                            <input placeholder="0" type="text" maxlength="4" class="valida numero" size="4" value="<?php echo isset($dados->QtdDias) ? $dados->QtdDias: ''; ?>" name='qtdDias' id='qtdDias' />
                            <label for="qtdDias">Qtd de dias</label>
                        </div>

                        <div class="input-field col s1">
                            <input placeholder="0" type="text" class="valida soma numero" size="3" id="qtd" maxlength="10" name="qtd" value="<?php echo isset($dados->Quantidade) ? (int) $dados->Quantidade : ''; ?>">
                            <label for="qtd">Quantidade</label>
                        </div>

                        <div class="input-field col s1">
                            <input placeholder="0" type="text" maxlength="4" class="valida soma numero" size="3" id="ocorrencia" maxlength="10" name="ocorrencia" value="<?php echo isset($dados->Ocorrencia) ? (int) $dados->Ocorrencia : ''; ?>">
                            <label for="ocorrencia">Ocorr&ecirc;ncia</label>
                        </div>
                        <div class="input-field col s1">
                            <input placeholder="R$" type="text" maxlength="13" class="valida soma numero" size="10" id="vlunitario" name="vlunitario" value="<?php echo isset($dados->ValorUnitario) ? number_format($dados->ValorUnitario, 2, ",", ".") : '';?>">
                            <label for="vlunitario">Valor Unit&aacute;rio</label>
                        </div>
                        <div class="input-field col s1">
                            <input placeholder="R$" type="text" value="" maxlength="6" class="disabled" size="15" name="total" id="total" disabled>
                            <label for="total">Total</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s4">
                            <label for="fonterecurso">Fonte de recurso</label><br><br><br>
                            <select class="valida browser-default" id="fonterecurso" name="fonterecurso">
                                <?php
                                    if( isset($dados->Recurso))
                                        $selected = $dados->Recurso;
                                    else
                                        $selected = 109;
                                ?>
                                <?php foreach($this->Recurso as $recurso) {?>
                                    <option <?php echo ($recurso->idverificacao == $selected) ? 'selected' : ''; ?>  value="<?php echo $recurso->idverificacao ?>"><?php echo $recurso->verificacaodescricao ?></option>
                                <?php } ?>
                            </select>
                        </div>

                        <div id="justificativa_current_item" class="input-field col s8 justificativa">
                            <label for="justificativa">Detalhamento / Justificativa / Observa&ccedil;&otilde;es (Opcional)</label>
                            <textarea cols="80" id="justificativa" name="justificativa" rows="7" class="materialize-textarea browser-default" placeholder=" "><?php echo $dados->Justificativa; ?></textarea>
                            <input type="hidden" name="stCustoPraticado" class="stCustoPraticado" value="<?php echo $dados->stCustoPraticado; ?>" />
                        </div>
                    </div>
                    <?php if( !empty($this->locaisRealizacao) && count($this->locaisRealizacao) > 1  ) : ?>
                        <div class="row">
                            <div class="input-field  col s6">
                                <select id="combo_cidades" multiple="multiple" name="comboOutrasCidades[]" class="comboOutrasCidades">
                                    <option disabled>Selecione as cidades</option>
                                    <?php foreach ($this->locaisRealizacao as $local) :?>
                                        <?php if( $local['idMunicipioIBGE'] != $this->Municipio['idMunicipioIBGE'] ) : ?>
                                            <option value="<?= $local['idUF'] ?>:<?= $local['idMunicipioIBGE'] ?>"><?= $local['uf']?> - <?= $local['cidade'] ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </select>
                                <label>Deseja aplicar este item para outras cidades? (Opcional)</label>
                            </div>
                        </div>

                        <div id="another-cities">

                        </div>
                    <?php endif; ?>
                    <?php if ($this->isEditavel) : ?>
                        <div class="row">
                            <div class="input-field col s12 center-align">
                                <a class="btn-close-modal waves-effect waves-teal btn btn-info"><i class="material-icons left">clear</i>Fechar</a>
                                <a id="btn-salvar" href="javascript:void(0);" class="disabled btn waves-effect waves-light" name="action">Salvar
                                    <i class="material-icons right">send</i>
                                </a>
                            </div>
                        </div>
                    <?php endif; ?>
                </form>
            <?php endforeach;?>
        </div>
    </div>
</div>

<script>
    $3(document).ready(function(){
        $3('.modal').find('select').material_select();

        $3('.btn-close-modal').on('click', function() {
            $3('#modal').modal('close');
        });



        // ao clicar em todas cidades marcar todas
//        $3("ul.dropdown-content li:nth-child(2)").on('click', function(){
//            $3('ul.dropdown-content li').not(':first-child,:nth-child(2)').each(function(index) {
//                $3(this).click();
//            });
//        });

        $3('body').on('click', '.btn-salvar', function () {


            var validar = true;
            $3('.valida').each(function () {
                if ($3(this).val() == '') {
                    validar = false;
                }
            });

            if (validar == false) {
                Materialize.toast("Dados obrigat&oacute;rios n&atilde;o informados!", 4000);
                return false;
            } else {
                if ($3("#qtd").val() == 0) {
                    Materialize.toast('Quantidade n&atilde;o pode ser igual a zero', 4000);
                    $3("#qtd").focusin();
                    return false;
                }

                if ($3("#ocorrencia").val() == 0) {
                    Materialize.toast('Ocorr&ecirc;ncia n&atilde;o pode ser igual a zero', 4000);
                    $3("#ocorrencia").focusin();
                    return false;
                }

                var vlunitario = $3("#vlunitario").val();
                vlunitario = vlunitario.replace(/\D/g, "");
                vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

                if (vlunitario == 0) {
                    Materialize.toast('Valor unit&aacute;rio n&atilde;o pode ser igual a zero', 4000);
                    $3("#vlunitario").focusin();
                    return false;
                }

                if ($3("#qtdDias").val() == 0) {
                    Materialize.toast('Quantidade de dias n&atilde;o pode ser igual a zero', 4000);
                    $3("#qtdDias").focusin();
                    return false;
                }

                if ($3("#justificativa.valida").val() == '') {
                    Materialize.toast('Justificativa neste caso &eacute; obrigat&oacute;ria!', 4000);
                    $3("#justificativa").focus();
                    return false;
                }


                $3.post($3('#form').attr('action'), $3('#form').serialize(), function (result) {

                    $3.each(result, function(index, item) {
                        console.log(result);

                        var uf = item.dados.UfDespesa;
                        var mun = item.dados.MunicipioDespesa;
                        var stringLocalizacao = $3("select option[value='" + uf + ":" +  mun + "']").text();

                        if (item.status == '1') {
                            if( item.action == 'update') {
                                $("#item-planilha-" +item.idPlanilhaProposta).replaceWith(item.html);
                            }
                            else if( item.action == 'insert') {

                                var produto = item.dados.idProduto;
                                var etapa = item.dados.idEtapa;

                                var idEtapa = "#etapa" + produto + "" + etapa + "" + mun;

                                $3(idEtapa + " div.info").hide();
                                $3(idEtapa + ' table tbody').append(item.html);
                                $3("#planilhaitem").focus();
                            }

                            if(item.close == '1' )
                                $3('#modal').modal('close');

                            $3('#form')[0].reset();
                            Materialize.toast(stringLocalizacao + ' '+ item.msg, 4000, 'green white-text');
                        } else {
                            Materialize.toast(stringLocalizacao + ' ' +item.msg, 8000, 'red darken-1 white-text');
                        }
                    });

                    $3.each($('#custosvinculados[data-ajax-render]'), function () {
                        $3.ajaxRender({
                            strUrl: $('#custosvinculados').attr('data-ajax-render'),
                            strTarget: '#custosvinculados'
                        });
                    });
                });
            }
            return false;
        });

        $3('body').on('focusout', '#vlunitario', function () {
            if($3(this).val() == 0)
                return false;

            var msg_old = $3('#modal-pre-loader #msg-pre-loader p').html();
            $3('#modal-pre-loader #msg-pre-loader p').html('Verificando valor unitário ...');

            $3('#modal-pre-loader').modal('open');

            $3("#btn-salvar").removeClass('btn-salvar').addClass('disabled');
            $3('#justificativa').addClass('valida');

            var urlAction = "<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterorcamento', 'action' => 'buscar-valor-mediana-ajax')); ?>";

            var dados = {
                idproduto: $3("#produto").val(),
                idplanilhaitem: $3("#planilhaitem").val(),
                idunidade: $3("#unidade").val(),
                vlunitario: $3("#vlunitario").val(),
                idufdespesa: $3("#uf").val(),
                idmunicipiodespesa: $3("#municipio").val()
            };

            $3.post(urlAction, dados, function (result) {
                if (result.status == '1') {
                    $3("#btn-salvar").addClass('btn-salvar').removeClass('disabled');

                    resetDadosMediana();
                } else {
                    Materialize.toast(result.msg, 60000, 'mensagem1 orange darken-3 white-text');
                    $3("#btn-salvar").addClass('disabled').removeClass('btn-salvar ');
                    $3('#justificativa').addClass('valida');
                    $3("#vlunitario").parent().addClass("danger");
                    $3("#justificativa_current_item label").text('Justificativa para valor unit\xE1rio maior que R$ ' + result.valorMediana + ' (Obrigat\xF3rio)').parent().addClass("danger");
                    $3("#justificativa_current_item .stCustoPraticado").val(1);
                }

                $3('#modal-pre-loader').modal('close');
                $3('#modal-pre-loader #msg-pre-loader p').html(msg_old);

            });

            return false;
        });

        // verificar se os textareas foram preenchidos quando obrigatórios
        $3('body').on('keyup', '.justificativa textarea', function () {

            var qtdJustificativaValida = parseInt($3(".justificativa textarea.valida").length);
            var qtdJustificaValidaVazia = parseInt($3(".justificativa textarea.valida").filter(function() {
                return !this.value;
            }).length);

            if (qtdJustificaValidaVazia == 0 || qtdJustificativaValida == 0) {
                $3("#btn-salvar").addClass('btn-salvar').removeClass('disabled');
                $3('.mensagem1').fadeOut(function(){
                    $(this).remove();
                });
            }else{
                $3("#btn-salvar").removeClass('btn-salvar').addClass('disabled');
            }
        });

        var array_cidades = '';

        $3('.comboOutrasCidades ul.dropdown-content li').on('click', function () {

            var array_combo = $3('#combo_cidades').val();
            var diferenca = [];

            $3.grep(array_combo, function (el) {
                if ($3.inArray(el, array_cidades) == -1) diferenca.push(el);
            });

            // limpar os itens que foram desmarcados
            $3("#another-cities div[localizacao]").each(function() {
                var checkExist = $3.inArray($3(this).attr('localizacao'), array_combo);

                if(checkExist == -1) {
                    $3(this).remove();
                }
            });

            // adicionar novos itens marcados
            $3.each(diferenca, function(index, item) {

                var ufMunicipio = item.split(':');
                var uf = ufMunicipio[0];
                var municipio = ufMunicipio[1];
                var stringLocalizacao = $3(".comboOutrasCidades option[value='" + item + "']").text();
                var urlAction = "<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterorcamento', 'action' => 'buscar-valor-mediana-ajax')); ?>";

                var dados = {
                    idproduto: $3("#produto").val(),
                    idplanilhaitem: $3("#planilhaitem").val(),
                    idunidade: $3("#unidade").val(),
                    vlunitario: $3("#vlunitario").val(),
                    idufdespesa: uf,
                    idmunicipiodespesa: municipio,
                    stringLocalizacao: stringLocalizacao
                };

                $3.post(urlAction, dados, function (result) {

                    var msg_old = $3('#modal-pre-loader #msg-pre-loader p').html();
                    $3('#modal-pre-loader #msg-pre-loader p').html('Verificando valor unitário ...');
                    $3('#modal-pre-loader').modal('open');

                    if (result.status == '1') {
                        $3("#another-cities").find("[localizacao='" + item + "']").remove();
                    } else {
                        Materialize.toast(result.msg, 60000, 'mensagem1 orange darken-3 white-text');

                        $3("#btn-salvar").addClass('disabled').removeClass('btn-salvar ');
                        $3('#justificativa-wraper-' + item).remove();

                        var $klon = $3('#justificativa-current-item').clone().prop('id', 'justificativa-wraper-' + item).attr('localizacao', item);
                        $klon.find("label").text(stringLocalizacao + ' - Justificativa para valor unit\xE1rio maior que R$ ' + result.valorMediana + ' (Obrigat\xF3rio)').parent().addClass("danger");
                        $klon.find('textarea').prop('id','justificativa_' + item).prop('name','justificativa_' + item).addClass('valida').val('');
                        $klon.find('.stCustoPraticado').prop('name','stCustoPraticado_' + item).val(1);
                        $klon.appendTo( "#another-cities");
                    }

                    $3('#modal-pre-loader').modal('close');
                    $3('#modal-pre-loader #msg-pre-loader p').html(msg_old);

                });

            });

            array_cidades = array_combo;
        });

        function resetDadosMediana() {
            $3('#justificativa').removeClass('valida');
            $3("#vlunitario").parent().removeClass("danger");
            $3("#justificativa_current_item label").text('Detalhamento / Justificativa / Observa\xE7\xF5es (Opcional)').parent().removeClass("danger");
            $3("#justificativa_current_item .stCustoPraticado").val(0);
        }


    });
</script>