<?php echo $this->partial("inc/menu.phtml", $this); ?>

<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Planilha Or&ccedil;ament&aacute;ria Geral</h1>

                    <?php if (isset($this->proposta['idpreprojeto'])) {
                        gerarNovoBreadCrumb(array(
                            array('Or&ccedil;amento do Projeto' => ''),
                            array('Planilha Or&ccedil;ament&aacute;ria Geral' => '')
                        ));
                    }
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="content">
            <div id="conteudo" class="card-panel">

                <?php /***** CARREGA A PLANILHA ORCAMENTARIA *****/ ?>
                <script type="text/javascript">
                    jqAjaxLink('<?php echo $this->Url(array('module'=>'default','controller' => 'index', 'action' => 'montar-planilha-orcamentaria')) ?>?idPronac=<?php echo $this->idPreProjeto; ?>&tipoPlanilha=<?php echo $this->tipoPlanilha; ?>', '', 'planilhaOrcamentariaMontada');
                </script>
                <div id="planilhaOrcamentariaMontada"></div>
                <?php /****** FIM DA PLANILHA ORCAMENTARIA ******/ ?>
            </div>
        </div>
    </div>
</div>

<script>

    function AbrirFecharPlanilha(elemento) {
        $('.' + elemento).toggle();
        if ($('#' + elemento).hasClass('icn_mais')) {
            $('#' + elemento).addClass('icn_menos');
            $('#' + elemento).removeClass('icn_mais');
        } else {
            $('#' + elemento).addClass('icn_mais');
            $('#' + elemento).removeClass('icn_menos');
        }
    }

    $(document).ready(function()
    {
        $('a.sanfona').click(function()
        {
            $(this).next().toggle('fast');
        });

        $(".icn_menos").click(function() {
            var tipo = $(this).attr('tipo');
            var aberto = $(this).attr('aberto');
            if (aberto == 'true') {
                adisplay = 'none';
                $(this).attr('aberto', 'false')
                $(this).removeClass('icn_menos').addClass('icn_mais')
            }
            else {
                adisplay = '';
                $(this).attr('aberto', 'true')
                $(this).removeClass('icn_mais').addClass('icn_menos')
            }
            if (tipo == 'fonte') {
                fonte = $(this).attr('fonte');
                $(".master[fonte='" + fonte + "']").css('display', adisplay);
                $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
            }
            if (tipo == 'produto') {
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                $(".produto[produto='" + produto + "'][fonte='" + fonte + "']").css('display', adisplay);
            }
            if (tipo == 'etapa') {
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                $(".etapa[produto='" + produto + "'][etapa='" + etapa + "'][fonte='" + fonte + "']").css('display', adisplay);
            }
            if (tipo == 'cidade') {
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                cidade = $(this).attr('cidade');
                $(".cidade[produto='" + produto + "'][etapa='" + etapa + "'][cidade='" + cidade + "'][fonte='" + fonte + "']").css('display', adisplay);
            }
        });
        $(".item").mouseover(function() {
            $(this).addClass('fundo_linha3');
        });
        $(".item").mouseout(function() {
            $(this).removeClass('fundo_linha3');
        });
        $(".item").click(function() {
            if ($(this).hasClass('fundo_linha4')) {
                $(this).removeClass('fundo_linha4');
            }
            else {
                $(this).addClass('fundo_linha4');
            }
        });
    });
</script>