<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/library/materialize/css/materialize.css">
<!--        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">-->
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/library/materialize/css/materialize-custom.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/animate.css">
<script>
    $(document).ready(function(){

        <?php if(isset($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>
    });
</script>

<div class="row container">
    <h5 class="light">Custo por produto </h5>
</div>


<!-- Page Layout here -->
<div class="row">
    <div class="col s12 m4 l2">
        <?php  echo $this->partial("manterpropostaincentivofiscal/inc/menu.inc.php", $this); ?>
    </div>
    <div id="container-list" class="col s12 m10 l10" data-ajax-render='/proposta/manterorcamento/listarprodutos/idPreProjeto/<?php echo( isset($this->idPreProjeto) ) ? $this->idPreProjeto : ''; ?>'></div>
</div>



<div id="frmCadastroItem" style="text-align: center; display: none;"></div>
<?php //echo $this->partial("manterpropostaincentivofiscal/inc/menu.inc.php", $this); ?>
<?php
        $controller = "manterorcamento";
        $links = array(
            array('Lista de Propostas' => array('controller' => 'manterpropostaincentivofiscal','action' => 'listar-propostas')),
            array('Or&ccedil;amento' => array())
        );
montaGuiaLinks($controller, $links);
?>

<div id="titulo">
    <div>Custos por Produtos <?php echo montaBotaoVoltar($controller, $links); ?></div></div>
</div>

<div id="conteudo">

    <?php
    if(count($this->Produtos)>0) {

        foreach ($this->Produtos as $produtos): ?>

            <div class="_produto">

                <table class='tabela' style="background: transparent">
                    <tbody>
                        <tr class="principal"><td align="left"><input type="button" id="" class="btn_adicionar produto" /><?php echo $produtos->DescricaoProduto;?></td></tr>

                        <?php foreach ($this->Etapa as $etapa) : ?>
                            <?php $CadastrarProduto = $this->url(array('controller' => 'manterorcamento', 'action' => 'cadastrarprodutos'))."?produto=".$produtos->CodigoProduto."&etapa=".$etapa->idEtapa."&etapaNome=".$etapa->DescricaoEtapa."&idPreProjeto=".$produtos->idProposta;?>

                            <?php if ($produtos->CodigoProduto) : ?>

                                <tr class="etapas" style="display: none;">
                                    <td>
                                        <table summary="Produto" style="margin: 0px;">
                                            <tbody>
                                                <tr onclick="abrirDinamico('.itens_<?php echo $produtos->CodigoProduto."_".$etapa->idEtapa; ?>', $(this));" style="cursor:pointer">
                                                    <th width="30px">
                                                        <img style="cursor: pointer; width: 14px; height: 14px;" class="" src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" alt="Adicionar" />
                                                    </th>
                                                    <th class="esquerda"><?php echo $etapa->DescricaoEtapa; ?></th>
                                                    <th class="direita">
                                                        <input type="button" class="btn_novo" onclick="abrirFrmCadastroItem('<?php echo $CadastrarProduto; ?>');" />
                                                    </th>
                                               </tr>
                                                <tr class="itens_<?php echo $produtos->CodigoProduto."_".$etapa->idEtapa; ?>" style='display: none;'>
                                                    <td colspan="3" style="margin: 0; padding:10px;">
                                                        <table class="tbitem" width="100%" style='margin: 0; border: 1px solid #aaa;' >
                                                            <tr class="destacar" align="center">
                                                                <td>Item</td>
                                                                <td>Unidade</td>
                                                                <td>Qtde</td>
                                                                <td>Ocorr&ecirc;ncia</td>
                                                                <td>Valor Unit&aacute;rio</td>
                                                                <td>Total</td>
                                                                <td>Localiza&ccedil;&atilde;o (Munic&iacute;pio/UF)</td>
                                                                <td colspan="2" width="10%">A&ccedil;&otilde;es</td>
                                                            </tr>
                                                            <?php if(isset($this->Item)) : ?>
                                                                <?php foreach ($this->Item as $itens) : ?>
                                                                    <?php if ($produtos->CodigoProduto == $itens->CodigoProduto) :
                                                                        if ($etapa->idEtapa == $itens->idEtapa) :  ?>

                                                                            <?php
                                                                                $valorTotalItem = ($itens->Quantidade * $itens->ValorUnitario) * $itens->Ocorrencia;
                                                                                $valorProjeto = $valorTotalItem + $valorProjeto;
                                                                            ?>
                                                                            <tr class='fundo' style='background-color: #fff' align="center">
                                                                                <td><?php echo $itens->DescricaoItem; ?></td>
                                                                                <td><?php echo $itens->Unidade; ?></td>
                                                                                <td><?php echo number_format($itens->Quantidade,0) ?></td>
                                                                                <td><?php echo number_format($itens->Ocorrencia,0) ?></td>
                                                                                <td><?php echo number_format($itens->ValorUnitario, 2, ",", ".") ?></td>
                                                                                <td><?php echo number_format(($itens->Quantidade * $itens->ValorUnitario) * $itens->Ocorrencia, 2, ",", ".") ?></td>
                                                                                <td><?php echo $itens->Municipio; ?>/<?php echo $itens->SiglaUF; ?></td>
                                                                                <td width="5%">
                                                                                    <input type="button" id="btn_editar" name="editar" style="width: 88px" class="btn_editar" onclick="abrirFrmCadastroItem('<?php echo $this->url(array('controller'=>'manterorcamento', 'action'=>'editarprodutos')); ?>?item=<?php echo $this->escape($itens->idItem); ?>&etapa=<?php echo $this->escape($etapa->idEtapa);?>&produto=<?php echo $this->escape($produtos->CodigoProduto);?>&idPlanilhaProposta=<?php echo $itens->idPlanilhaProposta;?>&idPreProjeto=<?php echo $this->escape($produtos->idProposta);?>');">
                                                                                </td>
                                                                                <td class='centro' width="5%">
                                                                                    <input type="button" id="btn_excluir" name="excluir" style="width: 88px" class="btn_exclusao" onclick="excluir(<?php echo $itens->idPlanilhaProposta; ?>);">
                                                                                </td>
                                                                            </tr>
                                                                        <?php endif; ?>
                                                                    <?php endif; ?>
                                                                <?php endforeach; ?>
                                                            <?php else : ?>
                                                                <tr  class='fundo'>
                                                                    <td colspan="10">
                                                                        <div class="center" align="center">Nenhum item cadastrado</div>
                                                                    </td>
                                                                </tr>
                                                            <?php endif; ?>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                </table>
            </div>

        <?php endforeach; ?>
            <?php if(!empty($valorProjeto) ) : ?>
                <?php if ($this->EtapaCusto) : ?>
                    <div class="custosvinculados">

                        <table class='tabela' style="background: transparent">

                            <?php foreach ($this->EtapaCusto as $etapaCusto) : ?>

                                <tr class="principal">
                                    <td align="left"><input type="button" id="" class="btn_adicionar produto" /><?php echo $etapaCusto->DescricaoEtapa; ?></td>
                                </tr>

                                <tr class="etapas" width="100%" style="display:none">
                                    <td colspan="2" style="margin: 0; padding:10px;">

                                        <?php if($this->ItensEtapaCusto) : ?>
                                            <table class="tbitem" width="100%" style='margin: 0; border: 1px solid #aaa;' >
                                                <tr class="destacar" align="center">
                                                    <td>Item</td>
                                                    <td>Munic&iacute;pio/UF</td>
                                                    <td>Total</td>
                                                </tr>
                                                <?php $valorTotalCustosVinculados = null; ?>
                                                <?php foreach ($this->ItensEtapaCusto as $itemEtapaCusto) : ?>
                                                    <?php if ($etapaCusto->idEtapa == $itemEtapaCusto->idEtapa) :  ?>
                                                        <tr class='fundo' style='background-color: #fff' align="center">
                                                            <td><?php echo $itemEtapaCusto->DescricaoItem; ?></td>
                                                            <td><?php echo $itemEtapaCusto->Municipio; ?>/<?php echo $itemEtapaCusto->SiglaUF; ?></td>
                                                            <td><?php echo number_format($itemEtapaCusto->valorunitario, 2, ",", ".") ?></td>
                                                            <?php $valorTotalCustosVinculados = $itemEtapaCusto->valorunitario + $valorTotalCustosVinculados; ?>
                                                        </tr>
                                                    <?php endif; ?>

                                                <?php endforeach; ?>
                                            </table>
                                        <?php else: ?>
                                            <div class="center" align="center">Nenhum item cadastrado</div>
                                        <?php endif; ?>
                                    </td>
                                </tr>

                            <?php endforeach; ?>
                        </table>

                        <table class='tabela' style="background: transparent">
                            <tr>
                                <td>
                                    <table summary="Produto" style="margin: 0px;">
                                        <tr>
                                            <th colspan="2" class="centro"><?php echo "Resumo da Planilha Or&ccedil;ament&aacute;ria"; ?></th>
                                        </tr>
                                        <tr class="" align="center">
                                            <td>Valor do Projeto: </td>
                                            <td><?php echo number_format($valorProjeto, 2, ",", "."); ?></td>
                                        </tr>
                                        <tr class="" align="center">
                                            <td>Valor Custos Vinculados: </td>
                                            <td><?php echo number_format($valorTotalCustosVinculados, 2, ",", "."); ?></td>
                                        </tr>
                                        <tr class="" align="center">
                                            <td>Valor total do Projeto: </td>
                                            <td><?php echo number_format($valorTotalCustosVinculados + $valorProjeto, 2, ",", "."); ?></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        <?php } else { ?>
        <br>
        <div class="center" align="center">Nenhum produto cadastrado</div>
        <br>
    <?php } ?>
    <br>
</div>
<!-- FIM DIV CONTEUDO -->
<div id="msg"></div>

<script>
function excluir(idPlanilhaProposta)
{
	$("#msg").html('Tem certeza que deseja excluir o registro?');
	$("#msg").dialog('open');
	$("#msg").dialog
    ({
    	width:350,
        height: 180,
        modal: true,
        draggable: false,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            'Não': function()
            {
                $(this).dialog('close');
            },
            'Sim': function()
            {
            	window.location.href="<?php echo $this->url(array('controller'=>'manterorcamento', 'action'=>'excluiritensprodutos')); ?>?idPlanilhaProposta="+idPlanilhaProposta+"&retorno=produtoscadastrados&idPreProjeto=<?php echo $this->idPreProjeto;?>";
            }
        }
    });
	$(".ui-dialog-titlebar-close").remove();
}

</script>
<!-- ========== INCIO RODAPE DO CONTEDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEDO ========== -->
<br clear="all" />


<script>

//    $('.btn_salvar').click(function () {
//
//        var validar = true;
//        $('.valida').each(function () {
//            if ($(this).val() == '') {
//                validar = false;
//            }
//        });
//
//        if (validar == false) {
//            $("#error").html('Dados obrigat&oacute;rios n&atilde;o informados!');
//            $("#error").dialog('open');
//
//        } else {
//            if ($("#qtd").val() == 0) {
//                $("#error").html('Quantidade n&atilde;o pode ser igual a zero');
//                $("#error").dialog('open');
//                $("#qtd").val('');
//                return false;
//            }
//
//            if ($("#ocorrencia").val() == 0) {
//                $("#error").html('Ocorr&ecirc;ncia n&atilde;o pode ser igual a zero');
//                $("#error").dialog('open');
//                $("#ocorrencia").val('');
//                return false;
//            }
//
//            var vlunitario = $("#vlunitario").val();
//            vlunitario = vlunitario.replace(/\D/g, "");
//            vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");
//
//            if (vlunitario == 0) {
//                $("#error").html('Valor unit&aacute;rio n&atilde;o pode ser igual a zero');
//                $("#error").dialog('open');
//                $("#vlunitario").val('');
//                return false;
//            }
//
//            if ($("#qtdDias").val() == 0) {
//                $("#error").html('Quantidade de dias n&atilde;o pode ser igual a zero');
//                $("#error").dialog('open');
//                $("#qtdDias").val('');
//                return false;
//            } else {
//                var jstv = $('#editor1').val();
//                if (jstv.length > 500) {
//                    $("#justificativaErro").dialog("destroy");
//                    $("#justificativaErro").html('O campo Justificativa n&atilde;o pode ultrapassar 500 caracteres!');
//                    $("#justificativaErro").dialog({
//                        width: 320,
//                        height: 180,
//                        title: 'Alerta!',
//                        draggable: true,
//                        EscClose: true,
//                        modal: true,
//                        buttons: {
//                            'Ok': function () {
//                                $(this).dialog('close');
//                            }
//                        }
//                    });
//                    return false;
//                }
//
//                $.ajax({
//                    url: $("#form").attr('action'),
//                    type: "POST",
//                    async: false,
//                    data: $("#form").serialize(),
//                    success: function (data) {
//                        if( data.error) {
//                            $("#msg").html(data.error);
//                        }else {
//                            $("#msg").html(data.success);
//                        }
//
//                    }, dataType: 'json'
//                });
//
//                $("#msg").dialog
//                ({
//                    width: 500,
//                    height: 250,
//                    draggable: true,
//                    EscClose: true,
//                    modal: true,
//                    close: function () {
//                        $("#item").val("");
//                        $("#unidade").val("");
//                        $("#qtd").val("");
//                        $("#ocorrencia").val("");
//                        $("#vlunitario").val("");
//                        $("#qtdDias").val("");
//                        $("#total").val("");
//                        $("#editor1").val("");
//                    },
//                    buttons: {
//                        'N\xE3o': function () {
//                            $("#frmCadastroItem").dialog("destroy");
////                                window.location.reload();
//                        },
//                        'Sim': function () {
//                            $(this).dialog('close');
//                        }
//                    }
//                });
//            }
//        }
//    });



    $3(document).ready(function () {
        $3('body').on('click', '.btn_salvar', function () {

            var validar = true;
            $3('.valida').each(function () {
                if ($3(this).val() == '') {
                    validar = false;
                }
            });

            if (validar == false) {
                Materialize.toast("Dados obrigat&oacute;rios n&atilde;o informados!", 4000);
            } else {
                if ($3("#qtd").val() == 0) {
                    Materialize.toast('Quantidade n&atilde;o pode ser igual a zero', 4000);
                    $3("#qtd").focusin();
                    return false;
                }

                if ($3("#ocorrencia").val() == 0) {
                    Materialize.toast('Ocorr&ecirc;ncia n&atilde;o pode ser igual a zero', 4000);
                    $3("#ocorrencia").focusin();
                    return false;
                }

                var vlunitario = $3("#vlunitario").val();
                vlunitario = vlunitario.replace(/\D/g, "");
                vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

                if (vlunitario == 0) {
                    Materialize.toast('Valor unit&aacute;rio n&atilde;o pode ser igual a zero', 4000);
                    $3("#vlunitario").focusin();
                    return false;
                }

                if ($3("#qtdDias").val() == 0) {
                    Materialize.toast('Quantidade de dias n&atilde;o pode ser igual a zero', 4000);
                    $3("#qtdDias").focusin();
                    return false;
                }


                $3.post($3('#form').attr('action'), $3('#form').serialize(), function (result) {
                    result = $3.parseJSON(result);
                    if (result.status == '1') {
                        $3('#modal').modal('close');
                        $3('#form')[0].reset();
                        $3.ajaxRender()
                        Materialize.toast(result.msg, 4000);
                        $3.each($('div[data-ajax-render]'), function () {
                            $3.ajaxRender({
                                strUrl: $(this).attr('data-ajax-render'),
                                strTarget: '#' + $(this).attr('id')
                            });
                        });
                    } else {
//                        if (Object.keys(result.msg).length > 1) {
//                            $3.each(result.msg, function (strNameElement, strMsg) {
//                                var elm = $3('[name=' + strNameElement + ']'),
//                                    elmLabel = elm.closest('div.input-field').find('label'),
//                                    strLabel = elm.closest('div.input-field').find('label').html();
//                                if (elm.length > 0) {
//                                    elm.focus();
//                                    Materialize.toast('Campo ' + strLabel + ' &eacute; obrigat&oacute;rio!', 8000);
//                                }
//                            });
//                        } else {
//                            Materialize.toast(result.msg, 4000);
//                        }
                    }
                });
            }
        });
    });
</script>