<style>
    #qm0 > a:first-of-type{
        background-color: #0A420E;
        color: #fff;
    }
    #qm0, #qm0.qmmc{
        padding-bottom: 0px;
    }


    #conteudo .bt_enviar, #conteudo .bt_rascunho, #conteudo .btn {
        color: #ffffff;
     }
    #conteudo a {
        color: #373737;
    }

</style>

<?= $this->partial('consultardadosprojeto/inc/menu.inc.php', 'default', $this); ?>

<div id="conteudo" class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="page-title">
                <div class="row">
                    <div class="col s12 m9 l10">
                        <h1>Enviar nova solicita&ccedil;&atilde;o Proponente</h1>

                        <?php
                        gerarNovoBreadCrumb(array(
                            array('Solicitações' => [
                                'module' => 'solicitacao',
                                'controller' => 'mensagem',
                                'action', 'index']
                            ),
                            array('Visualizar' => '')
                        ));
                        ?>
                    </div>
                    <div class="col s12 m3 l2 right-align">
                        <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                           class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="card-panel">
                    <div class="row">
                        <?php if ($this->arrPartial['dataForm']['idSolicitacao'] && $this->arrPartial['isProponente']) : ?>
                            <div class="msgALERT">
                                <div>Solicitação salva como rascunho!</div>
                            </div>
                        <?php endif; ?>

                        <?php echo $this->partial('/mensagem/partials/form.phtml', $this->arrPartial); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
