<?php
/**
 * Publicação no DOU
 * @author Equipe RUP - Politec
 * @since 11/08/2010
 * @version 1.0
 * @package application
 * @subpackage application.controller.PublicacaoDou
 * @link http://www.cultura.gov.br
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 */
	
?>
	
	<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
	<div id="breadcrumb">
		<ul>
			<li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para Início">Início</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'publicacaodou', 'action' => 'index')); ?>" title="Ir para Página Inicial da Publicação no Diário Oficial da União">Publicação no Diário Oficial da União</a></li>
			<li class="last">Página Inicial para Publicação no DOU</li>
		</ul>
	</div>
	<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
	
	
	
	<!-- ========== INÍCIO TÍTULO ========== -->
	<div id="titulo">
		<div>Página Inicial para Publicação no DOU<span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
	</div>
	<!-- ========== FIM TÍTULO ========== -->
	
	
	
	<!-- ========== INÍCIO CONTEÚDO ========== -->
	<div id="conteudo">
	
	
<table class="tabela">
<tr> <th>PORTARIA</th></tr>
</table>

<p class = "centro">ATO PORTARIA N.º XXXX, de XX (data atual) DE XX (mês atual) de XXXX (ano atual).</p> <br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;O SECRETÁRIO DE FOMENTO E INCENTIVO À CULTURA, no uso das atribuições legais, que lhe confere a Portaria nº 17 de 12 de janeiro  de 2010 e o art. 4º da Portaria nº 120, de 29 de narço de 2010, RESOLVE :
	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art. 1.º - Aprovar projetos culturais, relacionados nos anexos I e II à esta Portaria, para os quais os proponentes ficam autorizados a captar recursos, mediante doações ou patrocínios, na forma prevista, respectivamente, no § 1º do artigo 18 e no artigo 26 da lei n.º 8.313, de 23 de novembro de 1999.
<br>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art. 2.º - Esta portaria entre em vigor na data de sua publicação.
<br></br>
		<p class = "centro">		##ASS (nome do ator selecionado)</p>




</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />