export const SET_PAGAMENTOS_CONSOLIDADOS = 'SET_PAGAMENTOS_CONSOLIDADOS';
export const SET_PAGAMENTOS_UF_MUNICIPIO = 'SET_PAGAMENTOS_UF_MUNICIPIO';
export const SET_RELATORIOS_TRIMESTRAIS = 'SET_RELATORIOS_TRIMESTRAIS';
export const SET_EXECUCAO_RECEITA_DESPESA = 'SET_EXECUCAO_RECEITA_DESPESA';
export const SET_RELATORIO_FISICO = 'SET_RELATORIO_FISICO';
