export const SET_PAGAMENTOS_CONSOLIDADOS = 'SET_PAGAMENTOS_CONSOLIDADOS';
export const SET_PAGAMENTOS_UF_MUNICIPIO = 'SET_PAGAMENTOS_UF_MUNICIPIO';
export const SET_RELATORIOS_TRIMESTRAIS = 'SET_RELATORIOS_TRIMESTRAIS';
