<div id="example" class="plano-distribuicao">
    <?php $totalExemplares = 0;
    $totalReceita = 0; ?>
    <ul class="collapsible collapsible-produto" data-collapsible="accordion" style="margin: 0px; padding: 0px">
        <?php foreach ($this->planosDistribuicao as $planoDistribuicao) : ?>
            <li>
                <div class="collapsible-header"><i class="material-icons">add</i>
                    <?php echo $planoDistribuicao->Produto; ?>
                </div>
                <div class="collapsible-body">
                    <table>
                        <thead>
                           <tr>
                                <th>&Aacute;rea</th>
                                <th>Segmento</th>
                                <th>Principal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?php echo $planoDistribuicao->DescricaoArea; ?></td>
                                <td><?php echo $planoDistribuicao->DescricaoSegmento; ?></td>
                                <td><?php echo ($planoDistribuicao->stPrincipal == 0) ? 'N&atilde;o' : 'Sim'; ?></td>
                            </tr>
                        </tbody>
                    </table>

                    <table class="resumo-distribuicao planoDistribuicao ">
                        <caption><b>Resumo - <?php echo $planoDistribuicao->Produto; ?></b></caption>
                        <thead>
                        <tr>
                            <th class="center-align" rowspan="2">Quantidade</th>
                            <th colspan="3" class="proponente">Proponente</th>
                            <th colspan="3" class="popular">Pre&ccedil;o Popular</th>
                            <th colspan="3" class="gratuito">Distribui&ccedil;&atilde;o Gratuita</th>
                            <th class="right-align" rowspan="2" width="8%">Receita Prevista total</th>
                        </tr>
                        <tr>
                            <th class="proponente">Qtd. Inteira</th>
                            <th class="proponente">Qtd. Meia</th>
                            <th class="proponente">Valor m&eacute;dio</th>
                            <th class="popular">Qtd. Inteira</th>
                            <th class="popular">Qtd. Meia</th>
                            <th class="popular">Valor m&eacute;dio</th>
                            <th class="gratuito">Divulga&ccedil;&atilde;o</th>
                            <th class="gratuito">Patrocinador</th>
                            <th class="gratuito">Popula&ccedil;&atilde;o</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="center-align"><?php echo $planoDistribuicao->QtdeProduzida; ?></td>
                            <td class="proponente"><?php echo $planoDistribuicao->QtdeVendaNormal; ?></td>
                            <td class="proponente"><?php echo $planoDistribuicao->QtdeVendaPromocional; ?></td>
                            <td class="proponente"><?php echo $planoDistribuicao->PrecoUnitarioNormal; ?></td>
                            <td class="popular"><?php echo $planoDistribuicao->QtdeVendaPopularNormal; ?></td>
                            <td class="popular"><?php echo $planoDistribuicao->QtdeVendaPopularPromocional; ?></td>
                            <td class="popular"><?php echo $planoDistribuicao->ReceitaPopularNormal; ?>	</td>
                            <td class="gratuito"><?php echo $planoDistribuicao->QtdeProponente;	?></td>
                            <td class="gratuito"><?php echo $planoDistribuicao->QtdePatrocinador; ?></td>
                            <td class="gratuito"><?php echo $planoDistribuicao->QtdeOutros; ?></td>
                            <td class="right-align"><?php echo $planoDistribuicao->Receita; ?></td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col s12">
                            <ul class="collapsible" data-collapsible="expandable">
                                <?php foreach ($this->abrangencias as $abrangencia): ?>
                                    <li>
                                        <div class="collapsible-header"><i class="material-icons">add</i>
                                            <?= isset($abrangencia['uf']) ? $abrangencia['uf'] : 'Exterior' ?> <?= isset($abrangencia['cidade']) ? ' - ' . $abrangencia['cidade'] : '' ?>
                                        </div>
                                        <div class="collapsible-body">
                                            <visualizar-plano-distribuicao
                                                idplanodistribuicao="<?php echo $planoDistribuicao->idPlanoDistribuicao; ?>"
                                                idpreprojeto="<?php echo $this->idPreProjeto; ?>"
                                                iduf="<?php echo $abrangencia['idUF']; ?>"
                                                idmunicipioibge="<?php echo $abrangencia['idMunicipioIBGE']; ?>"
                                            ></visualizar-plano-distribuicao>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>

                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>


<script>
    $3(document).ready(function(){

        $3('.collapsible').collapsible({
            accordion: true,
            onOpen: function(el) { el.find('.material-icons:first').html('remove'); },
            onClose: function(el) { el.find('.material-icons:first').html('add'); }
        });
    });

</script>
<!-- my_component -->
<script type="text/x-template" id="visualizar-plano-distribuicao">
    <div>
        <div>
            <div class="row">
                <div class="center">
                    <table class="">
                        <thead v-if="produtos.length > 0">
                        <tr>
                            <th rowspan="2">Categoria</th>
                            <th rowspan="2">Quantidade</th>
                            <th class="proponente" colspan="3">
                                Proponente
                            </th>
                            <th class="popular" colspan="3">
                                Pre&ccedil;o Popular
                            </th>
                            <th class="gratuito" rowspan="2">
                                Distribui&ccedil;&atilde;o <br>Gratuita
                            </th>
                            <th rowspan="2" class="center-align">Receita <br> Prevista</th>
                        </tr>
                        <tr>
                            <th class="proponente">Qtd. Inteira</th>
                            <th class="proponente">Qtd. Meia</th>
                            <th class="proponente">Pre&ccedil;o <br> Unitario</th>
                            <th class="popular">Qtd. Inteira</th>
                            <th class="popular">Qtd. Meia</th>
                            <th class="popular">Pre&ccedil;o <br> Unitario</th>
                        </tr>
                        </thead>
                        <tbody v-if="produtos.length > 0">
                            <tr v-for="( produto, index ) in produtos">
                                <td>{{ produto.dsProduto }}</td>
                                <td class="center-align">{{ produto.qtExemplares }}</td>
                                <!--Preço Proponente -->
                                <td class="center-align">{{ produto.qtProponenteIntegral }}</td>
                                <td class="center-align">{{ produto.qtProponenteParcial }}</td>
                                <td class="right-align">{{ formatarValor(produto.vlUnitarioProponenteIntegral) }}</td>
                                <!--Preço Popular -->
                                <td class="center-align">{{ produto.qtPopularIntegral }}</td>
                                <td class="center-align">{{ produto.qtPopularParcial }}</td>
                                <td class="right-align">{{ formatarValor(produto.vlUnitarioPopularIntegral) }}</td>
                                <!-- Distribuicao Gratuita-->
                                <td class="center-align">{{ parseInt(produto.qtGratuitaDivulgacao) +
                                    parseInt(produto.qtGratuitaPatrocinador) + parseInt(produto.qtGratuitaPopulacao) }}
                                </td>
                                <td class="right-align">{{ formatarValor(produto.vlReceitaPrevista) }}</td>

                            </tr>
                        </tbody>
                        <tbody v-else>
                            <tr>
                                <td colspan="12" class="center-align">Sem detalhamento</td>
                            </tr>
                        </tbody>
                        <tfoot v-if="produtos.length > 0" style="opacity: 0.5">
                            <tr>
                                <td><b>Totais</b></td>
                                <td class="center-align"><b>{{ qtExemplaresTotal }}</b></td>
                                <!--Fim: Preço Popular -->
                                <td class="center-align"><b>{{ qtProponenteIntegralTotal }}</b></td>
                                <td class="center-align"><b>{{ qtProponenteParcialTotal }}</b></td>
                                <td class="right-align"> -</td>
                                <!--Preço Popular -->
                                <td class="center-align"><b>{{ qtPopularIntegralTotal }}</b></td>
                                <td class="center-align"><b>{{ qtPopularParcialTotal }}</b></td>
                                <td class="right-align"> -</td>
                                <td class="center-align"><b>{{ parseInt(qtGratuitaDivulgacaoTotal) +
                                        parseInt(qtGratuitaPatrocinadorTotal) + parseInt(qtGratuitaPopulacaoTotal)}}</b>
                                </td>
                                <td class="right-align"><b>{{ receitaPrevistaTotal }}</b></td>

                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</script>

<script>
(function (global, factory) {
    if (typeof define === 'function' && define.amd) {
        define(['../numeral'], factory);
    } else if (typeof module === 'object' && module.exports) {
        factory(require('../numeral'));
    } else {
        factory(global.numeral);
    }
}(this, function (numeral) {
    numeral.register('locale', 'pt-br', {
        delimiters: {
            thousands: '.',
            decimal: ','
        },
        abbreviations: {
            thousand: 'mil',
            million: 'milhões',
            billion: 'b',
            trillion: 't'
        },
        ordinal: function (number) {
            return 'º';
        },
        currency: {
            symbol: 'R$'
        }
    });
}));

// switch between locales
numeral.locale('pt-br');
numeral.defaultFormat('0,0.00');

// register
Vue.component('visualizar-plano-distribuicao', {
    template: '#visualizar-plano-distribuicao',
    data: function() {
        return {
            produto:{ }, // produto sendo manipulado
            produtos:  [], // lista de produtos
            active : false,
            icon : 'add'
        }
    },
    props:['idpreprojeto','idplanodistribuicao', 'idmunicipioibge', 'iduf', 'disabled'],
    computed:{
        // Total de exemplares
        qtExemplaresTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length; i++){
                total += parseInt(this.produtos[i]['qtExemplares']);
            }
            return total;
        },
        // Total de divulgação gratuita.
        qtGratuitaDivulgacaoTotal: function(){
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                total += parseInt(this.produtos[i]['qtGratuitaDivulgacao']);
            }
            return total;
        },
        // Total de divulgação Patrocinador
        qtGratuitaPatrocinadorTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++) {
                total += parseInt(this.produtos[i]['qtGratuitaPatrocinador']);
            }
            return total;
        },
        // Total de divulgação gratuita.
        qtGratuitaPopulacaoTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++) {
                total += parseInt(this.produtos[i]['qtGratuitaPopulacao']);
            }
            return total;
        },
        //Preço Popular: Quantidade de Inteira
        qtPopularIntegralTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                total += parseInt(this.produtos[i]['qtPopularIntegral']);
            }
            return total;
        },
        //Preço Popular: Quantidade de meia entrada
        qtPopularParcialTotal:function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                total += parseInt(this.produtos[i]['qtPopularParcial']);
            }
            return total;
        },
        vlReceitaPopularIntegralTotal :function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                var vl = (this.produtos[i]['vlReceitaPopularIntegral']);
                total += numeral(vl).value();
            }
            return numeral(total).format();
        },
        vlReceitaPopularParcialTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++) {
                var vl = (this.produtos[i]['vlReceitaPopularParcial']);
                total += numeral(vl).value();
            }
            return numeral(total).format();
        },
        qtProponenteIntegralTotal:function(){
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                total += parseInt(this.produtos[i]['qtProponenteIntegral']);
            }
            return total;
        },
        qtProponenteParcialTotal:function(){
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                total += parseInt(this.produtos[i]['qtProponenteParcial']);
            }
            return total;
        },
        vlReceitaProponenteIntegralTotal:function(){
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                vl = (this.produtos[i]['vlReceitaProponenteIntegral']);
                total += this.converterParaMoedaAmericana(vl);
            }
            return numeral(total).format();
        },
        vlReceitaProponenteParcialTotal: function() {
            total = 0 ;
            for ( var i = 0 ; i < this.produtos.length ; i++){
                var vl = (this.produtos[i]['vlReceitaProponenteParcial']);
                total += this.converterParaMoedaAmericana(vl);
            }
            return numeral(total).format();
        },
        receitaPrevistaTotal: function() {
            var total = numeral();

            for ( var i = 0 ; i < this.produtos.length ; i++){
                var vl = this.produtos[i]['vlReceitaPrevista'];
                total.add(parseFloat(vl));
            }
            return total.format();
        }
    },
    watch:{

    },
    mounted: function() {
        this.t();

    },
    methods: {
        t: function(){
            var vue = this;

            this.$data.produtos = [];
            url = "/proposta/visualizar-plano-distribuicao/detalhar/idPreProjeto/"+this.idpreprojeto+"?idPlanoDistribuicao=" + this.idplanodistribuicao + "&idMunicipio=" + this.idmunicipioibge +"&idUF=" + this.iduf;
            $3.ajax({
                type: "GET",
                url:url
            }).done(function(data) {
                    vue.$data.produtos = data.data;
            })
            .fail(function(){ alert('Erro ao buscar detalhamento'); });

        },
        converterParaMoedaAmericana: function(valor) {
            if( !valor )
                valor = '0';

            valor = valor.replace( /\./g, '' );
            valor = valor.replace( /\,/g, '.' );
            valor = parseFloat( valor );
            valor = valor.toFixed( 2 );

            if( isNaN( valor ) )
                valor = 0;

            return valor;
        },
        abrirFecharItem: function(el) {
            $3('.' + el).toggle();

            if ($3('#' + el).hasClass('icn_mais'))
            {
                $3('#' + el).addClass('icn_menos');
                $3('#' + el).removeClass('icn_mais');
            }
            else
            {
                $3('#' + el).addClass('icn_mais');
                $3('#' + el).removeClass('icn_menos');
            }
        },
        mostrar: function() {
            this.active = this.active == true ? false: true ;
            this.icon = this.icon == 'visibility_off' ? 'add': 'visibility_off';
        },
        formatarValor: function (valor) {
            valor = parseFloat(valor);
            return numeral(valor).format();
        }
    }
});

var app6 = new Vue({
    el: '#example'
});
</script>
