<script type="text/javascript">
    $(document).ready(function(){
        $(".btn_pesquisar").click(function(){
            //jqAjaxLink("<?php echo $this->baseUrl()?>/operacional/tabelas?consulta="+$("#consulta").val(), null, "resultadoConsulta");
            $("#resultadoConsulta").html("");
            jqAjaxForm(document.getElementById("frmPedidoProrrogacao"), "resultadoConsulta");
        });

        $("#tpDtPedido").change(function(){
            if($("#spanDtPedido").css("display")=="none" && $(this).val() == "entre"){
                $("#spanDtPedido").show();
            }else{
                $("#spanDtPedido").hide();
            }
            //$("#spanDtFinal").toggle();
        });

        $("#tpDtInicio").change(function(){
            if($("#spanDtInicio").css("display")=="none" && $(this).val() == "entre"){
                $("#spanDtInicio").show();
            }else{
                $("#spanDtInicio").hide();
            }
            //$("#spanDtFinal").toggle();
        });

        $(function()
        {
            $.datepicker.regional['pt-BR'] = {
                closeText: 'Fechar',
                prevText: '&#x3c;Anterior',
                nextText: 'Pr&oacute;ximo&#x3e;',
                currentText: 'Hoje',
                monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sabado'],
                dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
                dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
                weekHeader: 'Sm',
                dateFormat: 'dd/mm/yy',
                firstDay: 0,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''};
            $.datepicker.setDefaults($.datepicker.regional['pt-BR']);
            $(".cmpData").datepicker($.datepicker.regional['pt-BR']);
        });

    });
</script>

<?php include("scripts/operacional/inc/menu.inc.php"); ?>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'operacional', 'action' => '')); ?>">In&iacute;cio</a></li>
        <li class="last">Consultar Pedido de Prorroga&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Consultar Pedido de Prorroga&ccedil;&atilde;o<span class="voltar"><a href="javascript:voltar();">Voltar</a></span></div>
</div>

<div id="conteudo" align="center">

    <fieldset>
        <legend>Filtros de pesquisa</legend>
        <form action="<?php echo $this->url(array('controller' => 'operacional', 'action' => 'resultado-pedido-prorrogacao')); ?>" method="post" name="frmPedidoProrrogacao" id="frmPedidoProrrogacao">
        <table class="tabela" style="width:90%">
            <tbody><tr>
                    <th colspan="3">Selecionar campos para pesquisa</th>
                </tr>
                <tr>
                    <td width="120">Data Pedido</td>
                    <td width="220" align="center">
                        <select name="tpDtPedido" id="tpDtPedido" class="select_simples" onchange="if($(this).val()=='OT' || $(this).val()=='U7' || $(this).val()=='SP' || $(this).val()=='MM' || $(this).val()=='UM'){$('#camposDataDtPedido').css('display','none');}else{$('#camposDataDtPedido').css('display','');}">
                            <OPTGROUP LABEL="Normais">
                                <option value="">Selecione</option>
                                <option value="igual">Exatamente Igual</option>
                                <option value="entre">Entre dois valores</option>
                                <option value="maior">Maior ou igual a </option>
                                <option value="menor">Menor ou igual a</option>
                            </OPTGROUP>
                            <OPTGROUP LABEL="Especiais">
                               <option value="OT">Ontem</option>
                               <option value="U7">&Uacute;ltimos 7 dias</option>
                               <option value="SP">Semana Passada (seg-dom)</option>
                               <option value="MM">Este m&ecirc;s</option>
                               <option value="UM">&Uacute;ltimo m&ecirc;s</option>
                            </OPTGROUP>
                        </select>
                    </td>
                    <td align="left">
                        <span id="camposDataDtPedido">
                            <input name="dtPedido" id="dtPedido" value="" class="input_simples cmpData"/> (dd/mm/aaaa)
                            <span id="spanDtPedido" style="display: none;">&nbsp;e&nbsp;<input name="dtPedido_Final" id="dtPedido_Final" value="" class="input_simples cmpData"/></span>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td width="120">Data Inicio</td>
                    <td width="220" align="center">
                        <select name="tpDtInicio" id="tpDtInicio" class="select_simples" onchange="if($(this).val()=='OT' || $(this).val()=='U7' || $(this).val()=='SP' || $(this).val()=='MM' || $(this).val()=='UM'){$('#camposDataDtInicio').css('display','none');}else{$('#camposDataDtInicio').css('display','');}">
                            <OPTGROUP LABEL="Normais">
                                <option value="">Selecione</option>
                                <option value="igual">Exatamente Igual</option>
                                <option value="entre">Entre dois valores</option>
                                <option value="maior">Maior ou igual a </option>
                                <option value="menor">Menor ou igual a</option>
                            </OPTGROUP>
                            <OPTGROUP LABEL="Especiais">
                               <option value="OT">Ontem</option>
                               <option value="U7">&Uacute;ltimos 7 dias</option>
                               <option value="SP">Semana Passada (seg-dom)</option>
                               <option value="MM">Este m&ecirc;s</option>
                               <option value="UM">&Uacute;ltimo m&ecirc;s</option>
                            </OPTGROUP>
                        </select>
                    </td>
                    <td align="left">
                        <span id="camposDataDtInicio">
                            <input name="dtInicio" id="dtInicio" value="" class="input_simples cmpData"/> (dd/mm/aaaa)
                            <span id="spanDtInicio" style="display: none;">&nbsp;e&nbsp;<input name="dtInicio_Final" id="dtInicio_Final" value="" class="input_simples cmpData"/></span>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td width="120">Baixado</td>
                    <td align="left" colspan="2">
                        <select name="baixado" style="width: 200px;" class="input_simples">
                            <option value="">Selecione</option>
                            <option value="S">Sim</option>
                            <option value="N">N&atilde;o</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Dilig&ecirc;ncias</td>
                    <td align="left" colspan="2">
                        <select name="diligenciado" style="width: 200px;" class="input_simples">
                            <option value="">Selecione</option>
                            <option value="S">Sim</option>
                            <option value="N">N&atilde;o</option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="tabela" style="width: 90%">
            <tr>
                <td align="center">
                    <input type="button" style="width: 88px" class="btn_pesquisar" id="btn_pesquisar" value=""/>
                    <input type="reset" style="width: 88px" class="btn_limpar" id="btn_limpar" value=""/>
                </td>
            </tr>
        </table>
        </form>
    </fieldset>

<div id="resultadoConsulta"></div>
    
</div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />