<?php
$buscarDocumento = $this->url(array('module' => 'admissibilidade', 'controller' => 'admissibilidade', 'action' => 'buscardocumento'));
$edital='';
?>

<?php echo $this->partial("inc/menu.phtml", $this); ?>

<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Anexar Documentos</h1>

                    <?php
                    gerarNovoBreadCrumb(array(
                        $this->layout['listagem'],
                        array('Anexar Documentos' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="content">
            <div id="msgExclusaoArq" class="sumir">Deseja realmente efetuar a exclus&atilde;o?</div>
            <div class="card-panel">
                <?php if( $this->isEditavel) : ?>
                    <form method="post" action="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaedital', 'action' => 'incluir-anexo')) ?>" id="formulario"  enctype="multipart/form-data">
                        <input type="hidden" name="idPreProjeto" value="<?php echo $this->idPreProjeto; ?>" >
                        <input type="hidden" name="edital" value="<?php echo $edital ?>" />
                         <fieldset>
                            <legend>Novo Arquivo</legend>
                            <div class="row">
                            <div class="input-field col s12">
                                <label class="active">Arquivo <span class="red-text">*</span></label>
                                <input type="file" name="arquivo" id="arquivo" class="input_simples">
                                <span style="color:#f00" id="arquivoinvalido"></span>
                            </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <label class="active">Tipo do documento<span class="red-text">*</span></label>
                                    <p>
                                        <input type="radio"  name="tipoDocumento" class="tipoDocumento" id="tipoDocumento1" value="1" />
                                        <label for="tipoDocumento1">Proponente</label>
                                        <input type="radio"  name="tipoDocumento" class="tipoDocumento" id="tipoDocumento2" value="2" />
                                        <label for="tipoDocumento2"><?= isset($this->layout['titleShort']) ? $this->layout['titleShort']: 'Proposta'; ?></label>
                                        <span style="color:#f00" id="tipodocumentoinvalido"></span>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <label for="documento" class="active">Documento <span class="red-text">*</span></label>
                                    <select id="documento" name="documento" class="browser-default">
                                        <option value=""> - Selecione um Tipo de Documento - &nbsp;</option>
                                    </select>
                                    <span style="color:#f00" id="documentoinvalido"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <textarea name="observacao" class="materialize-textarea" cols="60" rows="5"></textarea>
                                    <label class="active">Observa&ccedil;&atilde;o</label>
                                </div>
                            </div>
                        </fieldset>
                        <div class="row">
                            <div class="col s12 center">
                                <button class="btn" id="enviar" type="button" onclick="enviaform()" value="">Enviar</button>
                            </div>
                        </div>
                    </form>
                <?php endif; ?>
                <?php if(count($this->arquivosProposta)>0){ ?>
                <table class="bordered">
                    <tr>
                        <th colspan="4">Documentos <?= isset($this->layout['titleShort']) ? $this->layout['titleShort']: 'Proposta'; ?></th>
                    </tr>
                    <tr class="destacar">
                        <td align="center"><b>Documento</b></td>
                        <td align="center"><b>Data envio</b></td>
                        <td align="center"><b>Arquivo</b></td>
                        <?php if($this->isEditavel) : ?>
                        <td align="center" width="150"><b>A&ccedil;&atilde;o</b></td>
                        <?php endif; ?>
                    </tr>
                    <?php foreach ($this->arquivosProposta as $arquivosProposta) { ?>
                    <tr>
                        <td><?php echo $arquivosProposta['descricao']; ?></td>
                        <td align="center"><?php echo Data::tratarDataZend($arquivosProposta['data'], 'Brasileira'); ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'upload', 'action' => 'abrir-documentos-pre-projeto')); ?>?id=<?php echo $arquivosProposta['iddocumentospreprojetos']; ?>">
                                <?php echo $arquivosProposta['noarquivo']; ?>
                            </a>
                        </td>
                        <?php if ($this->isEditavel) : ?>
                            <td align="center">
                                <a
                                    class="btn small waves-effect waves-light tooltipped red btn-excluir-item"
                                    href="javascript:void(0);"
                                    onclick="excluirAnexos(<?php echo $arquivosProposta['iddocumentospreprojetos']; ?>, <?php echo trim($this->idPreProjeto); ?>, 'proposta');"
                                    data-tooltip="Excluir arquivo">
                                    <i class="material-icons">delete</i>
                                </a>
                            </td>
                        <?php endif; ?>
                    <?php } ?>
                </table>
                <?php } ?>
                <?php if(count($this->arquivosProponente)>0){ ?>
                <br clear="all" />
                <table class="bordered">
                    <tr>
                        <th colspan="4">Documentos do Proponente</th>
                    </tr>
                    <tr class="destacar">
                        <td align="center"><b>Documento</b></td>
                        <td align="center"><b>Data envio</b></td>
                        <td align="center"><b>Arquivo</b></td>
                        <?php if( $this->isEditavel) : ?>
                            <td align="center" width="150"><b>A&ccedil;&atilde;o</b></td>
                        <?php endif; ?>
                    </tr>
                    <?php foreach ($this->arquivosProponente as $arquivosProponente) { ?>
                    <tr>
                        <td><?php echo $arquivosProponente['Descricao']; ?></td>
                        <td align="center"><?php echo Data::tratarDataZend($arquivosProponente['Data'], 'Brasileira'); ?></td>
                        <td><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'upload', 'action' => 'abrir-documentos-agentes')); ?>?id=<?php echo $arquivosProponente['idDocumentosAgentes']; ?>"><?php echo $arquivosProponente['NoArquivo']; ?></a></td>

                            <td align="center">
                                <?php if ($this->isEditavel) : ?>
                                    <a
                                        class="btn small waves-effect waves-light tooltipped red btn-excluir-item"
                                        href="javascript:void(0);"
                                        onclick="excluirAnexos(<?php echo $arquivosProponente['idDocumentosAgentes']; ?>, <?php echo trim($this->idPreProjeto); ?>, 'proponente');"
                                        data-tooltip="Excluir arquivo">
                                        <i class="material-icons">delete</i>
                                    </a>
                                <?php endif; ?>
                            </td>


                    <?php } ?>
                </table>
                <?php } ?>
            </div>
            <div id="rodapeConteudo"><span></span></div>
            <br clear="all" />
        </div>
    </div>
</div>

<script>
    $(document).ready( function() {

        <?php if (!$this->isEditavel) : ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>

        $('#Opcao').change( function(){
            jqAjaxLinkSemLoading('<?php echo $this->url(array('module'=>'proposta', 'controller' => 'manterpropostaedital', 'action' => 'listararquivos'))."?classificao="; ?>'+$(this).val(), '', "tipodocumento");
        });

        $('#arquivo').change( function(){
            arquivo = $('#arquivo').val();
            arquivo = arquivo.substr((arquivo.length-3), 3)
            if (arquivo == "PDF" || arquivo == "pdf"){
                $('#arquivoinvalido').html('');
                //$('#enviar').attr('class','btn_enviar');
            }else{
                $('#arquivoinvalido').html('<br />Somente documentos em formato PDF podem ser subidos!');
                $('#enviar').attr('class','btn_enviar-off');
            }
        });

        $('.tipoDocumento').click(function(){
            //alert("<?php //echo $buscarDocumento; ?>?idOpcao='+$(this).val()");
            jqAjaxLinkSemLoading('<?php echo $buscarDocumento; ?>?idOpcao='+$(this).val(), "", "documento");
        });

    });

    function enviaform(){
        arquivo = $('#arquivo').val();
        var erro = true;
        var erroarquivo = true;
        arquivo = arquivo.substr((arquivo.length-3), 3);

        if (arquivo == "PDF" || arquivo == "pdf"){
            erroarquivo = false;
        }else{
            $('#arquivoinvalido').html('<br>Somente documentos em formato PDF podem ser subidos!');
            erroarquivo = true;
        }

        if ( document.getElementById('tipoDocumento1').checked == false && document.getElementById('tipoDocumento2').checked == false ) {
            $('#tipodocumentoinvalido').html('<br />Selecione um tipo de documento!');
            erro = true;
        } else {
            $('#tipodocumentoinvalido').html('');
            erro = false;
        }

        if ( $("#documento").val() == "" || $("#documento").val() == "" ) {
            $('#documentoinvalido').html('<br />Selecione um documento!');
            erro = true;
        } else {
            $('#documentoinvalido').html('');
            erro = false;
        }

        if (!erro && !erroarquivo) {
            $('#formulario').submit();
        }
    }

    <?php if ($this->isEditavel) : ?>
        // funcao para excluir os anexos
        function excluirAnexos(idArquivo, idPreProjeto, tipoDocumento)
        {
            url = '<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterpropostaedital', 'action' => 'excluiranexo')) ?>?idArquivo=' + idArquivo + '&idPreProjeto=' + idPreProjeto + '&tipoDocumento=' + tipoDocumento;
            confirmModal('CONFIRMA&Ccedil;&Atilde;O', 'msgExclusaoArq', 320, 200, null, url);
        }
    <?php endif; ?>
</script>

