<?php
include_once 'scripts/manterpropostaedital/inc/menu.inc.php';
?>

<!-- ==========  BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>" title="Projetos">Projetos</a></li>
        <li class="last">Local e Per&iacute;odo de Realiza&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INULO ========== -->
<div id="titulo">
    <div>Msn Enviadas pelo MINC <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TITULO ========== -->



<!-- ========== IDO ========== -->
<div id="conteudo">
    <br>

    <table class="tabela" style="margin-bottom: 130px;">

        <tr class="titulo_tabela" >
            <th colspan="5">Mensagens enviadas pelo MinC</th>

        </tr>

        <tr class="fundo">
            <td class="centro" colspan="5">
            <?php echo "
            Não há Mensagem Enviadas pelo MINC" ?>
            </td>

        </tr>

    </table>



</div><!-- ========== FIM CONTEUDO ========== -->
<br clear="all" />
<!-- ========== I ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RO ========== -->
<br clear="all" />
