<?php
$hrefAnalisedeconteudo = $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'analisedeconteudo'));
$hrefAlterarintemsolicitado = $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'alterarintemsolicitado'));

/* INICIO DA GUIA DE LINKS */
$controller = 'analisarprojetoparecer';
$links = array();
$links[] = array('Projetos/Produtos para Análise' => array('controller' => 'analisarprojetoparecer', 'action' => 'index'));
$links[] = array('Análise do Produto' => array());

/* FIM DA GUIA DE LINKS */
?>

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.css" />

<?php /*if($this->grupoAtivo == 94): ?>
    <?php //require_once "inc/menu.inc.php"; // menu lateral ?>
<?php endif;*/ ?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
        <li class="second">Análise Técnica Inicial</li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'index'), '', true); ?>" title="Ir para Página Inicial">Projetos/Produtos para Análise</a></li>
        <li class="last">Análise do Produtos</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Análise do Produto <span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<div id="dialog-valor" class="sumir" title="Valor Inv&aacute;lido">
    <div class="msgERROR">
        <div>Valor de remanejamento maior que o permitido! M&aacute;ximo : <span id="valorpossivelApresentacao"></span></div>
    </div>
</div>

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <table class="tabela" >
        <tr>
            <th>
                Análise de Conteúdo do Projeto Nr: <?php echo $this->projeto->PRONAC; ?> - <?php echo $this->projeto->NomeProjeto; ?>
                <br/>Produto <?php
                if ($this->projeto->stPrincipal) {
                    echo 'Principal';
                } else {
                    echo 'Secundario';
                }
                ?>: <?php echo $this->projeto->dsProduto; ?>
            </th>
        </tr>
    </table>
    <!-- FIM ANALISE DE CONTEÚDO  -->
    <table class="tabela">
        <tr>
            <td><input type="button" id="abaAnaliseConteudo" class="btn_adicionar" />Análise de conteúdo</td>
        </tr>
    </table>
    <!-- Formulario -->
    <div id="divAnaliseConteudo" style="display:none;">
        <form name="formAnaliseConteudo" id="formAnaliseConteudo" action="<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'analisedeconteudo')); ?>" method="post">
            <input type="hidden" id="stAcao" name="stAcao" value="0"/>
            <input type="hidden" name="idPRONAC" value="<?php echo $this->projeto->IdPRONAC; ?>"/>
            <input type="hidden" name="idProduto" value="<?php echo $this->projeto->idProduto; ?>"/>
            <input type="hidden" id="stPrincipal" name="stPrincipal" value="<?php echo $this->projeto->stPrincipal; ?>"/>
            <input type="hidden" id="idD" name="idD" value="<?php echo $this->idD; ?>"/>

            <table class="tabela" style="width: 95%;">
                <tr>
                    <th colspan="5" class="center">Enquadramento</th>
                </tr>
                <tr>
                    <td colspan="5">&nbsp;</td>
                </tr>
                <tr>
                    <td rowspan="2" id="Lei8313" colspan="2">
                        <b>Lei 8.313/91 alterada pela Lei 9.874/1999 * </b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" name="Lei8313" onclick="APPescolherLei_8313();"/>Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" name="Lei8313" onclick="APPescolherLei_8313();" />N&atilde;o
                        </p>
                    </td>
                    <td id="Artigo3"><b>Artigo 3&deg;</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" name="Artigo3" onclick="APPescolherArtigo3();" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" name="Artigo3" onclick="APPescolherArtigo3();" />N&atilde;o
                        </p>
                    </td>
                    <td><b>Inciso</b>
                        <p>
                            <select class="campo select_simples" id="IncisoArtigo3" name="IncisoArtigo3">
                                <option value="0" >Selecione</option>
                                <option value="1">I</option>
                                <option value="2" >II</option>
                                <option value="3" >III</option>
                                <option value="4" >IV</option>
                                <option value="5" >V</option>
                            </select>
                        </p>
                    </td>
                    <td id="AlineaArtigo3">
                        <b>Alinea Artigo 3</b>
                        <p style="margin-top: 10px;">
                            <input type="text" class="input_simples" name="AlineaArtigo3" id="AlineaArtigo3" />
                        </p>
                    </td>
                </tr>
                <tr>
                    <td id="Artigo18">
                        <b>Artigo 18&deg;</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" name="Artigo18" onclick="APPescolherArt_18();" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" name="Artigo18" onclick="APPescolherArt_18();" />N&atilde;o
                        </p>
                    </td>
                    <td id="AlineaArtigo18">
                        <b>Alínea Artigo 18</b>
                        <p style="margin-top: 10px;">
                            <input type="text" class="input_simples" name="AlineaArtigo18" />
                            <input type="hidden" name="AlineaArt18" id="AlineaArt18" />
                        </p>
                    </td>
                    <td id="Artigo26">
                        <b>Artigo 26&deg;</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" name="Artigo26" onclick="APPescolherArt_26();" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" name="Artigo26" onclick="APPescolherArt_26();" />N&atilde;o
                        </p>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <b>Decreto 5761/2006 *</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" name="Lei5761" onclick="APPescolherDecreto5761();" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" name="Lei5761" onclick="APPescolherDecreto5761();" />N&atilde;o
                        </p>
                    </td>
                    <td id="Artigo27">
                        <b>Artigo 27&deg;</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;"  value="1" name="Artigo27" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;"  value="0" name="Artigo27" />N&atilde;o
                        </p>
                    </td>
                    <td id="IncisoArtigo27">
                        <b>Inciso(s)</b>
                        <p style="margin-top: 10px;">
                            <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_I" />I &nbsp;&nbsp;&nbsp;
                            <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_II" />II &nbsp;&nbsp;&nbsp;
                            <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_III" />III &nbsp;&nbsp;&nbsp;
                            <input type="checkbox" style="margin-right: 3px;" value="1" name="IncisoArtigo27_IV" />IV
                        </p>
                    </td>
                </tr>
                <tr>
                    <td colspan="5">
                        <b>Enquadramento Favorável? *</b>
                        <p style="margin-top: 10px;">
                            <input type="radio" style="margin-right: 5px;" value="1" class="ParecerFavoravel" name="ParecerFavoravel" checked="checked" />Sim &nbsp;&nbsp;
                            <input type="radio" style="margin-right: 5px;" value="0" class="ParecerFavoravel" name="ParecerFavoravel" />N&atilde;o
                        </p>
                    </td>
                </tr>
                <tr>
                    <td colspan="5">
                        <b>Justificativa do enquadramento*</b>
                        <p>
                        <center>
                            <textarea class="textarea_simples" id="ParecerDeConteudo" name="ParecerDeConteudo" rows="10" style="width: 98%;"></textarea>
                        </center>
                    </td>
                    <?php if($this->grupoAtivo == 93):?>
                </tr>
                <?php else: ?>
                <tr id="btSalvar">
                    <td colspan="6" align="center">
                        <input type="button" id="btSalvarAnaliseDeConteudo" value=" " class="btn_salvar"/>
                    </td>
                </tr>
                <?php endif; ?>
            </table>
        </form>
    </div>

    <table class="tabela">
        <tr>
            <td><input type="button" id="abaAnaliseCusto" class="btn_adicionar" />Análise de custos</td>
        </tr>
    </table>
    <div id="divAnaliseCusto" style="display:none;">
        <table class="tabela" style="width: 95%;" width="95%">
            <tr>
                <th colspan="13">Planilha de Or&ccedil;amento Sugerido <input id="valorpossivel" value="<?php echo $this->valorpossivel;?>" type="hidden"/></th>
            </tr>
            <?php
            $nrfonte = 0;
            $item = 1;
            //ForeachFonteIncentivo
            foreach ($this->itens['fonte'] as $fonte => $arrayProdutos) {
                ?>
            <tr>
                <td colspan="11">
                    <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
                </td>
            </tr>
    <?php
                $nrproduto = 0;
                foreach ($arrayProdutos as $produto => $arrayEtapas) {
                    ?>
            <tr class='master' fonte="<?php echo $nrfonte; ?>">
                <td class='master' colspan="11">
                    <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                </td>
            </tr>
        <?php
        $nretapa = 0;
                    foreach ($arrayEtapas as $etapa => $arrayCidades) {
                        ?>
            <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                <td colspan="11">
                    <div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div>
                </td>
            </tr>
            <?php
            $nrcidade = 0;
            foreach ($arrayCidades as $cidade => $planilha) {
                            ?>
            <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                <td colspan="11">
                    <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;">
                        <span class="black del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span>
                    </div>
                </td>
            </tr>
            <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" cidade="<?php echo $nrcidade; ?>">
                <td colspan="11">
                    <table class="tabela">
                <?php
                /* INICIO PLANILHA DE ITENS */
                $primeiro = 0;
                foreach ($planilha['itens'] as $idPlanilhaProjeto => $valPlanilha) {
                                            $valorprodutosolicitado = 0;
                                            $valorprodutoparecerista = 0;
                                            $trCampo = "<tr>";
                                            $conteudo = "<tr class='item' idPlanilhaProjeto='{$idPlanilhaProjeto}' id='item{$idPlanilhaProjeto}'>";

                                            foreach ($valPlanilha as $camp => $cont) {
                                                $trCampo .= "<th>{$camp}</th>";
                                                if ($camp == 'Valor Unitário' || $camp == 'Valor Solicitado' || $camp == 'Valor Sugerido pelo Parecerista') {
                                                    if ($camp == 'Valor Sugerido pelo Parecerista') {
                                                        $conteudo .= "<td class='ValorSugerido' style='width:10;'>{$this->formatarReal($cont)}</td>";
                                                    }
                                                    else {
                                                        $conteudo .= "<td style='width:12%;'>{$this->formatarReal($cont)}</td>";
                                                    }
                                                }
                                                else {
                                                    if ($camp == 'Justificativas do Parecerista') {
                                                        $conteudo .= "<td class='JustParecerista'>{$cont}</td>";
                                                    }
                                                    else {
                                                        $conteudo .= "<td>{$cont}</td>";
                                                    }
                                                }
                                            }
                                            $trCampo .= "</tr>";
                                            $conteudo .= "</tr>";

                                            if ($primeiro == 0) {
                                                echo $trCampo;
                                            }

                                            echo $conteudo;
                                            $primeiro++;
                                        }
                                        ?>
                        <tr style="font-weight: bold;">
                            <td class="esquerda black" style="font-size: 12pt; width: 12%;" colspan="7">Total de UF</td>
                            <td class="esquerda black" style="font-size: 12pt; width: 15%;"><?php echo $planilha['totalUfSolicitado']; ?></td>
                            <td class="esquerda black" style="font-size: 12pt; width: 12%;">&nbsp;</td>
                            <td class="valorUfSugerido esquerda black" style="font-size: 12pt; width: 15%;"><?php echo $planilha['totalUfSugerido']; ?></td>
                            <td class="esquerda black" style="font-size: 12pt; width: 12%;">&nbsp;</td>
                        </tr>
                    </table>
                </td>
            </tr>
                                        <?php
                                        /* FIM PLANILHA DE ITENS */
                                    }
            $nretapa++;
        } //fechaForeachetapa
        $nrproduto++;
    } //fechaForeachproduto
    $nrfonte++;
}//fechaForeachFonteIncentivo
?>
            <tr>
                <td colspan="11">
                    <table class="tabela">
                        <tr>
                            <th colspan="5">Total Solicitado do produto - Todas as fontes de incentivo</th>
                            <th colspan="6">Total Sugerido do produto - Todas as fontes de incentivo</th>
                        </tr>
                        <tr>
                            <td class="centro black" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="5"><?php echo $this->itens['totalSolicitado']; ?></td>
                            <td class="centro valorTotalSugerido esquerda black" style="font-size: 12pt; width: 12%; font-weight: bold;" colspan="6"><?php echo $this->itens['totalSugerido']; ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

    </div>

    <?php if(($this->stPrincipal == 1) && ($this->grupoAtivo == 94)){ ?>
    <table class="tabela">
        <tr>
            <td><input type="button" id="abaProdutosSecundarios" class="btn_adicionar" onclick="abrirfechar('produtosSecundarios');"/>Dados dos Produtos Secundários</td>
        </tr>
    </table>
    <table class="tabela sumir" id="produtosSecundarios" style="width:95%" width="95%">
        <?php if (count($this->produtosSecundarios)){ ?>
        <tr>
            <th align="left">PRODUTO</th>
        </tr>
        <?php if (!empty($this->produtosSecundarios) ) {?>
            <?php foreach($this->produtosSecundarios as $ps){ ?>
            <tr>
                <td align="left">
                    <a target="_blanck" href="<?php echo $this->url(array('controller'=> 'analisarprojetoparecer','action' =>'produtosecundario'));?>?idPronac=<?php echo $ps['IdPRONAC']; ?>&idProduto=<?php echo $ps['idProduto']; ?>&stPrincipal=<?php echo $ps['stPrincipal'];?>">
                        <?php echo $ps['Produto'] ;?>
                    </a>
                </td>
            </tr>
            <?php } ?>
        <?php } ?>

        <?php } else { ?>
            <tr>
                <td align="center" style="color: red; font-size: 16px;">Não há produto secundário.</td>
            </tr>
        <?php } ?>
    </table>
    <?php } ?>

    <?php if(($this->stPrincipal == 1) && ($this->produtosSecundariosEmAnalise == 0)){ ?>
    <table class="tabela">
        <tr>
            <td><input type="button" id="abaConsolidacao" class="btn_adicionar" onclick="abrirfechar('consolidacao');" />Consolidação do Parecer Técnico</td>
        </tr>
    </table>

    <form id="formConsolidacao" action="<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'consolidacaoprojeto')); ?>" method="post">

        <input type="hidden" name="idPronacP" 	 value="<?php echo $_GET['idPronac']; ?>" />
        <input type="hidden" name="AnoProjeto" 	 value="<?php echo $this->projeto->AnoProjeto; ?>" />
        <input type="hidden" name="Sequencial" 	 value="<?php echo $this->projeto->Sequencial; ?>" />
        <input type="hidden" name="sugeridoReal" value="<?php echo $this->itens['totalSugerido']; ?>" />
        <input type="hidden" name="stPrincipal"  value="<?php echo $_GET['stPrincipal']; ?>" />
        <input type="hidden" name="idProduto" 	 value="<?php echo $_GET['idProduto']; ?>" />

        <table class="tabela sumir" id="consolidacao" style="width:95%" width="95%">
        <?php if($this->Perfil == 94) { //Parecerista ?>
            <tr>
                <th colspan="3">Consolidação do Parecer Técnico</th>
            </tr>
            <tr>
                <td align="left" class="destacar bold" width="180">Parecer Favorável?</td>
                <td colspan="2">
                    <input class="obrigatorioRadio" <?php if(count($this->consolidacao) > 0){ echo ($this->consolidacao[0]->ParecerFavoravel == 2) ? 'checked="checked"' : ''; } ?> type="radio" name="parecerProjeto" id="parecerProjeto1" value="2" /> <label for="parecerProjeto2" style="margin-right:25px;">Sim</label>
                    <input class="obrigatorioRadio" <?php if(count($this->consolidacao) > 0){ echo ($this->consolidacao[0]->ParecerFavoravel == 1) ? 'checked="checked"' : ''; } ?> type="radio" name="parecerProjeto" id="parecerProjeto1" value="1" /> <label for="parecerProjeto1">Não</label>
                </td>
            </tr>
            <tr>
                <td align="left" class="destacar bold">Área / Segmento do Projeto</td>
                <td valign="top" width="300px">
                    <label for="areaCultural">Área Cultural</label>
                    <select name="areaCultural" id="areaCultural" class="input_simples obrigatorio" style="width: 160px;">

                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->comboareasculturais as $comboareacultural){ ?>
                        <option value="<?php echo $comboareacultural->id; ?>" <?php if ($this->projeto->Area == $comboareacultural->id) echo "selected=\"selected\""; ?>><?php echo $comboareacultural->descricao; ?></option>
                        <?php } ?>

                    </select>
                    &nbsp; <span id="erroAreaCultural" class="spanError"></span>

                </td>
                <td>
                    <label for="segmentoCultural">Segmento Cultural</label>
                    <select name="segmentoCultural" id="segmentoCultural" class="input_simples obrigatorio">

                        <?php if (!isset($this->projeto->Area) || empty($this->projeto->Area)) { ?>
                            <option value=""> - Selecione uma Área Cultural - </option>
                        <?php } else { ?>

                            <?php if (!isset($this->projeto->Segmento) || empty($this->projeto->Segmento)) { ?>
                            <option value=""> - Selecione - </option>
                            <?php } ?>

                            <?php foreach ($this->combosegmentosculturais as $combosegmentocultural){ ?>
                            <option value="<?php echo $combosegmentocultural->id; ?>" <?php if ($this->projeto->Segmento == $combosegmentocultural->id) echo "selected=\"selected\""; ?>>
                            <?php echo $combosegmentocultural->descricao; ?>
                            </option>
                            <?php } ?>

                        <?php } ?>

                    </select>
                    &nbsp; <span id="erroSegmentoCultural" class="spanError"></span>
                </td>
            </tr>
            <tr>
                <td align="left" class="destacar bold">Enquadramento</td>
                <td width="250" colspan="2">
                    <input type="hidden" name="enquadramentoProjeto" id="enquadramentoProjeto" value="" class="obrigatorio" />
                    <span id="enquadramentoText" class="bold"></span>
                </td>
            </tr>
            <tr>
                <td align="left" class="destacar bold">Sugerido</td>
                <td align="left" colspan="2"><?php echo $this->itens['totalSugerido']; ?></td>
            </tr>
            <tr>
                <td colspan="3">
                    <textarea cols="80" id="dsConsolidacao" name="dsConsolidacao" rows="10" class="textarea_simples" style="width: 99%"><?php echo isset($this->consolidacao[0]->ResumoParecer) ? $this->consolidacao[0]->ResumoParecer : ''; ?></textarea>
                </td>
            </tr>
            <td colspan="3" align="center">
                <input type="button" id="btSalvarConsolidacao" value=" " class="btn_salvar"/>
            </td>

        <?php } else { ?>

            <tr>
                <th colspan="2">Parecer</th>
            </tr>
            <tr>
                <td colspan="2"><?php echo isset($this->consolidacao[0]->ResumoParecer) ? $this->consolidacao[0]->ResumoParecer : ''; ?></td>
            </tr>
            <tr>
                <th width="250" align="left">Sugerido</th>
                <td><?php echo isset($this->consolidacao[0]->SugeridoReal) ? $this->formatarReal($this->consolidacao[0]->SugeridoReal) : ''; ?></td>
            </tr>
            <tr>
                <th align="left">Enquadramentos</th>
                <td><?php echo $this->enquadramento['Enquadramento'] == '1' ? 'Artigo 26' : 'Artigo 18'; ?></td>
            </tr>
            <tr>
                <th align="left">Área / Segmento do Projeto</th>
                <td><?php echo $this->dsArea.' - '.$this->dsSegmento; ?></td>
            </tr>
            <tr align="left">
                <th>Parecer favorável</th>
                <td><?php echo isset($this->consolidacao[0]->ParecerFavoravel) ? $this->consolidacao[0]->ParecerFavoravel == '2' ? 'SIM' : 'NÃO' : ''; ?></td>
            </tr>
        <?php } ?>
        </table>
    </form>
    <?php } ?>

    <!-- MODAL -->
    <div id="alteraritemsolicitado" link="<?php echo $hrefAlterarintemsolicitado; ?>" style="display: none;"></div>
    <div id="confirmacao" style="display: none;"></div>
    <!-- FIM MODAL -->
</div>
<!-- ========== FIM CONTEÚDO ========== -->

<div id="confirma" class="sumir"></div>
<div id="camposObrigatorios" class="sumir"></div>

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<input type="hidden" name="grupoAtivo" id="grupoAtivo" value="<?php echo $this->grupoAtivo; ?>" />
<br clear="all" />

<script type="text/javascript">

    function carregarSegmento(){
        $('#segmentoCultural').html('<option value=""> - Carregando - </option>');
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url(array('controller' => 'segmento', 'action' => 'combo')); ?>',
            data: {
                id: $('#areaCultural').val()
            },
            success: function(dados) {
                $('#segmentoCultural').find('option').remove();
                $('#segmentoCultural').append(dados);
            }
        });
    }

    function carregarEnquadramento(){
        var listaCodSegmento = [ '11','12','13','14','15','17','23','26','2A','2B','2E','2F','2G','2H','2I','2J','2K','2L','32','33','36','4B','4D','5A','5D','5E','5F','5G','5H','5I','5J','5K','5L','5M','5N','5O','5P','62','65','68','6C','6D','6E','6G','6H' ];
        if(in_array($('#segmentoCultural').val(), listaCodSegmento)){
            $('#enquadramentoProjeto').val('2');
            $('#enquadramentoText').html('Artigo 18');
        } else {
            $('#enquadramentoProjeto').val('1');
            $('#enquadramentoText').html('Artigo 26');
        }
    }
    function carregarTextAreaCKEditor(){
        CKEDITOR.replace( 'ParecerDeConteudo', { toolbar: [] } );
        <?php if(($this->stPrincipal == 1) && ($this->produtosSecundariosEmAnalise == 0)){ ?>
        CKEDITOR.replace( 'dsConsolidacao', { toolbar: [] } );
        <?php } ?>
    }

    $(document).ready(function(){
        
        carregarAnaliseDeConteudo();
        $('#btSalvarAnaliseDeConteudo').click(function(){
            var parecer = CKEDITOR.instances['ParecerDeConteudo'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,'');
//            var parecer = $('#ParecerDeConteudo').val();
            if( parecer.length  < 11){
                alertar('O parecer técnico deve ter no mínimo 11 caracter!');
            } else {
                $('#formAnaliseConteudo').submit();
            }
            return false;
        });

        window.setTimeout('carregarTextAreaCKEditor()', 1000);
        
        $('#areaCultural').change(function() {
            carregarSegmento();
        });

        $('#segmentoCultural').change(function() {
            carregarEnquadramento();
        });

        $('#btSalvarConsolidacao').click(function() {
            var i = 0;
            $('.obrigatorio').each(function(){
                if($.trim($(this).val()) == ''){
                    i++;
                }
            });

            var boolValid = false;
            $('.obrigatorioRadio').each(function() {
                if ($(this).is(':checked') ) {
                    boolValid = true;
                }
            });

            var texto = CKEDITOR.instances['dsConsolidacao'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,'');
//            var texto = $('#dsConsolidacao').val();
            if (texto == '' || texto == 'Digiteseutextoaqui...'){
                i++;
            }

            if(i > 0 || !boolValid) {
                $("#camposObrigatorios").dialog("destroy");
                $("#camposObrigatorios").html("Favor preencher os dados obrig&aacute;torios!");
                $("#camposObrigatorios").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:160,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();

            } else {
                $('#formConsolidacao').submit();
            }
        });

        $("#valorpossivelApresentacao").html('<?php echo $this->formatarReal($this->valorpossivel);?>');
        var grupoAtivo = $("#grupoAtivo").val();
        if(grupoAtivo == "93"){
            desabilitaFormConteudo(true);
            $("#divAnaliseCusto a").click(function() { return false; });
        }

        var cont = 0;
        $('.class_relatorio').each(function(){
            var contAux = cont;
            $('#abrir_fechar'+contAux).click(function(){
                $('#div_relatorio'+contAux).toggle('slow');
            });
            cont++;
        });


        $('.linkrelatorio').click(function(){
            var este = this;
            var cont = $(este).attr('cont');
            $('#div_relatorio'+cont).html('<table class="tabelaRelatorio" cellspacing="1" style="margin: 0;margin-left: 52px; width: 90%;  padding: 0px;"><tr><td align="center"><img src="../public/img/ajax.gif"/>&nbsp;Carregando...</td><tr></table>');
            $('#div_relatorio'+cont).css('display','');
            $.post($(este).attr('link'),{nrRelatorio: cont,idPRONAC:<?php echo $this->projeto->IdPRONAC; ?>},function(data){
                $('#div_relatorio'+$(este).attr('cont')).html(data);
            });
        });
        $(".icn_menos").click(function(){
            var tipo = $(this).attr('tipo');
            var aberto = $(this).attr('aberto');
            if(aberto == 'true'){
                adisplay = 'none';
                $(this).attr('aberto','false');
                $(this).removeClass('icn_menos').addClass('icn_mais');
            }
            else{
                adisplay = '';
                $(this).attr('aberto','true');
                $(this).removeClass('icn_mais').addClass('icn_menos');
            }
            if(tipo == 'fonte'){
                fonte = $(this).attr('fonte');
                $(".master[fonte='"+fonte+"']").css('display', adisplay);
                $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
            }
            if(tipo == 'produto'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'etapa'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
            if(tipo == 'cidade'){
                fonte = $(this).attr('fonte');
                produto = $(this).attr('produto');
                etapa = $(this).attr('etapa');
                cidade = $(this).attr('cidade');
                $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
            }
        });
        $(".item").mouseover(function(){
            $(this).addClass('fundo_linha3');
        });
        $(".item").mouseout(function(){
            $(this).removeClass('fundo_linha3');
        });
        $(".item").click(function(){
            if($(this).hasClass('fundo_linha4')){
                $(this).removeClass('fundo_linha4');
            }
            else{
                $(this).addClass('fundo_linha4');
            }
        });

        APPescolherLei_8313();

        carregarEnquadramento();
    }); //fecha document.ready

    function abrirfechar(elemento){
        $('#'+elemento).toggle();
    }

    function desabilitaFormConteudo(habilitar){
        $('#formAnaliseConteudo').find('input, select, textarea').each(function(key, object){
            if(habilitar){
                $(object).attr('disabled','true');
            }else{
                $(object).removeAttr('disabled');
            }
        });
    }
    function janelaAnaliseConteudoConfirm(stPrincipal,mensagem1,mensagem2){
        var nomeJanelaAlerta =   janelaObj({
            parametros : {
                width:      400,
                autoOpen:   false,
                resizable:  false,
                modal:      true,
                buttons: {
                    'N\u00e3o': function() {
                        $(this).dialog('close');
                    },
                    Sim: function() {
                        $('#formAnaliseConteudo').submit();
                        $(this).dialog('close');
                    }
                }
            },
            removerBtFechar:true,
            title : 'Alerta'
        });
        if(stPrincipal == 1){
            nomeJanelaAlerta.divConteudo.html(mensagem1);
        }else{
            nomeJanelaAlerta.divConteudo.html(mensagem2);
        }
        nomeJanelaAlerta.abrirJanela();

        return nomeJanelaAlerta;
    }

    function AlterarItem(idPlanilhaProjeto,idPronac,idProduto,stPrincipal)
    {
        //$('html').css('overflow', 'hidden');
        var este = $('#alteraritemsolicitado');
        este.html('<br><br><br><br><br><br><br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
        este.dialog(
        {
            title:"Alterar Item",
            resizable: false,
            width:800,
            height:600,
            modal: false,
            autoOpen:true,
            closeOnEscape:true
        });

        $.post(este.attr('link'),{idPlanilhaProjeto:idPlanilhaProjeto,idPronac:idPronac,idProduto:idProduto,stPrincipal:stPrincipal}
        ,function(data)
        {

            este.html(data);
            este.dialog(
            {
                title:"Alterar Item",
                resizable: false,
                width:800,
                height:600,
                modal: false,
                autoOpen:true,
                closeOnEscape:true,
                buttons:
                    {
                    'Cancelar': function()
                    {
                        $(this).dialog('close');
                        //$('html').css('overflow', 'auto');
                    },
                    'Salvar': function()
                    {

                        var texto = $('#justificativa'+$('#idPlanilhaProjeto').val()).val();
                        texto = texto.replace(/^\s+|\s+$/g,""); //retirando espaços
                        if (texto.length <= 0 || texto=="")
                        {
                            alertar('Dados obrigatórios não informados.');
                            return false;
                        }
                        else
                        {
                            var vlSugerido = $('#calcular_total'+$('#idPlanilhaProjeto').val()).html().replace(/\R\$\s+/g, '');
                            $('#totalcalculos'+$('#idPlanilhaProjeto').val()).val(vlSugerido);

                            var dados = $('#formSalvarItem').serialize();
                            $(this).append('<br><center>Aguarde, salvando informações...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br>');
                            $.post($('#formSalvarItem').attr('action'),dados
                            ,function(data)
                            {
                                var resposta = data;
                                $('#item'+$('#idPlanilhaProjeto').val()+' .JustParecerista').html($("#justificativa"+$('#idPlanilhaProjeto').val()).val());
                                $('#item'+$('#idPlanilhaProjeto').val()+' .ValorSugerido').html($("#calcular_total"+$('#idPlanilhaProjeto').val()).html());
                                somarValores();

                                //atualiza novo valor possivel de remanejamento
                                var vlSolicitado = '<?php echo $this->vlSolicitado;?>';
                                var vlTotalSugerido = recuperaTotalSugerido();
                                var valorpossivel = vlSolicitado - vlTotalSugerido;

                                $("#valorpossivel").val(valorpossivel);

                                //atualiza campo de apresentacao do novo valor possivel de remanejamento
                                var valorpossivelApresentacao = formatarParaReal(valorpossivel);
                                $("#valorpossivelApresentacao").html(valorpossivelApresentacao);

                                este.dialog('close');
                                janelaAlerta('Informações salvas com sucesso');
                            });

                        }
                    }
                }
            });
        });


    }

    function recuperaTotalSugerido()
    {
        // pega o valor total do relator
        var valor = $('.valorTotalSugerido').html();
        valor = valor.replace('R$ ', '');

        // retira os pontos e as virgulas, deixando somente numeros
        valor = valor.replace(/\D/g, "");
        valor = valor.replace(/(\d{0})(\d)/, "$1$2");

        // adiciona o ponto na casa decimal
        valor = valor.replace(/(\d)(\d{2})$/, "$1.$2");

        // converte para float
        valor = parseFloat(valor);

        return valor;
    }

    // formata para real
    function formatarParaReal(valor)
    {
        valor = (parseFloat(valor)).toFixed(2);
        valor = valor.replace(/\D/g, "");
        valor = valor.replace(/(\d)(\d{2})$/, "$1,$2");
        valor = valor.replace(/(\d+)(\d{3},\d{2})$/g, "$1.$2");

        var q = (valor.length - 3) / 3; // quantidade caracteres
        var c = 0; // contador
        while (q > c)
        {
            c++;
            valor = valor.replace(/(\d+)(\d{3}.*)/, "$1.$2");
        }
        valor = valor.replace(/^(0+)(\d)/g, "$2");
        valor = 'R$ ' + valor;

        return valor;
    }

    function areadetrabalho()
    {
        $('#abrir_fechar4').click(function()
        {
            $('#enquadramento').toggle('slow');
            $('#parecer').toggle('slow');
            $('#divAnaliseConteudo').hide('slow');
            $('#div_teste2').hide('slow');
        });

        $('#abaAnaliseConteudo').click(function()
        {
            $('#divAnaliseConteudo').toggle('slow');
        });

        $('#abaAnaliseCusto').click(function()
        {
            $('#divAnaliseCusto').toggle('slow');
        });
    }

    window.onload = function()
    {
        areadetrabalho();
    };

    function AbrirFecharPlanilha(elemento)
    {
        $('.' + elemento).toggle();
        if ($('#' + elemento).hasClass('icn_mais'))
        {
            $('#' + elemento).addClass('icn_menos');
            $('#' + elemento).removeClass('icn_mais');
        }
        else
        {
            $('#' + elemento).addClass('icn_mais');
            $('#' + elemento).removeClass('icn_menos');
        }
    }

    function carregarAnaliseDeConteudo()
    {
        recuperaFormulario($('#formAnaliseConteudo').attr('action'),{stAcao: 1, idPRONAC: <?php echo $this->projeto->IdPRONAC; ?>, idProduto: <?php echo $this->projeto->idProduto; ?>, stPrincipal:<?php echo $this->projeto->stPrincipal; ?>});
        return true;
    }

    function recuperaFormulario(url,params){
        if(params.length < 1)
        {
            params = {};
        }
        var btSalvar = false;
        $.post(url,params,function(data){
            if(data){
                $('#formAnaliseConteudo').find('input, select, textarea').each(function(key, object){
                    if($(object).attr('type') == 'radio'){
                        if($(object).val() == data[$(object).attr('name')]){
                            btSalvar = true;
                            $(object).attr('checked','true');
                        }
                    }else{
                        if($(object).attr('type') == 'checkbox'){
                            if(data[$(object).attr('name')] == 1){
                                btSalvar = true;
                                $(object).attr('checked','true');
                            }
                        }else{
                            btSalvar = true;
//                            if($(object).attr('type') == 'textarea'){
//                                console.debug(object);
//                            } else {
                                $(object).val(data[$(object).attr('name')]);
//                            }
                        }
                    }
                });
                $('#stAcao').val(2);
                // desabilitaFormConteudo(false);
            }else{
                $('#stAcao').val(3);
            }
        },'json');
    }

    function AbrirFecharPlanilha(elemento){
        $('.' + elemento).toggle();

        if ($('#' + elemento).hasClass('icn_mais'))
        {
            $('#' + elemento).addClass('icn_menos');
            $('#' + elemento).removeClass('icn_mais');
        }
        else
        {
            $('#' + elemento).addClass('icn_mais');
            $('#' + elemento).removeClass('icn_menos');
        }
        return false;
    }
    function janelaAlerta(mensagem,funcaoAdcional)
    {
        if(funcaoAdcional==undefined)
        {
            funcaoAdcional = function(){}
        }
        var nomeJanelaAlerta =   janelaObj({
            parametros : {
                width:      400,
                autoOpen:   false,
                resizable:  false,
                modal:      true,
                buttons: {
                    OK: function() {
                        funcaoAdcional();
                        $(this).dialog('close');
                    }
                }
            },
            removerBtFechar:true,
            title : 'Alerta'
        });
        nomeJanelaAlerta.divConteudo.html(mensagem);
        nomeJanelaAlerta.abrirJanela();

        return nomeJanelaAlerta;
    }
    function janelaObj(dados){
        var divConteudo = $('<div></div>')
        .attr('title',dados.title)
        .appendTo('body');
        var novaJanela =
            {
            divConteudo : divConteudo,
            removerBtFechar: true,
            parametros : {autoOpen: false},
            iniciarJanela : function(dados){
                this.refineParametrosObj(dados);

                this.divConteudo.dialog(this.parametros);
            },
            abrirJanela:function(){
                this.divConteudo.dialog('open');
                if(this.removerBtFechar)
                    $('.ui-dialog-titlebar-close').remove();
            },
            fecharJanela:function(){
                this.divConteudo.dialog('close');
                this.divConteudo.remove();
            },
            refineParametrosObj : function(data){
                if(data!= undefined)
                    for(var j in data){
                        this[j]=data[j];
                    }
            }
        }
        novaJanela.iniciarJanela(dados);
        return novaJanela;
    }
</script>
<script type="text/javascript">APPescolherArt_18(); APPescolherArt_26(); APPescolherLei_8313(); APPescolherArtigo3();</script>
