const TECNICO = '124';
const PERFIL_COORDENADOR_GERAL = '126';
const PERFIL_COORDENADOR = '125';
const PERFIL_DIRETOR = '148';
const PERFIL_SECRETARIO = '149';

const ESTADO_ANALISE_LAUDO = '10';
const ESTADO_AGUARDANDO_ASSINATURA_LAUDO = '11';
const ESTADO_AVALIACAO_RESULTADOS_FINALIZADA = '12';
const ESTADO_LAUDO_FINALIZADO = '14';
const ESTADO_AGUARDANDO_ANALISE_PARECER = '4';
const ESTADO_ANALISE_PARECER = '5';
const ESTADO_PARECER_FINALIZADO = '6';
const ESTADO_AGUARDANDO_ASSINATURA_COORDENADOR_PARECER = '9';
const ESTADO_AGUARDANDO_ASSINATURA_COORDENADOR_GERAL_PARECER = '15';
const ATO_ADMINISTRATIVO_PARECER_TECNICO = '622';
const ATO_ADMINISTRATIVO_LAUDO_FINAL = '623';

export default {
    TECNICO,
    PERFIL_COORDENADOR_GERAL,
    PERFIL_COORDENADOR,
    PERFIL_DIRETOR,
    PERFIL_SECRETARIO,
    ESTADO_ANALISE_LAUDO,
    ESTADO_AGUARDANDO_ASSINATURA_LAUDO,
    ESTADO_AVALIACAO_RESULTADOS_FINALIZADA,
    ESTADO_LAUDO_FINALIZADO,
    ESTADO_AGUARDANDO_ANALISE_PARECER,
    ESTADO_ANALISE_PARECER,
    ESTADO_PARECER_FINALIZADO,
    ESTADO_AGUARDANDO_ASSINATURA_COORDENADOR_PARECER,
    ESTADO_AGUARDANDO_ASSINATURA_COORDENADOR_GERAL_PARECER,
    ATO_ADMINISTRATIVO_PARECER_TECNICO,
    ATO_ADMINISTRATIVO_LAUDO_FINAL,
};
