<?php

$dbTable = new Admissibilidade_Model_DbTable_TbMensagemProjeto();
$auth = Zend_Auth::getInstance();
$arrAuth = $auth->getIdentity();
$intQtd = 0;
//$arrResult = $dbTable->getAllBy(array(
//    'tbMensagemProjeto.idDestinatario' => $arrAuth->usu_codigo,
//    'tbMensagemProjeto.idMensagemOrigem IS NULL' => '',
//    'dsMensagem IS NULL' => '',
//));

$grupoAtivo = new Zend_Session_Namespace('GrupoAtivo');
if (isset($arrAuth->usu_codigo) && isset($arrAuth->usu_orgao)) {
    $dbTable = new Admissibilidade_Model_DbTable_VwPainelDeMensagens();
    $arrResult = $dbTable->carregarPerguntasSemResposta($arrAuth->usu_codigo, $grupoAtivo->codOrgao);

    if (isset($arrAuth->usu_codigo)) {
        $intQtd = count($arrResult);
    }
//$intQtd = count($dbTable->getAllBy(array('idDestinatario' => $arrAuth->usu_codigo, 'tbMensagemProjeto.idUnidade => $arrAuth->usu_orgao')));
    if ($intQtd > 99) {
        $cssPadding = '1';
        $intQtd = '99+';
    } elseif ($intQtd > 9) {
        $cssPadding = '4';
    } else {
        $cssPadding = '6';
    }
}

?>

<li id="btn-solicitacoes" class="btn-notificacao" style="position: relative">
    <a class="white-text tooltipped" data-activates="header_notificacoes"
       data-position="left"
       data-delay="50"
       data-tooltip="Ir para Notifica&ccedil;&otilde;es" href="javascript:void(0)"
       data-ajax-render='/solicitacao/mensagem/listar-ajax<?= $this->params; ?>'
       data-ajax-target='#header_notificacoes'
    >
        <i class="material-icons left">notifications</i>
    </a>
    <div id="header_notificacoes" class="dropdown-content dropdown-media active black-text" style="opacity: 1"></div>
</li>

<script>
    // quando clicar fora do elemento fechar os icones
    $3(document).on("click", function (e) {
        if (!$3(e.target).closest('#header_notificacoes').length) {
            if ($3('#header_notificacoes').is(":visible")) {
                $3('#header_notificacoes').hide();
            }
        }

    });

    $3(document).ready(function () {
        contarSolicitacoesNaoLidas();
    });

    function contarSolicitacoesNaoLidas() {
        $3.ajax({
            type: "post",
            url: "<?php echo $this->url(array('module' => 'solicitacao', 'controller' => 'mensagem', 'action' => 'contar-solicitacoes-nao-lidas-ajax'), null, true); ?>",
            success: function (data) {
                if (data.status == true && data.msg > 0) {
                    $3("#btn-solicitacoes a").append('<span class="btn-floating waves-effect waves-light orange darken-1">' + data.msg + '</span>');
                }
            },
            dataType: 'json'
        });
    }
</script>

