<?php

$dbTable = new Admissibilidade_Model_DbTable_TbMensagemProjeto();
$auth = Zend_Auth::getInstance();
$arrAuth = $auth->getIdentity();
$intQtd = 0;

$grupoAtivo = new Zend_Session_Namespace('GrupoAtivo');
if (isset($arrAuth->usu_codigo) && isset($arrAuth->usu_orgao)) {
    $dbTable = new Admissibilidade_Model_DbTable_VwPainelDeMensagens();
    $arrResult = $dbTable->carregarPerguntasSemResposta($arrAuth->usu_codigo, $grupoAtivo->codOrgao);

    if (isset($arrAuth->usu_codigo)) {
        $intQtd = count($arrResult);
    }

    if ($intQtd > 99) {
        $cssPadding = '1';
        $intQtd =  '99+';
    } elseif ($intQtd > 9) {
        $cssPadding = '4';
    } else {
        $cssPadding = '6';
    }
}

?>
<style>
    .notificacao a {
        position: relative;
        padding: 0 !important;
        padding-top: 5px;
    }
    .notificacao .btn-floating {
        border-radius: 50%;
        color: #fff;
        cursor: pointer;
        height: 20px !important;
        width: 20px !important;
        line-height: 21px;
        position: absolute;
        left: 11px;
        top: 27px;
        display: block;
        text-align: center;
        vertical-align: middle;
        z-index: 1;
        font-size: 9px !important;
    }

</style>
<?php if ($intQtd > 0): ?>
<li class="notificacao">
    <a class="white-text tooltipped" data-position="left" data-delay="50" data-tooltip="Ir para mensagens" href="/admissibilidade/mensagem/perguntas-usuario">
        <i class="material-icons left">mail</i>
        <span class="btn-floating waves-effect waves-light orange darken-1"><?php echo $intQtd ?></span>
    </a>
</li>
<?php endif; ?>

