<script type="text/javascript">
    $(document).ready(function(){
        $('.btn_imprimir').click(function(){
            $('#addCampoXls').remove();
            $('#formImpressao').submit();
        });
        
        $('.btn_xls').click(function(){
            $('#addCampoXls').remove();
            $('#formImpressao').append('<input id="addCampoXls" type="hidden" name="xls" value="1">');
            $('#formImpressao').submit();
        });
    });
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first">Início</li>
        <li><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>" title="Ir para Consultar dados do Projeto">Consultar dados do Projeto</a></li>
        <li class="last">Providência Tomada</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Providência Tomada<span class="voltar"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index')); ?>?idPronac=<?php echo $this->idPronac; ?>">Voltar</a></span></div>
</div>


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    
    <?php if(count($this->dados)>0){ ?>
    <!-- ============ PAGINAÇÃO ============ -->
    <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr>
                <td align="center">
                <form name="form1" id="form1" action="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada'));?>" method="get">
                    <?php if($this->paginacao['pag']>1) { ?>
                    <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'">
                    <?php } ?>
                    <input id="btn_p_anterior" type="button"
                    <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                    <?php }else { ?>
                           class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'"
                    <?php } ?>>
                    <input id="btn_p_proximo" type="button"
                           <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                           class="btn_p_proximo-off"
                    <?php }else { ?>
                           class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'"
                    <?php } ?>>
                    <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                    <input class="btn_ultimo" id="btn_ultimo" type="button"
                           onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'">
                    <?php } ?>
                    Pág.:<select name="pag" id="pag" onchange="$('#form1').submit()" class="input_simples">
                        <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                        <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                        <?php endfor; ?>
                    </select>
                    &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                    <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                    <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                    <input type="hidden" name="idPronac" value="<?php echo $this->idPronac;?>">
                    <input type="button" class="btn_imprimir">
                    <input type="button" class="btn_xls">
                 </form>
                </td>
            </tr>
        </tbody>
    </table>
    <center>
        <?php
            echo $this->paginacao['inicio']." a ";
            echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
            echo " de ". $this->paginacao['total']. " Projetos listados";
        ?>
    </center>
    <!-- ========== FIM PAGINAÇÃO ========== -->
    <?php } ?>


    <?php if($this->qtdRegistros > 0){ ?>
    <table class="tabela tablesorter">
        <thead>
            <tr class="titulo_tabela">
                <th nowrap><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag=1&qtde='.$this->paginacao['qtde'].'&idPronac='.$this->idPronac.'&campo=1&ordem='.$this->paginacao['novaOrdem'];?>">Dt. Situa&ccedil;&atilde;o</a></th>
                <th>Situa&ccedil;&atilde;o</th>
                <th>Provid&ecirc;ncia tomada</th>
                <?php if(!in_array($this->idPerfil, array(90,91,94,104,105,115,118,130,1111))){ ?>
                <th>CPF</th>
                <th>Nome</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->dados as $d){ ?>
            <tr>
                <td align="center" nowrap><?php echo Data::tratarDataZend($d->DtSituacao, 'Brasileira'); ?></td>
                <td align="center"><?php echo $d->Situacao;?></td>
                <td align="left"><?php echo $d->ProvidenciaTomada;?></td>
                <?php if(!in_array($this->idPerfil, array(90,91,94,104,105,115,118,130,1111))){ ?>
                <td align="center" nowrap>
                    <?php
                    $nrCpfCnpj = trim($d->cnpjcpf);
                    if($nrCpfCnpj == '23969156149') {
                        echo '-';
                    } else {
                        echo (strlen($nrCpfCnpj) > 11) ? Mascara::addMaskCNPJ($nrCpfCnpj) : Mascara::addMaskCPF($nrCpfCnpj);
                    } ?>
                </td>
                <td align="left" nowrap><?php echo ($nrCpfCnpj == '23969156149') ? 'Sistema SALIC' : $d->usuario; ?></td>
                <?php } ?>
            </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php if(count($this->dados)>0){ ?>

        <!-- ============ PAGINAÇÃO ============ -->
        <?php if($this->qtdRegistros > 10) { //echo $this->dados; ?>
        <center>
            <?php
                echo $this->paginacao['inicio']." a ";
                echo ($this->paginacao['pag']-1)*$this->paginacao['Itenspag'] + $this->paginacao['tamanho'];
                echo " de ". $this->paginacao['total'];
            ?>
        </center>
        <table class="tabela" style="width: 97%;" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td align="center">
                    <form name="form2" id="form2" action="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada'));?>" method="get">
                        <?php if($this->paginacao['pag']>1) { ?>
                        <input class="btn_inicio" id="btn_inicio" type="button" class="btn_inicio"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag=1'."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'">
                        <?php } ?>
                        <input id="btn_p_anterior" type="button"
                        <?php if($this->paginacao['pag']<=1) { ?> class="btn_p_anterior-off"
                        <?php }else { ?>
                               class="btn_p_anterior" onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['pag'] - 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'"
                        <?php } ?>>
                        <input id="btn_p_proximo" type="button"
                               <?php if($this->paginacao['pag']+1 > $this->paginacao['totalPag']) { ?>
                               class="btn_p_proximo-off"
                        <?php }else { ?>
                               class="btn_p_proximo" onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['pag'] + 1)."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'"
                        <?php } ?>>
                        <?php if($this->paginacao['pag'] < $this->paginacao['totalPag']) { ?>
                        <input class="btn_ultimo" id="btn_ultimo" type="button"
                               onclick="location.href='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'providencia-tomada')).'?pag='.($this->paginacao['totalPag'])."&qtde=".$this->paginacao['qtde'].$this->paginacao['ordenacao'].'&idPronac='.$this->idPronac; ?>'">
                        <?php } ?>
                        Pág.:<select name="pag" id="pag" onchange="$('#form2').submit()" class="input_simples">
                            <?php for($i=1; $i<=$this->paginacao['totalPag']; $i++):?>
                            <option value="<?php echo $i;?>" <?php if($this->paginacao['pag'] == $i) echo "selected";?>><?php echo $i;?>&nbsp;</option>
                            <?php endfor; ?>
                        </select>
                        &nbsp;Registros por página:<input type="text" size="1" name="qtde" id="qtde" class="input_simples" value="<?php echo $this->intTamPag;?>"><input type="submit" class="btn_recarregar" value="">
                        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
                        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
                        <input type="hidden" name="idPronac" value="<?php echo $this->idPronac;?>">
                        <input type="button" class="btn_imprimir">
                        <input type="button" class="btn_xls">
                     </form>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- ========== FIM PAGINAÇÃO ========== -->

    <?php } } ?>


    <?php } else { ?>
    <table class="tabela">
        <tr>
            <td align="center">Nenhum registro encontrado.</td>
        </tr>
    </table>
    <?php } ?>
    <br clear="all" />

    <form target="_blank" class="form" name="formImpressao" id="formImpressao" method="post" action='<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'imprimir-providencia-tomada')); ?>'>
        <input type="hidden" name="campo" value="<?php echo $this->paginacao['campo'];?>">
        <input type="hidden" name="ordem" value="<?php echo $this->paginacao['ordem'];?>">
        <input type="hidden" name="pag" value="<?php echo $this->paginacao['pag'];?>">
        <input type="hidden" name="qtde" value="<?php echo $this->intTamPag;?>">
        <input type="hidden" name="idPronac" value="<?php echo $this->idPronac;?>">
    </form>

</div>


<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />