<?php header('Content-Type: text/plain; charset=ISO-8859-1'); ?>

<table class="tabela">
    <tr class="destacar">
        <td align="center"><b>PRONAC</b></td>
        <td align="center"><b>Nome do Projeto</b></td>
    </tr>
    <tr>
        <td align="center"><?php echo $this->dadosProjeto->pronac; ?></td>
        <td align="center"><?php echo $this->dadosProjeto->NomeProjeto; ?></td>
    </tr>
</table>

<fieldset>
    <legend>Proponente</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g1" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Proponente</strong></td>
        </tr>
    </table>
    <div id="div_g1" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td width="20%">CPF/CNPJ</td>
                <td>Nome do Proponente</td>
            </tr>
            <tr>
                <td align="center"><?php echo Validacao::mascaraCPFCNPJ($this->dadosProjeto['CNPJCPF']); ?></td>
                <td align="center"><?php echo $this->dadosProjeto['NomeProponente']; ?></td>
            </tr>
        </table>
    </div>
    <div id="proponente"></div>
</fieldset>


<br />



<fieldset>
    <legend>Produtos</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g2" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Produtos</strong></td>
        </tr>
    </table>
    <div id="div_g2" class="miolo_grid_01 sumir">

    <?php header('Content-Type: text/plain; charset=ISO-8859-1'); ?>
    <script type="text/javascript">

        function mostraOcultaElemento(elemento)
        {
                $('.' + elemento).toggle();

                if ($('#' + elemento).hasClass('btn_adicionar'))
                {
                        $('#' + elemento).addClass('btn_remover');
                        $('#' + elemento).removeClass('btn_adicionar');
                }
                else
                {
                        $('#' + elemento).addClass('btn_adicionar');
                        $('#' + elemento).removeClass('btn_remover');
                }
        }
    </script>
    <?php if(is_array($this->dadosProdutos) && count($this->dadosProdutos)>0):
        foreach($this->dadosProdutos as $distribuicao) : ?>
        <table class="tabela">
            <tr>
                <td align="left">
                    <input type="button" class="btn_adicionar" id="<?php echo $distribuicao->idPlanoDistribuicao;?>" onclick="mostraOcultaElemento('<?php echo $distribuicao->idPlanoDistribuicao;?>');" />  <b><?php echo "<b>".$distribuicao->Produto."</b>";?> <?php if($distribuicao->stPrincipal == 1) echo "<font color='red'>(produto principal)</font>";?></b>
                </td>
            </tr>
            <tr class="<?php echo $distribuicao->idPlanoDistribuicao;?> sumir" align="left">
                <td >
                    <table class="tabela">
                        <!--<tr class="destacar">
                            <th align="center"><b>Produto</b></th>
                        </tr>
                        <tr>
                            <td align='center' style="font-size: 11pt"><?php echo "<b>".$distribuicao->Produto."</b>";?> <?php if($distribuicao->stPrincipal == 1) echo "<font color='red'>(principal)</font>";?></td>
                        </tr>-->
                        <tr>
                            <td align='center' width="20%" class="destacar"><b>Produto</b></td>
                        </tr>
                        <tr>
                            <td align='center' width="80%" style="font-size: 11pt"><?php echo "<b>".$distribuicao->Produto."</b>";?></td>
                        </tr>
                        <tr>
                            <td align='center' width="20%" class="destacar"><b>Logomarca</b></td>
                        </tr>
                        <tr>
                            <td align='center' width="80%"><?php echo $distribuicao->PosicaoDaLogo;?></td>
                        </tr>
                        <tr>
                            <td align= 'center' style='padding:0;'>
                                <table class='tabela'>
                                    <tr class="destacar">
                                        <td align="center"><b>Distribui&ccedil;&atilde;o Gratuita (Qtde)</b></td>
                                        <td align="center"><b>Total para Venda (Qtde)</b></td>
                                        <td align="center"><b>Pre&ccedil;o Unit&aacute;rio (R$)</b></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table class='tabela'>
                                                <tr>
                                                    <td>
                                                        <b>Patrocinador</b><br>
                                                        <?php echo $distribuicao->QtdePatrocinador;?>
                                                    </td>
                                                    <td>
                                                        <b>Divulga&ccedil;&atilde;o</b><br>
                                                        <?php echo $distribuicao->QtdeOutros;?>
                                                    </td>
                                                    <td>
                                                        <b>Benefici&aacute;rios</b><br>
                                                        <?php echo $distribuicao->QtdeProduzida;?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td>
                                            <table class='tabela'>
                                                <tr>
                                                    <td>
                                                        <b>Normal</b><br>
                                                        <?php echo $distribuicao->QtdeVendaNormal;?>
                                                    </td>
                                                    <td>
                                                        <b>Promocional</b><br>
                                                        <?php echo $distribuicao->QtdeVendaPromocional;?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td>
                                            <table class='tabela'>
                                                <tr>
                                                    <td>
                                                        <b>Normal</b><br>
                                                       <?php echo number_format($distribuicao->PrecoUnitarioNormal, 2, ',', '.');?>
                                                    </td>
                                                    <td>
                                                        <b>Promocional</b><br>
                                                        <?php echo number_format($distribuicao->PrecoUnitarioPromocional, 2, ',', '.');?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr class="destacar">
                                        <td align="center"><b>Receita Prevista (R$)</b></td>
                                        <td align="center" colspan='2'><b>Total Receita Prevista (R$)</b></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table class='tabela'>
                                                <tr>
                                                    <td>
                                                        <b>Normal</b><br>
                                                        <?php echo number_format($distribuicao->ReceitaNormal, 2, ',', '.');?>
                                                    </td>
                                                    <td>
                                                        <b>Promocional</b><br>
                                                        <?php echo number_format($distribuicao->ReceitaPro, 2, ',', '.');?>
                                                    </td>
                                                    <td>
                                                        <b>Prevista</b><br>
                                                        <?php echo number_format($distribuicao->ReceitaPrevista, 2, ',', '.');?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td colspan='2'>
                                            <table class='tabela' >
                                                <tr>
                                                    <td>
                                                        <b>Total Receita Prevista (R$)</b><br>
                                                        <?php echo number_format($distribuicao->ReceitaPrevista, 2, ',', '.');?>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                </table>
                            </td>
                    </table>
                </td>
            </tr>
        </table>
        <?php endforeach; ?>
<?php else: ?>
    <table class="tabela">
        <tr>
            <td align="center"><em>Dados n&atilde;o informados!</em></td>
        </tr>
    </table>
<?php endif; ?>

	</div>
	<div id="produtos"></div>
</fieldset>



<br />



<fieldset>
    <legend>Ficha T&eacute;cnica</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g3" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Ficha T&eacute;cnica</strong></td>
        </tr>
    </table>
    <div id="div_g3" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td>Ficha T&eacute;cnica</td>
            </tr>
            <tr>
                <td><?php echo !empty($this->dadosPedido['FichaTecnica']) ? strip_tags($this->dadosPedido['FichaTecnica']) : 'Não Aplicável' ?></td>
            </tr>
        </table>
    </div>
    <div id="ficha-tecnica"></div>
</fieldset>


<br />


<fieldset>
    <legend>Local de Realiza&ccedil;&atilde;o</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g4" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Local de Realiza&ccedil;&atilde;o</strong></td>
        </tr>
    </table>
    <div id="div_g4" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td>Pa&iacute;s</td>
                <td>UF</td>
                <td>Cidade</td>
            </tr>
            <?php foreach ($this->dadosLocais as $d) : ?>
            <tr align="center">
                <td><?php echo $d->dsPais; ?></td>
                <td><?php echo $d->dsUF; ?></td>
                <td><?php echo $d->dsMunicipioIBGE; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <div id="local-realizacao"></div>
</fieldset>


<br />


<fieldset>
    <legend>Nome do Projeto</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g5" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Nome do Projeto</strong></td>
        </tr>
    </table>
    <div id="div_g5" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td width="20%">PRONAC</td>
                <td>Nome do Projeto</td>
            </tr>
            <tr>
                <td align="center"><?php echo $this->dadosProjeto['pronac']; ?></td>
                <td align="center"><?php echo $this->dadosProjeto['NomeProjeto']; ?></td>
            </tr>
        </table>
    </div>
    <div id="nome-projeto"></div>
</fieldset>


<br />


<fieldset>
    <legend>Prazo de Execu&ccedil;&atilde;o</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g6" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Prazo de Execu&ccedil;&atilde;o</strong></td>
        </tr>
    </table>
    <div id="div_g6" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td width="50%">Data de In&iacute;cio</td>
                <td width="50%">Data de Fim</td>
            </tr>
            <tr align="center">
                <td><?php echo isset($this->dadosPrazoExecucao->DtInicioExecucao) ? $this->dadosPrazoExecucao->DtInicioExecucao : ''; ?></td>
                <td><?php echo isset($this->dadosPrazoExecucao->DtFimExecucao)    ? $this->dadosPrazoExecucao->DtFimExecucao    : ''; ?></td>
            </tr>
        </table>
    </div>
    <div id="prazo-execucao"></div>
</fieldset>


<br />


<fieldset>
    <legend>Prazo de Capta&ccedil;&atilde;o</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g7" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Prazo de Capta&ccedil;&atilde;o</strong></td>
        </tr>
    </table>
    <div id="div_g7" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td width="50%">Data de In&iacute;cio</td>
                <td width="50%">Data de Fim</td>
            </tr>
            <tr align="center">
                <td><?php echo isset($this->dadosPrazoCaptacao->DtInicioCaptacao) ? $this->dadosPrazoCaptacao->DtInicioCaptacao : ''; ?></td>
                <td><?php echo isset($this->dadosPrazoCaptacao->DtFimCaptacao)    ? $this->dadosPrazoCaptacao->DtFimCaptacao    : ''; ?></td>
            </tr>
        </table>
    </div>
    <div id="prazo-captacao"></div>
</fieldset>


<br />


<fieldset>
    <legend>Proposta Pedag&oacute;gica</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g8" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Proposta Pedag&oacute;gica</strong></td>
        </tr>
    </table>
    <div id="div_g8" class="miolo_grid_01 sumir">
        <table class="tabela">
            <tr class="destacar bold" align="center">
                <td>Especifica&ccedil;&atilde;o T&eacute;cnica</td>
            </tr>
            <tr>
                <td><?php echo !empty($this->dadosPedido['EspecificacaoTecnica']) ? strip_tags($this->dadosPedido['EspecificacaoTecnica']) : 'Não Aplicável'; ?></td>
            </tr>
            <tr class="destacar bold" align="center">
                <td>Outras Informa&ccedil;&otilde;es</td>
            </tr>
            <tr>
                <td><?php echo !empty($this->dadosPedido['EstrategiadeExecucao']) ? strip_tags($this->dadosPedido['EstrategiadeExecucao']) : 'Não Aplicável'; ?></td>
            </tr>
        </table>
    </div>
    <div id="proposta-pedagogica"></div>
</fieldset>


<br />


<fieldset>
    <legend>Custo por Produtos</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g9" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Custo por Produtos</strong></td>
        </tr>
    </table>
    <div id="div_g9" class="miolo_grid_01 sumir">
        <script type="text/javascript">
            function AbrirFecharPlanilha(elemento)
            {
                    $('.' + elemento).toggle();

                    if ($('#' + elemento).hasClass('icn_mais'))
                    {
                            $('#' + elemento).addClass('icn_menos');
                            $('#' + elemento).removeClass('icn_mais');
                    }
                    else
                    {
                            $('#' + elemento).addClass('icn_mais');
                            $('#' + elemento).removeClass('icn_menos');
                    }
            }

            $(document).ready(function(){
                $(".icn_menos").click(function(){
                    var tipo = $(this).attr('tipo');
                    var aberto = $(this).attr('aberto');
                    if(aberto == 'true'){
                        adisplay = 'none';
                        $(this).attr('aberto','false')
                        $(this).removeClass('icn_menos').addClass('icn_mais')
                    }
                    else{
                        adisplay = '';
                        $(this).attr('aberto','true')
                        $(this).removeClass('icn_mais').addClass('icn_menos')
                    }
                    if(tipo == 'fonte'){
                        fonte = $(this).attr('fonte');
                        $(".master[fonte='"+fonte+"']").css('display', adisplay);
                        $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
                    }
                    if(tipo == 'produto'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                    if(tipo == 'etapa'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        etapa = $(this).attr('etapa');
                        $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                    if(tipo == 'cidade'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        etapa = $(this).attr('etapa');
                        cidade = $(this).attr('cidade');
                        $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                })
                $(".item").mouseover(function(){
                    $(this).addClass('fundo_linha3');
                })
                $(".item").mouseout(function(){
                    $(this).removeClass('fundo_linha3');
                })
                $(".item").click(function(){
                    if($(this).hasClass('fundo_linha4')){
                        $(this).removeClass('fundo_linha4');
                    }
                    else{
                        $(this).addClass('fundo_linha4');
                    }
                })
            })

        </script>
        <table class="tabela">
            <?php
            $nrfonte = 0;
            $item = 1;
            if(is_array($this->planilhaAP) && count($this->planilhaAP)>0) foreach ($this->planilhaAP as $fonte => $planilha) { //ForeachFonteIncentivo
                ?>
                <tr>
                    <td>
                        <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
                    </td>
                </tr>
                <?php
                $nrproduto = 0;
                $valorprodutosolicitado = 0;
                foreach ($this->planilhaAP[$fonte] as $produto => $planilha) {
                    ?>
                    <tr class='master' fonte="<?php echo $nrfonte; ?>">
                        <td class='master'>
                            <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                        </td>
                    </tr>
                    <?php
                    $nretapa = 0;
                    foreach ($this->planilhaAP[$fonte][$produto] as $etapa => $planilha) {
                        $valoretapasolicitado = 0;
                        ?>
                        <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                            <td>
                                <div><div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div></div>
                            </td>
                        </tr>
                        <?php
                        $nrcidade = 0;
                        foreach ($this->planilhaAP[$fonte][$produto][$etapa] as $cidade => $planilha) {
                            ?>
                            <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                                <td>
                                    <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;"><span class="black del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
                                </td>
                            </tr>
                            <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>"  fonte="<?php echo $nrfonte; ?>">
                                <td>
                                    <table class="tabela">
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th>Item</th>
                                            <th>Dias</th>
                                            <th>Unidade</th>
                                            <th>Qtde</th>
                                            <th>Ocor.</th>
                                            <th>Vl. Unit&aacute;rio</th>
                                            <th>Vl. Solicitado</th>
                                            <th>Justif. do proponente</th>
                                        </tr>
                                        <?php
                                        $valorufsolicitado = 0;
                                        foreach ($this->planilhaAP[$fonte][$produto][$etapa][$cidade] as $planilha) {
                                            $valorufsolicitado += $planilha['vlproponente'];
                                            ?>
                                            <tr class="item">
                                                <td><?php echo $item; ?></td>
                                                <td><a idPlanilhaProposta ="<?php echo $planilha['idPlanilhaProposta']; ?>" ><?php echo $planilha['item']; ?></a></td>
                                                <td><?php echo $planilha['diasprop']; ?></td>
                                                <td><?php echo $planilha['UnidadeProposta']; ?></td>
                                                <td class="direita"><?php echo $planilha['quantidadeprop']; ?></td>
                                                <td class="direita"><?php echo $planilha['ocorrenciaprop']; ?></td>
                                                <td class="direita"><?php echo $this->formatarReal($planilha['valorUnitarioprop']); ?></td>
                                                <td class="direita"><?php echo $planilha['vlproponente']; ?></td>
                                                <td><?php echo $planilha['justificitivaproponente']; ?></td>
                                            </tr>
                                            <?php
                                            $item++;
                                        } //fechaForeachplanilha
                                        $nrcidade++;
                                        $valoretapasolicitado += $valorufsolicitado;

                                        $valorprodutosolicitado += $valorufsolicitado;
                                        ?>
                                        <tr>
                                            <td colspan="7" class="black" style="font-size: 14pt;">Total de UF</td>
                                            <td class="black" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valorufsolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="7" class="orange" style="font-size: 14pt;">Total da Etapa</td>
                                            <td class="orange" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valoretapasolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="7" class="green" style="font-size: 14pt;">Valor para <?php echo $produto; ?></td>
                                            <td class="green" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valorprodutosolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <?php
                        } //fechaForeachcidade
                        $nretapa++;
                    } //fechaForeachetapa
                    $valorprodutosolicitado = 0;
                    $valorprodutoparecerista = 0;
                    $nrproduto++;
                } //fechaForeachproduto
                $nrfonte++;
            }//fechaForeachFonteIncentivo
            ?>
            <?php if(is_array($this->planilhaAP) && count($this->planilhaAP)>0): ?>
            <tr>
                <td>
                     <table class="tabela">
                       <tr class="destacar" style="font-size: 14pt;">
                           <th colspan="3">Total Geral</th>
                       </tr>
                        <tr class="destacar">
                            <th>Total Solicitado</th>
                        </tr>
                        <tr>
                            <td class="direita red" style="font-size: 14pt;"><?php echo $this->formatarReal($this->totalproponenteAP); ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php else: ?>
            <tr>
                <td align="center"><em>Dados n&atilde;o informados!</em></td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
    <div id="custos-produtos"></div>
</fieldset>


<br />


<fieldset>
    <legend>Custo Administrativo</legend>
    <table class="tabela" summary="Dados Atuais">
        <tr>
            <td><input type="button" name="grid1" id="g10" class="btn_adicionar" title="Expandir" /> <strong>Dados Atuais - Custo Administrativo</strong></td>
        </tr>
    </table>
    <div id="div_g10" class="miolo_grid_01 sumir">
        <script type="text/javascript">
            function AbrirFecharPlanilha(elemento)
            {
                    $('.' + elemento).toggle();

                    if ($('#' + elemento).hasClass('icn_mais'))
                    {
                            $('#' + elemento).addClass('icn_menos');
                            $('#' + elemento).removeClass('icn_mais');
                    }
                    else
                    {
                            $('#' + elemento).addClass('icn_mais');
                            $('#' + elemento).removeClass('icn_menos');
                    }
            }

            $(document).ready(function(){
                $(".icn_menos").click(function(){
                    var tipo = $(this).attr('tipo');
                    var aberto = $(this).attr('aberto');
                    if(aberto == 'true'){
                        adisplay = 'none';
                        $(this).attr('aberto','false')
                        $(this).removeClass('icn_menos').addClass('icn_mais')
                    }
                    else{
                        adisplay = '';
                        $(this).attr('aberto','true')
                        $(this).removeClass('icn_mais').addClass('icn_menos')
                    }
                    if(tipo == 'fonte'){
                        fonte = $(this).attr('fonte');
                        $(".master[fonte='"+fonte+"']").css('display', adisplay);
                        $(".clickproduto").removeClass('icn_mais').addClass('icn_menos');
                    }
                    if(tipo == 'produto'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        $(".produto[produto='"+produto+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                    if(tipo == 'etapa'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        etapa = $(this).attr('etapa');
                        $(".etapa[produto='"+produto+"'][etapa='"+etapa+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                    if(tipo == 'cidade'){
                        fonte = $(this).attr('fonte');
                        produto = $(this).attr('produto');
                        etapa = $(this).attr('etapa');
                        cidade = $(this).attr('cidade');
                        $(".cidade[produto='"+produto+"'][etapa='"+etapa+"'][cidade='"+cidade+"'][fonte='"+fonte+"']").css('display', adisplay);
                    }
                })
                $(".item").mouseover(function(){
                    $(this).addClass('fundo_linha3');
                })
                $(".item").mouseout(function(){
                    $(this).removeClass('fundo_linha3');
                })
                $(".item").click(function(){
                    if($(this).hasClass('fundo_linha4')){
                        $(this).removeClass('fundo_linha4');
                    }
                    else{
                        $(this).addClass('fundo_linha4');
                    }
                })
            })

        </script>
        <table class="tabela">
            <?php
            $nrfonte = 0;
            $item = 1;
            if(is_array($this->planilhaAP) && count($this->planilhaAP)>0) foreach ($this->planilhaAP as $fonte => $planilha) { //ForeachFonteIncentivo
                ?>
                <tr>
                    <td>
                        <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
                    </td>
                </tr>
                <?php
                $nrproduto = 0;
                $valorprodutosolicitado = 0;
                foreach ($this->planilhaAP[$fonte] as $produto => $planilha) {
                    ?>
                    <tr class='master' fonte="<?php echo $nrfonte; ?>">
                        <td class='master'>
                            <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                        </td>
                    </tr>
                    <?php
                    $nretapa = 0;
                    foreach ($this->planilhaAP[$fonte][$produto] as $etapa => $planilha) {
                        $valoretapasolicitado = 0;
                        ?>
                        <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                            <td>
                                <div><div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div></div>
                            </td>
                        </tr>
                        <?php
                        $nrcidade = 0;
                        foreach ($this->planilhaAP[$fonte][$produto][$etapa] as $cidade => $planilha) {
                            ?>
                            <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                                <td>
                                    <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;"><span class="black del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
                                </td>
                            </tr>
                            <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>"  fonte="<?php echo $nrfonte; ?>">
                                <td>
                                    <table class="tabela">
                                        <tr>
                                            <th>&nbsp;</th>
                                            <th>Item</th>
                                            <th>Dias</th>
                                            <th>Unidade</th>
                                            <th>Qtde</th>
                                            <th>Ocor.</th>
                                            <th>Vl. Unit&aacute;rio</th>
                                            <th>Vl. Solicitado</th>
                                            <th>Justif. do proponente</th>
                                        </tr>
                                        <?php
                                        $valorufsolicitado = 0;
                                        foreach ($this->planilhaAP[$fonte][$produto][$etapa][$cidade] as $planilha) {
                                            $valorufsolicitado += $planilha['vlproponente'];
                                            ?>
                                            <tr class="item">
                                                <td><?php echo $item; ?></td>
                                                <td><a idPlanilhaProposta ="<?php echo $planilha['idPlanilhaProposta']; ?>" ><?php echo $planilha['item']; ?></a></td>
                                                <td><?php echo $planilha['diasprop']; ?></td>
                                                <td><?php echo $planilha['UnidadeProposta']; ?></td>
                                                <td class="direita"><?php echo $planilha['quantidadeprop']; ?></td>
                                                <td class="direita"><?php echo $planilha['ocorrenciaprop']; ?></td>
                                                <td class="direita"><?php echo $this->formatarReal($planilha['valorUnitarioprop']); ?></td>
                                                <td class="direita"><?php echo $planilha['vlproponente']; ?></td>
                                                <td><?php echo $planilha['justificitivaproponente']; ?></td>
                                            </tr>
                                            <?php
                                            $item++;
                                        } //fechaForeachplanilha
                                        $nrcidade++;
                                        $valoretapasolicitado += $valorufsolicitado;

                                        $valorprodutosolicitado += $valorufsolicitado;
                                        ?>
                                        <tr>
                                            <td colspan="7" class="black" style="font-size: 14pt;">Total de UF</td>
                                            <td class="black" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valorufsolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="7" class="orange" style="font-size: 14pt;">Total da Etapa</td>
                                            <td class="orange" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valoretapasolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td colspan="7" class="green" style="font-size: 14pt;">Valor para <?php echo $produto; ?></td>
                                            <td class="green" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($valorprodutosolicitado); ?></td>
                                            <td></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <?php
                        } //fechaForeachcidade
                        $nretapa++;
                    } //fechaForeachetapa
                    $valorprodutosolicitado = 0;
                    $valorprodutoparecerista = 0;
                    $nrproduto++;
                } //fechaForeachproduto
                $nrfonte++;
            }//fechaForeachFonteIncentivo
            ?>
            <?php if(is_array($this->planilhaAP) && count($this->planilhaAP)>0): ?>
            <tr>
                <td>
                     <table class="tabela">
                       <tr class="destacar" style="font-size: 14pt;">
                           <th colspan="3">Total Geral</th>
                       </tr>
                        <tr class="destacar">
                            <th>Total Solicitado</th>
                        </tr>
                        <tr>
                            <td class="direita red" style="font-size: 14pt;"><?php echo $this->formatarReal($this->totalproponenteAP); ?></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php else: ?>
            <tr>
                <td align="center"><em>Dados n&atilde;o informados!</em></td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
    <div id="custos-administrativo"></div>
</fieldset>


<script type="text/javascript">
    /**
     * Ações que serão executadas após o carregamento da página
     */
    $(document).ready(function(){
	/**
	 * Função para carregar uma página dentro de outra via ajax
	 */
	function carregarDados(url, divRetorno){
            $('#' + divRetorno).html('<br><br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br><br>');
            $.ajax({
                url : url,
                success: function(data)
                {
                    $('#' + divRetorno).html(data);
                },
                type : 'post'
            });
        } // fecha função carregaDados()

        // atualiza o título da página
        window.parent.$("#titulo").html("<div>Readequa&ccedil;&atilde;o</div>");
        window.parent.$("#caminhoLocalAtual").html("Readequa&ccedil;&atilde;o");

	// grid
	$('input[name=grid1]').click(function(){
            grid_01(this.id);return false;
	});

	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-proponente', 'idpronac' => $this->idPronac)); ?>',           'proponente');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-produtos', 'idpronac' => $this->idPronac)); ?>',             'produtos');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-ficha-tecnica', 'idpronac' => $this->idPronac)); ?>',        'ficha-tecnica');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-local-realizacao', 'idpronac' => $this->idPronac)); ?>',     'local-realizacao');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-nome-projeto', 'idpronac' => $this->idPronac)); ?>',         'nome-projeto');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-prazo-execucao', 'idpronac' => $this->idPronac)); ?>',       'prazo-execucao');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-prazo-captacao', 'idpronac' => $this->idPronac)); ?>',       'prazo-captacao');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-proposta-pedagogica', 'idpronac' => $this->idPronac)); ?>',  'proposta-pedagogica');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-custo-produtos', 'idpronac' => $this->idPronac)); ?>',       'custos-produtos');
	carregarDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-custo-administrativo', 'idpronac' => $this->idPronac)); ?>', 'custos-administrativo');
    });
</script>