<table class="tabela">
    <?php
    $nrfonte = 0;
    $TotalUnitario = 0;
    $TotalAprovado = 0;
    $TotalComprovado = 0;
    if(is_array($this->planilha) && count($this->planilha)>0) foreach ($this->planilha as $fonte => $planilha) { //ForeachFonteIncentivo
        ?>
        <tr>
            <td>
                <div tipo="fonte" fonte="<?php echo $nrfonte; ?>" aberto="true" class="icn_menos" style="width:90%"><span class="red del_link" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
            </td>
        </tr>
        <?php
        $nrproduto = 0;
        $valorUnitarioTotalIncentivo = 0;
        $valorAprovadoTotalIncentivo = 0;
        $valorComprovadoTotalIncentivo = 0;
        foreach ($this->planilha[$fonte] as $produto => $planilha) {
            ?>
            <tr class='master' fonte="<?php echo $nrfonte; ?>">
                <td class='master'>
                    <div  tipo="produto" aberto="true" fonte="<?php echo $nrfonte; ?>" produto ="<?php echo $nrproduto; ?>" class="icn_menos clickproduto" style="width:98%; margin-left:2%;"><span class="green del_link" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
                </td>
            </tr>
            <?php
            $nretapa = 0;
            $valorUnitarioTotalProduto = 0;
            $valorAprovadoTotalProduto = 0;
            $valorComprovadoTotalProduto = 0;
            foreach ($this->planilha[$fonte][$produto] as $etapa => $planilha) {
                $valoretapasolicitado = 0;
                ?>
                <tr class="master produto" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>" >
                    <td>
                        <div><div tipo="etapa" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:4%;"><span class="orange-text del_link" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div></div>
                    </td>
                </tr>
                <?php
                $nrcidade = 0;
                $valorUnitarioTotalEtapa = 0;
                $valorAprovadoTotalEtapa = 0;
                $valorComprovadoTotalEtapa = 0;
                foreach ($this->planilha[$fonte][$produto][$etapa] as $cidade => $planilha) {
                    ?>
                    <tr class="master produto etapa" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>"  fonte="<?php echo $nrfonte; ?>" >
                        <td>
                            <div tipo="cidade" fonte="<?php echo $nrfonte; ?>" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>" aberto="true" class="icn_menos" style="width:94%; margin-left:6%;"><span class="black del_link" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
                        </td>
                    </tr>
                    <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>" etapa="<?php echo $nretapa; ?>" cidade="<?php echo $nrcidade; ?>"  fonte="<?php echo $nrfonte; ?>">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>&nbsp;</th>
                                    <th>Item</th>
				    <th>Unidade</th>
                                    <th>Dias</th>
                                    <th>Qtde</th>
                                    <th>Ocor.</th>
                                    <th>Vl. Unit&aacute;rio</th>
                                    <th>Vl. Aprovado</th>
                                    <th>Vl. Comprovado</th>
				    <th>Justif. Readequa&ccedil;&atilde;o</th>
                                </tr>
                                <?php
                                $valorAprovadoTotalUf = 0;
                                $valorComprovadoTotalUf = 0;
                                $vlUnitario = 0;
                                $vlAprovado = 0;
                                $vlComprovado = 0;
                                foreach ($this->planilha[$fonte][$produto][$etapa][$cidade] as $planilha) {
                                    $vlAprovado += $planilha['vlAprovado'];
                                    // soma somente quando não tiver excluído o item
                                    $valorAprovadoTotalUf += $planilha['vlAprovado'];
                                    $valorAprovadoTotalEtapa += $planilha['vlAprovado'];
                                    $valorAprovadoTotalProduto += $planilha['vlAprovado'];
                                    $valorAprovadoTotalIncentivo += $planilha['vlAprovado'];
                                    $TotalAprovado += $planilha['vlAprovado'];

                                    $valorComprovadoTotalUf += $planilha['vlComprovado'];
                                    $valorComprovadoTotalEtapa += $planilha['vlComprovado'];
                                    $valorComprovadoTotalProduto += $planilha['vlComprovado'];
                                    $valorComprovadoTotalIncentivo += $planilha['vlComprovado'];
                                    $TotalComprovado += $planilha['vlComprovado'];
                                ?>
                                    <?php
                                    $corLinha = '';
                                    switch ($planilha['tpAcao']) {
                                        case 'A':
                                            $corLinha = 'blue';
                                            break;
                                        default:
                                            $corLinha = '';
                                            break;
                                    }
                                    ?>
                                    <tr class="item" style="color: <?php echo $corLinha; ?> !important;">
                                        <td style="width: 5%;"><?php echo $planilha['Seq']; ?></td>
                                        <td style="width: 20%;">
					    <?php 
					    if ($this->ItemDisponivelParaEdicaoRemanejamento($planilha, $nrfonte)
					    && $this->link) : ?>
                                            <a href="#"
					       style="color: <?php echo $corLinha; ?> !important;"
					       title="clique para alterar os dados do item"
					       class="editarItem"
					       idPlanilhaAprovacao="<?php echo $planilha['idPlanilhaAprovacao']; ?>"
					       idPlanilhaAprovacaoPai="<?php echo $planilha['idPlanilhaAprovacaoPai']; ?>"
					    ><?php echo $planilha['Item']; ?></a>
                                            <?php else: ?>
                                            <?php echo $planilha['Item']; ?>
                                            <?php endif; ?>

                                        </td>
					<td class="direita textDias"><?php echo $planilha['Unidade']; ?></td>
                                        <td class="direita textDias"><?php echo $planilha['QtdeDias']; ?></td>
                                        <td class="direita textQuantidade"><?php echo $planilha['Quantidade']; ?></td>
                                        <td class="direita textOcorrencia"><?php echo $planilha['Ocorrencia']; ?></td>
                                        <td class="direita textValorUnitario"><?php echo @number_format($planilha['vlUnitario'], 2, ",", "."); ?></td>
                                        <td class="direita textValorAprovado"><?php echo @number_format($planilha['vlAprovado'], 2, ",", "."); ?></td>
                                        <td class="direita textValorComprovado"><?php echo @number_format($planilha['vlComprovado'], 2, ",", "."); ?></td>
                                        <td class="textJustificativa" style="width: 20%;"><?php echo $planilha['dsJustificativa']; ?></td>
                                    </tr>
                                    <?php
                                } //fechaForeachplanilha
                                $nrcidade++;
                                ?>
                                <tr>
                                    <td colspan="6" class="black" style="font-size: 14pt;">Total da UF</td>
                                    <td class="black" style="font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorAprovadoTotalUf, 2, ",", "."); ?></td>
                                    <td class="black" style="font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorComprovadoTotalUf, 2, ",", "."); ?></td>
                                    <td colspan="3"></td>
                                </tr>

                            <tr>
                                <td colspan="6" class="orange-text" style="width: 18%; font-size: 14pt;" nowrap>Total da Etapa</td>
                                <td class="orange-text" style="width: 1px; font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorAprovadoTotalEtapa, 2, ",", "."); ?></td>
				<td class="orange-text" style="width: 1px; font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorComprovadoTotalEtapa, 2, ",", "."); ?></td>
                                <td colspan="3" style="width: 40%;">&nbsp;</td>
                            </tr>
                            </table>
                        </td>
                    </tr>
                    <?php
                } //fechaForeachcidade
		?>
                <?php $nretapa++;
            } //fechaForeachetapa
            ?>
            <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>">
                <td>
                    <table class="tabela">
		      <tr>
			  <th colspan="6"></th>
			  <th style="text-align: right !important">Valor Aprovado</th>
			  <th style="text-align: right !important">Valor Comprovado</th>			
		      <th></th>
		    </tr>
                        <tr>
                            <td colspan="6" class="green-text" style="width: 68%; font-size: 14pt;">Total da <?php echo $produto; ?></td>
                            <td class="green-text" style="font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorAprovadoTotalProduto, 2, ",", "."); ?></td>
                            <td class="green-text" style="font-size: 12pt; font-weight: 600; text-align: right"><?php echo @number_format($valorComprovadoTotalProduto, 2, ",", "."); ?></td>
			    <td colspan="3" style="width: 21%;">&nbsp;</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <?php $nrproduto++;
        } //fechaForeachproduto
        ?>
        <tr class="master produto etapa cidade" produto="<?php echo $nrproduto; ?>"  fonte="<?php echo $nrfonte; ?>">
            <td>
              <table class="tabela">
		<tr>
		    <th colspan="6" style="width:69%"></th>
		    <th style="text-align: right !important">Valor Aprovado</th>
		    <th style="text-align: right !important">Valor Comprovado</th>		    
		    <th style="width:20%"></th>
		</tr>
		
                    <tr>
                        <td colspan="6" class="red-text" style="width: 69%; font-size: 14pt;">Total do <?php echo $fonte; ?></td>
                        <td class="red-text" style="width: 1px; font-size: 12pt; font-weight: 800; text-align: right"><?php echo @number_format($valorAprovadoTotalIncentivo, 2, ",", "."); ?></td>
			<td class="red-text" style="width: 1px; font-size: 12pt; font-weight: 800; text-align:right"><?php echo @number_format($valorComprovadoTotalIncentivo, 2, ",", "."); ?></td>
			<td colspan="3" style="width: 20%;">&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
	<?php $nrfonte++;
    }//fechaForeachFonteIncentivo

    ?>
    <?php if(is_array($this->planilha) && count($this->planilha)>0): ?>
    <tr>
        <td>
            <table class="tabela">
		<tr>
		    <th colspan="6" style="width: 69%" with></th>
		    <th style="text-align: right !important">Valor Aprovado</th>
		    <th style="text-align: right !important">Valor Comprovado</th>
		    <th style="width: 20%"></th>
		</tr>
		
                <tr>
		    <td colspan="6" class="blue-text" style="width: 69%; font-size: 14pt;">Total do Projeto</td>
		    <td class="blue-text" style="width: 1px; font-size: 12pt; font-weight: 800; text-align:right"><?php echo @number_format($TotalAprovado, 2, ",", "."); ?></td>
		    <td class="blue-text" style="width: 1px; font-size: 12pt; font-weight: 800; text-align: right"><?php echo @number_format($TotalComprovado, 2, ",", "."); ?></td>
		    <td colspan="3" style="width: 20%;">&nbsp;</td>
                </tr>
          </table>
        </td>
    </tr>
<?php else: ?>
    <tr>
        <td align="center"><em>Dados n&atilde;o informados!</em></td>
    </tr>
<?php endif; ?>
</table>
