export const SET_PERFIS_DISPONIVEIS = 'SET_PERFIS_DISPONIVEIS';
export const SET_SOLICITACOES = 'SET_SOLICITACOES';
export const SET_QUANTIDADE_SOLICITACOES = 'SET_QUANTIDADE_SOLICITACOES';
export const SET_VERSAO = 'SET_VERSAO';
export const SET_MODO_NOTURNO = 'SET_MODO_NOTURNO';
export const SET_STATUS_SIDEBAR_DIREITA = 'SET_STATUS_SIDEBAR_DIREITA';
export const SET_STATUS_SIDEBAR_ESQUERDA = 'SET_STATUS_SIDEBAR_ESQUERDA';
