export const SET_PERFIS_DISPONIVEIS = 'SET_PERFIS_DISPONIVEIS';
export const SET_USUARIO_ATIVO = 'SET_USUARIO_ATIVO';
export const SET_GRUPO_ATIVO = 'SET_GRUPO_ATIVO';
export const SET_GRUPO_SELECIONADO_INDEX = 'SET_GRUPO_SELECIONADO_INDEX';
export const SET_SOLICITACOES = 'SET_SOLICITACOES';
export const SET_VERSAO = 'SET_VERSAO';
