export const SET_PERFIS_DISPONIVEIS = 'SET_PERFIS_DISPONIVEIS';
export const SET_SOLICITACOES = 'SET_SOLICITACOES';
export const SET_QUANTIDADE_SOLICITACOES = 'SET_QUANTIDADE_SOLICITACOES';
export const SET_VERSAO = 'SET_VERSAO';
