<?php
echo $this->partial("manterpropostaincentivofiscal/inc/menu.inc.php", $this); // menu
$UpdateDivulgacao = $this->url(array('module' => 'proposta', 'controller' => 'divulgacao', 'action' => 'updatedivulgacao'));
$buscarVeiculo = $this->url(array('module' => 'proposta', 'controller' => 'divulgacao', 'action' => 'Veiculo')) . '?veiculo=' . $this->idveiculo;
?>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>"
                             title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a
                href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>"
                title="Projetos">Projetos</a></li>
        <li class="last">Divulga&ccedil;&atilde;o</li>
    </ul>
</div>
<div id="titulo">
    <div>Divulga&ccedil;&atilde;o<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<div id="conteudo">
    <form id="formDivulgacao" method="post" action="<?php echo $UpdateDivulgacao; ?>">
        <input type="hidden" name="idDivulgacao" id="idDivulgacao" value="<?php echo $this->idDivulgacao ?>"/>
        <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto; ?>">
        <table class="tabela">
            <tr class="titulo_tabela">
                <th width="50%">Pe&ccedil;a de Divulga&ccedil;&atilde;o</th>
                <th width="50%">Ve&iacute;culo de Divulga&ccedil;&atilde;o</th>
            </tr>
            <tr class="fundo">
                <td class="centro">
                    <select name="peca" id="peca" class="input_simples w350">
                        <?php foreach ($this->itensplano as $key => $itensConteudo) : ?>
                            <option value="<?php echo $key ?>" <?php if ($this->idpeca == $key) echo 'selected'; ?>><?php echo $itensConteudo ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="centro">
                    <select name="veiculo" id="veiculo" class="input_simples w150">
                        <?php foreach ($this->veiculo as $veiculoConteudo) :
                            $veiculoConteudo = array_change_key_case($veiculoConteudo);
                            ?>
                        <option value="<?php echo $veiculoConteudo['idverificacaoveiculo'] ?>" <?php if ($this->idveiculo == $veiculoConteudo['idverificacaoveiculo']) echo 'selected'; ?> ><?php echo $veiculoConteudo['veiculodescicao'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" class="btn_salvar" id="btn_salvar" value="">
                </td>
            </tr>
        </table>
    </form>
</div>
<div id="rodapeConteudo"><span></span></div>
<br clear="all"/>
<script>
    $(document).ready(function () {
        <?php if(isset($this->movimentacaoAtual) && !empty($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>
        /*$('#miolo #salvar').click(function(){
         //alert('teste');
         $('#formDivulgacao').attr('action','$UpdateDivulgacao;');
         $('#formDivulgacao').submit();
         });*/
        $('#peca').click(function () {
            jqAjaxLinkSemLoading('<?php echo $buscarVeiculo; ?>&idOpcao=' + $(this).val(), "", "veiculo");
        });
        $("#formDivulgacao").validate({
            rules: {
                peca: {required: true},
                veiculo: {required: true}
            },
            messages: {
                peca: {required: "<br>Dado obrigat&oacute;rio n&atilde;o informado"},
                veiculo: {required: "<br>Dado obrigat&oacute;rio n&atilde;o informado"}
            },
            submitHandler: function (form) {
                form.submit();
            }
        });
    });
</script>