<?php
$this->partial("manterpropostaincentivofiscal/inc/menu.inc.php");
$IncluirDivulgacao = $this->url(array('module' => 'proposta', 'controller' => 'divulgacao', 'action' => 'incluirdivulgacao'));

$buscarVeiculo   = $this->url(array('module'=>'proposta', 'controller' => 'divulgacao', 'action' => 'Veiculo'));

?>
<script>

    $(document).ready(function(){

        <?php if(isset($this->movimentacaoAtual) && $this->movimentacaoAtual != '95'): ?>
             //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
             JSBloquearAlteracaoFormulario();
        <?php endif; ?>

        /*$('#miolo #salvar').click(function(){

            //alert('teste');
            $('#formDivulgacao').attr('action','<?php echo $IncluirDivulgacao;?>');
            $('#formDivulgacao').submit();

        });*/
        $('#peca').change(function(){

            if($(this).val() != ""){
                $("#veiculo").html("<option value=''>Carregando dados...</option>");
                jqAjaxLinkSemLoading('<?php echo $buscarVeiculo; ?>?idOpcao='+$(this).val(), "", "veiculo");
            }
        });


        $("#formDivulgacao").validate({
            rules: {
                peca: { required: true } ,
                veiculo: { required: true }
            },
            messages: {
                peca: { required: "<br>Dado obrigat&oacute;rio n&atilde;o informado" },
                veiculo: { required: "<br>Dado obrigat&oacute;rio n&atilde;o informado" }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });
</script>
<style>
    label.error{ color:red; font-weight: normal; }
</style>
<!-- ========== INICIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>" title="Projetos">Projetos</a></li>
        <li class="last">Divulga&ccedil;&atilde;o</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INICIO TITULO ========== -->
<div id="titulo">
    <div>Divulga&ccedil;&atilde;o<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TITULO ========== -->

<!-- ========== INICIO CONTEUDO ========== -->
<div id="conteudo">
    <form id="formDivulgacao" name="formDivulgacao" method="post" action="<?php echo $IncluirDivulgacao;?>">
    <input type="hidden" name="idPreProjeto" id="idPreProjeto" value="<?php echo $this->idPreProjeto;?>">
    <table class="tabela">

        <tr class="titulo_tabela">
            <th width="50%">Pe&ccedil;a de Divulga&ccedil;&atilde;o</th>
            <th width="50%">Ve&iacute;culo de Divulga&ccedil;&atilde;o</th>
        </tr>

        <tr class="fundo">
            <td class="centro">
                <select name="peca" id="peca" class="input_simples w350">
                    <option value="">- Selecione -</option>
                            <?php
                            if(is_array($this->itensplano) and count($this->itensplano)>0)
                            foreach ($this->itensplano as $itensConteudo){
                                ?>
                                <option value="<?php echo $itensConteudo->idVerificacao?>"  ><?php echo utf8_encode($itensConteudo->Descricao)?></option>
                                <?php
                            }
                            ?>
                </select>
            </td>
            <td class="centro">
                <select name="veiculo"  class="input_simples w200" id="veiculo">
                    <option value="" >- Selecione uma pe&ccedil;a -</option>
                            <?php
                            if(is_array($this->veiculo) and count($this->veiculo)>0)
                            foreach ($this->veiculo as $veiculoConteudo){
                                ?>
                                <option value="<?php echo $veiculoConteudo->idVerificacao?>"  ><?php echo $veiculoConteudo->Descricao?></option>
                                <?php
                            }
                            ?>
                </select>
            </td>
        </tr>
        <tr>
            <td align="center" colspan="2">
                <input type="submit" class="btn_salvar" id="btn_salvar" value="">
            </td>
        </tr>
    </table>
</form>

</div><!-- ========== FIM CONTEUDO ========== -->

<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />
