<?php
/**
 * Cadastro de comprovantes (Acesso: PROPONENTES)
 * @author Equipe RUP - Politec
 * @since 28/04/2010
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.execucaofisicadoprojeto
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="last">Comprovação de Execução Física do Projeto</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Comprovação de Execução Física do Projeto <span class="voltar"><a href="#" onclick="redirecionar('<?php echo $this->url(array('controller' => 'execucaofisicadoprojeto', 'action' => 'buscardocumentos')); ?>?pronac=<?php echo $_GET['pronac']; ?>');">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">



	<!-- ========== INÍCIO FORMULÁRIO DE CADASTRO ========== -->
	<form name="formCadastrar" id="formCadastrar" method="post" 
		action="<?php echo $this->url(array('controller' => 'execucaofisicadoprojeto', 'action' => 'cadastrardocumentos')); ?>?pronac=<?php echo $_GET['pronac']; ?>" 
		enctype="multipart/form-data">

	<table class="tabela">
		<tr>
			<th colspan="2" class="titulo_tabela">UPLOAD DE DOCUMENTO</th>
		</tr>

		<?php foreach ($this->buscarPronac as $p): ?>
		<tr>
			<td colspan="2" class="centro">
				<p><strong>PRONAC: <?php echo $p->pronac; ?></strong></p>
				<p><strong>PROJETO: <?php echo $p->NomeProjeto; ?></strong></p>
				<input type="hidden" name="idPronac" id="idPronac" value="<?php echo $p->IdPRONAC; ?>" />
				<input type="hidden" name="pronac" id="pronac" value="<?php echo $p->pronac; ?>" />
			</td>
		</tr>
		<?php endforeach; ?>

		<tr>
			<th width="20%"><label for="tipoDocumento">Tipo Documento</label></th>
			<td>
				<select class="select_simples w600" name="tipoDocumento" id="tipoDocumento">
					<option value=""> - Selecione - </option>
	
					<?php foreach ($this->combotipodocumento as $comboTipoDocumento) : ?>
					<option value="<?php echo $comboTipoDocumento->idTipoDocumento ?>" <?php echo (isset($this->tipoDocumento) && $this->tipoDocumento == $comboTipoDocumento->idTipoDocumento) ? 'selected="selected"' : ''; ?>><?php echo $comboTipoDocumento->dsTipoDocumento ?></option>
					<?php endforeach; ?>
	
				</select>
			</td>
		</tr>
		<tr>
			<th><label for="titulos">Título</label></th>
			<td>
				<input class="input_simples w600" type="text" name="titulo" id="titulos" maxlength="100" 
					value="<?php echo isset($this->titulo) ? $this->titulo : 'Digite o título do comprovante...'; ?>" 
					onclick="limpar_campo(this, 'Digite o título do comprovante...');" onkeypress=" " 
					onblur="restaurar_campo(this, 'Digite o título do comprovante...');" onmouseout=" " />
			</td>
		</tr>
		<tr>
			<th><label for="descricao">Descrição</label></th>
			<td>
				<textarea class="textarea_simples w600" type="text" name="descricao" id="descricao" cols="60" rows="4" <?php echo $this->contadorTextarea('form.descricao', 'form.exibirContadorTextarea', 500); ?> 
					onclick="limpar_campo(this, 'Digite o texto do comprovante...');" onkeypress=" " onmousedown=" " 
					onblur="restaurar_campo(this, 'Digite o texto do comprovante...');" onmouseout=" " 
					><?php echo isset($this->descricao) ? $this->descricao : 'Digite o texto do comprovante...'; ?></textarea>
				<?php echo $this->exibirContadorTextarea('exibirContadorTextarea', 3, 500, strlen($this->descricao)); ?>
			</td>
		</tr>
		<tr>
			<th><label for="arquivo">Arquivo</label></th>
			<td>
				<input type="hidden" name="MAX_SIZE_FILE" value="10485760" />
				<input class="input_simples w600" type="file" name="arquivo" id="arquivo" />
			</td>
		</tr>
	</table>



	<!-- ========== BOTÕES DE CADASTRO E ETC ========== -->
	<table class="tabela">
		<tr>
			<td>
				<div class="float_left">
					<input type="button" class="btn_voltar" title=" Página Anterior "
						onkeypress=" " 
						onclick="redirecionar('<?php echo $this->url(array('controller' => 'execucaofisicadoprojeto', 'action' => 'buscardocumentos')); ?>?pronac=<?php echo $_GET['pronac']; ?>');" />
				</div>
	
				<div class="float_right">
					<input type="submit" title="Salvar" class="btn_salvar" value=" " />
				</div>
			</td>
		</tr>
	</table>
	
	
	
	</form>
	<!-- ========== FIM FORMULÁRIO DE CADASTRO ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />