<style>
    table caption {
        background: none repeat scroll 0 0 #ABDA5D;
        color: #3A7300;
        font-size: 11px;
        padding: 8px;
        text-transform: uppercase;
        font-weight: bold;
    }
</style>
<?php echo $this->partial('avaliaracompanhamentoprojeto/inc/menu.inc.php', $this) ?>
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->baseUrl(); ?>/comprovacao-objeto/avaliaracompanhamentoprojeto/index-tecnico" title="Lista de Relat&oacute;rios">Lista de Relat&oacute;rios</a></li>
        <li class="last">Plano de Divulga&ccedil;&atilde;o</li>
    </ul>
</div>


<div id="titulo">
    <div>Plano de Divulga&ccedil;&atilde;o <span class="voltar"><a href="<?php echo $this->baseUrl(); ?>/comprovacao-objeto/avaliaracompanhamentoprojeto/index-tecnico" title="Voltar">Voltar</a></span></div>
</div>

<div id="conteudo">
    <table class="tabela">
        <tr>
            <th align="center" width="30%">N&ordm; PRONAC:</th>
            <th align="center">Nome do Projeto:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo $this->DadosProjeto->pronac; ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProjeto; ?></td>
        </tr>
        <tr>
            <th align="center" width="30%">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tr class="linha">
            <td align="center"><?php echo (strlen($this->DadosProjeto->CNPJCPF) > 11) ? Mascara::addMaskCNPJ($this->DadosProjeto->CNPJCPF) : Mascara::addMaskCPF($this->DadosProjeto->CNPJCPF); ?></td>
            <td align="center"><?php echo $this->DadosProjeto->NomeProponente; ?></td>
        </tr>
    </table>

    <br clear="all" />

    <table class="tabela">
        <tr align="center">
            <th colspan="6">Plano de Divulga&ccedil;&atilde;o</th>
        </tr>
        <tr align="center">
            <td class="destacar bold">Pe&ccedil;a</td>
            <td class="destacar bold">Ve&iacute;culo</td>
            <td class="destacar bold" width="120px">Realizado</td>
            <td class="destacar bold" width="120px">Comprovado</td>
            <td class="destacar bold" width="120px">Arquivo</td>
            <td class="destacar bold" width="120px">Data da Anexa&ccedil;&atilde;o</td>
        </tr>
        <?php foreach ($this->PlanoDeDivulgacao as $PlanoDeDivulgacao) { ?>
        <tr>
            <td><?php echo $PlanoDeDivulgacao->Peca; ?></td>
            <td><?php echo $PlanoDeDivulgacao->Veiculo; ?></td>
            <td nowrap>
                <?php
                    if($PlanoDeDivulgacao->siPlanoDeDivulgacao == 0) {
                        echo 'Sem Informa&ccedil;&atilde;o';
                    } else if($PlanoDeDivulgacao->siPlanoDeDivulgacao == 1) {
                        echo 'N&atilde;o Realizado';
                    } else if($PlanoDeDivulgacao->siPlanoDeDivulgacao == 2) {
                        echo 'Realizado';
                    } else if($PlanoDeDivulgacao->siPlanoDeDivulgacao == 3) {
                        echo 'Realizado com outras fontes';
                    }
                ?>
            </td>
            <td align="center">
                <span id="spanArquivo<?php echo $PlanoDeDivulgacao->idPlanoDivulgacao; ?>" class="<?php echo($PlanoDeDivulgacao->siPlanoDeDivulgacao < 2)?'sumir':''; ?>">
                    <img src="<?php  echo $this->baseUrl().'/public/img/passed.gif'; ?>" />
                </span>
                <input type="file" class="sumir" id="arquivo<?php echo $PlanoDeDivulgacao->idPlanoDivulgacao; ?>" name="arquivo<?php echo $PlanoDeDivulgacao->idPlanoDivulgacao; ?>" />
            </td>
            <td nowrap><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $PlanoDeDivulgacao->idArquivo; ?>"><?php echo $PlanoDeDivulgacao->nmArquivo; ?></a></td>
            <td><?php echo !empty($PlanoDeDivulgacao->dtEnvio) ? Data::tratarDataZend($PlanoDeDivulgacao->dtEnvio, 'Brasileira', true) : ''; ?></td>
        </tr>
        <?php } ?>
    </table>

    <br clear="all" />

    <table class="tabela">
    <caption>Marcas Anexadas</caption>
    <?php if(count($this->marcas) > 0) : ?>
    <tr>
        <td class="destacar bold">Observa&ccedil;&otilde;es</td>
        <td class="destacar bold">Arquivo</td>
        <td class="destacar bold">Dt. Envio</td>
        <td class="destacar bold">Estado</td>
    </tr>
    <?php foreach ($this->marcas as $marca) : ?>
        <tr>
            <td><?php echo $marca->dsDocumento; ?></td>
            <td><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $marca->idArquivo; ?>"><?php echo $marca->nmArquivo ?></a></td>
            <td><?php echo Data::tratarDataZend($marca->dtEnvio, 'Brasileira'); ?></td>
            <td>
                <?php
                    if($marca->stAtivoDocumentoProjeto == 'D'){
                        echo 'Deferido';
                    } else if($marca->stAtivoDocumentoProjeto == 'I'){
                        echo 'Indeferido';
                    } else if($marca->stAtivoDocumentoProjeto == 'E'){
                        echo 'Enviado';
                    } else {
                        echo '';
                    }
                ?>
            </td>
        </tr>
    <?php
            endforeach;
        else:
    ?>
        <tr><td align="center">Nenhum registro encontrado</td></tr>
    <?php endif; ?>
    </table>
    <br clear="all" />
</div>
