export const SET_REGISTROS_TABELA = 'SET_REGISTROS_TABELA';
export const SET_REGISTRO_TABELA = 'SET_REGISTRO_TABELA';
export const SET_REGISTRO_ATIVO = 'SET_REGISTRO_ATIVO';
export const ATUALIZAR_REGISTRO_TABELA = 'ATUALIZAR_REGISTRO_TABELA';
export const REMOVER_REGISTRO = 'REMOVER_REGISTRO';
export const GET_CONSOLIDACAO_PARECER = 'GET_CONSOLIDACAO_PARECER';
export const MOCK_AVALIACAO_RESULTADOS = 'MOCK_AVALIACAO_RESULTADOS';
export const DESTINATARIOS_ENCAMINHAMENTO = 'DESTINATARIOS_ENCAMINHAMENTO';