<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINISTÉRIO DA CULTURA<br>
    Secretaria de Fomento e Incentivo à Cultura<br>
    Esplanada dos Ministérios, Bloco "B"<br>
    Brasília/DF - CEP 70.068-900
</p>
<div>
    <p lang="pt-BR" align="LEFT">
        <strong>Manifestação Final do Técnico de Prestação de Contas: {manifestacaoParecerTecnico}</strong>
    </p>
    <p lang="pt-BR" align="LEFT">
        <strong>Parecer Técnico :</strong></br>
        {parecerDoTecnico}
    </p>
</div>