<div class="container-fluid" id="vue-container">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Transfer&ecirc;ncia de recursos</h1>
		    
                    <?php
                    gerarNovoBreadCrumb(array(
                    array('Readequa&ccedil;&atilde;o' => [
                    'module' => 'readequacao',
                    'controller' => 'transferencia-recursos',
                    'action', 'index']
                    ),
                    array('Transfer&ecirc;ncia de recursos' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s3">
                            <b>Pronac: </b>{{ projeto.pronac }}<br>
                        </div>
                        <div class="col s3">
                            <b>Projeto: </b><span v-html="projeto.nomeProjeto"></span>
                        </div>
                        <div class="col s3">
                            <b>Vl. a Comprovar: </b>{{ projeto.valorComprovar }}
                        </div>
                        <div class="col s3">
                            <b>Saldo dispon&iacute;vel: </b>R$ {{ saldoDisponivel }}
                        </div>
                    </div>
		</div>
            </div>
	    
	    <div class="card">		
		<div class="card-content">
		    <h3>Solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o</h3>
		    <div class="row">
			<div class="input-field col s12">
			    <textarea
				id="textarea1"
				class="materialize-textarea"
				v-model="readequacao.justificativa"></textarea>
			    <label for="textarea1">Justificativa</label>
			</div>
			<div class="file-field input-field">
			    <div class="btn">
				<span>File</span>
				<input type="file">
			    </div>
			    <div class="file-path-wrapper">
				<input class="file-path validate" type="text">
			    </div>
			</div>
			<div class="center-align padding20 col s3">
			    <a href="javascript:void(0)"
			       v-on:click="salvarReadequacao"
			       class="btn">Salvar</a>
			</div>
			<div class="center-align padding20 col s3">
			    <a href="javascript:void(0)"
			       v-on:click="finalizarReadequacao"
			       v-show="disponivelFinalizar"
			       class="btn">Finalizar</a>
			</div>

		    </div>
		</div>
	    </div>
	    
	    <div class="card"
		 v-show="disponivelAdicionarRecebedores">
		<div class="card-content">
		    <table>
			<thead>
			    <th>Pronac</th>
			    <th>Nome do projeto</th>
			    <th>Tipo da transfer&ecirc;ncia</th>
			    <th>Vl. transfer&ecirc;ncia</th>
			</thead>
			<tbody>
			    <tr v-for="(projeto, index) in projetosRecebedores">
				<td>{{ projeto.idPronac }}</td>
				<td>{{ projeto.nomeProjeto}}</td>
				<td>{{ projeto.tipoTransferencia}}</td>
				<td>R$ {{ projeto.valorRecebido}}</td>
				<td>
				    <a href="javascript:void(0)"
				       v-on:click="excluirRecebedor(index)"
				       class="btn small">
					<i class="material-icons">delete</i>					
				    </a>
				</td>
			    </tr>
			</tbody>
			<tfoot>
			    <tr>
				<td colspan="2"></td>
				<td class="right">Total transferido: </td>
				<td>R$ {{ totalRecebido }} </td>
			    </tr>
			</tfoot>
		    </table>
		    
		    <form class="row">
			<div class="col s3">
			    <label>Projeto recebedor</label>
			    <select class="browser-default" v-model="projetoRecebedor.idPronac">
				<option value="" disabled selected>Selecione o projeto</option>
				<option value="173321">173321 - Projeto abc</option>
				<option value="163321">163321 - Projeto def</option>
				<option value="153321">153321 - Projeto gehehe</option>
			    </select>
			</div>
			<div class="col s3">
			    <label>Tipo da transfer&ecirc;ncia</label>
			    <select class="browser-default" v-model="projetoRecebedor.tipoTransferencia">
				<option value="" disabled selected>Selecione o tipo da transfer&ecirc;ncia</option>
				<option value="1">N&atilde;o homologados</option>
				<option value="2">Homologados</option>
				<option value="3">Recursos remanescentes</option>
			    </select>
			</div>
 			<div class="input-field col s3">
			    <input-money
                                v-on:ev="projetoRecebedor.valorRecebido = $event"
                                v-bind:value="projetoRecebedor.valorRecebido">
			    </input-money>
			    <label for="valor_recebido">Valor recebido</label>
			</div>		
			<div class="center-align padding20 col s3">
			    <a href="javascript:void(0)"
			       v-on:click="incluirRecebedor"
			       class="btn">Adicionar recebedor</a>
			</div>
		    </form>
		</div>
	    </div>
        </div>
    </div>
</div>
<script src="/public/js/vue.js" type="text/javascript"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<script src="/public/scripts/plugins/numeral.js" type="text/javascript"></script>
<script src="/public/scripts/mixins/utils.vue.js" type="text/javascript"></script>
<script src="/public/scripts/components/input-money.vue.js" type="text/javascript"></script>
<script src="/public/scripts/readequacao/readequacao-transferencia-recursos.vue.js" type="text/javascript"></script>
