<!-- vendor -->
<script src="/public/js/vue.js"></script>
<script src="/public/scripts/prestacao-contas/views/avaliacao-amostragem.vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/public/js/componentes/sl-btn-visualizar.js" ></script>
<script type="text/javascript" src="/public/js/componentes/sl-collapse-visualizar.js" ></script>
<script src="/public/scripts/diligencia/diligencia/cadastrar.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-produtos.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-etapas.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-ufs.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-cidades.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-itens.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/planilha/sl-planilha-button.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/button-scroll-top.vue.js"></script>
<!-- vendor -->


<div class="container-fluid" id="vue-container">
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10">
                <h1>Presta&ccedil;&atilde;o de Contas: Avalia&ccedil;&atilde;o por Amostragem</h1>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="javascript:voltar();" title="Página Anterior"title="Página Anterior" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">keyboard_return</i>
                </a>
            </div>
        </div>
    </div>
    <?php echo $this->partial('partials/card-projeto.phtml', 'prestacao-contas', $this); ?>
    <div class="row" id="app">
        <div class="col s12 m12">
            <avaliacao-amostragem idpronac="<?php echo $this->idPronac ?>" :avaliacao="<?php echo $this->tipoAvaliacao ?>"></avaliacao-amostragem>
        </div>
    </div>
    <?php echo $this->partial('partials/menu-fixo.phtml', 'prestacao-contas', $this); ?>
</div>

<script type="text/javascript">
    var bus = new Vue({})

    var app = new Vue({
        el: '#app',
        methods: {
            iniciarCollapsible: function () {
                $3('.collapsible').each(function () {
                    $3(this).collapsible();
                });
            }
        }
    })
</script>
<!-- script src="/public/scripts/projeto/salic-projeto-identificacao.vue.js" type="text/javascript"></script-->

<script>
$.validator.addMethod("dependeSituacao", function(value, element, params) {
    console.log($(element).val());

    console.log($('#situacao_1_' + params.id).is(':checked'));
    if ($('#situacao_1_' + params.id).is(':checked')) {
        return true;
    }
    if ($('#situacao_2_' + params.id).is(':checked') && $(element).val() == '' ) {
        return false;
    }
    return true;
}, "Por Favor preeencher: Ocorrencia");

$(document).ready(function(){
    $("form").each( function(index, value)
    {
      let id = this.id;
      /* console.log(id); */
        $(this).validate({
            rules: {
                justificativa: {
                    dependeSituacao: { id : id},
                },
                situacao: {
                  required: true,
                }
            },
            messages:{
                situacao: {
                    required: 'Por Favor preeencher: Situa&ccedil;&atilde;o'
                }
            },
            submitHandler: function (form) {
                let f = form;

                let id = f.idComprovantePagamento.value;
                let situacao = f.situacao.value;

                $3.ajax({
                    url: '/prestacao-contas/prestacao-contas/salvar-analise',
                    data: $3(f).formSerialize()
                })
                .done( function(data) {
                    Materialize.toast('Salvo!!', 4000, 'green darken-1');
                    if (situacao == 1){
                        $3('#head_' + id).removeClass('red lighten-3 grey lighten-2').addClass('green lighten-3');
                        $3('#icon_' + id).text('check_circle');
                    }

                    if (situacao == 3){
                        $3('#head_' + id).removeClass('green lighten-3 grey lighten-2').addClass('red lighten-3');
                        $3('#icon_' + id).text('block');
                    }
                });
            },
            errorPlacement: function(error, element) {
                Materialize.toast(error[0].textContent, 4000, 'red accent-1');
            },
            onkeyup: false,
            onclick: false,
            onfocusout: false,
        });
    })
});
</script>
