<script src="/public/js/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.4/numeral.min.js" type="text/javascript"></script>
<script src="/public/scripts/prestacao-contas/components/dados-projeto.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/item.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/comprovante-form.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/page-title.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/comprovante-table.vue.js"></script>
<script src="/public/scripts/prestacao-contas/components/comprovantes.vue.js"></script>
<script src="/public/js/moment.js"></script>

<div class="container-fluid" id="app-comprovante">
    <page-title></page-title>
    <dados-projeto idpronac="<?php echo $this->idpronac ?>"></dados-projeto>

    <item
        idpronac="<?php echo $this->idpronac ?>"
        uf="<?php echo $this->uf ?>"
        etapa="<?php echo $this->cdetapa ?>"
        cidade="<?php echo $this->cdcidade ?>"
        produto="<?php echo $this->cdproduto ?>"
        idplanilhaitens="<?php echo $this->idPlanilhaItens ?>">
    </item>



    <div class="card ">
        <div v-show="visivelForm" class="card-content ">
          <span class="card-title">Comprovante de Pagamento</span>
            <sl-comprovar-form
                url="/prestacao-contas/gerenciar/cadastrar"
                tipoform="cadastro"
                item="<?php echo $this->idPlanilhaItens ?>"
            ></sl-comprovar-form>
        </div>
    </div>
    <comprovantes
        idpronac="<?php echo $this->idpronac ?>"
        produto="<?php echo $this->cdproduto ?>"
        stitemavaliado="<?php echo $this->idPlanilhaItens ?>"
        uf="<?php echo $this->uf ?>"
        idmunicipio="<?php echo $this->cdcidade ?>"
        etapa="<?php echo $this->cdetapa ?>"
        componenteform="comprovante-form"
    ></comprovantes>

    <div class="fixed-action-btn">
        <a class="btn-floating btn-large"
                v-on:click.prevent="visivel()">
          <i class="large material-icons">add</i>
        </a>
    </div>
</div>

<script>

    const appComprovante = new Vue({
    components: {
        'comprovantes' : comprovantes
    },
    data : {
        visivelForm: false
    },
    methods: {
        visivel: function() {
            console.log('teste 11');
            this.visivelForm  = (!this.visivelForm);
        }
    }
    }).$mount('#app-comprovante');

</script>
