<style>
    .switch label .lever{
        background-color: #4CAF50;
    }
    .switch label .lever:after{
        background-color: #2c7930;
    }
    .switch label input[type=checkbox]:checked + .lever{
        background-color: #F44336;
    }
    .switch label input[type=checkbox]:checked + .lever:after{
        background-color: #d43024;
    }
</style>

<div class="container-fluid">
    <div class="page-title">
	<div class="row">
	    <div class="col s12 m9 l10">
		<h1>Listar Solicita&ccedil;&otilde;es de desarquivamento</h1>
	    </div>
	    <div class="col s12 m3 l2 right-align">
		<a href="javascript:voltar();" title="Página Anterior"title="Página Anterior" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">keyboard_return</i>
		</a>
	    </div>
	</div>
    </div>
    <div class="content">
        <div class="row">
            <div class="col s12 m12 l12">
            <div  id="propostasCadastradas">
                <div class="card z-depth-2">
                    <ul class="collapsible collapsible-accordion" data-collapsible="accordion">
                        <li class="">
                            <div class="collapsible-header active"><i class="material-icons">thumbs_up_down</i>Não avaliadas</div>
                            <div class="collapsible-body">
                                <span>
                                    <table id="tabelaSolicitacoesDesarquivamentoAvaliacao" style="width: 100%">
                                        <thead>
                                            <tr>
                                                <th>Proposta</th>
                                                <th>Nome</th>
                                                <th>Data da Solicita&ccedil;&atilde;o</th>
                                                <th>Analisar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </span>
                            </div>
                        </li>
                        <li class="">
                            <div class="collapsible-header"><i class="material-icons">thumb_up</i>Aprovadas</div>
                            <div class="collapsible-body">
                                <span>
                                    <table id="tabelaSolicitacoesDesarquivamentoAprovadas" style="width: 100%">
                                        <thead>
                                            <tr>
                                                <th>Proposta</th>
                                                <th>Nome</th>
                                                <th>Data da Solicita&ccedil;&atilde;o</th>
                                                <th>Visualizar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </span>
                            </div>
                        </li>
                            <li class="">
                                <div class="collapsible-header"><i class="material-icons">thumb_down</i>Reprovadas</div>
                                <div class="collapsible-body">
                                    <span>
                                        <table id="tabelaSolicitacoesDesarquivamentoReprovadas" style="width: 100%">
                                            <thead>
                                                <tr>
                                                    <th>Proposta</th>
                                                    <th>Nome</th>
                                                    <th>Data da Solicita&ccedil;&atilde;o</th>
                                                    <th>Visualizar</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
	    </div>
	</div>
</div>

<div id="modal_solicitacao" class="modal bottom-sheet" style="max-height:95%; height:95%">
    <div class="modal-content">
      <div class="row">
        <div class=" col s12">
          <h3>Analisar Desarquivamento</h3>
          <h4 id="titulo_proposta"></h4>
            <div class="card">
                <div class="card-content ">
                    <span class="card-title">Motivo Arquivamento</span>
                    <p id="motivoarquivamento"></p>
                </div>
            </div>
            <div class="card">
                <div class="card-content ">
                  <span class="card-title">Solicita&ccedil;&atilde;o Desarquivamento</span>
                  <p id="solicitacao"></p>
                </div>
            </div>
            <div class="card hoverable">
                <div class="card-content ">
                    <span class="card-title">Avaliação</span>
                    <div class="row s12">
                        <div class="switch">
                            <label>
                                Aprovar
                                <input class="switch_aprovacao" type="checkbox">
                                <span class="lever"></span>
                                Reprovar
                            </label>
                        </div>
                    </div>
                    <textarea cols="80" id="MotivoDesarquivamento"
                              name="MotivoDesarquivamento"
                              class="textarea"
                              style="width: 99%">
                    </textarea>
                </div>
            </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <input type="hidden" id="idpreprojeto" value="">
       <a href="#!" id="analisar" class="waves-effect waves-light btn"><i class="material-icons right">gavel</i>enviar</a>

       <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat red-text">Cancelar</a>
    </div>
</div>
<div id="modal_dados" class="modal bottom-sheet" style="max-height:95%; height:95%">
    <div class="modal-content">
        <div class="row">
            <div class=" col s12">
                <h3>Analisar Desarquivamento</h3>
                <h4 class="titulo_proposta_consulta"></h4>
                <div class="card">
                    <div class="card-content ">
                        <span class="card-title">Motivo Arquivamento</span>
                        <p class="motivoarquivamento_consulta"></p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content ">
                        <span class="card-title">Solicita&ccedil;&atilde;o Desarquivamento</span>
                        <p class="solicitacao_consulta"></p>
                    </div>
                </div>
                <div class="card avaliacao">
                    <div class="card-content">
                        <span class="card-title">Avalia&ccedil;&atilde;o</span>
                        <p class="avaliacao_consulta"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat red-text">Fechar</a>
    </div>
</div>
<script type="text/javascript">
 $(document).ready(function () {
     $("#MotivoDesarquivamento").editorRico({
         altura: 200,
         maxchar: 5000,
         isLimitarCarateres : true
     });

     $(".switch").find("input[type=checkbox]").on("change",function() {
         if($('.switch_aprovacao').prop('checked')){

             $(".mce-tinymce").show('slow');
             $("#contadorRicoMotivoDesarquivamento").show('slow');

         }else{
             $(".mce-tinymce").hide('slow');
             $("#contadorRicoMotivoDesarquivamento").hide('slow');
         }
     });

     $('.expandir').live('click', function () {
         var elemento = $(this),
             idAgente = elemento.attr('idAgente');

         $('.mostraProposta_' + idAgente).toggle();
         if (elemento.hasClass('btn_adicionar')) {
             elemento.addClass('btn_remover');
             elemento.removeClass('btn_adicionar');
         } else {
             elemento.addClass('btn_adicionar');
             elemento.removeClass('btn_remover');
         }
     });

 });
</script>

<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
<script type="text/javascript">
 (function ($) {
     $(document).ready(function () {
         $3('.modal').modal();

         var tableAvaliacao =  $('#tabelaSolicitacoesDesarquivamentoAvaliacao').DataTable(
             {
                 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json",
                 },
                 "lengthChange": true,
                 "ajax": {
                     url: "/proposta/pre-projeto-arquivado/listar-solicitacoes-aguardando-avaliacao",
                     data: {},
                     type: "POST"
                 },
                 "processing": true,
                 "serverSide": true,
                 "aoColumnDefs": [
                     {'bSortable': false, 'aTargets': [1,3]}
                 ],
                 "order": [[ 2, 'desc' ]],
                 "columns": [
                     {
                         data: null,
                         "name": "idpreprojeto",
                         render: function (data, type, row) {
                             return '<a data-ajax-modal="/admissibilidade/admissibilidade/exibirpropostacultural-ajax/idPreProjeto/' + data.idpreprojeto + '" href="javascript:void(0);" data-position="top" data-delay="50" data-ajax-modal-height="96%" data-ajax-modal-width="98%" data-tooltip="Visualizar proposta" class="waves-effect waves-teal btn small white tooltipped black-text" >' + data.idpreprojeto + '</a>'
                         }
                     },
                     {
                         "name": "nomeprojeto",
                         "data": "nomeprojeto"
                     },
                     {
                         "name": "dtSolicitacaoDesarquivamento",
                         "data": "dtSolicitacaoDesarquivamento"
                     },
                     {
                        data: null,
                        "name": "idpreprojeto",
                        render: function (data, type, row) {
                            var motivo = data.MotivoArquivamento;
                            motivo = motivo.replace(/\"/g,'&#34;'); // aspa dupla
                            motivo = motivo.replace(/\'/g,'&#39;'); // aspa simples
                            motivo = motivo.replace(/\n/g,'<br/>');
                            data.MotivoArquivamento = motivo;

                            var solicitacao = data.SolicitacaoDesarquivamento;
                            solicitacao = solicitacao.replace(/\"/g,'&#34;'); // aspa dupla
                            solicitacao = solicitacao.replace(/\n/g,'<br/>');
                            solicitacao = solicitacao.replace(/\'/g,'&#39;'); // aspa simples
                            data.SolicitacaoDesarquivamento = solicitacao;

                            return '<button data-target="modal_solicitacao" class="modal-trigger btn waves-effect waves-dark white black-text small"' +
                                    'data-idpreprojeto="' + data.idpreprojeto + '"' +
                                    'data-solicitacao="' + data.SolicitacaoDesarquivamento + '"' +
                                    'data-motivoarquivamento="' + data.MotivoArquivamento + '"' +
                                    'data-nome="' + data.nomeprojeto + '">' +
                                    '<i class="material-icons">gavel</i>' +
                                    '</button>'
                        }
                     }
                 ]
             }
         );

         var tableAprovadas =  $('#tabelaSolicitacoesDesarquivamentoAprovadas').DataTable(
             {
                 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                 },
                 "lengthChange": true,
                 "ajax": {
                     url: "/proposta/pre-projeto-arquivado/listar-solicitacoes-aprovadas",
                     data: {},
                     type: "POST"
                 },
                 "processing": true,
                 "serverSide": true,
                 "aoColumnDefs": [
                     {'bSortable': false, 'aTargets': [1,3]}
                 ],
                 "order": [[ 2, 'desc' ]],
                 "columns": [
                     {
                         data: null,
                         "name": "idpreprojeto",
                         render: function (data, type, row) {
                             return '<a data-ajax-modal="/admissibilidade/admissibilidade/exibirpropostacultural-ajax/idPreProjeto/' + data.idpreprojeto + '" href="javascript:void(0);" data-position="top" data-delay="50" data-ajax-modal-height="96%" data-ajax-modal-width="98%" data-tooltip="Visualizar proposta" class="waves-effect waves-teal btn small white tooltipped black-text" >' + data.idpreprojeto + '</a>'
                         }
                     },
                     {
                         "name": "nomeprojeto",
                         "data": "nomeprojeto"
                     },
                     {
                         "name": "dtSolicitacaoDesarquivamento",
                         "data": "dtSolicitacaoDesarquivamento"
                     },
                     {
                         data: null,
                         "name": "idpreprojeto",
                         render: function (data, type, row) {
                             var motivo = data.MotivoArquivamento;
                             motivo = motivo.replace(/\"/g,'&#34;'); // aspa dupla
                             motivo = motivo.replace(/\'/g,'&#39;'); // aspa simples
                             motivo = motivo.replace(/\n/g,'<br/>');
                             data.MotivoArquivamento = motivo;

                             var solicitacao = data.SolicitacaoDesarquivamento;
                             solicitacao = solicitacao.replace(/\"/g,'&#34;'); // aspa dupla
                             solicitacao = solicitacao.replace(/\n/g,'<br/>');
                             solicitacao = solicitacao.replace(/\'/g,'&#39;'); // aspa simples
                             data.SolicitacaoDesarquivamento = solicitacao;

                             return '<button data-target="modal_dados" class=" modal-trigger btn waves-effect waves-dark white black-text small"' +
                                 'data-idpreprojeto="' + data.idpreprojeto + '"' +
                                 'data-solicitacao="' + data.SolicitacaoDesarquivamento + '"' +
                                 'data-motivoarquivamento="' + data.MotivoArquivamento + '"' +
                                 'data-nome="' + data.nomeprojeto + '">' +
                                 '<i class="material-icons">remove_red_eye</i>' +
                                 '</button>'
                         }
                     }
                 ]
             }
         );

         var tableReprovadas =  $('#tabelaSolicitacoesDesarquivamentoReprovadas').DataTable(
             {
                 "language": {
                     "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json",
                 },
                 "lengthChange": true,
                 "ajax": {
                     url: "/proposta/pre-projeto-arquivado/listar-solicitacoes-reprovadas",
                     data: {},
                     type: "POST"
                 },
                 "processing": true,
                 "serverSide": true,
                 "aoColumnDefs": [
                     {'bSortable': false, 'aTargets': [1,3]}
                 ],
                 "order": [[ 2, 'desc' ]],
                 "columns": [
                     {
                         data: null,
                         "name": "idpreprojeto",
                         render: function (data, type, row) {
                             return '<a data-ajax-modal="/admissibilidade/admissibilidade/exibirpropostacultural-ajax/idPreProjeto/' + data.idpreprojeto + '" href="javascript:void(0);" data-position="top" data-delay="50" data-ajax-modal-height="96%" data-ajax-modal-width="98%" data-tooltip="Visualizar proposta" class="waves-effect waves-teal btn small white tooltipped black-text" >' + data.idpreprojeto + '</a>'
                         }
                     },
                     {
                         "name": "nomeprojeto",
                         "data": "nomeprojeto"
                     },
                     {
                         "name": "dtSolicitacaoDesarquivamento",
                         "data": "dtSolicitacaoDesarquivamento"
                     },
                     {
                         data: null,
                         "name": "idpreprojeto",
                         render: function (data, type, row) {
                             var motivo = data.MotivoArquivamento;
                             motivo = motivo.replace(/\"/g,'&#34;'); // aspa dupla
                             motivo = motivo.replace(/\'/g,'&#39;'); // aspa simples
                             motivo = motivo.replace(/\n/g,'<br/>');
                             data.MotivoArquivamento = motivo;

                             var solicitacao = data.SolicitacaoDesarquivamento;
                             solicitacao = solicitacao.replace(/\"/g,'&#34;'); // aspa dupla
                             solicitacao = solicitacao.replace(/\n/g,'<br/>');
                             solicitacao = solicitacao.replace(/\'/g,'&#39;'); // aspa simples
                             data.SolicitacaoDesarquivamento = solicitacao;

                             var avaliacao = data.Avaliacao;
                             avaliacao = avaliacao.replace(/\"/g,'&#34;'); // aspa dupla
                             avaliacao = avaliacao.replace(/\n/g,'<br/>');
                             avaliacao = avaliacao.replace(/\'/g,'&#39;'); // aspa simples
                             data.Avaliacao = avaliacao;

                             return '<button data-target="modal_dados" class=" modal-trigger btn waves-effect waves-dark white black-text small"' +
                                 'data-idpreprojeto="' + data.idpreprojeto + '"' +
                                 'data-solicitacao="' + data.SolicitacaoDesarquivamento + '"' +
                                 'data-motivoarquivamento="' + data.MotivoArquivamento + '"' +
                                 'data-avaliacao="' + data.Avaliacao + '"' +
                                 'data-nome="' + data.nomeprojeto + '">' +
                                 '<i class="material-icons">remove_red_eye</i>' +
                                 '</button>'
                         }
                     }
                 ]
             }
         );

         $("tbody").on('click','button', function () {
             let idpreprojeto = $3(this).data('idpreprojeto');
             let nome = $3(this).data('nome');
             let motivoarquivamento = $3(this).data('motivoarquivamento');
             let solicitacao = $3(this).data('solicitacao');
             let avaliacao = $3(this).data('avaliacao');

             $(".mce-tinymce").hide();
             $("#contadorRicoMotivoDesarquivamento").hide();

             $3('.avaliacao').show();
             if (avaliacao == null) {
                 $3('.avaliacao').hide();
             }

             $('.switch_aprovacao').prop('checked', false);
             tinyMCE.activeEditor.setContent('');


             $3('#idpreprojeto').val(idpreprojeto);
             $3('#titulo_proposta').text(idpreprojeto + ' ' + nome);
             $3('#motivoarquivamento').html(motivoarquivamento);
             $3('#solicitacao').html(solicitacao);

             $3('.idpreprojeto_consulta').val(idpreprojeto);
             $3('.titulo_proposta_consulta').text(idpreprojeto + ' ' + nome);
             $3('.motivoarquivamento_consulta').html(motivoarquivamento);
             $3('.solicitacao_consulta').html(solicitacao);
             $3('.avaliacao_consulta').html(avaliacao);
         });

        $3("#analisar").on('click', function () {

            if($('.switch_aprovacao').prop('checked')){
                $3.ajax({
                    url:'/proposta/pre-projeto-arquivado/avaliar-arquivamento',
                    data: {
                        idpreprojeto: $3('#idpreprojeto').val(),
                        Avaliacao: tinyMCE.get('MotivoDesarquivamento').getContent(),
                        stDecisao: 0,
                        stEstado: 0,
                        avaliacaoFinal: true
                    },
                    method:'POST'
                }).done(function(data) {
                    let message_type = (data.success) ? 'green' : 'red';
                    Materialize.toast(data.message, 4000, message_type+' white-text');
                    tableAvaliacao.ajax.reload();
                    tableAprovadas.ajax.reload();
                    tableReprovadas.ajax.reload();
                    if(data.success){
                        $3('#modal_solicitacao').modal('close');
                    }
                });
            } else {
                $3.ajax({
                    url:'/proposta/pre-projeto-arquivado/avaliar-arquivamento',
                    data: {
                        idpreprojeto: $3('#idpreprojeto').val(),
                        stDecisao: 1,
                        stEstado: 0,
                        avaliacaoFinal: true
                    },
                    method:'POST'
                }).done(function(data) {
                    let message_type = (data.success) ? 'green' : 'red';

                    Materialize.toast(data.message, 4000, message_type+' white-text');
                    tableAvaliacao.ajax.reload();
                    tableAprovadas.ajax.reload();
                    tableReprovadas.ajax.reload();
                    if(data.success){
                        $3('#modal_solicitacao').modal('close');
                        $3.ajax({
                            url:'/proposta/pre-projeto/update',
                            data: {
                                idPreProjeto: $3('#idpreprojeto').val(),
                                stEstado: 1
                            },
                            method:'POST'
                        }).done(function(data) {
                        });
                    }
                });
            }
        });

     });
 }($.noConflict(true)));
</script>
