<?php
/**
 * Solicitação de Recurso
 * @author Equipe RUP - Politec
 * @since 20/07/2010
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.recurso
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para Início">Início</a></li>
        <li class="last">Detalhar Recurso</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Detalhar Recurso <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <?php foreach ($this->dadosRecurso as $dadosRecurso) { ?>
    <table class="tabela">
        <tr>
            <th colspan="2">Solicitação</th>
        </tr>
        <tr>
            <td class="destacar bold" align="right" width="100">Data do Recurso</td>
            <td><?php echo Data::tratarDataZend($dadosRecurso->dtSolicitacaoRecurso, 'Brasileiro'); ?></td>
        </tr>
        <tr>
            <td class="destacar bold" align="right">Solicitação</td>
            <td><textarea class="textarea_simples" readonly="readonly" rows="" cols="" style="width: 99%"><?php echo strip_tags(trim($dadosRecurso->dsSolicitacaoRecurso)); ?></textarea></td>
        </tr>
    </table>

    <?php if($dadosRecurso->stAtendimento != 'N'){ ?>
    <table class="tabela">
        <tr>
            <th>Resposta</th>
        </tr>
        <tr>
            <td>Resposta</td>
        </tr>
    </table>
    <?php } ?>

    <?php } ?>
</div>
<!-- ========== FIM CONTEÚDO ========== -->


<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />