<?php
/**
 * Projetos Indeferidos
 * @author Equipe RUP - Politec
 * @since 20/07/2010
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.recurso
 * @copyright © 2010 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para Início">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'recurso')); ?>" title="Ir para Recurso">Recurso</a></li>
		<li class="last">Projetos Indeferidos</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Projetos Indeferidos <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<br />

	<!-- ========== INÍCIO TABELA RECURSO ========== -->
	<table class="tabela">
		<tr>
			<th>Pronac</th>
			<th>Nome do Projeto</th>
		</tr>

		<?php $tbinferidos = $this->recursoindeferidos; ?>
		<tr>
			<td><?php echo $this->escape($tbinferidos[0]->pronac);?></td>
			<td><?php echo $this->escape($tbinferidos[0]->NomeProjeto);?></td>
		</tr>

		<tr>
			<th>CNPJ/CPF</th>
			<th>Nome do Proponente</th>
		</tr>

		<?php $tbinferidos = $this->recursoindeferidos; ?>
		<tr>
			<td><?php echo (!empty($tbinferidos[0]->CgcCpf)) ? Validacao::mascaraCPFCNPJ($this->escape($tbinferidos[0]->CgcCpf)) : "<em>Não informado.</em>"; ?></td>
			<td><?php echo $this->escape($tbinferidos[0]->NomeProponente);?></td>
		</tr>
	</table>

	<br />

	<table class="tabela">
		<tr>
			<th>Recurso</th>
		</tr>

		<?php $tbinferidos = $this->recursoindeferidos; ?>
		<tr>
			<td><?php echo html_entity_decode($tbinferidos[0]->dsSolicitacaoRecurso);?></td>
		</tr>
	</table>
	<!-- ========== FIM TABELA RECURSO ========== -->



	<br />



	<!-- ========== INÍCIO FORMULÁRIO JUSTIFICATIVA ========== -->
	<div id="dialog-alert" class="sumir">Por favor, digite sua justificativa!</div>
	<form name="form" id="form" action="<?php echo $this->url(array('controller' => 'recurso', 'action' => 'indeferidos')); ?>?idPronac=<?php echo $_GET['idPronac']; ?>" method="post">
	<table class="tabela">
		<tr>
			<th>Justificativa</th>
		</tr>
		<tr>
			<td align="center">

				<!-- ========== EDITOR ========== -->
				<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/ckeditor.js"></script>
				<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.js"></script>
				<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/js/ckeditor/_samples/sample.css" />

				<label for="justificativa"> </label>
				<textarea cols="80" id="justificativa" name="justificativa" rows="10">&lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;p&gt;Digite seu texto aqui...&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</textarea>
				<script type="text/javascript">
					CKEDITOR.replaceAll();
				    $('#form').submit(function()
					{
						var texto = CKEDITOR.instances['justificativa'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,'');

						if (texto.length > 0 && texto != 'Digiteseutextoaqui...')
						{
							// verifica se o usuário clicou no botão
							 
							$('#justificativa').val(CKEDITOR.instances['justificativa'].getData());
						}
						else
						{
							$("#dialog").dialog("destroy");
							$("#dialog-alert").dialog
							({
								modal: true,
								draggable: false,
								resizable: false,
								closeOnEscape: false,
								title: 'Dados obrigatórios não informados!',
								buttons:
								{
									Ok:function()
									{
										$(this).dialog('close');
									}
								}
							});
							$('.ui-dialog-titlebar-close').remove();
							return false;
				        }
				    });
				</script>
				<input type="hidden" name="idRecurso" id="idRecurso" value="<?php echo $tbinferidos[0]->idRecurso; ?>" />
				<input type="hidden" name="idPronac" id="idPronac" value="<?php echo $_GET['idPronac']; ?>" />
				<br />
				<p align="center">
					<input type="radio" name="stAtendimento" id="D" value="D" checked="checked" /> <label for="D">Deferir</label> &nbsp;&nbsp;&nbsp; 
					<input type="radio" name="stAtendimento" id="I" value="I" /> <label for="I">Indeferir</label>
				</p>
				<br />
				<p>
					<input type="button" class="btn" value=" Análise do Projeto " onclick="redirecionar('<?php echo $this->url(array('controller' => 'realizaranaliseprojeto', 'action' => 'parecerconsolidado', 'idpronac' => $_GET['idPronac'])); ?>');" onkeypress=" " /> &nbsp; 
					<input type="submit" class="btn" value=" Salvar " /> &nbsp; 

					<input type="reset" class="btn" value=" Cancelar " onclick="redirecionar('<?php echo $this->url(array('controller' => 'recurso', 'action' => 'index')); ?>?idPronac=<?php echo $_GET['idPronac']; ?>');" onkeypress=" " /> &nbsp; 
				</p>
			</td>
		</tr>
	</table>
	</form>
	<!-- ========== FIM FORMULÁRIO JUSTIFICATIVA ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />