<main>
    <?php
    $links = array(
        array('Assinar Parecer' => array())
    );
    gerarBreadCrumb($links);
    ?>
    <div class="content">
      <div class="row">
	
	<?php if($this->qtdRegistro != 0){ ?>
	<table class="tabela">
          <tr>
            <th width="5"></th>
            <th width="50">PRONAC</th>
            <th width="300">Nome do Projeto</th>
            <th width="100">Produto</th>
            <th width="100">Tipo de produto</th>
            <th width="120">Data de Recebimento</th>
            <th width="90">Tempo Restante</th>
            <th width="70">Dilig&ecirc;ncia</th>
            <th width="120">Tempo da Dilig&ecirc;ncia</th>
            <th width="70">Hist&oacute;rico</th>
            <th width="">Conclus&atilde;o</th>
            <th width="70">Declarar impedimento</th>
          </tr>
          <?php
               $contador = 1;
               $rp = '';
               $diligenciado = '';
               $Titlediligenciado = '';

               foreach($this->buscar as $d) {

                   /* Verifica se tem diligencia para o projeto  */
                   $tbDiligencia = new tbDiligencia();
                   $rsDilig = $tbDiligencia->buscarDados($d->IdPRONAC);

                   // Conta quantas diligencias existe
                   $dilig = count($rsDilig);

                   $diligencia = NULL;
                   $tempoRestante = NULL;
                   $tempoDiligencia = NULL;

                   /* Diligencia */
                   if ($d->DtSolicitacao && $d->DtResposta == NULL) {
                       $diligencia = 1;
                   } else if ($d->DtSolicitacao && $d->DtResposta != NULL) {
                       $diligencia = 2;
                   } else if ($d->DtSolicitacao && round(data::CompararDatas($d->DtDistribuicao)) > $d->tempoFimDiligencia) {
                       $diligencia = 3;
                   } else {
                       $diligencia = 0;
                   }

                   switch ($diligencia) {
                   case 0:
                       $diligenciado = "notice1.png";
                       $Titlediligenciado = "A Diligenciar";
                       $corDiligencia =  "light-green accent-3";
                       break;
                   case 1:
                       $diligenciado = "notice.png";
                       $Titlediligenciado = "Diligenciado";
                       $corDiligencia = "yellow accent-3";
                       break;
                   case 2:
                       $diligenciado = "notice3.png";
                       $Titlediligenciado = "Diligencia respondida";
                       $corDiligencia = "cyan lighten-1";
                       break;
                   case 3:
                       $diligenciado = "notice2.png";
                       $Titlediligenciado = "Diligencia n&atilde;o respondida";
                       $corDiligencia = "amber accent-4";
            
                       break;
                   }


                   /* Tempo Restante */
                   switch ($diligencia) {
                   case 0:
                       $tempoRestante = round(data::CompararDatas($d->DtDistribuicao));
                       break;
                   case 1:
                       $tempoRestante = round(data::CompararDatas($d->DtDistribuicao, $d->DtSolicitacao));
                       break;
                   case 2:
                       $tempoRestante = round(data::CompararDatas($d->DtResposta));
                       break;
                   case 3:
                       $tempoRestante = round(data::CompararDatas($d->DtResposta));
                       break;
                   }

                   /* Tempo Diligencia */
                   switch ($diligencia) {
                   case 1: $tempoDiligencia = round(data::CompararDatas($d->DtSolicitacao));
                       break;
                   }

                   /* At&eacute; 10 dias (Verde)
                      -Entre 10 at&eacute; 20 dias (amarelo)
                      -Produto distribuido apos 20 dias (vermelho); *
                   */

                   if($tempoRestante <= 10) {
                       $tempoCor = 'green';
                   } else if($tempoRestante > 10 && $tempoRestante <=20) {
                       $tempoCor = 'yellow';
                   } else {
                       $tempoCor = 'red';
                   }

?>
          <tr>
            <td><?php echo $contador; ?></td>
            <td align="center">
              <a target="_blank" href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => 'index'),'',true); ?>?idPronac=<?php echo $d->IdPRONAC?>"><?php if($d->PRONAC != $rp) { echo $d->PRONAC; }else { echo ''; } ?></a>
            </td>
            <td><?php if($d->PRONAC != $rp) { echo $d->NomeProjeto; }else { echo ''; } ?></td>
            <td>
	      <?php if($this->verificarIN2017($d->IdPRONAC)): ?>
	      <?php if (!$this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante)): ?>
	      <a href="<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'produto')); ?>?idPronac=<?php echo $d->IdPRONAC; ?>&idProduto=<?php echo $d->idProduto; ?>&stPrincipal=<?php echo $d->stPrincipal; ?>&idD=<?php echo $d->idDistribuirParecer; ?>" > <?php echo $d->dsProduto; ?></a>
	      <?php else: ?>
	      <?php echo $d->dsProduto; ?>
	      <?php endif; ?>
	      
	      <?php else: ?>
	      <a href="<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'produto')); ?>?idPronac=<?php echo $d->IdPRONAC; ?>&idProduto=<?php echo $d->idProduto; ?>&stPrincipal=<?php echo $d->stPrincipal; ?>&idD=<?php echo $d->idDistribuirParecer; ?>" > <?php echo $d->dsProduto; ?></a>
	      <?php endif; ?>
	    </td>
	    <td align="center"><?php if($d->stPrincipal == 1): ?><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" width="20px" style="cursor: pointer;" title="Produto principal" alt="Produto principal" /><?php endif;?></td>
	    <td align="center"><?php echo Data::tratarDataZend($d->DtDistribuicao, 'Brasileira'); ?></td>
	    <td align="center"><?php echo "<b style='color:".$tempoCor."'>".$tempoRestante." de 10</b>"; ?></td>
	    <td align="center">
	      <?php if (!$this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante)): ?>
              <img src="<?php echo $this->baseUrl(); ?>/public/img/<?php echo $diligenciado; ?>" title="<?php echo $Titlediligenciado; ?>" width="30px" onclick="window.open('<?php echo $this->url(array('module' => 'proposta', 'controller' => 'diligenciar', 'action' => 'listardiligenciaanalista'))?>?idPronac=<?php echo $d->IdPRONAC ?>&idProduto=<?php echo $d->idProduto ;?>&situacao=<?php echo $d->situacao ;?>&tpDiligencia=124')" style="cursor: pointer;" alt="Diligencia" />
	      <?php endif; ?>
          </td>	    
	    <td align="center"><?php echo $d->tempoFimDiligencia; ?></td>
	    <td align="center">
	      <img src="<?php echo $this->baseUrl(); ?>/public/img/edit_ico.gif" style="cursor: pointer;" title="Histrico" alt="Histrico" onclick="redirecionar('<?php echo $this->url(array('controller' => 'Analisarprojetoparecer', 'action' => 'historico', 'idPronac'=> $d->IdPRONAC, 'stPrincipal'=> $d->stPrincipal, 'idProduto' => $d->idProduto)); ?>')" />
	    </td>
	    <td align="center">
	      <?php if(
              (($this->IsProdutosSecundariosAnalisados($d->IdPRONAC)) &&
              ($d->stPrincipal == 1) &&
              (!$this->IsProdutosPendentesParecer($d->IdPRONAC, $d->idProduto)) &&
              ($this->IsProjetoEnquadrado($d->IdPRONAC)) &&
              ($this->IsProjetoComParecer($d->IdPRONAC)) && ($dilig == 0))
    || (($d->stPrincipal == 0) && ($this->IsProdutosPendentesParecer($d->IdPRONAC, $d->idProduto) == 0)  && ($dilig == 0))
  ) :?>
	      <?php if($this->verificarIN2017($d->IdPRONAC)): ?>
          
	      <?php if($this->IsProjetoDisponivelParaAssinatura($d->IdPRONAC, $this->idTipoDoAtoAdministrativo)): ?>
	      <a class="btn waves-effect waves-light cyan tooltipped small"
		 href="<?php echo $this->url(array('module' => 'assinatura', 'controller' => 'index', 'action' => 'visualizar-projeto')) . "?IdPRONAC={$d->IdPRONAC}&idTipoDoAtoAdministrativo=" . Assinatura_Model_DbTable_TbAssinatura::TIPO_ATO_ANALISE_INICIAL; ?>&origin=parecer/index"
		data-tooltip="Visualizar documento para assinatura">
		<i class="material-icons white-text">pageview</i>
	      </a>
	      &nbsp;&nbsp;
	      
	      <?php if ($this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante)): ?>
	      <a class="btn waves-effect waves-light tooltipped small cyan"
		 href="<?php echo $this->url(
		       array(
		       'module' => 'default',
		       'controller' => 'analisarprojetoparecer',
		       'action' => 'fecharparecer',
		       'idPronac'=> $d->IdPRONAC,
		       'idD'=> $d->idDistribuirParecer,
		       'idProduto' => $d->idProduto,
		       'stPrincipal' => $d->stPrincipal
		       )
		       ); ?>"
		 data-position="top"
		 data-delay="50"
		 data-tooltip="Finalizar">
		<i class="material-icons white-text">grade</i>
	      </a>
	      
	      <?php elseif (!$this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante)): ?>
	      <a class="btn waves-effect waves-light cyan tooltipped small"
		 href="<?php echo $this->url(array('module' => 'assinatura', 'controller' => 'index', 'action' => 'assinar-projeto')) . "?IdPRONAC={$d->IdPRONAC}&idTipoDoAtoAdministrativo=" . Assinatura_Model_DbTable_TbAssinatura::TIPO_ATO_ANALISE_INICIAL; ?>&origin=parecer/index"
		data-tooltip="Assinar documento">
		<i class="material-icons white-text">create</i>
	      </a>
	      <?php endif; ?>
	      
	      <?php elseif(!$this->IsProjetoDisponivelParaAssinatura($d->IdPRONAC, $this->idTipoDoAtoAdministrativo)): ?>
	      <a class="btn waves-effect waves-light cyan tooltipped small"
		 href="<?php echo $this->url(array('module' => 'parecer', 'controller' => 'index', 'action' => 'encaminhar-assinatura')) . "?IdPRONAC={$d->IdPRONAC}&encaminhar=true&origin=parecer/index" ?>"
		data-tooltip="Gerar documento para assinatura">
		<i class="material-icons white-text">pageview</i>
	      </a>
	      <?php endif; ?>
	      <?php elseif(!$this->verificarIN2017($d->IdPRONAC)): ?>
	      <img src="<?php echo $this->baseUrl(); ?>/public/img/save.gif" onclick="redirecionar('<?php echo $this->url(array('controller' => 'Analisarprojetoparecer', 'action' => 'fecharparecer', 'idPronac'=> $d->IdPRONAC, 'idD'=> $d->idDistribuirParecer, 'idProduto' => $d->idProduto, 'stPrincipal' => $d->stPrincipal)); ?>')" style="cursor: pointer;" title="Concluir An&aacute;lise" alt="Concluir An&aacute;lise" />
	      <?php endif; ?>
	      <?php endif; ?>
	    </td>
	    <td align="center">
	      <?php if ($this->verificarIN2017($d->IdPRONAC)): ?>
	      <?php if (!$this->IsProjetoJaAssinado($d->IdPRONAC, $this->idTipoDoAtoAdministrativo, $this->idPerfilDoAssinante)): ?>
	      <img id="img_encaminhar_parecer834782" style="cursor:pointer; " title="Declarar impedimento" src="/public/img/table_multiple.png" onclick="redirecionar('<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'devolver-parecer'))?>?idPronac=<?php echo $d->IdPRONAC ?>&idProduto=<?php echo $d->idProduto ;?>&situacao=<?php echo $d->situacao ;?>&idD=<?php echo $d->idDistribuirParecer; ?>')">
		<?php endif; ?>
		<?php elseif (!$this->verificarIN2017($d->IdPRONAC)): ?>
	      <img id="img_encaminhar_parecer834782" style="cursor:pointer; " title="Declarar impedimento" src="/public/img/table_multiple.png" onclick="redirecionar('<?php echo $this->url(array('controller' => 'analisarprojetoparecer', 'action' => 'devolver-parecer'))?>?idPronac=<?php echo $d->IdPRONAC ?>&idProduto=<?php echo $d->idProduto ;?>&situacao=<?php echo $d->situacao ;?>&idD=<?php echo $d->idDistribuirParecer; ?>')">		
		<?php endif; ?>
	    </td>
	  </tr>
	  <?php
	     $rp = $d->PRONAC;
	  $contador++;
	  }
	  ?>
	</table>
	<div class="row">
	  <div class="col s12">
	    <table class="tabela">
	      <tr>
		<td>
		  <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice1.png" width="20px"/></div><div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left;"> A diligenciar</div>
		  <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice.png" width="20px"/></div><div style="margin-top: 2px;  margin-right: 15px; margin-left: 3px; float: left"> Diligenciado</div>
		  <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice3.png" width="20px"/></div><div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left"> Dilig&ecirc;ncia respondida</div>
		  <div style="float: left;"><img src="<?php echo $this->baseUrl(); ?>/public/img/notice2.png" width="20px"/></div><div style="margin-top: 2px; margin-right: 15px; margin-left: 3px; float: left"> Dilig&ecirc;ncia n&atilde;o respondida</div>
		</td>
	      </tr>
	    </table>
	  </div>
	</div>
      </div>
    </div>

    <!-- ========== PAGINA&CCEDIL;&ATILDE;O ========== -->
    <?php if($this->qtdRegistro > 5){ echo "<p>" . $this->buscar . "</p>"; } ?>
    <!-- ========== FIM PAGINA&CCEDIL;&ATILDE;O ========== -->

    <?php } else { ?>
    <table class="tabela" style="width: 95%;">
      <tr>
	<td align="center">NENHUM REGISTRO ENCONTRADO</td>
      </tr>
    </table>
    <?php } ?>

    <div id="conteudoDialogoModal">

      <div id="modalConfirmacao" class="modal modal-fixed-footer">
	<div class="modal-content">
	  <h4>Confirma&ccedil;&atilde;o</h4>
	  <p>Tem certeza que deseja concluir a an&aacute; do projeto <span class="bold" id="nrPronacConfirmacao"></span> ?</p>
	</div>
	<div class="modal-footer">
	  <a href="#!" id="botaoConfirmacaoEncaminhamento" class="modal-action modal-close waves-effect waves-green btn-flat">Sim</a>
	  <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">N&atilde;o</a>
	</div>
      </div>
    </div>

    <br clear="all"/>
    <script
       src="https://code.jquery.com/jquery-1.12.4.js"
       integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
       crossorigin="anonymous">
    </script>
</main>
