	
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Início">Início</a></li>
        <li class="last">Gerenciar Componente da Comiss&atilde;o</li>
    </ul>
</div>



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Gerenciar Componente da Comiss&atilde;o <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">



    <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/public/js/projetosGerenciar.js'></script>
    <script>
        $(document).ready(function(){
            $('.salvarencaminhamento').click(function(){

                if($(this).parent().parent().find('#justificativaencaminha').val()=='Digite a justificativa...')
                {
                    alert("Dados obrigatórios não informados");
                    return false;
		
                }
                else{
                    return true;
                }
            });
//
//            $('table').tablesorter({
//                // pass the headers argument and assing a object
//                headers: {
//                    0: {
//                        sorter: false
//                    }
//                    ,4: {
//                        sorter: false
//                    }
//                }
//            });
//
        });

        function desabilitarAlert(idagente){
            $("#dialog").dialog("destroy");
	
            $("#dialog-desabilitar").dialog({
                resizable: false,
                height:130,
                width: 440,
                modal: true,
                buttons: {
                    'Não': function() {
                        $(this).dialog('close');
                    },
                    Sim: function() {
                        $(this).dialog('close');
                        desabilitar(idagente);
					
                    }
                }
            });
		
        }
        function habilitarAlert(idagente){
            $("#dialog").dialog("destroy");
	
            $("#dialog-habilitar").dialog({
                resizable: false,
                height:130,
                width: 440,
                modal: true,
                buttons: {
                    'Não': function() {
                        $(this).dialog('close');
                    },
                    Sim: function() {
                        $(this).dialog('close');
                        habilitar(idagente);
					
                    }
                }
            });
        }

    </script>

    <div id="dialog-desabilitar" title="Desabilitar" style="display:none">
		Deseja realmente desabilitar o Componente da Comissão?
    </div>

    <div id="dialog-habilitar" title="Habilitar" style="display:none">
		Deseja realmente habilitar o Componente da Comissão?
    </div>

    <div style="width:100%; margin: 0 auto;">

        <table width="95%" cellspacing="0" cellpadding="0" summary=" ">
            <tr>
                <td width="66%" style="text-align:left; padding-left:4%" colspan="2">HABILITADOS</td>
                <td width="18%" align="center">Área Cultural</td>
                <td width="8%" align="center">Quantidade de Projetos</td>
                <td width="8%" align="center">Desabilitar</td>
            </tr>
        </table>

        <!-- Foreach que lista todos os componentes da comissão -->

        <?php foreach ($this->componente as $comp): ?>

            <table style="margin:0 auto;" width="95%" summary="Tabela com os agentes habilitados" class="tablesorter">
                <thead>
                    <tr>
                        <td width="3%"  align="center"><img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/buttons/btn_adicionar.gif" onclick="return abrir_fechar(<?php echo $comp->idAgente; ?>)" onkeypress="return abrir_fechar(<?php echo $comp->idAgente; ?>)" alt="Adicionar" /></td>
                        <td width="62%" style="text-align:left; padding-left:2%;"><?php echo $comp->Nome; ?></td>
                        <td width="18%"  align="center"><?php echo $comp->Area; ?></td>
                        <td width="8%"  align="center"><?php echo $comp->QTD; ?></td>
                        <td width="8%" align="center"><img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/btn_fechar.png" onkeypress="desabilitarAlert
                            (<?php echo $comp->idAgente; ?>+'d');" alt="Desabilitar" onclick="desabilitarAlert(<?php echo $comp->idAgente; ?>+'d');" alt="Desabilitar" /></td>
                </tr>
            </thead>
        </table>

        <!-- Modal para Desabilitar o componente da comissão -->



        <div id="desabilita<?php echo $comp->idAgente; ?>d" title="Desabilitar Componente da Comissão" style="display:none;">

            <form name="formd" id="form<?php echo $comp->idAgente; ?>d" action="<?php echo $this->baseUrl(); ?>/projetosgerenciar/desabilitarcomponente" method="post">
						Informe o motivo da desabilitação do componente da comissão:
                <br /><br>
                <label for="justificativaencaminha">Justificativa</label><br>
                <textarea name="justificativa" id="justificativaencaminha"rows="6" cols="50" style="width:100%;"
                          onclick="limpar_campo(this, 'Digite a justificativa...');" onkeypress=" "
                          onblur="restaurar_campo(this, 'Digite a justificativa...');">Digite a justificativa...</textarea>
                <br>
									* campo com preenchimento obrigatório.
                <p align="right">
                    <input type="submit" value=" " c value=" " class="btn_salvar salvarencaminhamento" />&nbsp;&nbsp;
                    <input type="reset"  value=" " class="btn_limpar Close"/>
                    <input type="hidden"  value="<?php echo $comp->idAgente; ?>" name="idAgente" />
                                                       </p>
                                                   </form>


                                               </div>

                                               <!-- Busca todos os projetos do componente -->

        <?php $pro = ProjetosGerenciarDAO::buscaProjetos($comp->idAgente); ?>

        <?php if ($pro) {
 ?>
                                                           <!-- foreach que lista os projetos do componente da comissão -->

<?php foreach ($pro as $projetos): ?>

                                                               <!-- Modal para encaminhar o projeto -->

                                                               <div style="display:none;" id="encaminhar<?php echo $projetos->idPRONAC; ?><?php echo $projetos->idAgente; ?>" title="Encaminhar projeto para comissão" >
                                                                   <form name="formencaminhar" id="form<?php echo $projetos->idPRONAC; ?><?php echo $projetos->idAgente; ?>" action="<?php echo $this->baseUrl(); ?>/projetosgerenciar/encaminharprojeto" method="post">
                                                                       <table>
                                                                           <tr>
                                                                               <td>PRONAC</td>
                                                                               <td>Nome do Projeto</td>
                                                                           </tr>
                                                                           <tr>
                                                                               <td><?php echo $projetos->PRONAC; ?></td>
                                                                               <td><?php echo $projetos->NomeProjeto; ?></td>
                                                                           </tr>
                                                                       </table>

                                                       						* Por favor informe uma justificativa para o encaminhamento do projeto:
                                                                       <br />	<br><label for="justificativaencaminha">Justificativa</label><br>


                                                                       <textarea name="justificativa" id="justificativaencaminha"rows="6" cols="50" style="width:100%;"
                                                                                 onclick="limpar_campo(this, 'Digite a justificativa...');" onkeypress=" "
                                                                                 onblur="restaurar_campo(this, 'Digite a justificativa...');">Digite a justificativa...</textarea>


                                                                       <br />

                                                                       <br>

                                                                       <label for="agenteNovo">* Encaminhar para:</label> <select name="agenteNovo" id="agenteNovo" style="width:42%;">

                    <?php
                                                               foreach ($this->areaComp as $lista):
                                                                   if ($lista->cdArea == $comp->cdArea) {
                    ?>
                                                                       <option value="<?php echo $lista->idAgente; ?>"><?php echo $lista->Area . ' - ' . $lista->Nome ?></option>
<?php } endforeach; ?>
                                                           </select>
                                                           <br>
                                                           <p align="left" style="margin-top:1%;">
                                                               <input type="submit"  value=" " class="btn_salvar salvarencaminhamento"  value=" " />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset"  value=" " class="btn_limpar" />
                                                               <input type="hidden"  value="<?php echo $projetos->idPRONAC; ?>" name="idPronac" />
                                                               <input type="hidden"  value="<?php echo $projetos->dtCompleta; ?>" name="data" />
                                                               <input type="hidden"  value="<?php echo $projetos->idAgente; ?>" name="agenteAtual" />
                                                           </p>
                                                       </form>
                                                   </div>


<?php endforeach; ?>
                                                               <div style="display:none;" id="<?php echo $comp->idAgente; ?>" >
                                                                   <table width="92%" cellspacing="0" cellpadding="0" style="margin:0 0 0 5%;" summary="Tabela com os projetos associados ao agente">
                                                                       <tr>
                                                                           <td width="7%" align="center" >PRONAC</td>
                                                                           <td width="48%" style="text-align:left;">Nome do projeto</td>
                                                                           <td width="5%" align="center">Qtd de Dias</td>
                                                                           <td width="10%" align="center">Data de recebimento</td>
                                                                           <td width="8%" align="center">Mensagens</td>
                                                                           <td width="8%" align="center">Redirecionar projeto</td>
                                                                       </tr>

<?php foreach ($pro as $projetos): ?>



                <?php
                                                                   echo '<tr class="tblGerenciar_projetos">';
                                                                   echo '<td align="center">' . $projetos->PRONAC . '</td>';
                                                                   echo '<td  style="text-align:left;">' . $projetos->NomeProjeto . '</td>';
                                                                   echo '<td align="center">' . $projetos->Dias . '</td>';
                                                                   echo '<td align="center">' . $projetos->dtDistribuicao . '</td>';
                                                                   echo '<td align="center"><a href="' . $this->url(array('controller' => 'mantermensagens', 'action' => 'consultarmensagem', 'idpronac' => $projetos->idPRONAC)) . '"><img border="0" src="../public/img/table_multiple.png" alt="Visualizar Histórico" /> </a></td>';
                                                                   echo '<td align="center"><img src="../public/img/user_gray.png" onclick="return encaminhar(' . $projetos->idPRONAC . $projetos->idAgente . ')" onkeypress="return encaminhar(' . $projetos->idPRONAC . $projetos->idAgente . ')" alt="Encaminhar" /></td>';
                                                                   echo '</tr>';
                ?>



<?php endforeach; ?>

                                                               </table>
                                                           </div>

        <?php } ?>

<?php endforeach; ?>

                                                           </div>

                                                           <br /><br />

                                                           <div style="width:100%; margin: 0 auto;">
                                                               <table width="95%" cellspacing="0" cellpadding="0" summary=" ">
                                                                   <tr>
                                                                       <td width="74%" style="text-align:left; padding-left:4%;" colspan="2">DESABILITADOS</td>
                                                                       <td width="18%" align="center">Área Cultural</td>
                                                                       <td width="8%" align="center">Habilitar</td>
                                                                   </tr>
                                                               </table>

                                                               <br />

                                                               <!-- foreach que lista os componentes desabilitados -->


                                                               </script>

<?php foreach ($this->desabilitados as $comp): ?>

                                                                   <div id="habilitar<?php echo $comp->idAgente; ?>" title="Habilitar Componente da Comissão" style="display:none;">
                                                               <form name="forma" id="form<?php echo $comp->idAgente; ?>a" action="<?php echo $this->baseUrl(); ?>/projetosgerenciar/habilitarcomponente" method="post">
                                                   			Informe o motivo da habilitação do componente da comissão:
                                                                   <br />	<br><label for="justificativaencaminha">Justificativa</label><br>

                                                                   <textarea name="justificativa" id="justificativaencaminha"rows="6" cols="50" style="width:100%;"
                                                                             onclick="limpar_campo(this, 'Digite a justificativa...');" onkeypress=" "
                                                                             onblur="restaurar_campo(this, 'Digite a justificativa...');">Digite a justificativa...</textarea>

                                                                   <br>
                                                   				* campo com preenchimento obrigatório.
                                                                   <p align="right">
                                                                       <input type="submit"  value=" " class="btn_salvar salvarencaminhamento" value=" " />
                                                                       &nbsp;&nbsp;<input type="reset"  value="" class="btn_limpar"/>
                                                                       <input type="hidden"  value="<?php echo $comp->idAgente; ?>" name="idAgente" />


                                                                   </p>

                                                               </form>

                                                           </div>




                                                           <table width="95%" summary="Tabela com os agentes desabilitados">
                                                               <tr>
                                                                   <td width="4%"  align="center"><img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/buttons/btn_adicionar.gif" onkeypress="return abrir_fechar2(<?php echo $comp->idAgente; ?>)" onclick="return abrir_fechar2(<?php echo $comp->idAgente; ?>)" alt="Adicionar" /></td>
                                                                   <td width="70%" style="text-align:left; padding-left:2%;"><?php echo $comp->Nome; ?></td>
                                                                   <td width="18%"  align="center"><?php echo $comp->Area; ?></td>
                                <td width="8%" align="center"><img style="cursor: pointer;" src="<?php echo $this->baseUrl(); ?>/public/img/passed.gif" onkeypress="habilitarAlert
                                    (<?php echo $comp->idAgente; ?>)" onclick="habilitarAlert(<?php echo $comp->idAgente; ?>)" alt="Habilitar" /></td>


                            </tr>
                        </table>

                        <div id="hab<?php echo $comp->idAgente; ?>" style="display:none;">
                            <table width="92%" cellspacing="0" cellpadding="0" style="margin:0 0 0 5%;" summary="Tabela com o motivo da desabilitação do agente">
                                <tr>
                                    <td align="center">Motivo</td>
                                    <td align="center">Desabilitado desde:</td>
                                </tr>
                                <tr>
                                    <td><?php echo $comp->Just; ?></td>
                                    <td align="center" width="15%"><?php echo $comp->Data; ?></td>
                                </tr>
                            </table>
                        </div>

<?php endforeach; ?>

    </div>




</div>




<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />
