<?php
/**
 * Exemplo de Utilização do Layout - Grids
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */

require_once "inc/menu.inc.phtml"; // menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a></li>
		<li class="last">Grids</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Grids
		<span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- ========== INÍCIO GRID 1 ========== -->
	<div class="miolo"><h4 class="centro">Grid 1</h4></div>

	<table class="tabela">
		<tr>
			<th>Título da Página</th>
		</tr>
	</table>

	<!-- INÍCIO TABELA PROJETOS INDEFERIDOS -->
	<table class="tabela">
		<tr>
			<td><input type="button" name="grid1" id="g1_1" class="btn_adicionar" title="Expandir" />Projetos Indeferidos</td>
		</tr>
	</table>
	<div id="div_g1_1" class="miolo_grid_01 sumir">
		<table class="tabela">
			<thead>
				<tr>
					<th width="70">Pronac</th>
					<th width="40%">Nome do Projeto</th>
					<th width="20%">Área de Segmento</th>
					<th width="90">Data de Início</th>
					<th width="90">Data de Fim</th>
					<th>Cidade</th>
				</tr>
			</thead>

			<tbody>
				<tr class="linha">
					<td class="centro"><a href="#" title="">121234</a></td>
					<td>Projeto Saber</td>
					<td class="centro">Nome da área - Nome do Segmento</td>
					<td class="centro">DD/MM/AAAA</td>
					<td class="centro">DD/MM/AAAA</td>
					<td>Brasília-DF</td>
				</tr>
				<tr class="linha">
					<td class="centro"><a href="#" title="">121234</a></td>
					<td>Projeto Saber</td>
					<td class="centro">Nome da área - Nome do Segmento</td>
					<td class="centro">DD/MM/AAAA</td>
					<td class="centro">DD/MM/AAAA</td>
					<td>Brasília-DF</td>
				</tr>
			</tbody>
		</table>
	</div>
	<!-- FIM TABELA PROJETOS INDEFERIDOS -->


	<!-- INÍCIO TABELA PROJETOS DEFERIDOS - REENQUADRAMENTO -->
	<table class="tabela">
		<tr>
			<td><input type="button" name="grid1" id="g1_2" class="btn_adicionar" title="Expandir" />Projetos Deferidos - Reenquadramento</td>
		</tr>
	</table>
	<div id="div_g1_2" class="miolo_grid_01 sumir">
		<table class="tabela">
			<thead>
				<tr>
					<th width="70">Pronac</th>
					<th width="40%">Nome do Projeto</th>
					<th width="20%">Área de Segmento</th>
					<th width="90">Data de Início</th>
					<th width="90">Data de Fim</th>
					<th>Cidade</th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td colspan="6" class="centro">Não existem Projetos Deferidos (Reenquadramento) com solicitação de Recurso!</td>
				</tr>
			</tbody>
		</table>
	</div>
	<!-- FIM TABELA PROJETOS DEFERIDOS - REENQUADRAMENTO -->


	<!-- INÍCIO TABELA PROJETOS DEFERIDOS - ORÇAMENTO -->
	<table class="tabela">
		<tr>
			<td><input type="button" name="grid1" id="g1_3" class="btn_adicionar" title="Expandir" />Projetos Deferidos - Orçamento</td>
		</tr>
	</table>
	<div id="div_g1_3" class="miolo_grid_01 sumir">
		<table class="tabela">
			<thead>
				<tr>
					<th width="70">Pronac</th>
					<th width="40%">Nome do Projeto</th>
					<th width="20%">Área de Segmento</th>
					<th width="90">Data de Início</th>
					<th width="90">Data de Fim</th>
					<th>Cidade</th>
				</tr>
			</thead>

			<tbody class="registros">
				<tr>
					<td class="centro"><a href="#" title="">121234</a></td>
					<td>Projeto Saber</td>
					<td class="centro">Nome da área - Nome do Segmento</td>
					<td class="centro">DD/MM/AAAA</td>
					<td class="centro">DD/MM/AAAA</td>
					<td>Brasília-DF</td>
				</tr>
				<tr class="fundo_linha2">
					<td class="centro"><a href="#" title="">121234</a></td>
					<td>Projeto Saber</td>
					<td class="centro">Nome da área - Nome do Segmento</td>
					<td class="centro">DD/MM/AAAA</td>
					<td class="centro">DD/MM/AAAA</td>
					<td>Brasília-DF</td>
				</tr>
				<tr>
					<td class="centro"><a href="#" title="">121234</a></td>
					<td>Projeto Saber</td>
					<td class="centro">Nome da área - Nome do Segmento</td>
					<td class="centro">DD/MM/AAAA</td>
					<td class="centro">DD/MM/AAAA</td>
					<td>Brasília-DF</td>
				</tr>
			</tbody>
		</table>
	</div>
	<!-- FIM TABELA PROJETOS DEFERIDOS - ORÇAMENTO -->

	<!-- ========== FIM GRID 1 ========== -->





	<br />
	<br />





	<!-- ========== INÍCIO GRID 2 ========== -->
	<script type="text/javascript">
	<!--
	/**
	 * Funções que são chamadas após a página ser carregada
	 */
	$(document).ready(function()
	{
		$('#dt_inicio, #dt_fim').keyup(function()
		{
			mascara(this, format_data); // máscaras de data
		});
		$('#dt_inicio, #dt_fim').click(function()
		{
			limpar_campo(this, '00/00/0000'); // quando o usuário clicar no campo o mesmo é limpado
		});
		$('#dt_inicio, #dt_fim').blur(function()
		{
			restaurar_campo(this, '00/00/0000'); // quando o usuário sair no campo o mesmo é restaurado
		});
		$('#pronac').click(function()
		{
			limpar_campo(this, 'Digite o Pronac...'); // quando o usuário clicar no campo o mesmo é limpado
		});
		$('#pronac').blur(function()
		{
			restaurar_campo(this, 'Digite o Pronac...'); // quando o usuário sair no campo o mesmo é restaurado
		});

		// calendário
		$.datepicker.regional['pt-BR'] = 
		{
			closeText: 'Fechar',
			prevText: '&#x3c;Anterior',
			nextText: 'Pr&oacute;ximo&#x3e;',
			currentText: 'Hoje',
			monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
			dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','S&aacute;bado'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
			dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
			weekHeader: 'Sm',
			dateFormat: 'dd/mm/yy',
			firstDay: 0,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ''
		};
		$.datepicker.setDefaults($.datepicker.regional['pt-BR']);

		// id dos campos que utilizarão o calendário
		$("#dt_inicio, #dt_fim").datepicker($.datepicker.regional['pt-BR']);
	});
	//-->
	</script>

	<div class="miolo"><h4 class="centro">Grid 2</h4></div>

	<!-- INÍCIO FORMULÁRIO DE BUSCA -->
	<form name="" id="" method="post" action="">
		<table class="tabela">
			<tbody>
				<tr class="centro">
					<td width="20%">
						<label for="pronac">PRONAC</label> 
						<input type="text" name="pronac" id="pronac" maxlength="10" class="input_simples" value="Digite o Pronac..." />
					</td>
					<td>
						<label for="status"> </label>
						<select name="status" id="status" class="select_simples">
							<option value="AG">Aguardando Avaliação</option>
							<option value="AV">Em Avaliação</option>
							<option value="EA">Em Aprovação</option>
							<option value="AA">Avaliado</option>
							<option value="TD" selected="selected">Todas</option>
						</select>
					</td>
					<td>
						<label for="dt_inicio">De</label> 
						<input type="text" name="dt_inicio" id="dt_inicio" maxlength="10" class="input_simples btn_calendario" value="00/00/0000" /> 
						<label for="dt_fim"> à </label> 
						<input type="text" name="dt_fim" id="dt_fim" maxlength="10" class="input_simples btn_calendario" value="00/00/0000" />
					</td>
					<td><input type="submit" class="btn_pesquisar" value=" " title="Pesquisar" /></td>
				</tr>
			</tbody>
		</table>
	</form>
	<!-- FIM FORMULÁRIO DE BUSCA -->


	<!-- INÍCIO BUSCA PROJETOS -->
	<table class="tabela">
		<thead>
			<tr class="titulo_tabela">
				<th>PRONAC</th>
				<th>Status</th>
				<th>Data de Recebimento</th>
				<th>Data de Resposta</th>
				<th>Ação</th>
			</tr>
		</thead>

		<tbody>
			<tr name="grid2" class="fundo_linha2 centro">
				<td><acronym title="Projeto Saber 1">121234</acronym></td>
				<td class="AV"><?php echo $this->statusCompFisicaProjeto('AV'); ?></td>
				<td>05/04/2010</td>
				<td>&nbsp;</td>
				<td><input type="button" class="btn_abrir" value=" " title="Abrir" /></td>
			</tr>
			<tr name="grid2" class="fundo_linha2 centro">
				<td><acronym title="Projeto Saber 2">112541</acronym></td>
				<td class="EA"><?php echo $this->statusCompFisicaProjeto('EA'); ?></td>
				<td>13/05/2010</td>
				<td>&nbsp;</td>
				<td><input type="button" class="btn_abrir" value=" " title="Abrir" /></td>
			</tr>
			<tr name="grid2" class="fundo_linha2 centro">
				<td><acronym title="Projeto Saber 3">094521</acronym></td>
				<td class="AD"><?php echo $this->statusCompFisicaProjeto('AD'); ?></td>
				<td>30/06/2010</td>
				<td>02/09/2010</td>
				<td><input type="button" class="btn_abrir" value=" " title="Abrir" /></td>
			</tr>
			<tr name="grid2" class="fundo_linha2 centro">
				<td><acronym title="Projeto Saber 4">129875</acronym></td>
				<td class="AI"><?php echo $this->statusCompFisicaProjeto('AI'); ?></td>
				<td>12/07/2010</td>
				<td>29/07/2010</td>
				<td><input type="button" class="btn_abrir" value=" " title="Abrir" /></td>
			</tr>
		</tbody>
	</table>
	<!-- FIM BUSCA PROJETOS -->


	<!-- INÍCIO PAGINAÇÃO -->
	<table class="tabela">
		<tr>
			<td class="centro">
				<input type="button" class="btn_inicio" id="btn_inicio" title="Ir para primeira página" />
				<input type="button" class="btn_p_anterior" id="btn_p_anterior" title="Ir para página anterior" />
				<select name="pagina" id="pagina" class="select_simples">
					<option value="1">1</option>
					<option value="2">2</option>
				</select>
				<input type="button" class="btn_p_proximo" id="btn_p_proximo" title="Ir para próxima página" />
				<input type="button" class="btn_ultimo" id="btn_ultimo" title="Ir para última página" />
				Exibindo de <strong>1</strong> à <strong>100</strong> de um total de <strong>200</strong>
			</td>
		</tr>
	</table>
	<!-- FIM PAGINAÇÃO -->

	<!-- ========== FIM GRID 2 ========== -->





	<br />
	<br />





	<!-- ========== INÍCIO GRID 3 ========== -->
	<div class="miolo"><h4 class="centro">Grid 3</h4></div>

	<table class="tabela">
		<thead>
			<tr>
				<th>Tipo Documento</th>
				<th>Nome</th>
				<th>Arquivo</th>
				<th>Tamanho</th>
				<th>Data de Recebimento</th>
				<th>Data de Resposta</th>
				<th>Status</th>
				<th>Ação</th>
			</tr>
		<thead>

		<!-- INÍCIO COMPROVANTES -->
		<tr class="fundo_linha2 registros">
			<td><div name="grid3" id="g3_1"><a href="#" title="Expandir"><div class="icn_mais"><span>Edital 1</span></div></a></div></td>
			<td class="centro">Teste 1</td>
			<td class="centro"><a href="#" title="Abrir arquivo">teste1.pdf</a></td>
			<td class="centro"><?php echo $this->converterBytes(1234); ?></td>
			<td class="centro">30/06/2010</td>
			<td class="centro">Testando grid 1</td>
			<td class="centro green">Avaliado - Deferido</td>
			<td class="centro"><input type="button" class="btn_ver" title="Ver" value=" " /></td>
		</tr>
		<!-- FIM COMPROVANTES -->

		<!-- INÍCIO HISTÓRICO -->
		<tbody id="tbody_g3_1" class="sumir">
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 1.1</span></div></td>
				<td class="centro">Teste 1.1</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste1.1.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 1.1</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
		</tbody>
		<!-- FIM HISTÓRICO -->



		<!-- INÍCIO COMPROVANTES -->
		<tr class="fundo_linha2 registros">
			<td><div name="grid3" id="g3_2"><a href="#" title="Expandir"><div class="icn_mais"><span>Edital 2</span></div></a></div></td>
			<td class="centro">Teste 2</td>
			<td class="centro"><a href="#" title="Abrir arquivo">teste2.pdf</a></td>
			<td class="centro"><?php echo $this->converterBytes(1234); ?></td>
			<td class="centro">30/06/2010</td>
			<td class="centro">Testando grid 2</td>
			<td class="centro green">Avaliado - Deferido</td>
			<td class="centro"><input type="button" class="btn_ver" title="Ver" value=" " /></td>
		</tr>
		<!-- FIM COMPROVANTES -->

		<!-- INÍCIO HISTÓRICO -->
		<tbody id="tbody_g3_2" class="sumir">
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 2.1</span></div></td>
				<td class="centro">Teste 2.1</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste2.1.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 2.1</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 2.2</span></div></td>
				<td class="centro">Teste 2.2</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste2.2.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 2.2</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
		</tbody>
		<!-- FIM HISTÓRICO -->



		<!-- INÍCIO COMPROVANTES -->
		<tr class="fundo_linha2 registros">
			<td><div name="grid3" id="g3_3"><a href="#" title="Expandir"><div class="icn_mais"><span>Edital 3</span></div></a></div></td>
			<td class="centro">Teste 3</td>
			<td class="centro"><a href="#" title="Abrir arquivo">teste3.pdf</a></td>
			<td class="centro"><?php echo $this->converterBytes(1234); ?></td>
			<td class="centro">30/06/2010</td>
			<td class="centro">Testando grid 3</td>
			<td class="centro green">Avaliado - Deferido</td>
			<td class="centro"><input type="button" class="btn_ver" title="Ver" value=" " /></td>
		</tr>
		<!-- FIM COMPROVANTES -->

		<!-- INÍCIO HISTÓRICO -->
		<tbody id="tbody_g3_3" class="sumir">
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 3.1</span></div></td>
				<td class="centro">Teste 3.1</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste3.1.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 3.1</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 3.2</span></div></td>
				<td class="centro">Teste 3.2</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste3.2.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 3.2</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
			<tr class="linha">
				<td><div class="icn_vazio"><span>Edital 3.3</span></div></td>
				<td class="centro">Teste 3.3</td>
				<td class="centro"><a href="#" title="Abrir arquivo">teste3.3.pdf</a></td>
				<td class="centro"><?php echo $this->converterBytes(25632); ?></td>
				<td class="centro">30/06/2010</td>
				<td class="centro">Testando grid 3.3</td>
				<td class="centro red">Avaliado - Indeferido</td>
				<td class="centro"><input type="button" class="btn_ver" title=" Ver " value=" " /></td>
			</tr>
		</tbody>
		<!-- FIM HISTÓRICO -->

	</table>


	<!-- INÍCIO PAGINAÇÃO -->
	<table class="tabela">
		<tr>
			<td class="centro">
				<input type="button" class="btn_inicio" id="btn_inicio" title="Ir para primeira página" />
				<input type="button" class="btn_p_anterior" id="btn_p_anterior" title="Ir para página anterior" />
				<select name="pagina" id="pagina" class="select_simples">
					<option value="1">1</option>
					<option value="2">2</option>
				</select>
				<input type="button" class="btn_p_proximo" id="btn_p_proximo" title="Ir para próxima página" />
				<input type="button" class="btn_ultimo" id="btn_ultimo" title="Ir para última página" />
				Exibindo de <strong>1</strong> à <strong>100</strong> de um total de <strong>200</strong>
			</td>
		</tr>
	</table>
	<!-- FIM PAGINAÇÃO -->

	<!-- ========== FIM GRID 3 ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />