<?php
/**
 * Exemplo de Utilização do Layout
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */

require_once "inc/menu.inc.phtml"; // menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li class="last">Exemplo de utilização do layout</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Exemplo de utilização do layout
		<span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- títulos -->
	<fieldset>
		<legend>Títulos</legend>
		<h1>Título utilizando <strong>h1</strong>.</h1>
		<h2>Título utilizando <strong>h2</strong>.</h2>
		<h3>Título utilizando <strong>h3</strong>.</h3>
		<h4>Título utilizando <strong>h4</strong>.</h4>
		<h5>Título utilizando <strong>h5</strong>.</h5>
		<h6>Título utilizando <strong>h6</strong>.</h6>
	</fieldset>



	<!-- parágrafos, links, imagens, etc -->
	<fieldset>
		<legend>Parágrafos, Estilos, Links e Imagens</legend>

		<!-- ========== INÍCIO MARGEM ========== -->
		<div id="miolo">
			<p class="bold">Parágrafo 1:</p>
			<p>
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>.
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 2 (identado):</p>
			<p class="identar">
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>.
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 3 (acrônimo e links):</p>
			<p>
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição.
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 4 (imagem simples):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" />
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 5 (imagem com borda):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="imagem" />
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 6 (imagem com texto):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="float_left" />
				Exemplo de parágrafo utilizando a tag <strong>p</strong> com imagem alinhada à esquerda. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>.
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição.
			</p>

			<br />

			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="float_right" />
				Exemplo de parágrafo utilizando a tag <strong>p</strong> com imagem alinhada à direita. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>.
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição. 
				Exemplo de parágrafo utilizando a tag <strong>p</strong>. 
				Quando uma página possui somente textos é necessário colocá-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em relação ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um parágrafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> está disponível no 
				endereço eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio às Leis de Incentivo à Cultura">SALIC</acronym> para ver sua descrição.
			</p>

			<br />
			<br />

			<p class="bold">Parágrafo 7 (cores e estilos de texto e links):</p>
			<p class="red">Utilize a classe <strong>.red</strong></p>
			<p class="green">Utilize a classe <strong>.green</strong></p>
			<p class="blue">Utilize a classe <strong>.blue</strong></p>
			<p class="orange">Utilize a classe <strong>.orange</strong></p>
			<p class="black">Utilize a classe <strong>.black</strong> ou <strong>.white</strong> para utilizar as cores preto ou branco</p>
			<p class="bg_red white">Utilize a classe <strong>.bg_red</strong></p>
			<p class="bg_green white">Utilize a classe <strong>.bg_green</strong></p>
			<p class="bg_blue white">Utilize a classe <strong>.bg_blue</strong></p>
			<p class="bg_orange white">Utilize a classe <strong>.bg_orange</strong></p>
			<p class="bg_white black">Utilize a classe <strong>.bg_white</strong></p>
			<p class="bg_black white">Utilize a classe <strong>.bg_black</strong></p>
			<p>
				<a href="#" title="Link com cor alterada" class="bg_red">
					<span class="white">
						Para link com cor diferente utilize a tag <strong>span</strong> dentro do mesmo e adicione a classe desejada
					</span>
				</a>
			</p>
			<p class="del_link">
				<a href="#" title="Link sem underline">
					<span class="green">
						Para link sem underline utilize a classe <strong>.del_link</strong> dentro de um elemento "pai" do link
					</span>
				</a>
			</p>
		</div>
		<!-- ========== FIM MARGEM ========== -->

	</fieldset>



	<!-- agrupamento de formulários -->
	<fieldset>
		<legend>Grupo 1</legend>
		Junte grupos de formulários utilizando a tag <strong>fieldset</strong>, e, coloque sua descrição utilizando a tag <strong>legend</strong>.
	</fieldset>
	<fieldset>
		<legend>Grupo 2</legend>
		Junte grupos de formulários utilizando a tag <strong>fieldset</strong>, e, coloque sua descrição utilizando a tag <strong>legend</strong>.
	</fieldset>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />