<?php
/**
 * Exemplo de Utilização do Layout - Máscaras em PHP
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */

require_once "inc/menu.inc.phtml"; // menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a></li>
		<li class="last">Máscaras em php</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Máscaras em php
		<span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<table class="tabela">
		<thead>
			<tr>
				<th colspan="2">Máscaras Utilizando PHP</th>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
			<tr>
				<th>Descrição</th>
				<th>Classe :: Método</th>
			</tr>
		</thead>
		<tbody class="registros">
			<tr>
				<td>Adicionar máscara de telefone.</td>
				<td>
					&lt;?php <strong>Mascara::addMaskFone($fone);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de telefone.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskFone($fone);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de cep.</td>
				<td>
					&lt;?php <strong>Mascara::addMaskCEP($cep);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de cep.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskCEP($cep);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de cpf.</td>
				<td>
					&lt;?php <strong>Mascara::addMaskCPF($cpf);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de cpf.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskCPF($cpf);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de cnpj.</td>
				<td>
					&lt;?php <strong>Mascara::addMaskCNPJ($cnpj);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de cnpj.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskCNPJ($cnpj);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de cpf ou cnpj.</td>
				<td>
					&lt;?php <strong>Validacao::mascaraCPFCNPJ($cpf_cnpj);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de cpf ou cnpj.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskCPFCNPJ($cpf_cnpj);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de moeda brasileira (somente nas views).</td>
				<td>
					&lt;?php <strong>$this->formatarReal($moeda);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Remover máscara de moeda.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskMoeda($moeda);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Adicionar máscara de milhar (somente nas views).</td>
				<td>
					&lt;?php <strong>$this->formatarMilhar($valor);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Conversão de bytes para KB, MB, GB, TB, PB, EB, ZB e YB (somente nas views).</td>
				<td>
					&lt;?php <strong>$this->converterBytes($bytes);</strong> ?&gt;<br />
				</td>
			</tr>
			<tr>
				<td>Remover erros comuns de e-mails.</td>
				<td>
					&lt;?php <strong>Mascara::delMaskEmail($email);</strong> ?&gt;<br />
				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="2">&nbsp;</td>
			</tr>
		</tfoot>
	</table>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />