<?php
/**
 * Exemplo de Utilização do Layout - Menu de Abas
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */

require_once "inc/menu.inc.phtml"; // menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a></li>
		<li class="last">Menu de abas</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Menu de abas 4
		<span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<?php require_once "inc/menu_abas1.inc.phtml"; // menu abas ?>
	<h4 class="centro">Modelo 1</h4>

	<br />
	<br />

	<?php require_once "inc/menu_abas2.inc.phtml"; // menu abas ?>
	<h4 class="centro">Modelo 2</h4>

	<br />
	<br />

	<?php require_once "inc/menu_abas3.inc.phtml"; // menu abas ?>
	<h4 class="centro">Modelo 3</h4>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />