<?php
/**
 * Exemplo de Utilização do Layout - Menu Lateral
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Ministério da Cultura - Todos os direitos reservados.
 */

require_once "inc/menu.inc.phtml"; // menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utilização do Layout">Exemplo de Utilização do Layout</a></li>
		<li class="last">Menu lateral</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Menu lateral
		<span class="voltar"><a href="javascript:voltar();" title="Página Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- ========== INÍCIO MARGEM ========== -->
	<div id="miolo">
		<p>Esse é o esqueleto de uma página com menu lateral.</p>

		<br />

		<p>
			Crie uma pasta chamada <strong>inc</strong> dentro de sua view e utilize o arquivo 
			<strong>/NovoSalic/application/views/scripts/manual-layout/inc/menu.inc.phtml</strong> como exemplo.
		</p>

		<br />

		<p>
			Inclua o arquivo no início da view que utilizará o menu lateral: 
			<strong>require_once "inc/menu.inc.phtml";</strong>
		</p>

		<br />

		<p class="bold">
			Considerações importantes sobre o menu:
		</p>

		<br />

		<p>
			Os itens de menu estão dentro de: <strong>&lt;div id="qm0" class="qmmc"&gt;</strong>
		</p>

		<br />

		<p>
			O formato de um menu simple é: 
			<strong>
				&lt;a class="no_seta" href="&lt;?php echo $this->url(array('controller' => 'nome-da-controller', 'action' => 'nome-da-action'), '', true); ?&gt;" title="Ir para Formul&aacute;rios"&gt;Formul&aacute;rios&lt;/a&gt;
			</strong>
		</p>

		<br />

		<p>
			O formato de um menu contendo sub-menus é: 
			<strong>
				<br />
				&lt;a class="sanfona" href="#" title="Ir para M&aacute;scaras"&gt;M&aacute;scaras&lt;/a&gt;<br />
				&lt;div class="sanfonaDiv sumir"&gt;<br />
				&nbsp;&nbsp;&nbsp;&nbsp; &lt;a class="no_seta" href="&lt;?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'mascaras-js'), '', true); ?&gt;" title="Ir para M&aacute;scaras em JavaScript"&gt;M&aacute;scaras em JavaScript&lt;/a&gt;<br />
				&nbsp;&nbsp;&nbsp;&nbsp; &lt;a class="no_seta" href="&lt;?php echo $this->url(array('controller' => 'manual-layout', 'action' => 'mascaras-php'), '', true); ?&gt;" title="Ir para M&aacute;scaras em PHP"&gt;M&aacute;scaras em PHP&lt;/a&gt;<br />
				&lt;/div&gt;
			</strong>
		</p>

		<br />

		<p>
			Quando o último menu não tiver sub-menus, utilizar a classe <strong>.last</strong>
		</p>
	</div>
	<!-- ========== FIM MARGEM ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />