<img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" class="corrigir-periodo-execucao" style="cursor: pointer" />

<script>
	$('.corrigir-periodo-execucao').click(function(){
		$("#msgAlerta").dialog("destroy");
        $("#msgAlerta").html(
        	'<p>Efetue a correção dessa inconsistência, prorrogando o período de execução do projeto.' +
        	'<br />Após efetuar a devida correção, clicar novamente em validar.</p>'
        );
        $("#msgAlerta").dialog({
            resizable: false,
            title: 'Alerta!',
            width: 700,
            height: 100,
            modal: true
        });
	});
</script>