<?php
/**
 * Histórico Proponente
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 24/04/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

$dados = $this->dados;
?>



<table class="tabela" summary="Histórico">
	<tr>
		 <td><input type="button" name="grid-proponente" id="g-proponente" class="btn_adicionar" title="Expandir" /> <strong>Hist&oacute;rico de Solicita&ccedil;&atilde;o de Readequa&ccedil;&atilde;o - Proponente</strong></td>
	</tr>
</table>

<div id="div_g-proponente" class="miolo_grid_01 sumir">
<?php if (isset($dados['idPedidoAlteracao'])) : ?>
<table class="tabela">
	<tr class="destacar bold" align="center">
		<td width="10%">Solicita&ccedil;&atilde;o</td>
		<td width="10%">Data Solicita&ccedil;&atilde;o</td>
		<td width="10%">CPF/CNPJ</td>
		<td width="20%">Nome do Proponente</td>
		<td width="10%">Justificativa Proponente</td>
		<td width="10%">Data Avalia&ccedil;&atilde;o</td>
		<td width="10%">Avalia&ccedil;&atilde;o MinC</td>
		<td width="10%">Justificativa MinC</td>
		<td>Anexos</td>
		<td>A&ccedil;&atilde;o</td>
	</tr>

	<?php for ($i = 0; $i < count($dados['idPedidoAlteracao']); $i++) : ?>
	<tr class="fundo_linha<?php echo ($i % 2 == 0) ? 1 : 2; ?>">
		<td align="center"><?php echo $dados['item'][$i]; ?></td>
		<td align="center"><?php echo $dados['dtSolicitacao'][$i]; ?></td>
		<td align="center"><?php echo Validacao::mascaraCPFCNPJ($dados['CNPJCPF'][$i]); ?></td>
		<td><?php echo $dados['NomeProponente'][$i]; ?></td>
		<td align="center">
			<a href="javascript:alertModal('Justificativa Proponente', 'dsProponente02<?php echo $dados['item'][$i]; ?>', 580, 360);" title="Visualizar justificativa"><img src="<?php echo $this->baseUrl(); ?>/public/img/edit_ico.gif" alt="Visualizar anexos" /></a>
			<div id="dsProponente02<?php echo $dados['item'][$i]; ?>" class="sumir">
				<table class="tabela">
					<tr>
						<th>Justificativa Proponente</th>
					</tr>
					<tr>
						<td><?php echo $dados['dsProponente'][$i]; ?></td>
					</tr>
				</table>
			</div>
		</td>
		<td align="center"><?php echo $dados['dtFimAvaliacao'][$i]; ?></td>
		<td align="center" class="<?php echo $dados['stAvaliacao'][$i] == 'AP' ? 'green' : 'red' ?>"><?php echo $dados['stAvaliacao'][$i] == 'AP' ? 'Aprovado' : 'Indeferido' ?></td>
		<td align="center">
			<a href="javascript:alertModal('Justificativa MinC', 'dsMinc02<?php echo $dados['item'][$i]; ?>', 580, 360);" title="Visualizar justificativa"><img src="<?php echo $this->baseUrl(); ?>/public/img/edit_ico.gif" alt="Visualizar anexos" /></a>
			<div id="dsMinc02<?php echo $dados['item'][$i]; ?>" class="sumir">
				<table class="tabela">
					<tr>
						<th>Justificativa MinC</th>
					</tr>
					<tr>
						<td><?php echo $dados['dsAvaliacao'][$i]; ?></td>
					</tr>
				</table>
			</div>
		</td>
		<td align="center">
			<?php if (count($dados['Arquivos'][$i]) > 0) : ?>
			<a href="javascript:alertModal('Anexos', 'arquivos02<?php echo $dados['item'][$i]; ?>', 580, 360);" title="Visualizar anexos"><img src="<?php echo $this->baseUrl(); ?>/public/img/ico/archive.png" alt="Visualizar anexos" /></a>
			<div id="arquivos02<?php echo $dados['item'][$i]; ?>" class="sumir">
				<table class="tabela">
					<tr>
						<th>Anexos</th>
					</tr>
					<tr>
						<td>
							<?php foreach ($dados['Arquivos'][$i] as $a) : ?>
							<p><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir'), '', true) . '?id=' . $a['idArquivo']; ?>" target="_blank" title="Abrir arquivo"><?php echo $a['nmArquivo']; ?></a></p>
							<?php endforeach; ?>
						</td>
					</tr>
				</table>
			</div>
			<?php else : ?>
			&nbsp;
			<?php endif; ?>
		</td>
		<td align="center"><strong><?php echo $dados['tpAlteracaoProjeto'][$i] ; ?></strong></td>
	</tr>
	<?php endfor; ?>

</table>

<?php else : ?>
<table class="tabela">
	<tr>
		<td align="center">N&atilde;o existe hist&oacute;rico de solicita&ccedil;&atilde;o de readequa&ccedil;&atilde;o para esse item.</td>
	</tr>
</table>
<?php endif; ?>
</div>



<script type="text/javascript">
<!--
/**
 * Função para abrir e fechar a grid
 */
function grid_proponente(elemento)
{
	if ( $('#' + elemento).attr('class') == 'btn_adicionar' )
	{
		$('#' + elemento).removeClass('btn_adicionar');
		$('#' + elemento).addClass('btn_remover');
		$('#' + elemento).attr({title:'Recolher'});
	}
	else
	{
		$('#' + elemento).removeClass('btn_remover');
		$('#' + elemento).addClass('btn_adicionar');
		$('#' + elemento).attr({title:'Expandir'});
	}
	$('#div_' + elemento).toggle('slow');
} // fecha função grid_proponente()

/**
 * Ações que serão executadas após o carregamento da página
 */
$(document).ready(function()
{
	$('input[name=grid-proponente]').click(function()
	{
		grid_proponente(this.id);return false;
	});
});
//-->
</script>