<?php
/**
 * PROPONENTE: Solicitação de alteração de dados do Proponente do Projeto
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 30/03/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Ministério da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

    require_once "inc/menu.inc.php"; // menu
    // define os valores dos campos do formulário, se será lido o dado original ou o dado readequado
    $CNPJCPF        = isset($this->dadosSR['CNPJCPF'])         ? Validacao::mascaraCPFCNPJ($this->escape($this->dadosSR['CNPJCPF'])) : Validacao::mascaraCPFCNPJ($this->escape($this->dadosAP['CNPJCPF']));
    $NomeProponente = isset($this->dadosSR['NomeProponente'])  ? $this->escape($this->dadosSR['NomeProponente'])                     : $this->escape($this->dadosAP['NomeProponente']);
    $Justificativa  = isset($this->pedido['dsJustificativa'])  ? $this->pedido['dsJustificativa']                                    : '';
?>

<script type="text/javascript">
    /**
     * Funções que são chamadas após a página ser carregada
     */
    $(document).ready(function(){
        // máscaras dos campos
        $("#cpfcnpj").keyup(function(){
            mascaraCnpjCpf(this);
        });

        // validação e cadastro de novo proponente
        $("#cpfcnpj").blur(function(){
            $('html').css('overflow', 'hidden');
            $("body").append("<div id='divDinamicaAgentes'></div>");
            $("#divDinamicaAgentes").html("");
            $('#divDinamicaAgentes').html("<br><br><center>Carregando dados...</center>");
            $.ajax({
                url : '<?php echo $this->url(array('module' => 'agente', 'controller' => 'agentes', 'action' => 'incluiragente')); ?>',
                data : {
                    cpf: cpfCnpj,
                    caminho: "",
                    modal : "s",
                    modulo : "readequacao"
                },
                success: function(data) {
                    if (data.error){
                        $('#divDinamicaAgentes').html(data.msg);
                    } else {
                        $('#divDinamicaAgentes').html(data);
                    }
                },
                complete: function() {
                    $("#resultadoFinalizar").html("");
                },
                type : 'post'
            });

            $("#divDinamicaAgentes").dialog({
                resizable: true,
                width:$(window).width() - 100,
                height:$(window).height() - 100,
                modal: true,
                autoOpen:true,
                draggable:false,
                title: 'Cadastrar proponente',
                buttons: {
                    'Fechar': function() {
                        $("#divDinamicaAgentes").remove();
                        $(this).dialog('close');
                        $('html').css('overflow', 'auto');
                        JSVerificaIncentivador(cpfCnpj,idColunaBotaoCorrigir);
                    }
                },
                close: function(){
                    $("#divDinamicaAgentes").remove();
                    $(this).dialog('close');
                    $('html').css('overflow', 'auto');
                    JSVerificaIncentivador(cpfCnpj,idColunaBotaoCorrigir);
                }
            });
        });
    }); // fim $(document).ready()
</script>

<?php
    $urlPronac = null;
    $urlPronac = (isset($this->idPronac)) ? "?idPronac=".Seguranca::encrypt($this->idPronac) : "";
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => ''), null, true); ?><?php echo $urlPronac; ?>" title="Ir para In&iacute;cio" onclick="carregandoModal();">Consultar dados do Projeto</a></li>
        <li>Readequa&ccedil;&atilde;o de projeto</li>
        <li class="last">Proponente</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Solicitar altera&ccedil;&atilde;o no projeto - Proponente <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

    <!-- ========== INÍCIO TOPO PROJETO ========== -->
    <?php require_once "inc/topo.inc.php"; ?>
    <!-- ========== FIM TOPO PROJETO ========== -->


    <!-- ========== INÍCIO FORMULÁRIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'proponente')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="stPedidoAlteracao" id="stPedidoAlteracao" value="T" />
        <input type="hidden" name="siVerificacao" id="siVerificacao" value="0" />
        <input type="hidden" name="tpAlteracaoProjeto" id="tpAlteracaoProjeto" value="1" />
        <table class="tabela">
            <tr>
                <th>Novo Proponente</th>
            </tr>
        </table>
        <table class="tabela">
            <tr class="destacar bold">
                <td align="center"><label for="cpfcnpj">CPF/CNPJ</label></td>
            </tr>
            <tr>
                <td><input type="text" name="cpfcnpj" id="cpfcnpj" class="input_simples w99p" maxlength="18" value="<?php echo $CNPJCPF; ?>" /></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="nome">NOME DO PROPONENTE</label></td>
            </tr>
            <tr>
                <td><input type="text" name="nome" id="nome" class="input_simples w99p" maxlength="300" value="<?php echo $NomeProponente; ?>" /></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="justificativa">JUSTIFICATIVA</label></td>
            </tr>
            <tr>
                <td>
                    <textarea name="justificativa" id="justificativa" class="textarea_simples w99p" rows="7" cols=""><?php echo $Justificativa; ?></textarea>
                    <span style="float: left; color: red;">Limite máximo de 600 caracteres</span>
                </td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="arquivo">ANEXOS</label></td>
            </tr>
            <tr>
                <td>
                    <div>
                        <span style="float: left; margin-right: 10px;"><input type="file" name="arquivo[]" id="arquivo" class="multi input_simples w99p" accept="pdf" /></span>
                        <span style="float: left; color: red;">Tamanho máximo de 5 MB</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <?php if (count($this->arquivos) > 0){ ?>
                    <?php foreach ($this->arquivos as $a){ ?>
                    <div id="excluir_arq<?php echo $a->idPedidoAlteracao . $a->idArquivo; ?>">
                        <input type="button" class="btn_exclusao btnsModReadequacao" title="Excluir Arquivo" onclick="excluir_arq_readeq('<?php echo $a->idPedidoAlteracao; ?>', '<?php echo $a->idArquivo; ?>', '<?php echo $a->nmArquivo; ?>');" />
                        <a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')) . '?id=' . $a->idArquivo; ?>" title="Abrir Arquivo"><?php echo $a->nmArquivo; ?></a>
                    </div>
                    <?php } ?>
                    <?php } else { ?>
                        Nenhum arquivo encontrado!
                    <?php } ?>
                </td>
            </tr>
        </table>

        <table class="tabela btnsModReadequacao">
            <tr>
                <td align="center">
                    <input type="submit" name="btn_salvar" id="btn_salvar" class="btn_salvar" value=" " title="Salvar" />
                    <input type="reset" name="btn_cancelar" id="btn_cancelar" class="btn_cancelar" value=" " title="Cancelar" />
                </td>
            </tr>
        </table>

    </form>
    <!-- ========== FIM FORMULÁRIO ========== -->


    <!-- ========== INÍCIO HISTÓRICO ========== -->
    <div id="historico"></div>
    <script type="text/javascript">
        carregaDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-proponente')); ?>', 'historico');
    </script>
    <!-- ========== FIM HISTÓRICO ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />
