<script type="text/javascript">
    $(document).ready(function()
    { 

        $("#frmDeclaracao").validate({
            rules: {
                deacordo: { required: true }
            },
            messages: {
                deacordo: { required: " Obrigat&oacute;rio aceite na declara&ccedil;&atilde;o de responsabilidade", maxlength:"" }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });

        $('#btn_sair').click(function(){
            window.location='<?php echo $this->url(array('controller' => 'manterpropostaincentivofiscal', 'action' => 'index')); ?>';
        });

    });
</script>

<style>
    label.error{ color:red; font-weight: normal; }
</style>

<!-- ===== -->
<!-- ========== FIM TITULO ========== -->

 
<style>
    .texto{
        font-size: 14px;
        padding: 1em;
        
    }
    </style>
<div style="width:1200px; height: 400px; overflow: auto; text-align:justify;">   

<form name="frmDeclaracao" id="frmDeclaracao" action="<?php echo $this->acao; ?>" method="post">
    <input type="hidden" name="idAgente" id="idAgente" value="<?php echo $this->agente; ?>"/>
    <br/>
    <table class="tabela" border="0" cellspacing="1" style="margin: 0px;">
        <tr>
            <th>
                DECLARA&Ccedil;&Atilde;O DE RESPONSABILIDADE
            </th>
        </tr>
        <tr>
            <td class="texto">
                DECLARA&Ccedil;&Atilde;O DE RESPONSABILIDADE<br>
                <br>
                DECLARO para todos os fins de direito, estar ciente da obrigatoriedade de:<br>
                <br>TER CONHECIMENTO<br>
                <br>
                i.	sobre a legisla&ccedil;&atilde;o referente ao benef&iacute;cio fiscal pretendido e das normas relativas &agrave; utiliza&ccedil;&atilde;o de recursos p&uacute;blicos e respectivos regulamentos;<br>
                <br>
                ii.	da veda&ccedil;&atilde;o para apresenta&ccedil;&atilde;o de proposta por pessoa f&iacute;sica ou pessoa jur&iacute;dica de direito privado que, respectivamente, seja ou tenha como dirigentes, propriet&aacute;rios ou controladores:<br>
                <br>
                a.	agente pol&iacute;tico de Poder ou do Minist&eacute;rio P&uacute;blico, tanto quanto dirigente de &oacute;rg&atilde;o ou entidade da administra&ccedil;&atilde;o p&uacute;blica, de qualquer esfera governamental, ou respectivo c&ocirc;njuge ou companheiro, bem como parente em linha reta, colateral ou por afinidade, at&eacute; o terceiro grau; e<br>
                <br>
                b.	servidor p&uacute;blico do Minist&eacute;rio da Cultura ou de suas entidades vinculadas, bem como seus respectivos c&ocirc;njuges, companheiros e parentes em linha reta, colateral ou por afinidade, at&eacute; o terceiro grau.<br>
                <br>
                iii.	da veda&ccedil;&atilde;o para transfer&ecirc;ncia de saldos n&atilde;o utilizados para outros projetos aprovados pelo Minist&eacute;rio da Cultura, ressalvada a hip&oacute;tese prevista no art. 68, par&aacute;grafo &uacute;nico, da Instru&ccedil;&atilde;o Normativa n&ordm; 1, de 9/2/2012.;<br>
                <br>
                iv.	da veda&ccedil;&atilde;o de doa&ccedil;&atilde;o ou patroc&iacute;nio efetuado a pessoa ou institui&ccedil;&atilde;o vinculada ao agente. Consideram-se vinculados ao doador ou patrocinador:<br>
                <br>
                a.	a pessoa jur&iacute;dica da qual o doador ou patrocinador seja titular, administrador, gerente, acionista ou s&oacute;cio, na data da opera&ccedil;&atilde;o, ou nos doze meses anteriores;<br>
                <br>
                b.	o c&ocirc;njuge, os parentes at&eacute; o terceiro grau, inclusive os afins, e os dependentes do doador ou patrocinador ou dos titulares, administradores, acionistas ou s&oacute;cios de pessoa jur&iacute;dica vinculada ao doador ou patrocinador, nos termos da al&iacute;nea anterior;<br>
                <br>
                c.	outra pessoa jur&iacute;dica da qual o doador ou patrocinador seja s&oacute;cio.<br>
                <br>
                v.	que a incorreta utiliza&ccedil;&atilde;o dos recursos do incentivo sujeitam o incentivador ou proponente ou ambos, &agrave;s san&ccedil;&otilde;es penais e administrativas, previstas na Lei n&ordm; 8.313, de 1991, e na Legisla&ccedil;&atilde;o do Imposto de Renda e respectivos regulamentos.<br>
                <br>MANTER comprovantes documentais das informa&ccedil;&otilde;es constantes no cadastro das propostas culturais, assim como das fases subsequentes de aprova&ccedil;&atilde;o, acompanhamento e presta&ccedil;&atilde;o de contas;<br>
                <br>ATUALIZAR minimamente a cada 6 (seis) meses, os dados cadastrais junto ao banco de dados do Sistema MinC;<br>
                <br>PERMANECER em situa&ccedil;&atilde;o de regularidade fiscal, tribut&aacute;ria e com a seguridade social durante toda a tramita&ccedil;&atilde;o da proposta e do projeto cultural;<br>
                <br>SABER que nenhuma institui&ccedil;&atilde;o benefici&aacute;ria poder&aacute; ressarcir-se de despesas efetuadas em data anterior &agrave; da publica&ccedil;&atilde;o da portaria de aprova&ccedil;&atilde;o e autoriza&ccedil;&atilde;o para capta&ccedil;&atilde;o de recursos, conforme o disposto no art. 35, &sect;1&deg; do Decreto 5.761, de 2006 e par&aacute;grafo &uacute;nico e caput do art. 45 da Instru&ccedil;&atilde;o Normativa n&ordm; 1, de 9/2/2012, e que a n&atilde;o observ&acirc;ncia desta determina&ccedil;&atilde;o acarretar&aacute; a devolu&ccedil;&atilde;o do recurso captado ao Fundo Nacional de Cultura ? FNC. <br>
                <br>ACATAR os valores definidos pelo Minist&eacute;rio da Cultura na portaria de aprova&ccedil;&atilde;o do projeto cultural ou, em caso de discord&acirc;ncia, formalizar pedido de reconsidera&ccedil;&atilde;o em at&eacute; 10 (dez) dias, conforme o disposto art. 40 da Instru&ccedil;&atilde;o Normativa n&ordm; 1, de 9/2/2012.<br>
                <br>PROMOVER a execu&ccedil;&atilde;o do objeto do projeto rigorosamente na forma e prazos estabelecidos;<br>
                <br>APLICAR os recursos captados exclusivamente na consecu&ccedil;&atilde;o do objeto, comprovando seu bom e regular emprego, bem como os resultados alcan&atilde;ados;<br>
                <br>COMPROVAR que disp&otilde;e de contrapartida, quando exig&iacute;vel, ou assegurar o provimento tempestivo de recursos, pr&oacute;prios ou de terceiros, complementares ao valor global da proposta, observado o disposto no art. 48, &sect; 3&ordm;, do Decreto n&ordm; 5.761, de 2006;<br>
                <br>PERMITIR E FACILITAR aos &oacute;rg&atilde;os competentes do MinC, ou a quem este indicar, o acesso a toda documenta&ccedil;&atilde;o, depend&ecirc;ncias e locais do projeto, bem como atender &agrave;s solicita&ccedil;&otilde;es de informa&ccedil;&otilde;es, reparos, altera&ccedil;&otilde;es, substitui&ccedil;&otilde;es ou regulariza&ccedil;&otilde;es de situa&ccedil;&otilde;es apontadas, no prazo estabelecido;<br>
                <br>DAR PUBLICIDADE, na promo&ccedil;&atilde;o e divulga&ccedil;&atilde;o do projeto, ao apoio do Minist&eacute;rio da Cultura, com observ&acirc;ncia dos modelos constantes do Manual de Uso das Marcas do Pronac, dispon&iacute;vel no portal do Minist&eacute;rio da Cultura (<a href="www.cultura.gov.br" target="_blank">www.cultura.gov.br</a>);<br>
                <br>PRESTAR CONTAS dos valores captados, depositados e aplicados, bem como dos resultados do projeto, nas condi&ccedil;&otilde;es e prazos fixados ou sempre que for solicitado;<br>
                <br>DEVOLVER em valor atualizado, o saldo dos recursos captados e n&atilde;o utilizados na execu&ccedil;&atilde;o do projeto, mediante recolhimento ao Fundo Nacional da Cultura (FNC), conforme instru&ccedil;&otilde;es dispostas no portal do Minist&eacute;rio da Cultura (<a href="www.cultura.gov.br" target="_blank">www.cultura.gov.br</a>).<br>
                <br>Assim, COMPROMETO-ME a:<br>
                <br>ACOMPANHAR e SANAR tempestivamente qualquer solicita&ccedil;&atilde;o das &aacute;reas t&eacute;cnicas do Minist&eacute;rio da Cultura;<br>
                <br>INSERIR no or&atilde;amento da proposta aquisi&ccedil;&atilde;o de material permanente apenas quando comprovadamente representar a op&ccedil;&atilde;o de maior economicidade ou constituir item indispens&aacute;vel &agrave; execu&ccedil;&atilde;o do objeto da proposta cultural, em detrimento da loca&ccedil;&atilde;o, devendo o proponente, em qualquer caso, realizar cota&ccedil;&atilde;o pr&eacute;via de pre&atilde;os no mercado, observados os princ&iacute;pios da impessoalidade e da moralidade;<br>
                <br>DESTINAR para fins culturais, todo e qualquer bem ou material permanente a ser adquirido ou produzido com recursos de incentivo fiscal, ap&oacute;s a finaliza&ccedil;&atilde;o do projeto ou dissolu&ccedil;&atilde;o da institui&ccedil;&atilde;o. No caso de direcionar o bem a outra entidade de natureza cultural, apresentar recibo quando do envio da presta&ccedil;&atilde;o de contas;<br>
                <br>OBTER E APRESENTAR AO MINC antes do in&iacute;cio de execu&ccedil;&atilde;o do projeto, alvar&aacute;(s) ou autoriza&ccedil;&atilde;o(&otilde;es) equivalente(s) emitida(s) pelo(s) &oacute;rg&atilde;o(s) p&uacute;blico(s) competente(s), caso alguma(s) da(s) atividade(s) decorrentes do projeto sejam executadas em espa&ccedil;os p&uacute;blicos;<br>
                <br>OBTER E APRESENTAR AO MINC antes do in&iacute;cio de execu&ccedil;&atilde;o do projeto, declara&ccedil;&atilde;o de autoriza&ccedil;&atilde;o dos titulares dos direitos autorais, conexos e de imagem em rela&ccedil;&atilde;o aos acervos, &agrave;s obras e imagens de terceiros como condi&ccedil;&atilde;o para utiliz&aacute;-los no projeto; e<br>
                <br>Por fim, ATESTO serem fidedignas as informa&ccedil;&otilde;es prestadas no preenchimento dos formul&aacute;rios, bem como de outras documenta&ccedil;&otilde;es juntadas ao longo da tramita&ccedil;&atilde;o do projeto.<br>

<!--

                <p><strong>DECLARO, ainda, para todos os fins de direito, estar ciente da obrigatoriedade de:</strong></p>
                
                <p>&bull;TER CONHECIMENTO</p> 
                
                <p><i>&nbsp;&nbsp;i.	sobre a legisla&ccedil;&atilde;o referente ao benef&iexcl;cio fiscal pretendido e das normas relativas &agrave; utiliza&ccedil;&atilde;o de recursos p&uacute;blicos e respectivos regulamentos;</i></p>
                
                <p><i>&nbsp;&nbsp;ii.	que &eacute; vedada a apresenta&ccedil;&atilde;o de proposta por pessoa f&iexcl;sica ou pessoa jur&iexcl;dica de direito privado que, respectivamente, seja ou tenha como dirigentes, propriet&aacute;rios ou controladores:</i></p>
                
                <p><i>&nbsp;&nbsp;&nbsp;a.	agente pol&iexcl;tico de Poder ou do Minist&eacute;rio P&uacute;blico, tanto quanto dirigente de &oacute;rg&atilde;o ou entidade da administra&ccedil;&atilde;o p&uacute;blica, de qualquer esfera governamental, ou respectivo c&ocirc;njuge ou companheiro, bem como parente em linha reta, colateral ou por afinidade, at&eacute; o terceiro grau; e</i></p>
                
                <p><i>&nbsp;&nbsp;&nbsp;b.	servidor p&uacute;blico do Minist&eacute;rio da Cultura ou de suas entidades vinculadas, bem como seus respectivos c&ocirc;njuges, companheiros e parentes em linha reta, colateral ou por afinidade, at&eacute; o terceiro grau.</i></p>

                <p><i>&nbsp;&nbsp;iii.	que &eacute; vedada a transfer&ecirc;ncia de saldos n&atilde;o utilizados para outros projetos aprovados pelo Minist&eacute;rio da Cultura, ressalvada a hip&oacute;tese prevista no art. 62, par&aacute;grafo &uacute;nico, da Instru&ccedil;&atilde;o Normativa  n&deg; 01, de 05/10/2010.</i></p>

                <p>MANTER comprovantes documentais das informa&ccedil;&otilde;es constantes no cadastro das propostas culturais, assim como das fases subsequentes de aprova&ccedil;&atilde;o, acompanhamento, e presta&ccedil;&atilde;o de contas, bem como atualizar minimamente a cada 6 (seis) meses, os dados cadastrais junto ao banco de dados do Sistema MinC;</p>

				<p>PERMANECER em situa&ccedil;&atilde;o de regularidade fiscal, tribut&aacute;ria e com a seguridade social em todas as fases da proposta;
				
				<p>SABER que nenhuma institui&ccedil;&atilde;o benefici&aacute;ria poder&aacute; ressarcir-se de despesas efetuadas em data anterior &agrave; da publica&ccedil;&atilde;o da portaria de aprova&ccedil;&atilde;o e autoriza&ccedil;&atilde;o para capta&ccedil;&atilde;o de recursos, conforme o disposto no art. 35, &sect;1&deg; do Decreto 5.761, de 27/04/2006 e par&aacute;grafos e caput do art. 40 da Instru&ccedil;&atilde;o Normativa n&deg; 1, de 05/10/2010, e que a n&atilde;o observ&acirc;ncia desta determina&ccedil;&atilde;o acarretar&aacute; na devolu&ccedil;&atilde;o do recurso captado ao Fundo Nacional de Cultura &minus;  FNC. </p>
				
				<p>ACATAR os valores definidos pelo Minist&eacute;rio da Cultura na portaria de aprova&ccedil;&atilde;o da proposta cultural; em caso de discord&acirc;ncia quanto aos valores definidos pelo Minist&eacute;rio da Cultura, formalizar pedido de reconsidera&ccedil;&atilde;o em at&eacute; 10 (dez) dias, a contar da publica&ccedil;&atilde;o da aprova&ccedil;&atilde;o do projeto;</p>
				
				<p>PROMOVER a execu&ccedil;&atilde;o do objeto da proposta na forma e prazos estabelecidos;</p>
				
				<p>APLICAR os recursos captados exclusivamente na consecu&ccedil;&atilde;o do objeto, comprovando seu bom e regular emprego, bem como os resultados alcan&ccedil;ados;</p>
				
				<p>COMPROVAR que disp&otilde;e de contrapartida, quando exig&iexcl;vel, ou assegurar o provimento tempestivo de recursos, pr&oacute;prios ou de terceiros, complementares ao valor global da proposta, observado o disposto no art. 48, &sect; 3&deg;, do Decreto n&deg; 5.761, de 2006;</p>
				
				<p>PERMITIR E FACILITAR aos &oacute;rg&atilde;os competentes do MinC, ou a quem este indicar, o acesso a toda documenta&ccedil;&atilde;o, depend&ecirc;ncias e locais da proposta, bem como atender &agrave;s solicita&ccedil;&otilde;es de informa&ccedil;&otilde;es, reparos, altera&ccedil;&otilde;es, substitui&ccedil;&otilde;es ou regulariza&ccedil;&otilde;es de situa&ccedil;&otilde;es apontadas, no prazo estabelecido;</p>
				
				<p>DAR PUBLICIDADE, na promo&ccedil;&atilde;o e divulga&ccedil;&atilde;o do projeto, ao apoio do Minist&eacute;rio da Cultura, com observ&acirc;ncia dos modelos constantes do Manual de Uso das Marcas do Pronac, dispon&iexcl;vel no portal do Minist&eacute;rio da Cultura <a href="www.cultura.gov.br" target="_blank">(www.cultura.gov.br)</a>;</p>
				
				<p>PRESTAR CONTAS dos valores captados, depositados e aplicados, bem como dos resultados do projeto, nas condi&ccedil;&otilde;es e prazos fixados ou sempre que for solicitado;
				 
				<p>DEVOLVER em valor atualizado, o saldo dos recursos captados e n&atilde;o aplicados na proposta, mediante recolhimento ao Fundo Nacional da Cultura (FNC), conforme instru&ccedil;&otilde;es dispostas no portal do Minist&eacute;rio da Cultura <a href="www.cultura.gov.br" target="_blank">(www.cultura.gov.br)</a>; </p>
				
				<p>DEIXAR de realizar o projeto, sem justa causa, ou de que a incorreta utiliza&ccedil;&atilde;o dos recursos do incentivo sujeitam o incentivador ou proponente ou ambos, &agrave;s san&ccedil;&otilde;es penais e administrativas, previstas na Lei n&deg;  8.313, de 23 de dezembro de 1991, e na Legisla&ccedil;&atilde;o do Imposto de Renda e respectivos regulamentos.</p>
				
				<p><strong>COMPROMETO-ME:</strong></p>
				
				<p>ACOMPANHAR e SANAR tempestivamente qualquer solicita&ccedil;&atilde;o das &aacute;reas t&eacute;cnicas do Minist&eacute;rio da Cultura;
				
				<p>INSERIR no or&ccedil;amento do projeto aquisi&ccedil;&atilde;o de material permanente apenas quando comprovadamente representar a op&ccedil;&atilde;o de maior economicidade ou constituir item indispens&aacute;vel &agrave; execu&ccedil;&atilde;o do objeto da proposta cultural, em detrimento da loca&ccedil;&atilde;o, devendo o proponente, em qualquer caso, realizar cota&ccedil;&atilde;o pr&eacute;via de pre&ccedil;os no mercado, observados os princ&iexcl;pios da impessoalidade e da moralidade;</p>
				
				<p>APRESENTAR, no momento do cadastramento da proposta cultural e caso haja aquisi&ccedil;&atilde;o de material permanente, Termo de Compromisso declarando a destina&ccedil;&atilde;o cultural do bem, ap&oacute;s a finaliza&ccedil;&atilde;o do projeto ou dissolu&ccedil;&atilde;o da institui&ccedil;&atilde;o e, se direcionar esse bem a outra entidade de natureza cultural, apresentar o recibo, quando da presta&ccedil;&atilde;o de contas;</p>
				
				<p>OBTER E APRESENTAR AO MINC antes do in&iexcl;cio de execu&ccedil;&atilde;o do projeto, alvar&aacute;(s) ou autoriza&ccedil;&atilde;o(&otilde;es) equivalente(s) emitida(s) pelo(s) &oacute;rg&atilde;o(s) p&uacute;blico(s) competente(s), caso alguma(s) da(s) atividade(s) decorrentes do projeto sejam executadas em espa&ccedil;os p&uacute;blicos;</p>
				
				<p>OBTER E APRESENTAR AO MINC antes do in&iexcl;cio de execu&ccedil;&atilde;o do projeto, declara&ccedil;&atilde;o de autoriza&ccedil;&atilde;o dos titulares dos direitos autorais, conexos e de imagem em rela&ccedil;&atilde;o aos acervos, &agrave;s obras e imagens de terceiros como condi&ccedil;&atilde;o para utiliz&aacute;-los no projeto; e</p>
				
				<p>SER fidedignas as informa&ccedil;&otilde;es prestadas no preenchimento dos formul&aacute;rios, bem como de outras documenta&ccedil;&otilde;es juntadas ao longo da tramita&ccedil;&atilde;o do projeto.</p>

-->
                <p>&nbsp;</p>
                <p><label><input type="checkbox"  id="deacordo" name="deacordo"><span style="color: red; font-weight: bold; font-size: 13px; margin-left: 0.7em;">De acordo</span></label></p>

            </td>
        </tr>
    </table>
    <br/>
    <center>
        <input id="btn_confirmar" type="submit" value=" " name="incluir" style="cursor: pointer; width: 88px;" class="btn_confirmar"  />&nbsp;
    </center>
    <br/>
</form>
</div>
<div id="mostra"></div>
