<?php echo $this->action('menu', 'menu', 'proposta', array('idPreProjeto' => $this->idPreProjeto));  ?>

<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Encaminhar Proposta Cultural ao Minist&eacute;rio da Cidadania</h1>

                    <?php
                    gerarNovoBreadCrumb(array(
                        $this->layout['listagem'],
                        array('Encaminhar para o Minist&eacute;rio da Cidadania' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="content">
            <div id="conteudo" class="card-panel">
                <?php if(!$this->resultado->Observacao) : ?>
                    <table class="tabela">
                        <tr>
                            <th colspan="2">Sua proposta possui as pend&ecirc;ncias listadas abaixo</th>
                        </tr>
                        <tr>
                            <th>Descri&ccedil;&atilde;o</th>
                            <th>Observa&ccedil;&atilde;o</th>
                        </tr>
                        <?php foreach ($this->resultado as $valor) : ?>
                            <tr class="fundo">
                                <td width="90%">
                                    <?php if (is_array($valor->Url)) : ?>
                                        <a href="<?php echo $this->url($valor->Url, null, true); ?>">
                                            <?php echo strip_tags($valor->dsInconsistencia); ?>
                                        </a>
                                    <?php else: ?>
                                        <?php echo strip_tags($valor->dsInconsistencia); ?>
                                    <?php endif; ?>
                                </td>
                                <td class="centro" width="10%" nowrap>
                                    <img alt="" src="<?php echo $this->baseUrl(); ?>/public/img/btn_excluir.gif"/>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <tr>
                            <td colspan="2" class="center">
                                <button class="btn waves-effect waves-light disabled" name="action">Finalizar altera&ccedil;&atilde;o e enviar
                                    <i class="material-icons right">send</i>
                                </button>
                            </td>
                        </tr>
                    </table>
                <?php else: ?>
                    <div class="row">
                        <form action="<?php echo $this->acao; ?>" method="post" id="frmProposta" name="frmProposta"
                              enctype="">
                            <input type="hidden" name="idPreProjeto" id="idPreProjeto"
                                   value="<?php echo isset($this->proposta['idpreprojeto']) ? $this->proposta['idpreprojeto'] : '' ?>">
                            <input type="hidden" name="acao" id="acao" value="alterar">
                            <input type="hidden" name="idagente"
                                   value="<?php echo isset($this->proponente['idagente']) ? $this->proponente['idagente'] : '' ?>">
                            <input type="hidden" name="url"
                                   value="<?php echo isset($this->url) ? $this->url : '' ?>">
                            <input type="hidden" name="confirmarenvioaominc"
                                   value="<?php echo true ?>">

                            <div class="row">
                                <div class="col s12">
                                    <br>
                                    <p class="caption">Ao finalizar o cadastro da proposta n&atilde;o ser&aacute; poss&iacute;vel editar os dados.
                                        Sua proposta ser&aacute; encaminhada ao Minist&eacute;rio da Cidadania.  </p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12 center">
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Finalizar altera&ccedil;&atilde;o e enviar
                                        <i class="material-icons right">send</i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                <?php endif; ?>
        </div>
    </div>
</div>
