<div class="container-fluid white">
    <div class="row">
        <?php echo $this->partial("inc/menu.phtml", $this); // menu ?>
        <div class="col s10 m12 l10">

            <?php
            gerarBreadCrumb(array(
                $this->layout['listagem'],
                array('Detalhes t&eacute;cnicos' => '')
            ));
            ?>
            <div id="titulo">
                <div>Encaminhar Proposta Cultural ao Minist&eacute;rio da Cultura</div>
            </div>

            <div id="conteudo">
                <table class="tabela">
                    <tr>
                        <th>Descri&Ccedil;&Atilde;o</th>
                        <th>Observa&ccedil;&atilde;o</th>
                    </tr>
                    <?php foreach ($this->resultado as $valor) { ?>
                        <tr class="fundo">
                            <td width="90%" <?php if ($valor->Observacao != 'PENDENTE' && $valor->Observacao != 'OK') {
                                echo 'colspan="2" class="centro"';
                            } ?>>
                                <?php if (is_array($valor->Url)) : ?>
                                    <a href="<?php echo $this->url($valor->Url, null, true); ?>">
                                        <?php echo $valor->Descricao; ?>
                                    </a>
                                <?php else: ?>
                                    <?php echo $valor->Descricao; ?>
                                <?php endif; ?>
                            </td>
                            <?php if ($valor->Observacao == 'PENDENTE' || $valor->Observacao == 'OK') { ?>
                                <td class="centro" width="10%" nowrap>
                                    <?php if ($valor->Observacao == 'PENDENTE') { ?>
                                        <img alt="" src="<?php echo $this->baseUrl(); ?>/public/img/btn_excluir.gif"/>
                                    <?php } else if ($valor->Observacao == 'OK') { ?>
                                        <img alt="" src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png"/>
                                    <?php } ?>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>