<table class="tabela">
    <tr>
        <th width="125px">N&uacute;mero da Proposta</th>
        <th>Nome da Proposta</th>
        <th>Nome do Proponente</th>
        <th>Situa&ccedil;&atilde;o</th>
    </tr>
    <?php foreach ($this->propostas as $prop) { //xd($prop['idPreProjeto']); ?>
        <?php
            $url = $this->url(array('controller' => 'manterpropostaincentivofiscal', 'action' => 'identificacaodaproposta', 'idPreProjeto' => $prop['idpreprojeto']));
        ?>
        <tr>
            <td class="centro"><a href="#" onclick="window.location='<?php echo $url; ?>'"><?php echo $prop['idpreprojeto']; ?></a></td>
            <td class="esquerda"><?php echo $prop['nomeprojeto']; ?></td>
            <td class="esquerda"><?php echo $prop['nomeproponente']; ?></td>
            <td class="esquerda"><?php echo $prop['movimentacao']['MovimentacaoNome']; ?></td>

        </tr>
        <?php } ?>
</table>