<div class="container-fluid white">
    <div class="row">
        <?php echo $this->partial("inc/menu.phtml", $this); // menu ?>
        <div class="col s10 m12 l10">

            <?php
            gerarBreadCrumb(array(
                $this->layout['listagem'],
                array('Responsabilidade Social' => '')
            ));
            ?>

            <div id="titulo" style="width: 100%;">
                <div><?php echo $this->layout['titleFull']; ?> - Responsabilidade Social</div>
            </div>
            <div class="clear-fix"></div>
            <div id="conteudo" class="section">
                <div class="row">
                    <form action="<?php echo $this->acao; ?>" method="post" id="frmProposta" name="frmProposta"
                          enctype="multipart/form-data">
                        <input type="hidden" name="idPreProjeto" id="idPreProjeto"
                               value="<?php echo isset($this->proposta['idpreprojeto']) ? $this->proposta['idpreprojeto'] : '' ?>">
                        <input type="hidden" name="acao" id="acao" value="alterar">
                        <input type="hidden" name="idagente"
                               value="<?php echo isset($this->proponente['idagente']) ? $this->proponente['idagente'] : '' ?>">
                        <input type="hidden" name="url"
                               value="<?php echo isset($this->url) ? $this->url : '' ?>">

                        <div class="row">
                            <div class="input-field col s12">
                                <p class="caption">
				  O campo Acessibilidade deve conter informa&ccedil;&otilde;es quanto &agrave; Acessibilidade
				  F&iacute;sica e Acessibilidade de Conte&uacute;do.
				  <br/>
				  A Acessibilidade F&Iacute;SICA deve oferecer facilitadores para a locomo&ccedil;&atilde;o no
				  espa&ccedil;o f&iacute;sico (banheiros, rampas, guias t&atilde;teis).
				  <br/>
				  A Acessibilidade de CONTE&Uacute;DO deve prever medidas para compreens&atilde;o do projeto
				  (Libras, Braille, audiodescri&ccedil;&atilde;o, legenda descritiva, visita sensorial).
                                </p>

                                <textarea id="acessibilidade" class="browser-default editor"
                                          name="acessibilidade" <?php echo isset($this->arrConfig['acessibilidade']['disabled']) ? 'disabled="disabled"' : '' ?>>
                                 <?php if (isset($this->proposta['acessibilidade'])) echo $this->proposta['acessibilidade']; ?>
                                </textarea>
                                <label for="acessibilidade" class="active">Acessibilidade *</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <p class="caption">
				  Descreva no campo Democratiza&ccedil;&atilde;o de Acesso a forma de distribui&ccedil;&atilde;o e
				  comercializa&ccedil;&atilde;o dos produtos da proposta.
				  <br/>
				  Apresente tamb&eacute;m outras medidas de amplia&ccedil;&atilde;o de acesso, tais como: ensaio
				  aberto, oficinas paralelas ou transmiss&atilde;o pela internet.
                                </p>
                                <textarea id="democratizacaodeacesso" class="browser-default editor"
                                          name="democratizacaodeacesso" <?php echo isset($this->arrConfig['democratizacaodeacesso']['disabled']) ? 'disabled="disabled"' : '' ?>>
                                    <?php if (isset($this->proposta['democratizacaodeacesso'])) echo $this->proposta['democratizacaodeacesso']; ?>
                                </textarea>
                                <label for="democratizacaodeacesso" class="active">Democratiza&ccedil;&atilde;o de
                                    Acesso
                                    *</label>
                            </div>
                        </div>

                        <?php if ($this->isEditavel) : ?>
                            <div class="row">
                                <div class="input-field col s12 center">
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Salvar
                                        <i class="material-icons right">send</i>
                                    </button>
                                </div>
                            </div>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function ($) {

        <?php  if ( !$this->isEditavel ) : ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>


        $("textarea.editor").each(function () {
            $(this).editorRico({
                altura: 400,
                maxchar: 8000,
                isLimitarCarateres : true,
                isDesabilitarEdicao: 0
            });
        });
    });
</script>
