<?php include_once 'scripts/admissibilidade/inc/menu.inc.php'; ?>
<!--<div id="breadcrumb">
    <ul>
        <li class="first"> <a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>" title="Ir para Projetos">Projetos</a></li>
        <li class="last">Listar Propostas</li>
    </ul>
</div>-->
<div id="titulo">
    <div>Admissibilidade de propostas - Despachos <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<div id="conteudo">
    <?php if(isset($this->itensDespacho[0])):?>
    <table class="tabela">
        <tr>
            <th>
                <?php echo $this->itensDespacho[0]->idProposta.' - '; echo $this->itensDespacho[0]->NomeProjeto;?>
            </th>
        </tr>
        <tr>
            <td align="center">
	    	<table>
                    <tr>
                        <th>Data</th>
                        <th>Despacho</th>
                        <th>Despachante</th>
                    </tr>
                    <?php
                    if(is_array($this->itensDespacho) and count($this->itensDespacho)>0)
                            foreach ($this->itensDespacho as $despacho){

                   ?>
                    <tr>
                        <td><?php echo str_replace(" ", " as ", data::dataBrasileira($despacho->Data)); ?></td>
                        <td align="center"><?php echo $despacho->Despacho ?></td>
                        <td align="center"><?php echo $despacho->Usuario ?></td>
                    </tr>
                    <?php
                            }
                    ?>
                </table>
            </td>
        </tr>
    </table>
    <?php else:?>
    <br>
    <br>
    <div class="centro">Nenhum Despacho encontrado para a Proposta.</div>
    <br>
    <br>
    <?php endif;?>
</div>
<!-- ========== FIM CONTEUDO ========== -->
<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />