<?php //include_once 'scripts/consultardadosprojeto/inc/menu.inc.php';   ?>
<!--<div id="breadcrumb">
    <ul>
        <li class="first"> <a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'index')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'prototipos', 'action' => 'projetos')); ?>" title="Ir para Projetos">Projetos</a></li>
        <li class="last">Listar Propostas</li>
    </ul>
</div>-->
<div id="titulo">
    <div>Admissibilidade de propostas - Imprimir etiqueta projeto <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<style type="text/css">
<!--
.mensagem {
    padding: 8px;
    border: darkgreen;
    background: #e3e3c7;
}
-->
</style>
<script type="text/javascript">
<!--
/*
 * Função responsável pela exibição ou ocultamento de conteúdo,
 * mudando a imagem.
 **/
$(document).ready(function() {
    window.print();
});
function abrirDinamico(elemento, obj) {
    if($(elemento).css('display') == 'none') {
        $(elemento).fadeIn('fast', function() {
            $('img', $(obj)).attr('src','<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png');
        });
    } else {
        $(elemento).fadeOut('fast', function() {
            $('img', $(obj)).attr('src','<?php echo $this->baseUrl(); ?>/public/img/navigation-baixo.PNG');
        });
    }
}
function toogleAjax(id, url){
    if(!url) {
        $('#'+id).toggle('slow');
    } else {
        elemento = '#'+id;
        if($(elemento).css('display') == 'none') {
            $(elemento).html('<img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /> ');
            $(elemento).fadeIn('fast');
            $.ajax({
                type: "POST",
                data: {
                    teste: 'testando'
                },
                url: url,
                success: function(data) {
                    $(elemento).html(data);
                }
            });
        } else {
            $(elemento).fadeOut('fast');
        }
    }
};
//-->
</script>
<div id="conteudo">
    <br />
    <table class="tabela">
        <tr>
            <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/102647.jpg" /></td>
        </tr>
        <tr>
            <td align="center">
                Processo
                <br />
                01400.006608/2010-88 - MinC
                <br />
                Proponente
                <br />
                GB Produtora
                <br />
                Projeto
                <br />
                Feira da Música do Sul 2010
            </td>
        </tr>
        <tr>
            <td align="center">
                <table class="tabela" id="proponente">
                    <tr>
                        <th align="left">
                            Identificação
                        </th>
                    </tr>
                    <tr id="identificacao">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>CNPJ / CPF </th>
                                    <th>Proponente </th>
                                </tr>
                                <tr>
                                    <td align="center">015.693.476-03 </td>
                                    <td align="center">Vinícius Feitosa da Silva </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            Endereço
                        </th>
                    </tr>
                    <tr id="endereco">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>Tipo de Endereço</th>
                                    <th>Tipo do Logradouro</th>
                                    <th>Logradouro</th>
                                    <th>Número</th>
                                    <th>Complemento</th>
                                    <th>Bairro</th>
                                    <th>Cidade</th>
                                    <th>UF</th>
                                    <th>CEP</th>
                                </tr>
                                <tr>
                                    <td align="center">Residencial</td>
                                    <td align="center">Outros</td>
                                    <td align="center">AC 2</td>
                                    <td align="center">21</td>
                                    <td align="center">Riacho 1</td>
                                    <td align="center">Riacho Fundo</td>
                                    <td align="center">Brasília</td>
                                    <td align="center">DF</td>
                                    <td align="center">71805-411</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            Telefones
                        </th>
                    </tr>
                    <tr id="telefones">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>Tipo </th>
                                    <th>UF </th>
                                    <th>DDD </th>
                                    <th>Número </th>
                                    <th>Divulgar </th>
                                </tr>
                                <tr>
                                    <td align="center">Celular</td>
                                    <td align="center">DF</td>
                                    <td align="center">61</td>
                                    <td align="center">9983-0222</td>
                                    <td align="center">Sim</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            E-mail
                        </th>
                    </tr>
                    <tr id="email">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th></th>
                                    <th>Tipo</th>
                                    <th>E-mail</th>
                                    <th>Para correspondência?</th>
                                    <th>Posso divulgar?</th>
                                </tr>
                                <tr>
                                    <td align="center">1</td>
                                    <td align="center">Particular</td>
                                    <td align="center">viniciusfesil@gmail.com</td>
                                    <td align="center">Sim</td>
                                    <td align="center">Não</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            Natureza
                        </th>
                    </tr>
                    <tr id="natureza">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>Direito</th>
                                    <th>Esfera</th>
                                    <th>Poder</th>
                                    <th>Administração</th>
                                </tr>
                                <tr>
                                    <td align="center" colspan="4">Não informado</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            Dirigente
                        </th>
                    </tr>
                    <tr id="dirigente">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>CPF</th>
                                    <th>Nome</th>
                                </tr>
                                <tr>
                                    <td align="center">015.693.476-03</td>
                                    <td align="center">Vinícius Feitosa da Silva</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">
                            Responsável
                        </th>
                    </tr>
                    <tr id="dirigente">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <th>CPF</th>
                                    <th>Nome</th>
                                </tr>
                                <tr>
                                    <td align="center">015.693.476-03</td>
                                    <td align="center">Vinícius Feitosa da Silva</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#projetoCultural', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Proposta cultural
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="projetoCultural">
                    <tr>
                        <th>Nº da Proposta</th>
                        <th>Título da Proposta</th>
                    </tr>
                    <tr>
                        <td align="center">23.698</td>
                        <td align="center">Proposta de teste de Prorrogação - Vinícius</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#informacoesComplementares', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Informações Complementares
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="informacoesComplementares">
                    <tr>
                        <th>É proposta de audiovisual?</th>
                        <th>Mecanismo</th>
                        <th>Agência Bancária</th>
                        <th>Dt. Início Execução</th>
                        <th>Dt. Final Execução</th>
                        <th>Dt. Fixa</th>
                        <th>Plano Atual</th>
                    </tr>
                    <tr>
                        <td align="center">Não</td>
                        <td align="center">Incentivo Fiscal</td>
                        <td align="center">47333</td>
                        <td align="center">23/02/2011</td>
                        <td align="center">24/02/2011</td>
                        <td align="center">Não</td>
                        <td align="center">Não</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#informacoesTombamento', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Informações sobre tombamento
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="informacoesTombamento">
                    <tr>
                        <th>Nº Ato Tombamento</th>
                        <th>Dt. Ato Tombamento</th>
                        <th>Esfera Tombamento</th>
                    </tr>
                    <tr>
                        <td align="center">987654321</td>
                        <td align="center">12/12/2011</td>
                        <td align="center">0</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <th align="center">Resumo do Projeto</th>
        </tr>
        <tr>
            <td align="center">Proposta de teste de Prorrogação - Vinícius Feitosa da Silva</td>
        </tr>
        <tr>
            <th align="center">Objetivos</th>
        </tr>
        <tr>
            <td align="center">Objetivossss s s s s Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Justificativa</th>
        </tr>
        <tr>
            <td align="center">Justificando o meu sono... Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Acessibilidade</th>
        </tr>
        <tr>
            <td align="center">Acessando a acessibilidade... Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Democratização de Acesso</th>
        </tr>
        <tr>
            <td align="center">Democratizando... Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Etapa de Trabalho</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Ficha Técnica</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Sinopse de obra</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Impacto Ambiental</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Especificações técnicas do produto</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr>
            <th align="center">Outras Informações</th>
        </tr>
        <tr>
            <td align="center">Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento - Teste de Desenvolvimento</td>
        </tr>
        <tr onclick="abrirDinamico('#planoDistribuicaoProduto', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Plano de Distribuição de Produto
            </th>
        </tr>
        <tr>
            <td align="center">
                <table class="tabela" id="planoDistribuicaoProduto">
                    <tr>
                        <th>Nome do Evento / Produto</th>
                        <th>Área</th>
                        <th>Segmento</th>
                        <th>Posição da Logomarca</th>
                        <th>Nº Exemplares / Ingressos</th>
                        <th>Distribuíção / Patrocinador</th>
                        <th>Distribuíção / Divulgação</th>
                        <th>Distribuíção / Beneficiários</th>
                        <th>Total Venda Normal</th>
                        <th>Total Venda Promocional</th>
                        <th>Preço Unitário Normal</th>
                        <th>Preço Unitário Promocional</th>
                        <th>Receita Prevista Venda Normal (R$)</th>
                        <th>Receita Prevista Venda Promocional (R$)</th>
                        <th>Total de Receita Prevista (R$)</th>
                    </tr>
                    <tr>
                        <td align="center">Acervo Bibliográfico e Documental</td>
                        <td align="center">Patrimônio Cultural</td>
                        <td align="center">Acervo</td>
                        <td align="center">Antes dos créditos finais</td>
                        <td align="center">200</td>
                        <td align="center">0</td>
                        <td align="center">0</td>
                        <td align="center">0</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">10.000,00</td>
                        <td align="center">10.000,00</td>
                        <td align="center">20.000,00</td>
                    </tr>
                    <tr>
                        <td align="center" colspan="4"><b>Total Geral</b></td>
                        <td align="center">200</td>
                        <td align="center">0</td>
                        <td align="center">0</td>
                        <td align="center">0</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">100</td>
                        <td align="center">10.000,00</td>
                        <td align="center">10.000,00</td>
                        <td align="center">20.000,00</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#planilhaOrcamentaria', $(this))" style="cursor:pointer">
            <th align="center">
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Planilha Orçamentária
            </th>
        </tr>
        <tr>
            <td align="center">
                <table class="tabela" id="planilhaOrcamentaria">
                    <tr>
                        <th colspan="8">Fonte de Recurso : Incentivo Fiscal Federal</th>
                    </tr>
                    <tr>
                        <td colspan="8">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="8"><b>Etapa: Custos Administrativos</b></td>
                    </tr>
                    <tr>
                        <td colspan="8">Acre / Rio Branco</td>
                    </tr>
                    <tr>
                        <th align="center"></th>
                        <th align="center">Item</th>
                        <th align="center">Em dias</th>
                        <th align="center">Unidade</th>
                        <th align="center">Quantidade</th>
                        <th align="center">Ocorrência</th>
                        <th align="center">Valor Unitário</th>
                        <th align="center">Total</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>A.R.T. de execução</td>
                        <td>5</td>
                        <td>Cachê</td>
                        <td>5,00</td>
                        <td>5,00</td>
                        <td>5,00</td>
                        <td>125,00</td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total UF</b></td>
                        <td><b>125,00</b></td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total da Etapa</b></td>
                        <td><b>125,00</b></td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total dos Custos Administrativos dos Produtos</b></td>
                        <td><b>125,00</b></td>
                    </tr>
                    <tr>
                        <th colspan="8">Acervo Bibliotecário e Documental</th>
                    </tr>
                    <tr>
                        <td colspan="8"><b>Etapa: Pré-Produção / Preparação</b></td>
                    </tr>
                    <tr>
                        <td colspan="8">Acre / Rio Branco</td>
                    </tr>
                    <tr>
                        <th align="center"></th>
                        <th align="center">Item</th>
                        <th align="center">Em dias</th>
                        <th align="center">Unidade</th>
                        <th align="center">Quantidade</th>
                        <th align="center">Ocorrência</th>
                        <th align="center">Valor Unitário</th>
                        <th align="center">Total</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>A.R.T. de execução</td>
                        <td>100</td>
                        <td>Cachê</td>
                        <td>100,00</td>
                        <td>100,00</td>
                        <td>100,00</td>
                        <td>1.000.000,00</td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total UF</b></td>
                        <td><b>1.000.000,00</b></td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total da Etapa</b></td>
                        <td><b>1.000.000,00</b></td>
                    </tr>
                    <tr>
                        <td colspan="7"><b>Total Mecanismos de Incentivo</b></td>
                        <td><b>1.000.125,00</b></td>
                    </tr>
                    <tr>
                        <th align="center" colspan="7">Total Geral(2)</th>
                        <td><b>1.000.125,00</b></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#fonteRecurso', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Fonte de Recurso
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="fonteRecurso">
                    <tr>
                        <th>Fonte de Recurso</th>
                        <th>Valor</th>
                    </tr>
                    <tr>
                        <td>Incentivo Fiscal</td>
                        <td>1.000.125,00</td>
                    </tr>
                    <tr>
                        <th>Total Geral (1)</th>
                        <td>1.000.125,00</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#localRealizacao', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Local de Realização
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="localRealizacao">
                    <tr>
                        <th>Pais</th>
                        <th>UF</th>
                        <th>Cidade</th>
                        <th>Dt. Início Execução</th>
                        <th>Dt. Final Execução</th>
                    </tr>
                    <tr>
                        <td>Brasil</td>
                        <td>Acre</td>
                        <td>Rio Branco</td>
                        <td>22/12/2011</td>
                        <td>31/03/2011</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#deslocamento', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Deslocamento
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="deslocamento">
                    <tr>
                        <th>Pais de Origem</th>
                        <th>UF de Origem</th>
                        <th>Cidade de Origem</th>
                        <th>Pais de Destino</th>
                        <th>UF de Destino</th>
                        <th>Cidade de Destino</th>
                        <th>Quantidade</th>
                    </tr>
                    <tr>
                        <td align="center" colspan="7">Não há registros para exibir</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#planoDivulgacao', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Plano de Divulgação
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="planoDivulgacao">
                    <tr>
                        <th>Peça de Divulgação</th>
                        <th>Veículo de Divulgação</th>
                    </tr>
                    <tr>
                        <td align="center">Adesivo de chão</td>
                        <td align="center">Internet</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#documentosAnexados', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Documentos Anexados
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="documentosAnexados">
                    <tr>
                        <th>Tipo de Documento</th>
                        <th>Nome do Documento</th>
                    </tr>
                    <tr>
                        <td align="center">PDF</td>
                        <td align="center">Documento 36</td>
                    </tr>
                    <tr>
                        <td align="center">Doc</td>
                        <td align="center">Documento 39</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr onclick="abrirDinamico('#historicoAvaliacoes', $(this))" style="cursor:pointer">
            <th>
                <img src="<?php echo $this->baseUrl(); ?>/public/img/navigation-right.png" id="imgDinamica" align="left"/>
                Histórico de Avaliações
            </th>
        </tr>
        <tr>
            <td>
                <table class="tabela" id="historicoAvaliacoes">
                    <tr>
                        <th>Data</th>
                        <th>Avaliação</th>
                    </tr>
                    <tr>
                        <td align="center">22/11/2010 10:41</td>
                        <td align="center">Proposta Cultural ENVIADA ao Ministério da Cultura para Conformidade Visual</td>
                    </tr>
                    <tr>
                        <td align="center">15/10/2010 01:21</td>
                        <td align="center">Ok.</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br />
    <table class="tabela">
    <tr>
    <td class="centro">
    	<input type="button" class="btn_incluir" title="Incluir" value=" " />
    	<input type="button" class="btn_imprimir" title="Imprimir" value=" " />
    	<input type="button" class="btn_sair" title="Sair" value=" " />
    </td>
    </tr>
    </table>
</div>
<!-- ========== FIM CONTEUDO ========== -->
<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />