<div class="container-fluid">
    <div class="row">
        <?= $this->action('menu', 'menu', 'proposta', array('idPreProjeto' => $this->idPreProjeto)); ?>
        <div class="content col s10 m12 l10 planilha-produtos">

            <div id="titulo">
                <div>
                    Produtos / Etapas / Itens j&aacute; cadastrados
                    <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span>
                </div>
            </div>
            <div id="conteudo">
                <?php if ($this->itemBuscado) : ?>
                    <div class="padding10">Item buscado: "<?= $this->itemBuscado; ?>"</div>
                    <input id="itemBuscado" type="hidden" name="itemBuscado" value="<?= $this->itemBuscado; ?>">
                <?php endif; ?>
                <?php if ($this->item == "" AND $this->tipopesquisa == 04) : ?>
                    <br/>
                    <div class="centro">Nenhum Produto/Etapa/Item</div>
                    <br/>
                <?php else : ?>
                    <div class="conteudoImprimivel" id="conteudoImprimivel">
                        <?php if (count($this->pretitem) > 0) : ?>
                            <table class="tabela">
                                <tr>
                                    <th>Produto</th>
                                    <th>Etapa</th>
                                    <th>Item</th>
                                </tr>
                                <?php foreach ($this->pretitem as $produto) : ?>
                                    <tr>
                                        <td>
                                            <?php echo $produto->Produto; ?>
                                        </td>
                                        <td>
                                            <?php echo $produto->Etapa; ?>
                                        </td>
                                        <td>
                                            <?php
                                            $item = str_replace(strtolower($this->itemBuscado), "<b class='green'>".$this->itemBuscado."</b>", strtolower($produto->Item));
                                            ?>
                                            <?= ucfirst($item); ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </table>
                        <?php else : ?>
                            <br/>
                            <div class="centro">Nenhum Produto/Etapa/Item</div>
                            <br/>
                        <?php endif; ?>

                        <br/><br/>

                        <form id="frmBusca" method="post" name="frmBusca"
                              action="<?php echo $this->url(array('module' => 'proposta', 'controller' => 'mantertabelaitens', 'action' => 'gerarpdf', 'idPreProjeto' => $this->idPreProjeto)); ?>">
                            <input type="hidden" name="tipoPesquisa" value="<?php echo $this->tipopesquisa; ?>">
                            <input type="hidden" name="produto" value="<?php echo $this->produto; ?>">
                            <input type="hidden" name="etapa" value="<?php echo $this->etapa; ?>">
                            <input type="hidden" name="item" value="<?php echo $this->item; ?>">
                        </form>
                    </div>
                <?php endif; ?>
                <form method="POST" id="formGerarPdf" name="formGerarPdf"
                      action="<?php echo $this->url(array('controller' => 'admissibilidade', 'action' => 'gerarpdf')); ?>"
                      style="display:none">
                    <textarea name="html" id="conteudoImprimir"></textarea>
                </form>

                <!-- <table class="tabela centro">
                    <tr>
                        <td>
                            <<input type="button" name="voltar" class="btn_voltar" value="" onclick="window.location='<?php echo $this->url(array('module' => 'proposta', 'controller' => 'mantertabelaitens', 'action' => 'consultartabelaitens', 'idPreProjeto' => $this->idPreProjeto)); ?>">
                            <input  type="button" name="imprimir" class="btn_imprimir" onclick='$("#conteudoImprimir").val($(".conteudoImprimivel").html()); $("#formGerarPdf").submit();'>
                        </td>
                    </tr>
                </table> -->
            </div>
            <br clear="all"/>
        </div>
    </div>
</div>
