<style type="text/css">
    label.error{ color:red; font-weight: normal; }
</style>

<?php echo $this->partial("inc/menu.phtml", $this); ?>

<div class="container-fluid">
    <div class="row">
        <div class="page-title">
            <div class="row">
                <div class="col s12 m9 l10">
                    <h1>Inclus&atilde;o de Novo Item/Etapa/Produto</h1>

                    <?php
                    gerarNovoBreadCrumb(array(
                        $this->layout['listagem'],
                        array('Inclus&atilde;o de Novo Item/Etapa/Produto' => '')
                    ));
                    ?>
                </div>
                <div class="col s12 m3 l2 right-align">
                    <a href="javascript:voltar();" title="P&aacute;gina Anterior" title="P&aacute;gina Anterior"
                       class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">arrow_back</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="content">
            <div id="conteudo" class="card-panel">
                <form name="form" id="form" action="<?php echo $this->url(array('module'=>'proposta', 'controller' => 'mantertabelaitens', 'action' => 'salvarsolicitacaoitem', 'idPreProjeto' => $this->idPreProjeto)); ?>" method="post">
                    <table class="tabela">
                        <tr class="titulo_tabela">
                            <th colspan="4">Novo Produto / Etapa / Item </th>
                        </tr>
                        <tr class="centro">
                            <td colspan="4">
                                <label style="font-weight: normal;"><input name="solicitacao" type="radio" value="associacao" id='associacao' checked/> Associar Item a Produto/Etapa</label>&nbsp; &nbsp;
                                <label style="font-weight: normal;"><input name="solicitacao" type="radio" value="novoitem" id='novoitem' /> Incluir novo Item</label>
                            </td>
                        </tr>
                    </table>

                    <table class="tabela">
                        <tr class="destacar bold">
                            <td width="33%">Produto <span class="red-text">*</span></td>
                            <td width="33%">Etapa <span class="red-text">*</span></td>
                            <td width="33%">Item <span class="red-text">*</span></td>
                        </tr>
                        <tr>
                            <td>
                                <select class="select_simples" name="produto" id="produto">
                                    <option value="">- Selecione - </option>
                                    <?php foreach($this->produto as $tbproduto) { ?>
                                    <option value="<?php echo $tbproduto->codproduto; ?>"> <?php echo $tbproduto->Produto; ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>
                                <select class="select_simples" name="etapa" id="etapa">
                                    <option value="">- Selecione - </option>
                                    <?php foreach($this->etapa as $tbetapa) { ?>
                                    <option value="<?php echo $tbetapa->codetapa; ?>"> <?php echo $tbetapa->Etapa; ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td id='tdprodutoitem'>
                                <select class="input_simples" name="idPlanilhaItens" id="idPlanilhaItens" style="width: 100%;">
                                    <option value="">- Selecione - </option>
                                    <?php foreach($this->item as $tbitem) { ?>
                                    <option value="<?php echo $tbitem->coditens; ?>"> <?php echo $tbitem->Item; ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td style='display:none;' id='tdnovoitem'>
                                <input type="text" name="Descricao" id="Descricao" maxlength="100" class="input_simples"><?php echo isset($this->Descricao) ? $this->Descricao : ''; ?>
                            </td>
                        </tr>
                        <tr class="destacar bold">
                            <td colspan="3">Justificativa <span class="red-text">*</span></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <textarea cols="50" id="justificativa" name="justificativa" rows="6" style="width: 99%;" class="textarea_simples"><?php echo isset($this->Descricao) ? $this->Descricao : ''; ?></textarea>
                            </td>
                        </tr>
                    </table>

                    <table class="tabela">
                        <tr class="centro">
                            <td colspan="4">
                                <div id="divMsg" style="display: none;"><font color="red-text">A justificativa deve ser preenchida!</font></div>
                                <button type="button" class="btn btnsalvar" name="salvar" value="" >salvar</button>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <br clear="all" />

            <div id="msgAlerta" class="sumir"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){

        $('.btnsalvar').click(function(){
            if($('#justificativa').val().length > 250){
                $("#msgAlerta").dialog("destroy");
                $("#msgAlerta").html("O campo Justificativa n&atilde;o pode ultrapassar a quantidade de 250 caracteres!");
                $("#msgAlerta").dialog({
                    resizable: false,
                    title: 'Alerta!',
                    width:320,
                    height:180,
                    modal: true,
                    buttons : {
                        'OK' : function(){
                            $(this).dialog('close');
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
                return false;
            } else {
                $('#form').submit();
            }
        });

        <?php if (!$this->isEditavel) : ?>
        //DESABILITA ALTERACOES NOS DADOS DO FORMULARIO (INCLUIR/ALTERAR/EXCLUIR)
        JSBloquearAlteracaoFormulario();
        <?php endif; ?>

        $("#form").validate({
            rules: {
                produto: { required: true },
                etapa: { required: true },
                justificativa: { required: true }
            },
            messages: {
                produto: { required: "<br>Dados obrigat&oacute;rios n&atilde;o informados" },
                etapa: { required: "<br>Dados obrigat&oacute;rios n&atilde;o informados" },
                justificativa: { required: "Dados obrigat&oacute;rios n&atilde;o informados" }
            },
            submitHandler: function(form) {
                //if(validarJustificativa()){
                form.submit();
                //}
            }
        });

        $("#produtoetapa").change(function(){
            $("#tdprodutoitem").css('display','');
            $("#tdnovoitem").css('display','none');

            $("#idPlanilhaItens").rules("add", {
                required: true,
                messages: {
                    required: "Dados obrigat&oacute;rios n&atilde;o informados"
                }
            });
            $("#Descricao").rules("remove");
        });

        $("#novoitem").change(function(){
            $("#tdprodutoitem").css('display','none');
            $("#tdnovoitem").css('display','');

            $("#Descricao").rules("add", {
                required: true,
                messages: {
                    required: "Dados obrigat&oacute;rios n&atilde;o informados"
                }
            });
            $("#idPlanilhaItens").rules("remove");
        });

        $("#idPlanilhaItens").rules("add", {
            required: true,
            messages: {
                required: "Dados obrigat&oacute;rios n&atilde;o informados"
            }
        });

        jQuery.validator.addMethod("validarJustificativa", function(value, element) {
            var texto = $('#justificativa').val();
            if (texto.length > 0) {
                // verifica se o usuario clicou no botao 'Reintegracao'
                $('#justificativa').val();
                return true;
            } else {
                return false;
            }
        });
    })
</script>
