<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        window.print();
    });
</script>

<style type="text/css" media="all">
    body {
        margin:0;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        color:#000;
        line-height:14pt;
    }
    a:link, a:active, a:visited {
        text-decoration:underline;
    }
    a:hover {
        text-decoration:none;
    }
    .tabela { /* tamanho de tabelas com registros */
        margin:10px auto;
        width:97%;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
        border-spacing: 1px;
        empty-cells: show;
    }
    table td {
        background:#fff;
        padding:4px;
        color:auto;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table tr.destacar td, table td.destacar {
        background:#e2e2e2;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table th {
        background:#cdcdcd;
        padding:4px;
        text-transform:uppercase;
        font-size:11px;
        border: 1px #999 solid;
        color: #000;
    }
    #brasao{
        width : 85px;
        height: 86px;
    }
    legend{
        font-size:13px;
        font-weight: bold;
    }
    .btn_imprimir{
        border-top:1px solid #efefef;
        border-left:1px solid #efefef;
        border-right:1px solid #aaa;
        border-bottom:1px solid #aaa;
        margin:0 5px 0 0;
        width:20px;
        height:21px;
        text-align:center;
        cursor:pointer;
        background:url('<?php echo $this->baseUrl(); ?>/public/img/buttons/imprimir.gif') center center no-repeat;
    }
    .btn_imprimir:hover{
        background-color:#fff;
        border-top:1px solid #aaa;
        border-left:1px solid #aaa;
        border-right:1px solid #efefef;
        border-bottom:1px solid #efefef;
    }
    .paginaA4{
        width:auto;
        margin: 1.111cm 1cm 1cm 1.005cm;
        page-break-after: always;
    }
    .TituloMinC{
        font-size: 14px;
        text-transform: uppercase;
    }
    .TituloDoDocumento{
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }
    .DataDoDocumento{
        font-size: 10px;
    }
    .QntdRegistros{
        font-size: 12px;
    }
</style>

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div class="paginaA4">
    <div align="center">
        <img id="brasao" src="<?php echo $this->baseUrl(); ?>/public/img/brasaoArmas.jpg" alt="Ministério da Cultura"/>
        <br clear="all" /><span class="TituloMinC">Ministério da Cultura</span>
        <br clear="all" /><span class="TituloDoDocumento">Relatório de Propostas - Resultado da pesquisa</span>
        <br clear="all" /><span class="DataDoDocumento">Data da impressão: <?php echo date('d/m/Y - H:i:s'); ?></span>
        <br clear="all" /><br clear="all" /><span class="QntdRegistros"><?php echo count($this->dados).' propostas listadas'; ?></span>
    </div>


    <?php if($this->qtdRegistros > 0){ ?>
    <table class="tabela tablesorter">
        <thead>
            <tr class="titulo_tabela">
                <th>&nbsp;</th>
                <th>N&ordm; Proposta</th>
                <th>Nome da Proposta</th>
                <th>CPF / CNPJ</th>
                <th>Proponente</th>
                <th>Valor</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            <?php $i=1; foreach($this->dados as $d){ ?>
            <tr>
                <td align="center"><?php echo $i; ?></td>
                <td align="center"><?php echo $d->idProjeto; ?></td>
                <td><?php echo $d->NomeProposta; ?></td>
                <td nowrap><?php echo strlen($d->CNPJCPF) == 11 ? Mascara::addMaskCPF($d->CNPJCPF) : Mascara::addMaskCNPJ($d->CNPJCPF); ?></td>
                <td><?php echo $d->Proponente; ?></td>
                <td align="right" nowrap><?php echo @number_format($d->valor, 2, ",", "."); ?></td>
                <td style="width: 150px;">
                    <?php
                        if($d->stEstado == 0){
                            echo 'Proposta arquivada';
                        } else if($d->stEstado == '1' && $d->Movimentacao == '95' && $d->estadoMovimentacao == '0' && $d->ConformidadeOK == '0' && $d->estadoAvaliacao == '0'){
                            echo 'Proposta diligenciada';
                        } else if($d->stEstado == '1' && $d->Movimentacao == '96' && $d->estadoMovimentacao == '0' && $d->ConformidadeOK == '0' && $d->estadoAvaliacao == '0'){
                            echo 'Diligência respondida';
                        } else if($d->stEstado == '1' && $d->Movimentacao == '95' && $d->estadoMovimentacao == '0' && is_null($d->ConformidadeOK) && is_null($d->estadoAvaliacao)){
                            echo 'Proposta em construção';
                        } else if($d->stEstado == '1' && $d->Movimentacao == '96' && $d->estadoMovimentacao == '0' && $d->ConformidadeOK == '9' && $d->estadoAvaliacao == '0'){
                            echo 'Enviada ao MinC p/ avaliação';
                        } else {
                            echo 'Enviada ao MinC p/ avaliação';
                        }
                    ?>
                </td>
            </tr>
            <?php $i++; } ?>
        </tbody>
    </table>

    <?php } else { ?>
    <table class="tabela">
        <tr>
            <td align="center">Nenhum registro encontrado.</td>
        </tr>
    </table>
    <?php } ?>
    <br clear="all" />

</div>