<script>
    $(document).ready(function(){
        $(".btn_pesquisar").click(function(){
            $("#resultadoConsulta").html("");
            jqAjaxForm(document.getElementById("frmDados"), "resultadoConsulta");
        });

        $('#regiao').change(function(){
            var regiao = $(this).val();
            if(regiao != ""){
                $("#uf").find("option").show().each(function(){
                    if($(this).attr("regiao") != regiao && $(this).val() != ""){
                        $(this).hide();
                        $("#uf").val("");
                    }
                });
            }else{
                $("#uf").find("option").show();
                $("#uf").val("");
            }
        });

        $("#uf").change(function(){
            carregar_combo($(this).val(), "cidade", "<?php echo $this->url(array('controller'=>'cidade', 'action'=>'combo')); ?>", "Selecione uma UF", "");
        });

    });
</script>

<?php include("scripts/relatorio/inc/menuPontoCultural.inc.php"); ?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para Página Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => ''), '', true); ?>" title="Ir para Relatorio">Gerar Relatório Análise</a></li>
		<li class="last">Por Região / UF / Cidade</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Por Regi&atilde;o/UF/Cidade<span class="voltar"><a href="javascript:voltar()">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<div id="conteudo">

    <fieldset>
        <legend> Filtros de pesquisa </legend>
        <form action="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'resultado-pc-regiao-uf-cidade')); ?>" method="post" name="frmDados" id="frmDados">
        <table class="tabela">
            <tr>
                <td><b>Regi&atilde;o</b></td>
                <td align="left" colspan="2">
                    <select class="input_simples w200" name="regiao" id="regiao">
                        <option value="">Todas</option>
                            <?php foreach($this->regioes as $regiao):?>
                            <option value="<?php echo $regiao; ?>"><?php echo $regiao; ?></option>
                            <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td><b>Unidade da Federa&ccedil;&atilde;o</b></td>
                <td align="left" colspan="2">
                    <select class="input_simples w200" name="uf" id="uf">
                        <option value="">Todos</option>
                            <?php foreach($this->ufs as $uf):?>
                            <option value="<?php echo $uf->idUF; ?>" regiao="<?php echo $uf->Regiao; ?>"><?php echo $uf->Descricao; ?></option>
                            <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td><b>Cidade</b></td>
                <td align="left" colspan="2">
                    <select class="input_simples w200" name="cidade" id="cidade">
                        <option value="">Selecione uma UF</option>
                    </select>
                </td>
            </tr>
        </table>
        <table class="tabela">
            <tr>
                <td align="center">
                    <input type="button" style="width: 88px" class="btn_pesquisar" id="btn_pesquisar"/>
                    <input type="reset" style="width: 88px" class="btn_limpar" id="btn_limpar" value=""/>
                </td>
            </tr>
        </table>
        </form>
</fieldset>
<div id="resultadoConsulta"></div>
</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->

<br clear="all" />