<script type="text/javascript">
    $(document).ready(function(){
        $('#conteudoXLS').val($('#conteudoImprimivel').html());
        $('#formGerarXls').submit();
    });
</script>
<div class="conteudoImprimivel" id="conteudoImprimivel" style="display:none">
<table class="tabela">
    <tr>
        <th width="7%">Nr Proposta</th>
        <th width="90%">Nome da Proposta</th>
        <th width="5%">Valor</th>
    </tr>
    <?php foreach($this->registros as $registro):?> 
    <tr class="linha">
        <td class="centro"><?php echo $registro['idProjeto']?></td>
        <td><?php echo $registro['NomeProposta']?></td>
        <td class="centro"><?php echo number_format($registro['valor'], 2, ",", ".")?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>
<form method="POST" id="formGerarXls" name="formGerarXls" action="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'gerar-xls')); ?>" style="display:none">
    <textarea name="html" id="conteudoXLS"></textarea>
</form>