export const SET_REGISTROS_TABELA = 'SET_REGISTROS_TABELA';
export const SET_ACTIVE_RECORD = 'SET_ACTIVE_RECORD';
export const UPDATE_REGISTRO_TABELA = 'UPDATE_REGISTRO_TABELA';
export const DELETE_RECORD = 'DELETE_RECORD';
