<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="second">Acompanhamento</li>
        <li class="last">Verificar readequa&ccedil;&atilde;o de projeto</li>
    </ul>
</div>

<div id="titulo">
    <div>READEQUAÇÃO: PRODUTOS E/OU ITENS DE CUSTO
        <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span>
    </div>
</div>

<style type="text/css">
    .pvermelho { color: red; font-weight: bold; }
    .pverde { color: green; font-weight: bold; }
    .pazul { color: blue; font-weight: bold; }
    .ppreto { color: black; font-weight: bold; }
</style>

<script type="text/javascript">
    function mostraOcultaElemento(elemento){
        $('.' + elemento).toggle();
        if ($('#' + elemento).hasClass('btn_adicionar')){
            $('#' + elemento).addClass('btn_remover');
            $('#' + elemento).removeClass('btn_adicionar');
        } else {
            $('#' + elemento).addClass('btn_adicionar');
            $('#' + elemento).removeClass('btn_remover');
        }
    }
</script>

<!-- ========== FIM TÍTULO ========== -->
<div id="conteudo">
    <table class="tabela">
        <thead>
            <tr>
                <th align="center">Nº PRONAC:</th>
                <th align="center">Nome do Projeto:</th>
            </tr>
        </thead>
        <tbody>
            <tr class="linha">
                <td align="center"><?php echo $this->dadosTopo['Pronac']; ?></td>
                <td align="center"><?php echo $this->dadosTopo['NomeProjeto']; ?></td>
            </tr>
        </tbody>
        <tr>
            <th align="center">CNPJ/CPF:</th>
            <th align="center">Proponente:</th>
        </tr>
        <tbody>
            <tr class="linha">
                <td align="center"><?php echo $this->dadosTopo['CNPJCPF']; ?></td>
                <td align="center"><?php echo $this->dadosTopo['NomeProponente']; ?></td>
            </tr>
        </tbody>
    </table>

    <?php if(is_array($this->dados) && count($this->dados)>0):
        $i = 0;
        foreach ($this->dados as $key => $value) {
            ?>
    <table class="tabela">
        <tr>
            <td align="left">
                <input type="button" class="btn_adicionar" style="display: inline;" id="<?php echo $value[$i]->idProduto; ?>" onclick="mostraOcultaElemento('<?php echo $value[$i]->idProduto; ?>');" />
                <b style="font-size: 12px;" class="
                        <?php
                        foreach ($this->produtosTpAcao as $tipo => $valor) {
                            if($tipo == $value[$i]->idProduto) {
                                if ($valor == "A") {
                                    echo "pazul";
                                } elseif ($valor == "I") {
                                    echo "pverde";
                                } elseif ($valor == "E") {
                                    echo "pvermelho";
                                } elseif ($valor == "N") {
                                    echo "ppreto";
                                }
                            }
                        }
                           ?>"><?php echo $key; ?>
                </b>
            </td>
        </tr>
        <tr class="<?php echo $value[$i]->idProduto; ?> sumir" align="left">
            <td>
                <?php foreach ($value as $dados) { ?>
                <table class="tabela">
                    <tr>
                        <td align="left">
                            <input type="button" class="btn_adicionar" style="display: inline;" id="planoNum<?php echo $dados->idPlano;?>" onclick="mostraOcultaElemento('planoNum<?php echo $dados->idPlano;?>');" />
                            <b>
                                <?php
                                    if($dados->tpPlanoDistribuicao == 'AP') {
                                        echo "APROVADO";
                                    } elseif($dados->tpPlanoDistribuicao == 'SR') {
                                        echo "SOLICITAÇÃO DE READEQUAÇÃO";
                                    } elseif($dados->tpPlanoDistribuicao == 'AT') {
                                        echo "ANÁLISE TÉCNICA";
                                    } elseif($dados->tpPlanoDistribuicao == 'CO') {
                                        echo "COMPONENTE DA COMISSÃO";
                                    }
                                ?>
                            </b>
                        </td>
                    </tr>
                    <tr class="planoNum<?php echo $dados->idPlano;?> sumir" align="left">
                        <td>
                            <table class="tabela">
                                <tr>
                                    <td align='center' width="20%" class="destacar"><b>Nome do Evento / Produto</b></td>
                                </tr>
                                <tr>
                                    <td>
                                        <table class='tabela'>
                                            <tr>
                                                <td>
                                                    <b>Produto</b><br>
                                                    <?php echo $dados->Produto;?>
                                                </td>
                                                <td>
                                                    <b>Produto Principal?</b><br>
                                                    <?php if ($dados->PrdotudoPrincpal == 0) {
                                                            echo "Não";
                                                        } else {
                                                            echo "Sim";
                                                        }
                                                    ?>
                                                </td>
                                                <td>
                                                    <b>Área</b><br>
                                                    <?php echo $dados->Area; ?>
                                                </td>
                                                <td>
                                                    <b>Segmento</b><br>
                                                    <?php echo $dados->Segmento; ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td align='center' width="20%" class="destacar"><b>Logomarca</b></td>
                                </tr>
                                <tr>
                                    <td align='center' width="80%"><?php echo $dados->Posicao;?></td>
                                </tr>
                                <tr>
                                    <td align= 'center' style='padding:0;'>
                                        <table class='tabela'>
                                            <tr class="destacar">
                                                <td align="center"><b>Distribui&ccedil;&atilde;o Gratuita (Qtde)</b></td>
                                                <td align="center"><b>Total para Venda (Qtde)</b></td>
                                                <td align="center"><b>Quantidade</b></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <table class='tabela'>
                                                        <tr>
                                                            <td>
                                                                <b>Patrocinador</b><br>
                                                                <?php echo $dados->Patrocinador;?>
                                                            </td>
                                                            <td>
                                                                <b>Divulga&ccedil;&atilde;o</b><br>
                                                                <?php echo $dados->Divulgacao;?>
                                                            </td>
                                                            <td>
                                                                <b>Benefici&aacute;rios</b><br>
                                                                <?php echo $dados->Beneficiarios;?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td>
                                                    <table class='tabela'>
                                                        <tr>
                                                            <td>
                                                                <b>Normal</b><br>
                                                                <?php echo $dados->NormalTV;?>
                                                            </td>
                                                            <td>
                                                                <b>Promocional</b><br>
                                                                <?php echo $dados->PromocionalTV;?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td>
                                                    <table class='tabela'>
                                                        <tr>
                                                            <td>
                                                                <b>N de Exemplares/Ingressos</b><br>
                                                                <?php echo ($dados->Patrocinador + $dados->Divulgacao + $dados->Beneficiarios + $dados->NormalTV + $dados->PromocionalTV);?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr class="destacar">
                                                <td align="center"><b>Pre&ccedil;o Unit&aacute;rio (R$)</b></td>
                                                <td align="center"><b>Receita Prevista (R$)</b></td>
                                                <td align="center"><b>Total Receita Prevista (R$)</b></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <table class='tabela'>
                                                        <tr>
                                                            <td>
                                                                <b>Normal</b><br>
                                                                <?php echo number_format($dados->NormalPU, 2, ',', '.');?>
                                                            </td>
                                                            <td>
                                                                <b>Promocional</b><br>
                                                                <?php echo number_format($dados->PromocionalPU, 2, ',', '.');?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td>
                                                    <table class='tabela'>
                                                        <tr>
                                                            <td>
                                                                <b>Normal</b><br>
                                                                <?php echo number_format(($dados->NormalPU * $dados->NormalTV), 2, ',', '.');?>
                                                            </td>
                                                            <td>
                                                                <b>Promocional</b><br>
                                                                <?php echo number_format(($dados->PromocionalPU * $dados->PromocionalTV), 2, ',', '.');?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td>
                                                    <table class='tabela' >
                                                        <tr>
                                                            <td>
                                                                <b>Total Receita Prevista (R$)</b><br>
                                                                <?php echo number_format(($dados->NormalPU * $dados->NormalTV) + ($dados->PromocionalPU * $dados->PromocionalTV), 2, ',', '.');?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                        </table>
                                    </td>
                                </tr>
                                <?php if(!empty($dados->JustificativaProponente)) { ?>
                                <tr>
                                    <td align='center' width="20%" class="destacar"><b>Justificativa</b></td>
                                </tr>
                                <tr>
                                    <td width="80%"><?php echo $dados->JustificativaProponente;?></td>
                                </tr>
                                <?php } ?>
                            </table>
                        </td>
                    </tr>
                </table>
                <?php } ?>
            </td>
        </tr>
    </table>

    <?php } ?>
    <?php endif; ?>

    <script type="text/javascript">
        $(document).ready(function(){
            $('#planilhaSolicitada').click(function(){
                $('.planilhaSolicitada').removeClass('sumir');
                $('.planilhaAprovada').addClass('sumir');
                $(this).addClass('fundo_linha4');
                $(this).removeClass('fundo_linha2');
                $('#planilhaAprovada').removeClass('fundo_linha4');
                $('#planilhaAprovada').addClass('fundo_linha2');
            });
            $('#planilhaAprovada').click(function(){
                $('.planilhaAprovada').removeClass('sumir');
                $('.planilhaSolicitada').addClass('sumir');
                $(this).removeClass('fundo_linha2');
                $(this).addClass('fundo_linha4');
                $('#planilhaSolicitada').removeClass('fundo_linha4');
                $('#planilhaSolicitada').addClass('fundo_linha2');
            });

            // controle de exibição da planilha aprovada
            $(".icn_menos_AP").click(function(){
                abrir_planilha(this, '');
            });

            $(".icn_menos_AP").click();

            // controle de exibição da planilha solicitada
            $(".icn_menos_SR").click(function(){
                abrir_planilha(this, 'SR');
            });

            $(".icn_menos_SR").click();

            // efeitos ao passar o mouse sobre o item
            $(".item").mouseover(function(){
                $(this).addClass('fundo_linha3');
            });

            $(".item").mouseout(function(){
                $(this).removeClass('fundo_linha3');
            });

            $(".item").click(function(){
                if ($(this).hasClass('fundo_linha4')){
                    $(this).removeClass('fundo_linha4');
                } else {
                    $(this).addClass('fundo_linha4');
                }
            });
        });

        /**
         * Função para expandir/recolher a planilha
         */
        function abrir_planilha(item, planilha){
            var tipo    = $(item).attr('tipo' + planilha);
            var aberto  = $(item).attr('aberto' + planilha);
            var fonte   = 'fonte' + planilha;
            var produto = 'produto' + planilha;
            var etapa   = 'etapa' + planilha;
            var cidade  = 'cidade' + planilha;

            if (aberto == 'true'){
                adisplay = 'none';
                $(item).attr('aberto' + planilha, 'false');
                $(item).removeClass('icn_menos').addClass('icn_mais');
            } else {
                adisplay = '';
                $(item).attr('aberto' + planilha, 'true');
                $(item).removeClass('icn_mais').addClass('icn_menos');
            }

            if (tipo == fonte){
                fonte = $(item).attr('fonte' + planilha);
                $(".master" + planilha + "[fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
                $(".clickproduto" + planilha + ", .clicketapa" + planilha + ", .clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
            }
            if (tipo == produto){
                fonte   = $(item).attr('fonte' + planilha);
                produto = $(item).attr('produto' + planilha);
                $(".produto" + planilha + "[produto" + planilha + "='" + produto + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
                $(".clicketapa" + planilha + ", .clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
            }
            if (tipo == etapa){
                fonte   = $(item).attr('fonte' + planilha);
                produto = $(item).attr('produto' + planilha);
                etapa   = $(item).attr('etapa' + planilha);
                $(".etapa" + planilha + "[produto" + planilha + "='" + produto + "'][etapa" + planilha + "='" + etapa + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
                $(".clickcidade" + planilha).removeClass('icn_mais').addClass('icn_menos');
            }
            if (tipo == cidade){
                fonte   = $(item).attr('fonte' + planilha);
                produto = $(item).attr('produto' + planilha);
                etapa   = $(item).attr('etapa' + planilha);
                cidade  = $(item).attr('cidade' + planilha);
                $(".cidade" + planilha + "[produto" + planilha + "='" + produto + "'][etapa" + planilha + "='" + etapa + "'][cidade" + planilha + "='" + cidade + "'][fonte" + planilha + "='" + fonte + "']").css('display', adisplay);
            }
        } // fecha função abrir_planilha()
    </script>

    <?php
        if(count($this->planSR)>0){
    ?>

    <?php
        $resultado = $this->buscaprojeto;
        $idPronac = $this->escape($resultado[0]->IdPRONAC);
    ?>
    <table class="tabela">
        <tr>
            <th class="fundo_linha2" id="planilhaAprovada" style="cursor: pointer;"><a>Planilha Aprovada</a></th>
            <th class="fundo_linha4" id="planilhaSolicitada" style="cursor: pointer;"><a>Planilha Readequada</a></th>
        </tr>
    </table>

    <table class="tabela sumir planilhaAprovada">
        <tr>
            <th>Planilha Orçamentária Aprovada</th>
        </tr>

        <?php if (count($this->planAP) <= 0) { ?>
        <tr>
            <td align="center">N&atilde;o existe(m) item(ns) aprovado(s) para esse produto.</td>
        </tr>
            <?php } ?>

        <?php $nrFonte = 0;
$item = 1;
foreach ($this->planAP as $fonte => $planilha) : //ForeachFonteIncentivo ?>
        <tr>
            <td>
                <div tipo="fonte" fonte="<?php echo $nrFonte; ?>" aberto="true" class="icn_menos icn_menos_AP" style="width:90%"><span class="red" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
            </td>
        </tr>
            <?php $nrProduto = 0;
            $totalProduto = 0;
    if (is_array($this->planAP[$fonte]))
        foreach ($this->planAP[$fonte] as $produto => $planilha) : //ForeachProduto
            ?>
        <tr class="master" fonte="<?php echo $nrFonte; ?>">
            <td class="master">
                <div tipo="produto" aberto="true" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" class="icn_menos icn_menos_AP clickproduto" style="width:98%; margin-left:2%;"><span class="green" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
            </td>
        </tr>
                    <?php $nrEtapa = 0;
                    if (is_array($this->planAP[$fonte][$produto]))
                foreach ($this->planAP[$fonte][$produto] as $etapa => $planilha) : //ForeachEtapa
                    $totalEtapa = 0;
                    ?>
        <tr class="master produto" produto="<?php echo $nrProduto; ?>" fonte="<?php echo $nrFonte;?>">
            <td>
                <div>
                    <div tipo="etapa" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" aberto="true" class="icn_menos icn_menos_AP clicketapa" style="width:80%; margin-left:4%; "><span class="orange" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div>
                </div>
            </td>
        </tr>
                    <?php $nrCidade = 0;
                    if (is_array($this->planAP[$fonte][$produto][$etapa]))
                        foreach ($this->planAP[$fonte][$produto][$etapa] as $cidade => $planilha) : //ForeachCidade ?>
        <tr class="master produto etapa" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" fonte="<?php echo $nrFonte; ?>">
            <td>
                <div tipo="cidade" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>" aberto="true" class="icn_menos icn_menos_AP clickcidade" style="width:94%; margin-left:6%;"><span class="black" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
            </td>
        </tr>
        <tr class="master produto etapa cidade" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>"  fonte="<?php echo $nrFonte; ?>">
            <td>
                <table class="tabela">
                    <tr class="master produto etapa cidade" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>" fonte="<?php echo $nrFonte;?>">
                        <th>Item</th>
                        <th>Dias</th>
                        <th>Unidade</th>
                        <th>Qtde.</th>
                        <th>Ocor.</th>
                        <th>Vl. Unit&aacute;rio</th>
                        <th>Vl. Solicitado</th>
                        <th>Justificativa</th>
                    </tr>
                    <?php $totalUF = 0;
                    if (is_array($this->planAP[$fonte][$produto][$etapa][$cidade]))
                        foreach ($this->planAP[$fonte][$produto][$etapa][$cidade] as $planilha){ //ForeachItem
                            $totalUF += $planilha['vlTotal'];
                    ?>
                    <tr class="item">
                        <td><?php echo $planilha['Item']; ?></td>
                        <td><?php echo $planilha['qtDias']; ?></td>
                        <td><?php echo $planilha['Unidade']; ?></td>
                        <td><?php echo $planilha['qtItem']; ?></td>
                        <td><?php echo $planilha['nrOcorrencia']; ?></td>
                        <td><?php echo $this->formatarReal($planilha['vlUnitario']); ?></td>
                        <td><?php echo $this->formatarReal($planilha['vlTotal']); ?></td>
                        <td><?php echo $planilha['dsJustificativa']; ?></td>
                    </tr>
                    <?php $item++; } //fechaForeachplanilha
                        $nrCidade++;
                        $totalEtapa   += $totalUF;
                        $totalProduto += $totalUF;
                    ?>
                    <tr>
                        <td colspan="5" class="black" style="font-size: 14pt;">Total de UF</td>
                        <td class="black" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalUF); ?></td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="orange" style="font-size: 14pt;">Total da Etapa</td>
                        <td class="orange" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalEtapa); ?></td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="green" style="font-size: 14pt;">Valor para <?php echo $produto; ?></td>
                        <td class="green" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalProduto); ?></td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
                        <?php
                        endforeach; //fechaForeachcidade
                    $nrEtapa++;
                endforeach; //fechaForeachetapa
            $totalProduto = 0;
            $nrProduto++;
        endforeach; //fechaForeachproduto
    $nrFonte++;
endforeach; //fechaForeachFonteIncentivo
?>
    </table>

    <table class="tabela planilhaSolicitada">
        <tr>
            <th>Planilha Orçamentária Readequada</th>
        </tr>

<?php $nrFonte = 0;
$item = 1;
foreach ($this->planSR as $fonte => $planilha) : //ForeachFonteIncentivo ?>
        <tr>
            <td>
                <div tipo="fonte" fonte="<?php echo $nrFonte; ?>" aberto="true" class="icn_menos icn_menos_AP" style="width:90%"><span class="red" style="font-size: 20pt; font-weight: 800;"><?php echo $fonte; ?></span></div>
            </td>
        </tr>
    <?php $nrProduto = 0;
    $totalProduto = 0;
    if (is_array($this->planSR[$fonte]))
        foreach ($this->planSR[$fonte] as $produto => $planilha) : //ForeachProduto
                    ?>
        <tr class="master" fonte="<?php echo $nrFonte; ?>">
            <td class="master">
                <div tipo="produto" aberto="true" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" class="icn_menos icn_menos_AP clickproduto" style="width:98%; margin-left:2%;"><span class="green" style="font-size: 16pt; font-weight: 800;"><?php echo $produto; ?></span></div>
            </td>
        </tr>
            <?php $nrEtapa = 0;
            if (is_array($this->planSR[$fonte][$produto]))
                foreach ($this->planSR[$fonte][$produto] as $etapa => $planilha) : //ForeachEtapa
                    $totalEtapa = 0;
                    ?>
        <tr class="master produto" produto="<?php echo $nrProduto; ?>" fonte="<?php echo $nrFonte;?>">
            <td>
                <div>
                    <div tipo="etapa" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" aberto="true" class="icn_menos icn_menos_AP clicketapa" style="width:80%; margin-left:4%; "><span class="orange" style="font-size: 14pt; font-weight: 800;"><?php echo $etapa; ?></span></div>
                </div>
            </td>
        </tr>
                    <?php $nrCidade = 0;
                    if (is_array($this->planSR[$fonte][$produto][$etapa]))
                        foreach ($this->planSR[$fonte][$produto][$etapa] as $cidade => $planilha) : //ForeachCidade ?>
        <tr class="master produto etapa" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" fonte="<?php echo $nrFonte; ?>">
            <td>
                <div tipo="cidade" fonte="<?php echo $nrFonte; ?>" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>" aberto="true" class="icn_menos icn_menos_AP clickcidade" style="width:94%; margin-left:6%;"><span class="black" style="font-size: 12pt; font-weight: 800;"><?php echo $cidade; ?></span></div>
            </td>
        </tr>
        <tr class="master produto etapa cidade" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>"  fonte="<?php echo $nrFonte; ?>">
            <td>
                <table class="tabela">
                    <tr class="master produto etapa cidade" produto="<?php echo $nrProduto; ?>" etapa="<?php echo $nrEtapa; ?>" cidade="<?php echo $nrCidade; ?>" fonte="<?php echo $nrFonte;?>">
                        <th>Item</th>
                        <th>Dias</th>
                        <th>Unidade</th>
                        <th>Qtde.</th>
                        <th>Ocor.</th>
                        <th>Vl. Unit&aacute;rio</th>
                        <th>Vl. Solicitado</th>
                        <th>Justificativa</th>
                        <th>Ação</th>
                    </tr>
                                                <?php $totalUF = 0;
                                                if (is_array($this->planSR[$fonte][$produto][$etapa][$cidade]))
                                                    foreach ($this->planSR[$fonte][$produto][$etapa][$cidade] as $planilha) : //ForeachItem
                                                        $totalUF += $planilha['vlTotal'];
                                                        ?>
                                                        <?php
                                                        switch ($planilha['tpAcao']) {
                                                            case 'I':
                                                                $corLinha = 'style="color: blue; font-weight: bold;"';
                                                                break;
                                                            case 'E':
                                                                $corLinha =  'style="color: red; font-weight: bold;"';
                                                                break;
                                                            case 'A':
                                            $corLinha =  'style="color: green; font-weight: bold;"';
                                            break;
                                        default:
                                            $corLinha =  '';
                                            break;
                                    }; ?>
                    <tr class="item" <?php echo $corLinha; ?>>
                        <td><?php echo $planilha['Item']; ?></td>
                        <td><?php echo $planilha['qtDias']; ?></td>
                        <td><?php echo $planilha['Unidade']; ?></td>
                        <td><?php echo $planilha['qtItem']; ?></td>
                        <td><?php echo $planilha['nrOcorrencia']; ?></td>
                        <td><?php echo $this->formatarReal($planilha['vlUnitario']); ?></td>
                        <td><?php echo $this->formatarReal($planilha['vlTotal']); ?></td>
                        <td><?php echo $planilha['dsJustificativa']; ?></td>
                        <td>
                                                                <?php
                                                                switch ($planilha['tpAcao']) {
                                                                    case 'I':
                                                                        echo 'INCLUIR';
                                                                        break;
                                                                    case 'E':
                                                                        echo 'EXCLUIR';
                                                                        break;
                                                                    case 'A':
                                            echo 'ALTERAR';
                                            break;
                                                            default:
                                                                echo '';
                                                                break;
                                                        }; ?>
                        </td>
                    </tr>
                                    <?php $item++;
                                endforeach; //fechaForeachplanilha
                            $nrCidade++;
                            $totalEtapa   += $totalUF;
                            $totalProduto += $totalUF;
                            ?>
                    <tr>
                        <td colspan="5" class="black" style="font-size: 14pt;">Total de UF</td>
                        <td class="black" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalUF); ?></td>
                        <td colspan="3">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="orange" style="font-size: 14pt;">Total da Etapa</td>
                        <td class="orange" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalEtapa); ?></td>
                        <td colspan="3">&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="green" style="font-size: 14pt;">Valor para <?php echo $produto; ?></td>
                        <td class="green" style="font-size: 12pt; font-weight: 600;"><?php echo $this->formatarReal($totalProduto); ?></td>
                        <td colspan="3">&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
                                <?php
                                endforeach; //fechaForeachcidade
                            $nrEtapa++;
                        endforeach; //fechaForeachetapa
            $totalProduto = 0;
            $nrProduto++;
        endforeach; //fechaForeachproduto
    $nrFonte++;
endforeach; //fechaForeachFonteIncentivo
?>
    </table>

<?php } ?>

    <script type="text/javascript">
        $('.trpai').click(function(){
            filhos(this);
        });

        function filhos(pai){
            var idtr = '.'+$(pai).attr('idFilho');
            $(idtr).toggle();
            if ($(pai).hasClass('icn_mais')){
                $(pai).addClass('icn_menos');
                $(pai).removeClass('icn_mais');
            } else {
                $(pai).addClass('icn_mais');
                $(pai).removeClass('icn_menos');
            }

            if ($(idtr).attr('idFilho')!= undefined){
                filhos($(idtr).attr('idFilho'));
            }
        }

        function abrirFecharFilhos(){
            $('.trFilho, .idFilhoTitulo').toggle();
            $('.trpai').each(function(){
                if ($(this).hasClass('icn_mais')){
                    $(this).addClass('icn_menos');
                    $(this).removeClass('icn_mais');
                    $('#abrir_fechar').addClass('icn_menos');
                    $('#abrir_fechar').removeClass('icn_mais');
                } else {
                    $(this).addClass('icn_mais');
                    $(this).removeClass('icn_menos');
                    $('#abrir_fechar').addClass('icn_mais');
                    $('#abrir_fechar').removeClass('icn_menos');
                }
            });
        }
    </script>

</div>
<!-- ========== INÍCIO RODAPÉ DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPÉ DO CONTEÚDO ========== -->
<br clear="all" />