<script type="text/x-template" id="visualizar">
    <div>
        <button class="btn" v-on:click="modal()">
            {{pronac}}
        </button>
    </div>
</script>

<script type="text/x-template" id="dados">
    <div>
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">COMPROVAÇÃO CONSOLIDADA POR PRODUTO</div>
              <div class="collapsible-body">
                <table class="bordered">
                    <thead>
                        <th>Produto</th>
                        <th>Qtd. Comprovantes</th>
                        <th>Valor Comprovado</th>
                        <th>% Comprovado</th>
                    </thead>
                    <tbody>
                        <tr v-for="dado in dados['comprovacao']">
                            <td>
                                {{dado.dsProduto}}
                            </td>
                            <td>
                                {{dado.qtComprovantes}}
                            </td>
                            <td>
                                {{dado.vlComprovado}}
                            </td>
                            <td>
                                {{dado.PercComprovado}}
                            </td>
                        </tr>
                    </tbody>
                </table>
              </div>
            </li>
            <li>
              <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
              <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
            </li>
            <li>
              <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
              <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
            </li>
          </ul>
    </div>
</script>

<script type="text/javascript">
    Vue.component('visualizar', {
        template: '#visualizar',
        data: function() {
            return {
                dados:[]
            }
        },
        props: ['idpronac', 'pronac'],
        mounted: function() {
            this.dados = [{ nome: 'teste' }, { nome: 'teste1' }]
        },
        methods: {
            modal: function() {
                bus.$emit('id-selected', this.idpronac)
                $3('#abrirModal').modal();
                $3('#abrirModal').modal('open');
            }
        }
    });

    Vue.component('dados', {
        template: '#dados',
        data: function() {
            return {
                dados:[]
            }
        },
        created: function() {
            vue = this;
            bus.$on('id-selected', function (id) {
                vue.idpronac = id;
                vue.alerta();
            });
        },
        props: ['idpronac'],
        mounted: function() {
            /* vue = this; */
            /* $3.ajax({ */
            /*     url: '/prestacao-contas/visualizar-projeto/dados-projeto?idPronac=' + vue.idpronac */
            /* }) */
            /* .done( function(data) { */
            /*     vue.dados = data; */
            /* }); */
        },
        methods: {
            alerta: function() {
                vue = this;
                $3.ajax({
                    url: '/prestacao-contas/visualizar-projeto/dados-projeto?idPronac=' + vue.idpronac
                })
                .done( function(data) {
                    console.info(data);
                    vue.dados = data; 
                });
            }
        }
    });

    var bus = new Vue({});
    var app = new Vue({
        el: '#container'
    });
</script>
<style>
  #abrirModal.modal{
       height: 90%;
       max-height: 96%;
       width: 98%;
    }
</style>
<!-- Modal Structure -->
